### PR TITLE
Zify: more aggressive application of saturation rules 

### LINKED ISSUE #11656: nia regression
```coq
Require Import Lia.
Require Import NArith.
Open Scope N_scope.

Goal forall (a b c: N),
    a <> 0 ->
    c <> 0 ->
    a * ((b + 1) * c) <> 0.
Proof.
  intros. nia.
Qed.
```

Works in 8.9.0 and 8.10.2, but fails in 8.11.0.

### PR DESCRIPTION
**Pull request by fajb**
`zify` saturates the context with positivity constraints.
The existing code was simply looking for positivity hypotheses in the context.

This PR is more aggressive and always instantiate the saturation lemma.
(It is now careful to not duplicate hypotheses)

This PR also removes the saturation lemma for multiplication that would otherwise clutter the context. 
The reasoning is now performed by `lia`/`nia`.

This is a prerequisite for PR #14037 

- [x] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).
- [x] Overlay pull requests (if this breaks 3rd party developments in CI, see
https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md for details)

### CODE REVIEW

**Comment by mrhaandi** [comment]
I'm trying to get it to work with PR https://github.com/coq/coq/pull/14037.
Is there a reason for this to be a few dozen commits behind `coq:master`?

**Comment by mrhaandi** [comment]
Upon combination with https://github.com/coq/coq/pull/14037 (but not each PR individually) there is a performance regression (and a stack overflow on `Qed`) in `test-suite/success/Nia.v` (e.g. in `mod_mod_same`).

**Comment by fajb** [comment]
> Upon combination with #14037 (but not each PR individually) there is a performance regression (and a stack overflow on `Qed`) in `test-suite/success/Nia.v` (e.g. in `mod_mod_same`).

I do not get why the problem occurs at Qed but what is sure is that both PR augments the context with more hypotheses.
Eventually, this blows up... Here, it is unfortunate because  the saturation rules for `mod` and `div` are subsumed by 
`Z.to_euclidean_division_equations`.

I see the following options:
1 - do not add saturation rules for `mod` and `div` and always set `Z.to_euclidean_division_equations`.
    (This used to be inefficient but it seems ok now ping @samuelgruetter )
2 - make `Z.to_euclidean_division_equations` aware of the saturation rules (clear them?)

Actually, I think both options would be viable without this PR!

**Comment by samuelgruetter** [comment]
If I remember correctly, calling `Z.to_euclidean_division_equations` too often can cause performance problems in 8.13, but not any more on master, in what I tried.

**Comment by fajb** [comment]
> Upon combination with #14037 (but not each PR individually) there is a performance regression (and a stack overflow on `Qed`) in `test-suite/success/Nia.v` (e.g. in `mod_mod_same`).

@mrhaandi the regression should be fixed.

**Comment by fajb** [comment]
bench at https://gitlab.com/coq/coq/-/jobs/1153426040

**Comment by mrhaandi** [comment]
> > Upon combination with #14037 (but not each PR individually) there is a performance regression (and a stack overflow on `Qed`) in `test-suite/success/Nia.v` (e.g. in `mod_mod_same`).
> 
> @mrhaandi the regression should be fixed.

@fajb Are you entirely sure? I rebased this on #14037 and still got the regression and a stack overflow on `Qed.` in `mod_mod_same`.
On `test-suite` I still get `success/Nia.v...Error! (should be accepted)`. Did I misconfigure something? Your latest `overlay` commit is in.

**Comment by fajb** [comment]
@mrhaandi you are right. Sorry.
The test-suite needs to be modified.
In Nia.v
`Ltac Zify.zify_post_hook ::= Z.to_euclidean_division_equations.` needs to be replaced by
`Ltac zify_convert_to_euclidean_division_equations_flag ::= constr:(true).`

**Comment by mrhaandi** [comment]
> @mrhaandi you are right. Sorry.
> The test-suite needs to be modified.
> In Nia.v
> `Ltac Zify.zify_post_hook ::= Z.to_euclidean_division_equations.` needs to be replaced by
> `Ltac zify_convert_to_euclidean_division_equations_flag ::= constr:(true).`

Yes, with the new flag there are no regressions and the combination of the two PRs works fine.
Is there a reason not to have it on by default?

**Comment by fajb** [comment]
> Is there a reason not to have it on by default?

Scalability problems. Though, this may be ok now.

**Comment by fajb** [comment]
```┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  152.83   153.13  -0.20 │   424938739045    424893312310   0.01 │   597943773256    597922266370   0.00 │  747824   745384   0.33 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  223.54   223.90  -0.16 │   621507690151    622972950567  -0.24 │   949784746313    949947261658  -0.02 │  662320   664480  -0.33 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   48.04    48.09  -0.10 │   133344408439    133241381266   0.08 │   186284479145    186316476567  -0.02 │  488592   488540   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  138.84   138.96  -0.09 │   385781727711    386170486799  -0.10 │   502734691011    502764276667  -0.01 │  556192   555884   0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1057.92  1058.45  -0.05 │  2944192764914   2943438743312   0.03 │  4685464725136   4685138595429   0.01 │  911176   909584   0.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2519.21  2520.12  -0.04 │  7019306538416   7021778262050  -0.04 │ 12243408723013  12242414814202   0.01 │  767308   737728   4.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  759.64   759.56   0.01 │  2112298362627   2114709722424  -0.11 │  3278782157263   3278896847651  -0.00 │ 1106532  1108372  -0.17 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │  146.30   146.28   0.01 │   403780714203    403706638929   0.02 │   499201787355    498920317596   0.06 │  825408   827968  -0.31 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-unimath │ 3958.91  3958.36   0.01 │ 11013612268096  11006815335502   0.06 │ 21203973999077  21194491595416   0.04 │ 1117140  1118056  -0.08 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-rewriter │  693.22   693.12   0.01 │  1926849320344   1925272688016   0.08 │  2920277558085   2916155174958   0.14 │ 1106588  1106652  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  622.97   622.56   0.07 │  1737716872196   1736537356026   0.07 │  2645746392334   2644747200971   0.04 │ 3688868  3688912  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1174.49  1173.55   0.08 │  3263526407989   3259416126554   0.13 │  4609117526076   4609151908457  -0.00 │  900260   899716   0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  171.13   170.94   0.11 │   475122040567    475019967878   0.02 │   676469048670    676458161836   0.00 │  688876   675900   1.92 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  329.16   328.74   0.13 │   925248526853    924251301671   0.11 │  1688427786032   1687266368529   0.07 │ 3546564  3546568  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1255.61  1253.92   0.13 │  3490538383883   3486755120502   0.11 │  5021117529413   5019132783202   0.04 │ 1090436  1095592  -0.47 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │ 1557.48  1554.51   0.19 │  4335606254112   4331570164781   0.09 │  7198781842910   7198954067682  -0.00 │ 1695736  1696080  -0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1373.78  1371.07   0.20 │  3820036986211   3812924435929   0.19 │  5626469384861   5625159694983   0.02 │  998600   996596   0.20 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-stdlib │  387.96   387.04   0.24 │  1077786965141   1075467746013   0.22 │  1399782429138   1396606080397   0.23 │  573104   573748  -0.11 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-perennial │ 5247.64  5231.95   0.30 │ 14597390138489  14572617228791   0.17 │ 22012349128078  21997349361839   0.07 │ 3110352  3095748   0.47 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-core │  107.88   107.46   0.39 │   301623379473    300984783908   0.21 │   455317328093    455310424730   0.00 │  263648   263704  -0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-verdi │   98.18    97.49   0.71 │   270230821776    269385705043   0.31 │   380813943498    379097399871   0.45 │  551380   549900   0.27 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   53.00    52.60   0.76 │   145120342744    144750596120   0.26 │   185219165919    184679293635   0.29 │  527704   527548   0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-bedrock2 │  201.18   199.58   0.80 │   556457743311    553316480562   0.57 │   916713485411    911664823292   0.55 │  777624   777944  -0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-coquelicot │   68.33    67.64   1.02 │   185967825971    184616393237   0.73 │   235212874832    233507082007   0.73 │  557788   557828  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │  106.15   104.54   1.54 │   301360837864    299624626275   0.58 │   409187255912    406487574223   0.66 │  484384   483532   0.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                         coq │    4.13     4.05   1.98 │    11146740378     11201713903  -0.49 │    22090241727     22094220722  -0.02 │  263616   263700  -0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-coqutil │   54.40    52.93   2.78 │   150748186878    146988174008   2.56 │   197642272098    191120436932   3.41 │  530472   522312   1.56 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘```

**Comment by mrhaandi** [comment]
For `Instance SatPowPos : Saturate Z.pow` why is the saturation condition `PArg2 := fun y => 0 < y` and not `... 0 <= y`? The lemma `Z.pow_pos_nonneg` would allow for the latter.

**Comment by fajb** [comment]
This used to be a syntactic check. So if the original type was nat, you would get a condition `0 <= x` and if it were positive `0 < x`.
Now, it may be possible to be otherwise...

**Comment by fajb** [comment]
The bench looks mostly ok. I cannot reproduce the slowdown with `coqutil` on my local machine.

**Comment by fajb** [comment]
@mrhaandi regarding `SatPow` do you have a lemma that is stronger in all cases?
If so, with the new implementation, that would make sense.

**Comment by mrhaandi** [comment]
> @mrhaandi regarding `SatPow` do you have a lemma that is stronger in all cases?
> If so, with the new implementation, that would make sense.

I was thinking just about 
```
Instance SatPowPos : Saturate Z.pow :=
  {|
    PArg1 := fun x => 0 < x;
    PArg2 := fun y => 0 <= y;
    PRes  := fun r => 0 < r;
    SatOk := Z.pow_pos_nonneg
  |}.
Add Zify Saturate SatPowPos.
```

Orthogonally (not strictly stronger or weaker), we could have
```
Instance SatPowNonneg : Saturate Z.pow :=
  {|
    PArg1 := fun x => 0 <= x;
    PArg2 := fun y => True;
    PRes  := fun r => 0 <= r;
    SatOk := fun a b Ha _ => @Z.pow_nonneg a b Ha
  |}.
Add Zify Saturate SatPowNonneg.
```

**Comment by mrhaandi** [comment]
Nice work, finally we can have (which should be put into the test-suite)
```
Open Scope Z_scope.

Goal forall (x y: Z), 0 < (1+y^2)^(x^2).
Proof. nia. Qed.

Goal forall (x y: Z), 0 <= (y^2)^x.
Proof. nia. Qed.
```
It currently does not work for `nat` and `N` due to missing zify instances, but this could/should be done as part of https://github.com/coq/coq/pull/14037 .

**Comment by mrhaandi** [comment]
@fajb it appears that this PR solves https://github.com/coq/coq/issues/12184.
If so, please add to `Fixes` and maybe add a test case.

**Comment by mrhaandi** [comment]
@fajb also https://github.com/coq/coq/issues/11656 may already be solved by this PR; please check.

**Comment by fajb** [comment]
@vbgl I think this is ready for review. The failure are spurious.
The bench is a bit disappointing for `coqutil` w.r.t master -- but seems ok w.r.t 8.13.2.

File: plugins/micromega/zify.ml [hunk 1]
```diff
@@ -1596,8 +1607,10 @@ let saturate =
           Array.iter sat args;
           if Array.length args = 2 then
             let ds = get_all_sat env evd c in
-            if ds = [] then ()
-            else List.iter (fun x -> CstrTable.HConstr.add table t x.deriv) ds
+            if ds = [] ||  CstrTable.HConstr.mem table t
```
Comment (vbgl) [inline plugins/micromega/zify.ml:1610]: Why is the check `mem table t` done after computing `ds`?

Comment (fajb) [reply plugins/micromega/zify.ml:1610]: Both check are sufficient conditions for doing nothing. Both tables are expected to be very small.
The `get_all_sat` is indexed by `GlobRef.t` whereas `CstrTable.HConstr.mem` may work with bigger terms.
I also expect `ds` to be [] most of the time. 
PS: I did not benchmark

**Review by vbgl — APPROVED** [review]

**Comment by fajb** [comment]
@vbgl thanks again. There will be a last PR and then this should be calmer for quite some time (I hope).

File: theories/micromega/ZifyInst.v [hunk 2]
```diff
@@ -480,39 +480,20 @@ Add Zify UnOpSpec ZabsSpec.
...
     PArg1 := fun x => 0 < x;
-    PArg2 := fun y => 0 < y;
+    PArg2 := fun y => 0 <= y;
     PRes  := fun r => 0 < r;
-    SatOk := Z.mul_pos_pos
+    SatOk := Z.pow_pos_nonneg
   |}.
-Add Zify Saturate SatProdPos.
-
-Lemma pow_pos_strict :
```
Comment (RalfJung) [inline theories/micromega/ZifyInst.v:501]: FWIW, removing this is a breaking change. It took me quite a bit of searching to find the (likely) intended replacement, `Z.pow_pos_nonneg`. Would be good to have a changelog entry for this (that's where I started my search...).

Comment (fajb) [reply theories/micromega/ZifyInst.v:501]: @RalfJung What do you mean exactly by breaking change? Solve more goals? Or regression?

Comment (RalfJung) [reply theories/micromega/ZifyInst.v:501]: A regression: proofs that used this lemma now fail since the lemma does not exist any more.
```
The reference ZifyInst.pow_pos_strict was not found
```

Comment (fajb) [reply theories/micromega/ZifyInst.v:501]: Sorry to hear that. In the future, we will be careful not to export those lemma to the user. 
If useful, their right place is in the standard library with the power function.

Comment (RalfJung) [reply theories/micromega/ZifyInst.v:501]: FWIW, the way I found this lemma in `SearchAbout` -- maybe we could have a way to not show internal lemmas there.

Comment (fajb) [reply theories/micromega/ZifyInst.v:501]: Yes. I guess `Add Search Blacklist ...` would fit the bill.
