### PR TITLE
Fix Canonical with universe polymorphism and primitive projection

### LINKED ISSUE #12528: "Canonical" failing due to primitive projection with universe polymorphism.
#### Description of the problem

    Set Primitive Projections.
    Set Universe Polymorphism.
    Record ptd := Ptd { t : Type ; p : t }.
    Definition type := Ptd Type (unit:Type).
    Definition type' := Ptd Type (p type).
    Fail Canonical type'.
    (* The command has indeed failed with message:
    Undeclared universe: Var(2) (maybe a bugged tactic). *)

On the other hand `Canonical type` succeeds. The presence of the primitive projection `p` in the definition of `type'` seems to trigger the issue. `Canonical type'` also succeeds if either of the flags `Primitive Projections` or `Universe Polymorphism` is unset.

#### Coq Version
8.11.2

### PR DESCRIPTION
**Pull request by SkySkimmer**
Perhaps we should thread an evar map with the Var universes added
through to cs_pattern_of_constr but that would be significantly more invasive.

Fix #12528

### CODE REVIEW

File: pretyping/recordops.ml [hunk 1]
```diff
@@ -185,7 +185,8 @@ let rec cs_pattern_of_constr env t =
   | Rel n -> Default_cs, Some n, []
   | Prod (_,a,b) when Vars.noccurn 1 b -> Prod_cs, None, [a; Vars.lift (-1) b]
   | Proj (p, c) ->
-    let { Environ.uj_type = ty } = Typeops.infer env c in
+    let ty = Retyping.get_type_of env (Evd.from_env env) (EConstr.of_constr c) in
+    let ty = EConstr.Unsafe.to_constr ty in
```
Comment (gares) [inline pretyping/recordops.ml:189]: I would be more keen in adding to Retyping an API like `get_type_of_constr env c` hiding the detour to econstr

Comment (SkySkimmer) [reply pretyping/recordops.ml]: Done.

**Comment by gares** [comment]
Ci shows many unrelated failures, but this also prevents proper testing. I could not find a "not merged yet" PR on elpi for example, so I'm a bit puzzled.

**Comment by SkySkimmer** [comment]
That's just because the CI run was between UIP being merged and its overlays being merged.
I rebased so we'll get a fresh one.

**Review by ejgallego — APPROVED** [review]
This looks OK, could you add your comment w.r.t. threading the evar_map to the code? I'm not sure we should promote the use of `get_type_of_constr`.

I let @gares take this but if he's busy feel free to assign me.

**Comment by SkySkimmer** [comment]
>This looks OK, could you add your comment w.r.t. threading the evar_map to the code? I'm not sure we should promote the use of get_type_of_constr.

get_type_of_constr is fine, the issue is rather at the canonical code which works on terms with poly universes without adding them to some evar map.

**Comment by ejgallego** [comment]
> get_type_of_constr is fine

Excuse my ignorance on the API, indeed it is supposed not to modify the `evar_map` so we can consider it safe.
