### PR TITLE
Fix #9652: rewrite fails to detect lack of progress

### LINKED ISSUE #9652: rewrite silently generates subgoal identical to original subgoal
#### Description of the problem

https://travis-ci.com/mit-plv/bedrock2/jobs/180373423#L1404
https://github.com/mit-plv/bedrock2/blob/24bd4f56b8fc3403d551422250816a79d2b6511f/bedrock2/src/Examples/bsearch.v#L151

In 8.9, [this line](https://github.com/mit-plv/bedrock2/blob/24bd4f56b8fc3403d551422250816a79d2b6511f/bedrock2/src/Examples/bsearch.v#L149) works on both occurrances of `word.unsigned` in the goal. On master, it works on the first occurrance, then "works" on the first occurrance again by doing a rewrite that does not change the goal (which would fail with "generated subgoal identical to original goal") in 8.9 and thus the repeat exits, without ever considering the second occurrance of word.unsigned.

#### Coq Version

8.9 good, current master bad

### PR DESCRIPTION
**Pull request by SkySkimmer**
cc @andres-erbsen 

Bug was uncovered by the removal of the nf_enter in `Equality.tclNOTSAMEGOAL`

### CODE REVIEW

File: proofs/goal.ml [hunk 1]
```diff
@@ -92,8 +92,8 @@ module V82 = struct
   let same_goal evars1 gl1 evars2 gl2 =
     let evi1 = Evd.find evars1 gl1 in
     let evi2 = Evd.find evars2 gl2 in
-    let c1 = EConstr.Unsafe.to_constr evi1.Evd.evar_concl in
-    let c2 = EConstr.Unsafe.to_constr evi2.Evd.evar_concl in
+    let c1 = EConstr.to_constr ~abort_on_undefined_evars:false evars1 evi1.Evd.evar_concl in
```
Comment (ppedrot) [inline proofs/goal.ml]: It really seems like we're going to backtrack on 9f723f14e5342c1303646b5ea7bb5c0012a090ef or what!?

Comment (ejgallego) [reply proofs/goal.ml]: Indeed why not to use the native `EConstr` equality [which should by the way perform much better in failure]

Comment (ejgallego) [reply proofs/goal.ml]: Oh, we need a new kind of equality that can take 2 evar maps here; don't we?

Comment (ppedrot) [reply proofs/goal.ml]: There is already such an equality `Constr.compare_head_gen_with` actually.

Comment (ejgallego) [reply proofs/goal.ml]: Indeed I reached to that one, so maybe we should try to fix that properly by adding an extra function to `EConstr` that does proper lazy-wrt-substitution equality?

Comment (SkySkimmer) [reply proofs/goal.ml]: There's also `UnivProblem.eq_constr_univs_infer_with` which is called by `Evarutil.eq_constr_univs_test`, except those look at universes.

**Review by ejgallego — COMMENTED** [review]
My point of view is that we should properly fix this; thus this is a soft "Request Changes" review.

**Comment by SkySkimmer** [comment]
Changed

**Review by ppedrot — APPROVED** [review]
LGTM, but I'd like a bench to see if there is any observable effect.

**Review by ejgallego — APPROVED** [review]
Cool, indeed let's run a bench tho it is not fair to compare maybe to master.

**Comment by SkySkimmer** [comment]
>Cool, indeed let's run a bench tho it is not fair to compare maybe to master.

What do you mean?

**Comment by ejgallego** [comment]
It is a supposition, pre-econstr code likely performed normalization at some (random?) points. When that was removed we got an speedup maybe, at the cost of the bug. So this PR may negate it, but it was not fair in the first place.

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/666/console
~~~

┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬───────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │        mem faults         │
│                        │                         │                                             │                                             │                               │                           │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │    NEW    OLD     PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│  coq-mathcomp-fingroup │   55.42   55.58 -0.29 % │      154921939500      154487225578 +0.28 % │      202548935150      202700280398 -0.07 % │     582432     582768 -0.06 % │     10      1   +900.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│          coq-fiat-core │  106.21  106.45 -0.23 % │      303448062624      302282721517 +0.39 % │      378423886198      377531321192 +0.24 % │     493060     493060 +0.00 % │    127    107    +18.69 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│       coq-math-classes │  219.55  219.25 +0.14 % │      613461742690      611634667396 +0.30 % │      776164263405      776162493524 +0.00 % │     518076     517196 +0.17 % │      7     13    -46.15 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│           coq-compcert │ 1019.06 1017.21 +0.18 % │     2841732592186     2834067803975 +0.27 % │     4407525473475     4408644882807 -0.03 % │    1293600    1293532 +0.01 % │    180     39   +361.54 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│             coq-sf-plf │   43.97   43.88 +0.21 % │      123252103390      123108600819 +0.12 % │      155844390095      155863985427 -0.01 % │     499988     500012 -0.00 % │     43      0      +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│   coq-mathcomp-algebra │  155.24  154.87 +0.24 % │      432835875540      431377656641 +0.34 % │      547390398623      547388075252 +0.00 % │     637340     637216 +0.02 % │     26     77    -66.23 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│            coq-bignums │   71.28   71.11 +0.24 % │      198251970123      197821277224 +0.22 % │      260404329045      260787620610 -0.15 % │     526176     525692 +0.09 % │     43      6   +616.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│     coq-mathcomp-field │  227.36  226.74 +0.27 % │      633807320443      631419110180 +0.38 % │      920584659972      920616337155 -0.00 % │     750508     751240 -0.10 % │      1      0      +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│ coq-mathcomp-character │  256.17  255.46 +0.28 % │      713782104794      711851086305 +0.27 % │      984102666749      984144520442 -0.00 % │    1059340    1057372 +0.19 % │      1      0      +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│              coq-verdi │  126.03  125.65 +0.30 % │      349991561504      349022188922 +0.28 % │      450918213260      450211102387 +0.16 % │     614944     614808 +0.02 % │     10      5   +100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│        coq-lambda-rust │ 2064.59 2058.06 +0.32 % │     5751637345454     5737019793151 +0.25 % │     7934374117183     7932638649534 +0.02 % │    1398796    1398888 -0.01 % │     49      0      +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│       coq-fiat-parsers │  696.70  694.31 +0.34 % │     1948475053183     1940807843458 +0.40 % │     2980359753983     2980119926557 +0.01 % │    2895340    2895744 -0.01 % │      3    208    -98.56 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│              coq-color │  693.28  690.77 +0.36 % │     1935950485291     1931392239413 +0.24 % │     2311137641326     2310224475815 +0.04 % │    1379228    1384764 -0.40 % │      5    103    -95.15 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│             coq-geocoq │ 2027.00 2018.37 +0.43 % │     5654686668724     5633560937319 +0.37 % │     8204717553211     8201820571256 +0.04 % │    1245692    1245964 -0.02 % │     42     63    -33.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│  coq-mathcomp-solvable │  194.84  193.88 +0.50 % │      543249611791      540538185456 +0.50 % │      727428012843      727509925765 -0.01 % │     844000     858116 -1.64 % │      0     38   -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│            coq-unimath │ 2094.60 2083.85 +0.52 % │     5830828045553     5798291538229 +0.56 % │    10203241222876    10201836490864 +0.01 % │     962220    1042880 -7.73 % │    519    158   +228.48 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│         coq-verdi-raft │ 1402.67 1393.94 +0.63 % │     3911320187853     3891638030632 +0.51 % │     5313546560017     5313223182181 +0.01 % │    1817424    1817316 +0.01 % │      0      0      +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│         coq-coquelicot │   74.99   74.49 +0.67 % │      205819556659      205131015920 +0.34 % │      248028017850      247213799324 +0.33 % │     695676     695440 +0.03 % │    214     11  +1845.45 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│               coq-hott │  346.52  344.02 +0.73 % │      943012221538      936464014032 +0.70 % │     1424139234640     1424087243934 +0.00 % │     480100     480060 +0.01 % │    346      2 +17200.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│               coq-corn │ 1509.67 1498.64 +0.74 % │     4212795625494     4185573300731 +0.65 % │     6217299699592     6217628660656 -0.01 % │     867468     867564 -0.01 % │      1      1     +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│        coq-fiat-crypto │ 4220.58 4187.46 +0.79 % │    11724936390233    11635299809648 +0.77 % │    18751886181576    18746316562443 +0.03 % │    2537520    2468312 +2.80 % │    774    999    -22.52 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│ coq-mathcomp-ssreflect │   39.48   39.17 +0.79 % │      109130877892      108918425762 +0.20 % │      130580108482      130564399859 +0.01 % │     527940     527840 +0.02 % │      9      1   +800.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│    coq-formal-topology │   30.68   30.42 +0.85 % │       84005901233       83845958605 +0.19 % │      109504971082      109503992956 +0.00 % │     470440     470380 +0.01 % │      4      0      +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│ coq-mathcomp-odd-order │ 1405.63 1392.02 +0.98 % │     3916812656413     3880068107741 +0.95 % │     6466605401655     6468429632559 -0.03 % │    1345624    1349272 -0.27 % │      1      0      +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│              coq-flocq │  569.44  563.68 +1.02 % │     1583667347544     1568764490200 +0.95 % │     2297016081786     2293942131136 +0.13 % │    1730968    1731408 -0.03 % │    203      1 +20200.00 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴───────────────────────────┘
~~~

**Comment by ejgallego** [comment]
I dunno, I guess we have no other choice than to merge this, @ppedrot ?

**Comment by ppedrot** [comment]
Yeah, let's merge, there is no way around :/

**Comment by ejgallego** [comment]
> Yeah, let's merge, there is no way around :/

Taking care of this @ppedrot
