### PR TITLE
Extended internal pattern language of the congruence tactic

### LINKED ISSUE #14651: congruence fails to specialize
#### Description of the problem

As per documentation of `congruence` the following goal is solved using hypothesis specialization.
```coq
Axiom p : (nat -> nat) -> nat.
Definition ap {X Y : Type} (f : X -> Y) (x : X) := f x.

Goal (forall f, p f = ap f 0) -> forall f, p f = ap f 0.
Proof. congruence. Qed.
```

However, unfolding `ap` results in a very similar goal which fails:
```coq
Goal (forall f, p f = f 0) -> forall f, p f = f 0.
Proof. Fail congruence. Admitted.
```

This is because the former pattern `p ?f = ap ?f 0` can be used by `congruence` whereas the `p ?f = ?f 0` cannot.
Specifically, the variable `?f` cannot appear as the head of an application in `?f 0`.
See zulip [discussion](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/congruence.20and.20specialization).

#### Coq Version
8.13.2

### LINKED ISSUE #14662: congruence loops on evar
#### Description of the problem

`congruence` loops on evar conclusion. Here is an overview over failing/working examples:
```coq
Goal False.
Proof.
  evar (e : Prop). assert e.
  { subst e. Fail Timeout 5 congruence. (* infinite loop *)
Abort.

Goal False.
Proof.
  evar (e : Prop). assert (e -> e).
  { subst e. Fail Timeout 5 congruence. (* infinite loop *)
Abort.

Goal False.
Proof.
  evar (e : Prop). assert (id e -> id e).
  { subst e. congruence. (* this works as expected *) }
Abort.  
```

This is also observed in #10210
Suggestion: `congruence` should fail gracefully (but not on all open goals, see third example).

Alternative minimal example:
```coq
Goal exists (x : Prop), x -> x.
Proof.
  eexists. Timeout 1 congruence.
Abort.
```

#### Coq Version
8.13.2

### PR DESCRIPTION
**Pull request by mrhaandi**
This PR extends patterns used by the congruence tactic.
Now it allows to represent patterns `?f p1..pn` with `n > 0`.
For example the following failing example is now successful (see zulip [discussion](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/congruence.20and.20specialization)).

```coq
Axiom p : (nat -> nat) -> nat.
Goal (forall f, p f = f 0) -> forall f, p f = f 0.
Proof. Fail congruence. Admitted.
```

The main observation (also in correspondence with the documentation) is that in the pattern `p ?f = ?f 0` the lhs fully suffices for pattern matching (see example below).

```coq
Definition ap {X Y : Type} (f : X -> Y) (x : X) := f x.

Goal (forall f, p f = ap f 0) -> forall f, p f = ap f 0.
Proof. congruence. Qed.
```

Let us see whether ci will like this one.

Closes  #14651, closes #14662

- [x] Added / updated test-suite
- [x] Entry added in the changelog.

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
This looks nice and interesting. If I understand correctly, it simulates a primitive form of `ap` which does not need to be mentioned explicitly. So, this is convenient and there shouldn't be an overhead I guess.

Note that I'm not expert in Nelson-Oppen though.

**Comment by mrhaandi** [comment]
> This looks nice and interesting. If I understand correctly, it simulates a primitive form of `ap` which does not need to be mentioned explicitly. So, this is convenient and there shouldn't be an overhead I guess.
> 
> Note that I'm not expert in Nelson-Oppen though.

There should be no additional overhead because the `?f t` pattern is still not used for actual matching. However, before `g ?f = ?f t` was discarded entirely because of the restricted pattern language. Now the lhs `g ?f` is considered for matching.

File: plugins/cc/cctac.ml [hunk 1]
```diff
@@ -475,9 +488,10 @@ let cc_tactic depth additionnal_terms =
           convert_to_hyp_tac ida ta idb tb p
   end
 
-
 let congruence_tac depth l =
-  Tacticals.New.tclTHEN (Tacticals.New.tclREPEAT introf) (cc_tactic depth l)
+  Tacticals.New.tclTHEN
+    (Tacticals.New.tclREPEAT (Tacticals.New.tclFIRST [intro; Tacticals.New.tclTHEN hnf_in_concl intro]))
```
Comment (ppedrot) [inline plugins/cc/cctac.ml:493]: I think it's a bad idea to use `hnf_in_concl` here, even if it corresponds to the inlining of `intro`. It's a very weird reduction tactic that should be phased out.  The way this is written is probably going to be inefficient as well. Since we're going for a change of semantics anyways, I'd rather recommend to do what `intro` does, i.e. match on the goal directly but try to `whd`-reduce if not a product / let-in.

Comment (mrhaandi) [reply plugins/cc/cctac.ml:493]: I was mostly following @herbelin's suggestion https://github.com/coq/coq/issues/14662#issuecomment-880867794.
Since `intro` (as opposed to `introf`) is fast and well behaved, I could (instead of copy-pasting `intro` code) replace in the above `hnf_in_concl` by a custom `whd_in_concl` which is basically `Reductionops.clos_whd_flags CClosure.all env sigma t`.
Trying `intro` twice in the reduction case, the performance hit (for `congruence`, which itself is far more expensive) is negligible.

Comment (herbelin) [reply plugins/cc/cctac.ml:493]: I somehow agree with @ppedrot that "`hnf_concl` is a very weird reduction tactic that should be phased out". I proposed to use it because it is what `intro` does already. A form of `whd_in_concl` which preserves let-ins is probably good.

Comment (ppedrot) [reply plugins/cc/cctac.ml:493]: There is a dedicated flag for that, so `Reductionops.clos_whd_flags CClosure.allnolet` is probably the desired reduction.

Comment (mrhaandi) [reply plugins/cc/cctac.ml]: I tried `Reductionops.clos_whd_flags CClosure.allnolet` but it broke a lot of use cases such as proving `Proper (le ==> le) f.` by `congruence`. For this, weak head without let does not produce a good conclusion for a subsequent `intro`.

File: plugins/cc/cctac.ml [hunk 2]
```diff
@@ -43,6 +43,15 @@ let whd env sigma t =
 let whd_delta env sigma t =
   Reductionops.clos_whd_flags CClosure.all env sigma t
 
+let whd_in_concl =
```
Comment (ppedrot) [inline plugins/cc/cctac.ml:46]: Use `Tactics.reduct_in_concl`.

Comment (mrhaandi) [reply plugins/cc/cctac.ml:46]: Ok (I presume `reduct_in_concl ~check:false (Reductionops.whd_all, DEFAULTcast)`).
Since I'm new to Coq's ltac internals, it is not obvious for me which functions are discouraged.

Comment (mrhaandi) [reply plugins/cc/cctac.ml:46]: I'm not sure why `reduct_in_concl` broke `test-suite:base+async` whereas the previous manual `Reductionops.clos_whd_flags CClosure.all` worked fine. I cannot reproduce the error.

Comment (herbelin) [reply plugins/cc/cctac.ml:46]: The async tests (iirc) outputs different things depending on some internal parallelism. If one of `Reductionops.clos_whd_flags CClosure.all` or `reduct_in_concl` is faster than the other, this may change the probabilty that one output comes after the other.

**Comment by ppedrot** [comment]
CI green, so this looks ready. @mrhaandi I think you should squash the various commits of this PR though.

**Comment by mrhaandi** [comment]
> CI green, so this looks ready. @mrhaandi I think you should squash the various commits of this PR though.

Now squashed and rebased. If ci likes it, then it is good to go. I'd suggest a merge after PR #14657 because (although orthogonal) there could be merge conflicts.

**Comment by ppedrot** [comment]
@mrhaandi as expected, this now needs a rebase.

**Comment by mrhaandi** [comment]
> @mrhaandi as expected, this now needs a rebase.

Done. ci `signal 9` errors seem due to the main branch.
