### PR TITLE
Only lower inductives to Prop if the type is syntactically an arity.

### LINKED ISSUE #13300: Anomaly error message when compiling an inductive definition
Hi all, 

First, know that I am using CoqIDE 8.12.0 and that I am rather new to Coq.

Second, here is my problem. I am trying to use some definitions from a file called dd_fc.v which was developed by another researcher in my lab using an earlier version of CoqIDE. When I try to compile it, the following error message appears when the compiler hits an inductive definition called botRule_fc:

> Anomaly
> "File "kernel/univ.ml", line 879, characters 4-10: Assertion failed."
> Please report at http://coq.inria.fr/bugs/.

Note that for the definitions derrec_concl, derrec_fc and dersrec_fc, appearing before botRule_fc, the compiler warns me with the following message:

> Not a truly recursive fixpoint. [non-recursive,fixpoints]

For some reason this last message does not appear on CoqIDE 8.11, even though I am not sure if this is related. 

Here is the code required to see the phenomenon I am describing happening: 

```coq
Set Implicit Arguments.
Notation "[ ]" := nil (format "[ ]") .
Notation "[ x ]" := (cons x nil) .
Notation "[ x ; y ; .. ; z ]" :=  (cons x (cons y .. (cons z nil) ..)) .
Open Scope list_scope.

Axiom map : forall {A B}, (A -> B) -> list A -> list B.

Polymorphic Definition rlsT W := list W -> W -> Type.

Inductive derrec X (rules : list X -> X -> Type) (prems : X -> Type) :
  X -> Type :=
  | dpI : forall concl,
    prems concl -> derrec rules prems concl
  | derI : forall ps concl,
    rules ps concl -> dersrec rules prems ps -> derrec rules prems concl
with dersrec X (rules : list X -> X -> Type) (prems : X -> Type) :
  list X -> Type :=
  | dlNil : dersrec rules prems []
  | dlCons : forall seq seqs,
    derrec rules prems seq -> dersrec rules prems seqs ->
    dersrec rules prems (seq :: seqs)
    .

Inductive derrec_fc X rules (prems : X -> Type) : Type :=
  | fcI : forall concl, derrec rules prems concl -> derrec_fc rules prems.

Inductive dersrec_fcs X rules (prems : X -> Type) : Type :=
  | fcsI : forall concls, dersrec rules prems concls -> dersrec_fcs rules prems.

Fixpoint derrec_concl X rules prems concl
  (der : @derrec X rules prems concl) :=
  match der with
    | dpI _ _ c _ => c
    | derI c _ _ => c
  end.

Fixpoint derrec_fc_concl X rules prems
  (der : @derrec_fc X rules prems) :=
  match der with
    | fcI d => derrec_concl d
  end.

Fixpoint dersrec_concls X rules prems concls
  (ders : @dersrec X rules prems concls) :=
  match ders with
    | dlNil _ _ => []
    | dlCons d ds => derrec_concl d :: dersrec_concls ds
  end.


Fixpoint dersrec_fc_concls X rules prems
  (ders : @dersrec_fcs X rules prems) :=
  match ders with
    | fcsI ds => dersrec_concls ds
  end.

Fixpoint dersrec_trees X rules prems concls
  (ders : @dersrec X rules prems concls) :=
  match ders with
    | dlNil _ _ => []
    | dlCons d ds => fcI d :: dersrec_trees ds
  end.

Definition nextup W rules prems (dt : @derrec_fc W rules prems) :=
  match dt with
    | fcI (dpI _ _ _ _) => []
    | fcI (derI _ _ ds) => dersrec_trees ds
  end.

Inductive botRule_fc X rules prems (der : @derrec_fc X rules prems) : rlsT X :=
  | botRule_fcI : botRule_fc der
    (map (@derrec_fc_concl _ _ _) (nextup der)) (derrec_fc_concl der).
```

Can someone tell me what is happening here? 

Thanks in advance. 

Best,
Ian

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13300

A nicer fix would be to allow Prop in instances, but that's more work.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Bench https://gitlab.com/coq/coq/-/jobs/829703305

File: kernel/univ.ml [hunk 1]
```diff
@@ -976,7 +976,9 @@ struct
 
   let instantiate inst (u, cst) =
     assert (Array.length u = Array.length inst);
-    subst_instance_constraints inst cst
```
Comment (ppedrot) [inline kernel/univ.ml:979]: This seems to be the wrong place to enforce this to me. It's effectively hardwiring unrelated design choices inside a generic purpose function. Is it too hard to add those constraints at the time of the creation of the abstract context?

**Comment by SkySkimmer** [comment]
Fails because it interferes with minimization to set.

**Comment by SkySkimmer** [comment]
Let's try this way instead.

File: vernac/comInductive.ml [hunk 2]
```diff
@@ -283,13 +282,15 @@ let inductive_levels env evd arities inds =
         in
         let minlev =
           (* Indices contribute. *)
-          if indices_matter env && List.length ctx > 0 then (
```
Comment (ppedrot) [inline vernac/comInductive.ml:286]: Why this seemingly unrelated change?

Comment (SkySkimmer) [reply vernac/comInductive.ml:286]: Drive by cleanup while working to understand what's going on

**Comment by ppedrot** [comment]
To be honest, I think that it's irritating that in general an inductive type explicitly annotated with `: Type` lands in `Prop` against my will. We might seize the opportunity to tweak this behaviour.

**Comment by SkySkimmer** [comment]
Not in a bugfix PR imo

**Comment by ppedrot** [comment]
All right.

File: vernac/comInductive.ml (hunk 2 above)
Comment (ppedrot) [reply vernac/comInductive.ml:286]: It's a bit hackish to rely on SProp being lower than anybody when there is no cumulativity relation between it and anybody else, though?

Comment (SkySkimmer) [reply vernac/comInductive.ml:286]: Where do we rely on that?

Comment (ppedrot) [reply vernac/comInductive.ml:286]: In ComInductive.sign_level.

Comment (SkySkimmer) [reply vernac/comInductive.ml:286]: If you mean Universe.sup imo that's well defined on sprop (at the cost of losing `u <= max(u,x)` when x = sprop)

Comment (ppedrot) [reply vernac/comInductive.ml:286]: Depends what you call well-defined. Since SProp is not in cumulativity relation with any other universe, `max(sprop, u)` shouldn't even be defined for any `u != SProp`.

**Comment by ppedrot** [comment]
Merging soon.

**Comment by gares** [comment]
ping

**Review by ppedrot — APPROVED** [review]

**Comment by herbelin** [comment]
I noticed that the PR (besides fixing the anomaly) modifies the behavior only for an inductive type with conclusion hidden behind  a constant. For comparison, the following continue to land in `Prop` or type0-:
```coq
Module NotTemplateTypeExplicit.
#[universes(template=no)] Inductive I : Type := C.
Check I : Prop.

#[universes(template=no)] Record R : Type := {}.
Check R : Prop.
End NotTemplateTypeExplicit.

Module NotTemplateTypeImplicit.
#[universes(template=no)] Inductive I := C'.
Check I : Prop.

#[universes(template=no)] Record R := {}.
Check R : Prop.
End NotTemplateTypeImplicit.

Module TemplateTypeExplicit.
Inductive I : Type := C.
Check I : Prop.

Record R : Type := {}.
Check R : Prop.
End TemplateTypeExplicit.

Module TemplateTypeImplicit.
Inductive I := C.
Check I : Prop.

Record R := {}.
Check R : Prop.
End TemplateTypeImplicit.

Module Hidden. (* non template *)
Polymorphic Definition type := Type.

Inductive I : type := C.
Fail Check I : Prop. (* the change made in this PR *)

Record R : type := {}.
Check R : Prop.
End Hidden.
```

I know it is related to the usual ambiguity about `Prop` being considered a particular case of `Type` or not but to be consistent with the change made in the PR, it seems that at least the `NoTemplateExplicit` and the `Record` in `Hidden` should be in `Set` too.
