### PR TITLE
[glob/aux files] Remove undocumented Stdout dump, cleanup flags.

### LINKED ISSUE #10640: How to disable output when importing in an rcfile?
#### Description of the problem

When I do an import in an rcfile, Coq always prints a message of the form `R15:20 Coq.Strings.String <> <> lib`. This is unhelpful line noise. Is there a way to disable it?

To reproduce:

```bash
echo "Require Import String." > string_rc.v
echo > empty.v
coqc -init-file string_rc.v empty.v
```

this outputs `R15:20 Coq.Strings.String <> <> lib`.

#### Coq Version

The Coq Proof Assistant, version 8.10+alpha (July 2019)
compiled on Jul 16 2019 14:45:28 with OCaml 4.07.1

### PR DESCRIPTION
**Pull request by ejgallego**
Fixes #10640

We remove the `StdOut` dump target, so now dump will only happen if a
file is specified. Indeed, we make the default no to dump, and enable
dump only in coqc.

Output to feedback must be explicitly enabled by clients / coqidetop.

No need for a changes entry as this feature was undocumented, and no
use case was given when introduced.

We could likely also remove the `File` glob dump option, as calling
`coqc` with several files is kind of deprecated.

### CODE REVIEW

File: toplevel/ccompile.ml [hunk 1]
```diff
@@ -108,8 +108,6 @@ let compile opts copts ~echo ~f_in ~f_out =
   in
   match copts.compilation_mode with
   | BuildVo ->
-      Flags.record_aux_file := true;
```
Comment (SkySkimmer) [inline toplevel/ccompile.ml]: Doesn't this change mean we never produce aux files?

Comment (ejgallego) [reply toplevel/ccompile.ml]: In theory the open aux file below should enable the generation for aux files, let me check again.

Comment (ejgallego) [reply toplevel/ccompile.ml]: Well, dune will complain if aux files are not generated so at least for the stdlib we are producing them.

Comment (gares) [reply toplevel/ccompile.ml]: Looks like `Aux_file.recording ()` says `true` iff an output "method" for the aux file is set. I guess we need to carefully check if the old behavior is respected (eg the output method set when the flag used to be false).

The risk is generating them more often I guess

**Comment by ejgallego** [comment]
This PR is pretty straightforward and fixes a very annoying bug that people is hitting in 8.10 [and previous versions], it'd be great if someone could get this merged.

**Comment by ppedrot** [comment]
I can assign if needed, but maybe @SkySkimmer would prefer to do so instead?

**Comment by ejgallego** [comment]
Thanks @ppedrot , this PR also falls in the area of expertise of @herbelin IIUC.

File: toplevel/coqloop.ml [hunk 2]
```diff
@@ -438,19 +438,15 @@ let rec loop ~state =
...
 let loop ~opts ~state =
   drop_args := Some opts;
   let open Coqargs in
   print_emacs := opts.config.print_emacs;
   (* We initialize the console only if we run the toploop_run *)
   let tl_feed = Feedback.add_feeder coqloop_feed in
-  if Dumpglob.dump () then begin
-    Flags.if_verbose warning "Dumpglob cannot be used in interactive mode.";
-    Dumpglob.noglob ()
-  end;
```
Comment (herbelin) [inline toplevel/coqloop.ml]: Why to suppress this? This means that `coqtop -dump-glob foo.glob` will silently do nothing when a dump option is given. Either the warning should be kept (with instead a test on `opts.config.glob_out`) or, better, since the glob file has no purpose in an interactive session with ephemere locations, the options `-dump-glob`, `-no-glob` and `feedback-glob` should be moved from `coqargs` to `coqcargs`.

**Review by herbelin — CHANGES_REQUESTED** [review]
> We remove the `StdOut` dump target, so now dump will only happen if a file is specified. Indeed, we make the default no to dump, and enable dump only in `coqc`.

The logic of `dumpglob` is rather convoluted. If I understand correctly, the exact cause of the bug was a too early call to `Dumpglob.dump_to_dotglob ()` in `coqc_init`, before  `load_init_vernacular` (responsible for loading the rc file) is called. So the new logic which activates glob dumping just before calling `start_dump_glob` and after `load_init_vernacular` is indeed the right thing to do.

I'd be tempted to suggest the following other cleanings if you like them:
- Moving the glob options to `coqcargs` (see comment on code)
- `dump_string` looks ad hoc: the real logic is happening in `dump_ref` and `dump_def` and `dump_string` is redoing half of the job (namely by testing again `NoGlob` and `Feedback`). I would suggest to inline `dump_string` within `dump_ref` and `dump_def` so that there is a better symmetry and the code is easier to understand.
- `MultFiles` and `File` are somehow overlapping. From the point of view of dumpglob, the only thing  which has an impact on dumping is `NoGlob | File of string | Feedback` (i.e. `MultFiles` is functionally equivalent to `File "myvfile.glob"`). From the point of view of `coqc` (more precisely of the `BuildVo` target of `ccompile.ml`), the difference between `MultFiles` and `File of string` is a configuration thing (i.e. whether the user name or the default name is used). This difference of point of view could be enforced by removing `MultFiles` which would allow to get rid of the `Dumpglob.glob_file` reference since then, the info on the file would be entirely contained in the `glob_output` ref. Then, from the point of view of the command line, the coqc info would be `DisableGlob | DefaultGlobFile | CustomGlobFile of string | FeedbackGlob`. This looks a bit redundant, but it seems to explain better the two purposes of `glob_output` (i.e. internal state for dumping vs internal state for the globdump command line options). Don't know your opinion though.

Incidentally, `MultFiles` looks to me like a confusing name (I don't see what is `Mult` in it).

By the way, when is `Feedback` supposed to be used for glob dumping? Is it intended for GUIs or for debugging? Was is used in coqpide? (It was apparently introduced by Carst.)

> Output to feedback must be explicitly enabled by clients / coqidetop.

OK

> No need for a changes entry as this feature was undocumented, and no use case was given when introduced.

OK.

> We could likely also remove the `File glob dump` option, as calling `coqc` with several files is kind of deprecated.

Yes, it is unclear whether we really need to offer the possibility to use a custom glob file. And even more unclear in case `coqc` took several files.

The `record_aux_file` change is unrelated, right? (But it is correct and even better afaicj - neither `proof_using.ml` nor `declare.ml` is supposed to output to the aux file before `start_aux_file` is called.)

Yet another question: should the `-quick` mode produce a glob file? If the glob file is not produced by the `-quick` mode, what shall produce it in a v -> vio -> vo chain?

Summary: this is a clear approve up to the removed coqtop warning (hence the Request changes). Tell me if you'd like to go further.

File: toplevel/coqloop.ml (hunk 2 above)
Comment (ejgallego) [reply toplevel/coqloop.ml]: I have moved the option to the `coqc` arguments as you suggested, thanks.

**Comment by ejgallego** [comment]
> I'd be tempted to suggest the following other cleanings if you like them:

Thanks for your careful review @herbelin . Indeed all your remarks make sense, however note that it may be better to keep this PR small, as it should be backported IMHO.

I had already opened #10644 as to perform further cleanups, so I suggest we implement all your suggestions in that PR targeting 8.11.

> Yes, it is unclear whether we really need to offer the possibility to use a custom glob file. And even more unclear in case `coqc` took several files.

Indeed using a custom file is used by a few contributions to keep the build directory un-cluttered, so IMHO we should then preserve it [it is not very costly I think]

> The `record_aux_file` change is unrelated, right? (But it is correct and even better afaicj - neither `proof_using.ml` nor `declare.ml` is supposed to output to the aux file before `start_aux_file` is called.)

Yup, it is unrelated but indeed I tried to make the aux/glob file generation "well-bracketed" in this PR.

> Yet another question: should the `-quick` mode produce a glob file? If the glob file is not produced by the `-quick` mode, what shall produce it in a v -> vio -> vo chain?

This is a very good question!

**Comment by herbelin** [comment]
> however note that it may be better to keep this PR small, as it should be backported IMHO.

OK.

**Review by herbelin — APPROVED** [review]

**Comment by ejgallego** [comment]
So IMHO we can merge this, @herbelin would you like to be the assignee? Or shall someone else take it?

**Comment by herbelin** [comment]
I'm assigning. Will merge tomorrow.
