### PR TITLE
Cache the result of node expansion of inductive guard checking.

### LINKED ISSUE #21105: x10 performance regression in guard check
### Description of the problem

A Link to The Relevant Repository: https://github.com/Beluga-lang/McTT

With Coq 8.20, [this `Qed.`](https://github.com/Beluga-lang/McTT/blob/b19d268b81c836d22a4bf67cca4f1523452b93c3/theories/Core/Syntactic/CtxSub.v#L90) works fine, finishing within 5 secs or less.
However, with both Rocq 9.0 and dev version, [this `Guarded.`](https://github.com/Beluga-lang/McTT/blob/d77bb6b04d2a34addd278339aee2f68510f45429/theories/Core/Syntactic/CtxSub.v#L90) (nor `Qed.` if the `Guarded.` is removed) does not terminate at least within 1 minute.

One can use https://github.com/Beluga-lang/McTT/tree/issue-rocq for reproduction, with the following steps:

1. Install Rocq 9.0 or dev version.
2. Clone the repository.
3. Run `make` in its `theories` directory.
4. See that `ROCQ compile ./Core/Syntactic/CtxSub.v` takes very long time, specifically on line 90.

### Small Rocq / Coq file to reproduce the bug

I could not come up with a small(er) example.

### Version of Rocq / Coq where this bug occurs

9.0,dev

### Interface of Rocq / Coq where this bug occurs

_No response_

### Last version of Rocq / Coq where the bug did not occur

8.20.0

### PR DESCRIPTION
**Pull request by ppedrot**
For big mutually recursive types, we kept recomputing the recarg expansion again and again. This was a clear source of inefficiency as witnessed in #21105. Since in this case the data is uniquely given by the inductive block, we simply cache it once and for all.

Fixes #21105: x10 performance regression in guard check.

One could legitimately argue the above bug is fixed. When the struct annotations are made explicit, the example takes now ~2s. Without the annotations, it's still taking 30s, which is about 10x faster than the time required on master. I believe that there are other design issues with the heuristic to guess struct annotation, and in addition it seems we still call the heuristic somehow even with the explicit structs.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

File: kernel/inductive.ml [hunk 1]
```diff
@@ -896,12 +896,30 @@ let is_primitive_positive_container env c =
   | Some c' when QConstant.equal env c c' -> true
   | _ -> false
 
+module Cache :
+sig
+  type t
+  val create : unit -> t
+  val get : MutInd.t -> mutual_inductive_body -> t -> wf_paths list array array
```
Comment (SkySkimmer) [inline kernel/inductive.ml]: maybe call this module SubtermCache or this function get_subterms

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
Please make the name Cache.get less generic

**Comment by ppedrot** [comment]
Done.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now
