### PR TITLE
Don't use "sort family" based logic in Indrec

### LINKED ISSUE #18831: Unprintable error with sort poly
~~~coq
Set Universe Polymorphism.

Inductive and@{s|u v|} (A:Type@{s|u}) (B:Type@{s|v}) : Type@{s|max(u,v)} := conj (_:A) (_:B).

Lemma foo (A B:Prop) (x:and A B) : A.
Proof.
  destruct x.
(* Error: <in exception printer>: Anomaly "Uncaught exception Option.IsNone."
Please report at http://coq.inria.fr/bugs/.
<original exception>: Uncaught exception Logic_monad.TacticFailure(_). *)
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #18831

Overlays:
- https://github.com/SkySkimmer/coq-lean-import/pull/17

### CODE REVIEW

File: pretyping/indrec.ml [hunk 1]
```diff
@@ -567,12 +569,12 @@ let mis_make_indrec env sigma ?(force_mutual=false) listdepkind mib u =
...
     in
     let rec put_arity env i = function
-      | ((indi,u),_,_,dep,kinds)::rest ->
+      | ((indi,u),_,_,dep,s)::rest ->
           let indf = make_ind_family ((indi,u), Context.Rel.instance_list mkRel i lnamesparrec) in
-          let s =
-            let sigma, res = Evd.fresh_sort_in_family ~rigid:Evd.univ_flexible_alg !evdref kinds in
-            evdref := sigma; res
-          in
+          (* let s = *)
```
Comment (ppedrot) [inline pretyping/indrec.ml:574]: Why not just remove this code?

**Comment by SkySkimmer** [comment]
@coqbot bench

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
