### PR TITLE
Fixes issue #7172 (don't include MinGW make in install)

### LINKED ISSUE #7172: Windows build: don't include make in installer
Currently the Windows build includes a MinGW make, but this make leads to problems (because it doesn't handle posix shell commands). Since it hides other make in the system, it is better to remove it by default.

there is a top level script option -make. Things to change are:

- set the default to N
- remove the override if MAKEINSTALLER==Y

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
Fix #7172.

For local test I did the following additional changes:

- added a new top level test file (sorry will all be merged into one later)
- fixed logging (especially the module name) for make_addon_bignums (because the output confused me)
- added some comments to the log functions to explain their intended usage

Note: having a module name like V8.8+beta1 is dangerous because this is the name used for caching. If the archive file name doesn't include the module name (or the version), an appropriate module name (used for caching and logging) must be explicitly specified.

One more note: I tested in a local build that make.exe is indeed no longer included.

### CODE REVIEW

File: dev/build/windows/makecoq_mingw.sh [hunk 1]
```diff
@@ -1281,7 +1285,6 @@ function get_cygwin_mingw_sources {
 
 function make_coq_installer {
   make_coq
-  make_mingw_make
```
Comment (gares) [inline dev/build/windows/makecoq_mingw.sh]: I'm fine with that, but IIRC you did want this line to stay...

**Review by gares — APPROVED** [review]

File: dev/build/windows/makecoq_mingw.sh (hunk 1 above)
Comment (MSoegtropIMC) [reply dev/build/windows/makecoq_mingw.sh]: I found that it is redundant. There is this code in makecoq_mingw.sh

if [ "$INSTALLMAKE" == "Y" ] ; then
  make_mingw_make
fi

before the call to make_coq_installer. So if INSTALLMAKE is Y, make will be built, otherwise not.

Sorry that I didn't review your changes properly last time!

Comment (gares) [reply dev/build/windows/makecoq_mingw.sh]: I did not spot it either, no problem. I'll merge as soon as CI says yes.
