### PR TITLE
Check existence of the name in Declare.CInfo.start_core

### LINKED ISSUE #15031: `Instance foo : ...` does not check `foo` is unbound, unlike `Definition` etc
#### Description of the problem

```coq
Class Foo := { foo : nat }.
Instance a : Foo. Admitted.
Instance a : Foo.  (* Accepted! *)
Fail Admitted. (* Delayed error *)
```

I was reminded of this by #15030 and couldn't find an existing issue.

This one is annoying for other reasons — the error message points far away from the error location, slowing down fixes. Other commands get this right.

#### Coq Version

Coq 8.13.2, but since forever?

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #15031

Leaving start_dependent (_derive, _equations) alone for now.

### CODE REVIEW

File: vernac/declare.ml [hunk 1]
```diff
@@ -63,6 +70,7 @@ module CInfo = struct
 
 
   let make ~name ~typ ?(args=[]) ?(impargs=[]) ?using () =
+    check_exists name;
```
Comment (ejgallego) [inline vernac/declare.ml:73]: Uh uh , `CInfo` I don't like CInfo.make getting a dependency on `Global`, this seems very brittle. The check should be added at the right place, which seems it is not here.

Comment (SkySkimmer) [reply vernac/declare.ml:73]: Yeah it's probably too low level.

Comment (ejgallego) [reply vernac/declare.ml]: Yes this info is passed around and stored so an imperative check on build makes no sense.

**Comment by SkySkimmer** [comment]
Let's try this.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by ejgallego** [comment]
A bit of a random thought, but if we want to centralize these kind of checks a bit more, we could have a `CInfo.validate : env -> .... -> bool` thing .
