### PR TITLE
Fix #9344, #9348: incorrect unsafe to_constr in vnorm

### LINKED ISSUE #9344: Uncaught exception Constr.DestKO
#### Version

8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following nonsense causes an anomaly.

```
Compute _ I.
```

```
Anomaly "Uncaught exception Constr.DestKO."
```

#### Notes

This may be a duplicate of #4612,
but the conditions to reproduce this bug are significantly simpler.

### LINKED ISSUE #9348: Assertion failed with primitive projections
#### Version

8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following nonsense causes an assertion failure.

```
Set Primitive Projections.
Record r {A} := R {f : A -> A}.
Compute f _ I.
```

```
Anomaly "File "pretyping/vnorm.ml", line 60, characters 9-15: Assertion failed."
```

#### Notes

This may be a duplicate of #9344,
but the observable result of this bug is different.

### LINKED ISSUE #9354: Anomaly "File "pretyping/vnorm.ml", line 60, characters 9-15: Assertion failed." (anomaly in vm_compute with evars)
#### Version

8.8.2 (also master @ ce8e37b97ce9db6f39368c50fb0ee4a7839ce754)

#### Operating system

Linux

#### Description of the problem

```coq
Fixpoint tuple' T n : Type :=
  match n with
  | O => T
  | S n' => (tuple' T n' * T)%type
  end.

Definition tuple T n : Type :=
  match n with
  | O => unit
  | S n' => tuple' T n'
  end.

(** right-associated tuples *)
Fixpoint rtuple' T n : Type :=
  match n with
  | O => T
  | S n' => (T * rtuple' T n')%type
  end.

Definition rtuple T n : Type :=
  match n with
  | O => unit
  | S n' => rtuple' T n'
  end.

Fixpoint cons' T n {struct n} : forall (y : T) (x : tuple' T n), tuple' T (S n)
  := match n return forall (y : T) (x : tuple' T n), tuple' T (S n) with
     | O => fun y x => (y, x)
     | S n' => fun y x => (@cons' T n' y (fst x), snd x)
     end.
Global Arguments cons' {T n} _ _.

Fixpoint assoc_left' {n T} {struct n}
  : rtuple' T n -> tuple' T n
  := match n return rtuple' T n -> tuple' T n with
     | 0 => fun x => x
     | S n' => fun ts => let xs := @assoc_left' n' T (snd ts) in
                         let x := fst ts in
                         cons' x xs
     end.

Definition assoc_left {n T}
  : rtuple T n -> tuple T n
  := match n with
     | 0 => fun x => x
     | S n' => @assoc_left' n' T
     end.

Compute @assoc_left 3 _ (?[a], ?[b], ?[c]).
(* Error:
Anomaly "File "pretyping/vnorm.ml", line 60, characters 9-15: Assertion failed."
Please report at http://coq.inria.fr/bugs/. *)
```

### PR DESCRIPTION
**Pull request by SkySkimmer**
To github: closes #9348, closes #9354.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
There are a couple unsafe to_constr left around https://github.com/coq/coq/blob/a55679c7ed863a3a0917ef52b9ccf9da248dcf5d/pretyping/vnorm.ml#L113-L114, can anyone tell if they're correct?

**Review by ppedrot — COMMENTED** [review]
I don't think that this is the proper fix. You should rather change the call to `whd_all` in `decompose_prod` to use an evarmap and reduce the defined evars.

**Comment by SkySkimmer** [comment]
We would need to change vnorm to operate on econstr for that to make sense imo.

**Comment by ppedrot** [comment]
Shouldn't be that hard, should it?

**Comment by SkySkimmer** [comment]
I don't want to get into it over some small bug.

**Comment by maximedenes** [comment]
> I don't want to get into it over some small bug.

I can give it a try, if you like.

**Comment by SkySkimmer** [comment]
Have fun

Gaëtan Gilbert

**Comment by JasonGross** [comment]
Should the test case for #9354 be added to the test-suite for this?

**Comment by SkySkimmer** [comment]
You have push rights so if you want it add it yourself. IMO there's not much point in having a bunch of duplicate regression tests though.

**Comment by maximedenes** [comment]
> We would need to change vnorm to operate on econstr for that to make sense imo.

VNorm should operate on a type of terms that are fully normalized but can contain evars (that have to be unresolved, then). I don't know what type is supposed to represent that in the current API. @ppedrot Any suggestion?

**Comment by maximedenes** [comment]
Note that we were using `Constr.t` for this purpose, until this invariant that it should not contain evars was unilaterally introduced...

**Comment by ejgallego** [comment]
What do you mean by "unilaterally"?

**Comment by maximedenes** [comment]
> What do you mean by "unilaterally"?

I mean that it is a global API change that I don't remember being discussed at a Working Group.

Note that I'm not necessarily opposing the idea of this introduced invariant, but I think that a few use cases like the one of these reduction functions were missed (or I'm simply unaware of what types are recommended for that purpose). We probably need to introduce something more fine-grained to support them.

**Comment by ejgallego** [comment]
What do you mean by "global API change"? I was not aware that global API changea, whatever they are, had to be discussed outside of their respective PR.

Anyways, the invariant (and limitations) you are talking about stem from the econstr PR, not from the added debug check that can be easily disabled.

**Comment by maximedenes** [comment]
> What do you mean by "global API change"? I was not aware that global API changea, whatever they are, had to be discussed outside of their respective PR.

I mean adding an invariant that all the components of the system need to be adjusted to. It is not that we have a rule to discuss them, it is more of a matter of common sense to synchronize with all maintainers for changes that are going to impact all components.

> Anyways, the invariant (and limitations) you are talking about stem from the econstr PR, not from the added debug check that can be easily disabled.

I personally don't know if the idea of this invariant was introduced by the econstr PR (I believe it was not made explicit at that time), or when the debug check was added, or somewhere in between. I think it is not very relevant for this discussion, which is about the proper way to interface evar-aware reduction procedures with the current API, in an efficient way.

**Comment by ejgallego** [comment]
Yeah so that is what I mean, I don't understand how the current problem at hand is related with the debug check [that we could get rid any time, even if that is still quite helpful on pointing out problematic places and did a good job in doing so].

So why did you mention it? My point is that indeed that's related to EConstr design API.

**Comment by maximedenes** [comment]
> So why did you mention it?

I did not mention it, you did.

**Comment by ejgallego** [comment]
> I mean adding an invariant that all the components of the system need to be adjusted to.

Note that this is not really an invariant but more of a debug check, many places use `Unsafe.to_constr` and are thus not bound to this invariant.

In 99% of the cases, the invariant makes sense tho. If you are moving from `EConstr.t` to `Term.t` then you better have no evars as the `evar_map` can be dropped after that step.

**Comment by ejgallego** [comment]
> I did not mention it, you did.

sorry:
https://github.com/coq/coq/pull/9349#issuecomment-456005961

> Note that we were using Constr.t for this purpose, until this invariant that it should not contain evars was unilaterally introduced...

**Comment by ejgallego** [comment]
So indeed can you point out to the change you refer to?

**Comment by maximedenes** [comment]
You are mixing the invariant and the check. I was indeed talking about the invariant.

**Comment by ejgallego** [comment]
> I never said that.

Then what was introduced "unilaterally"?

**Comment by ejgallego** [comment]
I mean, what PR are you talking about?

**Comment by ejgallego** [comment]
> This is precisely my remark. You may want to drop the evar-map because you know that all evars are unresolved and you are not doing inference (so they can't be instantiated anymore). This is precisely the setting of these reduction functions.

There is other information in the `evar_map` that you cannot drop, even in your context.

**Comment by maximedenes** [comment]
> There is other information in the `evar_map` that you cannot drop, even in your context.

Maybe, but you don't need the `kind` function on terms to apply substitutions I believe.

**Comment by SkySkimmer** [comment]
Historically  #6454 (introducing the assert in to_constr) says 
>We forbid calling EConstr.to_constr on terms that are not evar-free,
as to progress towards enforcing the invariant that Constr.t is
evar-free. [c.f. #6308]

#6308 proposes the invariant. In it is mentioned "WG discussion: this is not a blocker," I forgot if we said anything else in the WG about it (https://github.com/coq/coq/wiki/CoqWG20180226 doesn't mention it). It has no other discussion.

**Comment by SkySkimmer** [comment]
It looks like this PR is causing out of memory in fiat crypto?

**Comment by ejgallego** [comment]
So indeed it seems to me that the "unilateral" claim should be taken back as it is not factually true as we have discussed this check in the WG a few times.

**Comment by maximedenes** [comment]
> we have discussed this check in the WG a few times

I remember only discussions related to how to handle this check w.r.t. the release process (when to disable it, etc). The issue @SkySkimmer pointed to seems to suggest the same for the invariant (it simply mentions that not respecting the invariant is not a release blocker).

I don't recall any discussion on the invariant itself (whether it is desirable, how to adjust components to it, etc). If you have a pointer, I'll be happy to refresh my memory and it could give some inspiration as to how to improve the fix contained in this PR.

**Comment by ejgallego** [comment]
Usually when making an accusation the burden of proof is on the accuser. Anyways I am stopping discussion here as it doesn't seem useful, but I would rather hope people can refrain from making that kind of negative blame-assigning comments, specially when they are unfounded.

**Comment by maximedenes** [comment]
If the use of the word "unilaterally" has hurt you in any way, I apologize. I'll try another phrasing next time.

**Comment by ejgallego** [comment]
> If the use of the word "unilaterally" has hurt you in any way, I apologize. I'll try another phrasing next time.

Sorry @maximedenes and thanks, I didn't mean to create a discussion, I was not hurt, but very confused, as I don't see where the "unilateral" behavior happened, and so far you didn't indeed indicate it, neither correct your statement so I remain confused about what you mean.

Regarding the PR, indeed the key point here is what was done before `EConstr` I think. Using `Unsafe.to_constr` in these contexts is OK so I tend to think if there is a bug the bug was here before not now, but I lack the time to look at history today.

**Comment by SkySkimmer** [comment]
Fiat crypto failure disappeared? https://gitlab.com/coq/coq/pipelines/48009827
Let's have a rebase and re-CI to be sure.

**Comment by JasonGross** [comment]
We recently dropped a number of uses of vm_compute from fiat-crypto.  If you want an old commit to test with, I can point you at the commit right before we dropped these.  (Actually, I think you'll get it if you add the `new-pipeline` target to the legacy fiat-crypto CI.)

**Comment by SkySkimmer** [comment]
Benching https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/642/console

**Comment by SkySkimmer** [comment]
~~~
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │       mem faults       │
│                        │                         │                                             │                                             │                               │                        │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW    OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│  coq-mathcomp-fingroup │   54.30   54.49 -0.35 % │      151540218646      151351547561 +0.12 % │      197874934023      197927661096 -0.03 % │     574080     574080 +0.00 % │       5      1 +400.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│             coq-geocoq │ 1979.51 1986.31 -0.34 % │     5524995208480     5542523931050 -0.32 % │     8058745746232     8059920219552 -0.01 % │    1232676    1196156 +3.05 % │     461    253 +82.21 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│              coq-color │  680.97  682.92 -0.29 % │     1905211477749     1910520445628 -0.28 % │     2285740622511     2285621691309 +0.01 % │    1379464    1385064 -0.40 % │     100    150 -33.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│    coq-formal-topology │   29.87   29.92 -0.17 % │       82525880710       82424724978 +0.12 % │      107798870778      107801846974 -0.00 % │     467320     467324 -0.00 % │      22      1 +2100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│           coq-compcert │ 1004.23 1005.49 -0.13 % │     2797071822883     2798688222054 -0.06 % │     4363719654365     4363913389248 -0.00 % │    1312944    1312976 -0.00 % │     237    273 -13.19 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│        coq-fiat-crypto │ 3904.36 3908.72 -0.11 % │    10843337226709    10855420520368 -0.11 % │    17505923917749    17505914033789 +0.00 % │    2466956    2464692 +0.09 % │    1103    772 +42.88 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│       coq-math-classes │  215.29  215.52 -0.11 % │      603578955765      604064603804 -0.08 % │      767204344532      767261470920 -0.01 % │     514608     514568 +0.01 % │      34     17 +100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│       coq-fiat-parsers │  686.49  687.14 -0.09 % │     1921008898721     1921813166476 -0.04 % │     2949991335709     2950066786884 -0.00 % │    3023272    3033824 -0.35 % │     240    723 -66.80 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│  coq-mathcomp-solvable │  189.97  190.08 -0.06 % │      529057639938      529315251566 -0.05 % │      711685161698      711711751218 -0.00 % │     848376     848700 -0.04 % │      11      2 +450.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│        coq-lambda-rust │ 2062.12 2063.24 -0.05 % │     5740988830845     5750561372537 -0.17 % │     7927877134827     7933142295775 -0.07 % │    1366376    1366452 -0.01 % │      49      0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│               coq-corn │ 1484.38 1485.10 -0.05 % │     4143645150119     4148021843905 -0.11 % │     6168476863310     6168233812486 +0.00 % │     854636     854684 -0.01 % │       1      1 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│            coq-unimath │ 1944.15 1944.30 -0.01 % │     5411123864898     5415811907708 -0.09 % │     9428199343226     9425130502238 +0.03 % │     956412     903736 +5.83 % │     523    203 +157.64 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│            coq-bignums │   69.25   69.24 +0.01 % │      193790513056      193688671072 +0.05 % │      256871401006      256860414860 +0.00 % │     522548     522512 +0.01 % │     179    169 +5.92 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│               coq-hott │  336.51  336.39 +0.04 % │      914170322698      914783197578 -0.07 % │     1397462632548     1397547294427 -0.01 % │     479176     479168 +0.00 % │     457    155 +194.84 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│ coq-mathcomp-odd-order │ 1360.31 1359.78 +0.04 % │     3791419225754     3788918417346 +0.07 % │     6367528179592     6367149296751 +0.01 % │    1348868    1348616 +0.02 % │      48     73 -34.25 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│ coq-mathcomp-ssreflect │   38.67   38.65 +0.05 % │      107000498360      106943883206 +0.05 % │      128036308253      128034182257 +0.00 % │     523160     523020 +0.03 % │     135     10 +1250.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│     coq-mathcomp-field │  220.60  220.46 +0.06 % │      613786937911      614333957462 -0.09 % │      892401344915      891839332303 +0.06 % │     749840     749800 +0.01 % │       0     38 -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│   coq-mathcomp-algebra │  151.53  151.42 +0.07 % │      422756637278      422564074642 +0.05 % │      534350897006      534424221113 -0.01 % │     636812     636936 -0.02 % │      16     36 -55.56 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│          coq-fiat-core │  105.27  105.12 +0.14 % │      298989797648      299399616683 -0.14 % │      374513386737      374536578646 -0.01 % │     476448     476432 +0.00 % │     414    237 +74.68 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│ coq-mathcomp-character │  250.29  249.92 +0.15 % │      697256023600      696368220669 +0.13 % │      963672174690      963222150360 +0.05 % │    1068824    1069128 -0.03 % │      72     67 +7.46 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│                coq-vst │ 3041.79 3036.02 +0.19 % │     8478633761200     8465896514849 +0.15 % │    11851625945238    11851605998927 +0.00 % │    1715676    1715664 +0.00 % │     214    435 -50.80 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│              coq-flocq │  560.18  558.00 +0.39 % │     1557995494518     1552931353583 +0.33 % │     2280676120433     2280770567062 -0.00 % │    1717400    1718724 -0.08 % │     301    366 -17.76 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│         coq-coquelicot │   73.88   73.52 +0.49 % │      202274923621      202527665333 -0.12 % │      244799217585      244769175142 +0.01 % │     688104     687924 +0.03 % │     214     11 +1845.45 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│             coq-sf-plf │   43.25   42.87 +0.89 % │      121192019672      121104052856 +0.07 % │      153606183894      153602056431 +0.00 % │     490024     490036 -0.00 % │      44      0  +nan % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴────────────────────────┘
~~~

**Comment by SkySkimmer** [comment]
@maximedenes pong

**Comment by ppedrot** [comment]
I am still not happy with the PR, it is but a hotfix. We need to port the VM reduction to `EConstr` instead of randomly casting to evar-free-but-no-so-much terms, as I am pretty sure that other parts of the code would break in case of missing evar expansion. I won't complain if the PR is merged though, it's indeed solving a bug, but this should be properly rewritten at some point.

**Comment by maximedenes** [comment]
> randomly casting to evar-free-but-no-so-much terms

They are not evar-free at all, the are evar-normal. Is there a type to represent that?

**Comment by maximedenes** [comment]
> They are not evar-free at all, they are evar-normalized (substitution fully applied). Is there a type to represent that?

@ppedrot ping

**Comment by ppedrot** [comment]
There is no type for that, and I doubt it'd make sense at all. Being normalized is not stable by any reasonable typing rule.

**Comment by maximedenes** [comment]
> I won't complain if the PR is merged though, it's indeed solving a bug, but this should be properly rewritten at some point.

I suggest we merge this for 8.10, and I'll port the normalization to `EConstr` once I unify the code of VM and native (this is in progress already).

File: pretyping/vnorm.ml [hunk 1]
```diff
@@ -196,7 +196,7 @@ and nf_univ_args ~nb_univs mk env sigma stk =
 and nf_evar env sigma evk stk =
   let evi = try Evd.find sigma evk with Not_found -> assert false in
   let hyps = Environ.named_context_of_val (Evd.evar_filtered_hyps evi) in
-  let concl = EConstr.Unsafe.to_constr @@ Evd.evar_concl evi in
```
Comment (maximedenes) [inline pretyping/vnorm.ml]: @SkySkimmer doesn't `nativenorm` suffer the same issue?

Comment (SkySkimmer) [reply pretyping/vnorm.ml]: Looks like it does, or at least `Eval native_compute in _ I.` anomalies.

Comment (maximedenes) [reply pretyping/vnorm.ml]: Ok, I'll port the patch to `nativenorm` then.

Comment (maximedenes) [reply pretyping/vnorm.ml]: Done.

**Review by maximedenes — APPROVED** [review]

File: test-suite/bugs/closed/bug_9348.v [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Set Primitive Projections.
+Record r {A} := R {f : A -> A}.
+Compute f _ I.
+Eval native_compute in _ I.
```
Comment (SkySkimmer) [inline test-suite/bugs/closed/bug_9348.v]: Did you mean to put this in the other test file?

Comment (maximedenes) [reply test-suite/bugs/closed/bug_9348.v]: Right, will fix, thanks!

Comment (maximedenes) [reply test-suite/bugs/closed/bug_9348.v]: Done.
