### PR TITLE
Fixing use of argument scopes in patterns + a further cleanup of constrintern.ml

### LINKED ISSUE #13534: Match pattern with `@` accepted although to few arguments mentioned
#### Description of the problem
Is it intended that trailing implicit arguments can be ommited in  patterns when using `@`?
I would expect the following to fail at both `Check`s:

```` coq
Inductive Test := test : forall {a b c d e f : bool}, Test.
About test.
Axiom t : Test.

Check match t with | @test => _ end.
Check match t with | @test _ => _ end.
````

(This reminds me of https://github.com/mattam82/Coq-Equations/issues/77 and the confusion I had there, and might mean that Equations also allows strange things, which might sometimes lead to the same confusion for new users I had there. But I did not test if this transfers to Equations).

(I found this while constructing the example for #13533 )

#### Coq Version

master from a few days ago ( 0501761 )

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** fix + cleanup

This PR contains a few bug fixes:
- fixing argument scopes and let-ins in cases patterns
- for `foo` an abbreviation, accepting `@foo` in cases pattern as it is already the case in terms

It contains also cleanings such as making the interpretation path for cases pattern more consistent with the one of terms, even if more could be done.

It depended on #12027 (merged), #12684 (merged) and #12685 (merged) but eventually should be pushed also on top of #8808 (merged) and #12099 (merged).

- [X] Added / updated test-suite
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

Added: happened to have fixed #13534.

### CODE REVIEW

File: interp/constrintern.ml [hunk 1]
```diff
@@ -1657,6 +1639,29 @@ let drop_notations_pattern (test_kind_top,test_kind_inner) genv env pat =
...
+                Inductiveops.inductive_nparams env ind
+              else if Int.equal n (Inductiveops.constructor_nrealdecls env cstr) then
+                Inductiveops.inductive_nparamdecls env ind
+              else
+                error_wrong_numarg_constructor ?loc env cstr
+                  (Inductiveops.constructor_nrealargs env cstr)
+            | _ -> 0 in
+          List.make n (DAst.make @@ RCPatAtom None)
+        else
+          syndef_pl in
```
Comment (SkySkimmer) [inline interp/constrintern.ml]: Could you avoid this multiline `in` style, I really have trouble reading it for whatever reason.

**Review by SkySkimmer — APPROVED** [review]
I didn't look closely at the main commit but results look OK

Will give a day or 2 for comments before merging.

File: pretyping/cases.ml [hunk 2]
```diff
@@ -46,8 +46,8 @@ module NamedDecl = Context.Named.Declaration
 type pattern_matching_error =
   | BadPattern of constructor * constr
   | BadConstructor of constructor * inductive
-  | WrongNumargConstructor of constructor * int
-  | WrongNumargInductive of inductive * int
+  | WrongNumargConstructor of constructor * bool * int * int * int
+  | WrongNumargInductive of inductive * bool * int * int * int
```
Comment (ppedrot) [inline pretyping/cases.ml:50]: Can we get inline records? This is pretty cryptic at first sight.

File: interp/constrintern.ml [hunk 3]
```diff
@@ -1721,17 +1721,12 @@ let drop_notations_pattern (test_kind_top,test_kind_inner) genv env pat =
...
     | CPatCstr (qid, Some expl_pl, pl) ->
-      let g =
-        try Nametab.locate qid
-        with Not_found as exn ->
-          let _, info = Exninfo.capture exn in
-          let info = Option.cata (Loc.add_loc info) info loc in
-          Exninfo.iraise (InternalizationError (NotAConstructor qid), info)
-      in
-      (* Convention: (@r expl_pl) deactivates implicit arguments in expl_pl and in pl *)
-      (* but not scopes in expl_pl *)
```
[the remark this answers is not in the document]
Comment (herbelin) [reply interp/constrintern.ml]: It is not a special convention anymore, this is now the normal effect of `@`.

File: interp/constrintern.ml (hunk 1 above)
Comment (herbelin) [reply interp/constrintern.ml]: OK

File: pretyping/cases.ml (hunk 2 above)
Comment (herbelin) [reply pretyping/cases.ml]: Done. Are the field names informative enough to you?

File: pretyping/cases.ml [hunk 4]
```diff
@@ -46,8 +46,10 @@ module NamedDecl = Context.Named.Declaration
 type pattern_matching_error =
   | BadPattern of constructor * constr
   | BadConstructor of constructor * inductive
-  | WrongNumargConstructor of constructor * int
-  | WrongNumargInductive of inductive * int
+  | WrongNumargConstructor of
+      {cstr:constructor; expanded:bool; nargs:int; expected_nassums:int; expected_ndecls:int}
+  | WrongNumargInductive of
+      {ind:inductive; expanded:bool; nargs:int; expected_nassums:int; expected_ndecls:int}
```
Comment (ppedrot) [inline pretyping/cases.ml:52]: Good enough for me.

File: pretyping/cases.mli [hunk 5]
```diff
@@ -23,17 +23,19 @@ open Evardefine
...
   | NonExhaustive of cases_pattern list
   | CannotInferPredicate of (constr * types) array
 
 exception PatternMatchingError of env * evar_map * pattern_matching_error
 
-val error_wrong_numarg_constructor : ?loc:Loc.t -> env -> constructor -> int -> 'a
+val error_wrong_numarg_constructor : ?loc:Loc.t -> env -> constructor -> bool -> int -> int -> int -> 'a
 
-val error_wrong_numarg_inductive   : ?loc:Loc.t -> env -> inductive -> int -> 'a
+val error_wrong_numarg_inductive   : ?loc:Loc.t -> env -> inductive -> bool -> int -> int -> int -> 'a
```
Comment (ppedrot) [inline pretyping/cases.mli:38]: You might want to label the arguments here as well.

Comment (SkySkimmer) [reply pretyping/cases.mli:38]: @herbelin will you label the arguments here?

Comment (herbelin) [reply pretyping/cases.mli:38]: If you think it is really important I can.

Comment (SkySkimmer) [reply pretyping/cases.mli:38]: please do

Comment (herbelin) [reply pretyping/cases.mli]: OK, done.

**Comment by SkySkimmer** [comment]
@coqbot: merge now
