### PR TITLE
Remove various circumvolutions from reduction behaviors

### LINKED ISSUE #10056: Wrong description of reduction behavior in `About`
On the following definition:

```coq
Definition volatilematch (n : nat) :=
  match n with
  | O => O
  | S p => p
  end.

Arguments volatilematch / n : simpl nomatch.
```

`About volatilematch` says `The reduction tactics always unfold volatilematch`.

But that's not true: any of `Eval simpl in fun n => volatilematch n` or `Eval cbn in fun n => volatilematch n` gives `fun n : nat => volatilematch n`.

Of course, removing the `simpl nomatch` makes both tactics unfold the definition.

AFAICT, the documentation does not say anything about the combination of these flags. @gares is this an `About` bug, or a `cbn`/`simpl` bug?

### PR DESCRIPTION
**Pull request by maximedenes**
Incidentally, this fixes #10056

It seems we were doing a lot of unnecessary conversions between datatypes to represent these modifiers. Also none of the types used seemed to make a lot of sense. Finally, the data stored as a "request" in the libobject did not make more sense to me, so I removed it.

### CODE REVIEW

File: pretyping/reductionops.ml [hunk 1]
```diff
@@ -974,37 +956,39 @@ let rec whd_state_gen ?csts ~refold ~tactic_mode flags env sigma =
...
-                                        (arg,Stack.Cst(Stack.Cst_const (fst const, u'),curr,remains,bef,cst_l)::s')
-         end
+            | Some behavior ->
+              begin match behavior with
+              | ReductionBehaviour.NeverUnfold -> fold ()
+              | ReductionBehaviour.UnfoldWhen { nargs = Some n } when Stack.args_size stack < n ->
+                fold ()
+              | ReductionBehaviour.UnfoldWhen { recargs; dontexposematch } -> (* maybe unfolds *)
+                if dontexposematch then
+                  let app_sk,sk = Stack.strip_app stack in
```
Comment (maximedenes) [inline pretyping/reductionops.ml]: @gares isn't it suspicious that we ignore `recargs` in this branch?

File: pretyping/tacred.ml [hunk 2]
```diff
@@ -761,30 +767,29 @@ and whd_simpl_stack env sigma =
...
-	   else s'
-	 with Redelimination -> s')
-	  
+        (try
+           let unf = Projection.unfolded p in
+           if unf || is_evaluable env (EvalConstRef (Projection.constant p)) then
+             let npars = Projection.npars p in
+             (match unf, ReductionBehaviour.get (ConstRef (Projection.constant p)) with
+              | false, Some ReductionBehaviour.NeverUnfold -> s'
+              | false, Some (ReductionBehaviour.UnfoldWhen { recargs }) when not (List.is_empty recargs) -> (* TODO why are nargs and dontexposecase ignored? *)
```
Comment (maximedenes) [inline pretyping/tacred.ml]: @gares do you know why only recargs is taken into account here?

**Comment by maximedenes** [comment]
@gares ping, I'd need your input on this PR. Thanks!

File: pretyping/reductionops.ml [hunk 3]
```diff
@@ -90,48 +90,45 @@ module ReductionBehaviour = struct
...
+    | NeverUnfold
+    | UnfoldWhen of { nargs : int option;
+                      recargs: int list;
+                      dontexposematch : bool;
+                    }
+
+  let more_args k = function
+    | NeverUnfold as x -> x
+    | UnfoldWhen { nargs; recargs; dontexposematch } ->
+      UnfoldWhen { nargs = Option.map (fun n -> n + k) nargs;
```
Comment (SkySkimmer) [inline pretyping/reductionops.ml]:
```suggestion
      UnfoldWhen { nargs = Option.map ((+) k) nargs;
```
would look nicer considering the next line ;)

File: pretyping/reductionops.ml [hunk 4]
```diff
@@ -90,48 +90,45 @@ module ReductionBehaviour = struct
...
-  let classify = function
-    | ReqLocal, _ -> Dispose
-    | ReqGlobal _, _ as o -> Substitute o
+  let classify (local,_ as o) = if local then Dispose else Substitute o
 
-  let subst (subst, (_, (r,o as orig))) =
-    ReqLocal,
-    let r' = fst (subst_global subst r) in if r==r' then orig else (r',o)
+  let subst (subst, (local, (r,o) as orig)) =
+    let r' = fst (subst_global subst r) in if r==r' then orig
```
Comment (SkySkimmer) [inline pretyping/reductionops.ml]:
```suggestion
    let r' = subst_global_reference subst r in if r==r' then orig
```

File: pretyping/reductionops.ml (hunk 1 above)
Comment (gares) [reply pretyping/reductionops.ml]: I think it fine, but I suggest you make 2 branches in the match, putting first the `dontexposematch = true` one.
Note that this case only inserts a stack frame, the recursive call eventually looks at recargs.

File: pretyping/reductionops.ml [hunk 5]
```diff
@@ -1015,41 +999,43 @@ let rec whd_state_gen ?csts ~refold ~tactic_mode flags env sigma =
...
-	       |[] -> (* if nargs has been specified *)
-		(* CAUTION : the constant is NEVER refold
-                   (even when it hides a (co)fix) *)
+           let stack'', csts = whrec Cst_stack.empty stack' in
+           if equal_stacks sigma stack' stack'' then fold ()
+           else stack'', csts
+         | Some behavior ->
+           begin match behavior with
+             | ReductionBehaviour.NeverUnfold -> fold ()
+             | ReductionBehaviour.UnfoldWhen { nargs = Some n } when Stack.args_size stack < n - (npars + 1) -> (* TODO check this condition *)
```
[the remark this answers is not in the document]
Comment (gares) [reply pretyping/reductionops.ml]: Oh, but this code I've never looked at...

File: pretyping/tacred.ml (hunk 2 above)
Comment (gares) [reply pretyping/tacred.ml]: No, when I added the reduction behavior PrimProj was not there.. These lines come from 84544396cbbf34848be2240acf181b4d5f1f42d2 .

**Comment by gares** [comment]
I'm sorry but I don't know the code you point to.
At the same time the new datatype is more elegant, but makes even less clear that the various options have an order because the order is not in the type but in the way the match is written. For example the dontexposematch thing, given that is it applied always, should not be at the same level of recargs. It should eventually wrap it, so that in order to even see recargs one has to put the stack frame to check, at return time, if the output is match free.

**Comment by maximedenes** [comment]
> It should eventually wrap it, so that in order to even see recargs one has to put the stack frame to check, at return time, if the output is match free.

@gares Sorry, but I'm not sure to see what you mean exactly. Concretely, what type would you like it to be?

**Comment by gares** [comment]
I meant
```ocaml
type simpl_opts = Never | AllowCase of when_opts | DisallaowCase of when_opts
and when_opts = { recargs : ... ; nargs : ... }
```
Maybe factoring code is not trivial, but at least the `dontexposecase` thing is handled once and forall in one place.

**Comment by maximedenes** [comment]
All suggestions applied, should be ready modulo CI. Solving the bugs that seem to be already there will be for another day.

@gares can you be the assignee?

**Review by gares — APPROVED** [review]
