### PR TITLE
Fix bug #8432 : program fixpoint and universes

### LINKED ISSUE #8432: Universes and obligations for fixpoints
#### Version
8.8.1

#### Description of the problem

The following raises a typing error, because universes are not properly handled for mutual fixpoints in Program.

```
Require Import Program.Tactics.

Obligation Tactic := idtac.
Set Universe Polymorphism.

Inductive paths {A : Type} (a : A) : A -> Type :=
  idpath : paths a a.

Inductive Empty : Type :=.
Inductive Unit : Type := tt.
Definition not (A : Type) := A -> Empty.

  Lemma nat_path_O_S (n : nat) (H : paths O (S n)) : Empty.
  Proof. refine (
    match H in paths _ i return
      match i with
      | O => Unit
      | S _ => Empty
      end
    with
    | idpath _ => tt
    end
  ). Defined.
  Lemma symmetry {A} (x y : A) (p : paths x y) : paths y x.
  Proof.
    destruct p. apply idpath.
  Defined.
  Lemma nat_path_S_O (n : nat) (H : paths (S n) O) : Empty.
  Proof. eapply nat_path_O_S. exact (symmetry _ _ H). Defined.
Set Printing Universes.
Program Fixpoint succ_not_zero (n:nat) : not (paths (S n) 0) :=
match n as n return not (paths (S n) 0) with
| 0 => nat_path_S_O _
| S n' => let dummy := succ_not_zero n' in _
end.
Next Obligation.
  intros f _ n dummy H. exact (nat_path_S_O _ H).
  Show Universes.
Defined.
```

### PR DESCRIPTION
**Pull request by mattam82**
One didn't normalize the bodies of fixpoints according to the universe
context, resulting in a type errors. Use EConstr.to_constr to ensure
universes are normalized instead of using EConstr.Unsafe.to_constr.

**Kind:** bug fix

Fixes / closes #8432

It resolves one of the issues originally found in https://github.com/HoTT/HoTT/issues/895

- [x ] Added / updated test-suite

### CODE REVIEW

**Comment by ppedrot** [comment]
Doesn't seem to compile...

**Comment by SkySkimmer** [comment]
Needs rebase to have #8420.

**Comment by mattam82** [comment]
Yep I just rebased it realizing it

File: vernac/obligations.ml [hunk 1]
```diff
@@ -523,11 +523,11 @@ let declare_mutual_definition l =
...
 	let subs, typ = (subst_body true x) in
         let env = Global.env () in
-        let sigma = Evd.from_env env in
+        let sigma = Evd.from_ctx x.prg_ctx in
         let term = snd (Reductionops.splay_lam_n env sigma len (EConstr.of_constr subs)) in
         let typ = snd (Reductionops.splay_prod_n env sigma len (EConstr.of_constr typ)) in
-	let term = EConstr.Unsafe.to_constr term in
-	let typ = EConstr.Unsafe.to_constr typ in
+        let term = EConstr.to_constr sigma term in
+        let typ = EConstr.to_constr sigma typ in
```
Comment (ejgallego) [inline vernac/obligations.ml]: Are `term` and `typ` guaranteed to be ground here? Otherwise you need to use the `allow_undefined_evars` flag.

Comment (ppedrot) [reply vernac/obligations.ml]: What is the status of this flag? Isn't it supposed to be removed in the released version?

Comment (ppedrot) [reply vernac/obligations.ml]: Reading the code it looks like these terms should be evar-free though.

**Review by ppedrot — APPROVED** [review]

File: vernac/obligations.ml (hunk 1 above)
Comment (ejgallego) [reply vernac/obligations.ml]: @ppedrot the release version will just disable the anomaly, as not to bother users; however all new code should be aware to respect the invariant, as the anomaly will stay in master.

**Comment by Zimmi48** [comment]
@mattam82 @ppedrot @ejgallego Is this ready to merge?

**Comment by ejgallego** [comment]
> @mattam82 @ppedrot @ejgallego Is this ready to merge?

I am not competent enough, I guess you want to cc @SkySkimmer too.

**Comment by SkySkimmer** [comment]
I don't know how obligations work so not me.

**Comment by ppedrot** [comment]
I think this is ready. Unless I get some contrary notice, I'll merge this soon.

File: vernac/obligations.ml (hunk 1 above)
Comment (Zimmi48) [reply vernac/obligations.ml]: @ejgallego Is there an issue about this?
