### PR TITLE
Fix #16922: bug in Nametab.remove which #12324 introduced (deactivation of notations)

### LINKED ISSUE #16922: Anomaly not found in nametab (for syndef)
```coq
Module X.
Inductive t : Type := .
End X.
Notation t := X.t.
About t. (* anomaly *)
Print t. (* anomaly *)
```
This is on 387378141ed6c4426d4ebfee8f15766044909aba , while it works on 8.16.
CC 8.17 RM @Zimmi48

### PR DESCRIPTION
**Pull request by herbelin**
`Nametab.remove_path` was inadvertantly losing brothers of modified subtrees.

In passing, we:
- document `Nametab.push_until` a small bit further
- add debugging printers for `Nametab.nametree`
- remove code made dead by #12324 but which was still present in the archive

Fixes / closes #16922

- [x] Added / updated **test-suite**.

### CODE REVIEW

File: library/nametab.ml [hunk 1]
```diff
@@ -228,12 +227,9 @@ let push visibility uname o tab =
...
 let rec remove_path uname tree = function
   | modid :: path ->
+      let modify _ mc = remove_path uname mc path in
       let map =
-        try
-          let submap = ModIdmap.find modid tree.map in
-          let submap = remove_path uname submap path in
-          if is_empty_tree submap then ModIdmap.empty
-          else ModIdmap.add modid submap tree.map
+        try ModIdmap.modify modid modify tree.map
```
Comment (ppedrot) [inline library/nametab.ml:232]: Shouldn't we still remove the subtree pointed by modid when it's empty? I don't know if we rely somewhere on the invariant that tries should not contain empty components.

Comment (herbelin) [reply library/nametab.ml:232]: Why not. How would you do it? Using a specific version of modify taking an extra argument to check if the data has become irrelevant and contract  a `MNode {l=MEmpty; v; d; r=MEmpty; h}` for irrelevant `d` into a `MEmpty`?

Or to come back to the previous version, computing the map with the `modid` branch removed,  checking if both this new `map` and the new `submap` are empty, returning accordingly either `ModIdmap.empty` or the addition of the new `submap` to the modid-omitting `map`?

Comment (herbelin) [reply library/nametab.ml:232]: Good idea, done.

Comment (ppedrot) [reply library/nametab.ml]: I think that going back to the previous code and removing the binding instead of returning the empty map is the simplest way to fix it.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]
