### PR TITLE
ssr: skip impargs in pattern FO unif

### LINKED ISSUE #16763: [ssr] rewrite selects the wrong instance
#### Description of the problem

The first pass of ssreflect's rewrite matching mechanism, which first tries to find a syntactic occurrence of the pattern is too strict and should discard implicit arguments (since they should be invisible to the user).

Here is an example where we always expect the first occurence of `f` to match but because of the implicit unit they do not:
```coq
Require Import ssreflect.

Definition f {u : unit} (x y : nat) := x + y.

Definition ttt := tt.
Arguments ttt /.

Lemma fE x y : @f tt x y = y + x.
Proof. by rewrite /f; elim: x => //= ? ->. Qed.

Section f.
Variables (x y z t : nat).
Variables P : nat -> nat -> nat -> Prop.
Hypothesis G : P (y + x) (z + t) (y + x).

Lemma f_lemma : P (@f ttt x y) (@f tt z t) (@f tt x y).
Proof.
rewrite fE.
Fail exact: G. (* should rewrite first and last but rewrites second arg *)
Abort.

Lemma f_lemma : P (@f ttt x y) (@f tt z t) (@f tt x y).
Proof.
rewrite [f _ _]fE. (* works :o *)
exact: G.
Qed.

End f.
```

CC @gares

#### Coq Version

The Coq Proof Assistant, version 8.16.0
compiled with OCaml 4.12.1

### PR DESCRIPTION
**Pull request by gares**
This is an attempt to make changes in the algebraic hierarchy of mathcomp less painful.

When a structure s with op1 and op2 is broken into s1 with op1 and s2 with op2 it may be the case that lemmas involving both operations have a type like `forall i:sj, op1 i x (op2 i y) z = ..` where an instance of the structure sj (join of s1 and s2) occurs non linearly. A concrete goal may have after the split the shape `op1 canon_s1_on_T x (op2 (sj_to_s2 canon_sj_on_T) y) z` or something like that, while before both ops would have the same canonical instance on T (the type of x, y, z).
Because of the 2 syntactically different instances the FO pass makes a different choice than before.

#### This PR tries to avoid breakage by making the FO pass do

- ignore implicit arguments of constants, e.g. structure instances
  - ~in one case the real arg is implicit because it is followed by a phantom, hence I use the shortest list of impargs~
    Not needed/used anymore, but still valid: rewrite takes the shortest list of impargs among the existing ones.
- ignore subterms that are FO-different but the pattern is is a proj
- reduce the goal subterm if it is not equal to the pattern and is a proj (applied to a CS instance) 
- fail to match if the pattern contains more evars that the matched goal (i.e. if it contains non-instantiated variables)

- flags `Set SsrMatching LegacyFoUnif` makes it behave as before, so one can compare old/new using the same version of Rocq and/or give up fixing a proof.

#### Things tried and abandoned

- completely disable FO pass
  - lemmas with shape `_ (if ..)` or `_ f g` rely on the FO pass. I tried adjusting the HO one to behave the same (use the first arg key rigidly) but some lemmas nee more keys...
  - some rewritings become very surprising, even in algebra, eg (_ * _ * _) since some defs compute and can expose *
- do not ignore `proj _ = t` problems, since in groups we have plenty of set/group lemmas, with gval that would behave surprisingly, eg `x \in <[x]> || x \in G` where `G : group`, the second one has an explicit gval, the former none, the lemma has it.

- [x] Added / updated **test-suite**.

- [x] Added **changelog**.
- [x] Added / updated **documentation**.
   I don't think the FO pass was ever documented, and I'm not so sure it should. This PR contains the details for the braves.
  
  - [ ] Documented any new / changed **user messages**.
  - [ ] Updated **documented syntax** by running `make doc_gram_rsts`.

- [x] https://github.com/math-comp/math-comp/pull/1438
- [x] https://github.com/math-comp/odd-order/pull/69
- [x] https://github.com/math-comp/analysis/pull/1641
- [x] https://github.com/jasmin-lang/jasmin/pull/1209
- [x] https://github.com/math-comp/multinomials/pull/103
- [x] https://github.com/math-comp/real-closed/pull/78
- [x] https://github.com/rocq-community/coqeal/pull/109
- [x] https://github.com/math-comp/Abel/pull/101
- [x] https://github.com/rocq-community/gaia/pull/28
- [x] https://github.com/rocq-community/apery/pull/35
- [x] https://github.com/rocq-community/graph-theory/pull/47
- [x] https://gitlab.inria.fr/coquelicot/coquelicot/-/merge_requests/14
- [x] https://github.com/uwplse/verdi/pull/148
- [x] https://github.com/MetaRocq/metarocq/pull/1190
- [x] https://gitlab.mpi-sws.org/iris/iris/-/merge_requests/1124
- [x] https://github.com/mit-pdos/perennial/pull/279

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by gares** [comment]
@coqbot run full ci

**Comment by CohenCyril** [comment]
Great!!! There will be legitimate breakage! Maybe we need a flag ?
The second optim would be that the second phase only captures hidden occurrences when it wouldn't typecheck otherwise.

**Comment by proux01** [comment]
FWIW, a quick look at mathcomp show 85 proofs requiring an update.

**Comment by gares** [comment]
I'm still tweaking it, I have an overlay for mathcomp that should work. But there is one ugly thing that stays, eg
a pattern like `gval X` still matches the unexpects one among `x \in <[x]> || x \in G` because `<[x]>` is only canonically a group, while G is immediate (first order works). I tried to plug HO unif just for CS inference but does not work because I may have skipped earlier some terms that are implicit but kind of expected to be there, like the group type `gT`, hence calling HO "too rarely" fails.

**Comment by gares** [comment]
On the positive side, most of the broken proof were bad ones, i.e. relying in some way on the FO pass to select "the wrong one". The only cases where now things are reversed are because of the behavior above, IIRC 2 occurrences in MC.

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
coqbot is currently broken due to heroku problems https://rocq-prover.zulipchat.com/#narrow/channel/237656-Rocq-devs-.26-plugin-devs/topic/Gitlab.20CI.20Pipeline.20not.20starting.20on.20GitHub/with/523253084

**Comment by gares** [comment]
@coqbot bench

File: dev/bench/bench.sh [hunk 1]
```diff
@@ -41,15 +41,15 @@ check_variable () {
...
 : "${new_coq_opam_archive_git_branch:=master}"
 : "${old_coq_opam_archive_git_branch:=master}"
 : "${new_coq_version:=dev}"
 : "${old_coq_version:=dev}"
 : "${num_of_iterations:=1}"
 : "${timeout:=3h}"
-: "${coq_opam_packages:=rocq-stdlib rocq-bignums coq-hott coq-performance-tests-lite coq-engine-bench-lite rocq-elpi rocq-mathcomp-ssreflect rocq-mathcomp-fingroup rocq-mathcomp-algebra rocq-mathcomp-solvable rocq-mathcomp-field rocq-mathcomp-character coq-mathcomp-odd-order coq-mathcomp-analysis coq-math-classes coq-corn coq-compcert rocq-equations rocq-metarocq-utils rocq-metarocq-common rocq-metarocq-template rocq-metarocq-pcuic rocq-metarocq-safechecker rocq-metarocq-erasure rocq-metarocq-translations coq-color coq-coqprime coq-coqutil coq-bedrock2 coq-rewriter coq-fiat-core coq-fiat-parsers coq-fiat-crypto-with-bedrock coq-unimath coq-coquelicot coq-iris-examples coq-verdi coq-verdi-raft coq-fourcolor coq-rewriter-perf-SuperFast coq-vst coq-category-theory coq-neural-net-interp-computed-lite}"
+: "${coq_opam_packages:=rocq-mathcomp-ssreflect rocq-mathcomp-algebra rocq-mathcomp-fingroup rocq-mathcomp-solvable rocq-mathcomp-field rocq-mathcomp-character}"
```
Comment (gares) [inline dev/bench/bench.sh]:
```suggestion
: "${coq_opam_packages:=rocq-elpi rocq-mathcomp-ssreflect rocq-mathcomp-fingroup rocq-mathcomp-algebra rocq-mathcomp-solvable rocq-mathcomp-field rocq-mathcomp-character coq-mathcomp-odd-order}"
```

**Comment by gares** [comment]
Dear @rocq-prover/bench-maintainers I have a hard times running the bench on my overlay of mathcomp and oddorder. Ant ideas what I'm doing wrong?

File: dev/bench/bench.sh [hunk 2]
```diff
@@ -41,15 +41,15 @@ check_variable () {
 : "${old_ocaml_flambda:=0}"
 : "${new_coq_repository:=${CI_REPOSITORY_URL:-.}}"
 : "${old_coq_repository:=${CI_REPOSITORY_URL:-.}}"
-: "${new_coq_opam_archive_git_uri:=https://github.com/coq/opam-coq-archive.git}"
-: "${old_coq_opam_archive_git_uri:=https://github.com/coq/opam-coq-archive.git}"
+: "${new_coq_opam_archive_git_uri:=https://github.com/gares/opam.git}"
+: "${old_coq_opam_archive_git_uri:=https://github.com/rocq-prover/opam.git}"
 : "${new_coq_opam_archive_git_branch:=master}"
```
Comment (SkySkimmer) [inline dev/bench/bench.sh]: wrong branch?

Comment (gares) [reply dev/bench/bench.sh]: thanks

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
Much better performance.
I still don't know why odd order fail

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
> I still don't know why odd order fail

I see it passed in the newest bench, did you figure it out?

**Comment by gares** [comment]
yes, it was a bad url. The main problem is that one needs to look at the artifacts in order to see stderr. I wonder if we could `cat` all `*_stderr.log` for the packages at the end of the job

**Comment by gares** [comment]
@coqbot bench now

**Comment by gares** [comment]
@coqbot bench now

**Comment by gares** [comment]
CI for the odd-order thm is a big ugly. The problem is that the the FO pass succeeds more often than before generating some false positives. On these we run evarconv, and there are many huge terms if one unfolds. It is hard to fix at the level of scripts because they little things, 0.1 more here and there. Not to sure how to improve things. Maybe we should wait to see the bench on MCA (overlay still missing)

**Comment by proux01** [comment]
If it's also around 10% in MCA, we should probably consider it acceptable considering the huge quality-of-life improvement this is.

**Comment by gares** [comment]
I think we should also try if that would make (for real) a better QOL.
Like "reverting" recent overlays, I know the jasmin one for the introduction of monoids was perceived as "bad" by the upstreams. I'd like to check if that overlay would have been less invasive.

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
Looks like I found the root cause of the inefficiency, I think we are back in business!

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
Tested reverting `69bccc36eea070931ee9962a87a09df8f8602bbd` on jasmin and it seems to work.
I don't know if there are other recent commits in MC we could try to revert and see if this patch compensates them. CC @tragicus

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
is the last commit the snail? (avoided a "loop" in oothm/*9.v)
@coqbot bench now

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
My understanding is that, statistically, when FO fails on the instance to be rewritten because of a proj in the goal it is on a "late" potential match. All early matched failed with a visible cost. By failing we re-do most of the work in the HO pass to finally succeed where we could have in the FO pass thanks to the proj-in-goal rule.

The extra work (done by the subsequent HO pass) costs 25% overall, that seems too much.

I'll try to resurrect the failure cache from the FO phase to the HO one and see if it compensates for that (it did not serve much purpose before)

**Comment by gares** [comment]
@coqbot bench

**Comment by Tragicus** [comment]
> Tested reverting `69bccc36eea070931ee9962a87a09df8f8602bbd` on jasmin and it seems to work. I don't know if there are other recent commits in MC we could try to revert and see if this patch compensates them. CC @Tragicus

There are quite a few overlays on https://github.com/math-comp/math-comp/pull/1256 that are referenced after a few comments.

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
YES @proux01

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by proux01** [comment]
Perennial is fine, it will just be a matter of bumping the git submodule for iris in there, once the iris overlay gets merged.

**Comment by gares** [comment]
@coqbot run full CI

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
I found a countermeasure for MCA, I hope.

@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
dear @rocq-prover/ci-maintainers this very last run, an overlay was not picked up:
```
+ '[' -d /builds/coq/coq/_build_ci/analysis ']'
+ [[ -n https://github.com/gares/analysis ]]
+ '[' -n '' ']'
+ git clone https://github.com/math-comp/analysis /builds/coq/coq/_build_ci/analysis -b master --depth 10
```
I have no idea what happened, it worked until now

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
This job will fail as well https://gitlab.inria.fr/coq/coq/-/jobs/5927814 since it did not pick up the overlay.
I really don't get it, it used to work...

**Comment by SkySkimmer** [comment]
It's picked up AFAICT, in the log for https://gitlab.inria.fr/coq/coq/-/jobs/5927814
- line 1427 `+ local ov_url=https://github.com/gares/analysis`
- line 1497 `commit d8baad020bb746b28fd93b8db6f5905310c4cc86`

**Comment by SkySkimmer** [comment]
It's possible that a recent PR on analysis added some code that needs changing (CI tests the overlay rebased on the base branch so includes any changes since you made the overlay)

**Comment by gares** [comment]
Bench is good!

**Comment by proux01** [comment]
> It's possible that a recent PR on analysis added some code that needs changing (CI tests the overlay rebased on the base branch so includes any changes since you made the overlay)

Thanks, we only do that for the PR (not the overlays) in mathcomp nix-toolbox-based CI, that explains the difference.

**Comment by proux01** [comment]
CI "green" (the perennial failure is the iris git submodule in there that will need an update once the iris overlay gets merged).
BTW, @gares don't we have an iris merge request? (I don't see it in the top post list)

**Comment by gares** [comment]
> BTW, @gares don't we have an iris merge request? (I don't see it in the top post list)

yes, it is the last one.

**Comment by gares** [comment]
let me remove the bench commit that is totally off, as well as the install vscoq one that is another PR

**Comment by proux01** [comment]
> > BTW, @gares don't we have an iris merge request? (I don't see it in the top post list)
> 
> yes, it is the last one.

Yes, I found it and added it in the meantime ;-)

File: plugins/ssrmatching/ssrmatching.ml [hunk 3]
```diff
@@ -56,7 +56,10 @@ let _ =
       optwrite = debug }
 let pp s = !pp_ref s
 let { Goptions.get = option_LegacyFoUnif } =
-  Goptions.declare_bool_option_and_ref ~key:["SsrMatching";"LegacyFoUnif"] ~value:false ()
+  Goptions.declare_bool_option_and_ref ~key:["SsrMatching";"LegacyFoUnif"]
+    ~depr:{Deprecation.since=Some "9.2";
+            note=Some "Use this flag only to port scripts from 9.1 to 9.2, do not leave it in final scripts." }
```
Comment (proux01) [inline plugins/ssrmatching/ssrmatching.ml:61]: Maybe the flag can be mentionned in the changelog entry?

Comment (gares) [reply plugins/ssrmatching/ssrmatching.ml:61]: done

**Comment by proux01** [comment]
@upamanyus, @RalfJung, @tchajed please bump the iris submodule (to iris master) in perennial

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
once overlays are merged, we should do one last benchmark

**Comment by RalfJung** [comment]
(I am not involved with Perennial any more.)

**Comment by tchajed** [comment]
Perennial is now up-to-date with Iris master.

**Comment by proux01** [comment]
Thanks @tchajed here is the (trivial and backward compatible) overlay: https://github.com/mit-pdos/perennial/pull/279

**Comment by gares** [comment]
@proux01 I plan to test this PR on the wrapping branch with Matteo on Tuesday. Apparently it is not solving all problems as we expected, it may need more fine tuning.

**Comment by CalosciMatteo** [comment]
Yes, there still seems to be some problems with the unification of the notation "^+" which is present both on the ring and fingroup scope,

This is the error i get (for instance in `Lemma lerXn2r` in `numdomain.v`):
```
Check _ * (y^+n).
  (* The term "y" has type
         "POrderedZmodule.sort
            (join_Num_NumDomain_between_monoid_Magma_and_Num_POrderedZmodule R)"
       while it is expected to have type "BaseFinGroup.arg_sort ?T".
  *)
```
Despite `(y^+n)` getting correctly typed as
```
(*: Magma.sort
         (monoid_BaseUMagma__to__monoid_Magma
            (Num_NumDomain__to__monoid_BaseUMagma R))*)
```

this is under
'''Variable R : numDomainType.
Implicit Types x y z t : R. '''


The workaround is to annote the context as in 'Check _ * (y^+n)%R.'

**Comment by proux01** [comment]
Well, this is ready with (almost) all overlays merged, so I'd be inclined to merge it and let any further improvement happen in a new PR. Anyway, this won't land in 9.1 so changes won't be spread across multiple releases.

Let's do the following:
* wait until end of the week, if more fine tuning happens and doesn't need any new overlay, let's keep it here
* otherwise, merge this as it is and let further progress take place in a new PR.

**Comment by proux01** [comment]
@coqbot bench

**Comment by proux01** [comment]
> This is the error i get (for instance in `Lemma lerXn2r` in `numdomain.v`):
> 
> Check _ * (y^+n).

Not sure I understand the link between `Check` and ssrmatching (what this PR is about). I'll let you two sort this out on Tuesday.

> The workaround is to annote the context as in 'Check _ * (y^+n)%R.'

Again, this is just changing the notation interpretation, hard to see any clear link with pattern selection.

**Comment by gares** [comment]
> Well, this is ready with (almost) all overlays merged, so I'd be inclined to merge it and let any further improvement happen in a new PR. Anyway, this won't land in 9.1 so changes won't be spread across multiple releases.
> 
> Let's do the following:
> * wait until end of the week, if more fine tuning happens and doesn't need any new overlay, let's keep it here
> * otherwise, merge this as it is and let further progress take place in a new PR.

Totally agree, I just want to look at the rewrite errors. This PR and overlays are sound I believe. If we identify a needed change that requires no overlay update we will propose it, otherwise we make a separate pr.

**Comment by gares** [comment]
OK, we confirm the PR fixes all the matching related problems we have in the wrapping branch. Green light.

**Comment by proux01** [comment]
So, only waiting for the coquelicot overlay to be merged and I merge.

**Comment by proux01** [comment]
@coqbot merge now

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now
