### PR TITLE
Correction of ugly message described in #4667

### LINKED ISSUE #4667: functional induction: Uncaught exception Invalid_argument("List.addn")
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#4667
From: @tbelaire
Reported version: 8.5
CC:   @forestjulien, @ppedrot, @psteckler

### PR DESCRIPTION
**Pull request by forestjulien**
**Kind:** documentation / bug fix / feature / performance / infrastructure.
kind: bug fix

Fixes / closes #4667

### CODE REVIEW

**Comment by Zimmi48** [comment]
Just FTR, ugly only takes one "g" and GitHub doesn't seem to know the e-mail address from which you committed (no big deal though).

File: plugins/funind/indfun.ml [hunk 1]
```diff
@@ -91,10 +91,22 @@ let functional_induction with_clean c princl pat =
...
+      in
+      List.map2
+        (fun c pat ->
+          (
+            (None,
+             Ltac_plugin.Tacexpr.ElimOnConstr (fun env sigma -> (sigma,(c,NoBindings)) )
+            ),
+            (None,pat),
+            None)
+        )
```
Comment (gares) [inline plugins/funind/indfun.ml]: Not sure I understand the indentation of this piece of code...

**Review by gares — CHANGES_REQUESTED** [review]
fix indentation plz

File: plugins/funind/indfun.ml (hunk 1 above)
Comment (ejgallego) [reply plugins/funind/indfun.ml]: Yes please, use ocp-indent and conform the style prevalent in the codebase.

Comment (Zimmi48) [reply plugins/funind/indfun.ml]: I wouldn't say there is a prevalent style in the code base...
However, I'm interesting to learn what settings you recommend using ocp-indent with. Just the default?
What does it do? I find the official webpage pretty bare. Does it fix the indentation on save? Or does it guarantee a good indentation when you are using the tab key?
It would be very interesting to give such hints in the contributing guide BTW.

Comment (ejgallego) [reply plugins/funind/indfun.ml]: > I wouldn't say there is a prevalent style in the code base...

Indentation-wise there is some sort of uniformity, at least in the core.

> Just the default?

I find the defaults good.

> What does it do? I find the official webpage pretty bare. Does it fix the indentation on save? Or does it guarantee a good indentation when you are using the tab key?

I use it bound to `tab`.

> It would be very interesting to give such hints in the contributing guide BTW.

I was under the impression it was already discussed in `dev/doc/setup.txt` but I see it is not the case. And in fact, that file is a bit outdated, and in conflict with https://github.com/coq/coq/wiki/DevelSetup

Comment (Zimmi48) [reply plugins/funind/indfun.ml]: Indeed.

Comment (forestjulien) [reply plugins/funind/indfun.ml]: Done

**Comment by Zimmi48** [comment]
I think what @ejgallego was suggesting was to use ocp-indent more locally (on the lines affected by this PR).
In general, we are wary of such big commits re-indenting everything. I wouldn't be radically opposed to it though. But only if we all agreed to use ocp-indent and we made sure that we tested this in CI (like with the linter). A more limited approach where only modified lines are checked for indentation (like what @SkySkimmer did with the whitespace-linter) would probably be better but I'm not sure it is practicable.
In any case, this second commit is certainly too much for the present PR.

**Comment by SkySkimmer** [comment]
>only modified lines are checked for indentation

That wouldn't work well, if you replace tabs with spaces in random lines it will look the same but if you auto-indent random lines it will do silly things sometimes.

File: plugins/funind/indfun.ml (hunk 1 above)
Comment (SkySkimmer) [inline plugins/funind/indfun.ml]: In general we avoid spaces including newlines immediately after opening and before closing parentheses, so this would look like
```ocaml
      List.map2
        (fun c pat ->
           ((None,
             Ltac_plugin.Tacexpr.ElimOnConstr
               (fun env sigma -> (sigma,(c,NoBindings)))),
            (None,pat),
            None))
```

File: plugins/funind/indfun.ml [hunk 2]
```diff
@@ -29,115 +29,127 @@ let is_rec_info sigma scheme_info =
...
+        in
+        List.map2
+          (fun c pat ->
+             (
+               (None,
+                Ltac_plugin.Tacexpr.ElimOnConstr (fun env sigma -> (sigma,(c,NoBindings)) )
+               ),
+               (None,pat),
+               None)
+          )
```
Comment (gares) [inline plugins/funind/indfun.ml]: weird

**Review by gares — DISMISSED** [review]
The diff is now huge because of ocp-indent being run on many lines... but the weird lines are still there.

File: plugins/funind/indfun.ml (hunk 2 above)
Comment (Zimmi48) [reply plugins/funind/indfun.ml]: Interesting. So actually, ocp-indent doesn't help much there. Too bad.

**Comment by maximedenes** [comment]
If we want this fix in 8.8.0, it should be made ready today. Maybe we can just remove the second commit? @gares WDYT?

**Comment by gares** [comment]
The ugly indentation is in the first commit, so taking 1 commit is not an option I believe

**Comment by forestjulien** [comment]
Hope this indentation version is correct

**Comment by Zimmi48** [comment]
I think it is but it would be even better if you could squash the two commits together.

**Comment by forestjulien** [comment]
True  ;)
Done !

**Comment by Zimmi48** [comment]
@forestjulien Do you use two different machines? It looks like they are not configured to use the same e-mail address when committing and GitHub only knows about one of the two e-mail addresses.

**Comment by forestjulien** [comment]
@Zimmi48 : It was a problem with my .gitconfigure file which used to contain an alias of my real email. 
Should be fixed now

**Review by Matafou — APPROVED** [review]
LGTM

**Comment by Matafou** [comment]
I will merge as soon as tests are OK if nobody objects.

**Comment by maximedenes** [comment]
@Matafou tests ok, you can merge :)

**Comment by Matafou** [comment]
Done.
