### PR TITLE
Use automata rather than regular trees for guard checking.

### LINKED ISSUE #21526: Slow fixpoint type-checking due to the guard condition
### Description of the problem

Here is a self-contained example of a fixpoint that takes a lot of time to pass the guard condition. It comes from mattam82/Coq-Equations#620 with all the equations cruft removed.

### Small Rocq / Coq file to reproduce the bug

```coq
Notation "x ++ y" := (app x y) (right associativity, at level 60).

Module Deque.

  Inductive prodN (A : Type) : nat -> Type :=
    | prodZ : A -> prodN A 0
    | prodS {n : nat} : prodN A n -> prodN A n -> prodN A (S n).
  Arguments prodZ {A}.
  Arguments prodS {A n}.

  Inductive buffer (A : Type) (lvl : nat) : nat -> Type :=
    | B0         : buffer A lvl 0
    | B1         : prodN A lvl -> buffer A lvl 1
    | B2         : prodN A lvl -> prodN A lvl -> buffer A lvl 2
    | B3         : prodN A lvl -> prodN A lvl -> prodN A lvl ->
                  buffer A lvl 3
    | B4         : prodN A lvl -> prodN A lvl -> prodN A lvl ->
                  prodN A lvl -> buffer A lvl 4
    | B5         : prodN A lvl -> prodN A lvl -> prodN A lvl ->
                  prodN A lvl -> prodN A lvl -> buffer A lvl 5.
  Arguments B0 {A lvl}.
  Arguments B1 {A lvl}.
  Arguments B2 {A lvl}.
  Arguments B3 {A lvl}.
  Arguments B4 {A lvl}.
  Arguments B5 {A lvl}.

  Inductive packet (A : Type) (lvl : nat) : nat -> nat -> nat -> Type :=
    | Hole {size : nat} : packet A lvl lvl size size
    | Packet {clvl psize pktsize csize ssize} :
        buffer A lvl psize ->
        packet A (S lvl) clvl pktsize csize ->
        buffer A lvl ssize ->
        packet A lvl clvl (psize + pktsize + pktsize + ssize) csize.
  Arguments Hole {A lvl size}.
  Arguments Packet {A lvl clvl psize pktsize csize ssize}.

  Inductive chain (A : Type) (lvl : nat) : nat -> Type :=
    | Ending {size : nat} :
        buffer A lvl size ->
        chain A lvl size
    | Chain {clvl size csize : nat} :
        packet A lvl clvl size csize ->
        chain A clvl csize ->
        chain A lvl size.
  Arguments Ending {A lvl size}.
  Arguments Chain {A lvl clvl size csize}.

  Inductive t (A : Type) (size : nat) : Type :=
    | T : chain A 0 size -> t A size.
  Arguments T {A size}.

  Definition concat_map_prodN_seq
    {T : Type -> nat -> Type}
    (f : forall A lvl, T A lvl -> list A)
    {A lvlt lvl} : prodN (T A lvlt) lvl -> list A :=
    let fix local {lvl} (p : prodN (T A lvlt) lvl) : list A :=
      match p with
      | prodZ ta => f A lvlt ta
      | prodS p1 p2 => local p1 ++ local p2
      end
    in local.

  Definition concat_map_buffer_seq
    {T : Type -> nat -> Type}
    (f : forall A lvl, T A lvl -> list A)
    {A lvlt lvl size} (b : buffer (T A lvlt) lvl size) : list A :=
    match b with
    | B0 => nil
    | (B1 a) => concat_map_prodN_seq f a
    | (B2 a b) => concat_map_prodN_seq f a ++ concat_map_prodN_seq f b
    | (B3 a b c) => concat_map_prodN_seq f a ++ concat_map_prodN_seq f b ++
                    concat_map_prodN_seq f c
    | (B4 a b c d) => concat_map_prodN_seq f a ++ concat_map_prodN_seq f b ++
                      concat_map_prodN_seq f c ++ concat_map_prodN_seq f d
    | (B5 a b c d e) => concat_map_prodN_seq f a ++ concat_map_prodN_seq f b ++
                        concat_map_prodN_seq f c ++ concat_map_prodN_seq f d ++
                        concat_map_prodN_seq f e
    end.

  Definition concat_map_packet_seq
    {T : Type -> nat -> Type}
    (f : forall A lvl, T A lvl -> list A)
    {A lvlt lvl clvl pktsize csize} :
    packet (T A lvlt) lvl clvl pktsize csize -> list A -> list A :=
    let fix local {lvl clvl pktsize csize}
      (pkt : packet (T A lvlt) lvl clvl pktsize csize) (l : list A) : list A :=
      match pkt with
      | Hole => l
      | Packet p pkt s => concat_map_buffer_seq f p ++
                          local pkt l ++
                          concat_map_buffer_seq f s
      end
    in local.

  Definition concat_map_chain_seq
    {T : Type -> nat -> Type}
    (f : forall A lvl, T A lvl -> list A)
    {A lvlt lvl size} : chain (T A lvlt) lvl size -> list A :=
    let fix local {lvl size} (c : chain (T A lvlt) lvl size) : list A :=
      match c with
      | Ending b => concat_map_buffer_seq f b
      | Chain pkt c => concat_map_packet_seq f pkt (local c)
      end
    in local.

  Definition concat_map_seq
    {T : Type -> nat -> Type}
    (f : forall A lvl, T A lvl -> list A)
    {A lvlt size} (d : t (T A lvlt) size) : list A :=
    match d with
    | T c => concat_map_chain_seq f c
    end.

End Deque.

Inductive nkind : Type := only | left | right.

Notation ckind := nat.
Notation empty  := 0.
Notation single := 1.
Notation pair   := 2.

Definition prefix' := Deque.t.
Definition suffix' := Deque.t.

Inductive node' (A : Type) : nat -> nkind -> Type :=
  | Only_end {q  : nat} : prefix' A (S q) -> node' A 0 only
  | Only {qp qs nc : nat} :
    prefix' A (5 + qp) -> suffix' A (5 + qs) ->
    node' A (S nc) only
  | Left {qp qs nc : nat} :
    prefix' A (5 + qp) -> suffix' A 2 ->
    node' A nc left
  | Right {qp qs nc : nat} :
    prefix' A 2 -> suffix' A (5 + qs) ->
    node' A nc right.
Arguments Only_end {A q}.
Arguments Only {A qp qs nc}.
Arguments Left {A qp qs nc}.
Arguments Right {A qp qs nc}.

Inductive stored_triple (A : Type) : nat -> Type :=
  | Ground : A -> stored_triple A 0
  | Small {lvl q : nat} :
    suffix' (stored_triple A lvl) (3 + q) ->
    stored_triple A (S lvl)
  | Big {lvl qp qs : nat} {ck : ckind} :
    prefix' (stored_triple A lvl) (3 + qp) ->
    chain A (S lvl) ck only ->
    suffix' (stored_triple A lvl) (3 + qs) ->
    stored_triple A (S lvl)

with body (A : Type) : nat -> nat -> nkind -> nkind -> Type :=
  | Hole {lvl : nat} {k : nkind} : body A lvl lvl k k
  | Single_child {hlvl tlvl : nat} {hk tk : nkind} :
    node' (stored_triple A hlvl) 1 hk ->
    body A (S hlvl) tlvl only tk ->
    body A hlvl tlvl hk tk
  | Pair_yellow {hlvl tlvl : nat} {hk tk : nkind} :
    node' (stored_triple A hlvl) 2 hk ->
    body A (S hlvl) tlvl left tk ->
    chain A (S hlvl) single right ->
    body A hlvl tlvl hk tk
  | Pair_orange {hlvl tlvl : nat} {hk tk : nkind} :
    node' (stored_triple A hlvl) 2 hk ->
    chain A (S hlvl) single left ->
    body A (S hlvl) tlvl right tk ->
    body A hlvl tlvl hk tk

with packet (A : Type) : nat -> nat -> nat -> nkind -> Type :=
  | Packet {hlvl tlvl nc : nat} {hk tk : nkind} :
    body A hlvl tlvl hk tk ->
    node' (stored_triple A tlvl) nc tk ->
    packet A hlvl tlvl nc hk

with chain (A : Type) : nat -> ckind -> nkind -> Type :=
  | Empty {lvl : nat} : chain A lvl empty only
  | Single {hlvl tlvl : nat} {ck : ckind} {nk : nkind} :
    packet A hlvl tlvl ck nk ->
    chain A (S tlvl) ck only ->
    chain A hlvl single nk
  | Pair {lvl : nat} :
    chain A lvl single left ->
    chain A lvl single right ->
    chain A lvl pair only.

Arguments Ground {A}.
Arguments Small {A lvl q}.
Arguments Big {A lvl qp qs ck}.

Arguments Hole {A lvl k}.
Arguments Single_child {A hlvl tlvl hk tk}.
Arguments Pair_yellow {A hlvl tlvl hk tk}.
Arguments Pair_orange {A hlvl tlvl hk tk}.

Arguments Packet {A hlvl tlvl nc hk tk}.

Arguments Empty {A lvl}.
Arguments Single {A hlvl tlvl ck nk}.
Arguments Pair {A lvl}.

Definition prefix (A : Type) (lvl : nat) := prefix' (stored_triple A lvl).
Definition suffix (A : Type) (lvl : nat) := suffix' (stored_triple A lvl).

Definition node (A : Type) (lvl : nat) := node' (stored_triple A lvl).

Inductive cadeque : Type -> Type :=
| T {A : Type} {ck : ckind} : chain A 0 ck only -> cadeque A.

Definition concat_map_node'_seq
  {T : Type -> nat -> Type}
  (f : forall A lvl, T A lvl -> list A)
  {A lvlt nc nk} (n : node' (T A lvlt) nc nk) (l : list A) : list A :=
  match n with
  | Only_end p => Deque.concat_map_seq f p
  | Only p s => Deque.concat_map_seq f p ++ l ++ Deque.concat_map_seq f s
  | Left p s => Deque.concat_map_seq f p ++ l ++ Deque.concat_map_seq f s
  | Right p s => Deque.concat_map_seq f p ++ l ++ Deque.concat_map_seq f s
  end.

Definition stored_triple_seq_functional :=
  fun (stored_triple_seq : forall (A : Type) (lvl : ckind), stored_triple A lvl -> list A)
  (_ : forall (A : Type) (hlvl tlvl : ckind) (hk tk : nkind), body A hlvl tlvl hk tk -> list A -> list A)
  (_ : forall (A : Type) (hlvl tlvl nc : ckind) (nk : nkind),
       packet A hlvl tlvl nc nk -> list A -> list A)
  (chain_seq : forall (A : Type) (lvl ck : ckind) (nk : nkind),
               chain A lvl ck nk -> list A)
  (A : Type) (lvl : ckind) (st : stored_triple A lvl) =>
match st with
| Ground y => cons y nil
| @Small _ lvl0 q s => Deque.concat_map_seq stored_triple_seq s
| @Big _ lvl0 qp qs ck p c s =>
    Deque.concat_map_seq stored_triple_seq p ++
    chain_seq A (S lvl0) ck only c ++ Deque.concat_map_seq stored_triple_seq s
end.

Definition body_seq_functional :=
  fun (stored_triple_seq : forall (A : Type) (lvl : ckind), stored_triple A lvl -> list A)
  (body_seq : forall (A : Type) (hlvl tlvl : ckind) (hk tk : nkind),
              body A hlvl tlvl hk tk -> list A -> list A)
  (_ : forall (A : Type) (hlvl tlvl nc : ckind) (nk : nkind),
       packet A hlvl tlvl nc nk -> list A -> list A)
  (chain_seq : forall (A : Type) (lvl ck : ckind) (nk : nkind),
               chain A lvl ck nk -> list A)
  (A : Type) (hlvl tlvl : ckind) (hk tk : nkind) (b : body A hlvl tlvl hk tk)
  (l : list A) =>
match b with
| Hole => fun l0 : list A => l0
| @Single_child _ hlvl0 tlvl0 hk0 tk0 n b0 =>
    fun l0 : list A =>
    concat_map_node'_seq stored_triple_seq n (body_seq A (S hlvl0) tlvl0 only tk0 b0 l0)
| @Pair_yellow _ hlvl0 tlvl0 hk0 tk0 n b0 c =>
    fun l0 : list A =>
    concat_map_node'_seq stored_triple_seq n
      (body_seq A (S hlvl0) tlvl0 left tk0 b0 l0 ++ chain_seq A (S hlvl0) 1 right c)
| @Pair_orange _ hlvl0 tlvl0 hk0 tk0 n c b0 =>
    fun l0 : list A =>
    concat_map_node'_seq stored_triple_seq n
      (chain_seq A (S hlvl0) 1 left c ++ body_seq A (S hlvl0) tlvl0 right tk0 b0 l0)
end l.

Definition packet_seq_functional :=
  fun (stored_triple_seq : forall (A : Type) (lvl : ckind), stored_triple A lvl -> list A)
  (body_seq : forall (A : Type) (hlvl tlvl : ckind) (hk tk : nkind),
              body A hlvl tlvl hk tk -> list A -> list A)
  (_ : forall (A : Type) (hlvl tlvl nc : ckind) (nk : nkind),
       packet A hlvl tlvl nc nk -> list A -> list A)
  (_ : forall (A : Type) (lvl ck : ckind) (nk : nkind),
       chain A lvl ck nk -> list A)
  (A : Type) (hlvl tlvl nc : ckind) (nk : nkind) (p : packet A hlvl tlvl nc nk)
  (l : list A) =>
match p with
| @Packet _ hlvl0 tlvl0 nc0 hk tk b n =>
    fun l0 : list A => body_seq A hlvl0 tlvl0 hk tk b (concat_map_node'_seq stored_triple_seq n l0)
end l.

Definition chain_seq_functional :=
fun (_ : forall (A : Type) (lvl : ckind), stored_triple A lvl -> list A)
  (_ : forall (A : Type) (hlvl tlvl : ckind) (hk tk : nkind), body A hlvl tlvl hk tk -> list A -> list A)
  (packet_seq : forall (A : Type) (hlvl tlvl nc : ckind) (nk : nkind),
                packet A hlvl tlvl nc nk -> list A -> list A)
  (chain_seq : forall (A : Type) (lvl ck : ckind) (nk : nkind),
               chain A lvl ck nk -> list A)
  (A : Type) (lvl ck : ckind) (nk : nkind) (c : chain A lvl ck nk) =>
match c with
| Empty => nil
| @Single _ hlvl tlvl ck0 nk0 p c0 =>
    packet_seq A hlvl tlvl ck0 nk0 p (chain_seq A (S tlvl) ck0 only c0)
| @Pair _ lvl0 c0 c1 =>
    chain_seq A lvl0 1 left c0 ++ chain_seq A lvl0 1 right c1
end.

(* 23 seconds on my machine *)
Time Definition slow_fix :=
  fix stored_triple_seq (A : Type) (lvl : ckind) (st : stored_triple A lvl) {struct st} : list A :=
    stored_triple_seq_functional stored_triple_seq body_seq packet_seq chain_seq A lvl st
  with body_seq
    (A : Type) (hlvl tlvl : ckind) (hk tk : nkind) (b : body A hlvl tlvl hk tk) (l : list A) {struct b} :
      list A :=
    body_seq_functional stored_triple_seq body_seq packet_seq chain_seq A hlvl tlvl hk tk b l
  with packet_seq
    (A : Type) (hlvl tlvl nc : ckind) (nk : nkind) (p : packet A hlvl tlvl nc nk)
    (l : list A) {struct p} : list A :=
    packet_seq_functional stored_triple_seq body_seq packet_seq chain_seq A hlvl tlvl nc nk p l
  with chain_seq
    (A : Type) (lvl ck : ckind) (nk : nkind) (c : chain A lvl ck nk) {struct c} :
      list A :=
    chain_seq_functional stored_triple_seq body_seq packet_seq chain_seq A lvl ck nk c
  for
  chain_seq.
```

### Version of Rocq / Coq where this bug occurs

_No response_

### Interface of Rocq / Coq where this bug occurs

_No response_

### Last version of Rocq / Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by ppedrot**
This representation prevents an exponential blowup when nesting inductive types. It makes guard checking basically instantaneous on some examples that used to take about 30s.

Fixes #19650: Taking a long time to type check inductive types
Fixes #21526: Slow fixpoint type-checking due to the guard condition.

### CODE REVIEW

**Comment by ppedrot** [comment]
I am leaving this as needs: progress because I think we should probably store the automaton directly next to the rtree in the inductive block rather than recomputing it on the fly, but I first want to assess the effects on a CI / bench.

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Biggest vo size increases (sorted by % then absolute) are
~~~
coq-compcert/./cparser/Cabs.vo 64562 75120 10558 16%
rocq-metarocq-safechecker/./safechecker/theories/PCUICSafeReduce.vo 3255391 3300458 45067 1%
coq-fiat-parsers/./src/Parsers/MinimalParse.vo 25443 25834 391 1%
rocq-metarocq-template/./template-rocq/theories/Normal.vo 25895 26263 368 1%
coq-compcert/./cfrontend/Csyntax.vo 28288 28643 355 1%
coq-fiat-crypto-with-bedrock/./src/Util/Strings/String_as_OT_old.vo 4826 4880 54 1%
rocq-core/./_build/default/theories/Corelib/Floats/FloatClass.vo 1689 1709 20 1%
~~~
(then a bunch of 0% increases)

**Comment by SkySkimmer** [comment]
hott and perf tests failed because of network errors AFAICT

File: kernel/inductive.ml [hunk 1]
```diff
@@ -1726,7 +1766,7 @@ let check_fix_pre_sorts ?evars env ((nvect, _), (names, _, bodies as recdef) as
     if flags.check_guarded then
       let get_tree (kn,i) =
         let mib = Environ.lookup_mind kn env in
-        mib.mind_packets.(i).mind_recargs
+        WfPaths.make mib.mind_packets.(i).mind_automaton
```
Comment (yannl35133) [inline kernel/inductive.ml]: This should be unified with `lookup_subterms`.

File: kernel/inductive.ml
Comment (yannl35133) [inline kernel/inductive.ml:966]: This ought to be moved to `WfPaths`.

File: kernel/inductive.ml [hunk 2]
```diff
@@ -798,12 +851,7 @@ let lift1_stack = lift_stack 1
 
 let lookup_subterms env ind =
   let (_,mip) = lookup_mind_specif env ind in
-  mip.mind_recargs
-
-let match_inductive ind ra =
-  match ra with
-    | Mrec (RecArgInd i) -> Ind.CanOrd.equal ind i
-    | Norec | Mrec (RecArgPrim _) -> false
+  WfPaths.make mip.mind_automaton
```
Comment (yannl35133) [inline kernel/inductive.ml:852]: This should be moved to `WfPaths`.

File: kernel/inductive.ml [hunk 3]
```diff
@@ -664,27 +664,80 @@ let size_glb s1 s2 =
...
+| Norec, Norec -> Norec
+| (Norec, Mrec _) | (Mrec _, Norec) -> Norec
 
-let is_norec_path t = match Rtree.dest_head t with
+let inter t1 t2 =
+  let automaton = Atm.inter meet_recarg t1 t2 in
+  if automaton == t1 then t1 else Atm.compact compare_recarg automaton
+
+let restrict t p =
+  let automaton = Atm.inter meet_recarg t (make0 p) in
```
Comment (yannl35133) [inline kernel/inductive.ml]: Inline `make0` if it's the only call site? Also are two calls to compact faster than one here?

File: kernel/declareops.ml [hunk 4]
```diff
@@ -158,6 +158,18 @@ let eq_recarg r1 r2 = match r1, r2 with
 | Mrec t1, Mrec t2 -> eq_recarg_type t1 t2
 | Mrec _, _ -> false
 
+let compare_recarg_type t1 t2 = match t1, t2 with
+| RecArgInd ind1, RecArgInd ind2 -> Names.Ind.UserOrd.compare ind1 ind2
+| RecArgInd _, RecArgPrim _ -> -1
+| RecArgPrim c1, RecArgPrim c2 -> Names.Constant.UserOrd.compare c1 c2
+| RecArgPrim _, RecArgInd _ -> 1
```
Comment (yannl35133) [inline kernel/declareops.ml]: Why UserOrd?

File: kernel/rtree.mli [hunk 5]
```diff
@@ -109,3 +109,42 @@ val kind : 'a t -> 'a kind
...
+(** Get the data associated to a given state in the automaton *)
+val data : 'a t -> state -> 'a
+
+(** Get the transitions of the automaton from a given state *)
+val transitions : 'a t -> state -> state array array
+
+(** Move the automaton into the given state *)
+val move : 'a t -> state -> 'a t
+
+(** Given a comparison function on the data, produce a minimal automata *)
```
Comment (yannl35133) [inline kernel/rtree.mli]:
```suggestion
(** Given a comparison function on the data, produce a minimal automaton *)
```

File: kernel/rtree.mli [hunk 6]
```diff
@@ -109,3 +109,42 @@ val kind : 'a t -> 'a kind
...
+val compact  : ('a -> 'a -> int) -> 'a t -> 'a t
+
+(** Intersection of two automata given an intersection on data. Does not
+    produce a minimal automata on general. *)
```
Comment (yannl35133) [inline kernel/rtree.mli]:
```suggestion
    produce a minimal automaton on general. *)
```

**Review by yannl35133 — COMMENTED** [review]
I didn't review changes in rtree.ml or anything in hopcroft.ml{,i}.

File: kernel/inductive.ml [hunk 7]
```diff
@@ -664,27 +664,80 @@ let size_glb s1 s2 =
...
+  Atm.compact compare_recarg automaton
```
Comment (yannl35133) [inline kernel/inductive.ml:702]: Why does this not have the same fastpath as `inter`?

Comment (ppedrot) [reply kernel/inductive.ml:702]: Because it's trivially false.

File: kernel/inductive.ml
Comment (ppedrot) [reply kernel/inductive.ml:966]: I'm leaving this WfPaths tweak (and the one below) to an optional latter PR, especially given that you're going to remove the cache in your clean up PR.

File: kernel/inductive.ml (hunk 2 above)
Comment (ppedrot) [reply kernel/inductive.ml:852]: See above.

**Comment by ppedrot** [comment]
@yannl35133 I consider this ready.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now
