### PR TITLE
Fix #6323: stronger restrict universe context vs abstract.

### LINKED ISSUE #6323: Coq master broke fiat-crypto in the past couple of days
#### Version

423b7298535c88b14926e92a8763420c69f89f6d

#### Operating system

Linux

#### Description of the problem

This works fine in 8.7.0, breaks in current master, and I believe it was working on December 1:
```coq
Goal True.
  simple refine (let feBW_tight' : Type := _ in _);
    [ abstract exact Set using Set'
    | let feBW_tight := (eval cbv delta [feBW_tight'] in feBW_tight') in
      clear feBW_tight';
      simple refine (let id' : { x : feBW_tight | True } -> feBW_tight := _ in _);
      [ abstract refine (@proj1_sig _ _) | ]
    ].
  (* Error: Illegal application:
The term "sig" of type "forall A : Type, (A -> Prop) -> Type"
cannot be applied to the terms
 "Set'" : "Type"
 "fun _ : Set' => True" : "Set' -> Prop"
The 1st term has type "Type@{Top.1}" which should be coercible to
 "Type@{Coq.Init.Specif.1}". *)
```

Dropping either `abstract` makes the issue go away.  I should be able to adjust the lite target to test the file that this occurred in; when this is fixed, I can merge https://github.com/mit-plv/fiat-crypto/pull/279 .

### PR DESCRIPTION
**Pull request by SkySkimmer**
In the test we do [let X : Type@{i} := Set in ...] with Set
abstracted. The constraint [Set < i] was lost in the abstract.

We keep track in the UState of which universes are used in side
effects (and so should not be restricted away).

### CODE REVIEW

**Comment by SkySkimmer** [comment]
This doesn't quite work, I get phantom universes in HoTT again.

**Comment by SkySkimmer** [comment]
Take 2, attempting to be smarter: keep track in the ustate of which universes shouldn't be restricted because they appear through private constants.
Not sure how much this makes sense.

**Comment by ejgallego** [comment]
Ummm, I need some time to think about this, at a first glance I'd say that we should indeed go in the opposite direction, but however that could perfectly be a naïve wish from my part.

**Comment by SkySkimmer** [comment]
New approach which I feel is more principled: universes_of_constr includes the universes of monomorphic constants appearing in the term.

Old approach with recording side-effect universes in UState is at https://github.com/SkySkimmer/coq/tree/fix-6323-restrict%2Babstract-alt (da31b40).

File: proofs/proof_global.ml [hunk 1]
```diff
@@ -348,21 +348,17 @@ let close_proof ~keep_body_ucst_separate ?feedback_id ~now
 	    nf t
 	  else t
         in
-        let used_univs_body = Univops.universes_of_constr body in
-        let used_univs_typ = Univops.universes_of_constr typ in
-        (* Universes for private constants are relevant to the body *)
-        let used_univs_body =
-          List.fold_left (fun acc (us,_) -> Univ.LSet.union acc us)
-            used_univs_body (Safe_typing.universes_of_private eff)
-        in
```
Comment (SkySkimmer) [inline proofs/proof_global.ml]: This universes_of_private call is now redundant and thus removed.

**Comment by mattam82** [comment]
@SkySkimmer yes, that seems absolutely right. I had a similar issue where universes in evars were previously not recorded in universes_of_constr in #890 (leading to a new evar-aware universes_of_constr), so your extension seems only right.

File: engine/eConstr.ml [hunk 2]
```diff
@@ -645,11 +645,19 @@ let eq_constr_universes_proj env sigma m n =
...
-    | Const (_, u) | Ind (_, u) | Construct (_, u) ->
+    | Const (c, u) ->
+      let open Declarations in
+      begin match (Environ.lookup_constant c env).const_universes with
+        | Polymorphic_const _ ->
+          LSet.fold LSet.add (Instance.levels (EInstance.kind sigma u)) s
+        | Monomorphic_const (univs, _) ->
+          LSet.union s univs
+      end
+    | Ind (_, u) | Construct (_, u) ->
```
Comment (mattam82) [inline engine/eConstr.ml]: Are we sure we don't need to do the same for the inductives here?

**Review by mattam82 — APPROVED** [review]
Apart from my comment, the patch looks good to me.

File: engine/eConstr.ml (hunk 2 above)
Comment (SkySkimmer) [reply engine/eConstr.ml]: I don't know if there's currently a possibility of building an inductive by tactic to make Coq fail if we don't, but we should do it for sanity's sake.

Comment (SkySkimmer) [reply engine/eConstr.ml]: Fixed.

**Comment by mattam82** [comment]
Good. Would be curious to see if this has a performance impact, we might be doing a whole lot more unions of LSets now.

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/248/

Gaëtan Gilbert

**Comment by SkySkimmer** [comment]
Equations is broken.

**Comment by SkySkimmer** [comment]
https://github.com/mattam82/Coq-Equations/pull/33

**Comment by SkySkimmer** [comment]
```
INFO: the following OPAM-packages:
- coq-fiat-crypto
- coq-formal-topology
- coq-hott
- coq-sf-vfa
cannot be installed

┌──────────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │             CPU cycles              │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                     │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 3077.29 3096.36 -0.62 % │ 8585795456123 8636960127043 -0.59 % │ 14342863417083 14319896345550 +0.16 % │ 1216108 1251848 -2.85 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   75.26   75.55 -0.38 % │  209796337992  209750893096 +0.02 % │   287475937167   286185865821 +0.45 % │  530816  530992 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  450.60  451.50 -0.20 % │ 1253984094951 1255233978272 -0.10 % │  2098332349793  2094293639030 +0.19 % │  730244  727856 +0.33 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  191.20  191.33 -0.07 % │  531270366366  531523406408 -0.05 % │   773469239492   770887016409 +0.33 % │  715696  717428 -0.24 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-color │  567.11  567.37 -0.05 % │ 1587140034667 1585583402019 +0.10 % │  2015502882557  2006916329308 +0.43 % │ 1482184 1487624 -0.37 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  169.98  170.05 -0.04 % │  472178740513  471710896342 +0.10 % │   672553726459   668780616995 +0.56 % │  597264  590360 +1.17 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   59.55   59.56 -0.02 % │  165137150053  164722202308 +0.25 % │   231889452894   230481167841 +0.61 % │  530668  530064 +0.11 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │   58.34   58.32 +0.03 % │  160460883140  159876565148 +0.37 % │   207032931734   205756198233 +0.62 % │  646180  651568 -0.83 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1368.28 1366.48 +0.13 % │ 3808985685385 3805989658892 +0.08 % │  6718400797326  6699857495631 +0.28 % │ 1110948 1206280 -7.90 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  266.09  265.54 +0.21 % │  740743135558  739195376175 +0.21 % │  1097097357961  1091173593859 +0.54 % │  982460  982716 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  813.72  811.88 +0.23 % │ 2266732055972 2262412978107 +0.19 % │  3431713646576  3413001399879 +0.55 % │ 1389404 1389612 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  167.59  167.17 +0.25 % │  465617700218  464997510396 +0.13 % │   714993181651   712248227115 +0.39 % │  729940  730832 -0.12 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-vst │ 2153.94 2146.96 +0.33 % │ 6005104401455 5989263854477 +0.26 % │  8832411568174  8783226815463 +0.56 % │ 1952744 1950708 +0.10 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  119.14  118.51 +0.53 % │  312889965858  311567550493 +0.42 % │   420681795503   417676045031 +0.72 % │  501832  502960 -0.22 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-unimath │ 1280.71 1270.02 +0.84 % │ 3567610215806 3540005090784 +0.78 % │  6185746922233  6110243999838 +1.24 % │ 1152452 1075340 +7.17 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   38.86   38.51 +0.91 % │  106785245965  106200326342 +0.55 % │   133097561976   132195064728 +0.68 % │  480272  477380 +0.61 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  677.40  669.91 +1.12 % │ 1872064890993 1854504349474 +0.95 % │  3038107725276  3011846206458 +0.87 % │ 3519396 3514084 +0.15 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coquelicot │   74.86   74.03 +1.12 % │  206351521929  203245949075 +1.53 % │   260620480593   254160709078 +2.54 % │  659900  658920 +0.15 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-sf-plf │   42.01   41.27 +1.79 % │  117230762537  114824176432 +2.10 % │   154914169415   150148922669 +3.17 % │  517120  506612 +2.07 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-sf-lf │   15.84   14.79 +7.10 % │   43031499401   40659389644 +5.83 % │    60277292832    55899762830 +7.83 % │  417748  423624 -1.39 % │   0   0  +nan % │
└──────────────────────────┴─────────────────────────┴─────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘


```

**Comment by mattam82** [comment]
+1 on fiat-parsers and -0.62 on geocoq, I wonder if that’s meaningful. A priori hott is not impacted, right? If so it’s all green for me.

**Comment by SkySkimmer** [comment]
Travis failed compcert because of master, and iris timed out.
My own travis succeeded https://travis-ci.org/SkySkimmer/coq/builds/312423630

**Comment by maximedenes** [comment]
> I need some time to think about this

@ejgallego do you need more time?

**Comment by maximedenes** [comment]
> @ejgallego do you need more time?

@ejgallego ping

**Comment by ejgallego** [comment]
Sad to see "side-effects" cropping up more and more in the code, but unfortunately I don't have any constructive suggestion today.

**Comment by maximedenes** [comment]
Iris timed out on this one. I hope it is a coincidence.
