### PR TITLE
Fix #6621: Anomaly on fixpoint with primitive projections

### LINKED ISSUE #6621: Anomaly on fixpoint with primitive projections
```coq
Set Primitive Projections.

Axiom positive : Set.
Axiom xH : positive.
Inductive Z : Set := pos : positive -> Z.

Record Q : Set := Qmake { Qnum : Z }.

Record Qc : Set := Qcmake { this :> Q ; }.

Definition Q2Qc (q:Q) : Qc := Qcmake q.

Axiom pmul : positive -> positive -> positive.

Definition Zmul x y :=
  match x, y with
    | pos x', pos y' => pos (pmul x' y')
  end.

Definition Qmult := fun x y : Q => Qmake (Zmul (Qnum x) (Qnum y)) .

Notation Q1 := {| Qnum := pos xH |}.

Definition Qcmult (x y : Qc) := Q2Qc (Qmult x y).
Infix "*" := Qcmult.

Fixpoint Qcpower (q:Qc) (n:nat) {struct q} : Qc :=
  match n with
    | O => Q2Qc Q1
    | S n => q * (Qcpower q n)
  end.
(* Error:
Anomaly
"File "kernel/declareops.ml", line 211, characters 2-8: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
*)
```
https://github.com/coq/coq/blob/9aa2464375c1515aa64df7dc910e2f324e34c82f/kernel/declareops.ml#L172

This is related to and possibly fixed by #407. It is present in 8.7.

### PR DESCRIPTION
**Pull request by maximedenes**
The implementation of the subterm relation for primitive projections was
a bit wrong. I found the problem independently of this bug, and tried to
see if a proof of False could be derived, but I don't think so, due to
another check (check_is_subterm) that saves the kernel at the last
minute.

### CODE REVIEW

**Comment by mattam82** [comment]
Fits perfectly my slide "Trouble with the Guard Condition" at the TYPES meeting. Darn. LGTM, of course we should follow the allowed recursive calls only. I suppose it's check_subterm that disallows the obvious attempt of defining a non-terminating fixpoint through impredicativity?

**Comment by maximedenes** [comment]
:) Yeah, I added a check in `check_is_subterm` a while ago, following a recommendation of Bruno. It checks if the subterm value of the resulting subterm contains the one of the original argument of the fixpoint. And indeed, it is what saves the day on the following example:

```
Set Implicit Arguments.
Set Primitive Projections.

Inductive C : Prop :=
  wrap { unwrap : forall P : Prop, P -> P }.

Fixpoint foo (c : C) {struct c} : False :=
  foo (c.(unwrap) c).
```

**Comment by maximedenes** [comment]
I have the feeling that `dest_subterms` could be changed to cut non allowed subtrees (returning a specif instead of a tree).

But I'd rather invest my time working on type based termination later than do more local fixes now.

**Comment by maximedenes** [comment]
It seems that the checker doesn't have a subterm relation for primitive projections btw, I'll try to fix that.

File: kernel/inductive.ml [hunk 1]
```diff
@@ -797,17 +797,17 @@ let rec subterm_specif renv stack t =
...
-	   let wf_args = (dest_subterms wf).(0) in
-	   (* We extract the tree of the projected argument *)
-	   let kn = Projection.constant p in
-	   let cb = lookup_constant kn renv.env in
-	   let pb = Option.get cb.const_proj in
-	   let n = pb.proj_arg in
-	   Subterm (Strict, List.nth wf_args n)
-	| Dead_code -> Dead_code
-	| Not_subterm -> Not_subterm)
+  | Subterm (s, wf) ->
```
Comment (SkySkimmer) [inline kernel/inductive.ml]: Indentation is too small.
I think if you remove the tab from line 799 automatic indentation should work.

Comment (maximedenes) [reply kernel/inductive.ml]: Thanks, I was waiting for a hint from you :)

**Comment by maximedenes** [comment]
@mattam82 Can you approve this PR? :)

**Comment by maximedenes** [comment]
@mattam82 ping

**Comment by maximedenes** [comment]
@mattam82 ping ping :)

**Review by mattam82 — APPROVED** [review]
