### PR TITLE
Fix Windows 32 bit build

### LINKED ISSUE #11176: Windows 32 bit build is broken since native floats were added
Since #9867 , the windows build for 32bit is broken, example:
https://coq.gitlab.io/-/coq/-/jobs/359738453/artifacts/artifacts/buildlogs/coq-local-configure_err.txt
```
Detected non IEEE-754 compliant architecture (or wrong rounding mode). Use of Float is thus unsafe.
Configuration script failed!
```
this seems like a blocker bug for 8.11

### PR DESCRIPTION
**Pull request by proux01**
Fixes #11176

### CODE REVIEW

**Comment by proux01** [comment]
@ejgallego or @Zimmi48 could one of you launch the Windows 32 bit build to ensure this fixes it?

**Comment by SkySkimmer** [comment]
>@ejgallego or @Zimmi48 could one of you launch the Windows 32 bit build to ensure this fixes it?

I think the easiest way is for you to add a commit removing these 2 lines https://github.com/coq/coq/blob/0e9cd0fe99216bc09a09a0da6906f9501b682223/.gitlab-ci.yml#L304-L305
Then after the test has run remove the commit.

**Comment by proux01** [comment]
Thanks @SkySkimmer !

File: configure.ml [hunk 1]
```diff
@@ -924,9 +924,9 @@ let cflags_sse2 = ["-msse2"; "-mfpmath=sse"]
 let cflags, sse2_math =
   let _, slurp =
     (* Test SSE2_MATH support <https://stackoverflow.com/a/45667927> *)
-    tryrun "cc" (["-march=native"; "-dM"; "-E"]
-                 @ cflags_sse2
-                 @ [coqtop/"kernel/byterun/coq_interp.h"] (* any file *)) in
+    tryrun "gcc" (["-march=native"; "-dM"; "-E"]
```
Comment (JasonGross) [inline configure.ml]: Does this mean that Coq will not support clang/icc/msvc?  Or that configure will be out of sync when using those compilers?  Or was configure previously out of sync and we always use gcc?

Comment (proux01) [reply configure.ml]: Weren't we already not supporting other compilers than gcc (due to the VM)?

**Comment by proux01** [comment]
The windows build seem stalled (still pending for 17 hours)

**Comment by silene** [comment]
I don't think we should be testing `cc` or `gcc`. We should be using the same compiler as will be used later, that is, `ocamlfind ocamlc -ccopt $CFLAGS -c ...`.

**Comment by erikmd** [comment]
Thanks @silene ! your suggestion works smoothly:

`ocamlfind ocamlc -ccopt "-march=native -dM -E -msse2 -mfpmath=sse" -c kernel/byterun/coq_interp.c | grep "#define __SSE_MATH__ 1"`

(I let Pierre do the commit)

I just needed to replace `kernel/byterun/coq_interp.h` with `kernel/byterun/coq_interp.c` otherwise we'd get "don't know what to do with kernel/byterun/coq_interp.h"

File: configure.ml [hunk 2]
```diff
@@ -924,7 +924,8 @@ let cflags_sse2 = ["-msse2"; "-mfpmath=sse"]
 let cflags, sse2_math =
   let _, slurp =
     (* Test SSE2_MATH support <https://stackoverflow.com/a/45667927> *)
-    tryrun "cc" (["-march=native"; "-dM"; "-E"]
+    let cc = try which "cc" with Not_found -> "gcc" in
+    tryrun cc (["-march=native"; "-dM"; "-E"]
                  @ cflags_sse2
                  @ [coqtop/"kernel/byterun/coq_interp.h"] (* any file *)) in
```
Comment (SkySkimmer) [inline configure.ml]: In the stackoverflow link they use an empty stdin, can't we do that instead of doing some compilation in configure?
Or at least compile some dummy instead of something that looks like a real target.

**Comment by erikmd** [comment]
Yes, but it was simpler to implement with a dummy existing file, given option -E is:

```
-E 
Stop after the preprocessing stage; do not run the compiler proper. The output is in the form of preprocessed source code, which is sent to the standard output. 
```

File: configure.ml (hunk 2 above)
Comment (erikmd) [reply configure.ml]: Yes, but it was simpler to implement with a dummy existing file, given option -E is:

``` -E Stop after the preprocessing stage; do not run the compiler proper. The output is in the form of preprocessed source code, which is sent to the standard output. 
```

Comment (erikmd) [reply configure.ml]: (otherwise another possible choice for the dummy C file would be `dev/header.c`)

**Comment by proux01** [comment]
> `ocamlfind ocamlc -ccopt $CFLAGS -c ...`.

We were ashamed we couldn't easily retrieve the compiler command used by ocaml. This is obviously the way to go thanks.

Implementation unfortunately required to duplicate the `-ccopt` options but this should still be equivalent to the command launched by the Makefile. Tested on linux, windows32 and windows64; let's wait for the CI.

**Comment by proux01** [comment]
@coq/ci-maintainers gitlab says about windows jobs "This job is stuck because you don't have any active runners online with any of these tags assigned to them: windows" (e.g. : https://gitlab.com/coq/coq/-/jobs/361566683 ), is that expected?

**Comment by silene** [comment]
There is one runner with that tag, namely `INRIACI-trusted`, but since there are about 20 jobs currently waiting for this runner to become available, I wonder if Gitlab does not tentatively mark it as "stuck" rather than just "pending".

File: configure.ml [hunk 3]
```diff
@@ -919,16 +919,19 @@ let datadir,datadirsuffix = let (_,_,d,s) = select "DATADIR" in d,s
...
 let cflags, sse2_math =
   let _, slurp =
     (* Test SSE2_MATH support <https://stackoverflow.com/a/45667927> *)
-    tryrun "cc" (["-march=native"; "-dM"; "-E"]
-                 @ cflags_sse2
-                 @ [coqtop/"kernel/byterun/coq_interp.h"] (* any file *)) in
+    tryrun camlexec.find
+      (["ocamlc"]
+       @ List.fold_right (fun o l -> "-ccopt" :: o :: l)
+           (String.split_on_char ' '
```
Comment (silene) [inline configure.ml]: Note that you can pass all the options at once to `-ccopt`. In other words, `["ocamlc"; "-ccopt"; (cflags_dflt ^ " -march=native -dM -E " ^ cflags_sse2); "-c"; ...]` should be fine. No need to split `CFLAGS` and duplicate `-ccopt`.

Comment (proux01) [reply configure.ml]: That's the first thing I tried. Unfortunately, as I said above, it didn't work (the C compiler was receiving `native -dM -E`... as a single argument for `march`, don't know what happened to the spaces, I didn't investigate further as duplicating `-ccopt` sounded like a reasonnable fix).

Comment (silene) [reply configure.ml]: Oh, I hadn't understood what you meant by "to duplicate the `-ccopt` options" (despite both of us using the exact same terminology). That is quite mindboggling that it works from command line and `Makefile` but does not from `configure.ml`.

Comment (proux01) [reply configure.ml]: Maybe `Unix.create_process` is replacing spaces by unbreakable spaces or something like that. I don't know precisely.

Comment (SkySkimmer) [reply configure.ml]: That's strange, when I try eg `Unix.create_process "ocamlfind" [|"ocamlfind";"ocamlc";"-ccopt";"-march=native -dM -E";"-c";"dev/header.c"|] Unix.stdin Unix.stdout Unix.stderr` it works fine

Comment (proux01) [reply configure.ml]: Indeed, my mistake was to try to protect the argument with `"` or `'` (i.e. using
```OCaml
Unix.create_process "ocamlfind" [|"ocamlfind";"ocamlc";"-ccopt";"\"-march=native -dM -E\"";"-c";"dev/header.c"|] Unix.stdin Unix.stdout Unix.stderr
```
instead of what you offers). Thanks to both of you and sorry for all the noise!

**Review by ejgallego — APPROVED** [review]
LGTM thanks, please drop the CI commit and I'll merge.

**Comment by proux01** [comment]
Done, thanks!
