### PR TITLE
Pass the genargs from the tactic closure to uconstr interpretation.

### LINKED ISSUE #15177: Incorrect closure of uconstr
When interleaving tactic quotations with uconstr interpretation, the closure is not computed correctly leading to weird unbound variable errors.

Small example:
```
Ltac foo :=
match goal with
| [ x : ?T |- _ ] => refine (ltac:(exact x))
end.

Goal nat -> nat.
Proof.
intros n.
foo.
Qed.
```

### PR DESCRIPTION
**Pull request by ppedrot**
Fixes #15177: Incorrect closure of uconstr.

### CODE REVIEW

File: plugins/ltac/tacinterp.ml [hunk 1]
```diff
@@ -1079,7 +1079,7 @@ let type_uconstr ?(flags = (constr_flags ()))
     ltac_constrs = closure.typed;
     ltac_uconstrs = closure.untyped;
     ltac_idents = closure.idents;
-    ltac_genargs = Id.Map.empty;
+    ltac_genargs = closure.genargs;
```
Comment (SkySkimmer) [inline plugins/ltac/tacinterp.ml:1082]: https://github.com/coq/coq/blob/1a57401e2249e7c824d04afa0b3a169ee72c45fd/plugins/ltac/tacinterp.ml#L602 should be changed too?

File: pretyping/ltac_pretype.ml [hunk 2]
```diff
@@ -46,7 +46,8 @@ type extended_patvar_map = constr_under_binders Id.Map.t
 type closure = {
   idents:Id.t Id.Map.t;
   typed: constr_under_binders Id.Map.t ;
-  untyped:closed_glob_constr Id.Map.t }
+  untyped:closed_glob_constr Id.Map.t;
+  genargs : Geninterp.Val.t Id.Map.t; }
```
Comment (SkySkimmer) [inline pretyping/ltac_pretype.ml:50]: This type is now the same as `ltac_var_map` below, is it useful to have both?

File: plugins/ltac/tacinterp.ml (hunk 1 above)
Comment (ppedrot) [reply plugins/ltac/tacinterp.ml:1082]: No, the `ist.lfun` and the value returned in the closure by `extract_ltac_constr_context` coincide. I guess we should have an API that enforces this statically but this would require a bit of refactorization.

File: pretyping/ltac_pretype.ml (hunk 2 above)
Comment (ppedrot) [reply pretyping/ltac_pretype.ml:50]: I think that one of two should be made opaque and abstract away the implementation details of the classification of variables. For the time being I guess it does not hurt to keep both. (Also there is a nasty recursive type going on, I think it's better to have a toplevel type exporting a non-recursive definition.)

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
Judging from the error message, the fcl failure looks like a bug on their side. It was likely working by mistake before, because there was probably a variable shadowing with something that was not an identifier that is now clashing because the closure is preserved through antiquotations...

**Comment by ppedrot** [comment]
Here is a minimal example showcasing the problematic behaviour described above:
```
Goal True -> True.
Proof.
match goal with
| [ |- ?T ] =>
  refine (ltac:(refine (fun T => T)))
end. (* Fails with this PR, works on master *)
Qed.
```

**Comment by ppedrot** [comment]
I think that the problem is here:  https://github.com/mit-plv/fiat-crypto/blob/f21620034db2addaf47f85aded49b8c0f183ac26/src/Compilers/InterpRewriting.v#L120

The variable `e` is bound to a term by the lazymatch, but it clashes with the bound Gallina variable from the refine. Before the closure was dropped so there was no clash, but now it does not work anymore. cc @JasonGross

**Comment by JasonGross** [comment]
We try not to depend on generated names, so it should be safe to rename either of the `e`s to `e'`.

**Comment by herbelin** [comment]
Is that correct that what was missing the "genargs" (should it be better called it "lfun" or "full_lfun"?) was the [eval_tactic_ist](https://github.com/coq/coq/blob/1a57401e2249e7c824d04afa0b3a169ee72c45fd/plugins/ltac/tacinterp.ml#L2175) used in registering the `ltac` quotation in terms? By the way, why is `ltac:` bound to a `wit_tactic`; shouldn't it be called e.g. `wit_ltac_constr` on the model of `wit_ltac2_constr`?

**Comment by ppedrot** [comment]
> Is that correct that what was missing the "genargs" was the eval_tactic_ist

Indirectly, yes.

> By the way, why is ltac: bound to a wit_tactic; shouldn't it be called e.g. wit_ltac_constr

We don't care, we only use this to reuse a genarg that has the right glob type, but the interpretation function is not used. So it does not really make sense to introduce a new genarg for that. (It's used elsewhere for real tactic interpretation.)

**Comment by SkySkimmer** [comment]
@JasonGross please interrupt the minimizer

**Review by SkySkimmer — APPROVED** [review]
I'm still not convinced about duplicating the `closure` type but it doesn't matter.

**Comment by SkySkimmer** [comment]
@coqbot merge now
