### PR TITLE
[dune] Add to vo rules explicit location of coqlib in boot mode.

### LINKED ISSUE #8862: Coq Dune-based build fails on current master
#### Version

master (0ac673e562c34245e4e48efc428d808e917be79b)

#### Operating system

macOS 10.14 (Mojave)

#### Description of the problem

This issue follows the discussion at coq-community/lemma-overloading#14

```shell
$ cat .git/HEAD
ref: refs/heads/master
$ cat .git/refs/heads/master
0ac673e562c34245e4e48efc428d808e917be79b
$ git clean -dfx
$ make -f Makefile.dune voboot
dune build  @vodeps
dune exec coq_dune _build/default/.vfiles.d
$ dune build -p coq -j2
      coqtop theories/Init/Decimal.vo
While loading initial state:
Warning:
Cannot open /Users/antontrunov/prj/coq/coq/_build/install/default/theories
[cannot-open-path,filesystem]
While loading initial state:
Warning:
Cannot open /Users/antontrunov/prj/coq/coq/_build/install/default/plugins
[cannot-open-path,filesystem]
      coqtop theories/Init/Notations.vo (exit 1)
(cd _build/default && ../install/default/bin/coqtop -boot -noinit -R theories Coq -compile theories/Init/Notations.v)
While loading initial state:
Warning:
Cannot open /Users/antontrunov/prj/coq/coq/_build/install/default/theories
[cannot-open-path,filesystem]
While loading initial state:
Warning:
Cannot open /Users/antontrunov/prj/coq/coq/_build/install/default/plugins
[cannot-open-path,filesystem]
File "./theories/Init/Notations.v", line 128, characters 0-32:
Error:
File not found on loadpath : ltac_plugin.cmxs
Loadpath: /Users/antontrunov/prj/coq/coq/_build/default
$ ls -l _build/install/bin
ls: cannot access '_build/install/bin': No such file or directory
```

CC @ejgallego

### PR DESCRIPTION
**Pull request by ejgallego**
When `-coqlib $PATH` is absent, Coq will try to locate coqlib using a
heuristic based on the name of the executable.

The code in `envars.ml` basically does:
```ocaml
Filename.(dirname CUnix.(canonical_path_name (dirname Sys.executable_name)))
```
which doesn't seem to work very well on Windows and OSX when `coqtop`
is a symlink.

Instead, we now pass the right `-coqlib` to coqtop from `coq_dune`.

Fixes #8862

### CODE REVIEW

**Comment by ejgallego** [comment]
@herbelin , @anton-trunov , please let me know if this fixes the Dune issues you were having.

**Comment by ejgallego** [comment]
By the way, I do consider the `-boot` flag deprecated, as I'd like the stdlib to be treated as a regular library.

File: tools/coq_dune.ml [hunk 1]
```diff
@@ -175,8 +175,10 @@ let pp_vo_dep dir fmt vo =
   let deps = List.map (fun s -> bpath [sdir;s]) (edep @ vo.deps) in
   (* The source file is also corrected as we will call coqtop from the top dir *)
   let source = bpath (dir @ [Filename.(remove_extension vo.target) ^ ".v"]) in
+  (* We explicitely include the location of coqlib to avoid tricky issues with coqlib location *)
```
Comment (Zimmi48) [inline tools/coq_dune.ml]:
```suggestion
  (* We explicitly include the location of coqlib to avoid tricky issues with coqlib location *)
```

**Review by Zimmi48 — APPROVED** [review]

**Comment by ejgallego** [comment]
Merci !
