### PR TITLE
CoqIDE: Fix not escaping coqtop arguments when compiling

### LINKED ISSUE #11595: `Compile -> Compile Buffer` in CoqIDE fails silently when file paths contain whitespaces or symlinks
#### Description of the problem
`Compile -> Compile Buffer` in CoqIDE fails silently when file paths contain whitespaces or symlinks.
IDE feedback: `Running: coqc -topfile \Users\CENSORED\Lab assignments\library.v -Q C:\Users\CENSORED\Lab assignments sv -w -notation-overridden,-parsing "\Users\CENCORED\Lab assignments\library.v" 2>&1`.
Issues:
 - The drive letter (`C:`) is missing in two of the three paths in the command. This seems to be only the case when the path contains a symlink (created on Windows 10 using the `mklink` command).
 - Two of the three paths are not quoted, causing whitespaces in the path to make `coqc` interpret each file path as multiple arguments.

Note that the mentioned file path is the path to the file that is opened with the CoqIDE, and not the CoqIDE itself.

When not going through symlinks and quoting the file paths, the command functions properly from Windows 10 command prompt.

#### Coq Version
Release 8.11.0.

### PR DESCRIPTION
**Pull request by snyke7**
**Kind:** Bug fix/feature.

Fixes #11595 

Fixes compilation failure when pressing 'Compile buffer', when the arguments to coqtop contain spaces. This happens, for example, when a _CoqProject file is loaded and contains the option `-R relativepath name` and the absolute path contains a space.

Ideally the coqtop arguments dialog screen should also accept arguments containing spaces, but that is not as easy. The arguments are presented concatenated by a space and then split by spaces when pressing okay. Not splitting when apostrophes are present is possible, but not a complete solution (escaped apostrophes!) and somewhat complex.

When running `make test-suite` I ran into some more problems caused by a path containing spaces. These were all relatively simple to fix, except for the misc tests containing scripts. Here it was necessary to replace `export coqc="$(coqc)"` with `export coqc="eval $(coqc)"`since `BIN='/absolute path'/bin/`, and so `coqc='/absolute path'/bin/coqc -q -R prerequisite TestSuite`. Note the apostrophes around absolute path: these cause `make` to work properly, but the shell scripts interpret these apostrophes literally. Putting eval in front makes it work again, and requires no changes in the individual shell scripts.

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in CHANGES.md.

### CODE REVIEW

File: configure.ml [hunk 1]
```diff
@@ -936,7 +936,7 @@ let config_runtime () =
   | Some flags -> string_split ',' flags
   | _ when use_custom -> [custom_flag]
   | _ when !prefs.local ->
-    ["-dllib";"-lcoqrun";"-dllpath";coqtop/"kernel/byterun"]
+    ["-dllib";"-lcoqrun";"-dllpath";("\"" ^ coqtop ^ "/kernel/byterun\"")]
```
Comment (ejgallego) [inline configure.ml]: Not an expert here, but you could maybe use `String.escape`?

**Review by ejgallego — COMMENTED** [review]
Not an expert here, I guess the changes are good.

Any takers more knowledgeable on this stuff ? @gares @SkySkimmer @MSoegtropIMC ?

**Comment by SkySkimmer** [comment]
Without testing in CI we will probably break it again someday
If nobody volunteers to write such a test I guess we can live with the possibility.

**Comment by ejgallego** [comment]
> If nobody volunteers to write such a test I guess we can live with the possibility.

I tried to write something like that, however I don't remember what happened; I likely thought that I'd rather port everything to Dune and never see a path again.

File: configure.ml (hunk 1 above)
Comment (snyke7) [reply configure.ml]: I didn't know about this function, but I don't think it would help here, since `String.escaped` does not escape spaces/enclose the string in literal double quotes. These literal quotes are needed to make sure that the printed dllpath appearing in `config/Makefile` is properly escaped.

**Comment by herbelin** [comment]
@snyke7: this PR apparently did not get the visibility it would have deserved and #11640 has been proposed in the meantime, with an explicit associated bug report #11595.

Your PR is more comprehensive and it seems natural to adopt it. I don't know if you are around at this time. A suggestion coming from #11640 is to use `Filename.quote` rather than simple quoting for the `args`. This seems apparently worth (but I'm not so expert, in particular with Windows filenames).

It is also clear that more semantics should be introduced in these string manipulations (and in particular in the treatment of coqtop arguments).

If you are around, please tell. If not, I propose to merge as is (with just a change so as to use `Filename.quote`).

@skyskimmer:
> Without testing in CI we will probably break it again someday
> If nobody volunteers to write such a test I guess we can live with the possibility.

I just renamed my coq working directory with a space in it. Let's see what happens...

**Comment by herbelin** [comment]
> I'm still around! Have just rebased and replaced my simple quoting with `Filename.quote`, that should indeed work better.

Great! And thanks. Unless someone wants to say something more, I'll merge tomorrow.

Later on, I will maybe make the string manipulation in coqtop arguments more robust.

PS: I edited the head message to tell that it fixes #11595, so that that report is automatically closed.

File: test-suite/Makefile [hunk 2]
```diff
@@ -33,10 +33,10 @@ include ../Makefile.common
 #######################################################################
 
 ifneq ($(wildcard ../_build),)
-BIN:=$(shell cd ..; pwd)/_build/install/default/bin/
-COQLIB:=$(shell cd ..; pwd)/_build/install/default/lib/coq
+BIN:='$(shell cd ..; pwd)'/_build/install/default/bin/
```
Comment (gares) [inline test-suite/Makefile]: I suggest defining a new variable, say ROOT, that includes the `'` and there write a comment explaining that it is a make thing and eval is necessary later to make it shell compatible.

File: configure.ml (hunk 1 above)
Comment (gares) [reply configure.ml]: Would Filename.quote work here?

**Comment by gares** [comment]
> What would be a good approach to write such a test?

dear @coq/ci-maintainers don't we run `make test` on windows? If so, would it be possible to run it in a directory containing a space?

**Comment by herbelin** [comment]
About the window for changing coqtop arguments, I propose to do the following in a different PR:
- we keep `coqtop.sup_args` stored unquoted;
- we minimally quote it before displaying the arguments in the window (i.e. calling `Filename.quote` if there is a character whose meaning is special in `Unix.open_process_in`, i.e. special in `sh`);
- we unquote it before storing it back to `coqtop.sup_args`, possibly failing if the user did not give a correctly quoted string.

Otherwise said:
- we implicitly define a relation between `string list` to `string` expressing that string `s` is a quoting of list `l`;
- this relation is total on `string list`, expressing the idea that the strings of the list are arbitrary and have no particular meaning (e.g. the ` `, `` '``, ``\``, ``$``, ... there have to be non-interpreted by the shell);
- this relation is however partial on `string`: some strings, such as `"foo b'ar"` are not correct quotings;
- we implement a minimally-quoting injection of `string list` to `string` (minimally so that it is nicer to see; compare to `Filename.quote` which is a maximally-quoting injection);
- we implement a decoding function on the image of the relation (which e.g. decodes `"foo 'bar\ bar\'bar'"` into `["foo";"bar bar'bar"]`).

File: test-suite/Makefile (hunk 2 above)
Comment (herbelin) [reply test-suite/Makefile]: @snyke7: I'll assume that you're ok with the suggestion of @gares and I'll push a commit implementing it, then merge tomorrow.

Thanks again for the fix!

**Comment by SkySkimmer** [comment]
>dear @coq/ci-maintainers don't we run make test on windows? If so, would it be possible to run it in a directory containing a space?

Probably, maybe @coq/windows-build-maintainers know more though

**Comment by ejgallego** [comment]
> Probably, maybe @coq/windows-build-maintainers know more though

We run the test suite both in Gitlab and appveyor.

**Comment by herbelin** [comment]
@snyke7: Note that I pushed to your branch a proposal for a change log item announcing that the bug is fixed. I used your github identifier name there.

**Comment by herbelin** [comment]
OK, thanks, will merge tonight.

**Comment by herbelin** [comment]
@ppedrot: I put the 8.11.1 milestone, don't know your opinion though.

**Review by herbelin — APPROVED** [review]
