### PR TITLE
Close files in fetch_delayed

### LINKED ISSUE #12192: New Library.Faulty anomalies.
#### Description of the problem

The Sphinx build is consistently failing *locally* for both @jfehrle and myself with the following error (I call Sphinx through `dune` and Jim does it through `make`):

```
reading sources... [ 49%] language/coq-library
Extension error:
/mnt/c/proj/coq2/doc/sphinx/language/coq-library.rst:899: Error while sending the following to coqtop:
    Require Import Reals.
  coqtop output:
    Toplevel input, characters 0-21:
    > Require Import Reals.
    > ^^^^^^^^^^^^^^^^^^^^^
    Error:
    Anomaly
    "Uncaught exception Library.Faulty("/mnt/c/proj/coq2/theories/ZArith/Zminmax.vo")."
    Please report at http://coq.inria.fr/bugs/.
```

Strangely enough, it succeeds in the CI.

Recently, @llelf reported on Gitter a similar problem when trying to build the dev version of the opam package on macOS:

https://gist.github.com/llelf/aece08801e5a13d8558053f3561d8838

The error is in another file:

```
# File "./theories/Reals/Rtrigo1.v", line 25, characters 0-27:
# Error:
# Anomaly
# "Uncaught exception Library.Faulty("/Users/lelf/.opam/cnr/.opam-switch/build/coq.dev/_build/default/theories/Logic/Classical_Pred_Type.vo")."
# Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version

This is on an up-to-date master and is apparently a consequence of #12092 (that was merged two days ago).

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #12192

Also removed transforming arbitrary exceptions into Faulty to make it
easier to reason about exception flow

Introduced in #12092

### CODE REVIEW

File: vernac/library.ml [hunk 1]
```diff
@@ -57,14 +57,18 @@ let in_delayed f ch ~segment =
...
-    let obj = System.marshal_in f ch in
-    let digest' = Digest.input ch in
-    if not (String.equal digest digest') then raise (Faulty f);
-    obj
-  with e when CErrors.noncritical e -> raise (Faulty f)
+  let ch = open_in_bin f in
+  let obj, digest' =
+    try
+      let () = LargeFile.seek_in ch pos in
+      let obj = System.marshal_in f ch in
```
Comment (ppedrot) [inline vernac/library.ml:64]: This can also fail if the file is corrupted, and you'll get an anomaly instead. I don't think it's a good idea not to catch this exception.

**Comment by ppedrot** [comment]
Rather than changing the exception flow, I think it's better to store the underlying exception inside the `Faulty` constructor.

File: vernac/library.ml (hunk 1 above)
Comment (SkySkimmer) [reply vernac/library.ml:64]: That's just a user_err

Comment (ppedrot) [reply vernac/library.ml:64]: What about the other functions? `seek_in` and `Digest.input` can probably fail as well.

Comment (SkySkimmer) [reply vernac/library.ml:64]: Let them fail, we don't gain anything by catching them

Comment (ppedrot) [reply vernac/library.ml:64]: You'll get an anomaly instead of an error, in which case I don't really see the point of the `Faulty` exception and its accompanying message.

**Review by ejgallego — COMMENTED** [review]
I don't like this, the code is still fragile and moreover `%reraise` should be used.

I suggest we move to a proper structured handling of IO, using something such as `Stdio.with_file`

**Comment by ejgallego** [comment]
Anyways I think we should merge this today, as this is impacting quite a few people , even if I prefer a different style I'm OK with this version, @ppedrot ?

**Comment by ppedrot** [comment]
@ejgallego it's fine as a hotfix.

**Comment by ejgallego** [comment]
Failure is spurious, let's merge and refine later then.

**Review by ejgallego — APPROVED** [review]
Hotfix.
