### PR TITLE
[configure] Fix version checks for lablgtk and zarith

### LINKED ISSUE #13041: [build] Configure should check for `zarith` version
#### Description of the problem

https://launchpadlibrarian.net/497864805/buildlog_ubuntu-bionic-amd64.coq_8.master~git~202009162234+21704-0~daily336-95f78398bb~ubuntu18.04.1_BUILDING.txt.gz

File "./theories/micromega/Lia.v", line 31, characters 23-36:
Error: Anomaly "Uncaught exception Division_by_zero."
Please report at http://coq.inria.fr/bugs/.

#### Coq Version

95f78398bb

### PR DESCRIPTION
**Pull request by ejgallego**
Fixes #13041 #13047

Configure is quite messy, but we will improve it once we can link it
with findlib and move to dune [that will actually allow to remove all
ad-hoc calls to `ocamlfind` in favor of `findlib` code.

### CODE REVIEW

**Comment by ejgallego** [comment]
Nix needs a bump:
```
You have the Num library installed. Good!
Zarith version 1.10 is required, you have 1.9
Configuration script failed!
```

**Comment by Zimmi48** [comment]
I opened a PR: #98164

File: configure.ml [hunk 1]
```diff
@@ -717,20 +723,14 @@ let get_lablgtkdir () =
...
-(* ejgallego: we wait to do version checks until an official release is out *)
-(*  try
-    let vi = numeric_prefix_list v in
-    (* Temporary hack *)
-    if vi = ["3";"0";"beta3"] then (false, v) else
-    let vi = List.map s2i vi in
-    if vi < [3; 0; 0] then
+  try
+    let vl = numeric_prefix_list v in
+    let vn = List.map int_of_string vl in
```
Comment (ejgallego) [inline configure.ml:728]: This kind of code is very fragile if the version does contain strings; but it is not easy to fix as string comparison will fail. Only solution is to do the cleanup and vendor opam's code for version comparison.

**Comment by ejgallego** [comment]
> I opened a PR: [NixOS/nixpkgs#98164](https://github.com/NixOS/nixpkgs/pull/98164)

Thanks @Zimmi48 , please push the ref update when merged.

File: configure.ml [hunk 2]
```diff
@@ -698,10 +698,16 @@ let check_for_numlib () =
...
   match zarith with
   | ""  ->
     die "Zarith library not installed, required"
-  | _   -> cprintf "You have the Zarith library installed. Good!"
+  | _   ->
+    let zarith_version_int = List.map int_of_string (numeric_prefix_list zarith_version) in
+    if zarith_version_int >= [1;10;0] then
+      cprintf "You have the Zarith library %s installed. Good!" zarith_version
+    else
+      die ("Zarith version 1.10 is required, you have " ^ zarith_version)
```
Comment (JasonGross) [inline configure.ml:710]: There is not a single version of Ubuntu nor Debian which ships such a new zarith in libzarith-ocaml-dev.  The newest (in Ubuntu focal and groovy and Debian bullseye and sid) is 1.9.1.  If 1.9.1 is not new enough, I'd like to request that the switch to zarith be reverted until such time as there is at least *some* Ubuntu/Debian version with the relevant version of zarith, ideally a stable one (Debian stable currently ships 1.7.1).  You can see the newest package versions at https://packages.ubuntu.com/search?keywords=ocaml-zarith&searchon=sourcenames and https://packages.debian.org/search?searchon=names&keywords=libzarith-ocaml

**Review by JasonGross — DISMISSED** [review]

File: configure.ml (hunk 2 above)
Comment (Zimmi48) [reply configure.ml:710]: Added this question to the next call.

Comment (ejgallego) [reply configure.ml:710]: Usually we have this requirement on OCaml, as upgrading it is significantly complex; in particular it needs recompilation of all OCaml libs.

For an OCaml library I think the situation is much easier, whoever is uploading the Coq Debian package can also upload an updated `zarith` easily. Or alternatively, it can be vendored easily.

**Comment by ejgallego** [comment]
@JasonGross concern is orthogonal to this PR, which is IMO of high priority for users of `master`, thus I request to dismiss the review and go ahead.

**Comment by JasonGross** [comment]
Indeed, let's merge this PR and discuss whether or not to revert both the code dependency and this check on the call next week.  I would suggest splitting this PR into two commits, though, one for lablgtk and one for zarith, so that it's easier to revert if that's what we decide to do.

**Comment by JasonGross** [comment]
Er, nevermind my suggestion about splitting the commits, I see that we'd actually still want the version check, and would just want to edit the numbers.

**Comment by Zimmi48** [comment]
> Thanks @Zimmi48 , please push the ref update when merged.

Done.

**Comment by ejgallego** [comment]
> Done

Thanks a lot @Zimmi48 , this should be ready however the windows error is a bit bizarre :S

**Comment by ejgallego** [comment]
> Thanks a lot @Zimmi48 , this should be ready however the windows error is a bit bizarre :S

I see that's unrelated, so IMHO if CI passes this should be ready to merge.

**Review by vbgl — APPROVED** [review]

**Review by SkySkimmer — APPROVED** [review]
Looks OK

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Comment by SkySkimmer** [comment]
@coqbot: merge now

File: configure.ml [hunk 3]
```diff
@@ -717,20 +723,14 @@ let get_lablgtkdir () =
...
-(*  try
-    let vi = numeric_prefix_list v in
-    (* Temporary hack *)
-    if vi = ["3";"0";"beta3"] then (false, v) else
-    let vi = List.map s2i vi in
-    if vi < [3; 0; 0] then
+  try
+    let vl = numeric_prefix_list v in
+    let vn = List.map int_of_string vl in
+    if vn < [3; 1; 0] then
```
Comment (gares) [inline configure.ml:729]: This must be `>=`

Comment (gares) [reply configure.ml:729]: Sorry, the problem is not the comparison, but the beta version package by Debian I'm afraid.

Comment (gares) [reply configure.ml:729]: @treinen apparently the META from from sid of lablgtk3 does not contain the `version = ..` line.

Comment (ejgallego) [reply configure.ml:729]: Yes, one has to be careful to use the right upstream `tar.bz2` that contains the correct meta, or indeed tell dune to generate a meta with a git commit hash + version.

Comment (Zimmi48) [reply configure.ml:729]: I removed the "resolved" status so that @treinen will be able to spot this discussion more easily.

Comment (treinen) [reply configure.ml:729]: @gares what precise version are you talking about ? 3.0~beta3-1 from stable ?

I do not tamper with the META files, these are the ones installed by the lablgtk3 upstream. The current one (version 3.1.1-1) looks like this:
''''
$ cat /usr/lib/ocaml/lablgtk3/META 
description = ""
requires = "cairo2 threads"
archive(byte) = "lablgtk3.cma"
archive(native) = "lablgtk3.cmxa"
plugin(byte) = "lablgtk3.cma"
plugin(native) = "lablgtk3.cmxs"
''''

The version number of the **debian** package is slightly changed (note the ~ symbol) but this should not concern the configure script of coq, I hope.

Comment (ejgallego) [reply configure.ml:729]: There is at least two bugs on the packaging scripts for lablgtk3 in debian @treinen , first, as pointed out by Théo you are not picking the right upstream source, thus your files are incorrect; second, you are not properly invoking `dune build` in `rules`.

Comment (treinen) [reply configure.ml:729]: @ejgallo: There is no override of any build targets in debian rules, so dh_auto_build invokes make. Can't I trust that the Makefile provided by uspstream does the right thing ?

I cannot find a post by Théo about using a different usptream source. Currently I am pulling directly from git, using release tags (see the debian/watch file)

Comment (treinen) [reply configure.ml:729]: ok now I think I understand what you are trying to say, @ejgallego and @gares. I understood @gares saying that one has to be careful about pulling the right version. I understand now that one should pull a tar.gz and not directly from a git release tag, is that right ?

In what concerns the build script, you may look a buildlog to understand what is happening :+1: 
 https://buildd.debian.org/status/fetch.php?pkg=lablgtk3&arch=amd64&ver=3.1.1-1%2Bb1&stamp=1597481130&raw=0 for instance

Comment (ejgallego) [reply configure.ml:729]: @treinen I see an override of build indeed; tho we can maybe see this briefly in person some of these days ?

Comment (ejgallego) [reply configure.ml:729]: Actulally you are right about old `makefile` in lablgtk being not good for packagers, now the default make target just produces this:
```
Welcome to lablgtk Dune-based build system. Targets are

  - release:   build lablgtk package in release mode
  - dev:       build in developer mode [requires extra dependencies]
  - dev-all:   build in developer mode [requires extra dependencies]
  - nopromote: dev build but without re-running camlp5 generation
  - opam:      internal, used in CI testing
  - clean:     clean build tree

WARNING: Packagers should not use this makefile, but call dune
directly with the right options for their distribution, see README

```

Comment (treinen) [reply configure.ml:729]: Thanks for  the bug report against the debian package of lablgtk3, @ejgallego, this is fixed now for the latest version in sid.

Concerning the override of the build target, I was looking at 3.1.0-3, and was missing the fact that @glondu had in the meantime uploaded a new version. My bad.

Comment (ejgallego) [reply configure.ml:729]: Thanks @treinen , I will follow up in Debian BTS; I do believe having a `dh_ocaml_dune` helper would be great, Dune developers would happily add some features to `dune install` for example would that help debian.

We could even instruct Dune to produce Debian packages, but that would be a bit inflexible w.r.t. Debian policy IMO, at least until Dune itself is a bit more generic [then dh_dune could just ship a plugin and everything would be taken care of] Note that dune already knows install files etc...

Comment (glondu) [reply configure.ml:729]: @ejgallego See also https://salsa.debian.org/ocaml-team/dh-ocaml/-/merge_requests/1
