### PR TITLE
Fix #8119: anomalies in vm_compute with let and evars.

### LINKED ISSUE #8119: anomalies in vm_compute with let and evars
#### Version

~~~~~
The Coq Proof Assistant, version 8.8.1 (July 2018)
compiled on Jul 5 2018 7:25:50 with OCaml 4.06.0
~~~~~

#### Operating system

Arch Linux, up to date as of yesterday.

#### Description of the problem

~~~~~
Section T.
  Compute let x := tt in _.
(* Error: Anomaly "Uncaught exception Constr.DestKO." Please report at http://coq.inria.fr/bugs/. *)
  Compute let _ := Set in _.
(* Error: Anomaly "Uncaught exception Constr.DestKO." Please report at http://coq.inria.fr/bugs/. *)
  Compute let _ := Prop in _.
(* Error: Anomaly "Uncaught exception Constr.DestKO." Please report at http://coq.inria.fr/bugs/. *)
Section T.

Section U0.
  Let n : unit := tt.
  Compute _.
(* Error: Anomaly "Uncaught exception Constr.DestKO." Please report at http://coq.inria.fr/bugs/. *)
  Goal exists tt : unit, tt = tt. eexists. vm_compute.
(* Error: Anomaly "Uncaught exception Constr.DestKO." Please report at http://coq.inria.fr/bugs/. *)
End U0.

Require Import Coq.Strings.String.

Section S0.
  Let LF : string := String (Coq.Strings.Ascii.Ascii false true false true false false false false) "".
  Compute _.
(* Error: Anomaly "Uncaught exception Constr.DestKO." Please report at http://coq.inria.fr/bugs/. *)
  Goal exists tt : unit, tt = tt. eexists. vm_compute.
(* Error: Anomaly "Uncaught exception Constr.DestKO." Please report at http://coq.inria.fr/bugs/. *)
End S0.

Class T := { }.
Section S1.
  Context {p : T}.
  Let LF : string := String (Coq.Strings.Ascii.Ascii false true false true false false false false) "".
  Compute _.
(* Error: Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/. *)
  Goal exists tt : unit, tt = tt. eexists. vm_compute. Abort.
(* Error: Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/. *)
End S1.  

Class M := { T : Type }.
Section S2.
  Context {p : M}.
  Let LF : string := String (Coq.Strings.Ascii.Ascii false true false true false false false false) "".
  Compute _.
(* Error: Anomaly "File "pretyping/vnorm.ml", line 60, characters 9-15: Assertion failed." *)
  Goal exists tt : unit, tt = tt. eexists. vm_compute. Abort.
(* Error: Anomaly "File "pretyping/vnorm.ml", line 60, characters 9-15: Assertion failed." *)
End S2.
~~~~~

### PR DESCRIPTION
**Pull request by ppedrot**
There were actually two broken things with VM + evars, the fixes are:
- Do not pass let-bound arguments to evars.
- Use the right order for evar arguments.

Native compilation seems to be suffering from the same shortcomings, I will open a separate bug and adapt the PR.

Fixes #8119.

### CODE REVIEW

File: pretyping/vnorm.ml [hunk 1]
```diff
@@ -209,6 +209,13 @@ and nf_evar env sigma evk stk =
   | Zapp args :: stk ->
     (** We assume that there is no consecutive Zapp nodes in a VM stack. Is that
         really an invariant? *)
+    let drop_let decl = match decl with
+    | NamedDecl.LocalAssum _ -> decl
+    | NamedDecl.LocalDef (na, _, t) -> NamedDecl.LocalAssum (na, t)
+    in
+    (** Let-bound arguments are present in the evar arguments but not in the
+        type, so we turn the let into a product. *)
+    let hyps = List.map drop_let hyps in
```
Comment (maximedenes) [inline pretyping/vnorm.ml]: This should be a combinator.

File: kernel/cbytegen.ml [hunk 2]
```diff
@@ -501,6 +501,9 @@ let rec compile_lam env cenv lam sz cont =
       if Array.is_empty args then
         compile_fv_elem cenv (FVevar evk) sz cont
       else
+        (** Arguments are reversed in evar instances *)
+        let args = Array.copy args in
+        let () = Array.rev args in
```
Comment (maximedenes) [inline kernel/cbytegen.ml]: Ok for now, but can the order be fixed? Is there a reason for the discrepancy?

**Review by maximedenes — DISMISSED** [review]

File: kernel/cbytegen.ml (hunk 2 above)
Comment (ppedrot) [reply kernel/cbytegen.ml]: You mean in the `Constr.Evar` node or somewhere else?

Comment (maximedenes) [reply kernel/cbytegen.ml]: Yeah, that's what I meant. I was referring to your comment.

**Review by maximedenes — APPROVED** [review]
