### PR TITLE
Handle delayed opaque proofs in Print Assumptions

### LINKED ISSUE #13589: Print Assumptions for vok
#### Description of the problem

The documentation of `vok` compilation makes it seem that if regular (`vo`) compilation succeeds, then so also does a `vos` + `vok` compilation.
However, `vok` produces an error on `Print Assumptions` when multiple files are involved.
As a result, `vok` is not useful in presence of such.

Suggestion: `vok` could produce a warning, that `Print Assumptions` is not useful, but otherwise do its job.

#### Example

`file1.v`:
```
Lemma hidden : False.
Proof. Admitted.

Lemma aux : False.
Proof. apply hidden. Qed.
```
`file2.v`:
```
Require file1.

Lemma main : False.
Proof. apply file1.aux. Qed.

Print Assumptions main. (* this fails *)
```
Commands:
```
 coqc -vos .\file1.v
 coqc -vos .\file2.v
 coqc -vok .\file2.v
```
Result:
```
File ".\file2.v", line 6, characters 0-23:
Error: Cannot access opaque delayed proof
```

#### Coq Version

The Coq Proof Assistant, version 8.12.1 (December 2020)
compiled on Dec 6 2020 13:40:33 with OCaml 4.07.1

### PR DESCRIPTION
**Pull request by ppedrot**
Instead of using Global.body_of_constant_body and tinkering with the result we roll up our own version of the accessor which is delayed-proof-aware.

Fixes #13589: Print Assumptions for vok.

Supersedes #13614.

### CODE REVIEW

File: vernac/assumptions.ml [hunk 1]
```diff
@@ -190,14 +190,27 @@ let fold_with_full_binders g f n acc c =
...
+  let env = Global.env () in
+  let access = Library.indirect_accessor in
+  let otab = Environ.opaque_tables env in
+  match cb.const_body with
+  | Undef _ | Primitive _ -> None
+  | Def c -> Some (Mod_subst.force_constr c)
+  | OpaqueDef o ->
+    match Opaqueproof.force_proof access otab o with
+    | c, _ -> Some c
+    | exception _ -> None (* missing delayed body, e.g. in vok mode *)
```
Comment (SkySkimmer) [inline vernac/assumptions.ml:204]: Should we really catch everything?
Maybe force_proof should return an option or have a dedicated exception.

Comment (ppedrot) [reply vernac/assumptions.ml:204]: This should be done eventually but since I am planning to mess with this code, I prefer submitting this PR as a fix first.

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1291081315 is not happy

**Comment by ppedrot** [comment]
@SkySkimmer yes, it seems like the binary called by the script doesn't like the `-vok` flag. Unfortunately I don't know what happens exactly in async mode, isn't it supposed to be always a call to coqc?

**Comment by ppedrot** [comment]
Let's try a bit of cargo culting to see whether it works. I mimicked the script in the vos folder, which calls the `coqc` binary instead of going through the variable exposed by the test-suite wrapper.

**Comment by SkySkimmer** [comment]
I guess -vok is passed to the worker (incorrectly).

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now
