### PR TITLE
Forbid Include inside sections

### LINKED ISSUE #10060: Anomaly "File "kernel/subtyping.ml", line 236, characters 15-21: Assertion failed."
#### Description of the problem
Here’s the code:
```coq
Module Type T.
  Parameter b : Set.
End T.

Module M1(N : T).
End M1.

Module M2.
End M2.

Section S.
  Variable a : Set.
  Definition b := a.
  Include M1.
(* Anomaly "File "kernel/subtyping.ml", line 236, characters 15-21: Assertion failed."
 * Please report at http://coq.inria.fr/bugs/.
 *)

(* Doing "Include M2." instead will give the error message "you are not in a module"
 * which is (unfortunately :D) probably the intended behavior for the "M1" case, too.
 *)
End S.
```

_(I guess, my assumption that including a module functor by instantiating parameters with section variables might work somehow, is a pretty neat idea, yet apparently false.)_

#### Coq Version
current master

### PR DESCRIPTION
**Pull request by SkySkimmer**
This probably does not work well in general, and specifically avoids
an anomaly: close https://github.com/coq/coq/issues/10060

### CODE REVIEW

File: vernac/declaremods.ml [hunk 1]
```diff
@@ -972,6 +972,8 @@ let declare_modtype id args mtys mty_l =
   protect_summaries declare_mt
 
 let declare_include me_asts =
+  if Global.sections_are_opened () then
+    user_err Pp.(str "Modules and Module Types are not allowed inside sections.");
```
Comment (Blaisorblade) [inline vernac/declaremods.ml]: If I may butt in, I'd vote for "Include is not allowed inside sections".

If you wonder, imagine including a module with submodules — there a user would be entitled to think the submodules are the problem.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I'm wondering if it makes sense to hoist out of `*ModOps` similar checks, so that they are all in the same file.

**Comment by SkySkimmer** [comment]
Not sure what you mean, Modops is in the kernel so we can't just move those checks to the upper layers.

**Comment by gares** [comment]
(the kernel may still error out, but the user facing message better be close to the user IMHO)

**Comment by SkySkimmer** [comment]
>Your new error is in vernac, which seems fine, but the other ones are not.

There are checks for sections in vernacentries
I put this one in declaremods because the vernacentries part is just a function alias

**Review by ppedrot — APPROVED** [review]
