### PR TITLE
Various dynamic assertions and cleanups in opaque typing

### LINKED ISSUE #10251: Type-checking of polymorphic opaque constr entry types is broken
This piece of code in `Term_typing` is completely wrong for opaque polymorphic constants:
```
      let env, usubst, univs, private_univs = match c.const_entry_universes with
      | Monomorphic_entry univs ->
        [...]
      | Polymorphic_entry (nas, uctx) ->
        (** [ctx] must contain local universes, such that it has no impact
            on the rest of the graph (up to transitivity). *)
        let env = push_context ~strict:false uctx env in
        let sbst, auctx = Univ.abstract_universes nas uctx in
        let sbst = Univ.make_instance_subst sbst in
        let env, local =
          if opaque then
            push_subgraph ctx env, Some (on_snd (Univ.subst_univs_level_constraints sbst) ctx)
          else
            [...]
        in
        env, sbst, Polymorphic auctx, local
      in
      let j = Typeops.infer env body in
      let typ = match typ with
        | None ->
          [...]
        | Some t ->
           let tj = Typeops.infer_type env t in
           let _ = Typeops.judge_of_cast env j DEFAULTcast tj in
           Vars.subst_univs_level_constr usubst tj.utj_val
      in
```

Note how the type of the constant `typ` is type-checked in the environment extended with local opaque body constraints instead of the base environment. This would allow the type to depend on universes that do not exist in the global environment.

This bug was introduced in ed04b8eb07ca3925af852c30a75c553c134f7d72, and can probably be used to trigger soundness issues, at least from a ML plugin.

### PR DESCRIPTION
**Pull request by ppedrot**
We clean code in `Term_typing` and add several dynamic checks on well-formedness of data provided by the upper layers. Most notably, we force opaque entries to come with their type. Only `Add Ring` was breaking this invariant it seems.

Ideally these invariants should be ensured statically, but trying to do so reaches the can of worms of the proof management layer. Thus I am deferring this for a later PR.

We also seize the opportunity to fix #10251 by writing the code so as to keep the local environment local (erm...).

I will write a simpler, more self-contained fix for 8.10, which is the only release in the wild with the potential soundness bug.

Fixes #10251.

### CODE REVIEW

**Comment by ejgallego** [comment]
@ppedrot let me know if you want a pointer to the most recent branch with the proof later cleanup, it is quite far from master but it'd be good maybe to have a look as to avoid duplicate work.

You can also describe the issue in #10040 and I'll take care of it .

**Comment by ppedrot** [comment]
I had a look at your branch, and it mostly orthogonal to what I had in mind.

I think that the easiest way not to interfere would be to split the `Entries.definition_entry` type in two. Indeed, it is used both kernel-side and proof-side, and the expected invariants are not the same. Splitting it would allow tweaking both sides without strong coupling, with a shim in `Declare`. Clients in the upper layers are doing crazy things with definition entries, most specifically the plugin-which-must-not-be-named, and Program to a lesser extent. I have no hope to fix those alone and I am willing to let you act instead, but the current coupling prevents further kernel improvements.

I do have a tiny patch that perform the split, are you OK in principle with the idea?

**Comment by ejgallego** [comment]
> I do have a tiny patch that perform the split, are you OK in principle with the idea?

Sure, indeed what you say about usage of `definition_entry` does makes sense; I guess we'd have to see how code looks to say more. What is the particular bad use case you see?

Note that I have a branch which tries to modifiy `Proof_global.close_proof` which in its current form is indeed problematic as "closed proofs" cannot be re-injected back into the global proof state and that requires some incovenient hacks elsewhere, so I wonder how things will be here.

**Comment by ejgallego** [comment]
By the way I have another branch that almost unyfies all the proof save paths including obligations and funind; the resulting function looks a bit complicated however there is only _one_ of such functions.

**Comment by ppedrot** [comment]
> the resulting function looks a bit complicated

Worse than the spaghetti code of `Proof_global.close_proof`?

**Comment by ejgallego** [comment]
> Worse than the spaghetti code of `Proof_global.close_proof`?

That function takes as input the output of close_proof

**Review by maximedenes — APPROVED** [review]
I'll let @SkySkimmer review the fix, but otherwise looks good to me!

File: plugins/setoid_ring/newring.ml [hunk 1]
```diff
@@ -153,9 +153,11 @@ let decl_constant na univs c =
   let open Constr in
   let vars = CVars.universes_of_constr c in
   let univs = UState.restrict_universe_context univs vars in
-  let univs = Monomorphic_entry univs in
+  let () = Declare.declare_universe_context false univs in
+  let types = (Typeops.infer (Global.env ()) c).uj_type in
```
Comment (SkySkimmer) [inline plugins/setoid_ring/newring.ml]: I guess this could be a Retyping call but the econstr boilerplate makes it easier with typeops

**Review by SkySkimmer — APPROVED** [review]

File: plugins/setoid_ring/newring.ml (hunk 1 above)
Comment (ppedrot) [reply plugins/setoid_ring/newring.ml]: Well, technically it doesn't generate the same type in general. This version is backwards-compatible, although maybe a little slower. That said, this shouldn't matter at all here, this is only called at a ring definition time, i.e. virtually never.

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
A similar issue is present in the checker.

**Review by SkySkimmer — APPROVED** [review]
