### PR TITLE
[tools] Remove support for python2

### LINKED ISSUE #10491: [build] Removal of python2
Following discussion on #10466 , we have moved all our python scripts to explicitly use a `/usr/bin/python3` shebang, except for `update-compat.sh`.

`update-compat.sh` does fail in Ubuntu when used with python3 [decode error]

To fix this issue we should thus:
- fix `update-compat.sh` so the enconding error is no more
- remove `python2` from azure
- remove `python2` from Nix
- `python2` is still pulled indirectly in Docker, that will be fixed when we update the Docker image to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by ejgallego**
**Kind:** infrastructure.

Closes #10491

- [x] Added / updated test-suite
- [x] Corresponding documentation was added
- [x] Entry added in the changelog

### CODE REVIEW

**Review by vbgl — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Can we remove python2 from the dockerfile too or does something block it?

**Review by Zimmi48 — APPROVED** [review]

**Comment by ejgallego** [comment]
> Can we remove python2 from the dockerfile too or does something block it?

Last time I looked `python2` was being pulled by some TeX stuff I believe, so no unless we move from bionic.

File: test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh [hunk 1]
```diff
@@ -5,20 +5,14 @@ set -e
 
 cd "$(dirname "${BASH_SOURCE[0]}")"
 
-python2 "$COQLIB"/tools/make-one-time-file.py time-of-build.log.in time-of-build-pretty.log2 || exit $?
```
Comment (JasonGross) [inline test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh]: Please don't.  I'd like to keep these files compatible with both python2 and python3.  Feel free to makes this test pass with a warning when python2 does not exist (but please continue installing it on the CI for this test).

**Review by JasonGross — CHANGES_REQUESTED** [review]

File: doc/tools/coqrst/notations/fontsupport.py [hunk 2]
```diff
@@ -1,4 +1,4 @@
-#!/usr/bin/env python2
+#!/usr/bin/env python3
```
Comment (JasonGross) [inline doc/tools/coqrst/notations/fontsupport.py]: Have you checked that this code actually runs with python3?  IIRC, this file does not run with python3 and is not actually run at all, see the comment "This script is here for reference. It was used to generate the modified
font CoqNotations.ttf from UbuntuMono-B.ttf.
"

File: test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh (hunk 1 above)
Comment (ejgallego) [reply test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh]: I'm not sure I see a good reason we should keep supporting `python2` in 8.12, anyways that discussion should be done in #10491

File: doc/tools/coqrst/notations/fontsupport.py (hunk 2 above)
Comment (ejgallego) [reply doc/tools/coqrst/notations/fontsupport.py]: I have not, but then based on your comment we should not keep untested code in the repos.

Comment (Zimmi48) [reply doc/tools/coqrst/notations/fontsupport.py]: We have no idea whether it runs or not. See comment below:

>This script is here for reference. It was used to generate the modified font CoqNotations.ttf from UbuntuMono-B.ttf.

**Comment by ejgallego** [comment]
> Please don't. I'd like to keep these files compatible with both python2 and python3. Feel free to makes this test pass with a warning when python2 does not exist (but please continue installing it on the CI for this test).

After reading https://www.python.org/doc/sunset-python-2/ , python 2 is EOL effectively starting in Jan 1st 2020, thus IMHO it makes sense that 8.12 [scheduled mid-2020] doesn't support Python 2.

We will likely find ourselves having problems even installing Python 2 in our CI images.

**Comment by JasonGross** [comment]
I have heard whispers (from @andres-erbsen, I think) that effectively Google or some other large company with a great deal of legacy code will take over maintaining the python2 ecosystem.  I'm fine with dropping python2 support as soon as it becomes a hassle.  I remain unconvinced about doing it preemptively (but will bow to the consensus of coqdevs)

**Comment by SkySkimmer** [comment]
I think we should preemptively remove python2 from our required dependencies, including test suite dependencies.
For instance currently it's listed in the nix file, that's not great IMO

**Comment by Zimmi48** [comment]
> Google or some other large company with a great deal of legacy code will take over maintaining the python2 ecosystem

It seems like this transition will never end :cry: Anyway, we should not be taking part in this joke.

**Comment by ejgallego** [comment]
@JasonGross , what I'm missing is that you have said "keep python2 tests here", but you didn't really say "why" you need that. Do you folks have a setup where py3 is not available?

**Comment by ejgallego** [comment]
> @JasonGross , what I'm missing is that you have said "keep python2 tests here", but you didn't really say "why" you need that. Do you folks have a setup where py3 is not available?

@JasonGross ping again; unless there is a real platform / use case where python 2 is needed we are strongly leaning towards removal.

File: test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh [hunk 3]
```diff
@@ -5,20 +5,14 @@ set -e
...
-python3 "$COQLIB"/tools/make-one-time-file.py time-of-build.log.in time-of-build-pretty.log3 || exit $?
+python3 "$COQLIB"/tools/make-one-time-file.py time-of-build.log.in time-of-build-pretty.log || exit $?
```
Comment (JasonGross) [inline test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh]:
```suggestion
"$COQLIB"/tools/make-one-time-file.py time-of-build.log.in time-of-build-pretty.log || exit $?
```

File: test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh [hunk 4]
```diff
@@ -5,20 +5,14 @@ set -e
...
-cat time-of-build.log.in | python3 "$COQLIB"/tools/make-one-time-file.py - time-of-build-pretty.log3 || exit $?
+cat time-of-build.log.in | python3 "$COQLIB"/tools/make-one-time-file.py - time-of-build-pretty.log || exit $?
 
-diff -u time-of-build-pretty.log.expected time-of-build-pretty.log2 || exit $?
-diff -u time-of-build-pretty.log.expected time-of-build-pretty.log3 || exit $?
+diff -u time-of-build-pretty.log.expected time-of-build-pretty.log || exit $?
 
-(python2 "$COQLIB"/tools/make-one-time-file.py time-of-build.log.in - || exit $?) > time-of-build-pretty.log2
-(python3 "$COQLIB"/tools/make-one-time-file.py time-of-build.log.in - || exit $?) > time-of-build-pretty.log3
+(python3 "$COQLIB"/tools/make-one-time-file.py time-of-build.log.in - || exit $?) > time-of-build-pretty.log
```
Comment (JasonGross) [inline test-suite/coq-makefile/timing/precomputed-time-tests/003-non-utf8/run.sh]:
```suggestion
("$COQLIB"/tools/make-one-time-file.py time-of-build.log.in - || exit $?) > time-of-build-pretty.log
```

File: doc/tools/coqrst/notations/fontsupport.py (hunk 2 above)
Comment (JasonGross) [reply doc/tools/coqrst/notations/fontsupport.py]: This code does not run with python3, as fontforge does not provide python3 bindings, only python2 bindings.  (The code requires adding `# -*- coding: utf-8 -*-` to run with python2, but otherwise it seems to run fine under python2.  Note that this coding line was originally present but was removed by @Zimmi48 in 1a9c769ed363ee2f2784e7252af72e6c1e2fbcc6 which caused this file to no longer work.)

I don't have a strong opinion about removing this file vs keeping it for documentation purposes.  (`git blame` claims this file was introduced by @maximedenes and edited by @cpitclaudel ; they might have opinions?)  However, changing `python2` to `python3` is incorrect, and should not be commited.

```suggestion
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
```

**Review by JasonGross — CHANGES_REQUESTED** [review]
I do not have any particular setup in mind that only supports python2, so I will not stand in the way of removing it in favor of only supporting python3 if you feel strongly.

However, the change to `fontsupport.py` is incorrect, and should not be committed as-is

**Comment by Zimmi48** [comment]
Thanks @JasonGross for your comments. @ejgallego please apply the suggestions from Jason's code review. I tried to do it myself but it told me that I didn't have permission to push to your repository.

**Comment by maximedenes** [comment]
> I tried to do it myself but it told me that I didn't have permission to push to your repository.

You could report this to GH btw, it happened to me too some time ago. You do have permission to push to @ejgallego 's branch, most likely. The interface does not seem able to detect that correctly.

**Comment by ejgallego** [comment]
I have corrected the fontsupport.py script; suggested changes to the test suite seem orthogonal to this PR thus I'd prefer to do them in a different PR.

**Comment by JasonGross** [comment]
> suggested changes to the test suite seem orthogonal to this PR thus I'd prefer to do them in a different PR.

The suggested changes to the test-suite are to bring these files in line with the rest of the coq-makefile timing tests.  The only reason we were explicitly invoking python was to test with both versions.  All of the other `run.sh` scripts just invoke the scripts by path; I don't see any reason to leave the explicit call to `python3` here.

**Comment by Zimmi48** [comment]
@ejgallego Please do implement the other requested change by @JasonGross and I'll merge afterward. If you wish, I can also directly push to your branch to do the change (which is rather trivial).

**Comment by ejgallego** [comment]
Done @Zimmi48 thanks!

**Review by JasonGross — APPROVED** [review]
