### PR TITLE
Fix stage of generic_notation_printing_rules

### LINKED ISSUE #17627: uncaught Not_found with notation in Module Import
~~~coq
Module Import Bar.

  Notation "'φ' x" := (id x) (at level 0) .

End Bar.

Check (φ _). (* uncaught Not_found *)
~~~
The Not_found is from https://github.com/coq/coq/blob/5fa621536377bc43f183b4af50481857ca4be0b6/printing/ppextend.ml#L102

NB: this only happens with combined Module Import, `Module Bar. ... End Bar. Import Bar.` seems fine.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17627

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

File: printing/ppextend.ml [hunk 1]
```diff
@@ -75,12 +75,13 @@ type generic_notation_printing_rules = {
 }
 
 let generic_notation_printing_rules =
-  Summary.ref ~name:"generic-notation-printing-rules" (NotationMap.empty : generic_notation_printing_rules NotationMap.t)
+  Summary.ref ~stage:Synterp ~name:"generic-notation-printing-rules" (NotationMap.empty : generic_notation_printing_rules NotationMap.t)
```
Comment (SkySkimmer) [inline printing/ppextend.ml:78]: alternatively maybe this should be set by the Interp object instead of the Synterp object?

Comment (maximedenes) [reply printing/ppextend.ml:78]: It looks ok this way, cheaper than adding an interp phase to `Reserved Notation`

**Review by maximedenes — APPROVED** [review]
