### PR TITLE
Do not consider removed evars in evar name conflicts

### LINKED ISSUE #21637: "Ambiguous evar name" after name conflict was resolved
### Description of the problem

An evar's name might remain ambiguous even after a name conflict was resolved. This is due to how we track evar that participate in a full path as qualifiers: they are added to `removed_evars`, but still take part in name conflict checking.

### Small Rocq / Coq file to reproduce the bug

```coq
Goal forall a b c : bool, True.
Proof.
  intros.
  destruct a.
  [true]: {
    refine _.
    destruct b, c.
    all: exact I.
  }
  (* The following raises "Ambiguous evar name false.", but it really shouldn't. *)
  [false]: exact I.
Qed.
```

### Version of Rocq / Coq where this bug occurs

9.2+rc2

### Interface of Rocq / Coq where this bug occurs

_No response_

### Last version of Rocq / Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by dhalilov**
Fixes / closes #21637

- [x] Added / updated **test-suite**.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

File: engine/evarnames.ml [hunk 1]
```diff
@@ -262,6 +262,7 @@ let add_fresh basename ev ?parent evn =
   in
   let qualid = EvarQualid.{ basename; path = path ev evn } in
   let ans = NameResolution.find qualid evn.name_resolution in
+  let ans = Evar.Set.diff ans evn.removed_evars in
```
Comment (ppedrot) [inline engine/evarnames.ml]: Maybe you should write a helper function that combines NameResolution.find and the Evar.Set.diff. All callers respect the same scheme.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now
