### PR TITLE
coqchk accept absolute vo paths

### LINKED ISSUE #19440: coqchk fails on abolute .vo path
~~~
$ cd tmp
$ touch /tmp/foo.v
$ coqc -Q /tmp Tmp foo.v
$ coqchk -Q /tmp Tmp ./foo.vo
Modules were successfully checked
$ coqchk -Q /tmp Tmp foo.vo
Modules were successfully checked
$ cd / && coqchk -Q /tmp Tmp tmp/foo.vo
Modules were successfully checked
~~~
but
~~~
$ cd /tmp && coqchk -Q /tmp Tmp /tmp/foo.vo
Fatal Error: User error: Cannot find library /tmp/foo.vo in loadpath.
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #19440

### CODE REVIEW

File: checker/check.ml [hunk 1]
```diff
@@ -242,10 +242,6 @@ let try_locate_absolute_library dir =
 
 let try_locate_qualified_library lib = match lib with
 | PhysicalFile f ->
-  let () =
-    if not (System.file_exists_respecting_case "" f) then
-      error_lib_not_found { dirpath = []; basename = f; }
-  in
```
Comment (ppedrot) [inline checker/check.ml:248]: IIUC after this patch a missing file would fail with an uncaught exception in intern_from_file. Can't we get a more user-readable error still?

Comment (SkySkimmer) [reply checker/check.ml:248]: If you mean on non existing files we get
~~~
[intern /tmp/fo.vo ...
 failed!]

Fatal Error: User error: /tmp/fo.vo: /tmp/fo.vo: No such file or directory. Try to rebuild it.
~~~

Comment (ppedrot) [reply checker/check.ml:248]: That's a bit subpar, couldn't we fix the check instead?

Comment (ppedrot) [reply checker/check.ml:248]: Ping @SkySkimmer

Comment (SkySkimmer) [reply checker/check.ml:248]: changed

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci
