### PR TITLE
Fix #7854: Native compilation + flambda trigger SEGFAULT.

### LINKED ISSUE #7854: Native compilation triggers segmentation fault under flambda optimizations
#### Version

Coq 8.8

#### Operating system

Debian SID amd64, OCaml 4.06.1+flambda

#### Description of the problem

Confirming the suspicions of #7750, Coq native compilation is unsound w.r.t. OCaml semantics, and the optimizations performed by the `flambda` flag might cause serious errors. For instance, the following snippet triggers a SEGFAULT.
```
Set Primitive Projections.

CoInductive stream (A : Type) := cons {
  hd : A;
  tl : stream A;
}.

CoFixpoint const {A} (x : A) := cons A x (const x).

Check (@eq_refl _ tt <<: tl unit (const tt) = const tt).
```
I did not try to generate a proof of False, but I believe this is serious enough to deserve a critical label.

### PR DESCRIPTION
**Pull request by ppedrot**
We use a more abstract representation for accumulators in the native compilation scheme, that requires less fiddling with low-level implementation details. It might be slower though.

It should probably be backported, as it doesn't break the API.

Fixes #7854.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Changing the milestone since backporting was requested.

**Comment by Zimmi48** [comment]
Unless you meant that a separate PR will be necessary for backporting.

**Comment by ppedrot** [comment]
I don't think this code has changed between versions, so the same PR should apply.

File: kernel/nativevalues.ml [hunk 1]
```diff
@@ -68,28 +68,29 @@ type atom =
...
-  Obj.set_field r 0 (Obj.field (Obj.magic rcode) 0);
-  Obj.set_field r 1 (Obj.field (Obj.magic rcode) 1);
-  Obj.set_field r 2 (Obj.magic a);
-  (Obj.magic r:t);;
-
-let mk_accu (a:atom) = mk_accu_gen accumulate a
+(** Unique pointer used to drive the accumulator function *)
+let ret_accu = Obj.repr (ref ())
+
+type accu_data = { mutable acc_atm : atom; acc_val : Obj.t list }
```
Comment (maximedenes) [inline kernel/nativevalues.ml]: I would call the record `accu_val` and the field `acc_args`.

**Review by maximedenes — COMMENTED** [review]
I need to think a bit about how this is going to interact with the plan of unifying VM and native values.

**Comment by maximedenes** [comment]
@ppedrot can you run a benchmark on this?

**Comment by ppedrot** [comment]
Running there: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/480.

Do we have a lot of contributions testing native compilation though? AFAIR Fiat is the only one, right?

**Comment by ppedrot** [comment]
@maximedenes Do I understand correctly that you want to unify the reification functions for the VM and the native compiler? That seems like a very hard endeavour to me, I already had trouble encoding away naked pointers in the VM.

**Comment by maximedenes** [comment]
> Do I understand correctly that you want to unify the reification functions for the VM and the native compiler? That seems like a very hard endeavour to me, I already had trouble encoding away naked pointers in the VM.

What I had in mind was to share the high level reification functions. I guess we could share a lot of code between `nativenorm.ml` and `vnorm.ml` even if we abstract away the precise accumulator encodings (that would share the same API). Doesn't it sound feasible?

**Comment by ppedrot** [comment]
@maximedenes I guess we can turn reification into a functor abstracting away the differences of representation...

**Comment by ppedrot** [comment]
Result of the benchmark:
```
┌──────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                       │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │            NEW            OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  710.41  714.69 -0.60 % │  1970255881383  1979161289588 -0.45 % │  3030035309337  3029345722209 +0.02 % │ 3374604 3373732 +0.03 % │   7 359 -98.05 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  884.12  888.22 -0.46 % │  2447866046966  2461601118949 -0.56 % │  3546970712068  3546081134765 +0.03 % │ 1350532 1349540 +0.07 % │   0   4 -100.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   80.68   80.86 -0.22 % │   223107282561   223311519450 -0.09 % │   330291124838   330614840088 -0.10 % │  587336  586756 +0.10 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real-closed │  183.49  183.88 -0.21 % │   510972672286   511307764669 -0.07 % │   774677077156   774879881134 -0.03 % │  832516  831080 +0.17 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   61.52   61.64 -0.19 % │   168901665040   169177051966 -0.16 % │   238553295720   238729192091 -0.07 % │  532404  531916 +0.09 % │   1   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-sf-lf │   36.14   36.21 -0.19 % │    98583410447    98793002930 -0.21 % │   162636847344   162820803656 -0.11 % │  415204  414776 +0.10 % │   3   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-formal-topology │   53.78   53.88 -0.19 % │   146898432808   146828096537 +0.05 % │   219643233649   219859273597 -0.10 % │  479768  479252 +0.11 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  462.14  462.93 -0.17 % │  1285790415187  1287641813292 -0.14 % │  2114852348639  2115129984844 -0.01 % │  803984  803584 +0.05 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-color │  727.80  728.92 -0.15 % │  2012602615591  2013522922197 -0.05 % │  2427800950824  2428636975268 -0.03 % │ 1388176 1387936 +0.02 % │  64   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  198.80  199.04 -0.12 % │   552166399316   551908734465 +0.05 % │   775953561422   776348618108 -0.05 % │  645940  644352 +0.25 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-sf-plf │   68.02   68.10 -0.12 % │   187401920301   187204772081 +0.11 % │   270980614740   270944797926 +0.01 % │  512484  511736 +0.15 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-math-classes │  241.53  241.71 -0.07 % │   664382923810   663558711129 +0.12 % │   861137899654   861753351735 -0.07 % │  533600  532796 +0.15 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  215.49  215.60 -0.05 % │   598344262427   598206407825 +0.02 % │   854757050401   854601514050 +0.02 % │  837148  861152 -2.79 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 2824.71 2824.00 +0.03 % │  7830753003171  7829600918567 +0.01 % │ 12566220888115 12566926668691 -0.01 % │ 1396460 1395812 +0.05 % │ 388   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coquelicot │   98.00   97.87 +0.13 % │   271149211655   271279555606 -0.05 % │   360252842382   359861928721 +0.11 % │  711952  711076 +0.12 % │  24  83 -71.08 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-lambda-rust │ 1749.28 1746.91 +0.14 % │  4859629957457  4863452714040 -0.08 % │  6432019343255  6435298419421 -0.05 % │ 1364220 1367788 -0.26 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   95.34   95.16 +0.19 % │   264130609325   263287904059 +0.32 % │   375396045302   375517523653 -0.03 % │  517060  516540 +0.10 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  128.08  127.83 +0.20 % │   355746117162   355346331102 +0.11 % │   472223326167   472162495014 +0.01 % │  496632  496532 +0.02 % │  84   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-unimath │ 1313.74 1308.99 +0.36 % │  3634983815802  3619480951087 +0.43 % │  6181564932330  6182954468233 -0.02 % │ 1055372 1055100 +0.03 % │  21   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │  276.19  275.18 +0.37 % │   766946699751   763379649636 +0.47 % │   981627958297   982435919987 -0.08 % │ 1245308 1244780 +0.04 % │   1   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-sf-vfa │   42.07   41.91 +0.38 % │   115595145230   115725444581 -0.11 % │   183973643040   183958141998 +0.01 % │  532280  531792 +0.09 % │   0  24 -100.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  288.71  287.58 +0.39 % │   802782287129   799635081464 +0.39 % │  1167789942368  1167949414796 -0.01 % │ 1106168 1105920 +0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-corn │ 1566.82 1557.49 +0.60 % │  4333269665787  4313573911114 +0.46 % │  6393936870578  6392565501291 +0.02 % │  858564  883420 -2.81 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-vst │ 4010.60 3985.48 +0.63 % │ 11153067208756 11084919828424 +0.61 % │ 14598283901505 14600006561503 -0.01 % │ 2226296 2226356 -0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-hott │  328.61  325.87 +0.84 % │   912714476985   904189828073 +0.94 % │  1364887866056  1365047739900 -0.01 % │  611244  611276 -0.01 % │  27  26 +3.85 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd-order │ 1436.06 1415.02 +1.49 % │  4001837688674  3942275324608 +1.51 % │  6701647524736  6700865709787 +0.01 % │ 1353308 1402596 -3.51 % │   0   0  +nan % │
└──────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```
Mathcomp-odd-order seems slower but I don't know whether it is due to noise or this PR. AFAIK it doesn't use native compilation at all, so I'd be inclined towards the first option.

**Comment by ppedrot** [comment]
I reran the bench on vst and mathcomp, same results:
```
┌────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                        │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                        │                         │                                       │                                       │                         │                 │
│           package_name │     NEW     OLD PDIFF   │            NEW            OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-vst │ 4018.97 3986.99 +0.80 % │ 11171037744982 11086212301226 +0.77 % │ 14587822072148 14591802004842 -0.03 % │ 2225876 2226268 -0.02 % │   2   0  +nan % │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-odd-order │ 1441.27 1419.38 +1.54 % │  4003650707842  3943739598475 +1.52 % │  6701400085085  6704393321338 -0.04 % │ 1372100 1372832 -0.05 % │  13   0  +nan % │
└────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```
Now I am puzzled. Do you know how a modification of the runtime of native compilation could affect the odd order theorem, even if the latter doesn't use it?

**Comment by ejgallego** [comment]
> Now I am puzzled. Do you know how a modification of the runtime of native compilation could affect the odd order theorem, even if the latter doesn't use it?

Look at the per-line diff.

**Comment by ejgallego** [comment]
What's the timeframe on this?

**Comment by ppedrot** [comment]
@ejgallego That's a serious bug, so hopefully short. Extracting exploitable data from the bench runs is not easy though, that's a major pain.

**Comment by ejgallego** [comment]
> @ejgallego That's a serious bug, so hopefully short. Extracting exploitable data from the bench runs is not easy though, that's a major pain.

Yeah that seems like funny data, do you have a link to the bench build? I can use `wget + grep` to highlight the most interesting points.

**Comment by ppedrot** [comment]
@ejgallego It seems pendulum erases the data after some time, I am rerunning the bench currently. There are a few python scripts in `dev/` able to parse time diffs, but they don't operate over several files so I guess I'll have to tweak them myself.

**Comment by ejgallego** [comment]
> @ejgallego It seems pendulum erases the data after some time, I am rerunning the bench currently. There are a few python scripts in dev/ able to parse time diffs, but they don't operate over several files so I guess I'll have to tweak them myself.

Cool, please post the link to the build. We may want to do some command line helper to grab and analyze stuff.

**Comment by ppedrot** [comment]
Well, now I cannot reproduce the slowdown.
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                        │      user time [s]      │             CPU cycles              │          CPU instructions           │  max resident mem [KB]  │   mem faults    │
│                        │                         │                                     │                                     │                         │                 │
│           package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │           NEW           OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-odd-order │ 1421.28 1430.87 -0.67 % │ 3960626586227 3986679579942 -0.65 % │ 6702498002024 6704872132347 -0.04 % │ 1371720 1378560 -0.50 % │  15   0  +nan % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by ejgallego** [comment]
Yeah so this seems ready then.

**Comment by JasonGross** [comment]
@maximedenes What is "easy"?  If you are compiling it yourself, `git grep --name_only 'vm_' | xargs sed 's/vm_/native_/g' -i`.  If you want a branch that you can feed to something else, I can make a branch like that.  If you have a place for repos that persist to test Coq, I can copy the state over to some new repo frozen on the current version of fiat-crypto.

**Comment by ppedrot** [comment]
@maximedenes I've tried to measure the difference on the two examples from maximedenes/native-compute-bench. In theory there shouldn't be any observable difference because none of the terms use accumulators, as they're closed. It turns out that indeed `RecNoAlloc` takes the same time both before and after the patch, but for some reason `Lucas` is now *faster*, from ~4.4s to ~4.0s on my machine. I have no idea why though...

**Comment by maximedenes** [comment]
Handling of accumulators is usually not a bottleneck (apart from the `is_accu` calls), so I doubt it will have any bad impact, which seems confirmed by the benchmarks. Given that this is a blocking issue, I'll merge.

**Review by maximedenes — APPROVED** [review]
