### PR TITLE
Make detyping robust w.r.t. indexed anonymous variables

### LINKED ISSUE #3754: "Anomaly: index to an anonymous variable" in Set Debug Tactic Unification
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#3754
From: @mikeshulman
Reported version: 8.5
CC:   @herbelin, @ppedrot

### LINKED ISSUE #10026: Error: Anomaly "index to an anonymous variable." Please report at http://coq.inria.fr/bugs/. after `Set Debug RAKAM`
#### Description of the problem

```coq
Require Import Coq.Lists.List.
Set Debug RAKAM.
Check fun _ => fold_right (fun A B => prod A B) unit _.
(* Error: Anomaly "index to an anonymous variable." Please report at http://coq.inria.fr/bugs/. *)
```

cc @ejgallego ?  (Hypothesis: This is in printing)

#### Coq Version

8.9.0

### PR DESCRIPTION
**Pull request by maximedenes**
I don't think there's a reason to treat such variables more severely
than unbound variables. This anomaly is often raised by debug printers
(e.g. when studying complex scenarios using `Set Unification Debug`),
and so makes debugging less convenient.

Incidentally, this fixes #3754 and fixes #10026.

### CODE REVIEW

**Comment by maximedenes** [comment]
@ppedrot can you take this one?

**Comment by maximedenes** [comment]
Wow, I'm surprised Mtac2 uses `set_detype_anonymous`. I thought it was a hack for the debugger.

**Comment by maximedenes** [comment]
Ah ah the overlay is going to be easy: they were using the API to print literally what this PR prints :)

File: pretyping/detyping.ml [hunk 1]
```diff
@@ -732,11 +729,13 @@ and detype_r d flags avoid env sigma t =
   match EConstr.kind sigma (collapse_appl sigma t) with
     | Rel n ->
       (try match lookup_name_of_rel n (fst env) with
-	 | Name id   -> GVar id
-	 | Anonymous -> GVar (!detype_anonymous n)
+         | Name id   -> GVar id
+         | Anonymous ->
+           let s = "_ANONYMOUS_REL_"^(string_of_int n) in
```
Comment (ejgallego) [inline pretyping/detyping.ml]: The printers above do raise `Not_found` however here you just print, is that intended?

Comment (maximedenes) [reply pretyping/detyping.ml]: Sorry, I'm not sure I see what you mean. Which printers above?

Comment (maximedenes) [reply pretyping/detyping.ml]: Oh, but the `Not_found` (raised by the debug printer) is caught immediately. So the only difference is that this patch distinguishes unbound rels and rels to anonymous binders.

**Comment by beta-ziliani** [comment]
> Wow, I'm surprised Mtac2 uses `set_detype_anonymous`. I thought it was a hack for the debugger.

Don't be surprise. We plugin devs will use every hacky API you provide. Learn from C++: every feature provided is a feature used :-P (BTW, I guess it was removed now, I can't find it in the code).

**Comment by maximedenes** [comment]
@ppedrot This is ready to go.

**Review by ppedrot — APPROVED** [review]
