### PR TITLE
Fix refine and eapply to mark shelved goals as non-resolvable, always

### LINKED ISSUE #10298: Unexpected typeclass resolution (the return of)
#### Description of the problem

A trivial "apply" of the identity function triggers typeclass resolution on evars, very unexpectedly. This is a serious backward incompatibility with Coq-8.9, for which I cannot figure any sensible work around. This seems to be similar to a prior issue #6583, but perhaps in a yet tricker form. As it stands, this undesirable behavior compromises all the infrastructure of my CFML program verification tool. 

After 2 hours of efforts, I finally managed to obtain a small, independent example. Here it is:

```coq
Set Implicit Arguments.

Generalizable Variables A.

Parameter val : Type.

Class Enc (A:Type) :=
  make_Enc { enc : A -> val }.

Global Instance Enc_dummy : Enc unit.
Admitted.

Definition FORM := forall A (EA:Enc A) (Q:A->Prop), Prop.

Definition IDF (F:FORM) : FORM := F.

Parameter ID : forall (G:Prop), G -> G.

Parameter EID : forall A (EA:Enc A) (F:FORM) (Q:A->Prop),
  F _ _ Q ->
  F _ _ Q.

Lemma bla : forall F,
  (forall A (EA:Enc A), IDF F EA (fun (X:A) => True) -> True) ->
  True.
Proof.
  intros F M.
  notypeclasses refine (M _ _ _).
  notypeclasses refine (EID _ _ _ _).
  eapply ID. (* undesirable instantiation of ?Goal0 *)
Abort.
```

#### Coq Version

coq 8.10beta1

### PR DESCRIPTION
**Pull request by mattam82**
**Kind:** bug fix / feature

Fixes / closes #10298 

Previously, goals created by `notypeclasses refine` would not be candidates for typeclass resolution but shelved goals would still be. With this PR, shelved goals are also removed from the typeclass resolution candidates, preventing out-of-order, unexpected instantiations by later, unrelated tactics and letting the script/tactic writer decide on which subgoals typeclass resolution shall be launched.

- [x] Added / updated test-suite
- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by charguer** [comment]
I tested the patch; here is some feedback.

Annotation
==========

First observation, the patch imposes a few more type annotations.

```
Class Enc (A:Type) : Type :=
  make_Enc { enc : A -> val }.

Lemma annotation_not_required_before : forall A `{EA:Enc A} x,
  enc x = enc x.
(* Before, x would be automatically infered to be of type A.
   But I don't think this is quite legitimate. *)

Lemma annotation_required_now : forall A `{EA:Enc A} (x:A),
  enc x = enc x.
```

Remark: this is similar requirement from "strict resolution" flag.
One can argue this to be a better behavior.
Thought it has a cost, for example if overloading "empty" using a
typeclass to denote empty sets/multisets/etc, one more frequently 
needs a type annotation.

Explicit Hints for typeclass resolution required
==========

What used to work with `Instance` now requires an explicit hint to succeed.

``` 
Class Decode (v:val) `{EA:Enc A} (V:A) : Type :=
  mk_Decode { decode : v = ``V }.

Definition Cons `{Enc A} (V:A) (p:loc) : val := 
  val_constr "Cons" (``V::``p::nil).

Instance Decode_Cons : forall `{EA:Enc A} (V:A) (v vp:val) (p:loc),
  Decode v V ->
  Decode vp p ->
  Decode (val_constr "Cons" (v::vp::nil)) (Cons V p).
Admitted.
``` 

Before the following goal would be solved by eauto with typeclass_instances.

``` 
  @Decode ('VCstr "Cons" (``x) (``q)) ?Goal ?Goal0 ?V
``` 

But now it requires an explicit hint for that to happen:

``` 
  Hint Extern 1 (Decode ('VCstr "Cons" _ _) _) =>
    eapply Decode_Cons : typeclass_instances.
``` 

Blocking bug to evar instantiation not respected
==========

It arises with the `notypeclass refine` invokation of a lemma that introduces
an `Enc ?A1` for a `?A1` that cannot be resolved immediately.
The lemma below needs not be understood in detail, the point is that EA1 does
not appear in the goal.

```
Lemma xlet_lemma : forall A1 (EA1:Enc A1) H `{EA:Enc A} (Q:A->hprop) (F1:Formula) (F2of:forall `{EA1:Enc A2},A2->Formula),
  H ==> F1 A1 EA1 (fun (X:A1) => (F2of X) A EA Q) -> 
  H ==> (Wpgen_let F1 (@F2of)) A EA Q.
```

I have a call site for this lemma where the following fails:

```
  notypeclasses refine (xlet_lemma _ _ _ _ _); foo.
```

whereas with with a dot it succeeds:

```
  notypeclasses refine (xlet_lemma _ _ _ _ _). foo.
```

I also have a fairly interesting situation where the following fails:

```
  notypeclasses refine (xlet_lemma _ _ _ _ _).
  notypeclasses refine (xlet_lemma _ _ _ _ _). 
  foo.
```

but replacing the first dot with a semi-column makes it work.

```
  notypeclasses refine (xlet_lemma _ _ _ _ _);
  notypeclasses refine (xlet_lemma _ _ _ _ _). 
  foo.
```

I have a hard time though minimizing the example.

**Comment by mattam82** [comment]
Thanks for the feedback! For the first two points it is strange that you see a change of behavior due to this patch, as it should only impact `notypeclasses refine`, rather than changes already introduced in 8.10 by the previous patch. Could that be the case? I'll investigate the third.

**Comment by charguer** [comment]
Sorry for the confusion, I should not have written "the patch imposes" but "8.10+patch imposes".
I am evaluating here the final result.

**Comment by charguer** [comment]
The good news is that

```
 eapply @xlet_lemma;  eapply @xlet_lemma; foo
``` 

works, and is consistent with

```
 eapply @xlet_lemma. eapply @xlet_lemma; foo
``` 

So it seems to resolve most of my issues.

And definitely a bug related to `notypeclass refine`  in the handling of evars.

I'll continue trying to compile all of CFML2.

**Comment by charguer** [comment]
@mattam82 I have compiled quite a few files from CFML2, so I feel we're getting quite close.
There is one bug remaining, however, that needs to be solved, and that is not related to `notypeclass refine` because I no longer use this tactic anywhere (gladly).

It's related to a ` foo; bar` not equivalent to `foo. bar.`. More precisely, the tactic `foo` introduces `?A:Type` and `?EA:Enc A`, and that `bar` wishes to unify `?A` and `?EA` with, say, `bool` and `Enc bool`, and that unification fails.

 I'll try harder to obtain a minimal example, but it's not so easy, because there are cases where it succeeds.

**Comment by charguer** [comment]
Ok, i found a cause for the issue: the tactic `bar` in `foo; bar` uses `apply` and `rewrite`. If I change them to `eapply` and `erewrite`, then it works. Maybe that gives you some hint on what happens here.

Note that I would like to continue using `apply` and `rewrite` from `bar`  to manipulate goals that contain  evars introduced by `foo`. Note that the calls do not necessarily involve unification of evars, for example, I have one call to "rewrite associativity" that I need to change to `erewrite` for it to succeed.

**Comment by charguer** [comment]
@mattam82 any idea what could cause the difference in behavior between apply and eapply with respect to instantiation of existing evars? I thought than apply would simply refuse to introduce new evars, but that it would accept unifying existing ones. Isn't that the spec?

```
Lemma test : (forall (x:nat), x = 3 -> True) -> True.
Proof. intros M. try apply M. eapply M. apply eq_refl. (*instantiates ?x*) Qed.
```

**Comment by mattam82** [comment]
@charguer thanks for the feedback, I'll have a look at the apply/eapply discrepancy

**Comment by mattam82** [comment]
For #1 Annotation, that's because you use `Hint Mode Enc +.`? Otherwise I can't reproduce it.

**Comment by mattam82** [comment]
For #2 Explicit hints, can you make a self-contained example?

**Comment by mattam82** [comment]
For the last bug, in your example `apply` does instantiate the pre-existing evar, and your problem is when it doesn't, right? Do you have an example of that?

**Comment by mattam82** [comment]
It's quite probable that you need `erewrite` because there are still uninstantiated evars in implicit arguments, no?

**Comment by charguer** [comment]
I'll try to prepare self-contained examples, but it's not such an easy thing.

**Comment by charguer** [comment]
Regarding annotation: indeed I was using `Set Typeclasses Strict Resolution.` which is what forced the annotation. However, I see no effect of `Hint Mode Enc +.`.

```

Set Implicit Arguments.
Generalizable Variables A B.
Parameter val : Type.


(************************************)
(* About annotations: effect of strict resolution *)

Module Annotation1.

Set Typeclasses Strict Resolution.

Class Enc (A:Type) : Type :=
  make_Enc { enc : A -> val }.

(* fails without (x:A) annotation 
Lemma annotation_not_required_before : forall A `{EA:Enc A} x,
  enc x = enc x.
Abort.
*)
Lemma annotation_required : forall A `{EA:Enc A} (x:A),
  enc x = enc x.
Abort.

End Annotation1.


(************************************)
(* About annotations: no effect of hint mode *)

Module Annotation2.

Class Enc (A:Type) : Type :=
  make_Enc { enc : A -> val }.

Hint Mode Enc +.

Lemma annotation_not_required_before : forall A `{EA:Enc A} x,
  enc x = enc x.
Abort.

End Annotation2.
```

**Comment by charguer** [comment]
Self contained investigation of the typeclass resolution failure in strict mode.
Maybe you can explain that all of this is intended behavior. But I'm curious about the reasons, because I wasn't able to forge myself the mental model of what's going on.

```

Set Implicit Arguments.
Generalizable Variables A B.
Parameter val : Type.


Set Typeclasses Strict Resolution.

Class Enc (A:Type) : Type :=
  make_Enc { enc : A -> val }.

Instance Enc_val : Enc val.
Proof using. constructor. eapply (fun (x:val) => x). Defined.

Class Decode (v:val) `{EA:Enc A} (V:A) : Type :=
  make_Decode { decode : v = enc V }.

Arguments decode v {A} {EA} {V} {Decode}.

Instance Decode_enc : forall `{EA:Enc A} (V:A),
  Decode (enc V) V.
Proof using. intros. constructor. auto. Defined.


Parameter val_one : val -> val.

Definition One A `{EA:Enc A} (V:A) : val := 
  val_one (enc V).

Instance Decode_one : forall `{EA:Enc A} (V:A) (v:val),
  Decode v V ->
  Decode (val_one v) (One V).
Proof using.
  intros. unfold One. eapply make_Decode.
  simpl. f_equal. inversion H. auto.
Qed.


Parameter P : val -> Prop.

Parameter foo : forall (v:val) A1 (EA1:Enc A1) (X:A1), 
 (Decode v X) -> P v.

Lemma test_in_strict_resolution_mode : forall B `{EB:Enc B} (Y:B),
 P (val_one (enc Y)).
Proof.
  (* The intention of this proof is to apply [foo]
     and instantiate [X] with [One Y]. *)
  intros.
  eapply @foo.
  (* notypeclasses refine (@foo _ _ _ _ _). *)
  Show Existentials.
  (* here [?X] has type [?A1] with [?EA1:Enc ?A1] unresolved. *)
  (* Now, typeclass resolution fails. *)
  eauto with typeclass_instances.
  Show Existentials.
  eapply @Decode_one. 
  (* Observe how a manual application of Decode_one introduces
     fresh [?A] and [?EA:Enc ?A], and refines [?X] to [One ?V],
     and [?A1] to [val]. *)
  Show Existentials.
  eauto with typeclass_instances.
  (* Question: why is [eauto with typeclass_instances]
     not attempting to apply Decode_one? *)   
Abort.

(* Play this proof after commenting strict resolution and the
   lemma above. *)
Lemma test_without_strict_resolution_mode : forall B `{EB:Enc B} (Y:B),
 P (val_one (enc Y)).
Proof.
  intros.
  (* Remark: here, if not using "Set Typeclasses Strict Resolution.",
     then [eapply @foo] would systematically instantiate [A1]
     as [A], even though there is not absolutely evidence that
     this the right thing to do. In that case, 
     [notypeclasses refine (@foo _ _ _ _ _)] is necessary. *)
  (* eapply @foo. Show Existentials. *)
  notypeclasses refine (@foo _ _ _ _ _). 
  Show Existentials.
  (* here, typeclass resolution succeeds, by applying Decode_one. *)
  (* eapply Decode_one. Show Existentials. *)
  eauto with typeclass_instances.
Abort.
```

**Comment by charguer** [comment]
Regarding the behavior of `notypeclass refine`, with respect to a typeclass declared in "strict resolution mode".

It's too hard to isolate the behavior in a simple example, but I can show it to you on my screen. In short, I have a script (where M denotes an hypothesis):

```
  eapply xlet_lemma.
  eapply xapp_lemma. 
  eauto. (* succeeds to perform [eapply M]; note that [apply M] suceeds also *) 
```
yet

```
  notypeclasses refine (xlet_lemma _ _ _ _ _).
  eapply xapp_lemma. 
  eauto. (* fails to invoke [eapply M]; not that [apply M] would fail here. *)
  eapply M. (* suceeds *)
```

This suggests that use of `notypeclasses refine` has impact on what `eauto` can later do with evars.

**Comment by JasonGross** [comment]
@charguer in case you are not aware, you might be interested in my [bug minimizer](https://github.com/JasonGross/coq-tools/blob/master/find-bug.py) (which I've just added to the wiki [here](https://github.com/coq/coq/wiki/Tools#bug-minimizer)), which will automatically inline dependencies and remove unneeded code to make a small stand-alone test case exhibiting a bug (as defined by emitting a particular error message without changing whichever theorem/proof block/vernacular of the initial code resulted in the error message).  You can also have it produce a small test case that works fine (has no error message) with one version of Coq while having a particular error message with another version of Coq (it'll only remove lines that result in the file still passing on the one version of Coq and still emitting the same error message with the other version of Coq).

**Comment by mattam82** [comment]
I finally got what happened: we were no longer marking goals not resolved by the `eapply` as non-candidates for later instantiations, in the example:

```

Set Implicit Arguments.

Generalizable Variables A B.
Parameter val: Type.

Class Enc (A:Type) : Type :=
  make_Enc { enc : A -> val }.

Hint Mode Enc + : typeclass_instances.

Parameter bar : forall A (EA:Enc A), EA = EA.

Parameter foo : forall (P:Prop),
   P ->
   P = P ->
   True.

Parameter id : forall (P:Prop),
  P -> P.

  Check enc.

  Lemma test : True.
  eapply foo; [ eapply bar | apply id]. apply id.
  (* eapply bar introduces an unresolved typeclass evar that is no longer
     a candidate after the application (eapply should leave typeclass goals shelved).
     We ensure that this happens also _across_ goals in `[ | ]` and not only at `.`..
      *)
  Abort.
```
This was indeed an undetected regression from 8.9 behavior.

**Comment by charguer** [comment]
@mattam82 I will test your one-line fix tomorrow, to see whether all my stuff compiles fine with it.

**Comment by charguer** [comment]
HI. The patch works successfully.  I could compile all my proof scripts, and my problems are gone away. Hopefully this can make it to 8.10. (Won't be a drama if it goes to 8.10.1.)

**Comment by mattam82** [comment]
Great ! Indeed it will probably be in a patch release, unless we figure out that the two failures in the CI are legitimate

**Comment by charguer** [comment]
Note: I did have one or two occurrences where an extra type annotation was required when compiling with your latest fix.

**Comment by mattam82** [comment]
The fixes were independent of the Hint Mode/Strict Resolution changes?

**Comment by charguer** [comment]
I think so.  Goal is:

```
A : Type
B : Type
x : A
H : x \in \{}
______________________________________(1/1)
False
```

Before your last fix:

```
eapply in_empty; typeclasses eauto with typeclasses_instances.
```

would solve it.

After your last fix, I see:

```
All the remaining goals are on the shelf:
In_empty
```

The type of  `in_empty` is:
```
 forall (A T : Type) (BI : BagIn A T) (BE : BagEmpty T), In_empty -> forall x, x \in \{} -> False.
```

Thus, when exactly the hypothesis H is used to prove `x \in \{}` w.r.t. resolution would matter.
I am not very suprized that I need to invoke `eapply (@in_empty A)` or `eapply (@in_empty H)` here.

**Comment by mattam82** [comment]
IIUC `In_empty` is a class though? Shouldn't it be discharged automatically?

**Comment by charguer** [comment]
It does not seem to be a big deal though. But here are the details:

In Coq 8.10-beta1:
```
eapply @in_empty; typeclasses eauto with typeclass_instances. => solves the goal
eapply @in_empty; eauto with typeclass_instances. => solves the goal
eapply in_empty; typeclasses eauto with typeclass_instances. => leaves Is_empty on the shelve
eapply in_empty; eauto with typeclass_instances. => solves the goal
```

In your patched version:
```
eapply @in_empty; typeclasses eauto with typeclass_instances. => solves the goal
eapply @in_empty; eauto with typeclass_instances. => solves the goal
eapply in_empty; typeclasses eauto with typeclass_instances. => leaves Is_empty on the shelve
eapply in_empty; eauto with typeclass_instances. =>  leaves Is_empty on the shelve
```
The last case corresponds to the script that I had, and lead to the observable change. 

As you see, it's quite subtle. What `eapply @in_empty.` produces are the two subgoals:
```
______________________________________(1/2)
@In_empty ?A ?T ?BI ?BE
______________________________________(2/2)
@is_in ?A ?T ?BI ?x (@empty ?T ?BE)
```

Details: `git clone git@gitlab.inria.fr:charguer/tlc.git -b igration-to-coq-8.10`, file LibMap.v line 254.

**Comment by mattam82** [comment]
Sadly, the Iris failure shows that the implemented semantics of this patch might not satisfy everyone. The question is: when should typeclasses be resolved, and when they should be shelved and left outside of typeclass resolution. The current patch makes an `eapply foo` which involves typeclasses in its dependent arguments (which really are evars like ?someTC in `@foo ?X (?someTc : Class ?X)` TRY to resolve them after unification of the conclusion of the lemma with the goal,  and if that fails, shelves it and marks it as unresolvable (it won't be picked up by later typeclass resolution calls, like the `apply id` in this issues' example). 
For `notypeclasses refine foo` it is even stronger and just removes all evars of foo (even the ones shelved by the refine) from the typeclass candidate set: that was the initial whish of @charguer.
I find this more uniform too to enforce that `notypeclasses refine` really does not introduce typeclass constraint. However,  in Iris, there is a problem with:

```
(* Check that typeclasses are not resolved too early *)
Lemma test_TC_resolution `{!BiAffine PROP} (Φ : nat → PROP) l x :
  x ∈ l → ([∗ list] y ∈ l, Φ y) -∗ Φ x.
Proof.
  iIntros (Hp) "HT".
  iDestruct (big_sepL_elem_of _ (* Φ *) _ _ Hp with "HT") as "Hp".
  done. Unshelve. typeclasses eauto.
Qed.
```

I don't understand exactly how `iDestruct` is implemented, but apparently typeclass resolution is tried on an underspecified `Absorbing (?phi x)` goal, leading to it being shelved (and removed from typeclass constraints) and to remain after the `done`. If we uncomment the (* Φ *) then the typechecking of the lemma application gives enough information to resolve the `Absorbing` constraint early, but I also understand that it is precisely . NOT what the Iris developer want, and would rather postpone it until later constraints make that side condition instantiated enough.

FTR, the trace of resolution at the `iDestruct` call with the current patch is:
```
1: looking for (Absorbing (?Φ x)) with backtracking
1: no match for (Absorbing (?Φ x)), 0 possibilities
1: looking for (AsEmpValid (([∗ list] y ∈ l, ?Φ y) -∗ ?Φ x) ?b0) with backtracking
1.1: simple apply @as_emp_valid_here on
(AsEmpValid (([∗ list] y ∈ l, ?Φ y) -∗ ?Φ x) ?b0), 1 subgoal(s)
1.1-1 : (AsEmpValid0 (([∗ list] y ∈ l, ?Φ y) -∗ ?Φ x) ?b0)
1.1-1: looking for (AsEmpValid0 (([∗ list] y ∈ l, ?Φ y) -∗ ?Φ x) ?b0) with backtracking
1.1-1.1: simple apply @class_instances_bi.as_emp_valid_entails on
(AsEmpValid0 (([∗ list] y ∈ l, ?Φ y) -∗ ?Φ x) ?b0), 0 subgoal(s)
1: looking for (Decision ([spec_patterns.SIdent "HT" []] ≠ [])) without backtracking
1.1: simple apply @not_dec on
(Decision ([spec_patterns.SIdent "HT" []] ≠ [])), 1 subgoal(s)
1.1-1 : (Decision ([spec_patterns.SIdent "HT" []] = []))
1.1-1: looking for (Decision ([spec_patterns.SIdent "HT" []] = [])) without backtracking
1.1-1.1: simple apply @list_eq_nil_dec on
(Decision ([spec_patterns.SIdent "HT" []] = [])), 0 subgoal(s)
1: looking for (IntoWand true false (([∗ list] y ∈ l, ?Φ y) -∗ ?Φ x)
	              ([∗ list] y ∈ l, Φ y) ?Goal) with backtracking
1.1: simple apply @class_instances_bi.into_wand_wand on
(IntoWand true false (([∗ list] y ∈ l, ?Φ y) -∗ ?Φ x) 
   ([∗ list] y ∈ l, Φ y) ?Goal), 1 subgoal(s)
1.1-1 : (FromAssumption false ([∗ list] y ∈ l, Φ y) ([∗ list] y ∈ l, ?Φ y))
1.1-1: looking for (FromAssumption false ([∗ list] y ∈ l, Φ y)
	                  ([∗ list] y ∈ l, ?Φ y)) with backtracking
1.1-1.1: simple apply @class_instances_bi.from_assumption_exact on
(FromAssumption false ([∗ list] y ∈ l, Φ y) ([∗ list] y ∈ l, ?Φ y)), 0 subgoal(s) 
```

**Comment by mattam82** [comment]
Note that
```
unshelve iDestruct (big_sepL_elem_of _ _ _ Hp with "HT") as "Hp";
   [once typeclasses eauto|].
```
Also works.

**Comment by mattam82** [comment]
@charguer your issue is a similar problem:  eapply in_empty can't fill in the `BagEmpty ?A ?T` constraint, so all constraints are put on the shelf and set as non-resolvable. The following eauto/typeclasses eauto's can resolve the indices using H (first subgoal). Before my patch, I guess a side-effect call to resolution of eauto was solving the remaining typeclass candidates, but there are non left anymore after that patch, so they just stay on the shelf.

**Comment by mattam82** [comment]
@robbertkrebbers @RalfJung I would really like to have your feedback on this issue :)

**Comment by mattam82** [comment]
I would also like to know what's the resolution trace for the `iDestruct` call currently in math-classes if someone has it handy.

**Comment by mattam82** [comment]
Right, sorry to ping you Arthur, indeed, I would also expect Iris should be happy with this behavior, but it's broken ATM

**Comment by charguer** [comment]
Noproblme. Nevertheless my question remains: is Iris currently setting up the Hint Mode or not?

**Comment by robbertkrebbers** [comment]
I have been swamped with deadlines, so sorry for not responding. It will probably be only after the CPP deadline that I have time to properly look into this.

To answer @charguer's question, Iris already sets `Hint Mode` for `Absorbing`:

```
Hint Mode Absorbing + ! : typeclass_instances.
```

**Comment by charguer** [comment]
Maybe it is possible for `iDestruct` to use `notypeclass refine` (or a variant of it) instead of `eapply` to prevent eager resolution?

**Comment by RalfJung** [comment]
I'm afraid I know little about the typeclass magic in the Iris proof mode. What I do know is that we had (and in some cases still have) lots of trouble with typeclasses being resolved either too early or too late. The current code, in my understanding, is the result of lots of experiments until all our test cases passed -- it's not like we have a clear idea of what the shelved goals are at any point during the script, and the effect of various tactics on type-class-related goals often feels entirely random. I certainly have no mental model of the order in which TC resolution happens when there are many goals and how shelved goals play into that. This is all very fragile.

To our defense, it's not like there is any proper documentation of all of this that we could have worked against...^^

**Comment by mattam82** [comment]
Indeed, the interaction of typeclass resolution with tactics is ad-hoc. At the time we introduced them we mainly thought about what to do with `Definition`. So, let me try to give you an idea of when typeclass resolution is launched with common tactics: 
- for `apply` it is launched after unification of the goal with the lemma's conclusion and will fail if 
  there remains unresolved typeclasses *in the dependent and maximally inserted arguments*. Then it turns independent arguments into subgoals. There might be classes there, they won't get resolved. A goal is not a candidate for "implicit" typeclass resolution, one has to call `typeclasses eauto` explicitely to resolve it with typeclass instances as the implicit resolution would.
- for `eapply` it is also launched after unification of the goal with the lemma's conclusion and will *not* fail if there remains unresolved typeclasses *in the dependent and maximally inserted arguments*, but rather leave the constraints as shelved subgoals, which are no longer candidates for typeclass resolution. Then it turns independent arguments into subgoals. There might be classes there, they won't get resolved.
- for `destruct c`, it first tries to launch resolution on the typeclass constraints generated by elaborating `c`, then finds/builds the eliminator of c's type and looks for subterms of the goal to unify with `c`, then generalize those and finally builds the complete eliminator application, producing subgoals for the branches.

**Comment by mattam82** [comment]
The idea of explicit scoping of resolution is interesting. With #10858 you can control it: we can now leave the subgoals generated by an `eapply` as shelved and still typeclass candidates if they are only stuck (i.e. not respecting the goals). So it becomes less of an issue that e.g. destruct calls resolution early because we will keep on going and unify the term to destruct with subterms of the goal, which should give enough information to get the constraints unstuck for the second run of resolution. The big question is still: when do we fail when there are unresolved constraints left. In that PR, shelved goals can remain unsolved because the constraints are stuck, but one can do `unshelve tac; solve [typeclasses eauto]` to ensure no typeclass constraints remain, essentially scoping the resolution of typeclass constraints generated by `tac`.

**Comment by charguer** [comment]
Thanks @mattam82 for a tentative specification. However, I am still missing several elements: 
- what is the behavior on a call to refine?with respect to typeclasses that pre-exist

**Comment by charguer** [comment]
What I get from @RalfJung's message is that any minor change to the behavior of typeclass resolution will likely break their code somehow. I guess, what we'd like is thus a once-and-forall migration to a mechanism for which we can have a simple mental model and that enables us to express our patterns, somehow. With a compatibility flag somewhere, we could deal with the migration.

**Comment by robbertkrebbers** [comment]
I tried to look into this, but I cannot get std++ to compile due to https://github.com/coq/coq/issues/10957

**Comment by robbertkrebbers** [comment]
I created an MR for Iris: https://gitlab.mpi-sws.org/iris/iris/merge_requests/329/

Now let's hope it doesn't break too many of the Iris reverse dependencies and it's backwards compatible with older versions of Coq.

**Comment by robbertkrebbers** [comment]
Bad news.

- Iris uses a hack to get around https://github.com/coq/coq/issues/6583, see https://gitlab.mpi-sws.org/iris/iris/blob/master/theories/proofmode/ltac_tactics.v#L747. Basically, it wraps certain arguments into an `id` to stop TC search from eagerly resolving them.
- This hack stopped working when switching to `notypeclasses refine` in the tactics related to `iDestruct`, which was needed to provide compatibility with this PR.

So, I'm afraid to provide compatibility with this PR, I also need https://github.com/coq/coq/issues/6583 to be fixed.

**Comment by charguer** [comment]
@mattam82: I still have an issue. If I take my initial bug report, and define `Decode` as a definition rather than as a typeclass, I still have an `eapply` that performs an overly-aggressive instantiation. Could you please check whether this is intended behavior?

```
Set Implicit Arguments.
Generalizable Variables A B.
Parameter val : Type.

Class Enc (A:Type) : Type :=
  make_Enc { enc : A -> val }.

Hint Mode Enc +.

Instance Enc_val : Enc val.
Proof using. constructor. eapply (fun (x:val) => x). Defined.

Definition Decode (v:val) `{EA:Enc A} (V:A) : Type :=
  v = enc V.

Lemma Decode_enc : forall `{EA:Enc A} (V:A),
  Decode (enc V) V.
Proof using. intros. hnf. auto. Qed.

Hint Resolve @Decode_enc.

Parameter val_one : val -> val.

Definition One A `{EA:Enc A} (V:A) : val := 
  val_one (enc V).

Lemma Decode_one : forall `{EA:Enc A} (V:A) (v:val),
  Decode v V ->
  Decode (val_one v) (One V).
Proof using.
  intros. unfold One. unfold Decode.
  simpl. f_equal. inversion X. auto.
Qed.

Hint Resolve @Decode_one.

Parameter P : val -> Prop.

Parameter foo : forall (v:val) A1 (EA1:Enc A1) (X:A1), 
 (Decode v X) -> P v.

 Set Typeclasses Debug Verbosity  2.
 Set Printing All.

Lemma test : forall B `{EB:Enc B} (Y:B),
 P (val_one (enc Y)).
Proof.
  intros.
  (* ========> Bug: [eapply @foo] instantiates [A] as [B], it should not. *)
  (* I would instead expect it to perform the same thing as the following tactic,
   which is also the behavior that one gets when `Decode` is defined as typeclass *)
  notypeclasses refine (@foo _ _ _ _ _).
  Show Existentials.
  (* Remark: [typeclasses eauto]. fails.  *)
  eauto.
  (* Details: eapply @Decode_one. eapply @Decode_enc. *)
Abort.
```


For the record, I include the original script using the typeclass (it works fine thanks to the bugfix).

```
Set Implicit Arguments.
Generalizable Variables A B.
Parameter val : Type.

Class Enc (A:Type) : Type :=
  make_Enc { enc : A -> val }.

Hint Mode Enc + : typeclass_instances.

Instance Enc_val : Enc val.
Proof using. constructor. eapply (fun (x:val) => x). Defined.

Class Decode (v:val) `{EA:Enc A} (V:A) : Type :=
  make_Decode { decode : v = enc V }.

Arguments decode v {A} {EA} {V} {Decode}.

Instance Decode_enc : forall `{EA:Enc A} (V:A),
  Decode (enc V) V.
Proof using. intros. constructor. auto. Defined.

Parameter val_one : val -> val.

Definition One A `{EA:Enc A} (V:A) : val :=
  val_one (enc V).

Instance Decode_one : forall `{EA:Enc A} (V:A) (v:val),
  Decode v V ->
  Decode (val_one v) (One V).
Proof using.
  intros. unfold One. eapply make_Decode.
  simpl. f_equal. inversion H. auto.
Qed.

Parameter P : val -> Prop.

Parameter foo : forall (v:val) A1 (EA1:Enc A1) (X:A1),
 (Decode v X) -> P v.

 Set Typeclasses Debug Verbosity  2.
 Set Printing All.

Lemma test : forall B `{EB:Enc B} (Y:B),
 P (val_one (enc Y)).
Proof.
  intros.
   eapply @foo.
  (* not needed: notypeclasses refine (@foo _ _ _ _ _).*)
  Show Existentials.
  (* here, typeclass resolution succeeds, by applying Decode_one. *)
  (* eapply Decode_one. Show Existentials. *)
  typeclasses eauto with typeclass_instances.
  (* warning: eauto with typeclass_instances fails *)
  (* eapply @Decode_one. eapply @Decode_enc. *)
Abort.
```

**Comment by mattam82** [comment]
You should rather use: `Hint Mode Enc + : typeclass_instances` in the above code as well.
We don't care about hints from the implicit `core` database so that declaration was not taken into account and typeclass resolution was not blocked by modes.

**Comment by charguer** [comment]
> We don't care about hints from the implicit core database.

Ah, sorry, I missed the annotation once again.  Indeed, it works with the annotation.

When does it make sense to use another database than `typeclass_instances` for `Hint Mode`?
Would it make sense to issue a warning (or an error?) if another database is selected?

**Comment by robbertkrebbers** [comment]
I fix in Iris has landed: https://gitlab.mpi-sws.org/iris/iris/merge_requests/329 I have also updated the reverse dependencies of Iris, like RustBelt.

It took quite a lot of effort, since I basically had to change many of our proof mode tactics to use `notypeclasses refine` instead of `apply`.

**Comment by mattam82** [comment]
That's really good news @robbertkrebbers, and it seems from the MR comment that it does help clean-up and make apparent the model for calling resolution.  I guess we can now relaunch the CI on iris-lambda-rust and perennial?

**Comment by robbertkrebbers** [comment]
> I guess we can now relaunch the CI on iris-lambda-rust and perennial?

For lambda-rust it should be fine, since I've ported that. Perennial has not been ported yet, since I don't maintain that development. The probably of it working out of the box is small. The CI of @tchajed and @jtassero will probably inform them of possible breakage tonight.

**Comment by tchajed** [comment]
I started updating Perennial to be compatible with [iris/iris!329](https://gitlab.mpi-sws.org/iris/iris/merge_requests/329), but it will indeed not be an easy fix. It would be good to give us some time to fix things on our end before this merges.

CC: @jtassarotti

**Comment by mattam82** [comment]
@tchajed sure, just tell me when you’re ready!

**Comment by tchajed** [comment]
@mattam82 technically we're good now and Perennial master should build with this PR, but I fixed the backwards incompatibility in a brute force way by just calling `typeclasses eauto` on the new shelved goals: https://github.com/mit-pdos/perennial/commit/03ee3cfe726e69721c7adbb7ec6a8545a20df752. I suspect the solution is to change something in Iris but I didn't dig into what's happening.

**Comment by mattam82** [comment]
This is ready now!

**Comment by mattam82** [comment]
Adding Maxime to the loop as it is related to the shelving issues we're looking at these days.

**Review by Zimmi48 — APPROVED** [review]

File: proofs/clenvtac.ml [hunk 1]
```diff
@@ -72,7 +72,7 @@ let clenv_refine ?(with_evars=false) ?(with_classes=true) clenv =
         Typeclasses.resolve_typeclasses ~filter:Typeclasses.all_evars
           ~fail:(not with_evars) clenv.env clenv.evd
       in
-      Typeclasses.make_unresolvables (fun x -> List.mem_f Evar.equal x evars) evd'
+      Typeclasses.make_unresolvables (fun x -> true) evd'
```
Comment (maximedenes) [inline proofs/clenvtac.ml]: I think this would be worth a comment explaining what we are doing.

File: proofs/refine.mli [hunk 2]
```diff
@@ -19,15 +19,17 @@ open Proofview
...
+val refine : ?with_classes:bool -> typecheck:bool -> (Evd.evar_map -> Evd.evar_map * EConstr.t) -> unit tactic
+(** In [refine ?(with_classes=true) ~typecheck t], [t] is a term with holes under some
     [evar_map] context. The term [t] is used as a partial solution
     for the current goal (refine is a goal-dependent tactic), the
     new holes created by [t] become the new subgoals. Exceptions
     raised during the interpretation of [t] are caught and result in
-    tactic failures. If [typecheck] is [true] [t] is type-checked beforehand. *)
+    tactic failures. If [typecheck] is [true] [t] is type-checked beforehand.
+    If [with_classes] is false then shelved evars are marked as unresolvable
+    in addition to goals. *)
```
Comment (maximedenes) [inline proofs/refine.mli]: I read "in addition to goals", but could find only the code which marks the shelved evars as unresolvable. Where are goals marked as unresolvable?

Comment (mattam82) [reply proofs/refine.mli]: That's the `mark_as_goals` line in the primitive refine which performs this,  we always remove evars marked as goals from the set of typeclass evars.

File: proofs/clenvtac.ml (hunk 1 above)
Comment (mattam82) [reply proofs/clenvtac.ml]: True

File: proofs/refine.mli (hunk 2 above)
Comment (maximedenes) [reply proofs/refine.mli]: Ah! I see, thanks. And what does marking an evar as a goal do else? Couldn't we mark shelved goals as goals?

Comment (maximedenes) [reply proofs/refine.mli]: (said otherwise, I'm wondering why we need to apply two different operations on generated goals, depending on whether they are shelved or not).

Comment (mattam82) [reply proofs/refine.mli]: That's a good point. The problem is that the code marking goals should not mark shelved evars as unresolvable always, precisely for the call to resolution above. We can certainly simplify that logic in the next step.

Comment (maximedenes) [reply proofs/refine.mli]: Yeah, sure, I'd expect one operation being applied to two possible things (unshelved goals or all goals), depending on the flag. But here we have two operations being applied to two different things.

On a separate note, does `unshelve` mark evars as goals or unresolvable? Otherwise, I'd expect strange behaviors, like `refine; unshelve` not behaving the same as `simple refine` w.r.t. typeclasses.

Comment (mattam82) [reply proofs/refine.mli]: Maybe that possibility is not necessary and we should rather always "scope" the typeclass resolution to a single call to refine

Comment (mattam82) [reply proofs/refine.mli]: marking as a goal is the same as marking unresolvable.

Comment (mattam82) [reply proofs/refine.mli]: There's no `unshelve` tactic, but you're right that `unshelve refine foo`, in case there remains typeclass goals shelved would put them back in the goal list without removing them from the typeclass evar set.

Comment (mattam82) [reply proofs/refine.mli]: So it would seem that the same "shelving also implies not resolvable" semantics could be used for all variants of the refine tactic.

**Comment by mattam82** [comment]
@maximedenes let's try the simpler version where indeed all subgoals shelved or not are marked as unresolvable. It already passes the test-suite.

File: proofs/refine.mli (hunk 2 above)
Comment (maximedenes) [reply proofs/refine.mli]: Ah yes, it would be simpler, indeed.

**Comment by mattam82** [comment]
@maximedenes good news, it works! The semantics of all variants of refine is hence simpler: none of the generated subgoals are resolvable. And combination with `unshelve` will work as expected.
I'll update the doc to reflect this.

**Comment by mattam82** [comment]
I also squashed everything down to 1 commit.

**Review by maximedenes — APPROVED** [review]
I like this new version, it is much simpler to explain.

**Comment by maximedenes** [comment]
@mattam82 This PR introduces `test-suite/bugs/closed/bug_10762.v` but that's the number of this PR. What issue was it meant to point to?
