### PR TITLE
Show tooltips for syntax errors

### LINKED ISSUE #19152: Tooltip for syntax errors is highlighted but not displayed
### Description of the problem

The point of the error is highlighted as if it was a tooltip but the tooltip won't display.

image

This is the expected tooltip:

image

### Small Coq file to reproduce the bug

```coq
Goal True.
apply *.
```

### Version of Coq where this bug occurs

8.20+alpha

### Last version of Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by jfehrle**
Sentences with syntax errors were immediately removed from the document, but the tooltip can't be shown in that case.  This PR works around that.
 
This also substitutes HTML escape sequences for reserved characters in the tooltip text such as `"&'<>`.  This prevented tooltip messages containing those characters from displaying (such as the one shown in #19152).

Fixes / closes #19152

- [x] Added **changelog**.
- [ ] Added / updated **documentation**.

### CODE REVIEW

File: ide/coqide/coqOps.ml [hunk 1]
```diff
@@ -402,7 +402,20 @@ object(self)
...
       let msg = String.concat "\n" (CList.uniquize ss) in
+      let markup_escape msg =
+        let buf = Buffer.create (String.length msg) in
+        String.iter (fun c -> match c with
+          | '\'' -> Buffer.add_string buf "&#39;"
+          | '<' -> Buffer.add_string buf "&#60;"
+          | '>' -> Buffer.add_string buf "&#62;"
+          | '"' -> Buffer.add_string buf "&#34;"
+          | c -> Buffer.add_char buf c
+        ) msg;
```
Comment (herbelin) [inline ide/coqide/coqOps.ml:415]: Is this general-purpose and worth to be added as a "util"?

**Review by herbelin — APPROVED** [review]
Not really competent to review the gtk part. At least, the fix works for me

File: ide/coqide/coqOps.ml (hunk 1 above)
Comment (jfehrle) [reply ide/coqide/coqOps.ml:415]: The usual escapes for HTML are `"&'<>`, I will update.  That makes it general purpose.  Shall I put it in Ideutils or Util?

Comment (herbelin) [reply ide/coqide/coqOps.ml:415]: I would say in `clib/cString.ml`, or, if considered too specific by some of us, in `ideutils.ml`.

Comment (jfehrle) [reply ide/coqide/coqOps.ml]: Done.

**Comment by jfehrle** [comment]
@coqbot: run full ci

**Comment by jfehrle** [comment]
Oddly, I get a spurious failure email for macOS that doesn't show in the status on this page:

```
Coq < File "/Users/runner/work/coq/coq/test-suite/../_install_ci/lib/coq/../coq-core/dev/ml_toplevel/include_utilities", line 29, characters 43-68:
29 |   Option.get (Global.body_of_constant_body Library.indirect_accessor b)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: Library.indirect_accessor
Most commands should not be accessing opaque data.
```

**Comment by SkySkimmer** [comment]
@herbelin are you merging?

**Comment by proux01** [comment]
This seems ready, let's merge before branching.

@coqbot merge now
