### PR TITLE
Convert char/byte offsets where needed for error messages, debugger

### LINKED ISSUE #15235: Error highlighting in CoqIDE is not correct in the presence of unicode characters (regression)
#### Description of the problem
I have been observing incorrect underlining for various errors. Here is an example showing some small displacement:
```coq
Axiom A : Type.
Axiom Hc : A -> Prop.

Theorem soundness φ : Hc φ -> forall M, Satisfies M φ.
```

In CoqIDE at least, Satisfies is not underlined correctly.

#### Coq Version
8.15

### PR DESCRIPTION
**Pull request by jfehrle**
I fixed two errors:

First, the the initial offset of the added sentence in the `add` XML call was passing a character offset rather than the byte offset Coq expected.  That gave an incorrect offset for any breakpoint that appears after the first UTF-8 character in the buffer, causing the breakpoint to be ignored.

Second, the issue described in #15235.  The byte to char offset conversion needs to be relative to the buffer and not to the phrase.  (Before the debugger changes, the `add` call used offsets relative to the beginning of the phrase and the `loc` for the error message would be relative to the phrase.  So it needed to change.)

I don't know how to trigger the code in `get_errors` and `attach_tooltip` so I didn't test them, but I'm pretty sure they need the same adjustment.  (If someone would tell me how to trigger these, I'll test them.)

Fixes: #15235

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
> Second, the issue described in #15235. The byte to char offset conversion needs to be relative to the buffer and not to the phrase. (Before the debugger changes, the `add` call used offsets relative to the beginning of the phrase and the `loc` for the error message would be relative to the phrase. So it needed to change.)
> 
> I don't know how to trigger the code in `get_errors` and `attach_tooltip` so I didn't test them, but I'm pretty sure they need the same adjustment. (If someone would tell me how to trigger these, I'll test them.)
> 
> Fixes: #15235

This seems to work perfectly to me (tried on a big buffer with many unicode characters).

Afaicu, the `get_errors` is for the error buffer after evaluating several sequences at once. Locations are ok in my test.

I believe the `attach_tooltip` is for hovering and it seems to work. E.g., if I do `Definition α := forall {f₁}, f₁=0.`, the first `f` is blue and when hovering on it, a message is shown at the correct position (while the blue is shifted and no tooltip is shown w/o this PR).

**Comment by herbelin** [comment]
If needs to be done now, I can merge, otherwise I would wait for an acknowledgement from @jfehrle in the end of afternoon.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
I've also checked a few unicode heavy files and no longer have any complaints.

**Comment by jfehrle** [comment]
Please merge, thanks!

The tooltips only appear for warnings?

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by herbelin** [comment]
> The tooltips only appear for warnings?

I don't know so well. Tooltips were a (nice) contribution from @gares (who maybe would like to tell more).

File: ide/coqide/coqOps.ml [hunk 1]
```diff
@@ -759,7 +760,7 @@ object(self)
            | Some loc ->
              let (iter, _, phrase) = self#get_sentence s in
              let (start, _) = Loc.unloc loc in
-             iter#forward_chars (b2c phrase start)
+             iter#forward_chars (b2c buffer start)
```
Comment (jfehrle) [inline ide/coqide/coqOps.ml:763]: @herbelin This may be the cause of the problem Chris Dams mentioned in an email to Coq Club today.  I believe this code is used to populate the Errors panel.  If `start` is already relative to the beginning of the buffer, which seems likely, then this line should be:

```iter#forward_chars (byte_off_to_buffer_off phrase start)```

Can you tell me how to get errors to appear in the Errors panel so I can check this myself?

Comment (jfehrle) [reply ide/coqide/coqOps.ml:763]: Actually, the fix is in #15532.
