### PR TITLE
[cmdline] use / in -print-mod-uid as dir separator on windows

### LINKED ISSUE #13827: coq_makefile not producing valid paths for native objects under Cygwin
#### Description of the problem
Under Cygwin + OCaml-mingw64, I built Coq-8.13 (from github branch) with native-compiler turned on.  Then I tried to install MathComp-1.12.0. The build was successful, but `make install` failed:

```
$ make install
/usr/local/coq-8.13-github/bin/coq_makefile  -f Make -o Makefile.coq
make -f Makefile.coq --no-print-directory install
algebra.coq-nativeNmathcomp_algebra_all_algebra.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_finalg.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_countalg.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_fraction.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_intdiv.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_interval.cmi does not exist
```

The problem seems to be at the definition of  `vo_to_obj` in `<coq root>/tools/CoqMakefile.in`:
```
vo_to_obj = $(addsuffix .o,\
  $(filter-out Warning: Error:,\
  $(shell $(COQTOP) -q -noinit -batch -quiet -print-mod-uid $(1))))
```
where the path returned by `coqtop -print-mod-uid` contains single backslashes which are unfortunately trimmed at somewhere in the later stages and are not available when the path is used at `make install`.

I applied a quick fix using `cygpath` as this:
```
vo_to_obj = $(addsuffix .o,\
  $(filter-out Warning: Error:,\
  $(shell $(COQTOP) -q -noinit -batch -quiet -print-mod-uid $(1) | cygpath -f -)))
```
Although this worked, this is too specific to my use-case and I could not figure out a nice generic solution.

#### Coq Version

The tools and settings are:
- Windows 10
- Cygwin for shell and unix tools
- OCaml-mingw64, manually compiled
- Coq-8.13, manually compiled with ./configure -local -native-compiler yes
- MathComp 1.12.0, manually compiled

### PR DESCRIPTION
**Pull request by gares**
@MSoegtropIMC I've opted for the most conservative solution, I've flipped \ for / only in this option

Fix #13827

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
To be extra safe, you might want to check for files starting with \. This is fairly rare in Windows, one typically either uses relative paths or has a drive letter as well. `C:/a/b` works, `a/b` works, but `/a/b` can lead to interesting (very hard to debug) effects. I would consider throwing an error (or a warning) that one should either use relative paths or absolute paths with a drive letter.

File: toplevel/coqtop.ml [hunk 1]
```diff
@@ -207,9 +207,14 @@ let coqtop_parse_extra extras =
   let async_opts, extras = Stmargs.parse_args ~init:Stm.AsyncOpts.default_opts extras in
   ({ run_mode; color_mode}, async_opts), extras
 
+let fix_windows_dirsep s =
+  if Sys.win32 then Str.(global_replace (regexp_string "\\") "/" s)
+  else s
+
```
Comment (ejgallego) [inline toplevel/coqtop.ml:213]: Umm, the below code is already using `Filename.concat` which should do the right thing on Win32, so this seems wrong. Looking at the original bug, the problem seems to be in the Makefiles that mess with quoting, so it seems to me that the problem should be handled there.

In fact, this whole operation `get_native_name` seems to be ultra-costly, as it loads the whole summary, etc... the name of the native file can be easily computed without calling Coq [this is what we do in Dune] and indeed it seems like a better approach to me.

**Comment by gares** [comment]
Well, `Filename` would spit `/` if it did detect cygwin, but it does not. The "problem" is that we require a unix environment to run coq_makefile, but coq itself is compiled to also work without cygwin (so filename spits \ which is the default on windows). Given that this option is only used by coq_makefile I think it is safe (as ci shows) to flip the \ to /.

File: toplevel/coqtop.ml (hunk 1 above)
Comment (gares) [reply toplevel/coqtop.ml:213]: > In fact, this whole operation `get_native_name` seems to be ultra-costly, as it loads the whole summary, etc... the name of the native file can be easily computed without calling Coq [this is what we do in Dune] and indeed it seems like a better approach to me.

Are you saying that you coded, in dune, the whole `-R` and `-Q` resolution strategy?

**Comment by gares** [comment]
> To be extra safe, you might want to check for files starting with \.

Out of inspiration I replaced `.\` with `\1/`, hope it covers all your weird cases

File: toplevel/coqtop.ml (hunk 1 above)
Comment (ejgallego) [reply toplevel/coqtop.ml:213]: No, dune already knows about these flags natively, so the operation of producing the name for native is quite easy:

https://github.com/ocaml/dune/blob/86522e99241cea205cc3202e419e6a6e003cc3e8/src/dune_rules/coq_module.ml#L43-L47

Indeed having a bit more information about library resolution would be very interesting as it would solve the current problem of having to generate all source files before calling coqdep, but that's offtopic here.

As far as I can see the bug is a bug in the Makefiles, that are quoting incorrectly somewhere, so IMO it should be solved there, not in Coq which is doing the right thing. [If filename.concat is buggy upstream that's a different story, but then we should provide our own, not hack ad-hoc here]

**Review by ejgallego — DISMISSED** [review]
It seems that the problem here is that the makefiles are incorrect w.r.t. quoting, so instead of this  hack we should fix the makefiles instead to preserve the `\`.

**Comment by ejgallego** [comment]
> Well, `Filename` would spit `/` if it did detect cygwin, but it does not.

The problem is not that thing work when `/` is used and don't when `\` is, but that coq_makefile is eating the `\` symbol altogether, this points to broken quoting.

**Comment by silene** [comment]
This pull request is a one-liner. Either we apply it or we close it. Keeping it as a draft forever is just a waste of time.

**Comment by SkySkimmer** [comment]
In https://github.com/coq/coq/wiki/Coq-Call-2021-11-10 we said we would go with this solution

**Comment by ppedrot** [comment]
@SkySkimmer don't you want to assign and merge this one? It has been lingering quite a bit.

**Comment by ppedrot** [comment]
Since we collectively agreed on merging this I don't see any point in keeping this around. Let's fire and forget.

**Comment by ppedrot** [comment]
Since we collectively agreed on merging this I don't see any point in keeping this around. Let's fire and forget.

**Comment by ppedrot** [comment]
Since we collectively agreed on merging this I don't see any point in keeping this around. Let's fire and forget.

**Comment by ppedrot** [comment]
@coqbot merge now

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
