### PR TITLE
Fixes reduction effect printing in the presence of non purely applicative stacks

### LINKED ISSUE #10: print_id in match prints nothing
This prints nothing

```
From ReductionEffect Require Import PrintingEffect.
Eval cbv in (match print_id (3%nat) with
             | O => O
             | S p => 3
             end).

```

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

Fixes / closes  coq-community/reduction-effects#10.

The reduction effect plugin was expecting an applicative term of the form `print_id c`, so we drop any `match` or fixpoint, or  projection context from the stack.

An alternative would be to change the plugin. The question is whether we intend to communicate the applicative stack or the full stack. As it is, the intent is to communicate the applicative stack. Don't know if there would be a use for passing the whole stack.

- [ ] Entry added in the changelog

### CODE REVIEW

File: pretyping/cbv.ml [hunk 1]
```diff
@@ -397,6 +397,10 @@ and apply_env env t =
   | _ ->
     map_with_binders subs_lift apply_env env t
 
+let rec strip_app = function
+  | APP (args,st) -> APP (args,strip_app st)
+  | s -> TOP
```
Comment (SkySkimmer) [inline pretyping/cbv.ml:402]:
```suggestion
  | CASE _ | PROJ _ | TOP -> TOP
```
also the comment on cbv_stack says
~~~
 * Important remark: the APPs should be collapsed:
 *    (APP (l,(APP ...))) forbidden
~~~
so maybe we shouldn't be recursive and just do return `APP (args, TOP)` in the APP case

Comment (ppedrot) [reply pretyping/cbv.ml:402]: Nothing forces this statically so I think it's a bad idea not to be recursive.

**Comment by VincentSe** [comment]
Will this reduce the amount of information printed by `print_id` ?

**Comment by herbelin** [comment]
> Will this reduce the amount of information printed by print_id ?

When `print_id` was printing something, it will continue to print the same thing. When it was not printing even though it was applied to at least 2 arguments (a type and a term of this type), it will print the second argument (the term).

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Will merge soon.

**Comment by VincentSe** [comment]
@ppedrot Hello, this PR hasn't evolved for 23 days, can you merge it ?
