### PR TITLE
Fixes #13244: support for coercions in Search

### LINKED ISSUE #13244: Searching for `headconcl` and `headhyp` requires manually inserting coercions to Sortclass.
#### Description of the problem

When searching for something like the "contra" lemmas in ssr, a natural search might be `headconcl:(~~ _)`. However, this does not return any results as `~~ _` is always boolean rather than a type, and cannot be the head of a return type. So one has to search for `headconcl:(is_true (~~ _))` instead. This is a regression compared to the search function in the ssrsearch module, where the coercion to Prop/Sortclass was inserted automatically 

```coq
Require Import ssr.ssrbool.
Search headconcl:(~~ _). (* nothing *)
Search headconcl:(is_true (~~ _)). (* contra lemmas *)
Search concl:(~~ _). (* a lot more results *)
Require Import ssrsearch.ssrsearch.
Search (~~ _). (* same contra lemmas as above *)
```
#### Coq Version

8.12

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** enhancement

Fixes / closes #13244

This PR introduces typing of `Search` patterns, and, as a consequence, coercions are inserted in the patterns whenever insertable. This includes support for coercion head patterns to types, as ssreflect `Search` was doing.

Notations in head patterns are also interpreted in `type_scope`, so that `Search head:(_ + _)` is now talking about the `sum` type.

Don't know if this is considered important for 8.12.1. Maybe not.

- [X] Added / updated test-suite
- [x] Entry added in the changelog

### CODE REVIEW

File: interp/constrintern.ml [hunk 1]
```diff
@@ -2471,6 +2471,15 @@ let intern_constr_pattern env sigma ?(as_type=false) ?(ltacvars=empty_ltac_sign)
             ~pattern_mode:true ~ltacvars env sigma c in
   pattern_of_glob_constr c
 
+let interp_constr_pattern env sigma ?(expected_type=WithoutTypeConstraint) c =
+  let kind_for_intern = match expected_type with OfType _ -> WithoutTypeConstraint | _ -> expected_type in
```
Comment (SkySkimmer) [inline interp/constrintern.ml:2475]: This line is very strange.

File: test-suite/output/Search.v [hunk 2]
```diff
@@ -89,3 +89,16 @@ Module Bug12647.
...
+Coercion Some_nat := @Some nat.
+Axiom f : None = 0.
+Search (None = 0).
+End WithCoercions.
+
+Require Import ssr.ssrbool.
+Module Issue13244.
+Set Warnings "-ssr-search-moved".
+Search headconcl:(~~ _).
+End Issue13244.
```
Comment (SkySkimmer) [inline test-suite/output/Search.v:104]: Could we have a new file bug_13244 instead of piling stuff into Search.v?

Comment (herbelin) [reply test-suite/output/Search.v:104]: That's possible yes.

File: interp/constrintern.ml (hunk 1 above)
Comment (herbelin) [reply interp/constrintern.ml]: > This line is very strange.

I copied it from `tacinterp.ml` but it is indeed strange and actually useless (same job done by `allowed_binder_kind_of_type_kind` already).

Changed.

**Comment by Zimmi48** [comment]
> Don't know if this is considered important for 8.12.1. Maybe not.

I'd rather be strict and not accept an enhancement in 8.12.1.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
It seems possible that someone could search for a pattern which doesn't typecheck, eg something involving a unification problem which coq doesn't solve but which has solutions. If I understand correctly, this PR breaks such searches.
Is this something we should be concerned about?
Possible solutions:
- have some search option to avoid typing the pattern
- catch typing errors in `interp_constr_pattern` and fallback to `intern_constr_pattern`

**Comment by herbelin** [comment]
>  Is this something we should be concerned about?

I would say that this is something that we should be concerned about but I have no clear idea of an example.

> - catch typing errors in `interp_constr_pattern` and fallback to `intern_constr_pattern`

I would prefer this to a new option. That would be good to have a concrete example too.

**Comment by SkySkimmer** [comment]
For instance something involving Prop incompleteness
~~~coq
Search (forall A, A -> A /\ A).
~~~

**Comment by SkySkimmer** [comment]
@herbelin do you intend to change something to support non-typable patterns or do you prefer to merge as-is?

**Comment by herbelin** [comment]
> @herbelin do you intend to change something to support non-typable patterns or do you prefer to merge as-is?

I think your proposal is worth. No time before tonight or tomorrow though (don't hesitate to do it actually if you feel so).

File: vernac/comSearch.ml [hunk 3]
```diff
@@ -53,7 +53,16 @@ let kind_searcher = Decls.(function
 let interp_search_item env sigma =
   function
   | SearchSubPattern ((where,head),pat) ->
-      let _,pat = Constrintern.intern_constr_pattern env sigma pat in
+      let expected_type = Pretyping.(if head then IsType else WithoutTypeConstraint) in
+      let pat =
+        try Constrintern.interp_constr_pattern env sigma ~expected_type pat
+        with _ ->
```
Comment (SkySkimmer) [inline vernac/comSearch.ml:59]: should be a filtered catch as usual

Comment (herbelin) [reply vernac/comSearch.ml]: I'm distracted. Thanks!

**Comment by herbelin** [comment]
PS: did you mean "needs: progress" because of the catchall or for other reasons?

**Comment by herbelin** [comment]
PS: did you mean "needs: progress" because of the catchall or for other reasons?

**Comment by SkySkimmer** [comment]
For the catchall

File: vernac/comSearch.ml [hunk 4]
```diff
@@ -53,7 +53,16 @@ let kind_searcher = Decls.(function
...
+      let expected_type = Pretyping.(if head then IsType else WithoutTypeConstraint) in
+      let pat =
+        try Constrintern.interp_constr_pattern env sigma ~expected_type pat
+        with e when CErrors.noncritical e ->
+          (* We cannot ensure (yet?) that a typable pattern will
+             actually be typed, consider e.g. (forall A, A -> A /\ A)
+             which fails, not seeing that A can be Prop; so we use an
+             untyped pattern as a fallback (i.e w/o no insertion of
+             coercions, no compilation of pattern-matching) *)
+          snd (Constrintern.intern_constr_pattern env sigma ~as_type:head pat) in
```
Comment (SkySkimmer) [inline vernac/comSearch.ml:65]: I expected the catch to be done inside interp_constr_pattern but this works too.

**Comment by SkySkimmer** [comment]
@coqbot: merge now
