### PR TITLE
Do not rely on case scheme generation for internal lemma projections.

### LINKED ISSUE #17100: The apply in tactic uses wrong sort information for conjunction elimination
This is hidden most of the time because of Prop ≤ Type cumulativity and the fact that conjunction is a singleton, but this results in bad relevances when mixing apply in on `<->` and a goal in SProp.

The root of the problem is in
https://github.com/coq/coq/blob/8a22a3f7fb47a5b68657b8cfacbf214ee56e2a03/tactics/tactics.ml#L1827-L1832
because the sort passed to the case-building function is the one of the current goal, but this is unrelated to the sort of the hypothesis on which the elimination is performed.

Minimal test:
```
Set Warnings "+bad-relevance".

Axiom Prop1 : Prop.
Axiom Prop2 : Prop.
Axiom equiv : Prop1 <-> Prop2.

Lemma buggy (P : SProp) : Prop1 -> P -> P.
Proof.
  intros HO.
  apply equiv in HO.
  refine (fun x => x).
Qed. (* Bad relevance in case annotation. [bad-relevance,debug] *)
```

### PR DESCRIPTION
**Pull request by ppedrot**
Instead we simply build the case node by hand, since it is trivial. This is clearer, potentially more efficient as we do not create trivial β cuts, and sounder since we have the correct return sort at hand.

Fixes #17100: apply in uses wrong sort information for conjunction elimination.

### CODE REVIEW

**Comment by ppedrot** [comment]
I have added another test for the similar behaviour discovered after the fact in #17100.

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
This is now correct, the previous variant had an issue with De Bruijn indices because I am dumb.

**Comment by ppedrot** [comment]
@coqbot bench for good measure

**Comment by JasonGross** [comment]
> This is now correct, the previous variant had an issue with De Bruijn indices because I am dumb.

Should one (or more) of the minimized test-cases be added under `bug_17101.v`?

**Comment by ppedrot** [comment]
I could but the error on my side was really dumb, so unlikely to be repeated.

File: tactics/tactics.ml [hunk 1]
```diff
@@ -1781,12 +1780,20 @@ let make_projection env sigma params cstr sign elim i n c u =
...
+        let ksort = Retyping.get_sort_family_of (push_rel_context sign env) sigma t in
+        if Sorts.family_leq ksort mip.mind_kelim then
+          let arity = List.firstn mip.mind_nrealdecls mip.mind_arity_ctxt in
+          let mknas ctx = Array.of_list (List.rev_map get_annot ctx) in
+          let ci = Inductiveops.make_case_info env ind (get_relevance decl) RegularStyle in
+          let br = [| mknas cs_args, b |] in
+          let args = Context.Rel.instance mkRel 0 sign in
+          let pnas = Array.append (mknas arity) [|make_annot Anonymous mip.mind_relevance|] in
+          let p = (pnas, lift (Array.length pnas) t) in
+          let c = mkCase (ci, u, Array.of_list params, p, NoInvert, mkApp (c, args), br) in
```
Comment (herbelin) [inline tactics/tactics.ml:1794]: Would calling `build_case_analysis_scheme` here, where we now have the right sort IIUC, make sense?

Comment (ppedrot) [reply tactics/tactics.ml:1794]: This is generating a lot of cruft and creates dummy β-redexes even after head reduction, so not a good idea.

Comment (herbelin) [reply tactics/tactics.ml:1794]: Right, dummy β-redexes pas glop.

What worried me at first is that this is a piece of code that is morally semantically stand-alone and which is inlined in a way which makes the whole code more difficult to read.

Comment (ppedrot) [reply tactics/tactics.ml:1794]: I guess it's a matter of taste, but the previous code also required a bit of juggling.

**Comment by JasonGross** [comment]
> I could but the error on my side was really dumb, so unlikely to be repeated.

It's still an instance of incomplete code coverage, no?  I think it's worth adding examples to the test-suite, even if regressions are unlikely, to work incrementally towards complete code coverage

**Comment by ppedrot** [comment]
@JasonGross OK, will do.

**Comment by ppedrot** [comment]
Dummy test added, this should be ready.

**Comment by ppedrot** [comment]
@herbelin you should probably assign.

File: tactics/tactics.ml (hunk 1 above)
Comment (herbelin) [reply tactics/tactics.ml:1794]: > I guess it's a matter of taste, but the previous code also required a bit of juggling.

Possibly, but as it is, I find it more difficult to read in diagonal than before.

**Comment by herbelin** [comment]
OK, assigning. Will merge.

PS: benchmarking tests faster than 0.05s seem to give untrustable times. Would it be easy to filter them out?

**Comment by herbelin** [comment]
Fiat crypto killed after taking more than 3 hours.

@coqbot: merge now

**Review by herbelin — APPROVED** [review]

**Comment by herbelin** [comment]
@coqbot: merge now
