### PR TITLE
Fix #5368: Canonical structure unification fails.

### LINKED ISSUE #5368: Canonical structure unification fails and Anomaly universe
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5368
From: @amblafont
Reported version: 8.6
CC:   coq-bugs-redist@lists.gforge.inria.fr

### PR DESCRIPTION
**Pull request by ppedrot**
Universe instances were lost during constructions of the canonical instance.

### CODE REVIEW

File: pretyping/evarconv.ml [hunk 1]
```diff
@@ -218,6 +218,8 @@ let check_conv_record env sigma (t1,sk1) (t2,sk2) =
   let t' = EConstr.of_constr t' in
   let t' = subst_univs_level_constr subst t' in
   let bs' = List.map (EConstr.of_constr %> subst_univs_level_constr subst) bs in
+  let params = List.map (fun c -> subst_univs_level_constr subst c) params in
```
Comment (maximedenes) [inline pretyping/evarconv.ml]: Could this bug have been prevented by a better API? For example, couldn't the types distinguish whether we applied the substitution or not?

Comment (ppedrot) [reply pretyping/evarconv.ml]: Hard to tell. But it's clear that the current API is not satisfactory. In particular, `subst_univs_level_constr` is somewhat misleading, we should use `subst_instance_constr` instead, but it's not yet defined in EConstr.

**Comment by ppedrot** [comment]
I've launched a bench [here](https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/255/), but I highly doubt it'll have any observable consequence. The main reason being that in absence of polymorphic canonical structures, this shouldn't perform any additional substitution, and precisely because of the present bug the latter are not usable.

**Comment by ppedrot** [comment]
No observable change in time nor memory.

**Comment by maximedenes** [comment]
Build was canceled, restarting.
