### PR TITLE
Fix bad interaction between dune and local opam directory switches.

### LINKED ISSUE #20422: Error: path outside the workspace using 9.0.0 and setup-ocaml on GitHub CI
### Description of the problem

I have a [small project](https://github.com/henrytill/bits-coq) that I am attempting to update to >= 9.0.0.  It builds fine locally, but when I attempt to build it on GitHub CI using the default environment provided by [ocaml/setup-ocaml](https://github.com/ocaml/setup-ocaml), I get build errors like:

```
Error: path outside the workspace: ../../../_opam/lib/rocq-runtime/rocqworker
```

Full run here:
https://github.com/henrytill/bits-coq/actions/runs/14139378908/job/39618010647

Configuration here:
https://github.com/henrytill/bits-coq/blob/41ecd688a5b3d583d4b3fc11ff26d351e87f264b/.github/workflows/ci.yml

Note that this CI setup worked as expected before the move to 9.0.0.

Originally reported as part of #20408.

### Small Rocq / Coq file to reproduce the bug

```coq

```

### Version of Rocq / Coq where this bug occurs

9.0.0

### Interface of Rocq / Coq where this bug occurs

dune 3.17.2

### Last version of Rocq / Coq where the bug did not occur

8.20.1

### PR DESCRIPTION
**Pull request by rlepigre-skylabs-ai**
Fixes / closes #20422.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please use an actual description in the commit message and PR title instead of purely relying on the bug number.

File: tools/coqdep/lib/fl.ml [hunk 1]
```diff
@@ -61,7 +61,7 @@ let relative_if_dune path =
   (* relativize the path if inside the current dune workspace
      if we relativize paths outside the dune workspace it fails so make sure to avoid it *)
   match Sys.getenv_opt "DUNE_SOURCEROOT" with
-  | Some dune when CString.is_prefix dune path ->
+  | Some dune when CString.is_prefix (Filename.concat dune "_build") path ->
```
Comment (SkySkimmer) [inline tools/coqdep/lib/fl.ml:64]: in principle on windows we should probably be doing case-insensitive comparison and also consider / and \ separators to be equivalent. This is already an issue in the existing code though.

Comment (rlepigre-skylabs-ai) [reply tools/coqdep/lib/fl.ml:64]: I guess a proper and portable file path library should be used throughout the code. I'm not sure this is the right place to do it.

**Comment by SkySkimmer** [comment]
Can someone test on windows? Our windows CI is currently disabled due to unrelated breakage (https://github.com/garrigue/lablgtk/issues/188)

**Comment by ejgallego** [comment]
@SkySkimmer coq-lsp win CI does run the test suite natively  on Win, however coq-lsp uses extra care to handle paths in win so it is not representative.

> I guess a proper and portable file path library should be used throughout the code. I'm not sure this is the right place to do it.

Actually that's trickier than it looks, on the other hand we could try to solve this problem by improving coqdep as not to have to output paths (which has many advantages), but to output symbolic dep info, and let Dune resolve the paths.

Ali did write a nice PR doing that, but unfortunately it was also including a new lexer for coqdep so it got blocked on that orthogonal issue.

**Comment by SkySkimmer** [comment]
Could you rebase so that we get a windows CI run? If that works I think we will call it good enough and let windows users report if there are problems.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

File: doc/changelog/12-infrastructure-and-dependencies/20437-fix_20422.rst [hunk 2]
```diff
@@ -0,0 +1,5 @@
+- **Fixed:**
+  Bad interaction between dune and local opam directory switches
```
Comment (SkySkimmer) [inline doc/changelog/12-infrastructure-and-dependencies/20437-fix_20422.rst:2]:
```suggestion
  Bad interaction between dune, `rocq dep` and local opam directory switches
```

**Comment by rlepigre-skylabs-ai** [comment]
Oups, did I get in the way of full ci?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now
