### PR TITLE
Better primitive type support in custom string and numeral notations.

### LINKED ISSUE #13484: String notations and primitive arrays
#### Description of the problem

Currently, parsing a string notation will fail if the produced term is not "ground" (made up of inductive types, constructor applications or primitive integers):

`Unexpected term [|97;98;99 | 0 : int |] while parsing a string notation.`

 Would it be possible to extend that criterion to include primitive arrays?

#### Coq Version

Version 8.13+alpha (November 2020) compiled on Nov 11 2020 14:05:43 with OCaml 4.07.1

### LINKED ISSUE #13517: String notation printing fails with primitive integers inside lists
#### Description of the problem
String notations will not print if the value contains lists (or other polymorphic datatypes) over primitive integers, despite that one would maybe expect that from the documentation allowing `terms containing only function application, constructors, inductive type families, sorts, and primitive integers)`.

The problem is (at least) that [constants like the type of primitive integers are not allowed as type-parameter of constructors](https://github.com/coq/coq/blob/db13ff6866731001ad7d3021ab7cb4b3a54cba5c/interp/notation.ml#L643).

I think I will fix that (allow the constant denoting the primitive type) and submit a PR.

```` coq
(* Test for string notations with primitive integers *)
Require Import BinNums Int63 Byte.

Inductive nstring := mk_str (_ : list int).
Definition i63_from_byte (b : byte) : int := Int63.of_Z (BinInt.Z.of_N (Byte.to_N b)).
Definition i63_to_byte (i : int) : byte :=
    match Byte.of_N (BinInt.Z.to_N (Int63.to_Z i)) with Some x => x | None => x00%byte end.

Definition to_byte_list '(mk_str a) := List.map i63_to_byte a.

Definition from_byte_list (xs : list byte) : nstring:=
  mk_str (List.map i63_from_byte xs).

Declare Scope nstring_scope.
Delimit Scope nstring_scope with nstr.

String Notation nstring from_byte_list to_byte_list : nstring_scope.

Open Scope nstring_scope.
Import List.ListNotations.
Definition n := mk_str [97; 98; 99]%int63%list.

Print n.
Check "abc"%nstr.
````
I would expect that the last two statements both print as ` "abc"%nstr`. 

#### Coq Version

master

### PR DESCRIPTION
**Pull request by fakusb**
- float and array values are now supported for printing and parsing in custom notations
- the three constants bound to the primitive float, int and array type are now allowed anywhere inside a term to print, to handle them similar to "real"  type constructors
- Grants #13484: String notations for primitive arrays
- Fixes #13517: String notation printing fails with primitive integers inside lists

**Kind:**  bug fix / performance.

Fixes / closes #13484 and #13517

- [x] Added / updated test-suite

- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

File: interp/notation.ml [hunk 1]
```diff
@@ -633,17 +633,27 @@ exception NotAValidPrimToken
...
     considered for parsing. *)
 
-let constr_of_globref allow_constant env sigma = function
+let is_primitive_type c =
+  let is_this_ref name c =
+    if Coqlib.has_ref name
+    then GlobRef.equal c (Coqlib.lib_ref name)
+    else false
+  in
+  is_this_ref "num.int63.type" c || is_this_ref "num.float.type" c || is_this_ref "core.parray.type" c
```
Comment (SkySkimmer) [inline interp/notation.ml:642]: Why not look in the env instead?

Comment (SkySkimmer) [reply interp/notation.ml:642]: Then you don't need to add a registration.

Comment (fakusb) [reply interp/notation.ml:642]: Because I did cargo-cult this a bit to much. this should probably also fix the performance issue with the complexity/pretyping test.

Comment (SkySkimmer) [reply interp/notation.ml]: What perf issue is that?

Comment (fakusb) [reply interp/notation.ml]: on my machine, that test now takes 162 instead of the allow 150 units, which i think is due to tha fact that now, whenever something is printed, every constant needs some lookups in the environment (or before, every constant performed several calls to Coqlib.find_ref.)

I also noticed that `Environ.is_primitive` apperently does not do what i expected there, which I'll have to inverstigate further.

Comment (fakusb) [reply interp/notation.ml]: Do I have to use the retroknowledge as in Environ.is_array_type to test is the constant is primitive?
It seems that the primitive type constants are opaque and is_primitive does maybe never work?

Comment (SkySkimmer) [reply interp/notation.ml]: looks like it

File: doc/sphinx/user-extensions/syntax-extensions.rst [hunk 2]
```diff
@@ -1734,7 +1734,8 @@ Number notations
 
          Note that only fully-reduced ground terms (terms containing only
          function application, constructors, inductive type families,
-         sorts, and primitive integers) will be considered for printing.
+         sorts, primitive integers, primitive floats, primitive arrays, and the type
```
Comment (jfehrle) [inline doc/sphinx/user-extensions/syntax-extensions.rst:1737]:
```suggestion
         sorts, primitive integers, primitive floats, primitive arrays and the type
```

Generally we don't use the Oxford comma in the doc.

File: doc/sphinx/user-extensions/syntax-extensions.rst [hunk 3]
```diff
@@ -1891,7 +1892,8 @@ String notations
...
```
Comment (jfehrle) [inline doc/sphinx/user-extensions/syntax-extensions.rst:1895]:
```suggestion
         sorts, primitive integers, primitive floats, primitive arrays and the type
```

**Review by jfehrle — COMMENTED** [review]
minor comments

File: kernel/environ.ml [hunk 4]
```diff
@@ -568,11 +568,24 @@ let is_primitive env c =
...
+  | None -> false
+  | Some c' -> Constant.CanOrd.equal c c'
+
 let is_array_type env c =
   match env.retroknowledge.Retroknowledge.retro_array with
   | None -> false
   | Some c' -> Constant.CanOrd.equal c c'
 
+let is_primitive_type env c =
+  is_int63_type env c || is_float64_type env c || is_array_type env c
```
Comment (SkySkimmer) [inline kernel/environ.ml:587]: This may be difficult to keep up to date, perhaps we could do
```suggestion
  (* dummy match to force an update if we add a primitive type *)
  let _ = CPrimitives.(function PTE(PT_int63|PT_float64|PT_array) -> ()) in
  is_int63_type env c || is_float64_type env c || is_array_type env c
```

File: interp/notation.ml [hunk 5]
```diff
@@ -633,17 +633,19 @@ exception NotAValidPrimToken
     what it means for a term to be ground / to be able to be
     considered for parsing. *)
 
-let constr_of_globref allow_constant env sigma = function
+let constr_of_globref allow_constant env sigma c'=
+  begin match c' with
```
Comment (proux01) [inline interp/notation.ml:637]: This change looks unrelated to the current PR, you may want to avoid it.

File: test-suite/output/StringSyntaxPrimitive.v [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+
+Set Printing Depth 100000.
+Set Printing Width 1000.
+
+Close Scope char_scope.
+Close Scope string_scope.
+
+(* Notations for primitive integers inside polymorphic datatypes *)
+Module Test1.
+  Inductive intList := mk_intList (_ : list int).
```
Comment (proux01) [inline test-suite/output/StringSyntaxPrimitive.v:14]: You could probably get rid of the Inductive type and directly use lists using the Number Notation mechanism for non (necessarily) inductive types `via ... mapping ...`.

File: test-suite/output/StringSyntaxPrimitive.v [hunk 7]
```diff
@@ -0,0 +1,139 @@
...
+
+  Definition int' := int.
+  Check mk_intList (@cons int' 97 [98; 99])%int63%list.
+End Test1.
+
+Import PArray.
+
+(* Notations for primitive arrays *)
+Module Test2.
+  Inductive intArray := mk_intArray (_ : array int).
```
Comment (proux01) [inline test-suite/output/StringSyntaxPrimitive.v:42]: Here getting rid of the wrapping `mk_intArray` might be harder but we encountered a similar issues with printers for primitive integers, so maybe we could adapt the mechanism to other primitive types (floats and arrays).

**Review by proux01 — APPROVED** [review]
LGTM

File: test-suite/output/StringSyntaxPrimitive.v (hunk 6 above)
Comment (fakusb) [reply test-suite/output/StringSyntaxPrimitive.v:14]: I did not use this feature before. I think there is a benefit in using the `via ... mapping` feature at the same time to only test [problems related to the `re-constr`fication of primitive objects.

File: test-suite/output/StringSyntaxPrimitive.v (hunk 7 above)
Comment (fakusb) [reply test-suite/output/StringSyntaxPrimitive.v:42]: (same answer as for the Test1 comment above)

**Comment by fakusb** [comment]
I forget to push the changelog entry when I ticked it above. Could someone read through it once?

**Comment by proux01** [comment]
> I forget to push the changelog entry when I ticked it above. Could someone read through it once?

It looks reasonable to me.

BTW congrats for getting this to work! This code is not trivial to edit and debug.

File: test-suite/output/StringSyntaxPrimitive.v (hunk 6 above)
Comment (proux01) [reply test-suite/output/StringSyntaxPrimitive.v:14]: I agree the test should be kept. I was just suggesting it in case you'd like to get rid of the wrapping inductive.

File: doc/changelog/03-notations/13519-primitiveArrayNotations.rst [hunk 8]
```diff
@@ -0,0 +1,8 @@
+- **Added:**
+  :ref:`Number Notation <number-notations>` and :ref:`String Notation
+  <string-notations>` commands now support primitive floats and primitive arrays
```
Comment (Zimmi48) [inline doc/changelog/03-notations/13519-primitiveArrayNotations.rst:3]:
```suggestion
  :cmd:`Number Notation` and :cmd:`String Notation`
  commands now support primitive floats and primitive arrays
```

File: doc/sphinx/user-extensions/syntax-extensions.rst [hunk 9]
```diff
@@ -1734,7 +1734,8 @@ Number notations
 
          Note that only fully-reduced ground terms (terms containing only
          function application, constructors, inductive type families,
-         sorts, and primitive integers) will be considered for printing.
+         sorts, primitive integers, primitive floats, primitive arrays and the type
```
Comment (jfehrle) [inline doc/sphinx/user-extensions/syntax-extensions.rst:1737]:
```suggestion
         sorts, primitive integers, primitive floats, primitive arrays and type
```

File: doc/sphinx/user-extensions/syntax-extensions.rst [hunk 10]
```diff
@@ -1891,7 +1892,8 @@ String notations
...
```
Comment (jfehrle) [inline doc/sphinx/user-extensions/syntax-extensions.rst:1895]:
```suggestion
         sorts, primitive integers, primitive floats, primitive arrays and type
```

File: doc/changelog/03-notations/13519-primitiveArrayNotations.rst [hunk 11]
```diff
@@ -0,0 +1,8 @@
+- **Added:**
+  :cmd:`Number Notation` and :cmd:`String Notation`
+  commands now support primitive floats and primitive arrays
+  as well as the type constants of all primitive objects as parameter of inductives and arrays
```
Comment (jfehrle) [inline doc/changelog/03-notations/13519-primitiveArrayNotations.rst:4]:
```suggestion
  :cmd:`Number Notation` and :cmd:`String Notation`
  commands now support primitive floats, primitive arrays
  and type constants of primitive objects as parameters of inductives and arrays
```

I don't understand the `as parameters of inductives and arrays`, maybe `as` should be `for`?  And it's unclear how `parameters` and `inductives and arrays` relate to these syntax-oriented commands.  Are you referring to _printing_ inductives and arrays?

File: doc/sphinx/user-extensions/syntax-extensions.rst (hunk 9 above)
Comment (fakusb) [reply doc/sphinx/user-extensions/syntax-extensions.rst:1737]: I'm talking about the specific constant `Numbers.Cyclic.Int63.Int63.int` and the two others for floats and arrays. Is the `the` not needed/allowed because I talk about three things and not one?

File: doc/changelog/03-notations/13519-primitiveArrayNotations.rst (hunk 11 above)
Comment (fakusb) [reply doc/changelog/03-notations/13519-primitiveArrayNotations.rst]: I rephrased the whole changelog entry.
I want to communicate that:
-objects whose type is primitive float and primitive arrays can now be printed/parsed, while before this was only there for primitive integers.
-The constants that are the type of those objects (`Numbers.Cyclic.Int63.Int63.int` etc) are now allowed inside terms that get parsed/printed, which is for example needed when constructing polymorphic datatypes or arrays containing primitive values.
Would you mind to give feedback on the new phrasing?

File: doc/changelog/03-notations/13519-primitiveArrayNotations.rst [hunk 12]
```diff
@@ -0,0 +1,9 @@
+- **Added:**
+  :cmd:`Number Notation` and :cmd:`String Notation` can now register parsers
+  and printers for terms containing primitive floats, primitive arrays
+  and type constants for primitive types.
```
Comment (jfehrle) [inline doc/changelog/03-notations/13519-primitiveArrayNotations.rst:4]:
```suggestion
  :cmd:`Number Notation` and :cmd:`String Notation` now support
  parsing and printing of primitive floats, primitive arrays
  and type constants of primitive types.
```

Simpler and clearer--does it capture the essence of the change?  `type constants` or can it just be `constants`?

File: doc/changelog/03-notations/13519-primitiveArrayNotations.rst [hunk 13]
```diff
@@ -0,0 +1,9 @@
...
+  (`#13519 <https://github.com/coq/coq/pull/13519>`_,
+  fixes `#13484 <https://github.com/coq/coq/issues/13484>`_
+  and `#13517 <https://github.com/coq/coq/issues/13517>`_,
+  by Fabian Kunze, with help of Jason Gross, reviewed by Gaëtan Gilbert,
+  Pierre Roux, Théo Zimmermann and Jim Fehrle).
```
Comment (jfehrle) [inline doc/changelog/03-notations/13519-primitiveArrayNotations.rst:9]: You don't need to credit me as a reviewer.  IMHO reviewer credit is appropriate when the review was a lot of work or "above and beyond" what's normally needed.

**Review by jfehrle — APPROVED** [review]
Tweaked your new wording a bit.

File: doc/changelog/03-notations/13519-primitiveArrayNotations.rst (hunk 12 above)
Comment (fakusb) [reply doc/changelog/03-notations/13519-primitiveArrayNotations.rst:4]: It should be type constants, as `constants` sounds too much line ints themself instead of their type imho

File: doc/changelog/03-notations/13519-primitiveArrayNotations.rst [hunk 14]
```diff
@@ -0,0 +1,9 @@
+- **Added:**
+  :cmd:`Number Notation` and :cmd:`String Notation` can now register parsers
+  and printers for terms containing primitive floats, primitive arrays
+  and type constants for primitive types.
+  (`#13519 <https://github.com/coq/coq/pull/13519>`_,
+  fixes `#13484 <https://github.com/coq/coq/issues/13484>`_
+  and `#13517 <https://github.com/coq/coq/issues/13517>`_,
+  by Fabian Kunze, with help of Jason Gross, reviewed by Gaëtan Gilbert,
```
Comment (fakusb) [inline doc/changelog/03-notations/13519-primitiveArrayNotations.rst:8]:
```suggestion
  by Fabian Kunze, with help of Jason Gross)
```

File: doc/changelog/03-notations/13519-primitiveArrayNotations.rst (hunk 13 above)
Comment (fakusb) [inline doc/changelog/03-notations/13519-primitiveArrayNotations.rst:9]:
```suggestion
```

**Comment by fakusb** [comment]
Ok, i squashed everything into one commit and all tests work. This could be merged.

**Comment by jfehrle** [comment]
@Zimmi48 who would be good to be the assignee/merger?

**Comment by Zimmi48** [comment]
Anyone from @coq/extensible-syntax-maintainers. Coq developers were quite busy with CUDW though and unfortunately two of the members of this team are additionally busy with urgent project writing tasks, so give them some time.

**Comment by herbelin** [comment]
I can assign and merge @coq/extensible-syntax-maintainers. Will do tomorrow + margin.

**Comment by herbelin** [comment]
@coqbot: merge now
