### PR TITLE
In error messages, consider evars equal to all for deciding verbosity

### LINKED ISSUE #7223: Coercions around evars should always be printed
Coq version: 8.7.2

Here's an enhancement suggestion: No matter whether printing of coercions is enabled or not, coercions around evars, i.e. terms for the form `f ?x` where `f` is a coercion and `?x` is an evar, should always be printed as `f ?x` instead of just `?x`, because otherwise error messages can be very confusing, as illustrated by the following example:

```

Inductive expr :=
| Const: nat -> expr
| Add: expr -> expr -> expr.

Inductive eval: expr -> expr -> Prop :=
| EConst: forall n,
    eval (Const n) (Const n)
| EAdd: forall e1 v1 e2 v2,
    eval e1 (Const v1) ->
    eval e2 (Const v2) ->
    eval (Add e1 e2) (Const (v1 + v2)).

Coercion Const: nat >-> expr.

Lemma eval_total: forall e, exists v, eval e v.
Proof.
  induction e.
  - eauto using EConst.
  - destruct IHe1 as [v1 IH1]. destruct IHe2 as [v2 IH2].
    eexists.
    eapply EAdd.
    + Fail exact IH1.
      (* The term "IH1" has type "eval e1 v1" while it
         is expected to have type "eval e1 ?v1".

         This error message is very confusing, why does IH1 not match the goal? *)

      Set Printing Coercions.
    
      Fail exact IH1.
      (* The term "IH1" has type "eval e1 v1" while it
         is expected to have type "eval e1 (Const ?v1)".

         This is what the error message should look like,
         no matter whether "Set Printing Coercions" is enabled or not. *)
```

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #7223

### CODE REVIEW

**Comment by herbelin** [comment]
An alternative would be to modify `Himsg.display_eq` (i.e. to have a variant of `Constrexpr_ops.constr_expr_eq` equalizing evars with anything else) so that the coercion is displayed only when it is about printing a diff.

**Comment by ppedrot** [comment]
@herbelin I believe this is actually a more principled solution to the problem.

**Comment by SkySkimmer** [comment]
changed

File: vernac/himsg.ml [hunk 1]
```diff
@@ -114,6 +114,13 @@ let canonize_constr sigma c =
   in
   canonize_binders c
 
+let rec display_expr_eq c1 c2 =
+  let open Constrexpr in
+  match CAst.(c1.v, c2.v) with
+  | (CHole _ | CEvar _), _ | _, (CEvar _ | CHole _) -> true
```
Comment (ppedrot) [inline vernac/himsg.ml:120]: For the evar / evar case, you should also check the evar name, otherwise you might get extremely verbose output.

Comment (SkySkimmer) [reply vernac/himsg.ml:120]: You have a test case?

Comment (herbelin) [reply vernac/himsg.ml:120]: I thought that frozen evars would have provided a test case but searching for a couple of minutes, I couldn't elaborate a test case. Nevertheless, I agree with @ppedrot that that would be "safer" to check the evar name.

Comment (SkySkimmer) [reply vernac/himsg.ml:120]: Without a test case to look at I still don't know what the issue is.

Comment (herbelin) [reply vernac/himsg.ml:120]: I would think that @ppedrot had something like this is in mind, so that `?x1` and `?x2` are not considered equal:
```suggestion
  | CEvar (evk1,_) | CEvar (evk2,_) -> Evar.equal evk1 evk2
  | (CHole _ | CEvar _), _ | _, (CEvar _ | CHole _) -> true
```
If  `?x1` and `?x2` are not frozen, I'm finally doubting that they should be considered different. So, I'm rather leaning towards not changing the PR (@ppedrot??).

Comment (SkySkimmer) [reply vernac/himsg.ml:120]: I mean I want an example of an error message which is improved by that change.

Comment (ppedrot) [reply vernac/himsg.ml:120]: Improvement is subjective, but it's obvious that if you go with full printing throttle just because two evars are different may result in extremely verbose output. I am not sure why you're so adamant to have a minimal example when this can be demonstrated to happen from first principles.

**Comment by ppedrot** [comment]
@SkySkimmer can we get a small changelog before I merge?

**Review by ppedrot — APPROVED** [review]
