### PR TITLE
Evd.new_pure_evar relevance argument is required instead of guessing Relevant

### LINKED ISSUE #20131: simple refine (?) elaborates let-bound evars with incorrect relevance marks
### Description of the problem

_No response_

### Small Rocq / Coq file to reproduce the bug

```coq
Set Universe Polymorphism.

Inductive sFalse : SProp := .

Lemma foo: unit.
Proof.
  simple refine (let f : sFalse -> sFalse := _ in tt).
  exact (fun x => x).
Defined.

(* 
Binder (f : "sFalse -> sFalse" := "fun x : sFalse => x") has relevance mark set to
relevant but was expected to be irrelevant (maybe a bugged tactic). *)
```

### Version of Rocq / Coq where this bug occurs

9.0+alpha (38e603cc2cce4f302e0519b1ee164d0d3c3a5efb)

### Last version of Rocq / Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #20131

Overlays:
- https://github.com/unicoq/unicoq/pull/98
- https://github.com/mattam82/Coq-Equations/pull/633

### CODE REVIEW

File: pretyping/evarconv.ml [hunk 1]
```diff
@@ -1711,7 +1711,8 @@ let second_order_matching flags env_rhs evd (evk,args) (test,argoccs) rhs =
               refresh_universes ~status:Evd.univ_flexible (Some true)
                 env_evar_unf evd evty
             else evd, evty in
-          let (evd, evk) = new_pure_evar sign evd evty ~filter in
+          (* XXX incorrect relevance *)
+          let (evd, evk) = new_pure_evar sign evd ~relevance:ERelevance.relevant evty ~filter in
```
Comment (SkySkimmer) [inline pretyping/evarconv.ml:1715]: putting relevance_of_ty evty here breaks bug_4095 where evty's type is an undefined evar (so evty is not really a type, but it somehow still works)

File: plugins/ssr/ssrcommon.ml [hunk 2]
```diff
@@ -1162,15 +1163,15 @@ let tacTYPEOF c = Goal.enter_one ~__LOC__ (fun g ->
 
 (** This tactic creates a partial proof realizing the introduction rule, but
     does not check anything. *)
-let unsafe_intro env decl b =
+let unsafe_intro env decl ~relevance b =
```
Comment (ppedrot) [inline plugins/ssr/ssrcommon.ml:1166]: Why not get the relevance from the goal?

Comment (SkySkimmer) [reply plugins/ssr/ssrcommon.ml:1166]: That's what we do in the caller

Comment (ppedrot) [reply plugins/ssr/ssrcommon.ml:1166]: It's a bit weird to do it this way given we're already in the tactic monad...

Comment (JasonGross) [reply plugins/ssr/ssrcommon.ml:1166]: I agree with @ppedrot, if it's possible to get the relevance here from the goal, there's no need to give callers a footgun to pass the wrong relevance

Comment (SkySkimmer) [reply plugins/ssr/ssrcommon.ml:1166]: There's no "callers", it's a helper for the function right next to it

**Comment by SkySkimmer** [comment]
@ppedrot this is ready AFAICT

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
