### PR TITLE
Addresses #18096: more informative message when a notation cannot be intepreted as a reference 

### LINKED ISSUE #18096: "Print" works for some notations but not all.
#### Description of the problem

I recently noticed that `Print "="` works and prints `eq`, but `Print "<>"` does not work and just says
```
Unable to interpret "<>" as a reference.
```
Why can some notations be printed and others not? Is this a bug or somehow intended?

#### Coq Version
8.16.1

### PR DESCRIPTION
**Pull request by herbelin**
Examples:
```coq
Print "<>"
(* before: Unable to interpret "<>" as a reference. *)
(* after:
Unable to non-ambiguously interpret "<>" as a reference. Found:
Notation "x <> y" := (not (eq x y))
*)
```
Somehow, we could also write:
```
Unable to non-ambiguously interpret "<>" as a reference. Found:
Notation "x <> y" := (~ x = y)
```
Don't know which one is best.

Closes #18096

- [x] Added / updated **test-suite**.
- [x] Added **changelog**. (worth??)

### CODE REVIEW

File: interp/notation.ml [hunk 1]
```diff
@@ -2371,12 +2371,23 @@ let global_reference_of_notation ~head test (ntn,sc,(on_parsing,on_printing,{not
...
+    user_err ?loc
+      (str "Unable to interpret " ++ quote (str ntn) ++
+       str " as a reference.")
+  | l ->
+    let f (_,_,(_,_,c)) =
+      let { not_interp  = (_, r); not_location = (_, df) } = c in
+      str "Notation" ++ brk (1,2) ++
+      pr_notation_info prglob df r in
+    user_err ?loc
+      (str "Unable to non-ambiguously interpret " ++ quote (str ntn) ++
```
Comment (JasonGross) [inline interp/notation.ml:2386]:
```suggestion
      (str "Unable to unambiguously interpret " ++ quote (str ntn) ++
```
is somewhat more natural

**Review by JasonGross — DISMISSED** [review]

**Comment by herbelin** [comment]
Note: in the case of `Search`, we may actually prefer to interpret `Search "<>"` as `Search (not (eq _ _))` rather than failing?

**Comment by proux01** [comment]
> Note: in the case of `Search`, we may actually prefer to interpret `Search "<>"` as `Search (not (eq _ _))` rather than failing?

But then what about `Search "-"` should it be `Search (- _)` or `Search (_ - _)`. That sounds complicated.

**Comment by herbelin** [comment]
> But then what about Search "-" should it be Search (- _) or Search (_ - _). That sounds complicated.

Currently, `Search "-"` interprets `-` as the binary one. I agree that it sounds complicated to find a clear criterion.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

File: interp/smartlocate.mli [hunk 2]
```diff
@@ -39,13 +40,13 @@ val global_inductive_with_alias : qualid -> inductive
 val global_constructor_with_alias : qualid -> constructor
 
 (** Locate a reference taking into account notations and "aliases" *)
-val smart_global : ?head:bool -> qualid Constrexpr.or_by_notation -> GlobRef.t
+val smart_global : ?head:bool -> (glob_constr -> Pp.t) -> qualid Constrexpr.or_by_notation -> GlobRef.t
```
Comment (proux01) [inline interp/smartlocate.mli:43]: Not a big fan of that change. It seems to me that this makes that API harder to use for a relatively accessory feature. I understand some ml file dependency imposes that design, but isn't there any alternative? At worst, instead of printing the multiple notations, the error message could just say something like "use Locate "ntn" to list the <n> possible interpretations." At the very least, we should add a comment in `smartlocate.mli` explaining what the printer is and how to get it.

**Review by proux01 — COMMENTED** [review]
CI green this is technically mergeable but I'd like to clarify the API point before merging.

File: interp/smartlocate.mli (hunk 2 above)
Comment (ppedrot) [reply interp/smartlocate.mli:43]: Why not raise an algebraic exception and register the printer later on? That seems to be the best practice.

Comment (herbelin) [reply interp/smartlocate.mli:43]: OK, will do. Do I put the handler in `himsg.ml`?

Comment (ppedrot) [reply interp/smartlocate.mli:43]: This looks like a reasonable place indeed.

Comment (herbelin) [reply interp/smartlocate.mli]: Done, much less intrusive!

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
Merging soon if nobody complains.

**Comment by ppedrot** [comment]
CI failures spurious, @coqbot merge now
