### PR TITLE
[build] Some more fixes to Dune-Make bridge + ci-* targets

### LINKED ISSUE #14187: CoqMakefile.in missing from the install repository
The dune makefile wrapper does not copy the `CoqMakefile.in` file to a place where `coq_makefile` can find it. This happens even after a `make world`.

This leads to weird errors when compiling external developments, the source of which is hidden by the scripts. The root cause can be observed by simply calling `coq_makefile`, which prints `Error: cannot find CoqMakefile.in`.

cc @ejgallego

### PR DESCRIPTION
**Pull request by ejgallego**
We fix a few problems remaining from the transition:

- some dependencies were missing in the bridge, in particular legacy
  mode didn't rebuild tools always
- we didn't install CoqMakefile.in sometimes
- we forgot to update the timestamp on a couple of bridges
- parameter setup for ci-common was wrong after removal of -local
- we use `coqcorelib` in more places, this fixes `ci-*` targets with a local build when native is enabled

Fixes #14187

### CODE REVIEW

**Comment by ejgallego** [comment]
@ppedrot this should solve your woes with `make world + make ci-foo` in legacy mode, indeed the CI missed that case and the contents of `ci-common` were wrong and creating your problems after the merge of #14176

File: dev/ci/ci-common.sh [hunk 1]
```diff
@@ -19,26 +22,19 @@ then
 elif [ -d "$PWD/_build_vo/" ];
 then
     # Dune Ocaml build, vo build using make
```
Comment (Zimmi48) [inline dev/ci/ci-common.sh:24]: It could be worth to echo something BTW so that developers switching the two modes understand how the choice was made.

File: dev/ci/ci-common.sh [hunk 2]
```diff
@@ -19,26 +22,19 @@ then
...
+    export OCAMLPATH="$PWD/_build_vo/default/lib/:$OCAMLPATH"
+    export COQBIN="$PWD/_build_vo/default/bin"
+    export COQLIB="$PWD/_build_vo/default/lib/coq"
+    export COQCORELIB="$PWD/_build_vo/default/lib/coq-core"
     CI_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
     export CI_BRANCH
 elif [ -d "$PWD/_build/install/default/" ];
 then
     # Full Dune build
-    export OCAMLPATH="$PWD/_build/install/default/lib/:$PWD/_install_ci/lib:$OCAMLPATH"
```
Comment (Zimmi48) [inline dev/ci/ci-common.sh:32]: Why is it not needed anymore to extend `OCAMLPATH` with `_install_ci/lib`?

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
There's a problem in the test-suite with `misc/coq_environment.sh`.

File: dev/ci/ci-common.sh (hunk 2 above)
Comment (ejgallego) [reply dev/ci/ci-common.sh:32]: Not sure why it was needed in the first place, that directory is only relevant in the first case, right?

Comment (SkySkimmer) [reply dev/ci/ci-common.sh:32]: It comes from https://github.com/coq/coq/pull/13464

Comment (Zimmi48) [reply dev/ci/ci-common.sh:32]: >It comes from #13464

Then, it should probably be kept.

>that directory is only relevant in the first case, right?

I don't understand what you mean by this.

Comment (ejgallego) [reply dev/ci/ci-common.sh:32]: I mean that we only need to add _install_ci to the path when we are running in the CI, that is to say, the first if branch.

I'm not sure why #13464 did modify these parts which IIUC are not taken during CI, only during "manual" `make ci-foo` calls.

Comment (Zimmi48) [reply dev/ci/ci-common.sh:32]: What happens if you run `make ci-compcert` locally? How does it find its dependencies?

Comment (ejgallego) [reply dev/ci/ci-common.sh:32]: I'm not sure what is going on, but in this case there will be nothing in `_install_ci` , but things are installed in by the ci targets in whatever prefix we setup at configure time.

Comment (SkySkimmer) [reply dev/ci/ci-common.sh:32]: https://github.com/coq/coq/blob/6bd39f29e675e125edfcb1dcb7a0fc5997049741/dev/ci/ci-menhir.sh#L6

Comment (ejgallego) [reply dev/ci/ci-common.sh:32]: I see, thanks. That doesn't feel right at all tho.

**Comment by ejgallego** [comment]
Let's see how this looks now.

**Comment by JasonGross** [comment]
Does this fix https://github.com/coq/coq/issues/14218 ? (doc-stdlib-html)

File: dev/ci/ci-common.sh (hunk 2 above)
Comment (Zimmi48) [reply dev/ci/ci-common.sh:32]: Why doesn't it?

File: dev/ci/ci-common.sh (hunk 1 above)
Comment (ejgallego) [reply dev/ci/ci-common.sh:31]: Good idea.

File: dev/ci/ci-common.sh (hunk 2 above)
Comment (ejgallego) [reply dev/ci/ci-common.sh:32]: It feels weird to mess manually with the OCaml setup, usually if using opam you would pin the package to the right tree and let the standard tooling take care, or you could vendor that.

As of today we manage opam CI deps in the docker image, so indeed we should somehow extend that mechanism, but then Nix people etc... I'm not sure where they land.

Comment (ejgallego) [reply dev/ci/ci-common.sh:32]: In any case, the right path for this, for example in a dune build, would be `_build/install/default/lib/menhir` etc....

File: dev/ci/ci-common.sh (hunk 1 above)
Comment (ejgallego) [reply dev/ci/ci-common.sh:31]: I see we already echo a lot of stuff tho, including this info. So if we want to clean that I'm fine but as of now the message wouldn't provide a lot of info IMO unless we make the output cleaner.

Comment (SkySkimmer) [reply dev/ci/ci-common.sh:31]: Maybe we should set -x only on the CI, locally it's not so useful.

File: dev/ci/ci-common.sh (hunk 2 above)
Comment (Zimmi48) [reply dev/ci/ci-common.sh:32]: Any local install is fine with me, but no global one (precisely because I'm a NixOS user).

File: dev/ci/ci-common.sh (hunk 1 above)
Comment (ejgallego) [reply dev/ci/ci-common.sh:31]: Yup; even in the CI I'd prefer a silent setup [and a full log as an artifact] , but I have very low visual tolerance for noisy builds

**Comment by ejgallego** [comment]
Ok, I have flushed my TODO for this PR, CI seems OK, notes:

- Jason's bug, fixed in the doc PR
- make ci-foo noisy: I agree, but IMHO let's handle that in its own PR
- menhir install and _install_ci : I have kept the current setup, but refactored the code a bit by common parts.

**Comment by Zimmi48** [comment]
@SkySkimmer do you want to be the assignee for this PR?

File: test-suite/misc/coq_environment.sh [hunk 3]
```diff
@@ -9,14 +9,15 @@ cd $TMP
 cat > coq_environment.txt <<EOT
 # we override COQLIB because we can
 COQLIB="$TMP/overridden" # bla bla
+COQCORELIB="$TMP/overridden" # bla bla
```
Comment (SkySkimmer) [inline test-suite/misc/coq_environment.sh:12]: What does "bla bla" mean here? cc @gares

File: test-suite/misc/coq_environment.sh [hunk 4]
```diff
@@ -9,14 +9,15 @@ cd $TMP
...
 OCAMLFIND="$TMP/overridden"
 FOOBAR="one more"
 EOT
 
 cp $BIN/coqc .
 cp $BIN/coq_makefile .
 mkdir -p overridden/tools/
-cp $COQLIB/tools/CoqMakefile.in overridden/tools/ || cp $COQLIB/../coq-core/tools/CoqMakefile.in overridden/tools/
+cp $COQLIB/../coq-core/tools/CoqMakefile.in overridden/tools/
```
Comment (SkySkimmer) [inline test-suite/misc/coq_environment.sh:20]: Why isn't this using coqcorelib?

**Review by SkySkimmer — APPROVED** [review]

File: test-suite/misc/coq_environment.sh (hunk 4 above)
Comment (ejgallego) [reply test-suite/misc/coq_environment.sh:20]: Because we don't set it yet in `test-suite/Makefile` ; I was planning to clean this up in #14058 but I've chosen to address all these kind of discrepancies on #14059

File: test-suite/misc/coq_environment.sh (hunk 3 above)
Comment (gares) [reply test-suite/misc/coq_environment.sh:12]: It tests we can put comments

**Comment by SkySkimmer** [comment]
@coqbot: merge now
