### PR TITLE
Fix #6631: Derive Plugin gives "Anomaly: more than one statement".

### LINKED ISSUE #6631: Derive Plugin gives "Error: Anomaly "more than one statement."" on abstract
#### Version

8.8+alpha

#### Description of the problem

```coq
Require Import Coq.derive.Derive.

Derive f SuchThat (f = 1 + 1) As feq.
Proof.
  transitivity 2.
  2:abstract vm_cast_no_check (eq_refl 2).
  (* Error: Anomaly "more than one statement."
Please report at http://coq.inria.fr/bugs/. *)
```

### PR DESCRIPTION
**Pull request by ppedrot**
We use a lower level function that accesses the proof without raising an
anomaly. This is a direct candidate for backport, so I used a V82 API but
eventually this API should be cleaned up.

Fixes #6631.

### CODE REVIEW

File: tactics/tactics.ml [hunk 1]
```diff
@@ -4987,15 +4987,15 @@ let anon_id = Id.of_string "anonymous"
...
-       with NoCurrentProof -> s, default_gk)
-    | None   ->
-      let name, gk =
-	try let name, gk, _ = Pfedit.current_proof_statement () in name, gk
-	with NoCurrentProof -> anon_id, default_gk in
-      add_suffix name suffix, gk
+  | Some s -> s, gk
+  | None ->
+    let name = Option.default anon_id name in
+    add_suffix name suffix, gk
```
Comment (ejgallego) [inline tactics/tactics.ml]: Uh, while you are at it, do you think it'd be possible to remove the dependency on global state here?

Comment (ppedrot) [reply tactics/tactics.ml]: Not sure how to do that easily, albeit desirable. There is a hierarchical dependency breakage here, abstract should not care about the name of the proof being generated.

Comment (ejgallego) [reply tactics/tactics.ml]: Yeah that's one of the very few blocking spots that the proof global removal patch has.

Comment (ppedrot) [reply tactics/tactics.ml]: A easy fix would be to generate a lemma-independent name using some kind of nonce. I believe that if you rely on the names of generated subproofs, you deserve to die. Also, a more radical solution would be to implement those godamn definition-local values that would properly solve the abstract side-effects hell.

Comment (ejgallego) [reply tactics/tactics.ml]: > you deserve to die.

Or to thread an argument around in all your functions. I dunno which is worse.

Comment (ppedrot) [reply tactics/tactics.ml]: I can try something with a uniquely generated deterministic name, like e.g. taking the hash of the goal type and taint it with the goal evar number or something.

Comment (ejgallego) [reply tactics/tactics.ml]: I've added your comments to my working patch list, I suggest you wait for a first candidate version of the Proof_global removal patch and then we see what we can do there, maybe there is a more convenient way.

Comment (JasonGross) [reply tactics/tactics.ml]: > I can try something with a uniquely generated deterministic name, like e.g. taking the hash of the goal type and taint it with the goal evar number or something.

Uh, I'd rather not that.  I can just imagine chasing down bugs of the form "abstract only succeeds if I create and then clear an evar just before creating the goal in which abstract is run" or something insane like that.

Comment (ejgallego) [reply tactics/tactics.ml]: The irony is that the above approach would be less broken than the current one [which works only because the parallel proof checking engine is not very capable as of today]
