### PR TITLE
Fix mulc on 32-bit architectures

### LINKED ISSUE #11321: Deviation in numerical computations between 32 and 64 bit build (Windows, possibly the same on other OS)
Dear Coq Team,

on 8.11 master I get deviations in numerical computations between 32 bit and 64 bit Windows builds with Interval. Since Interval is entirely written in Coq (no plugin) this might be an error in numerical computations in the VM and it is quite possible that @silene can construct a proof of False out of this.

The Code is
```
Require Import Reals Coquelicot.Coquelicot.
Require Import Interval.Tactic.

Goal True.
interval_intro (Rabs (RInt (fun x => exp x) 0 3 - (exp(1)*exp(1)*exp(1) - 1))) with (i_integral_depth 0, i_integral_deg 12).
```

On a 64 bit Windows build I get the correct answer:
```
H : 0 <= Rabs (RInt (fun x : R => exp x) 0 3 - (exp 1 * exp 1 * exp 1 - 1)) <= 26 / 33554432
```

On 32 bit Windows I get the wrong answer:
```
H : 6607721 / 33554432 <= Rabs (RInt (fun x : R => exp x) 0 3 - (exp 1 * exp 1 * exp 1 - 1)) <=
    31676929 / 33554432
```

I set this to priority blocker because I think one should at least resarch if a proof of False can be made out of this before the next release or give a warning that 32 bit builds might be unstable.

### PR DESCRIPTION
**Pull request by silene**
Fixes #11321

### CODE REVIEW

File: kernel/uint63_31.ml [hunk 1]
```diff
@@ -118,27 +118,29 @@ let div21 xh xl y =
 let div21 xh xl y =
   if Int64.compare y xh <= 0 then zero, zero else div21 xh xl y
 
-     (* exact multiplication *)
+(* exact multiplication *)
```
[the remark this answers is not in the document]
Comment (MSoegtropIMC) [reply kernel/uint63_31.ml]: I guess I get it now - this are 63 bit integers contained in an 64 bit integer type. The "0x7FFF_FFFF_FFFF_FFFFL" syntax is confusing - it gives the impression that 32 bit OCaml has a built in 63 bit integer type, but I guess this is simply not the case. So "0x7FFF_FFFF_FFFF_FFFFL" is an Int64 literal?

File: kernel/uint63_31.ml [hunk 2]
```diff
@@ -118,27 +118,29 @@ let div21 xh xl y =
...
-
-let equal x y = mask63 x = mask63 y
+  (* compute the median products *)
+  let s = Int64.add (Int64.mul lx hy) (Int64.mul hx ly) in
+  (* s fits on 64 bits, split it into a 33-bit high part and a 31-bit low part *)
+  let lr = Int64.shift_left (Int64.logand s maxuint31) 31 in
+  let hr = Int64.shift_right_logical s 31 in
+  (* add the outer products *)
+  let lr = Int64.add (Int64.mul lx ly) lr in
+  let hr = Int64.add (Int64.mul hx hy) hr in
```
Comment (MSoegtropIMC) [inline kernel/uint63_31.ml]: Can't hr overflow by one to 2^64? As far as I understand hr can be up to
(2^32-1)*(2^32-1)+(2^33-1) = 2^64 - 2^33 + 1 + 2^33 -1 = 2^64
Is this taken care of below?

Comment (MSoegtropIMC) [reply kernel/uint63_31.ml]: Ah no, it is fine since the high part of s cannot be 2^33-1:
The maximum value of s is
2*(2^31-1)(2^32-1)=2*(2^63-2^31-2^32+1)=2^64-2^32-2^33+2
So if this is right shifted by 31, we get 2^33-2^1-2^2 = 2^33-6.
Since this is not so obvious (at least to me), you might want to document this.

**Review by MSoegtropIMC — APPROVED** [review]
All fine excpt that some subtleties should be documented.

File: kernel/uint63_31.ml (hunk 1 above)
[the remark this answers is not in the document]
Comment (silene) [reply kernel/uint63_31.ml]: Yes. Quoting OCaml's documentation, "literals for 64-bit integers are suffixed by L".

File: kernel/uint63_31.ml (hunk 2 above)
Comment (silene) [reply kernel/uint63_31.ml]: Your reasoning is right, but there is a much simpler way to prove the absence of overflow: We are computing a 126-bit product and `hr` contains the part of the result starting at bit 62.

**Comment by ppedrot** [comment]
Can we get this in as fast as possible, as #11318 depends on this, and this affects the release?

File: kernel/uint63_31.ml (hunk 2 above)
Comment (MSoegtropIMC) [reply kernel/uint63_31.ml]: Indeed, I was a bit in a VST style C verification forward analysis mode. I think it still doesn't hurt to document things if a simple forward bit counting analysis is not sufficient to guarantee results are in range.

Pondering over my "L suffix means they introduced a 63 bit integer type in 32 bit OCaml" confusion: in hindsight it is clear. Only if others reading this say they haven't seen this "L" suffix syntax before, I would think about putting in a short hint that this is the syntax for 64 bit integers. I still think that not that many people think about 63/64 bit integer arithmetic on 32 bit platforms so knowledge on the details might be less widespread than an expert in this area like you might think.

**Comment by MSoegtropIMC** [comment]
> Can we get this in as fast as possible, as #11318 depends on this, and this affects the release?

I will do a cherry pick of this into 11318 and do local and CI tests with it. If this is successful I will merge this PR unless someone objects. I all also add some tough tests which need more than 64 bit final result precision (need to develop these first).

**Review by JasonGross — CHANGES_REQUESTED** [review]
Shouldn't we add test-suite cases that would have caught the bug when run on 32-bit machines (and ideally also unit tests for these methods)?  Also an entry in the list of critical bugs?

**Comment by Zimmi48** [comment]
> Shouldn't we add test-suite cases that would have caught the bug when run on 32-bit machines (and ideally also unit tests for these methods)? Also an entry in the list of critical bugs?

Note that while I agree with all what you said, I disagree with making this a "requested change" and not just a suggestion since the PR itself might be one of the last remaining blockers for the 8.11.0 release.

**Comment by MSoegtropIMC** [comment]
> Shouldn't we add test-suite cases that would have caught the bug when run on 32-bit machines (and ideally also unit tests for these methods)? Also an entry in the list of critical bugs?

I will do the test cases in a separate PR. The best way to test arithmetic is to run the test suite and some addtional tough cases of the interval tactic (this as well as the division bug was found this way). But the interval tactic does not build on 8.11 and later cause of changes in the Reals library. At least a patch is on the way (#11318). If this is in I will add such tests to 8.11 (well at least on Windows there are in then - this was found by a CI failure of #11318). For master I would prefer if @silene integrates theses changes in interval upstream and we add interval to CI in upstream afterwards.

**Comment by JasonGross** [comment]
> I disagree with making this a "requested change" and not just a suggestion since the PR itself might be one of the last remaining blockers for the 8.11.0 release

Sure, feel free to consider my request non-blocking

**Comment by silene** [comment]
> Shouldn't we add test-suite cases that would have caught the bug when run on 32-bit machines

Note that you do not even need a 32-bit machine, as this code works just fine on a 64-bit machine (that is how I tested it). In fact, the multiplication code from `uint63_31.ml` is much faster than the one from `uint63_63.ml` on a 64-bit machine. That might seem counterintuitive, but the former has access to a full 32x32 multiplier, while the latter is stuck with a crippled 32x31 multiplier. So, ultimately, the same code should be used for both 32-bit and 64-bit architectures, hence making testing much simpler.

**Comment by MSoegtropIMC** [comment]
For the records the Interval test suite did run through on 32 bit windows with these changes cherry-picked:
[pipeline](https://gitlab.com/coq/coq/pipelines/104926582)
[32 bit win test log](https://coq.gitlab.io/-/coq/-/jobs/386865978/artifacts/artifacts/buildlogs/interval-839a03e1bddbafab868fbceee59abe678e32a0f3-remake_check_log.txt)
[64 bit win test log](https://coq.gitlab.io/-/coq/-/jobs/386828092/artifacts/artifacts/buildlogs/interval-839a03e1bddbafab868fbceee59abe678e32a0f3-remake_check_log.txt)

I will now design a few tests which require high precision (say comparing different ways to compute pi to 100 bits and a high precision polynomial approximation of some function) test these locally and then integrate this PR to master and 8.11.

@silene : can you (or someone else) please do the entry to the list of critical bugs requested by @JasonGross? I would say we agreed that the test cases are added a bit later.

**Comment by MSoegtropIMC** [comment]
This is my first batch of tests: compute pi in 5 different ways to 256 and 1024 bits and compare these with the integrated pi. With the new function from @silene this works on 32 bit and 64 bit Windows. Btw.: if you are afraid that this takes long: all 10 test together take less than 10 seconds - a fact I find quite amazing.

@silene: I also tried to compute pi via integrals to high precision but didn't suceed. E.g. I didn't manage to compute the circle integral to more than 12 bits. I guess I need some help with the parameters.

As I mentioned I will do a few more tests on high precision polynomial function approximation.

[example_2019_02_23_pi_machin.txt](https://github.com/coq/coq/files/3994592/example_2019_02_23_pi_machin.txt)

**Comment by MSoegtropIMC** [comment]
Here is my second test: a polynomial approximation of sine between 0 and 1.6 which has a deviation of less than 2^-140 in this range. The polynomial is degree 28 and has coefficients which are integer multiples of 2^-170. The checks are done for various bounds with various precisions. The 140 bit precision test is done with 150 bit arithmetic. The final test computes in about 30s on 64 bit Coq and 50s on 32 bit Coq (might be faster for you - I have Xeons which are more optimized for reliability and parallel performance). Btw.: the actual peak error of teh approximation is around 2^-140.6.

I would say that this is a fairly tough test of the arithmetic at various precisions. The 140 bit precision proof requires 18th degree taylor with 2^9 bisection. So large terms of huge numbers must cancel out at quite a few points to very high precision.

Unless someone objects I will add a note to the critical erros file as requested by @JasonGross and merge this PR today evening. I will add Interval and these tests to CI at a later point (after the 2.11 compatibility changes are merged upstream).

[example_2019_12_26_sin_approx.txt](https://github.com/coq/coq/files/4002559/example_2019_12_26_sin_approx.txt)

**Comment by MSoegtropIMC** [comment]
A short note: interestingly the bug was not introduced with the code @silene fixed. This code was introduced (afaikt) in 8.8.0. The bug is not there up to including 8.9.1 but it is there in 8.10.2. Still doing bisections to find out when this started.

**Comment by silene** [comment]
> I didn't manage to compute the circle integral to more than 12 bits. I guess I need some help with the parameters.

The integrand of the circle integral is not differentiable, which makes it the worst way of numerically approximating pi that I know of way. (Obviously, one can always design worst ways, but it requires unnatural definitions of pi.) A back-of-the-envelope calculation shows that, to reach an accuracy of k bits despite the singularity, you need an integral depth of at least 2/3 * k; and an integral depth of 2 * k guarantees that the computation succeeds (assuming the floating-point precision is high enough, e.g., k + 20). Due to the singularity, using high-degree Taylor models is a waste of time. To summarize, the following options should give you 30 bits of accuracy, though it will be quite slow: `i_integral_width (-30), i_integral_depth 30, i_prec 40, i_integral_deg 7`.

If you want to compute pi using a simple integral, just use 1 / (1+x^2) as the integrand. You can get an accuracy of 60 bits in about one second.

> This code was introduced (afaikt) in 8.8.0. The bug is not there up to including 8.9.1 but it is there in 8.10.2.

As far as I know, the bug was introduced in e43b1768d0f8399f426b92f4dfe31955daceb1a4, so only versions after 8.10 are impacted.

**Comment by MSoegtropIMC** [comment]
> The integrand of the circle integral is not differentiable, which makes it the worst way of numerically approximating pi that I know of way.

Well that's the point of using it as a test for the compute engine - compute something which is rather hard to compute but easy to test for correctness. But I agree that this is not a good test case if achievable precision is only 30 bits. I am looking for an integral that can be computed to more than 128 bits so that even on 64 bit machines one needs more than two words. Also with such high precision if anything goes wrong in the integral in any subinterval it is extremely unlikely that the error is compensated to more than 128 bits elsewhere. With 30 bits precision and a subdivision depth of 30 this is not so unlikely since the integral over some subintervals has about the size of the result precision. I will experiment with 1 / (1+x^2) and see if I can integrate it to 140 bits or so.

I think tests for the numercis engine should run for a few minutes in total and be designed such that if anything goes wrong in these few minutes it is likely that the tested results are wrong. The idea of having tests running for a few minutes is that one gets sufficient "random" coverage. I think it doesn't hurt if the CI for interval runs for 10 minutes.

Btw.: I know that everything beyond mulc and div21 is currently proven correct in Coq so there is no point in going to triple words. The reason I put in 140 bit tests is that one cannot exclude that this changes in some future (that is that there is an arbitrary precision integer primitive type). I just want to be on the safe side in case this happens.

**Comment by MSoegtropIMC** [comment]
@silene : as far as I can tell this test case fails both on systems which have the bug (on the second vm_compute) and those which don't have the bug (on the first vm_compute). The test case must be written such that it fails when the error is there and suceeds if it is not there.

I must say I don't see why the second vm_compute should deliver a different value than the first. I experimented with
```
assert( BigN.mul (BigN.pow 2 32) (BigN.pow 2 31) = (BigN.pow 2 64) ) by reflexivity.
assert( BigN.mul (BigN.pow 2 32) (BigN.pow 2 31) = (BigN.pow 2 63) ).
```
and wanted to prove the second one with BigN.pow_add_r but this seems to require a setoid rewrite and the required proper lemmas don't seem to be there for BigN.

Btw.: there is no need for vm_compute. The bug is also there in normal computations.

An extract from the test log:
```
    bugs/closed/bug_11048.v...Ok
    bugs/closed/bug_11161.v...Ok
    bugs/closed/bug_11321.v...Error! (bug seems to be opened, please check)
    bugs/closed/bug_1238.v...Ok
    bugs/closed/bug_1243.v...Ok
```

**Comment by silene** [comment]
The second `vm_compute` is not supposed to fail for systems with the bug. I am not sure what is going wrong there.

**Comment by MSoegtropIMC** [comment]
> The second `vm_compute` is not supposed to fail for systems with the bug. I am not sure what is going wrong there.

on a system where
```
From Bignums Require Import BigN.
Require Import Setoid.

Lemma foo : False.
Proof.
assert( BigN.mul (BigN.pow 2 32) (BigN.pow 2 31) = (BigN.pow 2 64) ) by reflexivity.
:
```
goes through (8.10.2 Windows 32 bit) the 2nd vm_compute also results in the wrong value (2^64), so it is 2^64=2^64 -> False. I actually don't see why the result of the first and second vm_compute should be different.

One thought: since one want to have a test case that 2^31*2^32 is computes correctly, why not simply do an obvious:
```
From Bignums Require Import BigN.
Require Import Setoid.

Lemma Test: (2^31*2^32=2^63)%bigN.
Proof.
  reflexivity.
Qed.
```
This passes on good systems and fails on bad systems.

**Comment by MSoegtropIMC** [comment]
P.S.: do you think it makes sense to have for each critical error separate files for an exploit (proof of False) and a testcase?

**Comment by MSoegtropIMC** [comment]
I regard @JasonGross change request as fullfilled and will merge this now.
