### PR TITLE
Fix #9294: critical bug with template polymorphism

### LINKED ISSUE #9294: Template polymorphism breaks Prop/Set separation
ie we can get a Prop equivalent to any Set, in this example equivalent to `nat`.
~~~coq
Inductive Foo@{i} (A:Type@{i}) : Type := foo : (nat:Type@{i}) -> Foo A.
Arguments foo {_} _.

Check Foo True : Prop. (* should fail *)

Definition bar : Foo True -> nat := fun '(foo x) => x.

Definition foo_bar n : foo (bar n) = n.
Proof. destruct n;reflexivity. Qed.

Definition bar_foo n : bar (foo n) = n.
Proof. reflexivity. Qed.
~~~

I think we can't actually get a proof of false from this without the kind of axiom which breaks impredicative set but still marking as critical.

The root cause is that we typecheck the inductive with universes considered >= Set but then template polymorphism allows instantiating with Prop.

Not sure if there's a way to trigger this with neither `@{i}` or explicit `#[universes(template)]` syntax (if I don't use the `@{i}` universes unify differently) but plugins could probably do it since a long time ago (maybe since universe polymorphism, maybe before, I don't know how universes worked before).

### PR DESCRIPTION
**Pull request by maximedenes**
This is adapted from #9444, and contains only the infrastructure required to fix #9294. It does not generalize universe polymorphism to `Prop` instances.

This is still work in progress, and will require some fixes.

### CODE REVIEW

File: pretyping/pretyping.ml [hunk 1]
```diff
@@ -419,7 +419,10 @@ let interp_instance ?loc evd l =
          (evd, l :: univs)) (evd, [])
       l
   in
-  if List.exists (fun l -> Univ.Level.is_prop l) l' then
+  let lbound = Global.universes_lbound () in
+  if List.exists (fun l -> Univ.Level.is_prop l &&
+                           Evd.check_leq evd (Univ.Universe.super (Univ.Universe.make l))
+                             (Univ.Universe.make lbound)) l' then
```
Comment (mattam82) [inline pretyping/pretyping.ml]: That looks a bit suspicious. We should still always disallow prop in instances, so I'd come back to the earlier version.

**Comment by maximedenes** [comment]
With the fix you suggested, here are the tests that are failing:
```
    success/name_mangling.v...could not be checked (Error!)
    success/name_mangling.v...Error! (should be accepted)
    success/primitiveproj.v...could not be checked (Error!)
    success/primitiveproj.v...Error! (should be accepted)
    success/Record.v...could not be checked (Error!)
    success/Record.v...Error! (should be accepted)
    success/sprop_hcons.v...could not be checked (Error!)
    success/sprop_hcons.v...Error! (should be accepted)
    success/sprop.v...could not be checked (Error!)
    success/sprop.v...Error! (should be accepted)
    bugs/closed/bug_3125.v...Error! (bug seems to be opened, please check)
    bugs/closed/bug_4622.v...Error! (bug seems to be opened, please check)
    bugs/closed/bug_5281.v...Error! (bug seems to be opened, please check)
    bugs/closed/bug_sprop_14.v...Error! (bug seems to be opened, please check)
    bugs/closed/HoTT_coq_093.v...Error! (bug seems to be opened, please check)
    output/NumeralNotations.v...Error! (unexpected output)
    output/UnivBinders.v...Error! (unexpected output)
```

The output tests failures are due to more constraints being printed.

File: vernac/comInductive.ml [hunk 2]
```diff
@@ -255,7 +258,7 @@ let solve_constraints_system levels level_bounds =
   done;
   v
 
-let inductive_levels env evd poly arities inds =
+let inductive_levels env evd arities inds =
   let destarities = List.map (fun x -> x, Reduction.dest_arity env x) arities in
   let levels = List.map (fun (x,(ctx,a)) ->
     if Sorts.is_prop a || Sorts.is_sprop a then None
```
Comment (mattam82) [inline vernac/comInductive.ml]: We should not do the "is_flexible_sort" stuff that handles "natural" props in the template_poly case, as that turns inductives in Prop when they were in Type@{i} for any i I think. That is why 3125 fails I think.

Comment (maximedenes) [reply vernac/comInductive.ml]: I'm a bit lost. Wasn't the `is_flexible_sort` stuff made precisely for template polymorphic inductives, that didn't really need to be?

Comment (mattam82) [reply vernac/comInductive.ml]: Nope, I think the is_flexible_sort stuff is rather for inferring the sort of "natural" propositions in Prop, but template polymorphic ones should stay in Type@{i} I believe. At least that's how I understand 3125.

**Comment by Zimmi48** [comment]
Is this on purpose that you put it in 8.10+beta1 rather than in 8.9.1?

**Comment by maximedenes** [comment]
> Is this on purpose that you put it in 8.10+beta1 rather than in 8.9.1?

I think it is going to be a bit painful to backport, but we can try.

File: pretyping/pretyping.ml (hunk 1 above)
Comment (JasonGross) [reply pretyping/pretyping.ml]: Why should we disallow prop in instances?

**Comment by mattam82** [comment]
Alright. We were just missing the same thing for records as inductives. Now the test-suite passes almost entirely, we're down to sprop universe inconsistencies I don't understand (!).

**Comment by mattam82** [comment]
I was guilty for sprop, and also for a minor change in the output tests for universes, both fixed now. This passes the test-suite. Now let's see if the more liberal elaboration constraints for template-polymorphic inductive declarations (anonymous universes can be instantiated with Prop) change anything in the CI.

**Comment by mattam82** [comment]
So, unsurprisingly, people use:

```
Section Foo.
  Context (A : Type).

  blah blah doing stuff with A that shouldn't allow it to be `True`.

  Ind I : Type := ...
End Foo.
```
And they expect `I` to be template-polymorphic on `A`'s universe, which I don't allow anymore. Avoiding the problematic case is a matter of defining the inductive separately. Don't know if that's easy to do in all examples.

**Comment by mattam82** [comment]
For paramcoq, the issue is that the relation for an inductive reuses the same universes as the inductive, so when checking that it is template none of the universe variables are seen as introduced by the inductive, so template-polymorphism does not apply anymore. Solution: refresh the universes.

For vst, the issue is that a failure of template-polymorphism, due to a definition of an inductive in a section in CompCert `cfrontend/Ctypes.v#fundef`, changes an automatic hyp naming (because something which was in Set turns into Type, so `H5` becomes `X`). Assigning the right name fixes it, as well as modifying the type definition in CompCert to be done outside a section.

For bedrock2, it's a definition of vectors in a section, changing hyp naming again. (Maybe other issues as well).

For ci-fiat-crypto-legacy, I'll see when it finished compiling...

**Comment by SkySkimmer** [comment]
For fiat-crypto legacy it's probably this bit https://github.com/mit-plv/fiat-crypto/blob/847b18bf8f38f7262331181f25ca96aee0423f52/src/Compilers/Syntax.v#L14-L16 inductive in a section later tries to be applied to a Set.

**Comment by mattam82** [comment]
I tried many things to treat template-polymorphism in sections but nothing satisfactory can be done: to be really safe we would have to elaborate everything in sections with `Prop <= i` constraints and do global checks at discharge time if some universe we're parameterizing on has been constrained elsewhere (good luck reporting a nice error there): in short that's ugly and too big a change. One halfway solution could be to have a typing_flag to govern the use of the stricter check that is implemented in this PR without delaying the release any further. @maximedenes @ppedrot @vbgl @herbelin what's your opinion on that solution?

Note that this all points to providing a clean solution to *sort* polymorphism (think PTS parameterization) and not just *universe-level* polymorphism, to support template-polymorphic style lowering to Prop but also multiple universe hierachies. This would also help improve elaboration of Prop/SProp by introducing a proper notion of sort variable that can be instantiated with impredicative or predicative universes (the later being further parameterized by a level). I'm planning to write up a CEP on that in the future (after the POPL deadline).

**Comment by vbgl** [comment]
Just to be sure: disabling the stricter check — using the typing flag you propose — is unsound (but convenient in some cases).

**Comment by mattam82** [comment]
Yes, disabling it means you can write unsound instances, just like with type-in-type.

**Comment by vbgl** [comment]
Thanks. Then what you propose sounds like a good plan to me.

**Comment by vbgl** [comment]
@mattam82 Any news regarding the implementation of your plan? It would be nice if we could at last release version 8.10.

**Comment by mattam82** [comment]
I’m sorry I got really busy with something else. I’ll get on it today and tomorrow

**Comment by mattam82** [comment]
Let's see where this gets up. New typing flag "-no-template-check" will have to be used on some contribs (e.g. parametricity)

**Comment by maximedenes** [comment]
> Avoiding the problematic case is a matter of defining the inductive separately. Don't know if that's easy to do in all examples.

Did fixing the problematic developments  turn out to be very difficult?

I'm not a big fan of introducing a flag for compatibility with a critical bug. What would be the value of a formal proof checked with the flag?

**Comment by mattam82** [comment]
I’m not a big fan either but I don’t have the time to fix fiat-parsers and parancoq and neither to implement the better solutions of using cumulative polymorphic inductives. There are cases that are not easily portable, e.g when using definitions hiding constraints on a section variable that requires moving also these definitions to polymorphic ones.

**Comment by mattam82** [comment]
Without the check, one can still manually ensure if a template inductive can rightfully be lowered, but as the CI shows it’s (thankfully) rarely needed. Note that for paramcoq there is a sound solution which is to refresh universe names when creating the relations for template-polymorphic inductives. That one is doable.

**Comment by maximedenes** [comment]
> I don’t have the time to fix fiat-parsers and parancoq and neither to implement the better solutions of using cumulative polymorphic inductives

Oh sure, I don't think you should be left alone dealing with this. My point was that it is more or less expected that developments relying on bugs (and even more so for critical ones) are expected to be broken by fixes. CI testing is mainly for discovering regressions early, it is not meant to prevent applying fixes.

Of course, we should collectively do our best to help downstream authors port their developments to fixed versions of Coq.

So I guess it depends what the purpose of the flag is. Is it to make (incremental) porting easier? If so, maybe we should deprecate it as we introduce it, and remove it from the next version. Also, we should not forget to open issues on the developments which require the flag and coordinate with their authors.

**Comment by mattam82** [comment]
Yes, that’s the idea, to give an option to help users fix their developments incrementally. It should be deprecated only if we know that we have a proper solution that allows instantiations of what I would call sort-polymorphic constructions. My plan is to work on that in the coming months, and it has links with other efforts: treating Prop/SProp correctly during elaboration and supporting multiple sort hierarchies for Pédrot and Tabareau’s effectful type theories. That’s however a non-trivial change so it’s hard to evaluate the timeline for this without at least prototyping it.

File: kernel/environ.mli [hunk 3]
```diff
@@ -51,8 +51,9 @@ type globals
 
 type stratification = {
   env_universes : UGraph.t;
-  env_engagement : engagement;
   env_sprop_allowed : bool;
+  env_universes_lbound : Univ.Level.t;
```
Comment (SkySkimmer) [inline kernel/environ.mli]: Should it be here or would it make more sense in the UGraph.t?

Comment (mattam82) [reply kernel/environ.mli]: Not sure, we set it dynamically to elaborate template inductives with `Prop <= i` by default for new universes. The graph itself is pretty agnostic to it (we just insert different constraints in it).

**Comment by mattam82** [comment]
Well, that worked!

**Comment by vbgl** [comment]
Thanks Matthieu for addressing this issue. It seems that only a bit of documentation is missing.

**Comment by mattam82** [comment]
I’ll have that done today. I think we should make it clear in the announcement. Is there an .md / .rst file I can add a long example to?

**Comment by SkySkimmer** [comment]
Around https://github.com/coq/coq/blob/master/doc/sphinx/language/cic.rst#template-polymorphism I guess

**Comment by mattam82** [comment]
Thanks. I don't know where to look for the beautified version of my changelog entry, it didn't appear magically when making `make -f Makefile.dune refman-html`

**Comment by vbgl** [comment]
The change log entry did not show up because the name of the file holding said entry should en with `.rst`. I’ve just renamed it.

I’ve also fixed a minor markup issue that broke the CI build.

**Comment by mattam82** [comment]
I've copied from `10439-uniform-opaque-seff-handling.md`, so that one should probably be changed to a `.rst` as well.

**Comment by mattam82** [comment]
I guess the OOM on fiat-crypto is unrelated.

**Comment by vbgl** [comment]
> I've copied from `10439-uniform-opaque-seff-handling.md`, so that one should probably be changed to a `.rst` as well.

Or the program that builds the changelog from these files may be more lenient on the file names. Théo, what do you think? (cc @Zimmi48).

**Comment by Zimmi48** [comment]
> > I've copied from `10439-uniform-opaque-seff-handling.md`, so that one should probably be changed to a `.rst` as well.
> 
> Or the program that builds the changelog from these files may be more lenient on the file names. Théo, what do you think? (cc @Zimmi48).

Well, `rst` and `md` do not bear the same format, so that would not make sense, unless we do some translation between formats which would require a dependency such as pandoc, so no.
Short-term solution would be for the build to catch that there are unknown extensions in the folder and to fail because of this (but beware of `~` and other common hidden files).
Long-term solution is probably going to be to adopt a more structured (custom) format for these files anyway, given the high-rate of errors that developers make when writing them...

**Comment by Zimmi48** [comment]
I had reviewed #10439 and did not even notice the wrong extension, which proves that a CI check is actually needed for this.

**Comment by vbgl** [comment]
Note that I did not suggest to accept any file format. Just any file name.

File: doc/changelog/01-kernel/09918-unsound-template-polymorphism.rst [hunk 4]
```diff
@@ -0,0 +1,25 @@
+- Declarations of template-polymorphic inductive types ignored the
+  provenance of the universes they were abstracting on and did not
+  detect if they should be greater or equal to Set in general. Previous
```
Comment (Zimmi48) [inline doc/changelog/01-kernel/09918-unsound-template-polymorphism.rst]: Could be:

```suggestion
  detect if they should be greater or equal to :g:`Set` in general. Previous
```

or

```suggestion
  detect if they should be greater or equal to :math:`\Set` in general. Previous
```

File: doc/changelog/01-kernel/09918-unsound-template-polymorphism.rst [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+  polymorphic over section parameters. For a backward compatible fix,
+  simply hoist the inductive definition out of the section.
+  An alternative is to declare the inductive as universe-polymorphic and
+  cumulative in a universe-polymorphic section: all universes and
+  constraints will be properly gathered in this case.
+  See :ref:`Template-polymorphism` for a detailed exposition of the
+  rules governing template-polymorphic types.
+
+  To help users incrementally fix this issue, a command line option
+  `-no-template-check` and a global option `Unset Template Check` are
```
Comment (Zimmi48) [inline doc/changelog/01-kernel/09918-unsound-template-polymorphism.rst]:
```suggestion
  `-no-template-check` and a global flag :flag:`Template Check` are
```

File: doc/sphinx/language/cic.rst [hunk 6]
```diff
@@ -1117,10 +1117,11 @@ provided that the following side conditions hold:
     + there are sorts :math:`s_i`, for :math:`1 ≤ i ≤ k` such that, for
       :math:`Γ_{I'} = [I_1 :∀ Γ_{P'} ,(A_1)_{/s_1} ;~…;~I_k :∀ Γ_{P'} ,(A_k)_{/s_k}]`
       we have :math:`(E[Γ_{I′} ;Γ_{P′}] ⊢ C_i : s_{q_i})_{i=1… n}` ;
-    + the sorts :math:`s_i` are such that all eliminations, to
-      :math:`\Prop`, :math:`\Set` and :math:`\Type(j)`, are allowed
-      (see Section :ref:`Destructors`).
-
+    + the sorts :math:`s_i` are all introduced by the inductive
+      declaration and have no universe constraints beside being greater
+      than or equal to :math:`Prop`, and such that all
```
Comment (Zimmi48) [inline doc/sphinx/language/cic.rst]:
```suggestion
      than or equal to :math:`\Prop`, and such that all
```

File: doc/sphinx/language/cic.rst [hunk 7]
```diff
@@ -1141,6 +1142,26 @@ Conversion is preserved as any (partial) instance :math:`I_j~q_1 … q_r` or
...
+.. flag:: Template Check
+
+   Unsetting option :flag:`Template Check` disables the check of
+   locality of the sorts when abstracting the inductive over its
+   parameters. This is an *unsafe* flag that can introduce
+   inconsistencies, it is only meant to help users incrementally update
+   code from Coq versions < 8.10 which did not implement this check. A
+   global ``-no-template-check`` command line option is also
+   available. Use at your own risk. Use of this flag is recorded in the
+   typing flags associated to a definition.
```
Comment (Zimmi48) [inline doc/sphinx/language/cic.rst]: And thus displayed by the `Print Assumption` command, right? If so, probably worth to say it explicitly.

**Review by Zimmi48 — COMMENTED** [review]
Should probably be documented in `dev/doc/critical-bugs` as well.

BTW, a more general comment about the proposed fix: first, congrats on explaining the issue at stake very well, second since IIUC no inductive declaration inside a section will be template-polymorphic anymore (unless the unsafe flag is set), what about emitting a new (documented of course) warning similar to the one that @SkySkimmer introduced about template polymorphic declarations (but which was silenced by default)? This warning would say: this inductive declaration is not template polymorphic because it is inside a section, and then would go on by proposing the three safe options of setting the no-template attribute to silence the warning, making the inductive full universe polymorphic, or moving it out of the section to keep it template polymorphic.

**Comment by Zimmi48** [comment]
> Note that I did not suggest to accept any file format. Just any file name.

Sorry, I don't get it.

**Comment by maximedenes** [comment]
@vbgl was not suggesting to accept markdown files, just to accept any name for an rst file. No pandoc needed.

**Comment by Zimmi48** [comment]
> @vbgl was not suggesting to accept markdown files, just to accept any name for an rst file. No pandoc needed.

Well, why not. Although, that would be a bit weird if we start to have many `md` files which actually contain Sphinx format.

**Comment by Zimmi48** [comment]
@mattam82: the documentation says the name of the flag is `Template Check` but the one that is actually defined is `Template Polymorphic Inductive Check`.

File: doc/sphinx/language/cic.rst (hunk 7 above)
Comment (Zimmi48) [reply doc/sphinx/language/cic.rst]: Actually it doesn't look like `Print Assumptions` print anything. Shouldn't it?

**Comment by Zimmi48** [comment]
This code should fail: the explitcit attribute shouldn't be silently ignored:

```
Polymorphic Definition f@{i} : Type@{i} := nat.
Polymorphic Definition baz@{i} : Type@{i} -> Type@{i} := fun x => x.

Section Foo.
  Universe u.
  Context (A : Type@{u}).

  #[universes(template)] Inductive Bar :=
  | bar : A -> Bar.

End Foo.
```

**Comment by Zimmi48** [comment]
This code should not fail, since the inductive is actually not declared template polymorphic, i.e. the warning should not be emitted:

```
Set Warnings "+auto-template".
Section Foo.
  Universe u.
  Context (A : Type@{u}).

  Inductive Bar :=
  | bar : A -> Bar.

End Foo.
```

File: kernel/indTyping.mli [hunk 8]
```diff
@@ -33,3 +34,10 @@ val typecheck_inductive : env -> mutual_inductive_entry ->
      (Constr.rel_context * (Constr.rel_context * Constr.types) array) *
      Sorts.family)
     array
+
+type univ_info = { ind_squashed : bool; ind_has_relevant_arg : bool;
+                   ind_min_univ : Universe.t option; (* Some for template *)
+                   ind_univ : Universe.t }
+
+val check_univ_leq :  ?is_real_arg:bool ->
```
Comment (SkySkimmer) [inline kernel/indTyping.mli]: Why's this stuff exported?

File: kernel/indTyping.ml [hunk 9]
```diff
@@ -236,22 +236,43 @@ let allowed_sorts {ind_squashed;ind_univ;ind_min_univ=_;ind_has_relevant_arg=_}
   if not ind_squashed then InType
   else Sorts.family (Sorts.sort_of_univ ind_univ)
 
+(* For a level to be template polymorphic, it must be introduced
+   by the definition (so have no constraint except lbound <= l)
+   and not to be constrained from below, so any universe l' <= l
+   can be used as an instance of l. All bounds from above, i.e.
+   l <=/< r will be valid for any l' <= l. *)
+let unbounded_from_below u cstrs =
+  Univ.Constraint.for_all (fun (l, d, r) ->
```
Comment (SkySkimmer) [inline kernel/indTyping.ml]: Can't we ask the ugraph instead of folding over constraints?

**Review by JasonGross — DISMISSED** [review]
Please update the Compat/Coq810.v file (or whichever one it should be) to `Global Unset Template Check` (or whatever the option is called)

File: doc/sphinx/language/cic.rst (hunk 7 above)
Comment (mattam82) [reply doc/sphinx/language/cic.rst]: Indeed it should, the accessors to the use of the template-check are there already.

File: kernel/indTyping.mli (hunk 8 above)
Comment (mattam82) [reply kernel/indTyping.mli]: Good point, remnant of debugging.

File: vernac/vernacentries.ml [hunk 10]
```diff
@@ -607,6 +607,24 @@ let vernac_assumption ~atts discharge kind l nl =
...
+let is_template_check () =
+  let typing_flags = Environ.typing_flags (Global.env ()) in
+  typing_flags.Declarations.check_template
+
+let () =
+  let tccheck =
+    { optdepr = true;
+      optname = "Template universe check";
+      optkey = ["Template"; "Polymorphic"; "Inductive"; "Check"];
+      optread = (fun () -> is_template_check ());
```
Comment (mattam82) [inline vernac/vernacentries.ml]: What do you guys prefer? The longer name is more explicit... but maybe overkill as we don't expect many users and this is already deprecated?

File: kernel/indTyping.ml [hunk 11]
```diff
@@ -286,10 +307,14 @@ let typecheck_inductive env (mie:mutual_inductive_entry) =
...
 
+  let has_template_poly = List.exists (fun oie -> oie.mind_entry_template) mie.mind_entry_inds in
+
   (* universes *)
   let env_univs =
     match mie.mind_entry_universes with
-    | Monomorphic_entry ctx -> push_context_set ctx env
+    | Monomorphic_entry ctx ->
+      let env = if has_template_poly then set_universes_lbound env Univ.Level.prop else env in
+      push_context_set ctx env
```
Comment (SkySkimmer) [inline kernel/indTyping.ml]: push_context_set catches the AlreadyDeclared exception, given that afterwards we assume the universes in ctx are new this is problematic.
We hope to someday stop catching this exception but sideeffect intricacies prevent it for now, so I guess adding an optional argument `?enforce_fresh` (defaulting with current behaviour) should be added to push_context_set

File: vernac/vernacentries.ml (hunk 10 above)
Comment (Zimmi48) [reply vernac/vernacentries.ml]: I prefer the shorter name.

**Comment by mattam82** [comment]
> This code should fail: the explitcit attribute shouldn't be silently ignored:
> 
> ```
> Section Foo.
>   Universe u.
>   Context (A : Type@{u}).
> 
>   #[universes(template)] Inductive Bar :=
>   | bar : A -> Bar.
> 
> End Foo.
> ```

I don't think so, it might take other parameters for which template polymorphism would be fine.

**Comment by mattam82** [comment]
> This code should not fail, since the inductive is actually not declared template polymorphic, i.e. the warning should not be emitted:
> 
> ```
> Set Warnings "+auto-template".
> Section Foo.
>   Universe u.
>   Context (A : Type@{u}).
> 
>   Inductive Bar :=
>   | bar : A -> Bar.
> 
> End Foo.
> ```

Same thing, it might be template polymorphic on other parameters. I will try to refine the code to not declare an inductive as template polymorphic if the inductive is template polymorphic on no universes after the check.

File: doc/changelog/01-kernel/09918-unsound-template-polymorphism.rst [hunk 12]
```diff
@@ -0,0 +1,25 @@
+- Declarations of template-polymorphic inductive types ignored the
+  provenance of the universes they were abstracting on and did not
+  detect if they should be greater or equal to :math:`Set` in
```
Comment (Zimmi48) [inline doc/changelog/01-kernel/09918-unsound-template-polymorphism.rst]:
```suggestion
  detect if they should be greater or equal to :math:`\Set` in
```

File: doc/changelog/01-kernel/09918-unsound-template-polymorphism.rst [hunk 13]
```diff
@@ -0,0 +1,25 @@
...
+  general. Previous universes and universes introduced by the inductive
+  definition could have constraints that prevented their instantiation
+  with e.g. :math:`Prop`, resulting in unsound instantiations later. The
```
Comment (Zimmi48) [inline doc/changelog/01-kernel/09918-unsound-template-polymorphism.rst]:
```suggestion
  with e.g. :math:`\Prop`, resulting in unsound instantiations later. The
```

File: doc/sphinx/language/cic.rst [hunk 14]
```diff
@@ -1141,6 +1142,26 @@ Conversion is preserved as any (partial) instance :math:`I_j~q_1 … q_r` or
 :math:`C_i~q_1 … q_r` is mapped to the names chosen in the specific instance of
 :math:`\ind{p}{Γ_I}{Γ_C}`.
 
+.. warning::
+
+   The restriction that sorts are introduced by the inductive
+   declaration prevents inductive types declared in sections to
+   be template-polymorphic: they cannot parameterize over their
```
Comment (Zimmi48) [inline doc/sphinx/language/cic.rst]: This is not specific enough apparently, should be:

>prevents inductive types declared in sections to be template-polymorphic on section universes

or something along those lines.

File: doc/sphinx/language/cic.rst (hunk 7 above)
Comment (Zimmi48) [reply doc/sphinx/language/cic.rst]: OK so now that `Print Assumptions` works, it should be mentioned in this description. Also, the flag is already deprecated, so it should appear in the description with the `.. deprecated:: 8.10` directive. BTW, what will coqchk say if this flag was used? Something similar to `Print Assumptions`, I suppose?

File: toplevel/usage.ml [hunk 15]
```diff
@@ -82,6 +82,7 @@ let print_usage_common co command =
 \n  -sprop-cumulative      make sort SProp cumulative with the rest of the hierarchy\
 \n  -indices-matter        levels of indices (and nonuniform parameters) contribute to the level of inductives\
 \n  -type-in-type          disable universe consistency checking\
+\n  -no-template-check     disable checking of universes constraints on universes parameterizing template polymorphic inductive types\
```
Comment (Zimmi48) [inline toplevel/usage.ml]: Should probably be documented as well in the chapter on the Coq commands.

**Review by Zimmi48 — COMMENTED** [review]
> > This code should fail: the explitcit attribute shouldn't be silently ignored:
> > ```
> > Section Foo.
> >   Universe u.
> >   Context (A : Type@{u}).
> > 
> >   #[universes(template)] Inductive Bar :=
> >   | bar : A -> Bar.
> > 
> > End Foo.
> > ```
> 
> I don't think so, it might take other parameters for which template polymorphism would be fine.

Alright.

**Comment by mattam82** [comment]
This is not the end of the story yet, I have some more work to do implementing the refined version where ˋuniverses(template)ˋ fails when there’s no template universe polymorphism to apply (which makes complete sense indeed). Bear with me...

**Comment by mattam82** [comment]
> Please update the Compat/Coq810.v file (or whichever one it should be) to `Global Unset Template Check` (or whatever the option is called)

You mean `Coq89` right?

**Comment by mattam82** [comment]
Let's hope for a nice CI. I had to change a lot of things to actually make sense of universes(template): now we print on which universes an inductive definition actually is polymorphic, and we can't be polymorphic for nothing (e.g. if the universes in the universe context don't actually appear in the conclusion). This prevents the attribute being ignored, making a user think his definition was meaningfully polymorphic when it's actually not doing anything. There is a tricky issue with the fact that one can have singletons that get template polymorphic even if they have no parameters, as long as at least one universe they introduce appears in its conclusion type, this is preserved: `#[universes(template)] Inductive foo := C.` gives foo the `Prop` sort which in this case means that foo can actually live in Prop or Type for any `i`. It's debatable why we want singletons like this to be template polymorphic (which will mess with extraction) while they could just be in `Prop` and get erased, but #6274 went into that direction of distinguishing the two so I followed it here.

This resulted in removing a lot of useless attributes in the stdlib. I also modified some files to use template-polymorphism where it seemed natural to keep it, e.g. micromegas' PExpr and Pol, FSets trees (although by the time we use functors template polymorphism is lost), and some generic definitions in ssr (mainly phantom types, although again they could certainly be left in Prop).

One remaining issue is that I don't know how to test the `Unset Template Check` flag which is not supported by the checker. Do we have a story for that?

**Comment by mattam82** [comment]
Oh and all contribs where we blindly added the attribute whereas things were actually not needing template polymorphism are going to fail...

**Comment by mattam82** [comment]
Well, that’s a relief, I will fix those tomorrow along with surely more minor things I missed. Given the non-trivial size of the fix in the end, it might be good to make an rc or last beta before the final.

**Comment by SkySkimmer** [comment]
>One remaining issue is that I don't know how to test the Unset Template Check flag which is not supported by the checker. Do we have a story for that?

Make the checker support it? We're going in the direction of having the checker understand local typing_flags in #10291 already.

**Comment by mattam82** [comment]
There we have it. I don’t think we should make the checker support that, it’s only meant as a transitional option for migration and not here to stay. Probably this choice should be documented though, I’ll add that along with doc on the changes of printing and the semantics of the template attribute being more strict. It’s kind of reassuring to see that not that much code relies on inductives defined in sections to be template polymorphic. In many cases I guess the inductives can not be usefully polymorphic in the end as soon as one uses constants or other things that make indirect references to the parameter universes, due to the highly syntactic nature of the criterion.

**Comment by mattam82** [comment]
I rebased and cleaned up everything, and the doc and changelog's have been updated. I think it's ready now. In the end not too many overlays which is nice!

File: kernel/indTyping.ml (hunk 11 above)
Comment (mattam82) [reply kernel/indTyping.ml]: You’re right I didn’t catch that one

**Comment by mattam82** [comment]
Regarding @SkySkimmer's comment, this should now be now fixed in #10616 I'd like to get this one merged first as it's already quite big.

**Comment by vbgl** [comment]
Thank you all for working on this issue.

Matthieu, would you mind opening PRs corresponding to the overlays? Also, the patch for VST seems backward compatible; is it?

Who should be the assignee?

**Comment by mattam82** [comment]
Yep, the VST one is backwards compatible, PRs open now. Please don't hesitate to take over and finis this, I'm won't be available anymore this week.

**Comment by mattam82** [comment]
I guess @SkySkimmer or @ppedrot ?

**Comment by Zimmi48** [comment]
Sorry for thinking about this only now but I was triggered by the overlay on aac-tactic which is not backward compatible because it uses `-no-template-check`, whereas it would if it used `-set "Template Check=false"`. Wouldn't it make sense given that the option is already deprecated and the command-line flag is not there to stay either to *not* introduce a new command-line flag but recommend the use of the new generic `-set` flag instead? Of course, I don't want to be a pain in the neck with such nitpicking so feel free to ignore this comment.

**Comment by ppedrot** [comment]
@mattam82 I'd prefer not to assign, expect maybe only for merging. I still have no clue about template polymorphism...

**Comment by mattam82** [comment]
Maybe @herbelin then?

**Comment by vbgl** [comment]
Gaëtan, do you think you’ll be able to review this PR? Thanks.

In order to correctly backport these changes, I would appreciate to get confirmation that the new `Record.check_anonymous_type` function is correctly implemented as follows. Thanks.

~~~
let check_anonymous_type ind =
  match ind with
  | { CAst.v = CSort (Glob_term.GType []) } -> true
  | _ -> false
~~~

File: vernac/record.ml [hunk 16]
```diff
@@ -111,15 +122,15 @@ let typecheck_params_and_fields finite def poly pl ps records =
...
               Loc.raise ?loc (Stream.Error "pattern with quote not allowed in record parameters")) ps
-  in 
+  in
   let sigma, (impls_env, ((env1,newps), imps)) = interp_context_evars ~program_mode:false env0 sigma ps in
   let fold (sigma, template) (_, t, _, _) = match t with
-    | Some t -> 
+    | Some t ->
        let env = EConstr.push_rel_context newps env0 in
        let poly =
          match t with
```
Comment (SkySkimmer) [inline vernac/record.ml]: Just below this line (github doesn't let me comment on the right line) we check that `t` is a bare `Type`, this should be reusing `check_anonymous_type` (or perhaps is redundant with the new use site of `check_anonymous_type`)

**Comment by SkySkimmer** [comment]
The commit history looks a bit messy, is it going to be cleaned up or should I just review the PR as 1 big change?

>In order to correctly backport these changes, I would appreciate to get confirmation that the new Record.check_anonymous_type function is correctly implemented as follows. Thanks.

Looks fine, as I said in the other comment it should be doing the same thing that we already do on https://github.com/coq/coq/blob/09002e0c20cf4da9cbb1e27146ae1fdd205b304a/vernac/record.ml#L126 ie https://github.com/coq/coq/blob/v8.10/vernac/record.ml#L127

**Comment by mattam82** [comment]
I think we should just squash everything, I tried to separate the commits by files touched but that won’t compile

**Comment by mattam82** [comment]
Indeed we should factorize record/comInd more

**Comment by vbgl** [comment]
Matthieu, just to clarify your last comment: do you intend to do that factorization as part of this PR?

**Comment by mattam82** [comment]
No !

**Comment by mattam82** [comment]
It would make rebasing even worse I guess

**Comment by vbgl** [comment]
Then shall we merge this as is? Gaëtan, do you approve these changes?

**Comment by vbgl** [comment]
There are now conflicts, as #10291 has been merged. This will make the port to the 8.10 branch a bit more tricky.

Shall this PR be merged?

**Comment by mattam82** [comment]
I can give it a go this morning (for sure).

**Review by herbelin — COMMENTED** [review]
Not knowing exactly if some action is (still) expected from me, but considering that noone formally approved yet, I started to look at the PR.

I find it a bit a pity to have a new option for disabling template checking and to have template polymorphism not supported anymore in sections but, at the stage of understanding I am, my feeling is that the PR otherwise reaches its goal, namely to fix #9294 in a safe way, while at the same time making some steps towards eventually reducing template polymorphism to universe polymorphism. As such, it is mergeable.

Specifically about sections (late reaction, sorry):

> I tried many things to treat template-polymorphism in sections but nothing satisfactory can be done: to be really safe we would have to elaborate everything in sections with `Prop <= i` constraints and do global checks at discharge time if some universe we're parameterizing on has been constrained elsewhere

Thinking at this, my conclusion is that the names used in the type of the arguments of a template polymorphic inductive type are actually _binding_ names, even though we use global names to represent them (at the time when template polymorphism was introduced there were no universe variables, so there were simulated using global names). So, in a configuration like:
```
Section S.
Universe u.
Variable A : Type@{u}.
Inductive box (A:Type@{u}) := Box : A -> box.
Definition B := Set : Type@{u}.
End S.
```
The constraint on `u` generated by the definition `B` has no effect on `box`. Outside the section, `box` should be:
```
Inductive box (A:Type@{i}) : Type@{i} := Box : A -> box.
 ```
or even, to adopt the notational convention of universe polymorphism:
```
Inductive box@{i} (A:Type@{i}) : Type@{i} := Box : A -> box.
```
with `i` a binding variable. In particular, when `box` is applied to `T:Type@{v}`, the name `u` (here renamed `i`) is just instantiated as a standard binding variable to give type `Type@{v}`.

The only remaining effect of the global name `u` on template polymorphism is in case `box` is unapplied and the absence of an argument does not allow to infer an instance. In this case, it is the global `u` which is used as default instance, i.e. `box` gets instantiated as `box@{u}` (otherwise said, the binding variable `u` gets instantiated by the eponym global variable `u`).

Otherwise said, I don't see what could be wrong in simply keeping the code discharging template polymorphic inductive types as it is. What is important is the local graph of an inductive type, i.e. when `u` is used inside the definition of the type, since then, this internal `u` is bound by the `u` of the type of the argument. Occurrences of `u` which are used outside the inductive definition, as the one in the body of `B`, are bound at the place of `Universe u`, not at the `box (A:Type@{u})` place. These are two distinct binders using the same binding name.

**Comment by mattam82** [comment]
I agree the universes should be binders in the case of template-polymorphism, just as in universe polymorphism. The problem is precisely when you interleave definitions depending on the same universes and the inductive (so when your definition B is above the inductive and used in its declaration). By a kind of miracle one could do that in the previous implementation (there's an example in ring of an abbreviation `Def cpol := Pol C` using that, perhaps unknowingly). To be correct one should keep track of the use of the section-introduced universe variables across definitions, to see if they're ever bounded from below, which is entirely silent in template-polymorphism mode. Also, I don't want to introduce even more confusion by interpreting global universes as binding variables rather than floating ones in general. Let's just have proper universe variables!

File: test-suite/failure/Template.v [hunk 17]
```diff
@@ -0,0 +1,32 @@
+(*
+Module TestUnsetTemplateCheck.
```
[the remark this answers is not in the document]
Comment (mattam82) [reply test-suite/failure/Template.v]: Yes

File: test-suite/success/Template.v [hunk 18]
```diff
@@ -46,3 +46,112 @@ Module No.
...
+
+Module ExplicitTemplate.
+  #[universes(template)]
+  Inductive identity@{i} (A : Type@{i}) (a : A) : A -> Type@{i} := id_refl : identity A a a.
+
+  (* Weird intraction of template polymorphism and inductives
+     which naturally fall in Prop: this one is template polymorphic but not on i:
+     it just lives in any universe *)
+  Check (identity Type nat nat : Prop).
+End ExplicitTemplate.
```
[the remark this answers is not in the document]
Comment (mattam82) [reply test-suite/success/Template.v]: I guess you mean we could require the parameters to be all anonymous to prevent sharing? I'm pretty sure a syntactic check like this would not be enough, one can use tactics in terms to get access to the parameters in constructor types.

**Comment by mattam82** [comment]
> Maybe this is the same feeling as @SkySkimmer, I find it a bit strange that whether universes have initial constraints >= Prop or >= Set is in the global environment vs being a property at least of the current declaration being treated, if not a property of each universe under consideration.

It could be indeed, it was just simpler to implement it there. You're right it makes more sense at the declaration level or the universe one. 

> For instance, maybe the idea is odd and not easy to implement, but would it make sense that the lower bound is just enforced as an explicit constraint in the constraints part of a Univ.UContext.t? In which case, the enforce_constraint in UGraph.add_universe would just be probably moved somewhere in uState.ml to add the constraint at the same time the universe is added.

Yes, but again that's a bigger change.

> Also, does it prevent something to ensure that some u is >=Prop or would it be equivalent to declare u w/o any constraints.

It prevents having universes lower than Prop, if you don't add any constraints one can declare i < Prop.

**Comment by herbelin** [comment]
> ... so when your definition B is above the inductive and used in its declaration ...

Ah, indeed, well spotted! This means that #9294 could (a priori) be exploited vernac side even before the introduction of universe polymorphism :(
```
Section Foo.
Context (A : Type).
Definition CastSet (A:Type) := Set : ltac:(let ty := type of A in exact ty).
Inductive Foo := foo : CastSet A -> Foo.
End Foo.
Check Foo True : Prop.
```
which can then be continued as in [9294](https://github.com/coq/coq/issues/9294#issuecomment-450860504). (It remains to find an equivalent to `ltac:(let ty := type of A in exact ty)` in 8.4 to get there a vernac-side critical bug.)

**Comment by herbelin** [comment]
> It prevents having universes lower than `Prop`, if you don't add any constraints one can declare `i < Prop`.

Am I correct that a cheaper alternative (in terms of number of edges in the graph) could be to ensure that no constraints `i<=Prop` or `i<Prop` is added.

Otherwise, yes, other suggestions would be big changes.

**Comment by herbelin** [comment]
> Also, I don't want to introduce even more confusion by interpreting global universes as binding variables rather than floating ones in general. Let's just have proper universe variables!

I agree.

**Comment by herbelin** [comment]
Another version, using `ltac:` and `type of` to force the universe level to be shared, but without using sections (nor `@{i}`):
```
Inductive Foo A (S:= fun _ => Set : ltac:(let ty := type of A in exact ty))
  := foo : S A -> Foo A.
Check Foo True : Prop.
```
Ruled out by the `unbounded_from_below` test of the PR.

**Comment by mattam82** [comment]
Yep, I’ll add those to the test-suite while I’m at it

File: vernac/comInductive.ml [hunk 19]
```diff
@@ -345,25 +363,46 @@ let restrict_inductive_universes sigma ctx_params arities constructors =
...
+  then user_err (str "Inductives with uniform parameters may not have attached notations.");
+
+  let indnames = List.map (fun ind -> ind.ind_name) indl in
+  let sigma, env_params, infos =
+    interp_params env0 udecl uparamsl paramsl
+  in
 
   (* Interpret the arities *)
-  let sigma, arities = List.fold_left_map (fun sigma -> interp_ind_arity env_params sigma) sigma indl in
+  let arities = List.map (intern_ind_arity env_params sigma) indl in
```
Comment (herbelin) [inline vernac/comInductive.ml]: More remark: this could be moved to the `else` branch of `not poly && is_template` per symmetry and to avoid `arities` to be computed twice in the `then` branch.

**Comment by mattam82** [comment]
I rebased, squashed everything and added Hugo's tests to the test-suite file. Should be ready now.

File: vernac/comInductive.ml (hunk 19 above)
Comment (mattam82) [reply vernac/comInductive.ml]: That must be old code you looked at, now we only intern_arity twice in template-polymorphism mode (because the params and sigma must be refreshed in that case).

**Comment by herbelin** [comment]
> Should an entry also be added in dev/doc/critical-bugs?

Here is a first proposal for addition:
```
  component: template polymorphism                                                                                                 
  summary: template polymorphism not collecting side constrains on the universe level of a parameter; this is a general form of the previous issue about template polymorphism exploiting other ways to generate untracked constraints                                
  introduced: morally at the introduction of template polymorphism, 23 May 2006, 9c2d70b, r8845, Herbelin                          
  impacted released versions: at least V8.4-V8.4pl6, V8.5-V8.5pl3, V8.6-V8.6pl2, V8.7.0-V8.7.1, V8.8.0-V8.8.1, V8.9.0-V8.9.1, in theory also V8.1-V8.1pl4, V8.2-V8.2pl2, V8.3-V8.3pl2 but not exploit found there yet (an exploit using a plugin to force sharing of universe level is in principle possible though)                                                                                   
  impacted development branches: all from 8.4 to 8.9 at the time of writing and suspectingly also all from 8.1 to 8.4 if a way to create untracked constraints can be found
  impacted coqchk versions: a priori all (tested with V8.4 and V8.9 which accept the exploit)                                      
  fixed in: soon in master and V8.10.0 (PR #9918, Aug 2019, Dénès and Sozeau)                                                                
  found by: Gilbert using explicit sharing of universes, exploit found for 8.5-8.9 by Pédrot, other variants generating sharing using sections, or using ltac tricks by Sozeau, exploit in 8.4 by Herbelin and Jason Gross by adding new tricks to Sozeau's variants 
  exploit: test-suite/failure/Template.v                                                                                           
  GH issue number: #9294                                                                                                           
  risk: moderate risk to be activated by chance         
```
About the risk: Gaëtan, how did you find it? I suppose this was by investigations of the semantics of template polymorphism? How would you qualify the risk?

**Comment by SkySkimmer** [comment]
I don't remember how I found it.
>How would you qualify the risk?

I don't expect any developments to use the bug. OTOH if someone has to deal with malicious proofs they should be very worried, it seems tricky to notice.

**Comment by ppedrot** [comment]
@herbelin's criticality entry looks good to me. Anyways, it would be good for this patch to go in as fast as possible. We can push the CEV atop of this branch ourselves, and if @SkySkimmer doesn't wish to assign I can do so instead. This PR has already been reviewed separately by several persons IIUC, so that there is little left before merging.

**Comment by herbelin** [comment]
Sure, merging is ok to me.

**Review by ppedrot — APPROVED** [review]
The changes to the kernel seem OK to me w.r.t. the high-level description of the issue.

**Comment by ppedrot** [comment]
OK, critical bug entry added. @coq/core Last round to complain, will merge tomorrow if no input by then.
