### PR TITLE
Locating error again in atomic tactics (fixes #12152)

### LINKED ISSUE #12152: Regression in locating errors at the level of atomic tactics
#### Description of the problem

```
Goal True.
intro H; auto.
^^^^^^^^^^^^^^
Error: No product even after head-reduction.
```
Formerly, `intro H` was underlined.

#### Coq Version

Since 8.10

In 8.10, this is related to #9142 and `Set Ltac Backtrace.` does recover the location. However, I believe that we always want the most precise location, even in the absence of backtrace.

In 8.11, `Set Ltac Backtrace.` does not restore the location. I don't know why.

Even if present since one release and a half, I believe that it is worth a blocker priority since this is a basic feature for daily work. Sorry for not submitting before, it is only now that I took some time to circumscribe the issue.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix 

We force setting location of atomic tactics if the error they possibly produce is not located. (Note that since we don't systematically have the call trace anymore, we explicitly add a test for failure in the `TacAlias` case.)

Fixes / closes #12152

- [x] Added / updated test-suite (not easy to test because `Fail` doesn't display the location)
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
A priori OK, but can we get a bench to see if this has effects on performance?

**Comment by Zimmi48** [comment]
Some output tests need to be adjusted.

**Comment by herbelin** [comment]
> A priori OK, but can we get a bench to see if this has effects on performance?

I'm confused, it seems my password for pendulum is not recognized. Don't know what to do.

What should we done if there is a slowdown?

> Some output tests need to be adjusted.

I had made a redundant change in the PR. Should not be ok.

**Comment by ppedrot** [comment]
> I'm confused, it seems my password for pendulum is not recognized. Don't know what to do.

Weird. I can definitely connect myself.

> What should we done if there is a slowdown?

I guess that trying to push the location down into the functions raising the underlying exception could be tried, if it's not too invasive.

File: plugins/ltac/tacinterp.ml [hunk 1]
```diff
@@ -162,17 +162,26 @@ let catching_error call_trace fail (e, info) =
...
   with e when CErrors.noncritical e ->
     let e = Exninfo.capture e in
+    let e = locate_if_not_already ?loc e in
     catching_error call_trace Exninfo.iraise e
 
-let wrap_error tac k =
-  if is_traced () then Proofview.tclORELSE tac k else tac
+let wrap_error ?loc tac k =
+  if is_traced () then Proofview.tclORELSE tac k
+  else Proofview.tclORELSE tac (fun exn ->
```
Comment (ppedrot) [inline plugins/ltac/tacinterp.ml:179]: I think that you can use `Proofview.plus` instead, it should be more efficient and semantically equivalent.

**Comment by herbelin** [comment]
> Weird. I can definitely connect myself.

I reset the password and could start a job.

**Comment by herbelin** [comment]
I cannot reproduce the failures. CI said that
```
==========> TESTING output-modulo-time/ltacprof.v <==========
-constructor ---------------------------   %   %       1    
-constructor ---------------------------   %   %       1    
 sleep ---------------------------------   %   %       0    
 sleep ---------------------------------   %   %       0    
 sleep' --------------------------------   %   %       0    
==========> FAILURE <==========
    output-modulo-time/ltacprof.v...Error! (unexpected output)

logs//output-modulo-time/ltacprof_abstract.v.log
==========> TESTING output-modulo-time/ltacprof_abstract.v <==========
 
 abstract (sleep; constructor) ---------   % %       1    
 abstract (sleep; constructor) ---------   % %       1    
-constructor -------------------------   %   %       1    
-constructor ---------------------------   %   %       1    
 sleep -------------------------------   %   %       0    
 sleep ---------------------------------   %   %       0    
 sleep' ------------------------------   %   %       0    
==========> FAILURE <==========
    output-modulo-time/ltacprof_abstract.v...Error! (unexpected output)
```
but the two pairs of missing `constructor` are there when I try locally. Is this a cutoff threshold issue? @jasongross, do you see the reasons why the calls to `constructor` could be missing?

**Review by JasonGross — DISMISSED** [review]
Can we get an output test-suite case to make sure we don't regress on this again?

**Comment by JasonGross** [comment]
@herbelin It should not be a cutoff issue, given that the file is using `("-profile-ltac-cutoff" "0.0")`  I'm not sure what's going on...

**Comment by JasonGross** [comment]
I guess if the number of successes of tactics changes, that might change things....  Does it change anything if you rebase on https://github.com/coq/coq/pull/12197 ?

**Comment by herbelin** [comment]
> I cannot reproduce the failures.

I found the explanation. I had used dune a few days ago which had created a `_build` directory. Then I used make. But when there is a `_build` directory, the test-suite makefile takes the coqc in there rather than the one in `bin`. So I was test-suiting with the wrong coqc.

So, I could reproduce and tried another fix (I'm not sure I understand exactly how the trace should be handled in general though).

**Comment by herbelin** [comment]
> Can we get an output test-suite case to make sure we don't regress on this again?

I wish we could. I believe it would require a different kind of tests. For instance, `Fail` does not display locations and I don't know what would be the best strategy (to modify `Fail` so that it can add locations? to re-add failing tests?).

**Comment by herbelin** [comment]
I'm not expert in interpreting benchmarks. The result is [here](https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/929/console).

**Comment by JasonGross** [comment]
> > Can we get an output test-suite case to make sure we don't regress on this again?
> 
> I wish we could. I believe it would require a different kind of tests. For instance, `Fail` does not display locations and I don't know what would be the best strategy (to modify `Fail` so that it can add locations? to re-add failing tests?).

Maybe add an `output-failure` directory of files which are meant to fail, where we check the output (including error messages), but consider failure of the file to compile to be not fatal?

File: plugins/ltac/tacinterp.ml [hunk 2]
```diff
@@ -162,17 +162,26 @@ let catching_error call_trace fail (e, info) =
...
   try f x
   with e when CErrors.noncritical e ->
     let e = Exninfo.capture e in
+    let e = locate_if_not_already ?loc e in
     catching_error call_trace Exninfo.iraise e
 
-let wrap_error tac k =
-  if is_traced () then Proofview.tclORELSE tac k else tac
+let wrap_error ?loc tac k =
+  if is_traced () then Proofview.tclORELSE tac k
```
Comment (ppedrot) [inline plugins/ltac/tacinterp.ml:178]: Actually I wonder why we use `tclORELSE` at all in this case. Apart from having an involved, slow implementation, it is also likely to change the semantics w.r.t. backtracking when tracing. While you're at it I think it'd be even better to change it into a `tclOR`, and even restrict the type of `k` to `exninfo -> exninfo`.

Comment (herbelin) [reply plugins/ltac/tacinterp.ml]: I moved the `tclORELSE` to a `tclERROR`. Changing the type of `k` would require more thinking and I'm also not fully sure of how you would like it to be done exactly. Don't hesitate to push a proposal to the branch.

**Comment by herbelin** [comment]
> Maybe add an output-failure directory of files which are meant to fail, where we check the output (including error messages), but consider failure of the file to compile to be not fatal?

Possibly, or offering a variant of `Fail` which reports the location.

I'm missing time and I don't think I can do it for this PR. Moreover it is easy to observe this particular regression (even if it took me weeks to decide to make a diagnosis and to open an issue).

**Comment by JasonGross** [comment]
@herbelin Based on the `Makefile`, output tests are not required to succeed, so you should just be able to drop a test in test-suite/output/` and have it work.

File: plugins/ltac/tacinterp.ml (hunk 1 above)
Comment (herbelin) [reply plugins/ltac/tacinterp.ml]: @ppedrot: Using `tclOR` changes the backtrace (it duplicated some calls, e.g. in test `output/Errors.v`). I'm afraid that I have to renounce to this change, at least at the current time. If you think it is worth further investigations, this can probably be done in another PR.

**Comment by herbelin** [comment]
> @herbelin Based on the Makefile, output tests are not required to succeed, so you should just be able to drop a test in test-suite/output/` and have it work.

Indeed. I thus added a few tests. Don't know how the linter will react because the output needs a trailing newline...

This PR is now relatively minimal in fixing the location. So I believe it can go to 8.11.2.

It ready on my side up to the need for some final squashing.

**Comment by ppedrot** [comment]
CI still seems broken...

**Comment by herbelin** [comment]
> CI still seems broken...

My bad. I forgot to commit the changes.

**Comment by Zimmi48** [comment]
@ppedrot Ready to merge?
