### PR TITLE
Fix has_dependent_elim to handle postponed eta

### LINKED ISSUE #21788: destruct does not play well with primitive records with sprop fields
### Description of the problem

cc @SkySkimmer 

### Small Rocq / Coq file to reproduce the bug

```coq
Inductive sTrue : SProp := stt.
Set Primitive Projections.
Record foo := { bar : sTrue }.
Goal forall x y : foo, x = y.
destruct x, y; reflexivity.
Defined.
```

### Version of Rocq / Coq where this bug occurs

9.2.0

### Interface of Rocq / Coq where this bug occurs

_No response_

### Last version of Rocq / Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #21789
Fix #21788

### CODE REVIEW

File: kernel/cClosure.ml [hunk 1]
```diff
@@ -963,20 +951,13 @@ let has_valid_relevance u ind_relevance flds =
...
-      match has_eta with
-      | NoEta -> raise Not_found
-      | MaybeEta ->
-        let relevances = Array.map snd projs in
-        if not @@ has_valid_relevance u ind_relevance relevances
-        then raise Not_found
-      | AlwaysEta -> ()
-    in
+  | None -> assert false
+  | Some (projs, _) ->
```
Comment (yannl35133) [inline kernel/cClosure.ml:960]: That was the only use case for `has_eta` as returned by `inductive_make_projections`.

**Review by yannl35133 — APPROVED** [review]
My comment can be fixed in a later PR; I think this fix should make it into 9.2

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I'm merging already so that this can be backported quickly. @coqbot merge now
