### PR TITLE
Fix variance inference for section universes

### LINKED ISSUE #15916: Inconsistency (incorrect inferred variance) with cumulative inductives and section universes
~~~coq
Set Universe Polymorphism. Set Printing Universes.

Section S.
  Universe u.

  Cumulative Inductive I1 := C1 (_:Type@{u}).

  Cumulative Inductive I2 := C2 (_:I1).
End S.

(* !!! should be covariant !!! *)
Cumulative Inductive I3@{*u} := C3 (_:I2@{u}).
(* alternative test without the variance syntax: *)
Check C3@{Type} _ : I3@{Set}. (* should fail but doesn't *)
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #15916

### CODE REVIEW

File: kernel/inferCumulativity.ml [hunk 1]
```diff
@@ -259,23 +259,20 @@ let infer_arity_constructor is_arity env variances arcn =
...
-open Entries
-
-let infer_inductive_core env univs entries =
+let infer_inductive_core ~env_params ~env_ar_par ~arities ~ctors univs =
   let variances = Inf.start univs in
-  let variances = List.fold_left (fun variances entry ->
-      let variances = infer_arity_constructor true
-          env variances entry.mind_entry_arity
-      in
-      List.fold_left (infer_arity_constructor false env)
```
Comment (SkySkimmer) [inline kernel/inferCumulativity.ml:270]: We used to run the inference for constructors in an env with the arities as unbound rels, I don't think it caused issues ut I fixed it regardless.

**Comment by ppedrot** [comment]
I think that this fix is a bit ugly. It's spreading redundant data in several parts of the code. I'm fine with merging it but I also believe that setting section universes to be invariant, period, would have been much simpler and cleaner.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
