### PR TITLE
[impargs] use clos_whd_all (by need, rather than by name)

### LINKED ISSUE #10751: Valid statement cannot be Admitted or Qed
The proof of rcomputation in the code below fails to pass Qed.
Actually, the statement itself, although accepted by Theorem, cannot be Admitted.

Preliminary debugging by Enrico suggests that this is due to implicit arguments : uncommenting the 'Unset Implicit Arguments' solves the problem.

You need the library at https://gitlab.inria.fr/amahboub/approx-models to compile that file.
(this public version on git does not move for now ; in case it would, commit e841ba45 from July 1st, 2019, is the one to select) 

Coq 8.9.1

Can't find how to attach a file to this report... I've put it there:
 http://perso.ens-lyon.fr/damien.pous/bug.v

### PR DESCRIPTION
**Pull request by gares**
Fix #10751

### CODE REVIEW

**Comment by ejgallego** [comment]
IMHO we should add a test-case for this.

File: interp/impargs.ml [hunk 1]
```diff
@@ -22,6 +22,11 @@ open EConstr
 open Reductionops
 open Constrexpr
 
+let whd_all env sigma t = t
```
Comment (ppedrot) [inline interp/impargs.ml:25]: Can't you use `Reductionops.clos_whd_flags`?

Comment (gares) [reply interp/impargs.ml:25]: Thanks

**Comment by gares** [comment]
bench at https://gitlab.com/coq/coq/-/jobs/748053829

File: kernel/reduction.ml [hunk 2]
```diff
@@ -149,19 +149,19 @@ let whd_betaiotazeta env x =
     | Rel _ | Cast _ | LetIn _ | Case _ | Proj _ ->
         whd_val (create_clos_infos betaiotazeta env) (create_tab ()) (inject x)
 
-let whd_all env t =
```
Comment (ppedrot) [inline kernel/reduction.ml:152]: You can revert these changes (and the corresponding mli diff).

File: interp/impargs.ml [hunk 3]
```diff
@@ -22,6 +22,8 @@ open EConstr
 open Reductionops
 open Constrexpr
 
+let whd_all = Reductionops.clos_whd_flags CClosure.all
```
Comment (ppedrot) [inline interp/impargs.ml:25]: I think it's a fairly bad idea to shadow a global function with a local one that has a subtly different behaviour. It'd be better to use a different name to insist on the changes.

Comment (gares) [reply interp/impargs.ml:25]: OK, but I won't touch this again before bench terminates. I'll call it whd_all_call_by_need.

IMO the right fix would be to deprecated all call by name APIs in reductionops. Why would one call these?

Comment (ppedrot) [reply interp/impargs.ml:25]: > IMO the right fix would be to deprecated all call by name APIs

Nope, non-kernel reduction makes sense sometimes. Sometimes the overhead introduced by the change of representation is so high that the use of call-by-need is irrelevant.

Comment (gares) [reply interp/impargs.ml]: Then they should be called `whd_*_by_name`. I pretty sure nobody wanted to call a by name procedure here, imo the names are misleading. If there is a use case for these API, fine, but how many of their users are consciously choosing by name?

**Comment by gares** [comment]
```
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │      max resident mem [KB]      │    mem faults     │
│                             │                         │                                             │                                             │                                 │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD   PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                 coq-bignums │   57.59   58.71 -1.91 % │      159808905298      162512984833 -1.66 % │      215559640746      215530906216 +0.01 % │     471304     471312   -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   59.40   60.09 -1.15 % │      165928085765      165986401834 -0.04 % │      207962169780      207952678357 +0.00 % │     533452     533360   +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1516.55 1529.75 -0.86 % │     4222163235123     4259392899413 -0.87 % │     6508142089796     6508446494924 -0.00 % │     855916     855792   +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│            coq-math-classes │  189.60  190.93 -0.70 % │      529613311147      532421842653 -0.53 % │      700376686138      700313256340 +0.01 % │     504748     505184   -0.09 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                   coq-verdi │  121.52  122.21 -0.56 % │      335944135754      337305344737 -0.40 % │      413700940201      413544803027 +0.04 % │     574480     574512   -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                   coq-color │  617.56  620.54 -0.48 % │     1724557123494     1729952080611 -0.31 % │     2191325039852     2190628990937 +0.03 % │    1456548    1455168   +0.09 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4953.34 4976.72 -0.47 % │    13753458976935    13819688816174 -0.48 % │    23795216389250    23792385879261 +0.01 % │    2396176    2396388   -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │ 1054.96 1059.36 -0.42 % │     2934206416223     2946728191991 -0.42 % │     4629178835517     4629383528218 -0.00 % │    1070824    1071056   -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1258.36 1263.47 -0.40 % │     3504114533329     3514631293511 -0.30 % │     4899138177235     4898899284449 +0.00 % │     934604     934672   -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  643.87  646.07 -0.34 % │     1803929598926     1808654543063 -0.26 % │     2718845890532     2717469024416 +0.05 % │    2998004    2998072   -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  219.10  219.82 -0.33 % │      606973296181      609387956546 -0.40 % │     1004287976169     1004302272448 -0.00 % │    1087600    1087368   +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  140.08  140.51 -0.31 % │      390040980871      390507183039 -0.12 % │      503840192297      503699593928 +0.03 % │     564840     561436   +0.61 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1261.94 1265.60 -0.29 % │     3513266196550     3521037104579 -0.22 % │     4950712900679     4946742320079 +0.08 % │    1171732    1219016   -3.88 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                coq-compcert │  664.61  666.49 -0.28 % │     1851363136283     1856968322349 -0.30 % │     2556369176714     2555996371759 +0.01 % │    1131136    1131296   -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1069.64 1071.96 -0.22 % │     2978072533409     2984864674021 -0.23 % │     4750143377289     4750173892180 -0.00 % │     988412     991548   -0.32 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  105.87  106.08 -0.20 % │      301745102566      302451692002 -0.23 % │      401786146900      401514828033 +0.07 % │     487624     487332   +0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                coq-rewriter │  607.06  608.26 -0.20 % │     1686283066764     1688556986767 -0.13 % │     2584205487943     2583990080517 +0.01 % │     990584     989564   +0.10 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                   coq-flocq │  160.76  161.02 -0.16 % │      445695522135      447509106439 -0.41 % │      553526272428      553469462319 +0.01 % │     822256     822104   +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                coq-coqprime │   80.76   80.86 -0.12 % │      222642829846      222563025110 +0.04 % │      310896182644      310739762925 +0.05 % │     768564     768388   +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                    coq-hott │  315.10  315.44 -0.11 % │      854168745725      856520639849 -0.27 % │     1377130495905     1376033295544 +0.08 % │     635860     636020   -0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                         coq │  543.63  543.97 -0.06 % │     1519301942889     1519614544573 -0.02 % │     2075697981114     2075656062471 +0.00 % │     594064     592344   +0.29 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   69.87   69.91 -0.06 % │      191133494127      191427410356 -0.15 % │      245303855711      245284144574 +0.01 % │     587216     586952   +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  172.48  172.55 -0.04 % │      480249628303      479969254134 +0.06 % │      677711724539      677592277503 +0.02 % │     690316     691712   -0.20 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  160.62  160.55 +0.04 % │      446270762708      446140711053 +0.03 % │      618943045998      619105154304 -0.03 % │     729684     736736   -0.96 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  291.47  291.30 +0.06 % │      811059297133      810149358250 +0.11 % │     1249229168927     1249222659582 +0.00 % │     825900     825700   +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   48.08   47.99 +0.19 % │      133124944663      133085140738 +0.03 % │      183818932330      183771053631 +0.03 % │     486336     486324   +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1477.36 1474.03 +0.23 % │     4118217732532     4107719348885 +0.26 % │     6222342101744     6222312012900 +0.00 % │    1189124    1147756   +3.60 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  383.47  381.66 +0.47 % │     1078829871068     1072541540715 +0.59 % │     1843742796708     1837089164281 +0.36 % │    3508904    3508868   +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2528.84 2515.87 +0.52 % │     7049725742997     7014574862428 +0.50 % │    11448809261373    11447089358528 +0.02 % │     775024     774984   +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   50.90   50.58 +0.63 % │      138428030230      138410673009 +0.01 % │      176425245589      176310590181 +0.07 % │     521580     521664   -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4058.53 3995.81 +1.57 % │    11295331507877    11113803883219 +1.63 % │    21641682617052    21164304802746 +2.26 % │    3479300    1113564 +212.45 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────┼───────────────────┤
│  coq-performance-tests-lite │  553.09  544.50 +1.58 % │     1543600371135     1522438137906 +1.39 % │     2795479077683     2794696521130 +0.03 % │     747404     747368   +0.00 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────┴───────────────────┘
```

**Comment by gares** [comment]
This should be ready for a last round of review and a merge.

**Comment by ppedrot** [comment]
@gares Ouch. Note that the way you wrote it, there is an additional difference between kernel and pretyper reduction, namely the former disregards the opacity status of constants for δ-reduction. You have to pass it explicitly inside the flags, but unfortunately the Reductionops API doesn't let you that. (I've been wanting to export it for a long time already but found it to be a bit artificial in a single PR, while non-related in another one...)

**Comment by gares** [comment]
How do you find which files got slower? I thought there was a per file time diff in the logs, but I can't find it

**Comment by ppedrot** [comment]
@gares You have to download the bench artifact and call the `coqbench-display` script from the coqbench repository.

**Comment by gares** [comment]
https://coq.gitlab.io/-/coq/-/jobs/748058922/artifacts/_bench/html/coq-unimath/UniMath/SyntheticHomotopyTheory/Circle2.v.html

**Comment by gares** [comment]
With this change the problematic file passes with no visible performance regression https://github.com/UniMath/UniMath/pull/1329

**Comment by gares** [comment]
Also looking at unimath there seem to be some room for an attribute `#[implicits(clear)]` since they repeatedly define a constant c and immediately `Arguments c : clear implicits` which seems a clumsy way of turning off temporarily impargs.

**Comment by gares** [comment]
FTR: they build with -type-in-type which is a kind of dangerous way to do their kind of math, no?

**Comment by ppedrot** [comment]
> Does anyone know why?

They wanted resizing rules. I've told some UniMath devs that a global type-in-type flag was a footgun and that they should use a wrapper record to implement resizing rules, to no avail. Now it's too big to be changed.

**Comment by ppedrot** [comment]
(Funnily enough at the same time the UniMath library is defiant towards inductive types because, you know they could be *dangerous*, so better reimplement a kludgy, expensive contraption outside of the language to emulate them :shrug:)

**Comment by gares** [comment]
CI shows some breakage, e.g. the implicit arguments as computed before were different.
Now that we respect the opacity thing, is there any other different between clos_whd_all and whd_all? (not in the name for sure).

**Comment by gares** [comment]
CC @ppedrot @mattam82 @herbelin any idea of what could change in the behavior of whd_all (from pretyping) and whd_all (from kernel) w.r.t. implicit arguments? I mean, the notion of weak-head form is clear, how can the computation of implicit arguments change?

Example from the test suite ([bug_2830.v](https://github.com/coq/coq/blob/master/test-suite/bugs/closed/bug_2830.v)):
```
Definition derives {A} `{ageable A} (P Q:pred A) := forall a:A, P a -> Q a.
Arguments derives : default implicits.
```
seems to have `{ageable A}` not set the implicit, hence line 100 fails because is passes two `pred` to it, and no `_` for the type class.

**Comment by herbelin** [comment]
That's a bit mysterious. So, you are saying that with the PR, `About derives` does not give both `A` and `H` (the  class) implicit but gives only `A` implicit? What does the debugger says when observing `whd_all_by_need` at the time of computing the implicit positions?

**Comment by gares** [comment]
I did put a `About` before/after the `Arguments` and I get
```
derives : forall {A : Type} {H : ageable A}, pred A -> pred A -> Prop

derives is not universe polymorphic
Arguments derives {A}%type_scope {H} (_ _)%pred
derives is transparent
Expands to: Constant bug_2830.B.derives


derives : forall [A : Type] (H : ageable A), pred A -> pred A -> Prop

derives is not universe polymorphic
Arguments derives [A]%type_scope _ (_ _)%pred
derives is transparent
Expands to: Constant bug_2830.B.derives
```
but it makes kind of sense to me, since the computed implicits do not know that H is inferrable.
How was this OK before then
```
Notation "P '|--' Q" := (derives P Q) (at level 80, no associativity).
```

**Comment by herbelin** [comment]
Before (i.e. now), it says:
```
derives :
forall {A : Type@{derives.u0}} {H : ageable A} (_ : @pred A H) (_ : @pred A H), Prop
```
That is, there is a hidden occurrence of `H` in `pred` which itself is non-erasable... ah, actually no, it occurs in `pred` under an `age` which can erase it. So the difference seems that one of the `whd_all` unfolds `pred` and `age` and the other keeps one of them folded. I.e. the transparency state is either different or treated differently.

**Comment by gares** [comment]
Nice catch! There is a `Global Opaque pred.` so I guess I'm not honoring it, but I thought that is how you would pass it to the kernel:
```ocaml
  let tstate = Conv_oracle.get_transp_state @@ Environ.oracle env in
  let flags = CClosure.RedFlags.red_add_transparent CClosure.all tstate in
```
I guess it is not correct. Ideas?

**Comment by gares** [comment]
(also, the patch for unimath shows that the new code does honor `Opaque`... totally puzzled)

**Comment by ppedrot** [comment]
@gares by-name and by-need do *not* compute the same normal forms. Due to sharing, the former can reduce in places that are not the head of the term.

**Comment by gares** [comment]
If that term ends up in head position... I don't think it is the case here

**Comment by ppedrot** [comment]
Minimal example:
```
Class ageable := mkAgeable { }.

Definition pred {AG:ageable} := True.

Opaque pred.

Definition derives `{ageable} (P:pred) := True.
Arguments derives : default implicits.
About derives.
```
I am having a look right now to see what's the difference.

**Comment by gares** [comment]
Did you find the culprit?

**Comment by ppedrot** [comment]
I did make progress but unfortunately I don't remember :/

**Comment by herbelin** [comment]
I would classify this PR as an important fix/fine-tuning for implicit arguments...
- is the pending problem to understand how much call-by-need from call-by-name?
- wouldn't it be worth to write a proper call-by-name environment machine at some time?
- would using the cbv machine be an alternative?

**Comment by ppedrot** [comment]
This is a bug in the Reductionops variant, it seems that `pred #1` is unfolded to `True` with `whd_all` despite the constant being opaque.

**Comment by ppedrot** [comment]
More precisely, Reductionops does not take the opacity status into account for reduction, so it will gladly reduce `pred`. Thus the second commit of this PR actually makes things *worse* w.r.t. backwards compatibility.

**Comment by ppedrot** [comment]
I have reverted the second commit to see what was breaking before, since it is not very clear from the discussion.

**Comment by ppedrot** [comment]
So it turns out that the first commit (i.e. replacing whd_all by the kernel variant without trying to set the transparent state) correctly compiles the CI. The test-suite failure seems spurious, it's just missing a Time command somewhere. Was it because of the potential performance problem that we added the transparent state? It is unlikely to change anything because the kernel and reductionops behave the same, i.e. they don't care about it.

**Comment by gares** [comment]
So what is the conclusion here? Should we bench again?
I don't know what this complexity measure is... did you get how to fix the test-suite?

**Comment by ppedrot** [comment]
The test-suite fix was part of the reverted commit, i.e. it needs a `Time` command. I've pushed the fix alone, and I think we should squash the commits actually. We should probably bench again in any case.

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1334468045

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                             │                         │                                       │                                       │                          │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-coqprime │  342.02   349.73  -2.20 │   951475566299    972052723753  -2.12 │  1599428505579   1598953008209   0.03 │  855748   855796   -0.01 │   0    0    nan │
│                 coq-bignums │   57.12    57.69  -0.99 │   158980464490    159593189796  -0.38 │   208938350146    208883960541   0.03 │  464892   465008   -0.02 │   0    0    nan │
│                    coq-hott │  348.57   351.77  -0.91 │   967232770220    975949650083  -0.89 │  1410525832040   1410254318938   0.02 │  568488   568572   -0.01 │   0    0    nan │
│               coq-perennial │ 7040.67  7091.09  -0.71 │ 19596918928742  19734340152807  -0.70 │ 29189352722527  29183542228717   0.02 │ 3078668  3079324   -0.02 │   0    0    nan │
│            coq-math-classes │  180.44   181.62  -0.65 │   504233093406    507535092228  -0.65 │   653661020793    653659529113   0.00 │  482132   482056    0.02 │   0    0    nan │
│  coq-performance-tests-lite │ 1645.31  1655.88  -0.64 │  4592595897123   4619558983391  -0.58 │  7470019451030   7469851094132   0.00 │ 2079280  2079148    0.01 │   0    0    nan │
│      coq-mathcomp-ssreflect │   56.02    56.32  -0.53 │   154507808878    154575372364  -0.04 │   192054659021    191943187002   0.06 │  527340   528720   -0.26 │   0    0    nan │
│             coq-lambda-rust │ 1309.30  1315.48  -0.47 │  3641934839095   3658276114670  -0.45 │  5101917669831   5104879905828  -0.06 │ 1077396  1096240   -1.72 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1098.07  1102.89  -0.44 │  3053993656444   3070178611369  -0.53 │  4719568931623   4720015325672  -0.01 │  939772   904344    3.92 │   0    0    nan │
│                    coq-corn │ 1533.31  1539.65  -0.41 │  4269310157620   4288315673871  -0.44 │  6027604303542   6028584084086  -0.02 │  809788   809924   -0.02 │   0    0    nan │
│                coq-bedrock2 │  316.96   317.98  -0.32 │   880280835718    883039026578  -0.31 │  1514733377886   1514063476321   0.04 │  798180   798244   -0.01 │   0    0    nan │
│                  coq-stdlib │  424.03   425.38  -0.32 │  1186160196933   1188684615340  -0.21 │  1495704083705   1495246860234   0.03 │  595964   596264   -0.05 │   0    0    nan │
│              coq-coquelicot │   70.93    71.14  -0.30 │   194980662891    195093265545  -0.06 │   240643204595    239995138562   0.27 │  555808   555840   -0.01 │   0    0    nan │
│                  coq-geocoq │ 1378.93  1382.95  -0.29 │  3839827971729   3856491900936  -0.43 │  5489676152216   5489174517974   0.01 │ 1003864   988200    1.59 │   0    0    nan │
│            coq-fiat-parsers │  613.20   614.90  -0.28 │  1713034368672   1719577506756  -0.38 │  2548502053473   2547732018399   0.03 │ 3076092  3076076    0.00 │   0    0    nan │
│                   coq-verdi │  101.16   101.38  -0.22 │   279899839613    280278891036  -0.14 │   383232711729    382493419042   0.19 │  541940   542224   -0.05 │   0    0    nan │
│              coq-verdi-raft │ 1143.72  1146.01  -0.20 │  3184454724106   3191916706963  -0.23 │  4407824088883   4407651240643   0.00 │  900600   900456    0.02 │   0    0    nan │
│       coq-engine-bench-lite │  325.50   326.09  -0.18 │   916582375783    917972143637  -0.15 │  1655670800842   1656106063201  -0.03 │ 3506104  3506452   -0.01 │   0    0    nan │
│                    coq-core │  109.77   109.91  -0.13 │   304247864530    304133473355   0.04 │   457704825560    457944183394  -0.05 │  282644   282616    0.01 │   0    0    nan │
│             coq-fiat-crypto │ 5002.19  5008.22  -0.12 │ 13903756318804  13907186655973  -0.02 │ 23988540512198  23983416224088   0.02 │ 2229036  2228040    0.04 │   0    0    nan │
│       coq-mathcomp-solvable │  178.61   178.78  -0.10 │   496930598702    496845809058   0.02 │   683804925445    683751356161   0.01 │  687720   672804    2.22 │   0    0    nan │
│        coq-mathcomp-algebra │  145.29   145.26   0.02 │   404029998602    404001196160   0.01 │   509974994828    509805234491   0.03 │  555748   553164    0.47 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │  775.37   775.08   0.04 │  2158587056733   2159366500705  -0.04 │  3286677263791   3290168408010  -0.11 │ 1071484  1153884   -7.14 │   0    0    nan │
│                coq-rewriter │  703.21   702.91   0.04 │  1954413308080   1953566874134   0.04 │  2921251506321   2919205444314   0.07 │ 1071336  1071384   -0.00 │   0    0    nan │
│       coq-mathcomp-fingroup │   50.38    50.35   0.06 │   140223663891    140216572584   0.01 │   190369099990    190415371079  -0.02 │  479496   479576   -0.02 │   0    0    nan │
│                   coq-color │  503.44   503.09   0.07 │  1406086299248   1407587921567  -0.11 │  1714238950181   1712780400065   0.09 │ 1141964  1141456    0.04 │   0    0    nan │
│               coq-fourcolor │ 2637.78  2634.27   0.13 │  7344754379429   7340943655947   0.05 │ 12249250711874  12250178778179  -0.01 │  731072   731068    0.00 │   0    0    nan │
│          coq-mathcomp-field │  232.51   231.73   0.34 │   646587121843    644977422940   0.25 │   955624237626    955781052165  -0.02 │  663096   660768    0.35 │   0    0    nan │
│      coq-mathcomp-character │  158.28   157.74   0.34 │   439692676964    439549735453   0.03 │   598752948974    598729896154   0.00 │  731104   730892    0.03 │   0    0    nan │
│                 coq-coqutil │   60.54    60.27   0.45 │   167988338427    167680387922   0.18 │   215123150922    214740480089   0.18 │  598280   598056    0.04 │   0    0    nan │
│               coq-fiat-core │  111.96   111.23   0.66 │   317886770194    317587368118   0.09 │   414375011865    412813137212   0.38 │  480380   480300    0.02 │   0    0    nan │
│                 coq-unimath │ 4127.55  4049.71   1.92 │ 11485231788912  11268673587175   1.92 │ 21640869118814  21231767663563   1.93 │ 3040880  1123996  170.54 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
The unimath problem is very real. It's not a 2% spread around, it's concentrated in 5 (five!) lines.
```
html/coq-unimath/UniMath/SyntheticHomotopyTheory/Circle2.v.html:333 10.09 0.73 10.82 (1384%)
html/coq-unimath/UniMath/SyntheticHomotopyTheory/Circle2.v.html:358 14.10 0.83 14.93 (1699%)
html/coq-unimath/UniMath/SyntheticHomotopyTheory/Circle2.v.html:384 15.25 0.79 16.05 (1923%)
html/coq-unimath/UniMath/SyntheticHomotopyTheory/Circle2.v.html:362 15.30 0.78 16.08 (1957%)
html/coq-unimath/UniMath/SyntheticHomotopyTheory/Circle2.v.html:385 15.54 0.80 16.34 (1938%)
```
This is a revival of https://github.com/UniMath/UniMath/pull/1329 since we don't respect opacity anymore.

**Comment by gares** [comment]
I don't get it, isn't unimath turning off kernel sharing? If so, whd by the kernel or by reductionops is by name.

**Comment by gares** [comment]
Asif reductionops was respecting opacity, then I don't get why the reverted commit is a problem.

**Comment by ppedrot** [comment]
> isn't unimath turning off kernel sharing?

Probably.

>  if reductionops was respecting

No, that's not what I meant. The linked PR was introduced after this one, so I was referring to the effects on the previous state of this PR.

**Comment by gares** [comment]
We can propose another PR which removes the opaque from unimath and unsets/sets impargs around the context variable declaration.

**Comment by ppedrot** [comment]
This might also be related to #13435.

**Comment by ppedrot** [comment]
The term generated by reduction UniMath is really monstrous. This is just the weak head of `PathOver loop a a`.
 
Even with `Fast Name Printing`, generating the output takes several dozens of seconds, to which you need to add a similar duration to serialize the CoqIDE message. I have not managed to get the head of the term yet, since CoqIDE crashes trying to print it in the buffer. It does manage to get the serialized data but even the gargantuan size of the string is too much for GTK it seems.

**Comment by ppedrot** [comment]
Here is an alternative approach. We still use the kernel as before, but we do not even try to normalize the goal if it's not a product.

**Comment by ppedrot** [comment]
This fixes the unimath issue, and it shouldn't make the other users any slower when compared to the first commit. I guess we can have yet another bench to be sure?

**Comment by gares** [comment]
If it passes CI, I'm OK with this approach. But my understanding of the use for whd was that `f : C` for `C` not a prod could still get implicit arguments...

**Comment by gares** [comment]
Sorry, I should have looked at your code first. Are you saying the problem is just unwinding the machine?

**Comment by ppedrot** [comment]
> Sorry, I should have looked at your code first. Are you saying the problem is just unwinding the machine?

Yup. Head reducing is instantaneous, the costly phase is reconstruction. Since we don't do that in Reductionops, I suspect this is why argument computation is fast in the current master branch.

**Comment by gares** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1339135031

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-unimath │ 4430.39  4483.89  -1.19 │ 12347214446052  12495833145183  -1.19 │ 23402023711073  23436273664990  -0.15 │ 3265388  3285868  -0.62 │   0    0    nan │
│              coq-verdi-raft │ 1141.44  1147.49  -0.53 │  3177273524960   3191450759595  -0.44 │  4407975279728   4407452086813   0.01 │  900256   900480  -0.02 │   0    0    nan │
│                coq-coqprime │  343.85   345.61  -0.51 │   956263589712    959371807883  -0.32 │  1599524995261   1598928747566   0.04 │  855712   855636   0.01 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1096.97  1101.75  -0.43 │  3052369399073   3066651106627  -0.47 │  4720270255765   4720270596151  -0.00 │  939740   939872  -0.01 │   0    0    nan │
│       coq-mathcomp-fingroup │   50.23    50.44  -0.42 │   139785867398    140005270723  -0.16 │   190476294650    190467397254   0.00 │  479324   479532  -0.04 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │  773.97   776.97  -0.39 │  2153627839407   2164363683009  -0.50 │  3286371265132   3288094127911  -0.05 │ 1071488  1071656  -0.02 │   0    0    nan │
│                 coq-bignums │   57.00    57.22  -0.38 │   159085088922    158851731936   0.15 │   209050840022    208983440824   0.03 │  464764   464868  -0.02 │   0    0    nan │
│                coq-rewriter │  701.89   704.08  -0.31 │  1950221002496   1959117982834  -0.45 │  2923379699551   2919949823615   0.12 │ 1108984  1071456   3.50 │   0    0    nan │
│                    coq-corn │ 1531.60  1535.93  -0.28 │  4267849223468   4279278386070  -0.27 │  6027908812385   6028691668689  -0.01 │  809796   810012  -0.03 │   0    0    nan │
│               coq-fourcolor │ 2623.92  2630.97  -0.27 │  7308406533256   7322802840264  -0.20 │ 12250582485188  12249574795326   0.01 │  730920   730920   0.00 │   0    0    nan │
│               coq-fiat-core │  111.16   111.40  -0.22 │   317912804318    317514495930   0.13 │   414409418212    412955952492   0.35 │  480424   480264   0.03 │   0    0    nan │
│       coq-mathcomp-solvable │  178.00   178.36  -0.20 │   495191870014    496050045654  -0.17 │   683853652711    683890119056  -0.01 │  693028   672788   3.01 │   0    0    nan │
│          coq-mathcomp-field │  231.30   231.74  -0.19 │   643927509777    644943107799  -0.16 │   955935338804    955908411437   0.00 │  662684   662416   0.04 │   0    0    nan │
│        coq-mathcomp-algebra │  147.34   147.57  -0.16 │   410843606578    411038680389  -0.05 │   519711452772    519590112373   0.02 │  554844   553392   0.26 │   0    0    nan │
│            coq-math-classes │  181.09   181.31  -0.12 │   505097657251    506282532259  -0.23 │   653793821288    653784702466   0.00 │  482048   482224  -0.04 │   0    0    nan │
│                   coq-color │  503.24   503.70  -0.09 │  1406378126002   1405096829915   0.09 │  1714362019180   1712667853633   0.10 │ 1142676  1142468   0.02 │   0    0    nan │
│                    coq-core │  109.77   109.87  -0.09 │   304368390497    304399760033  -0.01 │   457867667874    457890373048  -0.00 │  317608   317676  -0.02 │   0    0    nan │
│                   coq-verdi │  101.22   101.25  -0.03 │   280013747715    279622726927   0.14 │   383269159586    382654340392   0.16 │  541884   542052  -0.03 │   0    0    nan │
│      coq-mathcomp-character │  157.60   157.63  -0.02 │   438214671534    438807952128  -0.14 │   599015917939    598816923183   0.03 │  718032   731168  -1.80 │   0    0    nan │
│            coq-fiat-parsers │  614.10   614.13  -0.00 │  1718194904756   1716297476526   0.11 │  2548786542431   2547929373912   0.03 │ 3076188  3076128   0.00 │   0    0    nan │
│             coq-fiat-crypto │ 5016.65  5015.13   0.03 │ 13927883574623  13923756705041   0.03 │ 23991219890081  23994956287139  -0.02 │ 2219984  2218728   0.06 │   0    0    nan │
│             coq-lambda-rust │ 1312.47  1311.54   0.07 │  3650146747900   3648198128566   0.05 │  5101724271068   5101726836800  -0.00 │ 1077296  1077368  -0.01 │   0    0    nan │
│       coq-engine-bench-lite │  326.23   325.90   0.10 │   919422128837    917772538150   0.18 │  1659780106791   1657290786211   0.15 │ 3506240  3506320  -0.00 │   0    0    nan │
│  coq-performance-tests-lite │ 1649.76  1647.62   0.13 │  4602051835857   4594975696378   0.15 │  7470977176329   7471042671722  -0.00 │ 2079180  2079104   0.00 │   0    0    nan │
│               coq-perennial │ 7059.83  7048.98   0.15 │ 19654660219275  19647808908485   0.03 │ 29195637722870  29188593263132   0.02 │ 3061328  3078788  -0.57 │   0    0    nan │
│                  coq-geocoq │ 1383.58  1381.37   0.16 │  3856282021568   3849408294036   0.18 │  5489884000024   5489242048551   0.01 │  988372  1003832  -1.54 │   0    0    nan │
│                coq-bedrock2 │  318.83   318.16   0.21 │   885559649948    884705029114   0.10 │  1515639794272   1515008258073   0.04 │  798332   770504   3.61 │   0    0    nan │
│                    coq-hott │  350.30   349.15   0.33 │   969396153035    969035385295   0.04 │  1410693565413   1410443985233   0.02 │  568692   568512   0.03 │   0    0    nan │
│                 coq-coqutil │   60.38    60.14   0.40 │   167346867467    167459388738  -0.07 │   215249177699    214893566907   0.17 │  598180   598152   0.00 │   0    0    nan │
│      coq-mathcomp-ssreflect │   56.12    55.87   0.45 │   154324539690    154118102942   0.13 │   192201644235    192044850173   0.08 │  527408   528688  -0.24 │   0    0    nan │
│              coq-coquelicot │   71.29    70.92   0.52 │   194952135471    194794719855   0.08 │   240729699066    240094414947   0.26 │  555860   555776   0.02 │   0    0    nan │
│                  coq-stdlib │  425.25   422.78   0.58 │  1187092799409   1183917254531   0.27 │  1495657651074   1495290395703   0.02 │  596024   596220  -0.03 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
UniMath is now faster with this patch, go figure.

**Comment by gares** [comment]
Well, merge before it moves

**Comment by gares** [comment]
Wrt unimath, it's not completely nonsense: the terms are huge, the kernel reduction is faster... now that we compare apples with apples, with unwinding out of the picture, we might just see need versus name.

**Comment by ppedrot** [comment]
I believe this is ready but since I have become a coauthor it might be good to switch assignees. @SkySkimmer maybe?

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now
