### PR TITLE
Make rewrite use the registered elimination schemes

### LINKED ISSUE #10456: Equality rewrite using registered elimination schemes
#### Description of the problem

The rewrite and ssr-rewrite tactics do not use the registered elimination schemes for equality. For instance
```coq
Inductive EQ {A} (x : A) : A -> Type
  := EQ_refl : EQ x x.

Register EQ as core.eq.type.

Lemma renamed_EQ_rect_r {A} (x:A) (P : A -> Type)
  (c : P x) (y : A) (e : EQ y x) : P y.
Proof. destruct e. assumption. Qed.

Register renamed_EQ_rect_r as core.eq.rect_r.
Register renamed_EQ_rect_r as core.eq.ind_r.

Lemma EQ_sym1 {A} {x y : A} (e : EQ x y) : EQ y x.
Proof. rewrite e.
```
The `rewrite` fails with error message `Cannot find rewrite principle EQ_ind_r`, and so it ignores the registered elimination scheme.

I am currently working on fixing this.

### PR DESCRIPTION
**Pull request by andreaslyn**
**Kind:** bug fix

Fixes / closes #10456

- [x] Added / updated test-suite

### CODE REVIEW

File: plugins/ssr/ssrequality.ml [hunk 1]
```diff
@@ -128,10 +128,9 @@ let newssrcongrtac arg ist gl =
     x, re_sig si sigma in
   let arr, gl = pf_mkSsrConst "ssr_congr_arrow" gl in
   let ssr_congr lr = EConstr.mkApp (arr, lr) in
+  let eq, gl = pf_fresh_global Coqlib.(lib_ref "core.eq.type") gl in
```
Comment (andreaslyn) [inline plugins/ssr/ssrequality.ml]: When equality is universe polymorphic, then we need to keep the universes in context. Therefore this line has been moved up.

File: plugins/ssr/ssrequality.ml [hunk 2]
```diff
@@ -336,17 +335,21 @@ let pirrel_rewrite ?(under=false) ?(map_redex=id_map_redex) pred rdx rdx_ty new_
...
     let sort = elimination_sort_of_goal gl in
-    let elim, gl = pf_fresh_global (Indrec.lookup_eliminator env ind sort) gl in
-    if dir = R2L then elim, gl else (* taken from Coq's rewrite *)
-    let elim, _ = destConst elim in
-    let mp,l = Constant.repr2 (Constant.make1 (Constant.canonical elim)) in
-    let l' = Label.of_id (Nameops.add_suffix (Label.to_id l) "_r")  in
-    let c1' = Global.constant_of_delta_kn (Constant.canonical (Constant.make2 mp l')) in
-    mkConst c1', gl in
-  let elim = EConstr.of_constr elim in
+    match Equality.eq_elimination_ref (dir = L2R) sort with
```
Comment (andreaslyn) [inline plugins/ssr/ssrequality.ml]: This match-expression does the following: If the elimination scheme has been registered then use it, otherwise use the "old" code to obtain the elimination scheme.

File: plugins/ssr/ssrequality.ml [hunk 3]
```diff
@@ -491,7 +494,8 @@ let rwprocess_rule dir rule gl =
           | _ ->
             let sigma, pi2 = Evd.fresh_global env sigma coq_prod.Coqlib.proj2 in
             EConstr.mkApp (pi2, ra), sigma in
-        if EConstr.eq_constr sigma a.(0) (EConstr.of_constr (UnivGen.constr_of_monomorphic_global @@ Coqlib.(lib_ref "core.True.type"))) then
+        let sigma,trty = Evd.fresh_global env sigma Coqlib.(lib_ref "core.True.type") in
```
Comment (andreaslyn) [inline plugins/ssr/ssrequality.ml]: In the HoTT library `core.True.type` is not monomorphic.

File: tactics/equality.ml [hunk 4]
```diff
@@ -345,35 +360,35 @@ let find_elim hdcncl lft2rgt dep cls ot =
...
-        in
         begin match lft2rgt, cls with
         | Some true, None
         | Some false, Some _ ->
-          let c1 = destConstRef pr1 in
-          let mp,l = Constant.repr2 (Constant.make1 (Constant.canonical c1)) in
-          let l' = Label.of_id (add_suffix (Label.to_id l) "_r")  in
-          let c1' = Global.constant_of_delta_kn (KerName.make mp l') in
-          begin
+          begin match if is_eq then eq_elimination_ref true sort else None with
```
Comment (andreaslyn) [inline tactics/equality.ml]: This match-expression works as follows: If it is a rewrite of `core.eq.type` and the elimination scheme has been registered then use it. Otherwise it is a Jmeq or the equality elimination scheme has not been registered, in this case, just use the "old" code.

File: plugins/ssr/ssrequality.ml (hunk 2 above)
Comment (gares) [reply plugins/ssr/ssrequality.ml]: It looks like the old code was wrong, so the new one is also wrong.

`gl` contains a `sigma` so one should thread, as a state, only `gl`, that is what is typically done in the rest of the code.

But here we have both `(sigma,c)` and `gl`, and given that we are using `c` to build `proof` (as well as `elim`) we should update `sigma` to obtain a new `(sigma,proof)`.

Imo the branch you copied, the one for `None` should also update sigma (and not `gl`) and use `Evd.fresh_global` instead of the lifter `pf_fresh_global`. Similarly, `c_ty` should be reduced using sigma via `Tacred.reduce_to_quantified_ind`.

Would you mind updating the code?

Comment (andreaslyn) [reply plugins/ssr/ssrequality.ml]: Does it look right now?

Comment (gares) [reply plugins/ssr/ssrequality.ml]: Great

**Review by gares — APPROVED** [review]

**Review by gares — APPROVED** [review]
SSR ok

**Comment by spitters** [comment]
Are any of the CI problems related to this PR?

**Comment by maximedenes** [comment]
@ppedrot can you assign yourself?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@andreaslyn can you rebase to get a clean CI?

**Comment by andreaslyn** [comment]
I have rebased and fixed the last SSR test case  to use `rewrite -e` rather than `rewrite <- e`.

**Comment by ppedrot** [comment]
Is the CI failure of bedrock2 and fiat-crypto-legacy related or not?

**Comment by andreaslyn** [comment]
> Is the CI failure of bedrock2 and fiat-crypto-legacy related or not?

The error is
ls: cannot access '/builds/coq/coq/_install_ci/bin/': No such file or directory

It seems unrelated, but I am not sure. Maybe someone else knows?

**Comment by ejgallego** [comment]
@andreaslyn I recommend you rebase and push so the CI is ran again.

**Comment by andreaslyn** [comment]
The command `Register eq_rect_r as core.eq.rect_r` apparently caused some rewrites to fail by making coq unable to realize that `eq_rect_r` is defined in terms of `eq_rect` when rewriting.

I have removed the `Register` because is is not necessary. The rewrite defaults to the "old" code when `eq_rect_r` has not been registered.

**Comment by andreaslyn** [comment]
@ppedrot I think this is ready now.
