### PR TITLE
Fix #9455: avoid update_global_env when unchanged Global.universes()

### LINKED ISSUE #9455: Set  is slow when there are many universes / universe constraints, and Time fails to report correct timings
#### Version

8.8.2 (also 8.9.0, also master)

#### Description of the problem

foo.v:
~~~coq
Set Universe Polymorphism.
Set Printing Universes.
Ltac many n T :=
  let T' := match constr:(Type : T) with ?T' => T' end in
  lazymatch n with
  | S ?n' => many n' T'
  | O => pose T'
  | ?k => idtac k
  end.
Goal True.
  idtac "before 1". Time do 20 many 4999 Type. idtac "after 1".
  idtac "before 2". Time Set Printing Width 70. idtac "after 2".
  idtac "before 3". Time Set Printing Width 70. idtac "after 3".
  idtac "before 4". Time Set Printing Width 70. idtac "after 4".
  idtac "before 5". Time Set Printing Width 70. idtac "after 5".
  idtac "before 6". Time Set Printing Width 70. idtac "after 6".
  idtac "before 7". Time Set Printing Width 70. idtac "after 7".
  idtac "before 8". Time Set Printing Width 70. idtac "after 8".
  idtac "before 9". Time Set Printing Width 70. idtac "after 9".
  idtac "before 10". Time Set Printing Width 70. idtac "after 10".
  idtac "before 11". Time Set Printing Width 70. idtac "after 11".
  idtac "before 12". Time exact I.
Qed.
~~~
insert-timings.sh:
~~~bash
#!/bin/bash

set -e

PREV_TIME=$(date +%s.%N)
PREV=""
DO_PRINT=""

while read i
do
    NEXT="$(date +%s.%N)"
    DIFF="$(echo "$NEXT - $PREV_TIME" | bc)"
    if [ ! -z "$DO_PRINT" ];
    then
        echo "$DIFF: $PREV"
    else
        DO_PRINT="yes"
    fi
    PREV="$i"
    PREV_TIME="$NEXT"
done
~~~
~~~
$ time coqc -q -time foo.v 2>&1 | ./insert-timings.sh
.004712724: Chars 0 - 26 [Set~Universe~Polymorphism.] 0. secs (0.u,0.s)
.004934467: Chars 27 - 50 [Set~Printing~Universes.] 0. secs (0.u,0.s)
.004648122: Chars 51 - 210 [Ltac~~many~n~T~:=~~~let~T'~:=~...] 0. secs (0.u,0.s)
.004266738: Chars 211 - 221 [Goal~_~True.] 0. secs (0.u,0.s)
.004394168: Chars 224 - 241 [idtac~"before~1".] before 1
9.073842372: 0. secs (0.u,0.s)
.004120050: Chars 242 - 268 [Time~(do~20~many~4999~Type).] Finished transaction in 9.094 secs (8.767u,0.327s) (successful)
.004098339: 9.094 secs (8.767u,0.327s)
.004372295: Chars 269 - 285 [idtac~"after~1".] after 1
.003894177: 0. secs (0.u,0.s)
.003865365: Chars 288 - 305 [idtac~"before~2".] before 2
.003739245: 0. secs (0.u,0.s)
.003950665: Chars 306 - 333 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
.875859353: 0. secs (0.u,0.s)
.004114739: Chars 334 - 350 [idtac~"after~2".] after 2
.004399637: 0. secs (0.u,0.s)
.004427152: Chars 353 - 370 [idtac~"before~3".] before 3
.003690056: 0. secs (0.u,0.s)
.003593700: Chars 371 - 398 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
.960026850: 0. secs (0.u,0.s)
.004539827: Chars 399 - 415 [idtac~"after~3".] after 3
.004538316: 0. secs (0.u,0.s)
.004342874: Chars 418 - 435 [idtac~"before~4".] before 4
.003925015: 0. secs (0.u,0.s)
.003746309: Chars 436 - 463 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
1.138107013: 0. secs (0.u,0.s)
.004204189: Chars 464 - 480 [idtac~"after~4".] after 4
.004470147: 0. secs (0.u,0.s)
.004101535: Chars 483 - 500 [idtac~"before~5".] before 5
.005358555: 0. secs (0.u,0.s)
.004099959: Chars 501 - 528 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
1.020929774: 0. secs (0.u,0.s)
.004426571: Chars 529 - 545 [idtac~"after~5".] after 5
.004441045: 0. secs (0.u,0.s)
.004162402: Chars 548 - 565 [idtac~"before~6".] before 6
.004159529: 0. secs (0.u,0.s)
.003892189: Chars 566 - 593 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
.936709740: 0. secs (0.u,0.s)
.004444134: Chars 594 - 610 [idtac~"after~6".] after 6
.004415756: 0. secs (0.u,0.s)
.004155721: Chars 613 - 630 [idtac~"before~7".] before 7
.004087137: 0. secs (0.u,0.s)
.003772480: Chars 631 - 658 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
.944046201: 0. secs (0.u,0.s)
.004518382: Chars 659 - 675 [idtac~"after~7".] after 7
.004550309: 0. secs (0.u,0.s)
.004140333: Chars 678 - 695 [idtac~"before~8".] before 8
.004142852: 0. secs (0.u,0.s)
.004013728: Chars 696 - 723 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
2.168377323: 0. secs (0.u,0.s)
.004612835: Chars 724 - 740 [idtac~"after~8".] after 8
.004532193: 0. secs (0.u,0.s)
.004194022: Chars 743 - 760 [idtac~"before~9".] before 9
.004053230: 0. secs (0.u,0.s)
.003984221: Chars 761 - 788 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
.941996799: 0. secs (0.u,0.s)
.004281857: Chars 789 - 805 [idtac~"after~9".] after 9
.004419273: 0. secs (0.u,0.s)
.003679961: Chars 808 - 826 [idtac~"before~10".] before 10
.004546720: 0. secs (0.u,0.s)
.003617484: Chars 827 - 854 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
.889374164: 0. secs (0.u,0.s)
.004034528: Chars 855 - 872 [idtac~"after~10".] after 10
.004392084: 0. secs (0.u,0.s)
.003685162: Chars 875 - 893 [idtac~"before~11".] before 11
.003923619: 0. secs (0.u,0.s)
.003624200: Chars 894 - 921 [Time~Set~Printing~Width~70.] Finished transaction in 0. secs (0.u,0.s) (successful)
.901113303: 0. secs (0.u,0.s)
.003571677: Chars 922 - 939 [idtac~"after~11".] after 11
.006097648: 0. secs (0.u,0.s)
.004451554: Chars 942 - 960 [idtac~"before~12".] before 12
.004819130: 0. secs (0.u,0.s)
.003782265: Chars 961 - 974 [Time~exact~I.] Finished transaction in 0. secs (0.u,0.s) (successful)
1.503087702: 0. secs (0.u,0.s)
.004564926: Chars 975 - 979 [Qed.] Finished transaction in 0. secs (0.u,0.s) (successful)
.005486220: 0. secs (0.u,0.s)
.004178441: Finished transaction in 0. secs (0.u,0.s) (successful)
.004277179: 0. secs (0.u,0.s)
.003829345: Finished transaction in 0. secs (0.u,0.s) (successful)
.004001310: 0. secs (0.u,0.s)
.003758902: Finished transaction in 0. secs (0.u,0.s) (successful)
.003734920: 0. secs (0.u,0.s)
.003462902: Finished transaction in 0. secs (0.u,0.s) (successful)
.003309397: 0. secs (0.u,0.s)
.003203796: Finished transaction in 0. secs (0.u,0.s) (successful)
.003299325: 0. secs (0.u,0.s)
.003289328: Finished transaction in 0. secs (0.u,0.s) (successful)
.003461455: 0. secs (0.u,0.s)
.003347093: Finished transaction in 0. secs (0.u,0.s) (successful)
.003288947: 0. secs (0.u,0.s)
.003321123: Finished transaction in 0. secs (0.u,0.s) (successful)
.003272947: 0. secs (0.u,0.s)
.003324127: Finished transaction in 0. secs (0.u,0.s) (successful)
.003231499: 0. secs (0.u,0.s)

real    0m21.781s
user    0m21.284s
sys     0m0.520s
~~~
Note that each `Set Printing Width 70.` takes about 1--2 seconds.  If I double the number of universes / constraints, then the time for each `Set Printing Width` doubles.

Here is a flame-graph that @andres-erbsen made debugging this issue inside of bedrock2: https://gist.github.com/andres-erbsen/edd3902c927bf67cba0ca1e9a7718d7c

cc @gares @mattam82 @ejgallego @SkySkimmer

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/730/console

**Comment by SkySkimmer** [comment]
New version which makes vernacentries correct wrt update_global_env (for instance try Loading test-suite/success/sideff.v)
There's still a update_global_env in stm, used through inject_non_pstate, necessary according to the `sideff` test with a nested proof.

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/731/console

File: vernac/vernacentries.ml [hunk 1]
```diff
@@ -2749,7 +2749,10 @@ and vernac_load ~verbosely ~st fname =
 
 and interp_control ?proof ~st v = match v with
   | { v=VernacExpr (atts, cmd) } ->
-    interp_expr ?proof ~atts ~st cmd
+    let before_univs = Global.universes () in
+    let pstack = interp_expr ?proof ~atts ~st cmd in
+    if before_univs == Global.universes () then pstack
+    else Option.map Proof_global.(modify_current_pstate update_global_env) pstack
```
Comment (SkySkimmer) [inline vernac/vernacentries.ml]: Actually this is not correct, eg if you load
~~~coq
Definition idw (A : Type) := A.
Set Nested Proofs Allowed.

Lemma foobar' : unit.
  Lemma hide : True. Proof.
  Lemma aux : forall A : Type, A -> unit.
  Proof. intros. pose (foo := idw A). exact tt. Show Universes. Qed.
  exact I. Qed.
  apply (@aux unit tt).
Qed.
~~~
Not sure if we need to modify all pstates (instead of just the top one) or what.
The same code run in the regular way works fine (it's using the stm update_global_env instead I guess).

Comment (SkySkimmer) [reply vernac/vernacentries.ml]: I guess we can go with this for now, I doubt anyone uses Load on something with nested proofs since it already doesn't work in master.

Comment (ejgallego) [reply vernac/vernacentries.ml]: Even if the PR is correct as this IMHO we should reify the universe modifications into something that can allow clients to handle such effect in a more controlled way, so for example a tactic run will return a `result` type kind of `Nothing | UpdateUnivs of universe`.

Comment (ejgallego) [reply vernac/vernacentries.ml]: So what are the paths new universes get created?

Comment (ejgallego) [reply vernac/vernacentries.ml]: On the other hand it is reasonable to forbid load from every opening a proof.

Comment (ejgallego) [reply vernac/vernacentries.ml]: > So what are the paths new universes get created?

Also something I'm wondering is why do we do a merge, isn't the process of creating new universes monotonous [so an addition would suffice]?

But something is strange here, imagine we have:
```
Lemma p1 : T. Proof. p1. Qed.
Lemma p2 : T. Proof. p2. Qed.
```
where both proofs do create universes, it turns out we cannot really run them in parallel, right? We must use the "global" counter and keep the corresponding locks, etc....

So it seems to me that indeed new universe creation should go into a special part of the `evar_map` so that opaque proofs do return the set of universes created in the proof and then these are reconciled; likely by an update of the universe map as to be more efficient. WDYT?

Comment (ejgallego) [reply vernac/vernacentries.ml]: For now what I'm planning to do with delegated proofs is to check if they are producing new universes, and if so, re-schedule them to be run in a non-delegated way.

Comment (gares) [reply vernac/vernacentries.ml]: > For now what I'm planning to do with delegated proofs is to check if they are producing new universes, and if so, re-schedule them to be run in a non-delegated way.

No please. All proofs can generate new universes. There is a remote_counter interface (with locks and stuff). Also "re-scheduling" things is just extra complexity (wrt the already existing global remote counter with a lock).

The orthodox solution to get rid of this complexity is to make universe names depend on the constant in which they were generated, making them "global to a constant" instead of "global to the system". If it was done that way no lock would be needed, no global counter.

BTW, a while ago, if I'm not mistaken, @SkySkimmer make universes created during proof construction more hidden than before. Bet I don't recall the details.

Comment (ejgallego) [reply vernac/vernacentries.ml]: Having the tactic engine do IPC is just too heavy to me; anyways that's a valid choice as a client implementor, to trade off complexity for performance.

> The orthodox solution to get rid of this complexity is to make universe names depend on the constant in which they were generated, making them "global to a constant" instead of "global to the system". If it was done that way no lock would be needed, no global counter.

Even if you do so [which is what I was proposing above], you still have a question about combination of such local universes and that seems far from trivial I think.

Comment (SkySkimmer) [reply vernac/vernacentries.ml]: Delegated proofs can produce different universes and constraints compared to non-delegated proofs, including different unification failures and all that ensues.
Most scripts don't trigger such issues so in practice we just ignore the possibility when we want to run proofs in parallel.

>So what are the paths new universes get created?

Anything using constrs + a couple commands like Universe

>BTW, a while ago, if I'm not mistaken, @SkySkimmer make universes created during proof construction more hidden than before. Bet I don't recall the details.

I don't know what you're talking about.

Comment (ejgallego) [reply vernac/vernacentries.ml]: > Anything using constrs + a couple commands like Universe

Yeah thanks, I wonder how frequent that is in practice; I guess I'll instrument the CI once I can push some changes.

I guess from the User Interface point of view we want to mark such proofs and dependencies as unsafe, they could be added to a queue and re-checked in the background in the proper safe order, I just wish there was a way to construct a DAG-like dependency tree instead of just the linear order we'd do today.

**Comment by ejgallego** [comment]
Something I don't understand in this business of global universe generation is how the workers are coordinating when they generate new universes? I look at remote counter, but I don't exactly see where the IO is taking place. Do you maybe know @gares @SkySkimmer ?

**Comment by ejgallego** [comment]
Regarding the PR @SkySkimmer I was trying to move `Global.universes` to the `pstate` and I am not far, but indeed we can take this one if you want, I'd just like to try to understand the situation a bit better before merging.

**Comment by gares** [comment]
There is only one channel, that is hence multiplexed:
master: https://github.com/coq/coq/blob/master/stm/asyncTaskQueue.ml#L228
worker: https://github.com/coq/coq/blob/master/stm/asyncTaskQueue.ml#L337

**Comment by ejgallego** [comment]
> There is only one channel, that is hence multiplexed:

Thanks @gares ! Indeed I missed the move from `stm.ml` to `asynctask`.

**Comment by gares** [comment]
Which move? Git blame says the code is these since 8.5 https://github.com/coq/coq/commit/4e724634839726aa11534f16e4bfb95cd81232a4

**Comment by ejgallego** [comment]
> Git blame says the code is these since 8.5 [4e72463](https://github.com/coq/coq/commit/4e724634839726aa11534f16e4bfb95cd81232a4)

Exactly that commit is the one I missed [from stm to asynctaskqueue]

**Comment by SkySkimmer** [comment]
>Regarding the PR @SkySkimmer I was trying to move Global.universes to the pstate and I am not far

How does that work?

**Comment by ejgallego** [comment]
> How does that work?

See related [draft] PRs, but we would use the env stashed in the proofview. [There are two of them actually]

**Comment by SkySkimmer** [comment]
@gares @ejgallego I don't think waiting will get us much, shall we merge?

**Comment by ejgallego** [comment]
I have been thinking about this a bit, I'm not sure I'm very comfortable with the fix, but I guess you are right this is not something we are going to improve in the short term.

As the overhead of delaying the PR is small itself give me couple of days [well more like until next week] if you don't mind because I'd like to understand the situation a bit better.

But feel free to merge if you don't want to wait.

**Comment by ejgallego** [comment]
So if other devs agree I'm happy to assign and merge next week, once I can spend an extra hour trying to understand the low-level code.

**Comment by SkySkimmer** [comment]
It's already waited a couple weeks, what's one more.
Feel free to ask help when trying to understand (maybe on gitter or discourse rather than here?)

**Comment by ejgallego** [comment]
I am in the middle of this, and thinking out loud it seems to me that this kind of fix is not going to scale in the long term, clients need to be more flexible in general as for when they apply this kind of corrections, if proof delegation is controlled on a different layer for example.

So indeed while out of scope for this PR, maybe we should define a richer return type for `interp` that captures the relevant side-effects done in the interpretation, something such as `| NoEff | NewUnivs of ... | NewGlobals of ...` etc...

But indeed we should try to make a bit more progress on the lower-parts cleanup first.

**Comment by ejgallego** [comment]
I had finally time to review this, let me ask a couple of questions to be sure I understand:

- before we called `update_global_env` only when a side-effect took place in the middle of a proof, regardless of whether the universe graph had changed,
- now we call it at every command, including a normal tactic, if it has changed the universe counter.

is that correct?

**Comment by SkySkimmer** [comment]
>before we called update_global_env only when a side-effect took place in the middle of a proof, regardless of whether the universe graph had changed,

Yes

>now we call it at every command, including a normal tactic, if it has changed the universe counter.

No, the condition is "if it has changed the global universe graph". We don't look at the counter (there isn't even an API for looking at the counter without incrementing it)

**Comment by gares** [comment]
> We don't look at the counter (there isn't even an API for looking at the counter without incrementing it)

And if there was, it would still make no sense to look at the symgen value.
What you want to look at is "the universes that are part of the graph", not to peek which is the name of the next fresh universe one may generate.

Imo the discussion about the symgen for universe name is unrelated to updating the env. The only link is that are both hacks. One to deal with global side effects and the local copy in the proof monad of piece of the global state; the other with the choice of a global naming schema for universes.

**Comment by ejgallego** [comment]
Thanks for the explanation @SkySkimmer ,

> if it has changed the global universe graph

What kind of commands do modify such graph? For example, can regular tactics alter it?

**Comment by SkySkimmer** [comment]
If by regular you mean non-abstract then no (although I guess a 3rd party plugin could make something like abstract)

**Comment by SkySkimmer** [comment]
I guess abstract is supposed to do its own updating too

Gaëtan Gilbert

**Comment by ejgallego** [comment]
Ok thanks! IMHO we can then merge this for now; hopefully we should get rid of `Global.universes` quite soon [well, place it after vernacentries] and this hack can go away, but meanwhile I guess we can live with this.

Any other comment @gares ? If not I shall merge soon.

**Review by ejgallego — APPROVED** [review]
This seems a good idea until we can have better control of `Global.universes`.

**Comment by SkySkimmer** [comment]
>hopefully we should get rid of Global.universes quite soon [well, place it after vernacentries]

"get rid" is a pretty confusing way to say "place it after vernacentries"

**Comment by ejgallego** [comment]
> "get rid" is a pretty confusing way to say "place it after vernacentries"

well, I'd like to get rid of it completely, however that is not realistic unless someone can rewrite the STM to handle state functionally.
