### PR TITLE
[ssr] assertion -> error message (Fix #8134)

### LINKED ISSUE #8134: anomalies with elim
#### Version

```
The Coq Proof Assistant, version 8.8.0 (July 2018)
compiled on Jul 18 2018 11:50:33 with OCaml 4.05.0
```

#### Operating system
Ubuntu 18.04 LTS

#### Description of the problem

```
From mathcomp.ssreflect
Require Import ssreflect ssrbool ssrnat eqtype.


Lemma example (m : nat) : forall n, n == 0.
Proof.
    elim Hm: m => [n | m'].
(* Anomaly "File "plugins/ssr/ssripats.ml", line 369, characters 15-21: Assertion failed." Please report at http://coq.inria.fr/bugs/. *)

```

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]

File: plugins/ssr/ssripats.ml [hunk 1]
```diff
@@ -379,8 +379,9 @@ let elim_intro_tac ipats ?ist what eqid ssrelim is_rec clr =
          let ctx, last = EConstr.decompose_prod_assum sigma concl in
          let args = match EConstr.kind_of_type sigma last with
            | Term.AtomicType (hd, args) ->
-               assert(Ssrcommon.is_protect hd env sigma);
-               args
+               if Ssrcommon.is_protect hd env sigma then args
+               else Ssrcommon.errorstrm
+                  (Pp.str "Too many names in intro pattern")
```
Comment (maximedenes) [inline plugins/ssr/ssripats.ml]: Can't we provide a loc?

**Comment by herbelin** [comment]
I guess this is going its way, but @maximedenes should explicitly be assignee.

**Review by maximedenes — APPROVED** [review]
