### PR TITLE
Restore typing check in notation.eval_constr

### LINKED ISSUE #15709: string notations break on partial strings with anomaly
#### Description of the problem

```coq
Require Import Coq.Strings.String.
Require Import Coq.Strings.Ascii.
Check String "]".
```
gives
```
Error: Anomaly "Uncaught exception Invalid_argument("index out of bounds")." Please report at http://coq.inria.fr/bugs/.
```

This worked fine in Coq < 8.10; in 8.10 -- 8.13, it printed incorrectly as:
```
""%string
     : string -> string
```

The anomaly shows up since 8.14

#### Coq Version

8.14, also master 89c143ea69d9e615436e1227c720d6eb8fa5e487

### PR DESCRIPTION
**Pull request by SkySkimmer**
The check was lost in b0f8e09c3212fa96934817e7ca99465cd634f57c (8.10)

Fix #15709

### CODE REVIEW

File: interp/notation.ml [hunk 1]
```diff
@@ -613,6 +613,7 @@ module PrimTokenNotation = struct
 
 let eval_constr env sigma (c : Constr.t) =
   let c = EConstr.of_constr c in
+  let _, _ = Typing.type_of env sigma c in
```
Comment (proux01) [inline interp/notation.ml:616]: Why not
```suggestion
  let sigma, _ = Typing.type_of env sigma c in
```

**Review by JasonGross — CHANGES_REQUESTED** [review]
Thanks for fixing this!

**Comment by JasonGross** [comment]
@proux01 the test-suite breakage seems to be testing suspicious behavior.  Are number notations with parametrized inductives supposed to succeed even when the printer has the wrong inductive parameters?
https://github.com/coq/coq/blob/1e78a31710701a5d3a89dafb286476bc797a4981/test-suite/output/NumberNotations.v#L775-L789
The last line here prints on master, even though I'm involves reducing the application of a function of type `O = O -> Number.uint` to a proof of type `S O = S O`.  What should this test be?  (Or more precisely, what's a version of this test that should actually succeed?  I think we should leave the test in and add a new one, rather than changing this one, because none of the other tests hit this codepath (ill-typed before reduction based on parameters, but well-typed and matching the right family after), apparently.)

File: test-suite/output/NumberNotations.out [hunk 2]
```diff
@@ -419,7 +419,15 @@ Ip3 (S (S (S O))) nat bool
...
      : 1 = 1
 0
+     : 0 = 0
+eq_refl
+     : id 0 = id 0
+eq_refl
      : 1 = 1
+0
+     : 0 = 0
+eq_refl
```
Comment (JasonGross) [inline test-suite/output/NumberNotations.out:429]: This should print as `0 : id 0 = id 0`.  Is there a way to see what the typing error is?

File: test-suite/output/NumberNotations.v [hunk 3]
```diff
@@ -782,11 +782,15 @@ Number Notation eqO eqO_of_uint eqO_to_uint : nat_scope.
 
 Check 42.
 Check eq_refl (S O).  (* doesn't match eq _ O, printer not called *)
+Check eq_refl O.
```
Comment (JasonGross) [inline test-suite/output/NumberNotations.v:785]:
```suggestion
Check eq_refl O. (* matches eq _ O, printer called *)
```

File: test-suite/output/NumberNotations.v [hunk 4]
```diff
@@ -782,11 +782,15 @@ Number Notation eqO eqO_of_uint eqO_to_uint : nat_scope.
...
+Check eq_refl (id O).
```
Comment (JasonGross) [inline test-suite/output/NumberNotations.v:786]:
```suggestion
Check eq_refl (id O). (* doesn't match eq _ O, printer not called *)
```

File: test-suite/output/NumberNotations.v [hunk 5]
```diff
@@ -782,11 +782,15 @@ Number Notation eqO eqO_of_uint eqO_to_uint : nat_scope.
...
 
 Notation eq_ := (eq _ _) (only parsing).
 Number Notation eq_ eqO_of_uint eqO_to_uint : nat_scope.
 
-Check eq_refl (S O).  (* matches eq _ _, printer called *)
+Check eq_refl (S O).  (* matches eq _ _, printer called, but type incorrect *)
+Check eq_refl O.
```
Comment (JasonGross) [inline test-suite/output/NumberNotations.v:792]:
```suggestion
Check eq_refl O. (* matches eq _ _, printer called *)
```

File: test-suite/output/NumberNotations.out (hunk 2 above)
Comment (SkySkimmer) [reply test-suite/output/NumberNotations.out:429]: It bails because of allow_constant:false at https://github.com/coq/coq/blob/93f0cc96dbb825c467759aee5573e6969a3d9a0c/interp/notation.ml#L682

**Comment by SkySkimmer** [comment]
Are those `matches bla` comments really worthwhile?

**Comment by proux01** [comment]
I find them helpful, but no strong opinion. You are the author of the PR, fine by me if you prefer to remove them.

File: test-suite/output/NumberNotations.out (hunk 2 above)
Comment (JasonGross) [reply test-suite/output/NumberNotations.out:429]: Ah, I see.  In that case, before
```coq
Number Notation eqO eqO_of_uint eqO_to_uint : nat_scope.
```
could you add
```coq
Notation eqS := (eq _ (S _)) (only parsing).
Number Notation eqS eqO_of_uint eqO_to_uint : nat_scope.

Check 42.
Check eq_refl (S O).  (* matches eqS, but printer type errors, so not printed *)
Check eq_refl O. (* does not match eqS, printer not called *)
Check eq_refl (id O). (* contains a global constant, printer not called *)
```
to test that when the notation doesn't match we don't print

**Comment by proux01** [comment]
@SkySkimmer @JasonGross what's the status of this?

File: test-suite/output/NumberNotations.out (hunk 2 above)
Comment (SkySkimmer) [reply test-suite/output/NumberNotations.out:429]: I get `Cannot infer this placeholder of type "nat".` on `Number Notation eqS ...`

**Comment by SkySkimmer** [comment]
ping @JasonGross

**Comment by SkySkimmer** [comment]
ping @JasonGross

File: test-suite/output/NumberNotations.out (hunk 2 above)
Comment (JasonGross) [reply test-suite/output/NumberNotations.out:429]: Uh, this seems suspicious, but I guess it doesn't have to be solved in this PR.  Why is `(eq _ _)` fine but `(eq _ (S _))` not?  / Where does this error come from?

**Review by JasonGross — APPROVED** [review]

File: test-suite/output/NumberNotations.out (hunk 2 above)
Comment (SkySkimmer) [reply test-suite/output/NumberNotations.out:429]: https://github.com/coq/coq/blob/0b1ae026456fe950c895bfe5ecc519402dcfa4b0/plugins/syntax/number.ml#L403
`eq _ _` falls in the `NHole` case a couple lines above

Comment (proux01) [reply test-suite/output/NumberNotations.out:429]: This looks to me like a limitation of the current implem.
This shouldn't prevent merging the current PR.

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
I'll merge by the end of the week if there is no further comment.

**Comment by proux01** [comment]
@coqbot merge

**Comment by SkySkimmer** [comment]
It obeys "merge now" not "merge"

**Comment by proux01** [comment]
@coqbot merge now
