### PR TITLE
[elaboration] Bidirectionality hints

### LINKED ISSUE #5767: Typechecking the argument of an application does not take into account expected type
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5767
From: @Janno
Reported version: 8.7+beta1
CC:   @herbelin, @mattam82

See also: [BZ#5788](https://github.com/coq/coq/issues?q=is%3Aissue%20%22Original%20bug%20ID%3A%20BZ%235788%22)

### LINKED ISSUE #7910: Type inference/unification unable to propagate information on dependent types
#### Version

8.8.0

#### Operating system
Linux

#### Description of the problem

Consider the following example:
```coq
From Coq Require Import Utf8.
Set Default Proof Using "Type".

Local Set Universe Polymorphism.

(** Telescopes *)
Inductive tele : Type :=
  | TeleO : tele
  | TeleS {X} (binder : X → tele) : tele.

Arguments TeleS {_} _.

(** The telescope version of Coq's function type *)
Fixpoint tele_fun (TT : tele) (T : Type) : Type :=
  match TT with
  | TeleO => T
  | TeleS b => ∀ x, tele_fun (b x) T
  end.

Notation "TT -t> A" :=
  (tele_fun TT A) (at level 99, A at level 200, right associativity).

(** An eliminator for elements of [tele_fun].
    We use a [fix] because, for some reason, that makes stuff print nicer
    in the proofs in iris:bi/lib/telescopes.v *)
Definition tele_fold {X Y} {TT : tele} (step : ∀ {A : Type}, (A → Y) → Y) (base : X → Y)
  : (TT -t> X) → Y :=
  (fix rec {TT} : (TT -t> X) → Y :=
     match TT as TT return (TT -t> X) → Y with
     | TeleO => λ x : X, base x
     | TeleS b => λ f, step (λ x, rec (f x))
     end) TT.
Arguments tele_fold {_ _ !_} _ _ _ /.

(** A sigma-like type for an "element" of a telescope, i.e. the data it
  takes to get a [T] from a [TT -t> T]. *)
Inductive tele_arg : tele → Type :=
| TargO : tele_arg TeleO
(* the [x] is the only relevant data here *)
| TargS {X} {binder} (x : X) : tele_arg (binder x) → tele_arg (TeleS binder).

Definition tele_app {TT : tele} {T} (f : TT -t> T) : tele_arg TT → T :=
  λ a, (fix rec {TT} (a : tele_arg TT) : (TT -t> T) → T :=
     match a in tele_arg TT return (TT -t> T) → T with
     | TargO => λ t : T, t
     | TargS x a => λ f, rec a (f x)
     end) TT a f.
Arguments tele_app {!_ _} _ !_ /.

Coercion tele_arg : tele >-> Sortclass.
Coercion tele_app : tele_fun >-> Funclass.

(** Operate below [tele_fun]s with argument telescope [TT]. *)
Fixpoint tele_bind {U} {TT : tele} : (TT → U) → TT -t> U :=
  match TT as TT return (TT → U) → TT -t> U with
  | TeleO => λ F, F TargO
  | @TeleS X b => λ (F : TeleS b → U) (x : X), (* b x -t> U *)
                  tele_bind (λ a, F (TargS x a))
  end.
Arguments tele_bind {_ !_} _ /.

(** Telescopic quantifiers *)
Definition tforall {TT : tele} (Ψ : TT → Prop) : Prop :=
  tele_fold (λ (T : Type) (b : T → Prop), ∀ x : T, b x) (λ x, x) (tele_bind Ψ).
Arguments tforall {!_} _ /.
Definition texist {TT : tele} (Ψ : TT → Prop) : Prop :=
  tele_fold ex (λ x, x) (tele_bind Ψ).
Arguments texist {!_} _ /.

Notation "'∀..' x .. y , P" := (tforall (λ x, .. (tforall (λ y, P)) .. ))
  (at level 200, x binder, y binder, right associativity,
  format "∀..  x  ..  y ,  P").
Notation "'∃..' x .. y , P" := (texist (λ x, .. (texist (λ y, P)) .. ))
  (at level 200, x binder, y binder, right associativity,
  format "∃..  x  ..  y ,  P").

(** The actual test case *)
Definition test {TT : tele} (t : TT → Prop) : Prop :=
  ∀.. x, t x ∧ t x.

Notation "'[TEST' x .. z , P ']'" :=
  (test (TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))
        (tele_app (λ x, .. (λ z, P) ..)))
  (x binder, z binder).
Notation "'[TEST2' x .. z , P ']'" :=
  (test (TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))
        (tele_app (TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))
                  (λ x, .. (λ z, P) ..)))
  (x binder, z binder).

Fail Check [TEST (x y : nat), x = y].
(* The type of this term is a product while it is expected to be "?TT -t> ?T". *)

Check [TEST2 (x y : nat), x = y].
```
I'd expect `Check [TEST (x y : nat), x = y]` to succeed because I am explicitly giving the implicit argument to `test`, so if unification had a look at the types of `test` and `tele_app`, it'd realize that the telescope in `tele_app` has to be the same as in `test`.

The `TEST2` notation shows how we can work-around that, but that work-around has its problems: When using this notation for printing, it requires the types in both telescopes to be *syntactically* equal, which sometimes is not the case when e.g. coercions come into play. So to properly work around this, we would have to duplicate the notation and add another "only printing" variant that doesn't require the telescope to be the same. Unfortunately, in my actual use-case, that would amount to duplicating >100 lines of notation declarations.

May be related to https://github.com/coq/coq/issues/7597.

### PR DESCRIPTION
**Pull request by maximedenes**
This feature makes it possible to tell type inference to type
applications of a global `foo` using typing information from the context
once the `n` first arguments are known.

The syntax is: `Arguments foo x y | z`.

Closes #7910.
Closes #5767.

### CODE REVIEW

**Comment by maximedenes** [comment]
@Zimmi48 I'd like to write some documentation for this, but I failed to find where to start. I could hook this into the documentation of the elaboration and of the general `Arguments` syntax. Can you give a pointer to any of these? Thanks!

**Comment by maximedenes** [comment]
I was told by @gares that @ggonthier could be interested too. In particular, I'd welcome any suggestion for a better syntax ;)

**Comment by Zimmi48** [comment]
@maximedenes Most of the current documentation of the elaboration is in the Gallina extensions chapter. In particular, it contains a long section about implicit arguments, canonical structures, and the `Arguments` command. It also contains sections on extensions of `match`, and on Coercions. Thus, it feels like the right place for this, although you'll probably need to start a new section in this chapter because, contrarily to canonical structure, these typing hints do not feel like they belong to the section on implicit arguments. If you want, we can also open an issue about consolidating the documentation on type inference / elaboration.

**Comment by maximedenes** [comment]
Thanks for the hints.

> contrarily to canonical structure, these typing hints do not feel like they belong to the section on implicit arguments

Sorry for this naive question, but why would canonical structures belong to a section on implicit arguments?

> If you want, we can also open an issue about consolidating the documentation on type inference / elaboration.

We probably should indeed, because the information is currently hard to find even for developers who kind of know what they are looking for. So I imagine it must be hard for users to discover it.

**Comment by Zimmi48** [comment]
> Sorry for this naive question, but why would canonical structures belong to a section on implicit arguments?

I think it would be better if canonical structures belonged to a section on type inference / elaboration instead. But since it doesn't exist yet, I suppose that's where they fitted best (I don't know much about canonical structures, but if they are liked typeclasses, they serve to resolve implicit arguments automatically, right?).

**Comment by maximedenes** [comment]
> they serve to resolve implicit arguments automatically, right?

AFAIK, they serve to infer missing subterms (that are arguments of a canonical projection). Of course, it could come from an implicit argument, or a user-provided `_`. I don't think there's anything specific to implicit arguments there. So it seems strange to put canonical structures in a section about those.

**Comment by ggonthier** [comment]
> > they serve to resolve implicit arguments automatically, right?
> AFAIK, they serve to infer missing subterms (that are arguments of a canonical projection).

That's actually not quite correct - CS are hints telling the unification algorithm to handle problems involving a structure projection in a certain way, so they can help infer any missing subterm, not just those that are arguments of the projection. It's fairly common to infer missing proper subterms of arguments of projections, and they sometimes help infer missing sub terms in the term the projection is unified to - possibly even in cases where there are _no_ missing sub terms in the projection call (though the unification heuristics make this somewhat less likely).

**Comment by maximedenes** [comment]
> That's actually not quite correct - CS are hints telling the unification algorithm to handle problems involving a structure projection in a certain way, so they can help infer any missing subterm, not just those that are arguments of the projection. It's fairly common to infer missing proper subterms of arguments of projections, and they sometimes help infer missing sub terms in the term the projection is unified to - possibly even in cases where there are _no_ missing sub terms in the projection call (though the unification heuristics make this somewhat less likely).

Ah yes, thanks for the clarification! But it seems still unrelated to implicit arguments, right?

**Comment by Zimmi48** [comment]
I see two options:
1. Create the Elaboration / type inference section now in a separate PR and put canonical structures in it (and maybe coercions and extensions of `match` too, and actually maybe implicit arguments as well as a sub-section), then rebase this PR on top to add bidirectionality hints to this new section.
2. Create this new section in this PR with only bidirectionality hints and add more stuff to it later on.

**Comment by maximedenes** [comment]
I'll go for a third option: create a new section in the "Gallina extensions" chapter, and let the current mess being addressed separately. This will avoid delaying this PR because of preexisting doc issues.

**Comment by ggonthier** [comment]
> I was told by @gares that @ggonthier could be interested too. In particular, I'd welcome any suggestion for a better syntax ;)

I'm definitely interested in this feature, since I've been whispering about it in Enrico's ear for some years now... One change that should accompany this feature would be to apply it to standard library constants where it is sorely needed, such as `exist`, `exist2`, `existT`, and `existT2`, and indeed possibly implement a facility to automatically insert directionality hints (putting the `|` immediately after the last argument on which the return type depends, when other arguments depend on it), à la `Set Implicit Arguments`.
  In fact, it might be worth looking into the thesis that pushed me to ask for this feature: that Coq's generic unification problem delaying heuristic is only used to improve inference of two things: the `return` predicate of `match`es, and the predicate(s) if `exist` et al. Since directionality hints handle the latter more effectively, if some variant thereof could similarly handle the former, it might be possible to get rid of delayed unification constraints altogether... which Unicoq is attempting, I believe.
  Finally, I have no strong opinions about syntax, but I would note that using `&` instead of `|` would be consistent with the SSReflect alternative syntax for non-dependent arguments in datatype declarations (and more generally telescopes).

**Comment by maximedenes** [comment]
> possibly implement a facility to automatically insert directionality hints (putting the `|` immediately after the last argument on which the return type depends, when other arguments depend on it), à la `Set Implicit Arguments`.

Ah ah, this was next on my list ;)

**Comment by ggonthier** [comment]
> Ah yes, thanks for the clarification! But it seems still unrelated to implicit arguments, right?
Even more so, though there's the obvious relation that implicit arguments are the primary means of introducing missing sub terms, though by no means the only one (`rewrite`, `(e)apply`, `case`, `Notation`, explicit `_`  and even canonical instance insertion can all do so).

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
There should be a libobject declaration to allow bidir hints to survive modules/files ;) 
I guess it should behave like other Arguments objects if it's specified through Arguments. I'm not sure if all the Arguments functionality is the same as impargs (require-time, section-local unless `Global` specified).

Maybe there should be a way to clear the bidir hint for a global too (does putting the `|` at the end of the list have the same effect in general?)

Also `About`/`Print` should print the bidir hint if present.

The inline comments are nits, although I'd like some info about that `nargs >= 0` test.

**Comment by gares** [comment]
> I'm definitely interested in this feature, since I've been whispering about it in Enrico's ear for some years now...

Well, it turns out last week @maximedenes was prompted to solve an elaboration weakness by the "Coq Consortium support service" and that he came to my office... :grin: I'm very happy the code was finally written!

> it might be possible to get rid of delayed unification constraints altogether... which Unicoq is attempting, I believe.

That is also my hope, but I don't know well enough how Coq typechecks a match (I don't exactly see why delaying there helps its current algorithm) so I'm not so sure but I trust your intuition.

[OT] There is another case where "delay" helps, and that is not related to unification per se but rather the order in which the elaborateor processes terms. Eg `Lemma foo x : x == 1 -> stuff x`. Here `stuff` imposes on `x` a type for which an `eqType` instance exists, but if you process terms in the left to right order than you face the projection-value problem to early to infer a canonical solution. I'm sure this pattern occurs in MathComp, but I also believe it is a quite extreme case and I hope that this can also be solve by "rescheduling toplevel elaboration problems", rather that delaying (potentially deep) unification problems.
Any thoughts on that?

File: pretyping/pretyping.ml [hunk 1]
```diff
@@ -687,30 +716,46 @@ let rec pretype ~program_mode ~poly resolve_tc (tycon : type_constraint) (env :
...
+      (* Type the argument using this expected type *)
+      let sigma, j = pretype (Some ty) env sigma origarg in
+      (* Unify the (possibly refined) existential variable with the
+      (typechecked) original value *)
+      Evarconv.unify_delay !!env sigma newarg (j_val j)
+    in
+    (* We now refine any arguments whose typing was delayed for
+       bidirectionality *)
+    let sigma, t = app in
+    let sigma = List.fold_left refine_arg sigma bidiargs in
```
Comment (gares) [inline pretyping/pretyping.ml]: Aren't you refining these `bidiargs` in the wrong order, w.r.t. the order in which there occur in the original term?

**Review by gares — COMMENTED** [review]
LGTM.

I'd like to see a test like this
```coq
Axiom c : bool -> nat.
Coercion c : bool >-> nat.
Inductive Boxed A := Box (a : A).
Arguments Box {A} | a.
Check Box true : Boxed nat.

Axiom f : forall b, (if b then bool else nat) -> Type.
Check f true true : Type.
Arguments f | _ _.
Check f true true : Type. (* may not work, see my other comment *)
```

File: pretyping/pretyping.ml (hunk 1 above)
Comment (gares) [reply pretyping/pretyping.ml]: No problem, now I see the `List.rev`

**Comment by ggonthier** [comment]
> Eg `Lemma foo x : x == 1 -> stuff x.`
> then you face the projection-value problem too early to infer a canonical solution
Indeed, but this is one area where CS resolution outshines TC: assuming no `Implicit Type` for `x`, the type of `x` is initially `?T : Type`, unification of the constraints for `x == 1` first merely sets `?T := Equality.sort ?eqT` (CS resolution is not called since there is no unification conflict), then CS is used to unify this with the type of `1`, which would be `GRing.Zmodule.sort ?mT`, yielding the assignment `?eqT := GRing.Zmodule.eqType ?mT`, which make `?T` convertible to `GRing.Zmodule.sort ?mT`, and CS resolution may be called again whenever `stuff x` imposes a more precise type for `x`. It might not have to, as first order unification can be used if `stuff x` imposes a type of the form `GRing.Zmodule.sort someZmodType`, and if it never does impose any additional constraints, then TC and/or `Implicit tactic` can step in to fill the gap (and, if you're within an SSreflect proof and are using `have` rather than `Lemma`, then SSReflect will happily regeneralize `?mT` to leave you with a class-polymorphic statement.

File: pretyping/pretyping.ml [hunk 2]
```diff
@@ -635,24 +641,38 @@ let rec pretype ~program_mode ~poly resolve_tc (tycon : type_constraint) (env :
     let sigma, fj = pretype empty_tycon env sigma f in
     let floc = loc_of_glob_constr f in
     let length = List.length args in
+    let nargs_before_bidi =
+      (* if `f` is a global, we retrieve bidirectionality hints *)
+      try
+        let (gr,_) = destRef sigma fj.uj_val in
+        match GlobRef.Map.find_opt gr !bidi_hints with
+        | Some nargs when nargs >= 0 -> nargs
```
[the remark this answers is not in the document]
Comment (maximedenes) [reply pretyping/pretyping.ml]: This was a leftover from experimental code. Now fixed, thanks.

File: pretyping/pretyping.ml [hunk 3]
```diff
@@ -687,30 +716,46 @@ let rec pretype ~program_mode ~poly resolve_tc (tycon : type_constraint) (env :
...
+             refreshed right away. *)
+          let c = mkApp (f, args) in
+          let sigma, c = Evarsolve.refresh_universes (Some true) !!env sigma c in
+          let t = Retyping.get_type_of !!env sigma c in
+          sigma, make_judge c (* use this for keeping evars: resj.uj_val *) t
+        else sigma, resj
       | _ -> sigma, resj
     in
-    inh_conv_coerce_to_tycon ?loc env sigma resj tycon
+    let app = inh_conv_coerce_to_tycon ?loc env sigma resj tycon in
```
[the remark this answers is not in the document]
Comment (maximedenes) [reply pretyping/pretyping.ml]: Indeed, fixed, thanks.

File: pretyping/pretyping.ml [hunk 4]
```diff
@@ -662,20 +682,29 @@ let rec pretype ~program_mode ~poly resolve_tc (tycon : type_constraint) (env :
...
         | Prod (na,c1,c2) ->
           let tycon = Some c1 in
-          let sigma, hj = pretype tycon env sigma c in
+          let (sigma, hj), bidiargs =
+            if bidi then
+              (* We want to get some typing information from the context before
+              typing the argument, so we replace it by an existential
+              variable *)
+              let sigma, uj_val = new_evar env sigma ~src:(loc,Evar_kinds.InternalHole) c1 in
+              (sigma, { uj_val; uj_type = c1 }), (uj_val, c) :: bidiargs
```
[the remark this answers is not in the document]
Comment (maximedenes) [reply pretyping/pretyping.ml]: Right, thanks for the name suggestion.

**Comment by maximedenes** [comment]
> I'd like to see a test like this

Test added, thanks!

> Finally, I have no strong opinions about syntax, but I would note that using `&` instead of `|` would be consistent with the SSReflect alternative syntax for non-dependent arguments in datatype declarations (and more generally telescopes).

I've changed the syntax, thanks for the suggestion!

> Maybe there should be a way to clear the bidir hint for a global too (does putting the `|` at the end of the list have the same effect in general?)

Putting it after the last argument in the application has the same effect, but the last argument at the time of declaring the constant is not always the same (there can be extra arguments at the call site). So I added a `clear bidirectionality hint` modifier for `Arguments`.

> There should be a libobject declaration to allow bidir hints to survive modules/files ;)
> I guess it should behave like other Arguments objects if it's specified through Arguments. I'm not sure if all the Arguments functionality is the same as impargs (require-time, section-local unless `Global` specified).

Of course, where was my mind? I'll try to refactor the libobjects for `Arguments` first, though, as part of a separate PR.

> Also `About`/`Print` should print the bidir hint if present.

Right, I need to do that too.

**Comment by Janno** [comment]
Would it make any sense to allow multiple `|`? I imagine the semantics would be that the first `n₁` are used as context for the next `n₂` arguments, then `n₁ + n₂` arguments are used as context for the next group and so on an so forth. It seems like an obvious extension and, of course, exactly because of this obviousness it is at risk of being useless in practice. :)

**Comment by SkySkimmer** [comment]
I think the arguments can be discarded in a way we might not want. IIUC
~~~coq
Definition nat' := nat.
Definition foo T (x:T) := x.
Arguments foo | _ _.

Check (foo nat' : nat -> nat).
(* 
   fresh ?T : Type
   check [foo ?T : nat -> nat] -> ?T := nat 
   check [nat' : Type]
   unify [nat'] and [?T] -> success without side effect 
   return [foo nat : nat -> nat] even though we may expect [foo nat']
 *)
~~~
Is there some way we could fix that?

File: pretyping/pretyping.ml [hunk 5]
```diff
@@ -662,20 +683,29 @@ let rec pretype ~program_mode ~poly resolve_tc (tycon : type_constraint) (env :
...
+        let bidi = n >= nargs_before_bidi in
         let argloc = loc_of_glob_constr c in
         let sigma, resj = Coercion.inh_app_fun ~program_mode resolve_tc !!env sigma resj in
         let resty = whd_all !!env sigma resj.uj_type in
         match EConstr.kind sigma resty with
         | Prod (na,c1,c2) ->
           let tycon = Some c1 in
-          let sigma, hj = pretype tycon env sigma c in
+          let (sigma, hj), bidiargs =
+            if bidi then
```
Comment (SkySkimmer) [inline pretyping/pretyping.ml]: Is it useful to do the bidi stuff when there's no tycon? Otherwise we may add `&& tycon <> None` to this condition.

**Comment by gares** [comment]
Yes it is fixable at the cost of making the code a bit more convoluted.

I agree about the better guard.

@Janno I'm not so sure I get your suggestion. The pipe signals when the type expected by the context of the entire term has to be used.

**Comment by JasonGross** [comment]
I think it might be useful to have an option that automatically sets this point to after the final dependent argument.  (Also, it might make sense to someday flip the argument order of eliminators.)

**Comment by Janno** [comment]
> @Janno I'm not so sure I get your suggestion. The pipe signals when the type expected by the context of the entire term has to be used.

Ah, I think I misunderstood the PR then. Sorry for the noise.

**Comment by Janno** [comment]
Okay, I will add a bit more noise to be sorry for at some later time:

Is there any chance that this machinery can be used to fix https://github.com/coq/coq/issues/5767? I am a bit too tired to figure out how this differs from Ralf's bug that prompted this PR but I had always assumed these two bugs to be equivalent. Sadly they are not, seeing how mine is not fixed by this PR. (I tried with all possible locations for `&`..)

Are these problems unrelated?

**Comment by maximedenes** [comment]
@Janno thanks for mentioning it! This PR also fixes #5767. You can try it with:

```coq
Arguments base {A} m a & _.
Arguments tele {A} m {X} & _.
```

**Comment by Janno** [comment]
I am extremely baffled by this and I don't understand how annotations for base and tele can fix the issue but I will gladly take this solution! :)

**Comment by maximedenes** [comment]
> Yes it is fixable at the cost of making the code a bit more convoluted.

@gares can you describe the fix you have in mind?

**Comment by gares** [comment]
We have to document the feature anyway, so let's start here.

The user writes `f _ b` when `f : forall u, W u -> R u` with `Arguments f _ & _`. The system elaborates `f ?1 ?2` (yes, `b` was put aside and replaced by evar ?2) against an expected type, say `R a`. Given that `f ?1 ?2 : R ?1` the elaborator fixes `?1 = a` by unifying `R a = R ?1`. Now it goes back to the arguments after the `&`: when `b` is elaborated, its expected type is now `W a` instead of `W ?1` since `a` was read from the context, rather than inferred from (the type of) `b`. The difference is that sometimes `W` is a type constructor that recurse on its argument in order to generate a type that actually matches the one of `b`. This is the case for in the example of Ralf.

This feature is a generalization of the one presented in https://arxiv.org/abs/1202.4905 section 4.1. Example 4.5 has a little bug, but the final solution is correct. In that example the type constructor is not recursive, but higher order. Eg `ex_intro ?T ?P ?x p : ex nat (fun x => x > 0)`. Given `p : 2 > 0`, if one type checks the application ignoring the expected type he has to solve the unification problem `?P ?x = 2 > 0` that is very hard. If one says `Arguments ex_intro _ _ & _ _` then he has to solve `(fun x => x > 0) ?x = 2 > 0` that, once the LHS is reduced, it is just first order unification.

**Comment by gares** [comment]
> @gares can you describe the fix you have in mind?

The elaborator returns a term. Given the current code it returns the term where arguments after `&` are (eventually assigned) evars, no matter than the user wrote (the example of gaetan passes explicitly a term that is also read from the context). When processing the arguments after `&`, you could put them back in place, instead of just ensuring they unify. It is not trivial since the original evar could have been casted using a coercion, etc... so it may not be easy to find. If you recall, this was what the first implementation draft was doing, then we opted for the simpler one currently implemented. This is why I've mixed feelings about that request, that is reasonable, but complicates so much the code...

**Comment by SkySkimmer** [comment]
IIUC we expect the common case to have the remaining arguments be non-dependent, then they should be left alone by the unification/coercion (unless we get into some TC/CS issue?) and will be filled by the user given value.

**Comment by maximedenes** [comment]
> This is why I've mixed feelings about that request, that is reasonable, but complicates so much the code...
> I also don't know if it is a problem in practice.

IIRC we even concluded we didn't know how to do it.



> IIUC we expect the common case to have the remaining arguments be non-dependent, then they should be left alone by the unification/coercion (unless we get into some TC/CS issue?) and will be filled by the user given value.

Yes, but the application itself could have been changed (like a coercion to `Funclass` inserted), so just knowning *where* to look for the elaborated remaining arguments is not easy.

Coming back to the example, isn't expected after all that bidirectionality annotations give priority to typing info from the expected type? It's not that arguments are discarded, if they don't unify an error will be triggered.

**Comment by SkySkimmer** [comment]
>Yes, but the application itself could have been changed (like a coercion to Funclass inserted), so just knowning where to look for the elaborated remaining arguments is not easy.

I mean in this case the extra evars won't be touched so the final unification will define them using the user value without having to look at the application.

**Comment by gares** [comment]
Just to try to converge. The blocking issues are:
- libstack
- doc

File: CHANGES.md [hunk 6]
```diff
@@ -9,6 +9,11 @@ Unreleased changes
 
 **Specification language, type inference**
 
+- New annotation in `Arguments` for bidirectionality hints: it is now possible
+  to tell type inference to use type information from the context once the `n`
+  first arguments of an application are known. The syntax is:
+  `Arguments foo x y | z`.
```
Comment (RalfJung) [inline CHANGES.md]: Looks like it actually is `&`? (The initial comment in the PR is also wrong.)

**Comment by Janno** [comment]
@gares thank you very much for this explanation and the reference to your paper!

**Comment by gares** [comment]
@maximedenes can we get an updated on this? I know there are several PR that clean up code touched by this PR, but while this one seems kind of ready the cleanups are not. Can the order of the PRs be switched?

**Comment by maximedenes** [comment]
> can we get an updated on this? I know there are several PR that clean up code touched by this PR, but while this one seems kind of ready the cleanups are not. Can the order of the PRs be switched?

As I told you yesterday offline, I started documenting it. I fixed other problems (missing libobject etc), but didn't push yet.

**Comment by maximedenes** [comment]
Rebased, libobject and documentation added.

File: vernac/vernacentries.ml [hunk 7]
```diff
@@ -1428,10 +1466,22 @@ let vernac_arguments ~section_local reference args more_implicits nargs_for_red
...
+  if bidi_hint_specified then begin
+    let n = Option.get nargs_before_bidi in
+    if section_local then
+      Pretyping.add_bidirectionality_hint sr n
+    else
+      Lib.add_anonymous_leaf (inBidiHints (sr, n))
+    end;
+
+  if clear_bidi_hint then
+    Pretyping.clear_bidirectionality_hint sr;
```
Comment (SkySkimmer) [inline vernac/vernacentries.ml]: What about when we're not `section_local`?

**Review by SkySkimmer — CHANGES_REQUESTED** [review]

File: vernac/vernacentries.ml (hunk 7 above)
Comment (maximedenes) [reply vernac/vernacentries.ml]: Oh, right, I completely forgot to also port this. Will do, thanks!

Comment (maximedenes) [reply vernac/vernacentries.ml]: Done.

**Review by SkySkimmer — APPROVED** [review]

**Review by gares — APPROVED** [review]

**Comment by maximedenes** [comment]
@gares This seems ready to go.
