### PR TITLE
[zify] use the current injection to guide the transformation.

### LINKED ISSUE #17983: `zify` proves `False` by building ill-typed terms
```coq
From Coq Require Import Zify ZifyUint63 ZifySint63 Sint63 Uint63 ZArith Lia.

Lemma boom : False.
Proof.
  assert (sint_bad : forall y z : int, Sint63.to_Z (y / z) = Uint63.to_Z (y / z)).
  { zify; reflexivity. }
  specialize (sint_bad (-1)%sint63 1%uint63).
  vm_compute in sint_bad. (* sint_bad : (-1)%Z = 9223372036854775807%Z *)
  congruence.
Qed.
(* Error: Illegal application:
The term "ZifyClasses.mkapp" of type
 "forall (S1 S2 T1 T2 : Type) (OP : S1 -> S2) (I1 : S1 -> T1) (I2 : S2 -> T2)
    (TUOP : T1 -> T2),
  (forall n : S1, I2 (OP n) = TUOP (I1 n)) ->
  forall (s1 : S1) (t1 : T1), I1 s1 = t1 -> I2 (OP s1) = TUOP t1"
cannot be applied to the terms
 "int" : "Set"
 "Z" : "Set"
 "Z" : "Set"
 "Z" : "Set"
 "Sint63.to_Z" : "int -> Z"
 "Sint63.to_Z" : "int -> Z"
 "fun x : Z => x" : "Z -> Z"
 "fun x : Z => x" : "Z -> Z"
 "fun x : int => eq_refl"
   : "forall x : int, ZifyClasses.inj (Sint63.to_Z x) = ZifyClasses.inj (Sint63.to_Z x)"
 "(y / z)%uint63" : "int"
 "(φ (y)%uint63 / φ (z)%uint63)%Z" : "Z"
 "ZifyClasses.mkapp2 int int int Z Z Z div to_Z to_Z to_Z Z.div div_spec y φ
    (y)%uint63 eq_refl z φ (z)%uint63 eq_refl"
   : "to_Z (y / z) = (φ (y)%uint63 / φ (z)%uint63)%Z"
The 12th term has type "to_Z (y / z) = (φ (y)%uint63 / φ (z)%uint63)%Z"
which should be a subtype of "Sint63.to_Z (y / z) = (φ (y)%uint63 / φ (z)%uint63)%Z".
*)
```

### PR DESCRIPTION
**Pull request by fajb**
This avoids generated ill-typed terms when there are several possible injections for the same operator.
Fixes #17983 

- [x] Added / updated **test-suite**.

### CODE REVIEW

File: plugins/micromega/zify.ml [hunk 1]
```diff
@@ -1005,8 +1017,19 @@ type typed_constr = {constr : EConstr.t; typ : EConstr.t; inj : EInjT.t}
...
+      | []  -> assert false
+      | [e] -> (e,false)
+      | e::_ -> (e,true) in
+    match i with
+    | InjTyp i ->
+       if b then
+         Feedback.msg_warning
+           Pp.(str "Multiple injections for "++
+                 pr_constr env evd t ++ str ". Picking " ++
+                 pr_constr env evd i.decl ++ str".");
```
Comment (JasonGross) [inline plugins/micromega/zify.ml:1031]: Can we give this warning a category and make it silencable?

Comment (fajb) [reply plugins/micromega/zify.ml:1031]: > Can we give this warning a category and make it silencable (and also able to be turned into an error)?

I noticed that this is actually dead code. I have removed it completely.

**Comment by fajb** [comment]
@coqbot: run full CI

**Comment by fajb** [comment]
ping @coq/micromega-maintainers . What do you think?

**Comment by silene** [comment]
@coqbot run full ci

**Review by silene — APPROVED** [review]

**Comment by silene** [comment]
@coqbot merge now

**Comment by silene** [comment]
@coqbot merge now
