### PR TITLE
Fixes #18920: anomaly with evars turned into obligations in binders of Program Fixpoint measure/wf

### LINKED ISSUE #18920: Anomaly with obligations in the binders of a measure-based Program Fixpoint (some evars leaks when turning evars into obligations)
### Description of the problem

When a `Program Fixpoint` with `measure` or `wf` has more than 2 arguments, an auxiliary `_func` function is used. The retrieval of obligations from existential variables apply only to the type and body of the auxiliary function. When building the main constant from the auxiliary `_func`, a different context of binders is used whose existential variables have not been replaced by obligations (and they cannot directly be replaced because the name of the obligation constant is not yet known).

Several conventions are possible to pass the variables. For instance:
- an updated sigma whose relevant evars are replaced by obligation constant names is returned when the obligations are completed
- the `evmap` function returned by `retrieve_obligations` is used to turn the existential variables of the different context of binders into obligation constant names (anticipating the name they would have when the obligations are completed)

### Small Coq file to reproduce the bug

```coq
Require Import Program.
Program Fixpoint f (A : nat * _) (n:nat) {measure n} : nat :=
    match n with 0 => 0 | S n => f A n end.
Next Obligation. exact nat. Defined.
Next Obligation. Admitted.
(* Anomaly "in econstr: grounding a non evar-free term" *)
```

### Version of Coq where this bug occurs

at least from 8.2 but not always with the same error

### Last version of Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by herbelin**
We simply apply the evar->var and var->const maps provided by retrieve_obligations and the declare's hook.

Fixes / closes #18920 

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

File: vernac/comProgramFixpoint.ml [hunk 1]
```diff
@@ -160,48 +162,52 @@ let build_wellfounded pm (recname,pl,bl,arityc,body) ?scope ?clearbody poly ?typ
...
+              | Polymorphic_entry uctx -> UVars.UContext.instance uctx
+              | Monomorphic_entry _ -> UVars.Instance.empty) in
+          Constr.mkRef (dref, inst) in
+        let body = Term.it_mkLambda_or_LetIn (Constr.mkApp (h_body, [|make|])) binders_rel in
         (*FIXME poly? *)
-        let sigma = Evd.from_ctx uctx in
-        let ce = definition_entry ~types:ty ~univs (EConstr.to_constr sigma body) in
+        let ty = Term.it_mkProd_or_LetIn top_arity binders_rel in
+        let ce = definition_entry ~types:ty ~univs body in
         (* FIXME: include locality *)
```
Comment (SkySkimmer) [inline vernac/comProgramFixpoint.ml:191]: I think this comment has been outdated since 5cbcc8fd761df0779f6202fef935f07cfef8a228 (2016)

Comment (SkySkimmer) [reply vernac/comProgramFixpoint.ml:191]: https://github.com/coq/coq/pull/18987

**Review by SkySkimmer — APPROVED** [review]

File: vernac/comProgramFixpoint.ml [hunk 2]
```diff
@@ -160,48 +162,52 @@ let build_wellfounded pm (recname,pl,bl,arityc,body) ?scope ?clearbody poly ?typ
...
+  let evars, (_, evmap), evars_def, evars_typ =
+    RetrieveObl.retrieve_obligations env recname_func sigma 0 def typ
+  in
+  let hook =
+    if List.length binders_rel > 1 then
+      let hook { Declare.Hook.S.dref; uctx; obls; _ } =
+        let update c = CVars.replace_vars obls (evmap mkVar (Evarutil.nf_evar (Evd.from_ctx uctx) c)) in
+        let make = update make in
+        let top_arity = update top_arity in
+        let binders_rel = Context.Rel.map_het update binders_rel in
```
[the remark this answers is not in the document]
Comment (SkySkimmer) [reply vernac/comProgramFixpoint.ml:180]: (I'm putting needs:progress because needs:rebase may get automatically removed)

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot merge npw

**Comment by SkySkimmer** [comment]
@coqbot merge now
