### PR TITLE
Capture primitives by ssr-patterns in proofs

### LINKED ISSUE #12770: Int63 numbers are not captured by patterns in proofs
#### Description of the problem

Trying to capture an Int63 number X in a proof using a pattern fails with `Error: term X does not match any subterm in the goal`.

Example:

`Require Import Int63 ssreflect ssrfun ssrbool.`

`Lemma test : 43%int63 = (42 + 1)%int63.`
`Proof. set X := 43%int63. (* does not capture int63 *)`

#### Coq Version
Coq 8.11.2

### PR DESCRIPTION
**Pull request by JuanCoRo**
Fixes / closes #12770

- [x] Added / updated test-suite

### CODE REVIEW

**Review by gares — APPROVED** [review]
Amazing, thanks!

**Comment by gares** [comment]
You may want to add a changelog entry, saying that SSR patterns now work with primitive values such as ...
There is a script in dev/tools/ to create a template for you.

**Comment by gares** [comment]
bedrock2 failure is unrelated, please ignore

**Comment by JuanCoRo** [comment]
Added the changelog entry!

File: plugins/ssrmatching/ssrmatching.ml [hunk 1]
```diff
@@ -336,7 +336,7 @@ let proj_nparams c =
   with Not_found -> 0
 
 let isRigid c = match kind c with
-  | Prod _ | Sort _ | Lambda _ | Case _ | Fix _ | CoFix _ -> true
+  | Prod _ | Sort _ | Lambda _ | Case _ | Fix _ | CoFix _ | Int _ | Float _ | Array _ -> true
   | _ -> false
```
Comment (proux01) [inline plugins/ssrmatching/ssrmatching.ml:340]: You may want to take the opportunity to remove that catch all pattern, so that the bug doesn't happen again if another primitive type get added in the future.

Comment (gares) [reply plugins/ssrmatching/ssrmatching.ml:340]: This is a good advice. @Juancoro if you don't mind following it... Otherwise, if you don't have time, I can merge it as is and leave it as a further improvement.

Comment (JuanCoRo) [reply plugins/ssrmatching/ssrmatching.ml:340]: Sure! I'll do it right away. Thanks for the advice!

Comment (JuanCoRo) [reply plugins/ssrmatching/ssrmatching.ml]: Done!

Comment (proux01) [reply plugins/ssrmatching/ssrmatching.ml]: Thanks!
(not sure it is worth protecting against a change of arity of some constructors (`Evar (_, _)` instead of `Evar _` for instance), but why not)

**Comment by gares** [comment]
@coqbot merge now

File: plugins/ssrmatching/ssrmatching.ml (hunk 1 above)
Comment (JuanCoRo) [reply plugins/ssrmatching/ssrmatching.ml]: If you think it's better to have a wildcard instead of the arity I've no problem in changing it. Just tell me to which constructors does this apply (or rather, if it makes sense to have the arity at all) and I'll happily change it!

Comment (JuanCoRo) [reply plugins/ssrmatching/ssrmatching.ml]: It just got merged! Never mind then :smile: 
Thanks to the both of you for your suggestions!

Comment (proux01) [reply plugins/ssrmatching/ssrmatching.ml]: It's fine, I was just putting this side note in case you'd like to save a few characters next time ;-)
