### PR TITLE
CoqIDE: accept to open files with invalid names

### LINKED ISSUE #10988: CoqIDE still crash when opening some files whose name is not a valid identifier.
#### Description of the problem

If I open a file named `foo-bar.txt`, or `foo-bar.v`, CoqIDE crashes and leaves a message:

> Invalid character '-' in identifier "foo-bar".

When the file does not have any extension however, CoqIDE does not load the file but does not crash. It briefly displays the message:

>Load failed: Invalid_argument("Filename.chop_extension")

#### Coq Version

8.10-8.11 (regression from 8.9)

This shows that the fix in #10557 was actually incomplete.

### PR DESCRIPTION
**Pull request by vbgl**
How to close CoqIDE? Use the “File → Open” menu and select a file name which is not a valid identifier.

This PR fixes this unexpected behavior by removing a call to “exit”.

Fixes: #10988.

TODO:
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

File: ide/coqide/coqide.ml [hunk 1]
```diff
@@ -89,36 +89,21 @@ let make_coqtop_args fname =
...
-    | None -> args
-    | Some fname ->
-      if List.exists (String.equal "-top") args then args
-      else
-        (* We basically copy the code of Names.check_valid since it is not exported *)
-        (* to coqide. This is to prevent a possible failure of parsing  "-topfile"  *)
-        (* at initialization of coqtop (see #10286) *)
-        match Unicode.ident_refutation (Filename.chop_extension (Filename.basename fname)) with
-        | Some (_,x) -> output_string stderr (x^"\n"); exit 1
-        | None -> "-topfile"::fname::args
```
Comment (SkySkimmer) [inline ide/coqide/coqide.ml:119]: Doesn't this mean it stops passing -topfile? instead you could just ignore the error ie
~~~
        | Some (_,x) -> args
        | None -> "-topfile"::fname::args
~~~

Comment (vbgl) [reply ide/coqide/coqide.ml]: You’re right. Thanks.

**Review by MSoegtropIMC — APPROVED** [review]
LGTM
