### PR TITLE
[mltop] Store digest of modules used to compile files.

### LINKED ISSUE #10874: [dune] Digest-based builds need transitive dependency computation of ML plugin deps
**edit**: it seems `.vo` files do store the checksum of linked `.vo` files, so the above problem doesn't hold for the pure-`.vo` fragment, however that's still a problem for ML plugins.

As noted by @mattam82 on Gitter, the current dune-based build system doesn't always correctly rebuild target `.vo` files. This is mainly due to `Exports` and transitive side effects, in a sense, Coq's require is similar to linking, so when requiring library `A` we must also take into account the libraries and plugins library `A` is exporting.

**edit**: it seems `.vo` files do store checksums of imported `.vo` files so we should be safe in the `.vo` fragment, however that's still a problem w.r.t. plugins.

For example, if we have libraries `A` `B`, and `C`, with `B` exporting `A` and `C` requiring `B`, `coqdep` will only reflect the dependency of `C` on `B`, however, it does implicitly depend on `A` too. It could be the case that `A` does change, however `B`'s digest is the same, but changes in `A` should force a rebuild on `C`; right now we will incorrectly skip rebuilding `C`, as the implicit dependency on `A` is not taken into account.

A similar situation arises for plugins.

This seems like a hard problem to solve, we need to think about what the right approach here is.

Should we take into account in the transitive dep closure only modules that are under `Export`? Or can purely `Require`d modules also produce transitive implicit consistency invalidation.

What do you think @maximedenes ?

### PR DESCRIPTION
**Pull request by ejgallego**
This should allow digest-based builds to work correctly.

Fixes #10874

For now, we store the digest of the module selected, this means that
vo files loading modules will have different digests depending on
whether the `native` or `byte` version was used.

If that is a problem we can improve this tho; for example we could
disable the digest in those cases.

The code could be better, and indeed `Mltop` could enjoy a nice
cleanup, I will likely do some when I add support for `Fl_dynload`.

### CODE REVIEW

File: vernac/mltop.ml [hunk 1]
```diff
@@ -334,23 +333,38 @@ let _ =
 
 (* Liboject entries of declared ML Modules *)
 
+(* Digest of module used to compile the file *)
+type ml_module_digest =
+  | None
```
Comment (SkySkimmer) [inline vernac/mltop.ml]: This is going to be a pain if we use options in this file, either disable warning 40 or rename this constructor

**Comment by maximedenes** [comment]
> vo files loading modules will have different digests depending on
> whether the `native` or `byte` version was used.

Does it mean that `.vo` files are no longer portable?

File: vernac/mltop.ml [hunk 2]
```diff
@@ -334,23 +333,38 @@ let _ =
...
 
+(* Digest of module used to compile the file *)
+type ml_module_digest =
+  | NoDigest
+  | AnyDigest of Digest.t             (* digest of any used cma / cmxa *)
+
 type ml_module_object = {
   mlocal : Vernacexpr.locality_flag;
-  mnames : string list
+  mnames : (string * ml_module_digest) list
```
Comment (maximedenes) [inline vernac/mltop.ml]: The name of this field is now wrong.

File: vernac/mltop.ml [hunk 3]
```diff
@@ -334,23 +333,38 @@ let _ =
 
 (* Liboject entries of declared ML Modules *)
 
+(* Digest of module used to compile the file *)
+type ml_module_digest =
```
Comment (maximedenes) [inline vernac/mltop.ml]: Why not use an `option` type?

File: vernac/mltop.ml [hunk 4]
```diff
@@ -334,23 +333,38 @@ let _ =
...
+  mnames : (string * ml_module_digest) list
 }
 
+let add_module_digest m =
+  try
+    let file = file_of_name m in
+    let path, file = System.where_in_path ~warn:false !coq_mlpath_copy file in
+    m, AnyDigest (Digest.file file)
+  with
+  | Not_found ->
```
Comment (maximedenes) [inline vernac/mltop.ml]: In what kind of scenarios do we expect the file to be missing, but `trigger_ml_object` to succeed?

**Comment by SkySkimmer** [comment]
>Does it mean that .vo files are no longer portable?

It's not used by anything so no.

File: vernac/mltop.ml (hunk 2 above)
Comment (ejgallego) [reply vernac/mltop.ml]: I didn't want to change it to minimize diff noise, but if you think it is worth it I'll tweak.

Comment (SkySkimmer) [reply vernac/mltop.ml]: Maybe we should just have an extra field `mdigests : digest list`?

File: vernac/mltop.ml (hunk 3 above)
Comment (ejgallego) [reply vernac/mltop.ml]: This could also contain native/byte dependent digest so I'd like it to be extensible; also, I find most option types in Coq hard to read.

File: vernac/mltop.ml (hunk 4 above)
Comment (ejgallego) [reply vernac/mltop.ml]: A wrong `Declare Module` for example; this shouldn't produce not found. As I mentioned in the pull request we could refactor this to be better but I'll involve some more cleanups.

Also, there is the scenario that could be controlled by a flag to request the digests not to be stored; for whatever the reasons. Hard to know yet what kind of impact this has.

**Comment by ejgallego** [comment]
> Does it mean that `.vo` files are no longer portable?

Note that I am not sure they are already portable due to hashes and the way Marshall is used. What kind of portability you have in mind?

In jsCoq we managed to make them "portable" but it was a very big hack [so OSX users can compile with a 64bit Coq but then execute on a 32bit runtime like the one of js_of_ocaml]

This patch should not matter for portability concerns as the digest is not checked; as @SkySkimmer just noted. This is intended to help digest-based builds so I don't see the need to add the check, but indeed "safer" modes could actually check the digest I guess.

**Comment by ppedrot** [comment]
So far, vo files were portable across architectures as long as they had the same word size, for instance OCaml marshalling even tries to be endianness-agnostic.

This may be bad for reproducibility though. Furthermore, I am slightly concerned about the (ab)use of recompilation sharing that I was able to perform sometimes, i.e. not having to recompile a whole dev when tweaking a plugin that was not changing the API.

**Comment by ejgallego** [comment]
> This may be bad for reproducibility though.

How so? Digests are deterministic TTBOMK.

> I am slightly concerned about the (ab)use of recompilation sharing that I was able to perform sometimes, i.e. not having to recompile a whole dev when tweaking a plugin that was not changing the API.

I think that is fairly orthogonal to this PR, in the sense that if we don't store the checksum then the build system will have to compute the transitive plugin dependencies to regain soundness, so it will rebuild anyways.

Moreover, to do that you'd have to abuse already the make-based system as it doesn't support by default that kind of workflow as the updated plugin will have a different m-time.

Cutoffs may appear in dune soon tho (c.f. https://github.com/ocaml/dune/issues/1523)

**Comment by ppedrot** [comment]
> How so? Digests are deterministic TTBOMK.

Well, now we rely on OCaml compilation being reproductible. It was already quite tricky to enforce that in Coq (and indeed it was not the case), but now we're pulling in a much bigger hypothesis.

File: vernac/mltop.ml (hunk 2 above)
Comment (ejgallego) [reply vernac/mltop.ml]: Seems rather the module info should go in a single list, unless you want to deprecate the capability of multi-load of `Declare ML Module`.

**Comment by ejgallego** [comment]
> Well, now we rely on OCaml compilation being reproductible. It was already quite tricky to enforce that in Coq (and indeed it was not the case), but now we're pulling in a much bigger hypothesis.

If OCaml compilation is not reproducible then very hardly you are gonna have a reproducible Coq build as `coqc` itself will vary then, so the hypothesis was already there.

Anyways the digest is optional so it could be disabled if needed by an env var, etc...

**Comment by ejgallego** [comment]
Anyone willing to assign this?

**Comment by ejgallego** [comment]
> Anyone willing to assign this?

? Maybe @SkySkimmer ?

**Review by SkySkimmer — APPROVED** [review]
Seems OK, will merge tomorrow to give time for complaints

**Comment by ejgallego** [comment]
I plan to address some of the comments in a future refactoring, but it is way more invasive than the scope of this PR.

File: vernac/mltop.ml (hunk 4 above)
Comment (herbelin) [reply vernac/mltop.ml:352]: Hi, I fell on a situation where `add_module_digest` fails, it is when configured with `-natdynlink no`. I'm not about what is the right fix but the following e.g. works:
```
let add_module_digest m =                                                              
  if module_is_known m then                                                            
    m, NoDigest                                                                        
  else                                                                                 
  try                                                                                  
    let file = file_of_name m in                                                       
    let path, file = System.where_in_path ~warn:false !coq_mlpath_copy file in         
    m, AnyDigest (Digest.file file)                                                    
  with                                                                                 
  | Not_found ->                                                                       
    m, NoDigest   
```
