### PR TITLE
make critical sections safe in the presence of exceptions

### LINKED ISSUE #13949: Mutex deadlock when timeout SIGALRM signals fire.
#### Description of the problem

Steps to reproduce:
```
Ltac loop t := case t; loop t.
Lemma test (P : Prop) (b : bool) : P.
do 1000 ((timeout 1 loop b) || idtac "hi").
Qed.
```
Run this in `coqc` on master. After 5 to 10 minutes the `coqc` process will enter a Sleeping state and never exit. Tail of the `strace` log:
```
getitimer(ITIMER_REAL, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}) = 0
setitimer(ITIMER_REAL, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}) = 0
rt_sigaction(SIGALRM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fdea5efc960}, {sa_handler=0x55be595567b0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fdea5efc960}, 8) = 0
write(1, "hi\n", 3hi
)                     = 3
getitimer(ITIMER_REAL, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}) = 0
rt_sigaction(SIGALRM, {sa_handler=0x55be595567b0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fdea5efc960}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fdea5efc960}, 8) = 0
setitimer(ITIMER_REAL, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=1, tv_usec=0}}, {it_interval={tv_sec=0, tv_usec=0}, it_value={tv_sec=0, tv_usec=0}}) = 0
futex(0x55be5b56d450, FUTEX_WAIT_PRIVATE, 2, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
futex(0x55be5b56d450, FUTEX_WAIT_PRIVATE, 2, NULL
```
From the logs, it is clear that multiple threads are waiting on the same mutex. We have confirmed that this is a logic error in Coq by testing it on @ejgallego's simple_compiler branch: https://github.com/ejgallego/coq/commits/simple_compiler. The problem can be reproduced in commit https://github.com/ejgallego/coq/commit/2e0b53c5481534251651e6ef84a78043381fbd75, but dissapears in commit https://github.com/ejgallego/coq/commit/b155c69ee4781986979a8ec3f70bf05d6873343c where all usages of the Thread library have been removed.

The code that looks most suspicous to me are the mutexes in `exinfo.ml`.

See also the discussion here: https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Deadlock.20in.20OCaml.20runtime

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
This ensures that exceptions thrown by signals will not leave the system in a
deadlocked state.

See #13951 and #13949 and https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Deadlock.20in.20OCaml.20runtime for discussions.

**Kind:** bug fix

Fixes / closes #13949

- [ ] Entry added in the changelog

### CODE REVIEW

File: clib/cThread.ml [hunk 1]
```diff
@@ -107,3 +107,18 @@ let mask_sigalrm f x =
...
+  Critical sections :
+   - Mutex.lock does not poll on leaving the blocking section
+     since 4.12.
+   - Never inline, to avoid theoretically-possible reorderings with
+     flambda.
+     (workaround to the lack of masking)
+*)
+let[@inline never] with_lock m ~scope =
+  let () = Mutex.lock m (* BEGIN ATOMIC *) in
+  match (* END ATOMIC *) scope () with
```
Comment (gares) [inline clib/cThread.ml:122]: Given you want to be that precise, can you put this in administrative normal form (hoist the `scope ()` value)?
I don't know what your comment means otherwise (without already knowing it).

Comment (gares) [reply clib/cThread.ml:122]: I mean
```
  match
    (*here*)
    let res = scope () in
   (* or here *)
    res
  with
```

Comment (gares) [reply clib/cThread.ml:122]: (I admit I'm not a super expert, but if the comment does not help me, I'm unsure it will help many readers out there)

Comment (LasseBlaauwbroek) [reply clib/cThread.ml:122]: Yeah, I´m also not exactly sure what these comments mean (@gadmm  wrote them). Maybe he can comment on what they indicate exactly?

Comment (gadmm) [reply clib/cThread.ml:122]: It is true that it is not entirely precise; the beginning of the atomic scope is inside the C function that defines Mutex.lock. Would it be fine to simply remove the comments?

Comment (gares) [reply clib/cThread.ml:122]: yes

Comment (ejgallego) [reply clib/cThread.ml:122]: I like the comments tho, I got their purpose and they are useful.

**Review by ejgallego — APPROVED** [review]
LGTM, shouldn't introduce more problems than the ones already existing.

(I don't have a strong opinion w.r.t. comments, personally I like them)

**Comment by ejgallego** [comment]
Not sure the title of the PR / commit is the best one tho; maybe should be more in the line of "make critical sections safe in the presence of exceptions"

File: clib/cThread.ml [hunk 2]
```diff
@@ -107,3 +107,18 @@ let mask_sigalrm f x =
...
+  | (* BEGIN ATOMIC *) x -> Mutex.unlock m ; (* END ATOMIC *) x
+  | (* BEGIN ATOMIC *) exception e -> Mutex.unlock m ; (* END ATOMIC *) raise e
```
Comment (SkySkimmer) [inline clib/cThread.ml:124]: No exninfo?

File: clib/cThread.ml (hunk 1 above)
Comment (gares) [inline clib/cThread.ml:122]:
```suggestion
  let () = Mutex.lock m (* BEGIN ATOMIC : exit from C code of lock *) in
  match (* END ATOMIC : exit from C code setting exception handler*)
    scope ()
  with
```
(assuming I got it right)

File: clib/cThread.ml (hunk 2 above)
Comment (gadmm) [reply clib/cThread.ml:124]: You do not need to reattach the exninfo when re-raising pointers do you? The info is still in the store. Anyway this would lead to a circularity since you want this combinator to protect `Exninfo.iraise`.

File: clib/cThread.ml (hunk 1 above)
Comment (gadmm) [reply clib/cThread.ml:122]: I am not sure to understand these precisions or how precise you want it. The beginning of the atomic operation is the acquisition of the (system) resource (here when the posix lock call returns in the C function). The end of the atomic operation is the initialisation of the (semantic) resource (so here setting up the exception handler).

**Comment by gadmm** [comment]
- Note the comment about OCaml 4.12: this is still incorrect with earlier OCaml versions. However, even then this still greatly reduces the probability of getting the bug.
- If any of the affected code is meant to run in bytecode, then there is a minor complexification to do (I do not think this is the case but I prefer to warn).

File: clib/cThread.ml (hunk 2 above)
Comment (ejgallego) [reply clib/cThread.ml:124]: Unfortunately you need to re-attach; I'd like to get rid of exninfo and use something like https://github.com/ocaml/dune/blob/main/otherlibs/stdune-unstable/exn_with_backtrace.mli , but we didn't have a lot of agreement last time we discussed.

Comment (gadmm) [reply clib/cThread.ml:124]: I don't understand: this re-raises the same exception with the same backtrace. The store has not changed. What goes wrong?

**Comment by LasseBlaauwbroek** [comment]
> Note the comment about OCaml 4.12: this is still incorrect with earlier OCaml versions.
Yeah that is a shame, but an almost complete fix is better not no fix :-) If I ever encounter the issue I might just upgrade my local Coq to use OCaml 4.12.

> If any of the affected code is meant to run in bytecode, then there is a minor complexification to do
Currently I have no plans to run in bytecode mode, so unless it is really easy to add the complexification I suggest we skip it. But other people might also run into this issue at a later point, so if this is trivial I suggest we just fix it now and be done with it.

File: clib/cThread.ml (hunk 2 above)
Comment (ejgallego) [reply clib/cThread.ml:126]: Indeed IIRC the problem here is that there is not guarantee that the compiler will actually insert `%reraise` here, so if it inserts `raise` the backtrace would be lost? This has changed in OCaml versions, but AFAIU the only way to guarantee that `reraise` will be use is to actually use `reraise e` , not `raise e`, which can be done by declaring it as an external.

**Review by ejgallego — APPROVED** [review]
I'm gonna assume that the `raise` is always a `reraise` [which seems true in recent OCaml] so I think this can be merged. Are you OK @SkySkimmer ?

I'll wait a couple of days in any case.

**Comment by ejgallego** [comment]
> If any of the affected code is meant to run in bytecode, then there is a minor complexification to do (I do not think this is the case but I prefer to warn).

I guess this should be documented, @gadmm , can you suggest what to add as a comment?

**Comment by gadmm** [comment]
> I guess this should be documented, @gadmm , can you suggest what to add as a comment?

If you feel like it might be important one day, it is better to just do the change which is very simple. You need to inline the call to `Mutex.unlock` to avoid polling when calling it in bytecode. That is, you declare
```ocaml
external unlock: t -> unit = "caml_mutex_unlock"
```
and replace `Mutex.unlock` by `unlock`.

**Comment by ejgallego** [comment]
> If you feel like it might be important one day, it is better to just do the change which is very simple. You need to inline the call to `Mutex.unlock` to avoid polling when calling it in bytecode.

Thanks for all the help @gadmm , I am not sure doing this optimization is worth it, but I'd suggest @LasseBlaauwbroek to incorporate your comment before merge so this is properly documented at least.

**Comment by LasseBlaauwbroek** [comment]
I added the inlined `unlock` (just adding it seems easier than describing how this could be done in the future). Somebody should check if this is the intention. I have no idea what I´m doing here :-)

**Comment by gadmm** [comment]
Looks good to me.

**Comment by ejgallego** [comment]
Looks good to me too, thanks to all; will merge soon.

**Comment by ejgallego** [comment]
@coqbot: merge now
