### PR TITLE
Fix an algorithmic issue in the vernac guardedness checker.

### LINKED ISSUE #7286: Guarded relies on non-ground EConstr
Since the merge of #6454, the `Guarded` command is essentially useless, because it relies on term normalization that contain evars, and raises an anomaly as soon as there is an open goal.

```
Goal True.
Guarded.
(** Anomaly "grounding a non evar-free term" *)
```

### PR DESCRIPTION
**Pull request by ppedrot**
Calling the O(n) EConstr.to_constr function at every node is a very bad idea (tm).

EDIT: Fixes #7286.

### CODE REVIEW

File: pretyping/inductiveops.ml [hunk 1]
```diff
@@ -758,8 +758,11 @@ let type_of_projection_knowing_arg env sigma p c ty =
    syntactic conditions *)
 
 let control_only_guard env sigma c =
+  let c = Evarutil.nf_evar sigma c in
   let check_fix_cofix e c =
-    match kind (EConstr.to_constr sigma c) with
+    (** [c] has already been normalized upfront *)
+    let c = EConstr.Unsafe.to_constr c in
```
Comment (ejgallego) [inline pretyping/inductiveops.ml]: Don't we have a safe method to do this?

Comment (ppedrot) [reply pretyping/inductiveops.ml]: As witnessed by #7286, this is hopeless, the argument might contain unresolved evars.

**Review by mattam82 — APPROVED** [review]
Looks good. I believe using the to_constr there is better than rewriting everything with Constr.

File: pretyping/inductiveops.ml [hunk 2]
```diff
@@ -758,8 +758,11 @@ let type_of_projection_knowing_arg env sigma p c ty =
    syntactic conditions *)
 
 let control_only_guard env sigma c =
+  let c = Evarutil.nf_evar sigma c in
```
Comment (SkySkimmer) [inline pretyping/inductiveops.ml]: Why don't we just to_constr here?

Comment (ppedrot) [reply pretyping/inductiveops.ml]: Because the types do not agree. There is no `iter_full_binder` for kernel terms...

Comment (SkySkimmer) [reply pretyping/inductiveops.ml]: So add it.

Comment (SkySkimmer) [reply pretyping/inductiveops.ml]: In fact it used to be on kernel terms until the commit which introduced this issue.

Comment (ejgallego) [reply pretyping/inductiveops.ml]: Indeed this is what I was going to say, the origin of this problem was a try not to duplicate that function; it is clear now that the motivation was ill-founded so we are bound to duplication.

**Comment by ejgallego** [comment]
Add a test case for #7555 #7286

File: pretyping/inductiveops.ml (hunk 2 above)
Comment (ppedrot) [reply pretyping/inductiveops.ml]: There are no `full_binders` functions in the kernel, I am not really willing to introduce just that one function there. Either we are uniform and provide this variant for all functions or we keep it for EConstr. Such functions are not required by the kernel so I'd advocate against kernel code inflation.

Comment (maximedenes) [reply pretyping/inductiveops.ml]: I don't understand this. Why would such combinators be needed on `econstr` but not `constr`? Kernel code inflation is irrelevant here IMHO, the code is generic, doesn't increase the complexity for bugs, and is low risk if tested properly.

Comment (ppedrot) [reply pretyping/inductiveops.ml]: I am fine with adding it, but then we need all such functions, not just `iter`.

Comment (maximedenes) [reply pretyping/inductiveops.ml]: I agree, but that's certainly not an argument for not adding one ;)

**Comment by gares** [comment]
What is the vernacular guardedness checker?

File: pretyping/inductiveops.ml (hunk 2 above)
Comment (ppedrot) [reply pretyping/inductiveops.ml]: OK, so it turns out it is harder than I thought. In order to implement the `full_binder` variants you need term lifting. But the latter is only defined in `Vars` so that the variants cannot be defined in the `Constr` module. What do?

Comment (SkySkimmer) [reply pretyping/inductiveops.ml]: Define it in vars, or move lifting to constr
Or have a module outside the kernel for stuff on constr that the kernel doesn't use.

Comment (ppedrot) [reply pretyping/inductiveops.ml]: Guys, this is really starting to be very complex for a simple fix that is 3-line patch...

Comment (ejgallego) [reply pretyping/inductiveops.ml]: Well, indeed; but on the other hand this is highligthing serious issues with the API; given that the fix seems far from "critical" we can take some time to discuss what'd be the proper way to address this.

**Comment by SkySkimmer** [comment]
>What is the vernacular guardedness checker?

`Guarded.`

File: pretyping/inductiveops.ml (hunk 2 above)
Comment (SkySkimmer) [reply pretyping/inductiveops.ml]: >OK, so it turns out it is harder than I thought. In order to implement the full_binder variants you need term lifting. But the latter is only defined in Vars so that the variants cannot be defined in the Constr module. What do?

Actually I don't see where fold_with_full_binders needs term lifting. It needs Context but that was moved before Constr so it's not a problem.

Comment (ppedrot) [reply pretyping/inductiveops.ml]: It needs term lifting to push fixpoint and cofixpoint binders. Look at `Environ.push_rec_types`.

Comment (SkySkimmer) [reply pretyping/inductiveops.ml]: The current code does 
~~~ocaml
  | Fix (_,(lna,tl,bl)) ->
      let n' = CArray.fold_left2 (fun c n t -> g (LocalAssum (n, t)) c) n lna tl in
      let fd = Array.map2 (fun t b -> (t,b)) tl bl in
      Array.fold_left (fun acc (t,b) -> f n' (f n acc t) b) acc fd
~~~
so is it broken?

Comment (ppedrot) [reply pretyping/inductiveops.ml]: Looks like it...

Comment (ppedrot) [reply pretyping/inductiveops.ml]: Interstingly it seems it has been broken since the very beginning, see d9dc86a6f7194c2e7ea704c95495955ca4f4b08d from November 2000 (!).

Comment (SkySkimmer) [reply pretyping/inductiveops.ml]: The annoying part is that IIUC once we have rec-rec fixpoints the lift will go away x_x

Comment (ppedrot) [reply pretyping/inductiveops.ml]: Well, I think we still have time to see that coming.

**Comment by SkySkimmer** [comment]
I'll merge monday afternoon if nobody complains.

**Comment by ejgallego** [comment]
I am not happy to see this in, but it is better than what we have now in master so green light.
