### PR TITLE
Fix pretty-printing of primitive integers

### LINKED ISSUE #9888: Missing scope delimiter when printing primitive integers
#### Description of the problem

Consider the following code:

```coq
Require Import Int63.
Check 2%int63.
2
     : int
(* and if you reparse the output *)
Check 2.
2
     : nat
```

I've just prepared a bug fix for that issue so I'll submit a PR at once.

#### Coq Version

Coq `master` under GNU/Linux

### PR DESCRIPTION
**Pull request by erikmd**
**Kind:** bug fix

Fixes #9888

* A scope delimiter was missing for primitive integers constants.
* Add related regression tests.
* Make the fix "optimal" with respect to the scope environment, see example below.

```coq
Require Import Int63.
Check 2%int63.
2%int63
     : int
Check (2 + 2)%int63.
(2 + 2)%int63
     : int
```

- [x] Added / updated test-suite

### CODE REVIEW

File: interp/constrextern.ml [hunk 1]
```diff
@@ -969,7 +977,8 @@ let rec extern inctx (custom,scopes as allscopes) vars r =
       CCast (sub_extern true scopes vars c,
              map_cast_type (extern_typ scopes vars) c')
   | GInt i ->
-     CPrim(Numeral (Uint63.to_string i,true))
+     extern_prim_token_delimiter_if_required
+       (Numeral (Uint63.to_string i,true)) "int63" "int63_scope" (snd scopes)
```
Comment (JasonGross) [inline interp/constrextern.ml]: Would it be possible to use `Register` to register a scope for printing primitive integers, rather than hard-coding this here?

Comment (erikmd) [reply interp/constrextern.ml]: Hi @JasonGross, The `int63_scope` is indeed registered in `int63_syntax.ml`, but I'm unsure whether the code I proposed in this PR could be inserted in another place… Indeed IINM, this scope is a bit different than, e.g., real_scope, because the primitive integers pretty-printing can't be disabled by doing `Set Printing All` or so… Anyway, I'll be glad to refactor my PR if need be.

@maximedenes WDYT?

Comment (proux01) [reply interp/constrextern.ml]: @JasonGross that would indeed be nice but Register doesn't seem to support scopes currently. I may look into it further but that's definitely beyond the scope (no pun intended) of this PR.

**Comment by erikmd** [comment]
Dear @maximedenes and @herbelin,
as this primitive-integers-related PR has not yet a milestone nor assignee, do you think it could be part of 8.10+beta1?
(BTW I don't know whether there's some dedicated GitHub-based operation I should have done to request this, instead of writing a comment?)

File: interp/constrextern.ml (hunk 1 above)
Comment (maximedenes) [reply interp/constrextern.ml]: I agree it would be nice, but can be done later.

**Review by maximedenes — APPROVED** [review]
LGTM, thanks a lot!
