### PR TITLE
Fix check that fixpoints on SProp inductives produce SProp values

### LINKED ISSUE #18314: Incorrectly accepted sort polymorphic fixpoint on sprop inductive
~~~coq
Section Well_founded.

 Variable A : Type.
 Variable R : A -> A -> Prop.

 Inductive Acc (x: A) : SProp :=
     Acc_intro : (forall y:A, R y x -> Acc y) -> Acc x.

 Lemma Acc_inv : forall x:A, Acc x -> forall y:A, R y x -> Acc y.
  destruct 1; trivial.
 Defined.

 Global Arguments Acc_inv [x] _ [y] _, [x] _ y _.

 Polymorphic Definition Fix_F@{s|u|} (P:A -> Type@{s|u}) (F:forall {x:A}, (forall y:A, R y x -> P y) -> P x)
   := fix Fix_F {x:A} (a:Acc x) {struct a} : P x :=
     F (fun (y:A) (h:R y x) => Fix_F (Acc_inv a h)).

End Well_founded.
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #18314

### CODE REVIEW

File: kernel/inductive.ml [hunk 1]
```diff
@@ -1437,7 +1437,7 @@ let inductive_of_mutfix env ((nvect,bodynum),(names,types,bodies as recdef)) =
        not (Environ.is_type_in_type env (GlobRef.IndRef ind))
     then
       begin
-        if names.(i).Context.binder_relevance == Sorts.Relevant
+        if not (names.(i).Context.binder_relevance == Sorts.Irrelevant)
```
Comment (ppedrot) [inline kernel/inductive.ml:1440]: The curse of adding neutrals to booleans.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
