### PR TITLE
Normalize evars during bytecode compilation.

### LINKED ISSUE #13841: vm_compute no longer reduces in presence of unified evars
Consider the following testcase:
```coq
Goal True.
evar (p : bool).
unify ?p true.
assert (orb p false = true).
vm_compute.
match goal with |- true = _ => idtac end.
(* Error: No matching clause for match. *)
```

Indeed, `vm_compute`  refuses to reduce `match` and `fix` involving this value, thus leaving the goal as `(if true then true else false) = true`.

All the other reduction engines (`lazy`, `cbv`, `native_compute`) properly reduce the goal to `true = true`.

Tactic `eval vm_compute` does not work any better, but strangely enough, `Eval vm_compute` does succeed.

This is a regression. It was introduced at some point between 8.9.1 and 8.11.1.

Note that 8.9.1 has some other bugs of its own:
```coq
Require Import List.
Goal True.
evar (l : list nat).
assert (List.length l = 0).
vm_compute.
apply eq_refl. (* Success?! *)
```

But due to the former bug, I do not know if the later one still exists.

### PR DESCRIPTION
**Pull request by silene**
Otherwise, the interpreter sees already unified evars as accumulators rather than actual constants, thus preventing the computations from progressing.

This was caused by 6b61b63bb8626827708024cbea1312a703a54124, which removed evar normalization. The effect went unnoticed because the computed term is still convertible to the reduced term, except that it is the lazy machinery that ends up reducing it, rather than the bytecode one. So, performances became abysmal, seemingly at random.

**Kind:** bug fix / performance.

Fixes / closes #13841

### CODE REVIEW

File: pretyping/vnorm.ml [hunk 1]
```diff
@@ -416,7 +416,7 @@ let cbv_vm env sigma c t  =
   (* This evar-normalizes terms beforehand *)
   let c = EConstr.to_constr ~abort_on_undefined_evars:false sigma c in
   let t = EConstr.to_constr ~abort_on_undefined_evars:false sigma t in
-  let v = Vmsymtable.val_of_constr env c in
+  let v = Vmsymtable.val_of_constr env (Evd.existential_opt_value0 sigma) c in
```
Comment (ejgallego) [inline pretyping/vnorm.ml:419]: Is the `to_constr` above now necessary?

Comment (silene) [reply pretyping/vnorm.ml:419]: Yes and no. Yes, the term still needs to be normalized. No, `EConstr.Unsafe.to_constr` could be used instead.

So, it is mostly a matter of whether we want to encourage the use of `Unsafe` when it does not improve performances.

Comment (SkySkimmer) [reply pretyping/vnorm.ml:419]: I think we prefer `Unsafe` to `abort_on_undefined_evars:false` here.
Indeed the reason we have to pass `opt_value` is that we do `Unsafe` things, just hidden because the `env` type is shared between the kernel and the econstr interfaces.

Comment (silene) [reply pretyping/vnorm.ml:419]: Good point. Done.

Comment (silene) [reply pretyping/vnorm.ml:419]: So, this breaks things:
```coq
Definition barvm (x := true) := Eval vm_compute in x.
(* Error: The type int must be registered before this construction can be typechecked. *)
```

Any suggestion or should I just go back to using `abort_on_undefined_evars:false`?

Comment (SkySkimmer) [reply pretyping/vnorm.ml:419]:
~~~coq
Definition barvm (t:=_) (x := true : t) := Eval vm_compute in x.
~~~
gets the same error even wth abort_on_undefined_evars (both master and current PR with Unsafe replaced), so IMO we should just fix that bug.
The issue seems to be `construct_of_constr`.

Comment (silene) [reply pretyping/vnorm.ml:419]: Right, I was just reading your comments on #8059. You just saved me the hassle of exhibiting this test case. Thanks.

Comment (silene) [reply pretyping/vnorm.ml:419]: Please double check that I did it correctly. I mindlessly ported your changes from #8059. I do not understand them.

Comment (SkySkimmer) [reply pretyping/vnorm.ml:419]: Looks ok

File: pretyping/vnorm.ml [hunk 2]
```diff
@@ -78,9 +78,9 @@ let type_constructor mind mib u (ctx, typ) params =
 
 
 
-let construct_of_constr const env tag typ =
+let construct_of_constr const env sigma tag typ =
   let (t, allargs) = decompose_appvect (whd_all env typ) in
-  match Constr.kind t with
+  match EConstr.kind_upto sigma t with
```
Comment (SkySkimmer) [inline pretyping/vnorm.ml:83]: actually we should probably be changing the whd_all call too
Let me try to get an example

Comment (SkySkimmer) [reply pretyping/vnorm.ml:83]: `Definition barvm (z:nat) (t:=_ z) (x := true : t) := Eval vm_compute in x.` still failing

Comment (silene) [reply pretyping/vnorm.ml:83]: The native code does
```ocaml
let t = whd_all env c in
let (t, allargs) = try destApp t with DestKO -> (t,[||])
```
Is that the way to go?

Comment (SkySkimmer) [reply pretyping/vnorm.ml:83]: AFAICT no, it needs to be changed to evar-aware whd_all too.
Does the example work with native compute?

Comment (silene) [reply pretyping/vnorm.ml:83]: Right, it fails too.

Comment (silene) [reply pretyping/vnorm.ml:83]: So, `whd_all env sigma`.

What do you make of the `destApp` dance? Do I add it to `vm_compute`? Remove it from `native_compute`? Neither?

Comment (silene) [reply pretyping/vnorm.ml:83]: Sorry, that was a dumb question. It is the same code both sides, just written in a different way.

Comment (SkySkimmer) [reply pretyping/vnorm.ml:83]: decompose_appvect is a nicer way to do the same thing 
Do what you like with it.

Comment (silene) [reply pretyping/vnorm.ml:83]: I am a bit worried by the sheer amount of `whd_all` calls in those files. Do they all need to be converted? Or are some of them correct? (You can also tell me that it does not hurt to convert them all.)

Comment (SkySkimmer) [reply pretyping/vnorm.ml:83]: I don't know.

Comment (silene) [reply pretyping/vnorm.ml:84]: I went for the minimal change. (No idea if there is a more idiomatic way of writing it.) Let us see how it fares.

Comment (SkySkimmer) [reply pretyping/vnorm.ml:84]: We don't need kind_upto as whd_all will handle it btw

Comment (silene) [reply pretyping/vnorm.ml:84]: This is getting ridiculous. File `test-suite/bugs/closed/bug_5096.v`, which is supposed to terminate instantly, now takes 20 seconds.

Comment (silene) [reply pretyping/vnorm.ml:84]: So, if I understand #5096 correctly, we are not allowed to use `Reductionops.whd_all` here, because it is way too slow.

Comment (SkySkimmer) [reply pretyping/vnorm.ml:84]: Probably
cc @ppedrot

Comment (ppedrot) [reply pretyping/vnorm.ml:84]: You may try to use `clos_whd_flags` instead.

Comment (silene) [reply pretyping/vnorm.ml]: Seems to work better. (What is the difference?) Let us see if it succeeds this time.

**Review by SkySkimmer — APPROVED** [review]
Let's bench https://gitlab.com/coq/coq/-/jobs/1051171384
If it's not too shocking I'll merge

**Comment by silene** [comment]
As expected, the change in number of CPU instructions is zero.
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  135.78   136.19  -0.30 │   376990348861    376762828931   0.06 │   506584478627    506602243634  -0.00 │  555604   557164  -0.28 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-coqutil │   57.58    57.74  -0.28 │   158905916346    158306401975   0.38 │   206456923322    205966185270   0.24 │  522400   523156  -0.14 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-hott │  319.06   319.68  -0.19 │   859437884666    856829187985   0.30 │  1442620031642   1442658735536  -0.00 │  716136   703648   1.77 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   51.02    51.05  -0.06 │   138649179112    138393039282   0.19 │   184223152077    184248779354  -0.01 │  522020   522284  -0.05 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  165.39   165.34   0.03 │   460173485400    458761331937   0.31 │   676878717810    676739440678   0.02 │  686796   688664  -0.27 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-bignums │   53.80    53.78   0.04 │   147676108547    146974257873   0.48 │   204546913412    204585310279  -0.02 │  473176   473212  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │ 1520.06  1519.41   0.04 │  4237927157072   4233062974990   0.11 │  7267291099461   7265535618384   0.02 │ 2433204  2433144   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   46.50    46.44   0.13 │   128665891936    128182864485   0.38 │   185460499889    185463318830  -0.00 │  484500   483352   0.24 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                         coq │  478.76   477.90   0.18 │  1332610042315   1328535996357   0.31 │  1812038913635   1812233342464  -0.01 │  568992   566920   0.37 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │  140.64   140.38   0.19 │   389131859230    388509182559   0.16 │   499236111830    499155450494   0.02 │  828488   827824   0.08 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1160.41  1156.30   0.36 │  3226897708924   3215454150495   0.36 │  4672927721438   4671815668227   0.02 │  907248   906756   0.05 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2454.93  2444.99   0.41 │  6832416036007   6803177584388   0.43 │ 12197289837442  12198311179938  -0.01 │  735608   735788  -0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  149.38   148.75   0.42 │   415336982905    412939052197   0.58 │   599953651172    599955823711  -0.00 │  721136   717564   0.50 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1027.58  1023.24   0.42 │  2861090528076   2849543699316   0.41 │  4687437769467   4687486960644  -0.00 │  980976   981068  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-verdi │   96.91    96.50   0.42 │   265236325511    265096988350   0.05 │   386064906686    385107356775   0.25 │  550308   550244   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │   98.30    97.86   0.45 │   277821841214    276038460155   0.65 │   389558250446    388073200879   0.38 │  484148   485320  -0.24 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  592.86   589.92   0.50 │  1654169405832   1643910507581   0.62 │  2611887113210   2609290995198   0.10 │ 3285668  3283640   0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 4726.17  4700.72   0.54 │ 13113006644312  13043423342820   0.53 │ 23732499595707  23729475715484   0.01 │ 2228356  2221324   0.32 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1153.99  1147.38   0.58 │  3209348952337   3189806654219   0.61 │  4757762968043   4757744618905   0.00 │ 1016656  1114932  -8.81 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-color │  472.87   470.00   0.61 │  1311946867349   1304847602683   0.54 │  1713658668189   1712336000628   0.08 │ 1141808  1136316   0.48 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-perennial │ 4890.10  4858.83   0.64 │ 13611608995950  13522936421566   0.66 │ 21135565037435  21143560604978  -0.04 │ 3063788  3069908  -0.20 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1337.23  1326.90   0.78 │  3718452038376   3691146511616   0.74 │  5627220803473   5626551478961   0.01 │  996264  1011500  -1.51 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-coqprime │   76.79    76.17   0.81 │   207958467970    207027839641   0.45 │   304073130169    303033142382   0.34 │  762364   763440  -0.14 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-corn │ 1428.37  1416.74   0.82 │  3963874995355   3932618979866   0.79 │  5877594188357   5877447371479   0.00 │  783704   822644  -4.73 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  219.77   217.80   0.90 │   611372938962    605057291794   1.04 │   952114074948    952143013428  -0.00 │  668312   670952  -0.39 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-coquelicot │   66.78    66.18   0.91 │   180336359161    179486494659   0.47 │   237639104099    236748925810   0.38 │  564440   560116   0.77 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-rewriter │  677.03   670.76   0.93 │  1878842809289   1860735314956   0.97 │  2941267793727   2938522270189   0.09 │ 1106420  1108384  -0.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-math-classes │  198.85   196.90   0.99 │   551762445358    546203992556   1.02 │   759968917363    759997608074  -0.00 │  500188   499192   0.20 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-bedrock2 │  196.77   194.56   1.14 │   542216586900    537300818316   0.91 │   917598081621    916385433258   0.13 │  777772   776404   0.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  743.74   733.98   1.33 │  2068233714040   2041441089805   1.31 │  3321945584137   3318293839232   0.11 │ 1104540  1104388   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  324.96   319.17   1.81 │   914004209479    896659134751   1.93 │  1700675414719   1698494785965   0.13 │ 3124512  3124396   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-unimath │ 3953.36  3881.62   1.85 │ 10992017570016  10789681433795   1.88 │ 21226356828529  21221754327812   0.02 │ 1022156  1022224  -0.01 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by SkySkimmer** [comment]
Those slowdowns are a bit beyond the usual noise range but they seem to be on lines unrelated to vm so ?_?
@coqbot: merge now
