### PR TITLE
Fix printing for empty primitive arrays

### LINKED ISSUE #13178: Anomaly when printing empty primitive array
~~~coq
Primitive array := #array_type.

Check [| | 0 |]. (* invalid_argument index out of bounds *)
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13178

### CODE REVIEW

File: printing/ppconstr.ml [hunk 1]
```diff
@@ -661,7 +661,7 @@ let tag_var = tag Tag.variable
         for i = Array.length t - 1 downto 1 do
           pp :=  str ";" ++ pr mt ltop t.(i) ++ !pp
         done;
-        pp :=  pr mt ltop t.(0) ++ !pp;
+        if not (Array.is_empty t) then pp :=  pr mt ltop t.(0) ++ !pp;
```
Comment (herbelin) [inline printing/ppconstr.ml:664]: Would it then make sense to reuse a formatting box similar to what is done for records? After all, the logic of a `prlist_with_sep` would probably be easier to understand than the logic of this `for` loop.

File: test-suite/bugs/closed/bug_13178.v [hunk 2]
```diff
@@ -0,0 +1,3 @@
+Primitive array := #array_type.
+
+Check [| | 0 |].
```
Comment (herbelin) [inline test-suite/bugs/closed/bug_13178.v:3]: Maybe worth to also have a couple of output tests?

**Review by herbelin — COMMENTED** [review]
Well found!

File: printing/ppconstr.ml (hunk 1 above)
Comment (SkySkimmer) [reply printing/ppconstr.ml]: changed

File: test-suite/bugs/closed/bug_13178.v (hunk 2 above)
Comment (SkySkimmer) [reply test-suite/bugs/closed/bug_13178.v:3]: added output test

**Comment by herbelin** [comment]
OK, let me assign and merge some time tomorrow (+ margin error).

**Review by herbelin — APPROVED** [review]
Good to me.

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by Zimmi48** [comment]
Primitive arrays were introduced in 8.13.
