### PR TITLE
Ensure "simpl never" is respected in presence of aliases

### LINKED ISSUE #13428: Arguments simpl never is ignored by subsequent definitions
#### Description of the problem

The problem occurred in https://github.com/math-comp/math-comp/pull/660
Here is a canonical example:
```coq
Arguments plus : simpl never.
Lemma test P : P (1 + 2).
simpl. (* P (1 + 2) as expected *)
match goal with |- P (_ + _) => idtac "ok" end.
Abort.

Definition plus' := plus.
Lemma test P : P (plus' 1 2).
simpl. (* P 3, not expected *)
Fail match goal with |- P (plus' _ _) => idtac "ok" end. (* Should succeed! *)
Fail match goal with |- P (plus _ _) => idtac "ok" end. (* or at least, this should succeed! *)
Abort.
```
Of course we can lock `plus'` again!
```coq
Arguments plus' : simpl never.
```
 But it is impossible/impractical for local definitions
```coq
Lemma test (P : nat -> Prop) : False.
pose (plus'' := plus').
assert (P (plus'' 1 2)).
simpl. (* P 3, not expected *)
Fail match goal with |- P (plus'' _ _) => idtac "ok" end. (* Should succeed! *)
Abort.
```

In constrast, ssreflect's `nosimpl` trick works perfectly:
```coq
Require Import ssreflect.

Definition nosimpl_plus := nosimpl plus.
Lemma test P : P (nosimpl_plus 1 2).
simpl. (* P (nosimpl_plus 1 2) as expected *)
match goal with |- P (nosimpl_plus _ _) => idtac "ok" end.
Abort.

Definition nosimpl_plus' := nosimpl_plus.
Lemma test P : P (nosimpl_plus' 1 2).
simpl. (* P (nosimpl_plus' 1 2) as expected *)
match goal with |- P (nosimpl_plus' _ _) => idtac "ok" end.
Abort.
```
ssreflect's `nosimpl` could even be used to compensate for this bug as in:
```coq
Lemma test (P : nat -> Prop) : False.
pose plus'' := nosimpl plus'.
have : P (plus'' 1 2).
simpl. (* P (plus'' 1 2) as expected *)
match goal with |- P (plus'' _ _) => idtac "ok" end.
Abort.
```
#### Coq Version

Coq 8.10 and above

### PR DESCRIPTION
**Pull request by ybertot**
**Kind:** bug fix

Fixes / closes #13428

- [x] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

Overlays:
- https://github.com/PrincetonUniversity/VST/pull/527 - already merged
- https://github.com/jwiegley/category-theory/pull/122

### CODE REVIEW

File: pretyping/tacred.ml [hunk 1]
```diff
@@ -268,7 +268,35 @@ let invert_name labs l {binder_name=na0} env sigma ref na =
...
+      | Lambda(id, t, bd) ->
+        check_no_nosimpl
+          (let open Context.Rel.Declaration in
+           push_rel (LocalAssum (id, t)) env) bd
+           (* todo: include also l in the arguments, but they probably
+              have to be "lifted" to be interpreted in the current
+              environment. *)
+      | _ -> true in
+  let rec srec env n labs onlyproj c : constant_evaluation =
     let c',l = whd_betadeltazeta_stack env sigma c in
```
Comment (gares) [inline pretyping/tacred.ml:300]: What I was suggesting is the one could pass more flags to this function, in particular 
https://github.com/coq/coq/blob/94d579844817edcbb2454dd9dc79071b2cd1d12a/kernel/cClosure.mli#L53
plus
https://github.com/coq/coq/blob/94d579844817edcbb2454dd9dc79071b2cd1d12a/kernel/cClosure.mli#L43
plus some code to fetch all key-value pairs such that value is "simpl never"
https://github.com/coq/coq/blob/94d579844817edcbb2454dd9dc79071b2cd1d12a/pretyping/reductionops.ml#L135
should let one force `whd_betadeltazeta_stack` to stop at any simpl-never flagged constants and one
can add a case in the code below raising `Redelimination` as you do in this patch.

It's a bit of code because one has to patch reductionops to "expose" the reduction flags.
IIRC @ppedrot was also interested to be able to pass these flags down to cClosure

**Comment by gares** [comment]
The 3 CI failures are real, but I don't have time to look at them closely. Even if we change implementation strategy, they have to be addressed.

**Comment by ppedrot** [comment]
Since `simpl` is a pretty sensitive part of the system, I believe this needs a benchmark to rule out bad surprises...

File: pretyping/tacred.ml [hunk 2]
```diff
@@ -267,9 +267,27 @@ let invert_name labs l {binder_name=na0} env sigma ref na =
...
+  let flags =
+    let open CClosure.RedFlags in
+    let open ReductionBehaviour in
+    red_add
+      (red_add
+         (List.fold_right
+            (fun x r ->
+              red_sub r
+                (match x with
+                   Names.GlobRef.ConstRef xx ->  fCONST xx
```
Comment (gares) [inline pretyping/tacred.ml:280]: This deserves a comment.
Also, I'm not 100% sure that one cannot use `Arguments` on a `Let` for example, which is a `VarRef` IIRC

**Comment by gares** [comment]
I did unblock the CI pipeline, bench job included.

File: pretyping/tacred.ml (hunk 2 above)
Comment (ybertot) [reply pretyping/tacred.ml]: Two answers:
1/ from the code, it is not possible that a "Let" defined constant has a flag stored in the ReductionBehaviour table, because this only works for constants.
2/ I also tried.  the following code fragment
```
Section playground.
Let plus3 := fix plus3 (n m : nat) := match n with O => m | S p => plus3 p (S m) end.
Arguments plus3 : simpl never.
```
got the following error message.
```
Error: Modifiers of the behavior of the simpl tactic are relevant for
constants only.
```

Comment (gares) [reply pretyping/tacred.ml]: ok!

**Comment by gares** [comment]
Every time you push a commit a new CI job "tries to start". In spite of Matthieu's attempts to get a "gold" gitlab account, Coq is still throttled, and one has to follow the link to gitlab ci and cancel/restart the "pipeline" of CI jobs, otherwise they don't run. (FYI)

**Comment by gares** [comment]
I've also started a bench as PMP asked: https://gitlab.com/coq/coq/-/jobs/884440631

**Comment by Zimmi48** [comment]
> one has to follow the link to gitlab ci and cancel/restart the "pipeline" of CI jobs, otherwise they don't run. (FYI)

FYI, as I mentioned in one of the recent Coq Calls, you can restart jobs directly from GitHub, by clicking on "Re-run" (your issue https://github.com/coq/bot/issues/113 is fixed).

File: pretyping/reductionops.ml [hunk 3]
```diff
@@ -89,11 +104,19 @@ module ReductionBehaviour = struct
...
+  that is this set. *)
   let table =
-    Summary.ref (GlobRef.Map.empty : t GlobRef.Map.t) ~name:"reductionbehaviour"
+    Summary.ref ((GlobRef.Set.empty, GlobRef.Map.empty) :
+                   GlobRef.Set.t * t GlobRef.Map.t) ~name:"reductionbehaviour"
 
   let load _ (_,(_,(r, b))) =
-    table := GlobRef.Map.add r b !table
+    table := ((match b with
+                NeverUnfold ->
```
Comment (ppedrot) [inline pretyping/reductionops.ml:116]: Note that this is wrong: when you add a ref to one side, you need to remove it from the other. Otherwise the semantics of maps is not respected.

File: doc/changelog/04-tactics/13428-simpl-never-delta.rst [hunk 4]
```diff
@@ -0,0 +1,6 @@
+- **Fixed:**
+  The :tacn:`simpl` tactic now respects the :n:`simpl never` flag even
+  when the subject function is referred to through an other definition.
```
Comment (jfehrle) [inline doc/changelog/04-tactics/13428-simpl-never-delta.rst:3]:
```suggestion
  when the subject function is referred to through another definition.
```

**Comment by gares** [comment]
You need to rebase the branch (and resolve the conflict in reductionops), otherwise  CI won't run.

**Comment by gares** [comment]
Dear @coq/ci-maintainers it seems perennial uses it's own copy (git submodule) of stdpp hence the overlay is not picked up. What shall @ybertot do?

To me no CI job should use its own copies of other projects, as part of our CI policy.

**Comment by ybertot** [comment]
I was able to verify the compilation of perennial with my version of stdpp by cloning the repository on my machine and then checking out my version of stdpp.  It succeeds, but I don't know how to make the ci process reproduce the computations I did.

**Comment by Zimmi48** [comment]
There are many projects that use git submodules to get their dependencies. It's a bit cumbersome to prepare an overlay since you need another branch for the dependency and another branch of the tested project just to update the submodule.

However, you should think of overlays as a convenience, not as a hassle. So if you have already tested compatibility of perennial with your branch locally, then you don't have to worry that it is failing in CI (although in this case, you have already figured it out).

**Comment by ybertot** [comment]
All checks pass.  Can we enter a more active review phase?

**Comment by gares** [comment]
I've started a bench: https://gitlab.com/coq/coq/-/jobs/1011863809

**Comment by gares** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-bignums │   53.53    53.95  -0.78 │   147719516663    147620021832   0.07 │   205760633241    204596408399   0.57 │  477236   473396   0.81 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  316.92   318.41  -0.47 │   889764834433    895268510540  -0.61 │  1689769051256   1695639179559  -0.35 │ 3124576  3124556   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                         coq │  477.87   479.00  -0.24 │  1328869669511   1330711029860  -0.14 │  1813101440827   1812655845858   0.02 │  569224   568936   0.05 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2445.86  2448.41  -0.10 │  6816202159434   6814888901704   0.02 │ 12199438070511  12188608386614   0.09 │  736132   735668   0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  734.38   734.80  -0.06 │  2042236230933   2042177940840   0.00 │  3309530439094   3309691611500  -0.00 │ 1104412  1104504  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-bedrock2 │  208.04   208.06  -0.01 │   574521287032    572766500492   0.31 │   981580367772    979476263612   0.21 │  777860   777324   0.07 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-coqprime │   75.74    75.73   0.01 │   206600981616    205984680893   0.30 │   302812912430    301204306095   0.53 │  765204   763588   0.21 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-unimath │ 3830.01  3828.48   0.04 │ 10643142454742  10644595600327  -0.01 │ 21044998291614  21042772706688   0.01 │ 1118644  1118768  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  217.43   217.28   0.07 │   604029944899    603816687020   0.04 │   950896467434    949556999709   0.14 │  671896   666616   0.79 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 4699.40  4695.20   0.09 │ 13043979943807  13026223516631   0.14 │ 23682171691173  23674533182882   0.03 │ 2231960  2225188   0.30 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1152.42  1151.38   0.09 │  3202441640199   3199596523587   0.09 │  4664569242587   4660747079324   0.08 │  903860   903592   0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  589.61   588.06   0.26 │  1644168131379   1638639242294   0.34 │  2607259405425   2603690445579   0.14 │ 3283588  3283624  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  148.53   148.10   0.29 │   412451147323    411456541266   0.24 │   599401493064    598065976846   0.22 │  710980   703112   1.12 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-rewriter │  669.91   667.81   0.31 │  1857477793746   1853210729375   0.23 │  2936389671967   2933324970313   0.10 │ 1104404  1104340   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1332.32  1328.09   0.32 │  3702690004955   3691211520552   0.31 │  5621817623738   5617809227843   0.07 │  996120   996476  -0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-corn │ 1410.20  1405.02   0.37 │  3911499045283   3897380325434   0.36 │  5858328938636   5849411680123   0.15 │  825544   787332   4.85 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-color │  469.97   468.18   0.38 │  1303595427739   1299337585902   0.33 │  1708997841744   1706474030056   0.15 │ 1141620  1138276   0.29 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   46.39    46.20   0.41 │   127996095516    127683162428   0.25 │   184918420363    184477388449   0.24 │  482980   483732  -0.16 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  131.92   131.31   0.46 │   364994664937    363975355319   0.28 │   491042573557    489909225331   0.23 │  540340   541368  -0.19 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1021.46  1016.66   0.47 │  2843263302944   2828038008399   0.54 │  4702146695157   4683467580911   0.40 │  974180   981096  -0.70 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-math-classes │  196.44   194.91   0.78 │   544195387635    541875515686   0.43 │   756971454417    756225126149   0.10 │  498988   500360  -0.27 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-verdi │   94.85    94.07   0.83 │   259851666387    257924648120   0.75 │   381165217459    378451280454   0.72 │  550200   557704  -1.35 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │  141.34   139.80   1.10 │   390095372916    387156301376   0.76 │   500134626265    497868417758   0.46 │  826764   827932  -0.14 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  165.92   163.77   1.31 │   458864126302    455659504322   0.70 │   677517342333    674538125102   0.44 │  657548   688548  -4.50 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   50.06    49.36   1.42 │   135671601458    134646707904   0.76 │   180617799501    179298223779   0.74 │  516276   518660  -0.46 │   0    0    nan 
│
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-coqutil │   58.14    57.12   1.79 │   160130733816    157816668208   1.47 │   206212818317    205207693638   0.49 │  524412   522732   0.32 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │   97.89    96.17   1.79 │   275568060806    272933665491   0.97 │   386787838711    383357181839   0.89 │  485280   486608  -0.27 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-coquelicot │   65.62    64.16   2.28 │   177791317267    175137550001   1.52 │   235869853636    232721443784   1.35 │  559676   562164  -0.44 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by gares** [comment]
The bench shows a little slowdown, unfortunately coquelicot does not use coq-makefile so we don't get the per line timing info in the benchmark artifacts :-/ Maybe @silene is willing to fix that one (here the relevant snippets):

https://github.com/coq/coq/blob/16765871394a81975047b37f15a902fcc112dc40/tools/CoqMakefile.in#L712-L720
https://github.com/coq/coq/blob/16765871394a81975047b37f15a902fcc112dc40/tools/CoqMakefile.in#L230-L243

File: pretyping/reductionops.ml [hunk 5]
```diff
@@ -79,6 +79,21 @@ module ReductionBehaviour = struct
   type t = NeverUnfold | UnfoldWhen of when_flags | UnfoldWhenNoMatch of when_flags
   and when_flags = { recargs : int list ; nargs : int option }
 
+  let equal t1 t2 =
+    match t1, t2 with
+      NeverUnfold, NeverUnfold -> true
+    | (UnfoldWhen {recargs = r1; nargs = n1}),
+      (UnfoldWhen {recargs = r2; nargs = n2}) ->
+       List.length r1 = List.length r2 &&
+         List.for_all2 (fun k1 k2 -> Int.equal k1 k2) r1 r2 &&
```
Comment (gares) [inline pretyping/reductionops.ml:88]:
```suggestion
         List.for_all2 Int.equal r1 r2 &&
```

File: pretyping/reductionops.ml [hunk 6]
```diff
@@ -79,6 +79,21 @@ module ReductionBehaviour = struct
...
+           Option.equal Int.equal n1 n2
+    | UnfoldWhenNoMatch {recargs = r1; nargs = n1},
+      UnfoldWhenNoMatch {recargs = r2; nargs = n2} ->
+       List.length r1 = List.length r2 &&
+         List.for_all2 (fun k1 k2 -> Int.equal k1 k2) r1 r2 &&
```
Comment (gares) [inline pretyping/reductionops.ml:93]:
```suggestion
         List.for_all2 Int.equal r1 r2 &&
```

File: pretyping/reductionops.ml [hunk 7]
```diff
@@ -89,11 +104,22 @@ module ReductionBehaviour = struct
...
   let load _ (_,(_,(r, b))) =
-    table := GlobRef.Map.add r b !table
+    table := ((match b with
+                NeverUnfold ->
+                GlobRef.Set.add r (fst !table)
+                | _ -> GlobRef.Set.remove r (fst !table)),
+                       (match b with
+                         NeverUnfold ->
+                         GlobRef.Map.remove r (snd !table)
+                        |_ -> GlobRef.Map.add r b (snd !table)))
```
Comment (gares) [inline pretyping/reductionops.ml:122]:
```suggestion
    table := (match b with
                | NeverUnfold -> GlobRef.Set.add r (fst !table), GlobRef.Map.remove r (snd !table)
                | _ -> GlobRef.Set.remove r (fst !table), GlobRef.Map.add r b (snd !table))
```

I rephrase the code so that the invariant @ppedrot was talking about is more explicit

File: pretyping/tacred.ml [hunk 8]
```diff
@@ -656,11 +657,29 @@ let whd_nothing_for_iota env sigma s =
...
+let make_simpl_reds () =
+  let open CClosure.RedFlags in
+  red_add
+    (red_add
+       (GlobRef.Set.fold
+          (fun x r ->
+            red_sub r
+              (match x with
+                 Names.GlobRef.ConstRef xx ->  fCONST xx
+               | _ -> assert false))
```
Comment (gares) [inline pretyping/tacred.ml:672]:
```suggestion
              (match x with
                 Names.GlobRef.ConstRef xx ->  red_sub r (fCONST xx)
               | _ -> r))
```
This way there is no `assert false` (the data structures are about any globref, I don't even know if it is true that you cannot make an inductive simpl never even if it would have no effect).

**Review by gares — CHANGES_REQUESTED** [review]
It's all good but for the assert false thing.
I've added a few nits, totally optional.

**Comment by gares** [comment]
@ppedrot if you have time to do your magic about perf on coquelicot...

**Comment by silene** [comment]
> unfortunately coquelicot does not use coq-makefile

Note that there is a `_CoqProject` file, so you can always run `coq_makefile` if you need to. I am not the maintainer for the `dev` package, so feel free to modify it as you see fit for benchmarking.

That said, I can add a timing infrastructure to Coquelicot proper. But I don't understand how it supposed to work. For example, `dev/becnh/gitlab.sh` does `export TIMING=1`, but `coq_makefile` tests for `TIMING=before` and `TIMING=after`. Which one is it?

**Comment by gares** [comment]
The former is the one used by the bench infrastructure.

The latter 2 were added by Jason (the python thing), I don't know what they do exactly but they should be documented in the refman.

**Comment by silene** [comment]
> The former is the one used by the bench infrastructure.

I have pushed a commit that adds it to Coquelicot.

**Comment by gares** [comment]
New bench here: https://gitlab.com/coq/coq/-/jobs/1018753767

**Comment by gares** [comment]
The good news is that coquelicot has now colored output: https://coq.gitlab.io/-/coq/-/jobs/1018753767/artifacts/_bench/html/coq-coquelicot/theories/Complex.v.html

The other news is that bench is fluctuating a bit, there is a little generalized slowdown.

**Comment by gares** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   46.42    46.70  -0.60 │   128084490703    128132024314  -0.04 │   184975059354    184543202963   0.23 │  486264   483668   0.54 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-unimath │ 3827.50  3829.66  -0.06 │ 10642358006193  10649275566223  -0.06 │ 21046071102390  21042681435088   0.02 │ 1118352  1121260  -0.26 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2446.69  2446.43   0.01 │  6817934290394   6816536811086   0.02 │ 12199171708246  12187742143864   0.09 │  736056   735764   0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 4702.37  4697.46   0.10 │ 13046679756467  13026570405052   0.15 │ 23690149753858  23673215438263   0.07 │ 2223056  2231736  -0.39 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-corn │ 1405.59  1403.93   0.12 │  3908887894904   3896489684293   0.32 │  5858325527842   5849518567191   0.15 │  824560   822792   0.21 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                         coq │  478.33   477.45   0.18 │  1328549914263   1325509224903   0.23 │  1813104670989   1812686512572   0.02 │  571400   571720  -0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  318.55   317.94   0.19 │   894547988724    893502641807   0.12 │  1693221584952   1696334619398  -0.18 │ 3124548  3124408   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  217.05   216.58   0.22 │   604398088495    603141640739   0.21 │   951083812555    949600819583   0.16 │  670084   666544   0.53 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  148.54   148.18   0.24 │   412353306073    411604666157   0.18 │   599371129309    598199457688   0.20 │  709244   703208   0.86 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1330.79  1327.16   0.27 │  3700458756654   3690823861572   0.26 │  5621873217361   5617777300273   0.07 │ 1013556   996452   1.72 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  165.15   164.68   0.29 │   458359567342    456961519794   0.31 │   677578244807    674513781973   0.45 │  674472   686396  -1.74 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-math-classes │  196.27   195.67   0.31 │   543919203075    542977489134   0.17 │   757009052521    756289864611   0.10 │  498260   502796  -0.90 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1020.43  1017.21   0.32 │  2838865880713   2829904743319   0.32 │  4702174573311   4683511159445   0.40 │  980964   977704   0.33 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1154.20  1150.42   0.33 │  3205963352667   3199562247450   0.20 │  4664820411351   4660635514976   0.09 │  904340   904360  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  590.44   588.29   0.37 │  1644804886779   1639000701003   0.35 │  2607268338856   2603437506538   0.15 │ 3283660  3285848  -0.07 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  734.53   731.81   0.37 │  2044875316443   2035100139226   0.48 │  3309626575595   3309552863277   0.00 │ 1104524  1104216   0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-coqprime │   75.78    75.45   0.44 │   206525144724    205548401805   0.48 │   302889760240    301264330850   0.54 │  765428   760192   0.69 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-coquelicot │   66.04    65.65   0.59 │   179955856590    178163621793   1.01 │   237535825536    234542597574   1.28 │  561728   558136   0.64 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  131.92   131.06   0.66 │   365694597637    364133568815   0.43 │   491111412809    489908004355   0.25 │  539976   537564   0.45 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-rewriter │  672.47   667.51   0.74 │  1863706145384   1850003487984   0.74 │  2936086785864   2933418813636   0.09 │ 1108348  1104644   0.34 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-bedrock2 │  208.54   206.88   0.80 │   574593829391    571875775323   0.48 │   981511502542    979545198207   0.20 │  776976   776372   0.08 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-color │  471.26   467.31   0.85 │  1306136189679   1297460098129   0.67 │  1709072118622   1706456019440   0.15 │ 1138504  1137572   0.08 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   50.23    49.78   0.90 │   136091615576    134916531932   0.87 │   180692098450    179330984983   0.76 │  515908   518760  -0.55 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │   98.20    97.18   1.05 │   276311688183    273233771247   1.13 │   386879418540    383432510322   0.90 │  484460   483204   0.26 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │  141.66   140.08   1.13 │   390819170303    387507975039   0.85 │   500164842330    497836896207   0.47 │  830204   827980   0.27 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-bignums │   53.92    53.30   1.16 │   148246066979    146840903139   0.96 │   205815555130    204635786653   0.58 │  475692   473412   0.48 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-verdi │   94.96    93.83   1.20 │   259914476706    257533655274   0.92 │   381223995617    378524344474   0.71 │  553748   552480   0.23 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-coqutil │   58.03    57.22   1.42 │   159129124583    157543856570   1.01 │   206235609528    205281003521   0.47 │  524656   526104  -0.28 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by gares** [comment]
Dear @coq/bench-maintainers , can you help us read these results? Should we be worried or not?

**Comment by ppedrot** [comment]
Probably not. The per-line diff shows a few slowdowns in the order of 2-3% that might be reproducible, but it's small enough to not be problematic.

**Comment by gares** [comment]
Great! @ybertot would you mind accepting at least my last fix to the code? Then I think I can merge it.

**Comment by gares** [comment]
@ppedrot you once showed me how to find the lines that do slow down (and now I forgot). Can we get the script be run automatically as part of bench and its output saved at the root of the html/ thing?

**Comment by ppedrot** [comment]
It generates a pretty big file though. I am already not quite happy about the current size of the artifact zip file (about 60Mib) which could be reduced by processing locally the relevant generated data. I had to access this data on a crappy connection recently and had to wait for like 15 minutes before getting my hand on it, so it's not just theoretical concern.

**Review by ppedrot — COMMENTED** [review]
I remember we talked about this design choice but I don't remember the motivation, so let me state it here: I am not very fond of the explicit argument passing in all the functions, that's a lot of noise both from the point of view of line diff and raw code. I think it was due to potential concerns about efficiency, but even that way we could generate the flags once and for all without mangling all these functions. For instance, we could extend the `env` argument to a tuple containing said flags. It's not a hard requirement for this PR to be merged, but it does look quite messy currently.

File: pretyping/reductionops.mli [hunk 9]
```diff
@@ -274,13 +275,18 @@ type state = constr * constr Stack.t
...
+  state_reduction_function -> stack_reduction_function
+
 val pr_state : env -> evar_map -> state -> Pp.t
 
 val whd_nored_state : state_reduction_function
 
 val whd_betaiota_deltazeta_for_iota_state :
   TransparentState.t -> state_reduction_function
 
+val whd_state_gen : CClosure.RedFlags.reds -> state_reduction_function
```
Comment (ppedrot) [inline pretyping/reductionops.mli:288]: Don't export this function as well as the above `stack_red_of_state_red` wrapper, since they are only used both together. Instead you should only export a `whd_stack_gen` combining both. FTR anything remotely using the explicity stack representation delays a future change of representation.

**Comment by gares** [comment]
> It generates a pretty big file though.

I usually browse the artifact online, I'd like to just have a list of files with the higher diff in time printed for me. Even just the first 10 hits would be great.

**Comment by gares** [comment]
> For instance, we could extend the `env` argument to a tuple containing said flags.

As a reader of the code, I would not be happy having a variable called `env` carrying something that is not just the `env`.
Also, following the same reasoninig, we would pack env sigma and allowed_reds into a single argument.

So I find this specific comment quite debatable (I know it's optional, but IMO also not really improving the patch)

**Comment by ppedrot** [comment]
It's quite clear that semantically those flags are part of the environment, so it seems legit to put them there. Note that environments and evar maps cannot be mixed although there would be a lot of advantages in doing so, because one is reader-like and the other state-like.

**Comment by gares** [comment]
>  one is reader-like and the other state-like.

Not sure it is the case in this piece of code, their are both reader like IMO.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I took the liberty to commit the suggested changes. If CI is green I will merge.

File: dev/ci/user-overlays/13448-ybertot-fix_simpl_never_wrt_delta.sh [hunk 10]
```diff
@@ -0,0 +1,3 @@
+overlay hott https://github.com/ybertot/HoTT respect_simpl_never_flags 13448
+overlay stdpp https://gitlab.inria.fr/bertot/stdpp respect_simpl_never_flags 13448
+overlay perennial https://github.com/ybertot/perennial respect_simpl_never_flags 13448
```
Comment (gares) [inline dev/ci/user-overlays/13448-ybertot-fix_simpl_never_wrt_delta.sh:3]:
```suggestion
#overlay stdpp https://gitlab.inria.fr/bertot/stdpp respect_simpl_never_flags 13448
#overlay perennial https://github.com/ybertot/perennial respect_simpl_never_flags 13448
```

Comment (gares) [reply dev/ci/user-overlays/13448-ybertot-fix_simpl_never_wrt_delta.sh:3]: IIRC Iris merged this upstream, so I'll try to comment them out and see. The don't apply anymore as they are, since there are conflicts now.

So if they are still needed @ybertot will have to rebase them, but maybe we are lucky and commenting them is just ok.

**Comment by gares** [comment]
The good new is that CI is green. @ppedrot I pushed a commit addressing your comment.

**Comment by gares** [comment]
@ppedrot how is your bench? Can I merge

**Comment by ppedrot** [comment]
Oops, forgot to start the bench in the end. It is now running here: https://gitlab.com/coq/coq/-/jobs/1157134531.

**Comment by gares** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                             │                         │                                       │                                       │                          │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                         coq │    4.09     4.14  -1.21 │    11133100840     11107237182   0.23 │    21992516687     21999636274  -0.03 │  290100   290996   -0.31 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  328.34   330.67  -0.70 │   922765546766    928815368191  -0.65 │  1691107526919   1693389076419  -0.13 │ 3546640  3546640    0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   52.58    52.82  -0.45 │   145665073132    144749153916   0.63 │   185925774966    184725205523   0.65 │  522832   524636   -0.34 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1369.68  1374.71  -0.37 │  3809570861962   3822022879042  -0.33 │  5639055521082   5634822266179   0.08 │ 1000772   996608    0.42 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-stdlib │  387.83   389.11  -0.33 │  1077561074033   1079524817104  -0.18 │  1396966539923   1396451055955   0.04 │  569344   571612   -0.40 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-corn │ 1457.14  1461.30  -0.28 │  4048469244777   4055736658305  -0.18 │  5875292459157   5865753269789   0.16 │  819484   806268    1.64 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │ 1551.33  1555.60  -0.27 │  4322425676859   4333266227445  -0.25 │  7205483397435   7198867275277   0.09 │ 2433140  1696276   43.44 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-core │  107.23   107.52  -0.27 │   301760903673    300720006620   0.35 │   455215256105    455118514932   0.02 │  263952   263904    0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1171.30  1174.16  -0.24 │  3261523310073   3270969544438  -0.29 │  4627769652445   4624861709418   0.06 │  902784   903504   -0.08 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  761.66   762.92  -0.17 │  2118081712479   2120771772100  -0.13 │  3291050426295   3290043230344   0.03 │ 1106624  1104476    0.19 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-math-classes │  202.83   203.11  -0.14 │   563585528742    564294457449  -0.13 │   762267316792    761531824659   0.10 │  502516   501236    0.26 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-bedrock2 │  200.25   200.50  -0.12 │   553589745817    555279920233  -0.30 │   915835038146    913809654435   0.22 │  778500   778204    0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  138.98   139.11  -0.09 │   386493501577    386275051200   0.06 │   504059424361    502733269968   0.26 │  559044   556320    0.49 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 4838.74  4840.64  -0.04 │ 13434562202825  13425960848316   0.06 │ 23677166410694  23664111715126   0.06 │ 2230636  2234580   -0.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  624.98   625.20  -0.04 │  1745634526223   1746479232042  -0.05 │  2660323284768   2658631697560   0.06 │ 3283412  3692964  -11.09 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  153.36   153.32   0.03 │   425582537285    425649664802  -0.02 │   599306818369    598037899911   0.21 │  734488   711164    3.28 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-color │  488.64   488.17   0.10 │  1356747790914   1357057599560  -0.02 │  1718493602730   1715792972673   0.16 │ 1070916  1069140    0.17 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1062.12  1060.52   0.15 │  2953613006711   2949572080937   0.14 │  4703890962224   4685468515358   0.39 │  916784   912276    0.49 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2525.56  2521.67   0.15 │  7039817238325   7022362827278   0.25 │ 12263100190695  12252503894097   0.09 │  735844   735784    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-flocq │  146.82   146.55   0.18 │   405581124092    405163495506   0.10 │   503085749642    500484475769   0.52 │  827912   828156   -0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  171.17   170.75   0.25 │   476516278995    474630703835   0.40 │   679365595036    676430911439   0.43 │  688868   684744    0.60 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-rewriter │  696.95   694.75   0.32 │  1935777726221   1931513222418   0.22 │  2928089651713   2924892092519   0.11 │ 1108220  1104704    0.32 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   48.28    48.10   0.37 │   133838460351    133249288286   0.44 │   186894980930    186240462606   0.35 │  484880   483288    0.33 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  224.37   223.49   0.39 │   623640635634    622017487597   0.26 │   950901172414    949747624135   0.12 │  664496   659644    0.74 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-coqprime │   78.79    78.48   0.40 │   216068061097    214849552351   0.57 │   305934781795    304104404273   0.60 │  763384   758104    0.70 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-verdi │   98.98    98.40   0.59 │   271862663620    271963153816  -0.04 │   385040127780    383314866465   0.45 │  548644   549172   -0.10 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-bignums │   55.01    54.67   0.62 │   151782037693    151528014184   0.17 │   206093004424    205121984880   0.47 │  476376   472640    0.79 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-coquelicot │   69.16    68.61   0.80 │   188433297062    186792070624   0.88 │   240200412037    237016006070   1.34 │  564232   560128    0.73 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-unimath │ 3996.84  3964.12   0.83 │ 11116053184296  11023984320808   0.84 │ 21234561897750  21238046095908  -0.02 │ 1101864  1090560    1.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fiat-core │  108.53   107.40   1.05 │   307552686245    305049811689   0.82 │   418694507691    415321313582   0.81 │  485540   486000   -0.09 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-coqutil │   54.13    53.52   1.14 │   149657160705    148531698177   0.76 │   195150530236    194092221600   0.55 │  524388   523180    0.23 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-perennial │ 5495.70  5371.96   2.30 │ 15284717705718  14939094084524   2.31 │ 23024974343364  22523262071847   2.23 │ 3055100  3101236   -1.49 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1305.54  1255.98   3.95 │  3629791242405   3492172010153   3.94 │  5219340288472   5028855815515   3.79 │ 1106704  1086196    1.89 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by gares** [comment]
Given perennial embeds iris, I guess the last two lines are about the same slowdown, which happens to be the only relevant one.
I won't have time to investigate @ppedrot but if you have a minute to run your script and see if it is just a few places that blow up, it would be great.

**Comment by ppedrot** [comment]
Here is a list of the per-line stats with > 1s difference.
```
html/coq-unimath/UniMath/SubstitutionSystems/SignatureExamples.v.html:614 1.00 47.92 48.91 (2%)
html/coq-rewriter-perf-SuperFast/src/Rewriter/Rewriter/Wf.v.html:510 1.00 58.88 59.88 (2%)
html/coq-unimath/UniMath/SyntheticHomotopyTheory/Circle2.v.html:443 1.01 56.12 57.13 (2%)
html/coq-perennial/src/goose_lang/metatheory.v.html:42 1.02 5.65 6.67 (18%)
html/coq-unimath/UniMath/SubstitutionSystems/ModulesFromSignatures.v.html:201 1.03 49.13 50.17 (2%)
html/coq-perennial/src/goose_lang/lang.v.html:1212 1.41 2.04 3.45 (69%)
html/coq-perennial/src/program_proof/twophase/twophase_refinement_proof.v.html:356 1.85 7.84 9.69 (24%)
html/coq-perennial/src/goose_lang/metatheory.v.html:85 2.66 5.18 7.84 (51%)
html/coq-perennial/src/goose_lang/metatheory.v.html:148 2.87 3.47 6.34 (83%)
html/coq-perennial/src/goose_lang/lib/encoding/encoding.v.html:593 4.35 37.73 42.08 (12%)
```
As you can see, some slowdowns in perennial are localized. For lambda-rust it seems to be more spread out.

**Comment by gares** [comment]
I could find a hot spot in iris https://coq.gitlab.io/-/coq/-/jobs/1157134531/artifacts/_bench/html/coq-lambda-rust/theories/typing/own.v.html , the `solve_type_proper` thing seems considerably slower. @RalfJung any idea how this PR could affect it?

**Comment by RalfJung** [comment]
I'm afraid I have no idea -- performance of Coq is pretty much entirely a black box to me.

That tactic boils down to something like a loop running the std++ `f_equiv` tactic, but also trying to apply some lemmas on each step -- so either part could be what has slowed down here.

**Comment by mattam82** [comment]
I guess that has to do with searches for `Proper`? Maybe diffing the typeclasses search before and after could point to the problem.

**Comment by silene** [comment]
What is the status of this pull request? Are we fine with the slowdown or should we just postpone the pull request?

**Comment by ppedrot** [comment]
I'd personally recommend postponing until we find out if there is something that can be done to solve the slowdown.

**Comment by Alizter** [comment]
Looks like this PR is heading to the graveyard, any plans to save it?

**Comment by gares** [comment]
I've rebased this one, let's see how the bench goes

**Comment by Janno** [comment]
One thing I have noticed is has `stdpp` sets `decide` and `decide_rel` set to `simpl never` but in practice clients rely on them being unfolded when used in `if` terms and when the underlying `Decision` instance reduces. Now, I am not sure if iris and perennial have a lot of case distinctions like that in their terms but it seems at least possible. *If* this patch makes it so that `decide` and `decide_rel` do not unfold any more then this could lead to much bigger terms in goals, potentially repeated reductions, etc.

This is a big "if", though, because I don't actually understand why `decide` and `decide_rel` are simplified despite being marked as `simpl never`.

**Comment by gares** [comment]
Hum, if a term `f` is simpl never but it occurs in a `match` context, then it is reduced anyway. This is the desired spec, which makes the simpl never name badly chosen (by me).

This PR makes it so if an occurrence of `f` is not reduced, then also an occurrence of `d` where `d := f` is not reduced either.

**Comment by Janno** [comment]
Ah, I see. Thanks for elaborating. That explains my confusion but sadly does not at all explain the slowdown.

**Comment by gares** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2541.68  2556.00  -0.56 │  7075951462528   7125314144670  -0.69 │ 12244614039142  12234482505752   0.08 │  732556   732836  -0.04 │   0    0    nan │
│                   coq-flocq │  147.09   147.36  -0.18 │   409191524287    409047925484   0.04 │   506990314638    504460524192   0.50 │  810384   810452  -0.01 │   0    0    nan │
│      coq-mathcomp-character │  148.63   148.88  -0.17 │   413742273914    413389076816   0.09 │   577774457304    576431114719   0.23 │  710016   732396  -3.06 │   0    0    nan │
│                  coq-stdlib │  413.85   414.38  -0.13 │  1156484621564   1158673582109  -0.19 │  1469911502707   1469632204336   0.02 │  614764   597516   2.89 │   0    0    nan │
│  coq-performance-tests-lite │ 1404.63  1406.09  -0.10 │  3918353088073   3921693082751  -0.09 │  6324362751897   6324488066445  -0.00 │ 2084988  2085044  -0.00 │   0    0    nan │
│                 coq-unimath │ 4581.45  4586.07  -0.10 │ 12744008981499  12760753603417  -0.13 │ 24406729812293  24419908938792  -0.05 │ 3711884  3732368  -0.55 │   0    0    nan │
│       coq-engine-bench-lite │  291.17   291.45  -0.10 │   820334234351    820536515677  -0.02 │  1497440206969   1492648288750   0.32 │ 1410716  1410716   0.00 │   0    0    nan │
│                  coq-geocoq │ 1298.70  1298.65   0.00 │  3623502998065   3620579952923   0.08 │  5339637710357   5336316939671   0.06 │ 1070424   980188   9.21 │   0    0    nan │
│        coq-mathcomp-algebra │  139.63   139.62   0.01 │   388407414893    387660430630   0.19 │   503412108938    502016561600   0.28 │  554064   555944  -0.34 │   0    0    nan │
│                    coq-core │  108.13   108.11   0.02 │   298991733352    298584231212   0.14 │   463041431622    463123413614  -0.02 │  299944   299976  -0.01 │   0    0    nan │
│                coq-coqprime │  332.15   332.07   0.02 │   922234390793    921818933967   0.05 │  1595218119596   1593792456183   0.09 │  916164   857560   6.83 │   0    0    nan │
│                    coq-corn │ 1468.23  1467.32   0.06 │  4094735038238   4084890530225   0.24 │  5870182854037   5861832661236   0.14 │  801140   808948  -0.97 │   0    0    nan │
│            coq-math-classes │  172.21   171.91   0.17 │   480188417810    480000905866   0.04 │   637900447589    637105393497   0.12 │  482008   481860   0.03 │   0    0    nan │
│            coq-fiat-parsers │  582.52   581.50   0.18 │  1630217960741   1625023027316   0.32 │  2485582429464   2481024115471   0.18 │ 3485292  3485304  -0.00 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │ 1640.96  1637.84   0.19 │  4564770241509   4558564254818   0.14 │  7148259303691   7150350208967  -0.03 │ 1074628  1074776  -0.01 │   0    0    nan │
│             coq-fiat-crypto │ 4869.78  4860.03   0.20 │ 13527022756582  13501192890971   0.19 │ 23758893751024  23769900744723  -0.05 │ 2229848  2229096   0.03 │   0    0    nan │
│          coq-mathcomp-field │  219.16   218.60   0.26 │   609891742764    608156033581   0.29 │   919964910697    918423965740   0.17 │  664524   660680   0.58 │   0    0    nan │
│       coq-mathcomp-solvable │  169.96   169.49   0.28 │   473328218209    471085161970   0.48 │   667967796491    665009909817   0.44 │  693284   692804   0.07 │   0    0    nan │
│                coq-rewriter │  684.81   682.60   0.32 │  1901128300989   1895184684772   0.31 │  2927095159755   2925012197477   0.07 │ 1074804  1074956  -0.01 │   0    0    nan │
│                   coq-color │  483.93   482.21   0.36 │  1352273268675   1348819714964   0.26 │  1694919675526   1692107141602   0.17 │ 1155468  1157016  -0.13 │   0    0    nan │
│       coq-mathcomp-fingroup │   48.34    48.12   0.46 │   134068130576    133486777446   0.44 │   187089180373    186617863245   0.25 │  481664   482820  -0.24 │   0    0    nan │
│                 coq-bignums │   56.00    55.74   0.47 │   155385179327    154583986109   0.52 │   207872986327    207400060680   0.23 │  464452   463104   0.29 │   0    0    nan │
│              coq-verdi-raft │ 1066.45  1061.38   0.48 │  2969451339735   2953490862709   0.54 │  4185011744548   4181044869028   0.09 │  918044   917872   0.02 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1047.05  1041.07   0.57 │  2917529752612   2898206886557   0.67 │  4614537652268   4596146064431   0.40 │  906684   959804  -5.53 │   0    0    nan │
│                 coq-coqutil │   59.52    59.18   0.57 │   164898203623    164505810490   0.24 │   217487677149    216358330232   0.52 │  601196   599624   0.26 │   0    0    nan │
│               coq-fiat-core │  108.11   107.48   0.59 │   305629307708    303554389837   0.68 │   410637739417    407242366960   0.83 │  479308   480056  -0.16 │   0    0    nan │
│                coq-bedrock2 │  303.56   301.73   0.61 │   841770147057    837240141691   0.54 │  1492078768486   1490258931456   0.12 │  800128   777672   2.89 │   0    0    nan │
│                   coq-verdi │   98.24    97.45   0.81 │   270501814156    268287463811   0.83 │   378477994713    376668409756   0.48 │  542388   542784  -0.07 │   0    0    nan │
│              coq-coquelicot │   69.32    68.40   1.35 │   188827395642    187104499858   0.92 │   242485321805    239111475043   1.41 │  558368   557540   0.15 │   0    0    nan │
│      coq-mathcomp-ssreflect │   55.06    53.97   2.02 │   149934551741    148332785125   1.08 │   193583983223    192139425105   0.75 │  528720   529176  -0.09 │   0    0    nan │
│               coq-perennial │ 7521.18  7284.36   3.25 │ 20946865777461  20292819748871   3.22 │ 31702778084085  31016497921851   2.21 │ 2985348  3152756  -5.31 │   0    0    nan │
│             coq-lambda-rust │ 1334.89  1268.99   5.19 │  3714253744973   3532103106318   5.16 │  5292783525981   5079487083889   4.20 │ 1115816  1103100   1.15 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by gares** [comment]
I suspect that the performance problem in lambda rust comes from an interactively Defined constant/instance which is less simplified than before and hence requires Coq's conversion check to run longer.

**Comment by Blaisorblade** [comment]
@gares’ theory make sense to me, also because the `solve_proper*` stdpp tactics use `simpl` in the `solve_proper_unfold` step (which is pretty heuristic and demands a certain coding discipline).*

*stdpp’s `solve_proper` and `f_equiv` are not to be confused with Coq’s ones.

**Comment by gares** [comment]
Thanks @ppedrot for the analysis. I'm off today, but if @ybertot pushes a fix for the last comment we can rerun the benches and see where we are next week.

**Comment by gares** [comment]
And sorry for the bogus analysis, I must have misused the tool for comparing the timings

**Comment by silene** [comment]
Said otherwise, this pull request transitively modifies `hnf`, which is used all over the place. Keeping the behavior of `simpl` and `hnf` as close as possible is presumably a good idea, but it should at least be mentioned in the change log.

**Comment by SkySkimmer** [comment]
#15026 for iris/lambda rust
opam dev packages for compcert and vst have the wrong flocq dependency and nobody can be bothered to fix them

**Comment by gares** [comment]
OK, then perennial is probably fixed while iris is still affected. @ppedrot would you help me again to pinpoint the problem in there?

**Comment by SkySkimmer** [comment]
Seems unlikely to make it for 8.15

**Comment by gares** [comment]
@ppedrot would you help me again to pinpoint the problem in there?

@SkySkimmer fine

**Comment by ppedrot** [comment]
@gares I'll have a look, but I am afraid I don't have the time right now so this will need to be backported / delayed to 8.16.

**Comment by gares** [comment]
> @gares I'll have a look, but I am afraid I don't have the time right now so this will need to be backported / delayed to 8.16.

RFH still open ;-)

**Comment by gares** [comment]
This is just a polite ping in case @ppedrot has a few spare cycles.

**Comment by Alizter** [comment]
@ppedrot ping

**Comment by ppedrot** [comment]
I have rebased to get a clean CI. I had a look at the code and apart from minor cosmetic tweaks I don't see anything suspicious, in particular that could trigger a slowdown by mistake. I'll rerun a bench when the CI finishes.

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by gares** [comment]
As I did recall, there fix in the semantics of simpl comes at some extra cost. I'm personally fine with it @ppedrot, but maybe you can find out if it is really necessary.

**Comment by ppedrot** [comment]
I didn't find anything really suspicious in the diffs. It's a bit sad that we cannot completely eliminate the very small slowdown, but if this cannot be helped I'm fine with merging this PR as-is (modulo a bit of squashing maybe).

**Comment by gares** [comment]
I'm a bit worried that VST is not part of the bench, and IIRC @MSoegtropIMC reported slow calls to simpl. I also know he is eliminating simple in favor of a fine tuned cbv, but I don't know if that happened already.

Maybe we should wait VST to be working again an re-run the bench.

**Comment by MSoegtropIMC** [comment]
No, I had to delay my PR in favour of the Coq Platform release (which had a new tricky CI issue every week). It will anyway be a longer process. My PR just includes the machinery and a few example usages and the VST team is going to replace simpl with this mechanism piece by piece. I guess it will take 6 month.

@andrew-appel: FYI.

**Comment by gares** [comment]
@coqbot bench

**Comment by gares** [comment]
vst is still broken in the bench, do we know why?
I just want to check the slowdown is not horrible and then merge. cc @coq/bench-maintainers

**Comment by SkySkimmer** [comment]
It says `- Makefile:130: *** COMPCERT VERSION MISMATCH: COMPCERT_VERSION=version=3.11 but /home/gitlab-runner/builds/av_eR6za/0/coq/coq/_bench/opam.NEW/ocaml-NEW/lib/coq/user-contrib/compcert/VERSION=version=3.12.  Stop.`

**Comment by andrew-appel** [comment]
For the last few years, the VST within the Coq CI has used the "bundled" version of CompCert (that is, an internal copy of the few CompCert files that VST imports) precisely to avoid this kind of problem.  Apparently that changed recently in the Coq CI.  One way to fix this is to set COMPCERT=bundled, either as an argument to make or in a CONFIGURE file that make reads.

Regarding the VST / COMPCERT mismatch:  I've reviewed the changes in CompCert between CompCert 3.11 and 3.12, and I expect that VST (2.11.1 or master branch) will be equally compatible with either of them.   So we could imagine a different workaround, some sort of IGNORECOMPCERTVERSION flag that tells the Makefile to skip the test at line 129.

**Comment by gares** [comment]
Metacoq is also failing. Sorry but I can't find the error message you copied @SkySkimmer (maybe I just need more sleep).

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/3666095209/artifacts/external_file/_bench/logs/coq-vst.NEW.opam_install.1.stdout.log

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
VST is fine it seems.

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot merge now

CC @ybertot

File: dev/ci/user-overlays/13448-ybertot-fix_simpl_never_wrt_delta.sh [hunk 11]
```diff
@@ -0,0 +1,3 @@
+overlay hott https://github.com/ybertot/HoTT respect_simpl_never_flags 13448
```
Comment (SkySkimmer) [inline dev/ci/user-overlays/13448-ybertot-fix_simpl_never_wrt_delta.sh:1]: It seems this overlay was missed, I made https://github.com/HoTT/Coq-HoTT/pull/1713
