### PR TITLE
Fixes #12417: check that the argument of "wf" in funind is a well-typed relation

### LINKED ISSUE #12417: Encountered an Anomaly when defining a Function
## Description of the problem
Hi, I am trying to define a function with a non-standard recursion pattern and encountered an
anomaly on the sum_total function: ' Anomaly "Uncaught exception Retyping.RetypeError(0)." '
```coq
Require Import List.
Require Export PeanoNat.
Require Export Omega.
Require Export CpdtTactics.
Require Import FunInd.
Require Import Recdef.

Notation "A :: B" := (cons A B).
Notation "[]" := nil.
Notation "[[ A ]]" := (A :: nil).

Inductive tm :=
| E: nat -> tm
| L: list tm -> tm.

Definition T := list tm.

Fixpoint max_list (p: nat) (l: list nat) : nat :=
  match l with
  | [] => p
  | n :: l' => max_list (Init.Nat.max n p) l'
  end.

Fixpoint depth (t: tm) : nat :=
  match t with
  | E _ => 0
  | L l => 1 + max_list 0 (map depth l)
  end.

Fixpoint sum_depth (l: T) : nat :=
  match l with
  | [] => 0
  | n :: l' => (depth n) + sum_depth l'
  end.

Definition sum_depth_order (t1 t2 : T) :=
  sum_depth t1 < sum_depth t2.

Hint Constructors Acc.

Lemma sum_depth_order_wf' : forall d l, sum_depth l <= d ->
  Acc sum_depth_order l.
Proof.
  unfold sum_depth_order. induction d; intros.
  - assert (sum_depth l = 0). omega.
    apply Acc_intro. intros. omega.
  - apply Acc_intro. intros. assert (sum_depth y <= d). omega.
    apply IHd. auto.
Defined.

Theorem sum_depth_order_wf : well_founded sum_depth_order.
Proof.
  unfold well_founded. unfold depth_order. intros.
  eapply sum_depth_order_wf'. eauto.
Defined.

Function sum_total (l: T) {wf sum_depth l} : nat :=
  match l with
  | [] => 0
  | t :: l' =>
    (match t with
      | E n => n
      | L li => sum_total li
      end) + sum_total l'
  end.
```
#### Coq Version
8.10.1 on MacOs Mojave 10.14.5

### PR DESCRIPTION
**Pull request by herbelin**
Fixes / closes #12417

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
@coqbot run full ci

File: plugins/funind/recdef.ml [hunk 1]
```diff
@@ -1615,6 +1615,22 @@ let com_eqn uctx nb_arg eq_name functional_ref f_ref terminate_ref
   in
   ()
 
+let check_relation_type env evd relation =
```
Comment (ppedrot) [inline plugins/funind/recdef.ml:1618]: This is too restrictive, you're asking for a type that is syntactically equal to some relation but you should probably use conversion instead. I'd recommend using `Reductionops.dest_arity`.

Comment (herbelin) [reply plugins/funind/recdef.ml:1618]: Indeed, that was rather naive. `Reductionops.dest_arity` keeps let-ins I think, so, we can also adds `whd_all` ourselves. I'll push a new version when CI is done.

File: plugins/funind/recdef.ml [hunk 2]
```diff
@@ -1615,6 +1615,23 @@ let com_eqn uctx nb_arg eq_name functional_ref f_ref terminate_ref
...
+  let err () = CErrors.user_err (strbrk "a well-founded relation is expected to be of type A->A->Prop for some type A.") in
+  let evd, t = Typing.type_of env evd relation in
+  let open Reductionops in
+  match EConstr.kind evd (whd_all env evd t) with
```
Comment (ppedrot) [inline plugins/funind/recdef.ml:1622]: The env below are incorrect since the Prod constructor binds a variable. Really, I think it'd be cleaner to use dest_arity and filter the result. (Also this is spaghetti code.)

**Comment by ppedrot** [comment]
ping @herbelin

**Comment by ppedrot** [comment]
ping @herbelin this is fairly trivial

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@SkySkimmer I tweaked the test, hopefully it should go through now.

**Comment by SkySkimmer** [comment]
@coqbot merge now
