### PR TITLE
More principled implementation of Btermdnet matching

### LINKED ISSUE #13209: TC search treats `match` (`if`) as TC-opaque
#### Description of the problem

In the following example, only the first and third calls to `apply _` succeed. It is hard to say which calls should succeed but I think it is rather reasonable to say that the current behaviour is surprising.

```coq
Class A (n : nat) := {}.
Definition three := 3.
Instance A_three : A three := {}.
Definition three' := if true then three else 1.
(* 1 *) Goal A (if true then three else 1). apply _. Qed.
Hint Opaque three : typeclass_instances.
(* 2 *) Goal A (if true then three else 1). Fail apply _. Abort.
(* 3 *) Goal A (three'). apply _. Qed.
```

Here is my interpretation of what Coq is doing:
1) Coq sees a TC-opaque `if` term and a TC-transparent constant `three` and it given the usual rule of TC search Coq optimistically tries to unify them since at least one of them is TC-transparent.
2) Coq sees a TC-opaque `if` term in the goal and an instance on the TC-opaque constant `three` and concludes that it should not attempt to unify these two because both are TC-opaque.
3) Coq sees a TC-transparent constant `three'` and a TC-opaque constant `three` and attempts to unify them since one of them is TC-transparent.

So basically this makes total sense if you buy the assumption that `if` (i.e. `match`) terms should be TC-opaque. However, given the counter-intuitive consequences of this choice and the fact that basically anything else is considered transparent by default I wonder if it wouldn't make more sense to make `match` terms TC-transparent by default at least for now? Alternatively (but also independently) maybe Coq should have a `Hint Match Transparent/Opaque` command?

There is some discussion about this in zulip: https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Opaque.20does.20not.20imply.20Typeclasses.20Opaque

#### Coq Version
8.11.2

### PR DESCRIPTION
**Pull request by ppedrot**
We try to move closer to an overapproximation of neutral forms for βι-reduction, up to η-conversion. Before, case nodes were incorrectly mapped to Nothing, even if they could have ι-reduced to an arbitrary term. Now we consider them to match anything, which is a bit violent and should probably be handled in a more subtle manner in a future patch. We also handle undiscriminated β-redexes as arbitrary patterns for good measure.

Finally, this also removes a very weird part of the code which was probably there for bad reasons. Notably, the dnet matching algorithm was so ad-hoc that it would match (or not) many things erroneously, so that the ground check was there allow to bypass those bugs without much fuss.

Fixes #13209: TC search treats match (if) as TC-opaque.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1507802394

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
Further minimization of the compcert failure:
```
Definition ptr64 := false.

Inductive val: Set := Vundef: val.

Inductive lessdef: val -> val -> Prop := lessdef_undef: forall v, lessdef Vundef v.

Global Hint Resolve lessdef_undef : foo.

Axiom memval : Set.
Axiom load_result : memval -> val.

Lemma foo : forall (v : val)
  (vl' : memval), lessdef (if ptr64 then load_result vl' else Vundef) v.
Proof.
intros vl'.
auto with foo.
Qed.
```
The root of the failure is that btermdn pattern recognition does not realize that the if can be reduced by unfolding `ptr64`. Since we don't want to perform agressive βδι-reduction  I guess we'll have to match everything in this case...

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1514200166

**Comment by Janno** [comment]
> The root of the failure is that btermdn pattern recognition does not realize that the if can be reduced by unfolding `ptr64`. Since we don't want to perform agressive βδι-reduction I guess we'll have to match everything in this case...

Any connection to https://github.com/coq/coq/issues/13209?

**Comment by ppedrot** [comment]
Probably. The PRs I have been writing around Btermdn are precisely trying to put a bit of order around the semantics of dn matching, which was pretty crazy before. Now we're essentially using an (overapproximation) of syntactic equality on neutral forms for βι-reduction up to η-equality. There are still a few weird cases (notably for let-ins) but it should be saner.

**Comment by ppedrot** [comment]
Indeed, I confirm that #13209 is solved by this PR.

**Comment by Janno** [comment]
On second thought, I suppose I shouldn't be too happy before I understand this fully. Does this PR fix the bug by treating `if`s as matching everything in a symmetric way? If so, it might be bad news because that would bring down the performance of some of our proofs by quite a bit. We have hints keyed on `if`s and they always match everything. Obviously I would prefer if they only matched `if` terms but at least we only get one multiplicative factor (number of hints keyed on `if` times all possible application sites in the goal). If we now have `if` terms in the goal that also match all other hints we will pay a much higher price.

Would it be reasonable to return `Everything` *only if* the condition returns `Everything`. That would sense to me.

**Comment by ppedrot** [comment]
> Would it be reasonable to return Everything only if the condition returns Everything? That would make sense to me.

This is possible, but I'll do that in the next round of changes. As I mentioned above, I believe that the correct criterion is to look at neutral forms. In particular, a case over a rigid term should be considered rigid, but any other case should be considered flexible.

**Comment by ppedrot** [comment]
> that would bring down the performance of some of our proofs by quite a bit

I'd be interested if you had some self-contained benchmarking files btw.

**Comment by Janno** [comment]
> I'd be interested if you had some self-contained benchmarking files btw.

I'll see if I can figure something out.

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │  140.72   147.93  -4.87 │   389889990087    410088260242  -4.93 │   479565173162    506083712055  -5.24 │  806236   810232  -0.49 │   0    0    nan │
│               coq-fiat-core │  102.99   107.43  -4.13 │   291301143347    305686939853  -4.71 │   392689012010    412980280589  -4.91 │  475184   479888  -0.98 │   0    0    nan │
│                   coq-color │  471.16   484.65  -2.78 │  1314899422225   1352993377737  -2.82 │  1645469946014   1700268829198  -3.22 │ 1155464  1155756  -0.03 │   0    0    nan │
│                   coq-verdi │   96.83    98.94  -2.13 │   265809989802    271253356388  -2.01 │   371780544111    379512848466  -2.04 │  538736   545208  -1.19 │   0    0    nan │
│                    coq-corn │ 1439.24  1469.70  -2.07 │  4006156482155   4090174396562  -2.05 │  5756501538722   5873566067774  -1.99 │  822840   822824   0.00 │   0    0    nan │
│                  coq-geocoq │ 1310.35  1329.57  -1.45 │  3650077564742   3708666400249  -1.58 │  5364341336925   5421739183250  -1.06 │ 1056208   985268   7.20 │   0    0    nan │
│              coq-verdi-raft │ 1090.60  1100.48  -0.90 │  3036188427068   3064080972233  -0.91 │  4266470362064   4308097317710  -0.97 │  916680   916472   0.02 │   0    0    nan │
│                  coq-stdlib │  410.52   413.37  -0.69 │  1149472524364   1158629753783  -0.79 │  1460444852461   1469066118539  -0.59 │  597540   597504   0.01 │   0    0    nan │
│        coq-mathcomp-algebra │  138.50   139.44  -0.67 │   385333665809    386797586104  -0.38 │   502398676993    502544992514  -0.03 │  556884   556260   0.11 │   0    0    nan │
│      coq-mathcomp-ssreflect │   53.61    53.93  -0.59 │   147560488803    147357497613   0.14 │   191390109907    191578396703  -0.10 │  528796   529972  -0.22 │   0    0    nan │
│            coq-math-classes │  172.09   172.90  -0.47 │   479165060879    482847035046  -0.76 │   637205616693    641090863522  -0.61 │  481992   481980   0.00 │   0    0    nan │
│            coq-fiat-parsers │  580.00   582.22  -0.38 │  1618998586417   1630677275856  -0.72 │  2473807054097   2492225723129  -0.74 │ 3485252  3485496  -0.01 │   0    0    nan │
│              coq-coquelicot │   68.50    68.74  -0.35 │   187111238857    187673258687  -0.30 │   239743546943    241083659865  -0.56 │  558452   558952  -0.09 │   0    0    nan │
│          coq-mathcomp-field │  217.35   218.06  -0.33 │   605424864213    607032517522  -0.26 │   919024150806    918696871086   0.04 │  665720   659828   0.89 │   0    0    nan │
│                coq-coqprime │  328.04   329.08  -0.32 │   911302055984    912918498886  -0.18 │  1594729634001   1594957174333  -0.01 │  917488   914312   0.35 │   0    0    nan │
│                 coq-bignums │   55.70    55.85  -0.27 │   153825479291    154357204306  -0.34 │   206376038638    207112253809  -0.36 │  462888   463492  -0.13 │   0    0    nan │
│                 coq-coqutil │   59.52    59.61  -0.15 │   165502349661    165596085751  -0.06 │   218716366761    218385751075   0.15 │  600292   600288   0.00 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1037.58  1038.97  -0.13 │  2890513980784   2894645384006  -0.14 │  4596743895500   4597281948610  -0.01 │  910612   960048  -5.15 │   0    0    nan │
│               coq-fourcolor │ 2546.24  2549.63  -0.13 │  7098295900283   7107443697988  -0.13 │ 12238690155010  12237896039869   0.01 │  732572   732692  -0.02 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │ 1629.62  1631.40  -0.11 │  4533646474110   4540201396473  -0.14 │  7150821404630   7150309933450   0.01 │ 1073920  1073900   0.00 │   0    0    nan │
│       coq-mathcomp-solvable │  168.85   168.99  -0.08 │   469686700779    470371561217  -0.15 │   665465297352    665517658413  -0.01 │  692576   690832   0.25 │   0    0    nan │
│      coq-mathcomp-character │  148.03   148.15  -0.08 │   411447432409    411959119711  -0.12 │   576402157618    576840979782  -0.08 │  732024   724988   0.97 │   0    0    nan │
│             coq-lambda-rust │ 1275.52  1276.30  -0.06 │  3548484279640   3550689504784  -0.06 │  5088657308677   5090761902101  -0.04 │ 1104688  1079932   2.29 │   0    0    nan │
│                    coq-hott │  297.14   297.31  -0.06 │   818301103771    818080379172   0.03 │  1268800877308   1268836973776  -0.00 │  571040   570876   0.03 │   0    0    nan │
│                 coq-unimath │ 4634.05  4634.95  -0.02 │ 12894885541396  12893700755756   0.01 │ 24852056164125  24871284376909  -0.08 │ 3711856  3711920  -0.00 │   0    0    nan │
│       coq-mathcomp-fingroup │   48.24    48.22   0.04 │   133271341280    133409473149  -0.10 │   186929659587    186818366763   0.06 │  483488   483344   0.03 │   0    0    nan │
│               coq-perennial │ 7257.31  7250.02   0.10 │ 20211608851066  20196793317344   0.07 │ 30727715175326  30728643850467  -0.00 │ 2999088  3007580  -0.28 │   0    0    nan │
│  coq-performance-tests-lite │ 1402.04  1400.63   0.10 │  3912469891589   3907772173258   0.12 │  6331750147256   6330596457479   0.02 │ 2085112  2085056   0.00 │   0    0    nan │
│             coq-fiat-crypto │ 4853.82  4840.29   0.28 │ 13479299106750  13446851005450   0.24 │ 23775115703938  23767965151843   0.03 │ 2233084  2232904   0.01 │   0    0    nan │
│                coq-bedrock2 │  303.28   302.20   0.36 │   840852940291    839110798383   0.21 │  1493347762666   1492524417825   0.06 │  800008   778536   2.76 │   0    0    nan │
│       coq-engine-bench-lite │  292.78   291.72   0.36 │   824676124138    822244574343   0.30 │  1501348797647   1497035934220   0.29 │ 1411884  1411904  -0.00 │   0    0    nan │
│                coq-rewriter │  684.74   682.23   0.37 │  1899425798774   1892346754106   0.37 │  2932652424993   2931304684577   0.05 │ 1073916  1073752   0.02 │   0    0    nan │
│                    coq-core │  108.20   107.15   0.98 │   298976151656    298191299864   0.26 │   462625232586    462580732697   0.01 │  299072   299004   0.02 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
Pretty good bench.

**Comment by ppedrot** [comment]
I deem this ready, even if this might introduce slowdowns in some of @Janno 's examples. There is always room for improvement by βι-normalizing on the fly. The current PR emphasizes soundness over efficiency.

File: tactics/btermdn.ml [hunk 1]
```diff
@@ -89,7 +89,12 @@ let evaluable_named id env ts =
   (try Environ.evaluable_named id env with Not_found -> true) &&
   (match ts with None -> true | Some ts -> TransparentState.is_transparent_variable ts id)
 
+(* The pattern view functions below try to overapproximate βι-neutral terms up
+   to η-conversion. Some historical design choices are still incorrect w.r.t. to
+   this specification. TODO: try to make them follow the spec. *)
```
Comment (Janno) [inline tactics/btermdn.ml:94]: Since you are already adding comments, could you elaborate a bit on this specification? I am not sure I really understand `βι-neutral`. Are those neutral terms (in the traditional sense) that also do not create new iota reduction steps when composed via application?
It might also be worth expanding on the `η-conversion` bit since that depends on the optional transparency state IIUC.

File: test-suite/bugs/closed/bug_13209.v [hunk 2]
```diff
@@ -0,0 +1,8 @@
+Class A (n : nat) := {}.
+Definition three := 3.
+Instance A_three : A three := {}.
+Definition three' := if true then three else 1.
+(* 1 *) Goal A (if true then three else 1). apply _. Qed.
+Hint Opaque three : typeclass_instances.
+(* 2 *) Goal A (if true then three else 1). apply _. Qed.
```
Comment (Janno) [inline test-suite/bugs/closed/bug_13209.v:7]: I see some MRs adding comments about the exact failure that was fixed. Is there a convention for that? (Same question below about the test case for #14788)

**Review by Janno — APPROVED** [review]
I am not a maintainer of anything so my approval doesn't count. However, I have reviewed these changes and I think they make sense. I left two comments but they don't relate to the actual code changes.

Obviously I would prefer to not include the overapproximation of `if` terms in the way it is done now. But before we delay these changes here any longer I will simply look forward to reviewing the next change that refines this. :)

File: tactics/btermdn.ml (hunk 1 above)
Comment (ppedrot) [reply tactics/btermdn.ml:94]: > Are those neutral terms (in the traditional sense)

Yes, neutral means that it's normal and it won't create a redex when substituted inside a context (not only β via application, but also ι when substituted inside a case). This is the reason we need to be clever w.r.t. to η-expansion since it might turn an actual neutral into a non-neutral. Also note that constructors are not neutral but we consider them here nonetheless for pattern recognition.

> that depends on the optional transparency state

Does it? We perform η-contraction regardless of the ts. Lambda-abstractions are not classified the same whether we're discriminated or not, but it should be uncommon to hit a difference and it shouldn't affect the η-quotient anyways. In any case I am going to try to get those behaviours even closer, so that in the end the only different between them is that in undiscriminated mode all references should be considered transparent.

Comment (Janno) [reply tactics/btermdn.ml:94]: > Does it? We perform η-contraction regardless of the ts. 

Oh, of course. I am not sure why but even after spending half a minute looking for the right key combination to write `η` I still read it as `δ`. Disregard that part of my comment.

File: test-suite/bugs/closed/bug_13209.v (hunk 2 above)
Comment (ppedrot) [reply test-suite/bugs/closed/bug_13209.v:7]: No convention, but if you want you can push a commit that adds a comment to this PR.

**Comment by Janno** [comment]
While documenting the fixed failure in #13209 I realized that the other test case doesn't fail on 8.13.2. Does it only fail on master?

**Comment by ppedrot** [comment]
@Janno yes, it was discovered while writing this patch. I've added it to expand the test coverage of btermdn behaviour from the wild.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now
