### PR TITLE
Fix returning delimiter instead of scope name for About in specific scope

### LINKED ISSUE #20754: Unable to get notation scope correct in About and Print
### Description of the problem

When querying a notation in a scope with Print and About, there is an error for both scope options.
In repl :
```
Rocq < About "_ * _"%type.
Toplevel input, characters 0-19:
> About "_ * _"%type.
> ^^^^^^^^^^^^^^^^^^^
Error: Scope type is not declared.

Rocq < About "_ * _"%type_scope.
Toplevel input, characters 0-25:
> About "_ * _"%type_scope.
> ^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unknown scope delimiting key type_scope.
```
I don't know which one (or both) should work.

I investigated the issue and it seems to be a conflict between what is done [here](https://github.com/rocq-prover/rocq/blob/780f301e9299d3d1a1dd736268c941785e08e88f/interp/notation.ml#L2498) and [there](https://github.com/rocq-prover/rocq/blob/780f301e9299d3d1a1dd736268c941785e08e88f/interp/notation.ml#L2760C68-L2760C78). Both are called near [here for About](https://github.com/rocq-prover/rocq/blob/780f301e9299d3d1a1dd736268c941785e08e88f/vernac/prettyp.ml#L1091) and [there for Print](https://github.com/rocq-prover/rocq/blob/780f301e9299d3d1a1dd736268c941785e08e88f/vernac/prettyp.ml#L1007).

### Small Rocq / Coq file to reproduce the bug

```coq
About "_ * _"%type.
About "_ * _"%type_scope.
Print "_ * _"%type.
Print "_ * _"%type_scope.
```

### Version of Rocq / Coq where this bug occurs

8.20.0, 9.0.0

### Interface of Rocq / Coq where this bug occurs

All

### Last version of Rocq / Coq where the bug did not occur

8.19.2

### PR DESCRIPTION
**Pull request by SkySkimmer**
interp_notation_as_global_reference_expanded returns the scope name, gotten from the key in the scope map.

When checking a specific scope (`About "foo"%bar`) it is specified using it delimiter, and we would produce a map restricted to that scope but incorrectly using the delimiter instead of the scope name.

Then the delimiter would be returned and used as a scope name, leading to errors.

Fix #20754

### CODE REVIEW

File: interp/notation.ml [hunk 1]
```diff
@@ -2494,9 +2494,9 @@ let error_notation_not_reference ?loc ntn ntns =
 
 let interp_notation_as_global_reference_expanded ?loc ~head test ntn sc =
   let scopes = match sc with
-  | Some sc ->
-      let scope = find_scope (find_delimiters_scope sc) in
-      String.Map.add sc scope String.Map.empty
+    | Some sc ->
```
Comment (proux01) [inline interp/notation.ml]: That indentation change looks strange

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now
