### PR TITLE
Ad hoc fix for #12298: flushing defined Ltac evars in tactical abstract

### LINKED ISSUE #12298: Anomaly "Evar ?X166 was not declared." with (transparent_)abstract
#### Description of the problem

(smaller example a couple comments later)

```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-w" "-notation-overridden" "-R" "." "PerformanceExperiments" "-top" "make_nested_sig_abstraction_common") -*- *)
(* File reduced by coq-bug-finder from original input, then from 195 lines to 176 lines, then from 213 lines to 179 lines, then from 194 lines to 180 lines *)
(* coqc version 8.11.1 (April 2020) compiled on Apr 4 2020 17:41:20 with OCaml 4.06.1
   coqtop version 8.11.1 (April 2020) *)

Module Export DynList.
  Inductive t := nil | cons {T} (v : T) (rest : t).
  Infix "::" := cons (at level 60, right associativity) : dyn_scope.
  Notation "[ ]" := nil (format "[ ]") : dyn_scope.
  Notation "[ x ]" := (cons x nil) : dyn_scope.
End DynList.

Ltac cache_term T v name :=
  let H := fresh in
  let T := constr:(T) in
  let __ := lazymatch constr:(Set) with
            | _
              => simple refine (let H : T := _ in _);
                 [ transparent_abstract exact v using name
                 | ]
            end in
  lazymatch goal with
  | [ H := ?v |- _ ]
    => let __ := match goal with _ => clear H end in
       v
  end.

Local Open Scope dyn_scope.
Ltac make_Ts count mkSigT mkExistT mkProjT1 mkProjT2 mkSigTEta cont :=
  let hd x := lazymatch x with ?v :: _ => v end in
  lazymatch count with
  | 0
    => let _T       := fresh "_T0" in
       let _Build_T := fresh "Build_T0" in
       let _T_proj  := fresh "_proj_T0" in
       let _T_eta   := fresh "_eta_T0" in
       let _T_ty       := constr:(Set) in
       let _T          := cache_term _T_ty
                                     unit
                                     _T in
       let _Build_T_ty := constr:(unit -> _T) in
       let _Build_T    := cache_term _Build_T_ty
                                     (fun x0 : unit => x0)
                                     _Build_T in
       let _T_proj_ty  := constr:(_T -> unit) in
       let _T_proj     := cache_term _T_proj_ty
                                     (fun x0 : _T => x0)
                                     _T_proj in
       let _T_eta_ty   := constr:(forall x : _T, x = _Build_T (_T_proj x) :> _T) in
       let _T_eta      := cache_term _T_eta_ty
                                     (fun x : _T => @eq_refl _T x)
                                     _T_eta in
       cont (@DynList.cons _T_ty _T DynList.nil)
            (@DynList.cons _Build_T_ty _Build_T DynList.nil)
            (@DynList.cons _T_proj_ty _T_proj DynList.nil)
            (@DynList.cons _T_proj_ty _T_proj DynList.nil)
            (@DynList.cons _T_eta_ty _T_eta DynList.nil)
  | S ?count
    => let cont' _Ts _Build_Ts _T_proj1s _T_proj2s _T_etas
           := let _T'       := hd _Ts in
              let _Build_T' := hd _Build_Ts in
              let _T_proj1' := hd _T_proj1s in
              let _T_proj2' := hd _T_proj2s in
              let _T_eta'   := hd _T_etas in
              let _T       := fresh "_T0" in
              let _Build_T := fresh "Build_T0" in
              let _T_proj1 := fresh "_proj1_T0" in
              let _T_proj2 := fresh "_proj2_T0" in
              let _T_eta   := fresh "_eta_T0" in
              let _T_ty       := constr:(Set) in
              let _T_v        := mkSigT unit _T' in
              let _T          := cache_term _T_ty
                                            _T_v
                                            _T in
              let _Build_T_ty := constr:(unit -> _T' -> _T) in
              let _Build_T_v  := mkExistT unit _T' in
              let _Build_T    := cache_term _Build_T_ty
                                            _Build_T_v
                                            _Build_T in
              let _T_proj1_ty := constr:(_T -> unit) in
              let _T_proj1_v  := mkProjT1 unit _T' in
              let _T_proj1    := cache_term _T_proj1_ty
                                            _T_proj1_v
                                            _T_proj1 in
              let _T_proj2_ty := constr:(_T -> _T') in
              let _T_proj2_v  := mkProjT2 unit _T' in
              let _T_proj2    := cache_term _T_proj2_ty
                                            _T_proj2_v
                                            _T_proj2 in
              let _T_eta_ty   := constr:(forall x : _T, x = _Build_T (_T_proj1 x) (_T_proj2 x) :> _T) in
              let _T_eta_v    := mkSigTEta unit _T' in
              let _T_eta      := cache_term _T_eta_ty
                                            _T_eta_v
                                            _T_eta in
              cont (@DynList.cons _T_ty _T _Ts)
                   (@DynList.cons _Build_T_ty _Build_T _Build_Ts)
                   (@DynList.cons _T_proj1_ty _T_proj1 _T_proj1s)
                   (@DynList.cons _T_proj2_ty _T_proj2 _T_proj2s)
                   (@DynList.cons _T_eta_ty _T_eta _T_etas) in
       make_Ts count mkSigT mkExistT mkProjT1 mkProjT2 mkSigTEta cont'
  end.

Ltac make_T _Ts :=
  let hd x := lazymatch x with ?v :: _ => v end in
  let tl x := lazymatch x with _ :: ?v => v end in
  let T := fresh "T" in
  let _T' := hd _Ts in
  cache_term Set _T' T.

Ltac make_T_projs T _Ts _T_proj1s _T_proj2s proj_T_rest' cont :=
  let hd x := lazymatch x with ?v :: _ => v end in
  let tl x := lazymatch x with _ :: ?v => v end in
  let _T'_proj1 := hd _T_proj1s in
  let _T_proj1s := tl _T_proj1s in
  let proj_T      := fresh "proj_T_1" in
  let proj_T_ty      := constr:(T -> unit) in
  let proj_T_v       := constr:(fun x : T => _T'_proj1 (proj_T_rest' x)) in
  let proj_T         := cache_term proj_T_ty proj_T_v proj_T in
  lazymatch _Ts with
  | DynList.nil
    => cont (@DynList.cons proj_T_ty proj_T DynList.nil) DynList.nil
  | ?_T :: ?_Ts
    => let _T'_proj2 := hd _T_proj2s in
       let _T_proj2s := tl _T_proj2s in
       let proj_T_rest := fresh "proj_T_rest_1" in
       let proj_T_rest_ty := constr:(T -> _T) in
       let proj_T_rest_v  := constr:(fun x : T => _T'_proj2 (proj_T_rest' x)) in
       let proj_T_rest    := cache_term proj_T_rest_ty proj_T_rest_v proj_T_rest in
       let cont' proj_Ts proj_T_rests
           := cont (@DynList.cons proj_T_ty proj_T proj_Ts)
                   (@DynList.cons proj_T_rest_ty proj_T_rest proj_T_rests) in
       make_T_projs T _Ts _T_proj1s _T_proj2s proj_T_rest cont'
  end.

Ltac make_Build_T_ty T _Build_Ts :=
  lazymatch _Build_Ts with
  | [] => T
  | _ :: ?_Build_Ts
    => let res := make_Build_T_ty T _Build_Ts in
       uconstr:(unit -> res)
  end.

Ltac make_Build_T T _Build_Ts :=
  let Build_T_ty := make_Build_T_ty T _Build_Ts in
  let __ := match goal with
            | _ => simple refine (let H : Build_T_ty := _ in
                                  _);
                   [ let rec iter _Build_Ts cont :=
                         let x := fresh "x" in
                         intro x;
                         lazymatch _Build_Ts with
                         | [?_Build_T] => cont uconstr:(_Build_T x)
                         | ?_Build_T :: ?_Build_Ts
                           => iter _Build_Ts ltac:(fun res => cont uconstr:(_Build_T x res))
                         end in
                     iter _Build_Ts ltac:(fun res => refine res)
                   | ]
            end in
  lazymatch goal with
  | [ H := ?v |- _ ]
    => let __ := match goal with _ => clear H end in
       let Build_T := fresh "Build_T" in
       cache_term Build_T_ty v Build_T
  end.

Goal True.
  let hd x := lazymatch x with ?v :: _ => v end in
  let tl x := lazymatch x with _ :: ?v => v end in
  let mkSigT A B := constr:(@sigT A (fun _ : A => B)) in
  let mkExistT A B := constr:(@existT A (fun _ : A => B)) in
  let mkProjT1 A B := constr:(fun x : @sigT A (fun _ : A => B) => @projT1 A (fun _ : A => B) x) in
  let mkProjT2 A B := constr:(fun x : @sigT A (fun _ : A => B) => @projT2 A (fun _ : A => B) x) in
  let mkSigTEta A B := constr:(@sigT_eta A (fun _ : A => B)) in
  let cont _Ts _Build_Ts _T_proj1s _T_proj2s _T_etas :=
      let T := make_T _Ts in
      let _T := hd _Ts in
      let _Ts' := tl _Ts in
      let cont proj_Ts proj_T_rests :=
          let Build_T := make_Build_T T _Build_Ts in
          idtac T proj_Ts Build_T proj_T_rests _Ts _Build_Ts _T_proj1s _T_proj2s _T_etas in
      make_T_projs T _Ts' _T_proj1s _T_proj2s constr:(fun x : T => x) cont in
  make_Ts 5 mkSigT mkExistT mkProjT1 mkProjT2 mkSigTEta cont.
(* Error: Anomaly "Evar ?X166 was not declared."
Please report at http://coq.inria.fr/bugs/.
*)
```
#### Coq Version

8.11.0

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** fix

This is an ad hoc fix for #12298 to mitigate the difficult interaction between `abstract` and defined existential variables occurring in Ltac values.

Fixes / closes #12298

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by JasonGross** [comment]
@coqbot CI minimize

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1432883247.

File: plugins/ltac/tacinterp.ml [hunk 1]
```diff
@@ -309,6 +309,23 @@ let extend_values_with_bindings (ln,lm) lfun =
...
 
+let flush_value_evars sigma v =
+  if has_type v (topwit wit_constr) then
+    let c = out_gen (topwit wit_constr) v in
+    let c =
+      try EConstr.of_constr (Evarutil.flush_and_check_evars sigma c)
+      with Evarutil.Uninstantiated_evar _ ->
+        (* How to tell to not use this binding anymore? *)
+        (* If it is used it might fail because of the evar *)
+        (* But this has to work if it is not used *)
```
Comment (SkySkimmer) [inline plugins/ltac/tacinterp.ml:320]: We could map to some special `wit`?

Comment (herbelin) [reply plugins/ltac/tacinterp.ml:320]: You mean some `wit_unavailable` which triggers an error when we try to access it, or something like that?

Comment (ppedrot) [reply plugins/ltac/tacinterp.ml:320]: In any case, this wouldn't be a genarg but a toplevel tag value. And I don't think it would be a special value precisely because we want to share toplevel representations as much as possible.

Comment (SkySkimmer) [reply plugins/ltac/tacinterp.ml:320]: >You mean some wit_unavailable which triggers an error when we try to access it, or something like that?

yes
>In any case, this wouldn't be a genarg but a toplevel tag value. And I don't think it would be a special value precisely because we want to share toplevel representations as much as possible.

I don't know what any of this means.

Comment (ppedrot) [reply plugins/ltac/tacinterp.ml:320]: Whatever. Don't mess with the bound variable environment proactively, this would break some hidden invariants. This PR is a hackish workaround, instead we should make clients more robust. The problem is much more general than abstract, most functions should tolerate terms with missing evars or variables and fail gracefully instead of raising anomalies.

**Review by ppedrot — APPROVED** [review]
