### PR TITLE
Fixes #17854 anomaly: check for duplicate variables in a list of patterns was done too late for disjunctive patterns

### LINKED ISSUE #17854: Error: Anomaly "Uncaught exception Failure("hd")." Please report at http://coq.inria.fr/bugs/. with overlapping names in Constrintern.check_or_pat_variables
#### Description of the problem

```coq
From Coq Require Import Qround Sint63 Uint63 NArith PArith ZArith QArith Floats.
Local Open Scope float_scope.
Notation "'∞'" := infinity : float_scope.
Check let j := 5 in
        match Prim2SF j, Prim2SF (-j) with (* inl i or inr return *)
        | S754_nan, _ => inr nan
        | S754_zero _, _ => inl 0%Z
        | S754_infinity false, _ => inr ∞
        | S754_infinity true, _ => inr (-∞)
        | S754_finite false m e, _
          => inl (_ (e - shift)%Z)
        | S754_finite true m e, S754_finite false m e
        | S754_finite true m e, _ => inr nan (* should be impossible *)
        end.
(* Error: Anomaly "Uncaught exception Failure("hd")."
Please report at http://coq.inria.fr/bugs/.
 *)
```

According to the backtrace, the use of floats is probably not relevant, cc @herbelin for deep pattern matching issues?

Backtrace (from `Compute` rather than `Check`)
```
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Stdlib__list.hd in file "list.ml" (inlined), line 30, characters 10-23
Called from Constrintern.check_or_pat_variables in file "interp/constrintern.ml", line 1475, characters 16-31
Called from Constrintern.internalize.intern_disjunctive_multiple_pattern in file "interp/constrintern.ml", line 2361, characters 4-49
Called from Constrintern.internalize.intern_eqn in file "interp/constrintern.ml", line 2366, characters 22-71
Called from CList.map_loop in file "clib/cList.ml", line 291, characters 21-24
Called from CList.map in file "clib/cList.ml", line 299, characters 4-18
Called from Constrintern.internalize.intern.(fun) in file "interp/constrintern.ml", line 2250, characters 20-68
Called from Constrintern.internalize.intern.(fun) in file "interp/constrintern.ml", line 2132, characters 10-91
Called from Constrintern.intern_unknown_if_term_or_type in file "interp/constrintern.ml" (inlined), line 2564, characters 2-29
Called from Vernacentries.vernac_check_may_eval in file "vernac/vernacentries.ml", line 2012, characters 11-67
Called from Vernacentries.translate_vernac.(fun) in file "vernac/vernacentries.ml", line 2568, characters 8-43
Called from Vernacextend.vtreadproofopt.(fun) in file "vernac/vernacextend.ml", line 159, characters 29-44
Called from Vernacinterp.interp_typed_vernac in file "vernac/vernacinterp.ml", line 20, characters 20-113
Called from Vernacinterp.interp_control.(fun) in file "vernac/vernacinterp.ml", line 207, characters 24-69
Called from Flags.with_modified_ref in file "lib/flags.ml", line 17, characters 14-17
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Vernacinterp.interp_gen.(fun) in file "vernac/vernacinterp.ml", line 257, characters 18-43
Called from Vernacinterp.interp_gen in file "vernac/vernacinterp.ml", line 255, characters 6-279
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Stm.Reach.known_state.reach.(fun) in file "stm/stm.ml", line 2173, characters 16-43
Called from Stm.State.define in file "stm/stm.ml", line 960, characters 6-10
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Stm.Reach.known_state.reach in file "stm/stm.ml", line 2315, characters 4-105
Called from Stm.observe in file "stm/stm.ml", line 2412, characters 4-60
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Vernac.interp_vernac in file "toplevel/vernac.ml", line 68, characters 31-52
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Flags.with_modified_ref in file "lib/flags.ml", line 17, characters 14-17
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Flags.silently in file "lib/flags.ml" (inlined), line 64, characters 19-40
Called from Vernac.load_vernac_core.loop in file "toplevel/vernac.ml", line 120, characters 8-69
Called from Vernac.load_vernac_core in file "toplevel/vernac.ml", line 124, characters 6-19
Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Vernac.load_vernac in file "toplevel/vernac.ml", line 180, characters 30-94
Called from Ccompile.compile in file "toplevel/ccompile.ml", line 64, characters 18-95
Called from Ccompile.compile in file "toplevel/ccompile.ml" (inlined), line 132, characters 2-59
Called from Ccompile.compile_file in file "toplevel/ccompile.ml", line 141, characters 4-61
Called from Coqc.coqc_main in file "toplevel/coqc.ml", line 48, characters 2-100
Called from Coqc.coqc_run in file "toplevel/coqc.ml", line 67, characters 4-36
```

This is the error message in
https://github.com/coq/coq/blob/99f5ecc2d8006a6cffdd93dc6182e45269bde573/interp/constrintern.ml#L1464-L1475
so I'm guessing the problem is that this code is not robust to duplicated identifiers?

#### Coq Version

8.17.0

### PR DESCRIPTION
**Pull request by herbelin**
Fixes #17854 anomaly when interning disjunctive pattern-matching clauses over multiple patterns with duplicate variables.

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

An easy-to-review PR for 8.18 if still possible.

### CODE REVIEW

File: interp/constrintern.ml [hunk 1]
```diff
@@ -1634,7 +1624,8 @@ let merge_aliases aliases {loc;v=na} =
   match na with
   | Anonymous -> aliases
   | Name id ->
-  let alias_ids = aliases.alias_ids @ [make ?loc id] in
+  let alias_ids = List.add_set (fun id1 id2 -> Id.equal id1.v id2.v) (make ?loc id) aliases.alias_ids in
+  (* Note: assumes that add_set adds in front, see alias_of *)
```
Comment (proux01) [inline interp/constrintern.ml:1628]: As a user I guess I would prefer a warning when I type "foobar as id as id" as it seems more likely to be a typo but why not.

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
I'll merge when CI is green.

File: interp/constrintern.ml (hunk 1 above)
Comment (herbelin) [reply interp/constrintern.ml:1628]: A warning would be easy to add. As you want.

Actually, we could even syntactically forbid nesting `as` because it is anyway useless.

Comment (proux01) [reply interp/constrintern.ml:1628]: > Actually, we could even syntactically forbid nesting as because it is anyway useless.

Indeed, that sounds like the best solution.

**Comment by proux01** [comment]
@coqbot merge now

File: interp/constrintern.ml (hunk 1 above)
Comment (proux01) [reply interp/constrintern.ml:1628]: I merged this but we can syntactically forbid nesting as in a further PR.
