### PR TITLE
Fix #8121: anomalies in native_compute with let and evars.

### LINKED ISSUE #8121: anomalies in native_compute with let and evars
#### Version

Coq 8.8

#### Description of the problem

Similarly to #8119, native compilation behave wrongly on evars.

### PR DESCRIPTION
**Pull request by ppedrot**
Même causes, mêmes effets, similar fix to #8119:
- Do not pass let-bound arguments to evars.

We seize the opportunity to remove the useless type information for Aevar.

Special fixes to native compilation:
- Evars are not handled correctly when iterating over lambda terms.
- Names.id_of_string is gone.

Fixes #8121.

### CODE REVIEW

**Comment by ppedrot** [comment]
Arg! The tests for native compilation with flambda rely on #8000...

@maximedenes Come on, #8000 should be merged quickly, it's just preventing us from actually testing the native compiler.

**Comment by maximedenes** [comment]
> @maximedenes Come on, #8000 should be merged quickly, it's just preventing us from actually testing the native compiler.

Yep, I'll do it ASAP, I was waiting to see the results of the bench you sent today.

**Comment by ppedrot** [comment]
OK, this has nothing to do with flambda in the end. The only reason this fails is that the current flambda-enabled CI deactivates native compilation, which makes the test fallback to VM computation, and hit right into bug #8119 that uses the exact same tests. O irony.

To solve this, either we merge #8122 to fix #8119, or we enable native compilation with flambda by merging #8040.

**Comment by ejgallego** [comment]
#8040 is merged now.

File: pretyping/nativenorm.ml [hunk 1]
```diff
@@ -399,22 +400,31 @@ and  nf_predicate env sigma ind mip params v pT =
...
+and nf_evar env sigma evk args =
   let evi = try Evd.find sigma evk with Not_found -> assert false in
   let hyps = Environ.named_context_of_val (Evd.evar_filtered_hyps evi) in
+  let ty = EConstr.Unsafe.to_constr @@ Evd.evar_concl evi in
   if List.is_empty hyps then begin
     assert (Int.equal (Array.length args) 0);
     mkEvar (evk, [||]), ty
   end
   else
+    let drop_let decl = match decl with
```
Comment (maximedenes) [inline pretyping/nativenorm.ml]: Same remark as the other PR.

**Review by maximedenes — DISMISSED** [review]

File: pretyping/nativenorm.ml (hunk 1 above)
Comment (ppedrot) [reply pretyping/nativenorm.ml]: OK, I introduced the combinator in the other PR, so that I'll rebase that one atop of the other once it is merged.

**Comment by ppedrot** [comment]
Same problem with Travis now, as it has the native compiler deactivated. Let's wait for #8119...

**Comment by maximedenes** [comment]
> Same problem with Travis now, as it has the native compiler deactivated. Let's wait for #8119...

Sorry, which one did you mean?

**Comment by ppedrot** [comment]
Travis failed because it has native compilation disabled and falls back to the buggy VM.

**Comment by maximedenes** [comment]
Yes, but which PR did you mean we were waiting for?

**Comment by ppedrot** [comment]
We were waiting for #8122. Now that it is in master, I've rebased atop of it. Hopefully it should work now.
