### PR TITLE
Fixes bug #6774 (anomaly with ill-typed template polymorphism).

### LINKED ISSUE #6774: Anomaly when attempting to generalize a value
#### Version

Coq 8.7.1, with CoqIDE

#### Operating system

Windows 10

#### Description of the problem

I'm messing around with types and i've ran across the following anomaly.
I do not know if the generalization i'm attempting is even possible or not, but from other tests i've done, it seems it isn't.
Rest of the issue is sample code that generates the bug.

```coq

Definition huh (b:bool) := if b then Set else Prop.
Definition lol b: huh b := if b return huh b then nat else True.
Goal (lol true) * unit.
generalize true. (* Fails with Anomaly "Uncaught exception Reduction.NotArity."
Please report at http://coq.inria.fr/bugs/. *)
```

### PR DESCRIPTION
**Pull request by herbelin**
Computation of the sort of the inductive type was done before ensuring that the arguments of the inductive type had the correct types, possibly brutally failing with `NotArity` in case one of the types expected to be typed with an arity was not so.

Fixes / closes #6774.

I made a minimal fix in a well-delimited portion of code so that when template polymorphism is replaced by full polymorphism, the code can easily be removed.

### CODE REVIEW

**Comment by maximedenes** [comment]
This seems to break stuff, and the linter complains.

File: pretyping/typing.ml [hunk 1]
```diff
@@ -49,18 +49,20 @@ let e_assumption_of_judgment env evdref j =
...
+  | hj::restjl as allj ->
+      match EConstr.kind !evdref (whd_allnolet env !evdref typ) with
+      | LetIn (_,c1,_,c2) ->
+	  apply_rec (n+1) (subst1 c1 c2) allj
       | Prod (_,c1,c2) ->
 	 if Evarconv.e_cumul env evdref hj.uj_type c1 then
 	   apply_rec (n+1) (subst1 hj.uj_val c2) restjl
 	 else
-	   error_cant_apply_bad_type env !evdref (n, c1, hj.uj_type) funj argjv
+           error_cant_apply_bad_type env !evdref (n+1, c1, hj.uj_type) funj argjv
```
Comment (SkySkimmer) [inline pretyping/typing.ml]: Why change `n` to `n+1`?

File: pretyping/typing.ml [hunk 2]
```diff
@@ -49,18 +49,20 @@ let e_assumption_of_judgment env evdref j =
...
 
-let e_judge_of_apply env evdref funj argjv =
+let e_judge_of_applied_inductive_knowing_parameters env evdref funj ind argjv =
   let rec apply_rec n typ = function
   | [] ->
       { uj_val  = mkApp (j_val funj, Array.map j_val argjv);
-        uj_type = typ }
-  | hj::restjl ->
-      match EConstr.kind !evdref (whd_all env !evdref typ) with
+        uj_type = whd_all env !evdref (EConstr.of_constr (snd (Term.decompose_prod_n_assum n (inductive_type_knowing_parameters env !evdref ind argjv)))) }
```
Comment (SkySkimmer) [inline pretyping/typing.ml]: This seems suspicious, we reduce in the original `env` even though we are under binders.

File: pretyping/typing.ml (hunk 1 above)
Comment (herbelin) [reply pretyping/typing.ml]: Because I changed the initial value of the loop from 1 to 0, so that `n` now counts the number of binders, but there is indeed a problem which is that the expected `n` is here the number of effective arguments, not the number of binders. I fixed it.

File: pretyping/typing.ml (hunk 2 above)
Comment (herbelin) [reply pretyping/typing.ml]: Indeed, thanks. I fixed it.

File: pretyping/typing.ml [hunk 3]
```diff
@@ -49,6 +49,30 @@ let e_assumption_of_judgment env evdref j =
...
+      | Prod (_,c1,c2) ->
+         if Evarconv.e_cumul env evdref hj.uj_type c1 then
+           apply_rec (n+1) (subst1 hj.uj_val c2) restjl
+         else
+           error_cant_apply_bad_type env !evdref (n, c1, hj.uj_type) funj argjv
+      | Evar ev ->
+          let (evd',t) = Evardefine.define_evar_as_product !evdref ev in
+          evdref := evd';
+          let (_,_,c2) = destProd evd' t in
+          apply_rec (n+1) (subst1 hj.uj_val c2) restjl
```
Comment (SkySkimmer) [inline pretyping/typing.ml]: Why don't we unify the domain with the type of the argument here and in e_judge_of_apply?

**Review by SkySkimmer — APPROVED** [review]
Seems like it should work.

File: pretyping/typing.ml (hunk 3 above)
Comment (herbelin) [reply pretyping/typing.ml]: Well, that's a very good question. Seems like we shall (in theory) loose solutions otherwise. I don't know how to build an example which shall reach this line in `typing.ml` though.

I shall do a different PR for it.
