### PR TITLE
Make cbn consider primitive values "constructors"

### LINKED ISSUE #20003: `cbn` does not consider literal primitive strings to be "constructors"
### Description of the problem

`simpl` seems to do the right thing. I haven't tested the other primitives but I assume they are the same.

### Small Rocq / Coq file to reproduce the bug

```coq
Require Import Stdlib.Strings.PrimString.
Definition t (s : string) := True.
Arguments t !_ /.
Goal t "test".
Proof.
  Succeed progress simpl.
  Fail progress cbn.
Abort.
```

### Version of Rocq / Coq where this bug occurs

8.20

### Last version of Rocq / Coq where the bug did not occur

_No response_

### LINKED ISSUE #20008: Incorrect handling of primitive projections with Arguments !
~~~coq
Set Primitive Projections.

Record R A := mk { p : A -> A -> A }.

Arguments mk {_} _.
Arguments p {_} _ !_ !_.

Eval cbn in fun x => p (mk (fun _ _ => 2)) x x.
(* correct (not reduced) *)

Eval cbn in fun x => p (mk (fun _ _ => 2)) 3 x.
(* correct (not reduced) *)

Eval cbn in fun x => p (mk (fun _ _ => 2)) 3 4.
(* incorrect (not reduced but should be) *)

Arguments p {_} _ !_ _.

Eval cbn in fun x => p (mk (fun _ _ => 2)) x x.
(* correct (not reduced) *)

Eval cbn in fun x => p (mk (fun _ _ => 2)) 3 x.
(* incorrect (not reduced but should be) *)

Eval cbn in fun x => p (mk (fun _ _ => 2)) 3 4.
(* correct (reduced) *)
~~~
https://github.com/coq/coq/blob/6e32b07d9f38f9ff845f80b4d13e2bb6c5996069/tactics/cbn.ml#L836 should be `curr-1` (because the principal argument is not in the stack), or we should do `strip_n_app curr (append_stack [|c|] stack)` (and then we don't need the curr == 0 branch above)

### PR DESCRIPTION
**Pull request by Janno**
Fixes / closes #20003 
Fixes / closes #20008

- [x] Added / updated **test-suite**.

- [x] Added **changelog**.
- [ ] Added / updated **documentation**.
  
  - [ ] Documented any new / changed **user messages**.
  - [ ] Updated **documented syntax** by running `make doc_gram_rsts`.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

File: tactics/cbn.ml [hunk 1]
```diff
@@ -953,6 +953,39 @@ let whd_state_gen ?csts flags env sigma =
...
+                let const = (fst const, EInstance.make (snd const)) in
+                let body = EConstr.of_constr body in
+                let cst_l = Cst_stack.add_cst ~volatile (mkConstU const) cst_l in
+                whrec cst_l (body, s' @ (Stack.append_app [|x'|] s'')))
+            | Stack.Cst_proj (p,r) ->
+              let stack = s' @ (Stack.append_app [|x'|] s'') in
+              match Stack.strip_n_app 0 stack with
+              | None -> assert false
+              | Some (_,arg,s'') ->
+                whrec Cst_stack.empty (arg, Stack.Proj (p,r,cst_l) :: s''))
```
Comment (Janno) [inline tactics/cbn.ml:974]: The entire block of code added here is copied from the `Construct` case in line 875. I suspect this particular sub-case here is actually unreachable but I am not 100% sure.

**Comment by ppedrot** [comment]
@coqbot run full ci

File: tactics/cbn.ml (hunk 1 above)
Comment (ppedrot) [reply tactics/cbn.ml:974]: As you wish.

Comment (SkySkimmer) [reply tactics/cbn.ml:974]: this is not dead code but primitive projections are a bit bugged https://github.com/coq/coq/issues/20008

**Comment by Janno** [comment]
Since we are piling on bug fixes for cbn: any chance somebody can fix (the cbn part of) https://github.com/coq/coq/issues/19387?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now
