### PR TITLE
Qualified import in coqchk

### LINKED ISSUE #5746: "make validate" passes incorrect `-Q` option to coqchk
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5746
From: @RalfJung
Reported version: 8.7+beta1
CC:   @ejgallego, @silene

### PR DESCRIPTION
**Pull request by ppedrot**
This PR fixes #5746 by introducing the `-Q` option in `coqchk` which acts the same as `-R`. It also cleans up the flags by making `-I` deprecated and synonymous for `-Q`, as `-I` does not make sense in the checker (in `coqtop` it manipulates the ML loadpaths).

We also take advantage of this loadpath-related patch to get rid of the ad-hoc behaviour of `coqchk` to consider single identifier arguments as being implicitly relative. Now all arguments are taken to be absolute.

### CODE REVIEW

**Comment by ppedrot** [comment]
Forgot to mention: it depends on #6276.

**Comment by gares** [comment]
awesome!

File: checker/checker.ml [hunk 1]
```diff
@@ -178,7 +174,9 @@ let print_usage_channel co command =
   output_string co command;
   output_string co "coqchk options are:\n";
   output_string co
-"  -R dir coqdir          map physical dir to logical coqdir\
+"  -Q dir coqdir          map physical dir to logical coqdir\
+\n  -R dir coqdir          synonymous for -Q\
```
Comment (maximedenes) [inline checker/checker.ml]: in `coqtop`, the doc for `-R` says "map recursively". Why is it different in the checker? Because we don't need to resolve names?

File: man/coqchk.1 [hunk 2]
```diff
@@ -34,12 +34,16 @@ add directory
 in the include path
 
 .TP
-.BI \-R \ dir\ coqdir          
+.BI \-Q \ dir\ coqdir
 recursively map physical
```
Comment (maximedenes) [inline man/coqchk.1]: This seems to contradict what `coqchk --help` says (see above)

**Review by maximedenes — DISMISSED** [review]

File: checker/checker.ml (hunk 1 above)
Comment (ppedrot) [reply checker/checker.ml]: I documented it in the reference manual: "recursivity" is irrelevant in `coqchk`. Not to mention that it's actually badly phrased in `coqtop`. Qualified import with `-Q` in `coqtop` is also recursive, the adjective used should rather be *relative* vs. *absolute* (or maybe implicit).

**Comment by Zimmi48** [comment]
If I understand correctly the proposed fix, it goes way too far to be backported in v8.7.
That's fine but there is still a regression in coq_makefile in 8.7. Do we intend to solve it in 8.7.1 or not? Maybe @gares can propose a v8.7-only lighter solution...

BTW there is a conflict in CHANGES. I guess this does not deserve a rebase and can be solved at merge time.

**Comment by ppedrot** [comment]
> If I understand correctly the proposed fix, it goes way too far to be backported in v8.7.

It depends how you see it. The `-I` option is mostly useless, and I think this means people don't use it in practice (do they?). Anyways if this is an issue altogether I can provide a backport that keeps the semantics of `-I` as-is, and simply add `-Q` as a synonymous to `-R`.

Also, being able to use filenames is backward compatible except for people that would call a Coq file `vo.v`, which would be looking for trouble.

**Comment by Zimmi48** [comment]
It's just me following the rule "we don't merge features in stable branches". Maybe this deserves an exception (honestly, I'm not sure), but I would want the opinion of others to grant it.

**Comment by ppedrot** [comment]
@maximedenes So how do you want me to fix this? At best I think I can make the man page and the command line help coincide (but how?), as the issue is rather in `coqtop` documentation which is independent from this PR.

**Comment by maximedenes** [comment]
> I can make the man page and the command line help coincide

Yes, this is what should be done in this PR. "recursivity" should not be mentioned, IIUC.

> the issue is rather in coqtop documentation which is independent from this PR.

Indeed, could you open another PR to remove the "recursive"/"non recursive" terminology in favor of relative vs absolute for `coqtop`?

**Comment by ppedrot** [comment]
Fixed the documentation.

**Comment by RalfJung** [comment]
If we get everything up until 46c3ab137fe6705293e8a44624e2a564cde1d55a into 8.7.1, that would be enough to fix the regression. So the only new feature there is being able to refer to filenames.

**Comment by Zimmi48** [comment]
> If we get everything up until 46c3ab1 into 8.7.1, that would be enough to fix the regression. So the only new feature there is being able to refer to filenames.

@maximedenes Any opinion on this?

**Comment by maximedenes** [comment]
> @maximedenes Any opinion on this?

Seems ok to me. This is not really a new "feature", just a missing synonym for a flag.

**Comment by RalfJung** [comment]
> Seems ok to me. This is not really a new "feature", just a missing synonym for a flag.

Oh, so you mean *just* that patch? Yeah that fixes the regression indeed, though it is rather hacky when relative imports are still accepted. I was thinking of also including #6276 to fix the ambiguity (we have multiple files with thew same basename in different directories, coqchk doesn't know which one to use). But that ambiguity has always been around, it is not a regression.

**Review by gares — APPROVED** [review]

**Comment by Zimmi48** [comment]
@maximedenes Can you clarify your position after @RalfJung's comment?

**Comment by maximedenes** [comment]
Accepting file names is a new feature, unless `coqchk`'s documentation was already saying that they were accepted. So not material for a minor release IMHO. Remember that one of the points of short release cycles is to be strict on selection of material for minor releases (doc & bug fixes only).

Meanwhile, is seems we can merge this in `master`.

**Comment by maximedenes** [comment]
The checker seems broken after this merge. I haven't bisected yet. @ppedrot did you test this on CompCert's checker target?

**Comment by Zimmi48** [comment]
@maximedenes It was tested by Travis and it was failing: https://travis-ci.org/coq/coq/jobs/308986676.

**Comment by maximedenes** [comment]
OMG I merged something with failing tests, right? It is really a pain to have like 50% with spurious failures, I get used to bypassing...

**Comment by Zimmi48** [comment]
Yes.
Additionally, I deeply regret that you merged this PR so soon after your clarifying comment. Following this comment, I would have requested that this PR be rebased on master without including the commits from the PR it depended on. It would have made backporting to v8.7 so much easier.

**Comment by maximedenes** [comment]
I see. Really sorry about that. I suggest we wait for a diagnosis by @ppedrot before choosing between a revert and a fix.

**Comment by ppedrot** [comment]
I guess it's quite easy to fix in a backward compatible way, it should be a one-liner in the Makefile:
```
-	$(COQCHK) -admit Integers -admit SelectDivproof Complements
+	$(COQCHK) -admit Integers -admit SelectDivproof driver.Complements
```

**Comment by maximedenes** [comment]
Can you open a PR on CompCert?

**Comment by RalfJung** [comment]
>  It would have made backporting to v8.7 so much easier.

What exactly do you want to backport? This PR also enforces absolute paths, which is not compatible with prior versions of `coq_makefile`.

**Comment by Zimmi48** [comment]
I have not a clear view of this change but from what @RalfJung is saying, this fix is not backportable and a different fix will be required for 8.7.1. This is even truer with the fact that it breaks compatibility.
So I'm putting the 8.8 milestone on this and moving the discussion back to the original issue.

**Comment by ppedrot** [comment]
PR submitted in AbsInt/CompCert#210.
