### PR TITLE
Helping issue #11659 by leaving only the Cast hack in the grammar.

### LINKED ISSUE #11659: Logic in def_body in g_vernac.mlg is out of place.
The `vernac_expr` AST should reflect exactly what is parsed and `mlg` files should be limited to parsing. Here, we have a case of out of place early translation:

https://github.com/coq/coq/blob/7ef010c50c9d8efcd20d44807126efcd418c4e0d/vernac/g_vernac.mlg#L351-L372

~~This is detrimental to properly implementing some syntax restrictions following @ejgallego's [suggestion](https://github.com/coq/coq/pull/11646#issuecomment-589740074).~~ EDIT1: In this case, the transformation is actually fine for this particular check because the `CLocalPattern` binders will anyway be disallowed and thus what this transformation does is to render indistinguishable `Definition foo : nat := 0.` and `Definition foo := 0 : nat.` (not a big deal). EDIT2: But this transformation may actually lead to incorrect error messages (say "type must be provided" when the issue is actually "pattern binder is not supported").

### PR DESCRIPTION
**Pull request by Zimmi48**
The `CLocalPattern` hack is moved to `comDefinition.ml`.

**Kind:** clean-up.

Closes #11659

(prepared by @herbelin)

### CODE REVIEW

File: vernac/comDefinition.ml [hunk 1]
```diff
@@ -40,10 +40,29 @@ let check_imps ~impsty ~impsbody =
   | [], [] -> () in
   aux impsty impsbody
 
+let pattern_in_binder_hack bl c ctypopt =
```
Comment (maximedenes) [inline vernac/comDefinition.ml]: Please add a description of what this function does.

**Review by maximedenes — CHANGES_REQUESTED** [review]

**Review by ejgallego — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Why are we leaving the Cast hack in the mlg?

**Comment by herbelin** [comment]
> Why are we leaving the `Cast` hack in the mlg?

Why deconstructing the `Cast`: It is a design choice, doing such that if the user writes `Definition d bl := c : t`, then the body of the definition in the kernel is `fun bl => c` and not `fun bl => c : t`. 

Maybe we could remove it, on the assumption that if the user does not want a cast in the body, it uses the syntax `Definition d bl : t := c`. Which one is most intuitive? Which one is simplest to explain?

Why in the `mlg`: no particular reason, it could be in `comDefinition.ml` too.

**Comment by herbelin** [comment]
I fixed the failures of the patch and improved it so that `Eval` applies exactly on what it was supposed to apply.

> Please add a description of what this function does.

Done (and don't hesitate to suggest more details if you think it is worth).

**Comment by Zimmi48** [comment]
There are some slight changes in `test-suite/output/PatternsInBinders`:

```diff
@@ -4,7 +4,7 @@
      : A * B -> B * A
 forall '(x, y), swap (x, y) = (y, x)
      : Prop
-proj_informative = fun '(exist _ x _) => x : A
+proj_informative = fun '(exist _ x _) => x
      : {x : A | P x} -> A
 foo = fun '(Bar n b tt p) => if b then n + p else n - p
      : Foo -> nat
@@ -29,8 +29,7 @@
 ∀ '(x, y), swap (x, y) = (y, x)
      : Prop
 both_z = 
-fun pat : nat * nat =>
-let '(n, p) as x := pat return (F x) in (Z n, Z p) : F (n, p)
+fun pat : nat * nat => let '(n, p) as x := pat return (F x) in (Z n, Z p)
      : forall pat : nat * nat, F pat
 fun '(x, y) '(z, t) => swap (x, y) = (z, t)
      : A * B -> B * A -> Prop
```

**Comment by herbelin** [comment]
> There are some slight changes in `test-suite/output/PatternsInBinders`:

This is because I improved the "hack" so that it also removes the cast that it had introduced. I approved the new output and committed.

**Comment by Zimmi48** [comment]
@maximedenes can you check the comment and maybe self-assign?

**Comment by Zimmi48** [comment]
@maximedenes Your comment has been addressed. Do you want to review, and perhaps merge this PR?

**Comment by Zimmi48** [comment]
ping @maximedenes

**Review by maximedenes — APPROVED** [review]
LGTM modulo CI

**Comment by maximedenes** [comment]
I'll rebase to trigger a fresh CI run.

**Comment by maximedenes** [comment]
@herbelin for some reason I don't have permission to push the rebased branch to your fork. Can you do it?

**Comment by Zimmi48** [comment]
> @herbelin for some reason I don't have permission to push the rebased branch to your fork. Can you do it?

The reason is that I was the one who opened the PR, so GitHub couldn't ask *me* to give push rights to maintainers.

**Comment by herbelin** [comment]
> @herbelin for some reason I don't have permission to push the rebased branch to your fork. Can you do it?

Done.

**Comment by maximedenes** [comment]
> The reason is that I was the one who opened the PR, so GitHub couldn't ask _me_ to give push rights to maintainers.

I see, thanks for the explanation.
