### PR TITLE
Preserving canonical structure of return predicate in vm_compute and native_compute (partial fix to #7068; also fixes #7076))

### LINKED ISSUE #7076: Anomaly with vm_compute and native_compute in the presence of non-canonical forms of inductive arities
I'm reporting here a border case anomaly with `vm_compute` and `native_compute`. Fix ready and coming soon but I'm reporting it as an issue to avoid reporting a bug at the same time as a PR.

```coq
Inductive A : nat -> id (nat->Type) := .                              
Eval vm_compute in fun x => match x in A y z return y = z with end.
(* Anomaly "Returned a functional value in a type not recognized as a product type." *)
Eval native_compute in fun x => match x in A y z return y = z with end.
(* Anomaly "File "pretyping/nativenorm.ml", line 214, characters 9-15: Assertion failed."*)
```
The reason is that whd-normalization should be called recursively on the arity of the inductive type.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

This is a partial fix of #7068 for the case of `vm_compute` and `native_compute`. This also fixes #7076.

As a curiosity, I did not try to bypass an invisible peculiarity of the `lazy` machine that `vm_compute` and `native_compute` use to normalize the assumptions of the arity of an inductive types. In the presence of:
```coq
Inductive A : let B:=nat in B -> Type := .
Eval vm_compute in fun x => match x in A y z return y = z with end.
```
the `B` used in the internal representation of the return predicate shall not be reduced to `nat`. I believe that this is not important (see also ceps [#35](https://github.com/coq/ceps/pull/35)).

### CODE REVIEW

File: pretyping/nativenorm.ml [hunk 1]
```diff
@@ -362,20 +362,24 @@ and nf_atom_type env sigma atom =
...
-	try decompose_prod env pT with
-	  DestKO ->
-	  CErrors.anomaly
-	    (Pp.strbrk "Returned a functional value in a type not recognized as a product type.")
-      in
       let dep,body = 
 	nf_predicate (push_rel (LocalAssum (name,dom)) env) sigma ind mip params vb codom in
       dep, mkLambda(name,dom,body)
-  | Vfun f, _ -> 
+    | _ -> assert false
```
Comment (mattam82) [inline pretyping/nativenorm.ml]: I'm a bit worried here, the previous function was not returning the same in the Prod/not Vfun case, right?

**Review by mattam82 — APPROVED** [review]
That looks like a pure bugfix to me, in the readback phase of native/vm_compute which I'm not so specialist with, I guess @maximedenes would know better.

File: pretyping/nativenorm.ml (hunk 1 above)
Comment (herbelin) [reply pretyping/nativenorm.ml]: Right. I implicitly made the assumption that the body was enough eta-expanded but maybe do I anticipate too much about the invariants to be preserved by CEP [#34](https://github.com/coq/ceps/pull/34). I can put a `nf_type` again with a note telling that this should not be necessary with a canonically eta-expanded form?

**Comment by herbelin** [comment]
@maximedenes: Are you willing to be the assignee on this PR?

**Comment by maximedenes** [comment]
@herbelin yes, no pb. Sorry if I'm a bit slow these days, I'm still busy with the CI infrastructure but should be done soon.

File: pretyping/nativenorm.ml [hunk 2]
```diff
@@ -303,10 +303,10 @@ and nf_atom_type env sigma atom =
       let (mib,mip) = Inductive.lookup_mind_specif env (fst ind) in
       let nparams = mib.mind_nparams in
       let params,realargs = Array.chop nparams allargs in
+      let nparamdecls = Context.Rel.length (Inductive.inductive_paramdecls (mib,u)) in
       let pT = 
-	hnf_prod_applist env 
+        hnf_prod_applist_assum env nparamdecls
```
Comment (maximedenes) [inline pretyping/nativenorm.ml]: I realize now that you had already fixed this in `vm_compute`. I should really make progress on https://github.com/coq/coq/projects/17 to avoid this kind of duplicate bugs.

Comment (herbelin) [reply pretyping/nativenorm.ml]: And I heard that this would make @mattam82 and CertiCoq happy as well.

**Comment by herbelin** [comment]
Lint fixed. Seems ok from my side.

**Review by ppedrot — COMMENTED** [review]
Outside of my understanding of the invariants of reification.

File: pretyping/nativenorm.ml (hunk 1 above)
Comment (maximedenes) [reply pretyping/nativenorm.ml]: In fact, I think there is a lot of legacy code around this `dep` thing. I'll remove it as part of another PR. For the scope of this PR, I suggest to put back the `nf_type` just in case.

**Review by maximedenes — DISMISSED** [review]

File: pretyping/nativenorm.ml (hunk 1 above)
Comment (herbelin) [reply pretyping/nativenorm.ml]: OK, done.

**Comment by maximedenes** [comment]
I addressed the legacy `dep` thing in #7607. This is now good to go, once CI has run.

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
I'm afraid there is some trailing whitespace in the test cases. Sorry for not realizing earlier. Should be easy to fix, though.

**Comment by herbelin** [comment]
That's strange. The automatic whitespace fixing did not work here?

Anyway, I removed the spaces manually.
