### PR TITLE
[ssr] rewrite: turn anomaly into regular error

### LINKED ISSUE #7255: ssr: anomaly occurs when trying to rewrite with a logical equivalence
#### Version

Coq master (4c466c429902d0ef0bd0da0f42e1a3b6d9f7d32a)

#### Operating system

macOS 10.13.3 High Sierra

#### Description of the problem

Please consider the following minimized example:

```coq
From Coq Require Import ssreflect Setoid.

Structure SEProp := {prop_of : Prop; _ : prop_of <-> True}.

Fact anomaly: forall P : SEProp, prop_of P.
Proof.
move=> [P E].
rewrite E.
```

`rewrite E` produces an anomaly:

>Error: Anomaly "cvtac's exception: Pretype_errors.PretypeError(_, _, _)"
>Please report at http://coq.inria.fr/bugs/.

Obverse that if I simplify the goal, then the anomaly goes away:
```coq
Fact no_anomaly: forall P : SEProp, prop_of P.
Proof. by move=> [P /= ->]. Qed.
```

Also, it seems that the usage of SSReflect is essential here, because 
```coq
From Coq Require Import Setoid.
Structure SEProp := {prop_of : Prop; _ : prop_of <-> True}.

Fact no_anomaly2: forall P : SEProp, prop_of P.
Proof. intros [P E]. Fail rewrite E. Abort.
```

results in the following error message:

> build_signature: no constraint can apply on a dependent argument

### PR DESCRIPTION
**Pull request by gares**
I think the bug was introduces when apply_type was made safe.
In the test joint to #7255 rewrite (setoid case) generates an
ill-typed goal and apply_type raises a Pretype_error.

It is unclear to me why the tactic monad does not turn the
pretype_error into a UserError

Fix #7255

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>It is unclear to me why the tactic monad does not turn the
pretype_error into a UserError

Why would it do that?

**Comment by gares** [comment]
Maybe you are right, and the exception should be fatal.
But it is not clear to me, not documented AFAICT.

The label is `~typecheck`, and I've added it, but I would have chosen `~assert_well_typed` if it was intended to be a fatal error to pass an ill typed term. So maybe we should rename the flag?

**Comment by gares** [comment]
@maximedenes

**Comment by maximedenes** [comment]
@gares I think you forgot to add me as a reviewer.

File: plugins/ssr/ssrequality.ml [hunk 1]
```diff
@@ -417,7 +417,7 @@ let rwcltac cl rdx dir sr gl =
       then errorstrm Pp.(str "Rewriting impacts evars")
       else errorstrm Pp.(str "Dependent type error in rewrite of "
         ++ pr_constr_env (pf_env gl) (project gl) (Term.mkNamedLambda pattern_id (EConstr.Unsafe.to_constr rdxt) (EConstr.Unsafe.to_constr cl)))
-    | CErrors.UserError _ as e -> raise e
+    | (CErrors.UserError _ | Pretype_errors.PretypeError _) as e -> raise e
     | e -> anomaly ("cvtac's exception: " ^ Printexc.to_string e);
```
Comment (maximedenes) [inline plugins/ssr/ssrequality.ml]: What is this trying to catch? Why not just let the exception bubble up?

Comment (gares) [reply plugins/ssr/ssrequality.ml]: I don't know what I was trying to catch here. IMO it is my (bad?) habit of having assertions that backfires me (as the "no safe_id attached" one). `cvtac` is supposed to be a tactic, hence, IMO, it should only fail with `CErrors.UserError`. On purpose I type-check the inferred predicate and raise a different exception (few lines above) to re-raise a better error message. It is unclear to me if `Pretype_errors.PretypeError _` is a legit exception that can be raised by tactics.

**Comment by maximedenes** [comment]
@gares this is missing a test case

**Comment by gares** [comment]
there you go

**Comment by Zimmi48** [comment]
Same remark as in another PR of yours: this will need a rebase to make the CI happy.

**Comment by gares** [comment]
ping @maximedenes

**Comment by gares** [comment]
ci failures on gitlab seem spurious, I've restarted the windows one (segmentation fault)

**Comment by gares** [comment]
Ready to be merged

**Comment by Zimmi48** [comment]
@gares Any reason not to put this in the 8.8.1 milestone? Given the size of the patch and what it's changing, I would say it is backportable.

**Review by maximedenes — APPROVED** [review]

**Comment by Zimmi48** [comment]
@gares ping
