### PR TITLE
[micromega] add magic number and pcache_version in persistent caches

### LINKED ISSUE #15629: [micromega] Segmentation fault if old cache not cleared after #15584
#### Description of the problem

Manual build by `make -f Makefile.dune world` fails with:
```
coqc theories/Arith/.Cantor.aux,theories/Arith/Cantor.{glob,vo} (got signal SEGV)
```

[EDIT] the other problem was due to a bad old makefile configuration not clearing `.lia.cache`, I delete it.

#### Coq Version
master on `Ubuntu 18.04`:
- fails on master
- OK at 293ee82

due to #15584?

### PR DESCRIPTION
**Pull request by fajb**
This PR intends to prevents crashes due to changes of format of the micromega caches (.lia.cache, .nia.cache).
The workaround consists in inserting and checking the presence of `ObjFile.magic_number` and `pcache_version`.

The caches will invalidated if the `pcache_version` does not match thus preventing unmarshalling of invalid data.

Fixes #15629

### CODE REVIEW

**Comment by olaure01** [comment]
> This does not fix #15629

Unfortunately, github does not seem to understand this remark properly and links the issue to the PR.
Is there a way to unlink so that the issue is not closed when the PR is merged?

**Comment by Alizter** [comment]
@olaure01 I reordered the fix and now it won't close that.

File: plugins/micromega/persistent_cache.ml [hunk 1]
```diff
@@ -130,7 +130,30 @@ module PHashtable (Key : HashedType) : PHashtable with type key = Key.t = struct
...
+    for _i = 0 to 3 do
+      let c = input_byte ch in
+      accu := Int32.add (Int32.shift_left !accu 8) (Int32.of_int c)
+    done;
+    !accu
+
+  let output_int32 ch n =
+    for i = 0 to 3 do
+      output_byte ch (Int32.to_int (Int32.shift_right_logical n (24 - 8 * i)))
+    done
```
Comment (silene) [inline plugins/micromega/persistent_cache.ml:147]: It would be better to just export these functions from `ObjFile`.

**Review by silene — CHANGES_REQUESTED** [review]
Also, I am not sure what is going on with `test-suite/.csdp.cache.test-suite`, but a squash is in order.

File: plugins/micromega/persistent_cache.ml (hunk 1 above)
Comment (fajb) [reply plugins/micromega/persistent_cache.ml:147]: I agree that duplication is not the right way. Yet it seems `ObjFile` does not expose this kind of stuff (on purpose?).
Could `lib/system.mli` be the home for these functions?

File: plugins/micromega/persistent_cache.ml [hunk 2]
```diff
@@ -143,9 +166,17 @@ module PHashtable (Key : HashedType) : PHashtable with type key = Key.t = struct
...
+    let good_magic_and_version = ref true in
     try
       (* Locking of the (whole) file while reading *)
-      let htbl = do_under_lock Read finch (fun () -> xload Table.empty) in
+      let htbl = do_under_lock Read finch (fun () ->
+          let table = Table.empty in
+          good_magic_and_version :=  check_magic_number_and_version inch ;
+          if !good_magic_and_version
+          then xload table
+          else raise (InvalidTableFormat table)
```
[the remark this answers is not in the document]
Comment (fajb) [reply plugins/micromega/persistent_cache.ml:178]: You are right. There is no need for the reference. 
If `good_magic_and_version` is false, the table is empty and therefore it does not hurt to
`(* Try to salvage what we can *)` on an empty table. I'll fix that.

File: plugins/micromega/persistent_cache.ml [hunk 3]
```diff
@@ -158,9 +189,11 @@ module PHashtable (Key : HashedType) : PHashtable with type key = Key.t = struct
         | exception e -> accu
       in
       (* Try to salvage what we can *)
-      let data = do_under_lock Read finch (fun () -> Table.fold fold htbl []) in
+      let data = if !good_magic_and_version
+        then do_under_lock Read finch (fun () -> Table.fold fold htbl [])
+        else [] in
       let () = close_in_noerr inch in
-      let flags = [O_WRONLY; O_TRUNC; O_CREAT] in
+      let flags = [O_WRONLY; O_TRUNC; O_APPEND;O_CREAT] in
```
[the remark this answers is not in the document]
Comment (fajb) [reply plugins/micromega/persistent_cache.ml:196]: Thanks for raising the issue! I do not feel comfortable *at all* with Posix programming.
There is something wrong.

Without the `O_APPEND` flag, I could not understand why starting from an invalid cache, the magic number did not appear in the regenerated cache. That works with `O_APPEND`, Linux and OCaml 4.13.1 - that does not make sense to me.

Note that there is also the `O_TRUNC` flag so the file is truncated with length 0. 
I guess your worry is about concurrency: another process creates and writes. 
magic number is inserted at the end of file... That would be bad...

File: plugins/micromega/persistent_cache.ml (hunk 1 above)
Comment (silene) [reply plugins/micromega/persistent_cache.ml:147]: Either that or `lib/util.mli`. No strong opinion either way.

File: plugins/micromega/persistent_cache.ml (hunk 3 above)
[the remark this answers is not in the document]
Comment (fajb) [reply plugins/micromega/persistent_cache.ml]: Don't thank me for opening the Pandora's box.
PS: I tried to implement your proposal.

**Comment by fajb** [comment]
> By the way, this raises an interesting point. You should update `dev/doc/release-process.md`, as regenerating the cache file will therefore become a mandatory step of the release process.

Gosh. So maybe having a `persistent_cache` version (instead of vo version) would actually be better.
- Fix https://github.com/coq/coq/issues/15629
- and would not impact the release process.

File: plugins/micromega/persistent_cache.ml [hunk 4]
```diff
@@ -128,54 +124,46 @@ module PHashtable (Key : HashedType) : PHashtable with type key = Key.t = struct
...
+      | Some (hash, pos) -> xload (Table.add hash { pos =  Some pos; obj = None } table)
+      | exception e when CErrors.noncritical e -> raise InvalidTableFormat
     in
+
     try
       (* Locking of the (whole) file while reading *)
-      let htbl = do_under_lock Read finch (fun () -> xload Table.empty) in
+      let htbl = do_under_lock Read finch (fun () ->
+          let table = Table.empty in
+          if check_magic_number_and_version inch
```
Comment (silene) [inline plugins/micromega/persistent_cache.ml:154]: Perhaps you should check the magic numbers outside of the lock. Otherwise, you might end up in a strange situation where you write into a file that does not even have the correct format.

But perhaps we can just ignore this issue, as it opens a whole new can of worms. That is, two different Coq versions are manipulating the cache at the same time, which does not bode well.

I guess it warrants a comment such as "This caching mechanism supports concurrent accesses, as long as all the Coq executables are identical. Some cache entries might get lost in the process, but none should become corrupted."

**Comment by silene** [comment]
> So maybe having a `persistent_cache` version (instead of vo version) would actually be better.

I guess so.

**Comment by silene** [comment]
@Zimmi48 The `pkg:nix` job instantly fails with the following message:
```
building '/nix/store/qk33w6qgdarzik7j3k6c4kl6b1q5a0ql-ocaml4.09.1-zarith-1.12.drv'...
unpacking sources
unpacking source archive /nix/store/agnv4yryhisn2pdaw8aydzhwqprs2ics-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
install flags: SHELL=/nix/store/wadmyilr414n7bimxysbny876i2vlm5r-bash-5.1-p8/bin/bash install
make: *** No rule to make target 'install'.  Stop.
note: keeping build directory '/builds/coq/coq/nix-build-ocaml4.09.1-zarith-1.12.drv-0'
builder for '/nix/store/qk33w6qgdarzik7j3k6c4kl6b1q5a0ql-ocaml4.09.1-zarith-1.12.drv' failed with exit code 2
```
I retried the job, but nothing changed. Is this a known failure?

**Comment by vbgl** [comment]
About the `pkg:nix` build: it fails twice on the “roquableu” machine. Is there enough free disk space available on this machine?

**Review by silene — APPROVED** [review]

**Comment by silene** [comment]
@coqbot merge now

**Comment by silene** [comment]
@coqbot merge now
