### PR TITLE
Fix #8364: making univ algebraic when already equal to another.

### LINKED ISSUE #8364: Error: Anomaly "A universe comparison can only happen between variables." (in inductive type)
#### Version

8.8.1

#### Description of the problem

```coq

Definition map {A B} (f:A -> B) :=
  fix map l :=
  match l with nil => nil | cons x xs => cons (f x) (map xs) end.

Fixpoint tuple (l : list Type) : Type :=
  match l with
  | cons x nil => x
  | cons x xs => prod x (tuple xs)
  | nil => unit
  end.

Inductive stack : Type -> Type :=
| Stack T foos :
  tuple (map stack foos) ->
  stack T.
(* Error: Anomaly "A universe comparison can only happen between variables."
Please report at http://coq.inria.fr/bugs/. *)
```

### PR DESCRIPTION
**Pull request by SkySkimmer**
When making a universe a variable we iterate through the universes
we're equal to and if we find one we update the substitution
accordingly.

NB: The bug called make_flexible_variable on Top.15 and
~~~
   {Top.15 Top.14} |= Top.11 < Top.6
                      Top.14 < Top.5
                      Top.11 = Top.15

  ALGEBRAIC UNIVERSES:{Top.17 Top.16}
  UNDEFINED UNIVERSES:Top.17 := Top.14+1
                      Top.16 := Top.14+1
  WEAK CONSTRAINTS:
~~~
so now we would add [Top.15 := Top.11].

Depends on #8936.

### CODE REVIEW

**Review by mattam82 — APPROVED** [review]
Good catch, indeed the precondition was that u was not defined but it didn't take care of the fact that u might be equal to another universe.

File: kernel/uGraph.ml [hunk 1]
```diff
@@ -866,6 +866,21 @@ let constraints_for ~kept g =
         arc.ltle csts)
     kept csts
 
+let choose p g u =
+  let exception Found of Level.t in
+  let ru = (repr g u).univ in
+  if p ru then Some ru
+  else
+    try LMap.iter (fun v -> function
```
Comment (ppedrot) [inline kernel/uGraph.ml]: Isn't that *horribly* inefficient?

**Comment by ppedrot** [comment]
Please run a benchmark, crawling through all defined universes to create flexible variables looks daunting.

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/565/console

**Comment by mattam82** [comment]
@ppedrot It crawls only the equivalence class of u not all universes, IIUC.

**Comment by SkySkimmer** [comment]
No, the iter is over all universes. The predicate is only called on the equivalence class.

**Comment by mattam82** [comment]
Right, my mistake.

**Comment by SkySkimmer** [comment]
```

┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬──────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │        mem faults        │
│                        │                         │                                             │                                             │                               │                          │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW     OLD  PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│           coq-compcert │  880.78  886.46 -0.64 % │     2443177126001     2456480150646 -0.54 % │     3555102324816     3555755201917 -0.02 % │    1335752    1335980 -0.02 % │     119      38 +213.16 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│       coq-fiat-parsers │  714.15  718.02 -0.54 % │     1982327747142     1993014087956 -0.54 % │     3051518790238     3051441253787 +0.00 % │    2907888    2907892 -0.00 % │      65     650 -90.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│          coq-fiat-core │  135.04  135.64 -0.44 % │      376365330466      377323421882 -0.25 % │      505165599738      505469350493 -0.06 % │     495680     496076 -0.08 % │     216      62 +248.39 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-flocq │  590.96  593.00 -0.34 % │     1644390251145     1646930355156 -0.15 % │     2410065455964     2410003250836 +0.00 % │    1766352    1766540 -0.01 % │     247      43 +474.42 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│    coq-formal-topology │   58.92   58.96 -0.07 % │      160605902941      160618517069 -0.01 % │      243665054646      243857636181 -0.08 % │     477324     477628 -0.06 % │       0       0   +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-ssreflect │   66.43   66.46 -0.05 % │      182707576827      182985871046 -0.15 % │      261528887125      261765103009 -0.09 % │     531628     531824 -0.04 % │      12       0   +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│             coq-sf-vfa │   47.88   47.88 +0.00 % │      132335383299      132431405320 -0.07 % │      213172622527      213324895468 -0.07 % │     534096     534152 -0.01 % │      28       6 +366.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│             coq-sf-plf │   75.01   74.96 +0.07 % │      207156194341      207007650108 +0.07 % │      303486095897      303613453801 -0.04 % │     517856     517872 -0.00 % │      15       0   +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-sf-lf │   44.99   44.96 +0.07 % │      123895324917      123956833137 -0.05 % │      202560256659      202777607669 -0.11 % │     414356     414272 +0.02 % │     130       0   +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│            coq-bignums │   99.42   99.33 +0.09 % │      275382246387      274484973555 +0.33 % │      397275873023      397476786915 -0.05 % │     534300     534784 -0.09 % │     189       0   +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│         coq-coquelicot │  104.84  104.71 +0.12 % │      289848227973      289906166073 -0.02 % │      391541797484      391653854515 -0.03 % │     710744     710536 +0.03 % │     269      12 +2141.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│       coq-math-classes │  251.06  250.32 +0.30 % │      692026766519      689794243200 +0.32 % │      904481898503      904700617455 -0.02 % │     521136     521316 -0.03 % │      26      12 +116.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│        coq-lambda-rust │ 2368.83 2358.26 +0.45 % │     6600201876097     6569892365495 +0.46 % │     9093173741896     9090925016389 +0.02 % │    1446824    1419264 +1.94 % │       0      11 -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-color │  736.52  733.11 +0.47 % │     2039796491359     2031778899152 +0.39 % │     2464855527026     2464729237649 +0.01 % │    1369892    1430420 -4.23 % │     119     120  -0.83 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│        coq-fiat-crypto │ 6361.09 6328.90 +0.51 % │    17690064796783    17606804575390 +0.47 % │    29048018870811    29014234746455 +0.12 % │    2438516    2454552 -0.65 % │    1721    1233 +39.58 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│            coq-unimath │ 1330.42 1321.72 +0.66 % │     3694230912223     3668744394890 +0.69 % │     6186354653691     6186553074655 -0.00 % │    1112716    1112864 -0.01 % │     316       5 +6220.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│                coq-vst │ 1677.09 1663.67 +0.81 % │     4661845869580     4623551513231 +0.83 % │     6458880087983     6462610672128 -0.06 % │    2221720    2217264 +0.20 % │     296     429 -31.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│               coq-hott │  341.96  338.40 +1.05 % │      945935190805      938314390315 +0.81 % │     1437973410754     1438135496302 -0.01 % │     600548     600572 -0.00 % │     396       0   +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│               coq-corn │ 1557.84 1539.60 +1.18 % │     4322436688940     4272645059531 +1.17 % │     6356295423874     6356669144187 -0.01 % │     812888     813036 -0.02 % │      55     394 -86.04 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴──────────────────────────┘

```
mathcomp was still broken at the time of the bench
NB: #8863 should remove most of the calls to make_flexible_variable leaving only the ones for inductive types (unless that PR is only valid because of a bug?)

**Comment by mattam82** [comment]
I'm a bit worried about the time difference, especially if 8863 cannot be done. @SkySkimmer shall we wait to fix that first?

**Comment by SkySkimmer** [comment]
Bench together with #8936 waiting to start at jenkins 576.

**Comment by SkySkimmer** [comment]
(together with #8936)
```

┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬─────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │       mem faults        │
│                        │                         │                                             │                                             │                               │                         │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW     OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│ coq-mathcomp-odd-order │ 1372.24 1395.74 -1.68 % │     3823657624175     3887374311772 -1.64 % │     6480242482221     6479156070758 +0.02 % │    1347620    1343464 +0.31 % │       0       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│           coq-compcert │  879.00  889.56 -1.19 % │     2437957363309     2466672076391 -1.16 % │     3555344050743     3554617447842 +0.02 % │    1327336    1327700 -0.03 % │     101     179 -43.58 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│            coq-unimath │ 1318.02 1333.75 -1.18 % │     3661321611564     3703232837907 -1.13 % │     6186925865521     6186340946599 +0.01 % │    1079784    1079684 +0.01 % │     344      19 +1710.53 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│            coq-bignums │   98.95  100.06 -1.11 % │      274587349508      276701758657 -0.76 % │      398229226056      398574696260 -0.09 % │     539928     539996 -0.01 % │      60       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│               coq-hott │  341.52  345.27 -1.09 % │      945496384494      954498327203 -0.94 % │     1445890790533     1446274982290 -0.03 % │     600652     600608 +0.01 % │     136       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│               coq-corn │ 1525.31 1541.30 -1.04 % │     4232087639748     4276238684552 -1.03 % │     6268781754262     6268920521201 -0.00 % │     837212     836992 +0.03 % │      44      44 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│       coq-math-classes │  249.86  252.22 -0.94 % │      688807066752      694217350895 -0.78 % │      906349705980      906726582785 -0.04 % │     524356     524460 -0.02 % │      84      84 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│             coq-geocoq │ 1999.86 2017.66 -0.88 % │     5556035205950     5605613679252 -0.88 % │     8114704415223     8115367066440 -0.01 % │    1222152    1240300 -1.46 % │     205     162 +26.54 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│              coq-flocq │  589.57  594.76 -0.87 % │     1640939536822     1654585173404 -0.82 % │     2413161358887     2414153283750 -0.04 % │    1767380    1767424 -0.00 % │     169      40 +322.50 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│  coq-mathcomp-solvable │  215.56  217.45 -0.87 % │      598820712787      603490976667 -0.77 % │      852007233905      852159246123 -0.02 % │     847920     865324 -2.01 % │      17     112 -84.82 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│        coq-fiat-crypto │ 6233.20 6287.80 -0.87 % │    17571097809262    17723312004351 -0.86 % │    28895904376270    28880119929078 +0.05 % │    2441912    2457116 -0.62 % │    1359    1296 +4.86 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│     coq-mathcomp-field │  258.58  260.74 -0.83 % │      719064745832      724914821593 -0.81 % │     1095389620434     1095682680750 -0.03 % │     756680     756984 -0.04 % │       0     175 -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│  coq-mathcomp-fingroup │   83.68   84.30 -0.74 % │      231513139380      232432772524 -0.40 % │      344018898591      344216536620 -0.06 % │     586284     586336 -0.01 % │     129       1 +12800.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│          coq-fiat-core │  135.96  136.77 -0.59 % │      379396925133      381599619391 -0.58 % │      511032902178      511284550290 -0.05 % │     500104     500052 +0.01 % │     265     174 +52.30 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│       coq-fiat-parsers │  711.58  715.56 -0.56 % │     1973723009244     1987699709587 -0.70 % │     3032568782898     3033099553573 -0.02 % │    2908072    2911076 -0.10 % │     301     454 -33.70 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│ coq-mathcomp-character │  279.32  280.76 -0.51 % │      776847914160      780967741951 -0.53 % │     1121186336081     1121524357823 -0.03 % │    1094332    1094572 -0.02 % │      14       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│                coq-vst │ 2963.70 2977.88 -0.48 % │     8245673144479     8284863796380 -0.47 % │    11417552143515    11416042535999 +0.01 % │    2217476    2219276 -0.08 % │     387     250 +54.80 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│             coq-sf-plf │   75.67   76.01 -0.45 % │      209492169714      210519580657 -0.49 % │      307497771711      307926213968 -0.14 % │     513816     513724 +0.02 % │      15       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│              coq-color │  733.17  736.34 -0.43 % │     2032510470717     2041270341323 -0.43 % │     2461896035973     2461104936367 +0.03 % │    1371252    1431988 -4.24 % │      59     132 -55.30 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│        coq-lambda-rust │ 2318.74 2328.64 -0.43 % │     6460306969707     6485908254009 -0.39 % │     8892925402764     8894729780994 -0.02 % │    1443808    1438200 +0.39 % │       4      15 -73.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│   coq-mathcomp-algebra │  184.62  185.36 -0.40 % │      511962768877      514755932353 -0.54 % │      700089716960      700212056290 -0.02 % │     642752     643184 -0.07 % │     127      12 +958.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│             coq-sf-vfa │   48.73   48.92 -0.39 % │      134526802816      135130764001 -0.45 % │      216741151792      217070284135 -0.15 % │     537016     536740 +0.05 % │      30       5 +500.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│         coq-coquelicot │  105.16  105.56 -0.38 % │      290521436383      292268162032 -0.60 % │      393423113255      393806129687 -0.10 % │     711720     711496 +0.03 % │     281      13 +2061.54 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│ coq-mathcomp-ssreflect │   67.00   67.22 -0.33 % │      184402744492      185232603845 -0.45 % │      264345149427      264664004665 -0.12 % │     532924     533100 -0.03 % │       2       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│              coq-sf-lf │   45.77   45.81 -0.09 % │      126439250337      126259981597 +0.14 % │      206433520986      206794474562 -0.17 % │     427880     427768 +0.03 % │     115       1 +11400.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│    coq-formal-topology │   59.87   59.55 +0.54 % │      163345755647      163771170230 -0.26 % │      248005452396      248324525891 -0.13 % │     479468     479540 -0.02 % │       0       0  +nan % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴─────────────────────────┘

```

**Comment by mattam82** [comment]
Looking good! What about the CI failure?

**Comment by SkySkimmer** [comment]
fiat ran out of memory (it didn't change in the bench)
nix logs are too big for gitlab, it seems to be compiling gcc (?), are we somehow depending on stuff that dropped out of the nix binary caches? Is that even possible? @coq/nix-maintainers

**Comment by vbgl** [comment]
Concerning the `pkg:nix` build, something went wrong with the verification of the signatures of the binary cache. Restarting the build seems to make the problem disappear; let’s forget about it.

**Comment by SkySkimmer** [comment]
@mattam82 appveyor looks spurious, should be good to merge.

**Comment by mattam82** [comment]
@SkySkimmer I'll merge after you rebase

**Comment by SkySkimmer** [comment]
Rebased.
