### PR TITLE
Fixes #18434: arguments of --external in coqdoc were inadvertently swapped

### LINKED ISSUE #18434: regression in coqdoc 8.18.0 (--external stopped working)
#### Description of the problem

It appears that `coqdoc` stopped honoring the `--external` flag in version 8.18.0. It still worked in 8.17.0. 

#### Coq Version

```
% coqtop -v
The Coq Proof Assistant, version 8.18.0
compiled with OCaml 4.14.1
```

#### Example

Example that reproduces the issue: [example.zip](https://github.com/coq/coq/files/13745761/example.zip)

Example file `test.v`: 

```coq
From mathcomp Require Import ssreflect ssrbool seq.

Section Foo.

  Variable bar : seq bool.

  Definition baz := foldl andb true.

End Foo.
```

Expectation: `coqdoc` should link `foldl` to [its definition](https://math-comp.github.io/htmldoc//mathcomp.ssreflect.seq.html#foldl). 

Actual behavior: no link is generated. 

#### Steps to Reproduce

1. Create the `Makefile` and tell `coqdoc` to link to mathcomp definitions:   
```
% coq_makefile -f _CoqProject -o Makefile COQDOCEXTRAFLAGS = "--external https://math-comp.github.io/htmldoc/ mathcomp"
```
2. Generate the HTML spec:  
```
% make html      
```
3. Check if `foldl` is linked to https://math-comp.github.io/htmldoc//mathcomp.ssreflect.seq.html#foldl  
```
% grep 'mathcomp.ssreflect.seq.html#foldl' html/example.test.html 
```

With Coq 8.18.0, I'm getting nothing and inspecting the file confirms that the identifier `foldl` is not linked to anything.

With Coq 8.17.0, I'm getting the below output and the link works as expected. (Reformatted for clarity.)

```
&nbsp;&nbsp;<span class="id" title="keyword">Definition</span>
<a id="baz" class="idref" href="#baz"><span class="id" title="definition">baz</span></a> := 
<a class="idref" href="https://math-comp.github.io/htmldoc//mathcomp.ssreflect.seq.html#foldl"><span class="id" title="definition">foldl</span></a>  <===== LINKED AS EXPECTED
<a class="idref" href="http://coq.inria.fr/distrib/V8.17.0/stdlib//Coq.Init.Datatypes.html#andb"><span class="id" title="definition">andb</span></a>
<a class="idref" href="http://coq.inria.fr/distrib/V8.17.0/stdlib//Coq.Init.Datatypes.html#true"><span class="id" title="constructor">true</span></a>.<br/>
```

### PR DESCRIPTION
**Pull request by herbelin**
Fixes / closes #18434

- [ ] Added / updated **test-suite**.
- [x] Added **changelog**.

Should go to 8.18.1 (if any) or 8.19.0

### CODE REVIEW

File: tools/coqdoc/cmdArgs.ml [hunk 1]
```diff
@@ -78,13 +78,13 @@ let arg_path f = Arg.String (fun s ->
...
     prefs := f !prefs (normalize_path s, Sys.argv.(!Arg.current + 1)))
-let arg_url_path f = Arg.String (fun s ->
+let arg_url_path f = Arg.String (fun url ->
   if Array.length Sys.argv < !Arg.current + 3 ||
     Sys.argv.(!Arg.current + 2).[0] = '-' then
     raise (Arg.Bad ("Two arguments expected: <url> and <path>"))
   else
     Arg.current := !Arg.current + 1;
-    f s Sys.argv.(!Arg.current + 1))
+    f Sys.argv.(!Arg.current + 1) url)
```
Comment (silene) [inline tools/coqdoc/cmdArgs.ml:87]: While the fix is fine, I think the resulting code will be very confusing for anyone that reads it later on, since it surreptitiously swaps the arguments. Rather than modifying the function above, it might better to just replace its call `arg_url_path Index.add_external_library` below by `arg_url_path (fun url lp -> Index.add_external_library lp url)`.

Comment (herbelin) [reply tools/coqdoc/cmdArgs.ml:87]: To have to twist less our minds, we could also swap the arguments in `Index.add_external_library`?

Comment (ppedrot) [reply tools/coqdoc/cmdArgs.ml:87]: You could also use labels, they're a great way to disambiguate arguments with the same type.

Comment (silene) [reply tools/coqdoc/cmdArgs.ml:87]: > To have to twist less our minds, we could also swap the arguments in `Index.add_external_library`?

I did consider it, but since it involves changing the API, I refrained from suggesting it. (And I consider the API to be fine here, since having the logical path as the first argument is the sensible choice, in my opinion. As a user, I did mess a few times the order of the arguments of `--external` becomes it is not natural to me.) That said, I would not oppose it, since I doubt anyone other than Coq itself is using that API.

Comment (herbelin) [reply tools/coqdoc/cmdArgs.ml]: OK, then, to preserve the API, I adopted `arg_url_path (fun url lp -> Index.add_external_library lp url)`.

**Review by silene — APPROVED** [review]

**Comment by silene** [comment]
@coqbot run full ci

**Comment by silene** [comment]
@coqbot merge now

@SkySkimmer mention, just in case it goes under the radar for 8.19.0

**Comment by ejgallego** [comment]
Backport seems done, however the 8.19.0 project page was not updated, added this PR to the "request" list so it can be properly processed.

**Comment by Zimmi48** [comment]
Removing from the 8.18.1 milestone since it was never backported there.
