### PR TITLE
Simplify code for [Definition := Eval ...]

### LINKED ISSUE #3690: [Eval compute in] fails to minimize universes
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#3690
From: @JasonGross
Reported version: 8.5
CC:   coq-bugs-redist@lists.gforge.inria.fr

### PR DESCRIPTION
**Pull request by SkySkimmer**
This fixes #3690 for real (it was added to the test suite as closed even though it was wontfix for some reason) by restricting universes after running the Eval.

Note the commit touching nativenorm, I don't know if that's the right fix but without it the test for #7631 breaks with assert false. I don't know if there's a way to trigger it with the current system but it's not good for a function taking econstr to fail when the constr is not evar normal.
I have further simplification in mind which would may make it suboptimal to econstr.to_constr before the eval so I avoided it but if someone strongly thinks it's better I can deal with it.

### CODE REVIEW

File: pretyping/nativenorm.ml [hunk 1]
```diff
@@ -132,15 +132,15 @@ let construct_of_constr_notnative const env tag (mind, _ as ind) u allargs =
   (mkApp(mkConstructU((ind,i),u), params), ctyp)
  
 
-let construct_of_constr const env tag typ =
+let construct_of_constr const env sigma tag typ =
```
Comment (maximedenes) [inline pretyping/nativenorm.ml]: @SkySkimmer did you check if `vnorm` needs a similar fix?

**Review by maximedenes — APPROVED** [review]
The nativenorm change looks ok to me.

File: pretyping/nativenorm.ml (hunk 1 above)
Comment (SkySkimmer) [reply pretyping/nativenorm.ml]: vnorm does
~~~ocaml
  (** This evar-normalizes terms beforehand *)
  let c = EConstr.to_constr ~abort_on_undefined_evars:false sigma c in
  let t = EConstr.to_constr ~abort_on_undefined_evars:false sigma t in
~~~
so no.
I'm going to add vm_compute to that one test file for future safety.

File: test-suite/bugs/closed/3956.v [hunk 2]
```diff
@@ -129,13 +129,13 @@ Module Comodality_Theory (F : Comodality).
       := IdmapM FPM.
     Module cip_FPM := FPM.coindpathsM FPM cmpinv_o_cmp_M idmap_FPM.
     Module cip_FPHM <: HomotopyM FPM cmpM.PM cip_FPM.fhM cip_FPM.fkM.
-      Definition m : forall x, cip_FPM.fhM.m@{i j} x = cip_FPM.fkM.m@{i j} x.
+      Definition m : forall x, cip_FPM.fhM.m x = cip_FPM.fkM.m x.
```
Comment (herbelin) [inline test-suite/bugs/closed/3956.v]: I did not understand in which sense this is related to this PR.

**Review by herbelin — APPROVED** [review]
Looks much nicer than before!

File: test-suite/bugs/closed/3956.v (hunk 2 above)
Comment (SkySkimmer) [reply test-suite/bugs/closed/3956.v]: This is about this part:

>This fixes #3690 for real (it was added to the test suite as closed even though it was wontfix for some reason) by restricting universes after running the Eval.

Comment (herbelin) [reply test-suite/bugs/closed/3956.v]: Ah, ok, you meant #3956, not #3960. Thanks.

Comment (SkySkimmer) [reply test-suite/bugs/closed/3956.v]: No, I did mean #3960. The change in the test for #3956 is a side effect of the fix.

Comment (herbelin) [reply test-suite/bugs/closed/3956.v]: Sorry, I don't understand, there is no `Eval` in  #3960. And no ` 3960.v` in your commits. I'm confused.

Comment (SkySkimmer) [reply test-suite/bugs/closed/3956.v]: Sorry it was #3690 (eval compute in fails to minimize universes).

**Comment by SkySkimmer** [comment]
ping @mattam82

**Comment by SkySkimmer** [comment]
ping @mattam82 ping

**Review by mattam82 — APPROVED** [review]
Much nicer indeed, and bravo on the fix thanks to the improved minimization!

**Comment by mattam82** [comment]
Are the ci issues related?

**Comment by SkySkimmer** [comment]
Don't think so, but have a rebase regardless.

**Comment by SkySkimmer** [comment]
Ready to merge

**Review by ejgallego — APPROVED** [review]
