### PR TITLE
Fixes #7228: anomaly with Set Extraction Conservative Types on singletons

### LINKED ISSUE #7228: Anomaly with Set Extraction Conservative Types.
#### Version

```
% coqtop -v
The Coq Proof Assistant, version 8.7.2 (March 2018)
compiled on Mar 13 2018 2:25:05 with OCaml 4.05.0
```

#### Operating system

```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

#### Description of the problem

I encountered an Anomaly.

```
Require Extraction.
Set Extraction Conservative Types.

Inductive data := Data : forall (T:Type), T -> data.
Definition t_of d := match d with Data t _ => t end.
Definition v_of (d : data) := match d return t_of d with Data _ v => v end.
Extraction v_of.
(*
Anomaly
"File "plugins/extraction/extraction.ml", line 839, characters 3-9: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
*)
```

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** fix

We fix it by taking into account the `Extraction Conservative Types` option when computing if an inductive type is singleton.

Fixes #7228
Fixes (probably) #12831

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

File: plugins/extraction/extraction.ml [hunk 1]
```diff
@@ -488,7 +488,7 @@ and extract_really_ind env kn mib =
         if p.ip_logical then raise (I Standard);
         if not (Int.equal (Array.length p.ip_types) 1) then raise (I Standard);
         let typ = p.ip_types.(0) in
-        let l = List.filter (fun t -> not (isTdummy (expand env t))) typ in
+        let l = List.filter (fun t -> conservative_types () || not (isTdummy (expand env t))) typ in
```
Comment (ppedrot) [inline plugins/extraction/extraction.ml:491]: To clearly show the intent, I think you should extrude the check outside of the filter as in
```
let l = if conservative_types () then l else ...
```

**Comment by ppedrot** [comment]
I am assigning since it's a simple patch and the maintainers are not reactive.

File: plugins/extraction/extraction.ml (hunk 1 above)
Comment (herbelin) [reply plugins/extraction/extraction.ml]: You are right, that's better. Done.

File: plugins/extraction/extraction.ml [hunk 2]
```diff
@@ -488,7 +488,7 @@ and extract_really_ind env kn mib =
         if p.ip_logical then raise (I Standard);
         if not (Int.equal (Array.length p.ip_types) 1) then raise (I Standard);
         let typ = p.ip_types.(0) in
-        let l = List.filter (fun t -> not (isTdummy (expand env t))) typ in
+        let l = if conservative_types () then [] else List.filter (fun t -> not (isTdummy (expand env t))) typ in
```
Comment (ppedrot) [inline plugins/extraction/extraction.ml:491]: If you write it this way, you should even `raise (I Standard)` directly.

**Review by ppedrot — APPROVED** [review]
