### PR TITLE
Fix VM implementation of addmuldiv for large shifts (fix #19402).

### LINKED ISSUE #19402: Inconsistency when evaluating Uint63 addmuldiv primitive
### Description of the problem

The expression `addmuldiv 64 42 42` evaluates to 0 when using `native_compute` / `cbn` / `cbv `, which I think(?) is the correct result, while it evaluates to 42 when using `Compute` and `vm_compute`, enabling a proof of `False`.

System: Linux (Fedora) x86-64
OCaml compiler version: 4.14.1

### Small Coq file to reproduce the bug

```coq
From Coq Require Import Uint63.
Open Scope uint63.

Eval native_compute in (addmuldiv 64 42 42). (* 0 *)
Eval cbn in (addmuldiv 64 42 42).            (* 0 *)
Eval cbv in (addmuldiv 64 42 42).            (* 0 *)

Eval vm_compute in (addmuldiv 64 42 42).     (* 42 *)
Compute (addmuldiv 64 42 42).                (* 42 *)
```

### Version of Coq where this bug occurs

8.17.1, 8.19.2

### Last version of Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by silene**
This commit also makes clearer the actual types of the values.

Fixes / closes #19402 

- [X] Added / updated **test-suite**.
- [X] Added / updated **documentation**.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
I am trusting you on this one.

**Comment by ppedrot** [comment]
Did we thoroughly test for discrepancies between native and VM for the other primitives?

**Comment by silene** [comment]
There is one file per primitive in `test-suite/primitive/uint63` and they all check lazy, VM, and native. They only test a handful of inputs, though, so it will depend on your definition of "thorough".

Fortunately, Bignums-based libraries exercise both lazy and VM on the primitives (and native mostly defers to lazy). But in the case of `addmuldiv`, the failing input was outside the domain of meaningful definition of the operator, so Bignums code would not trigger the issue. We had similar issues in the past with things like division by zero and the like.

File: kernel/byterun/coq_uint63_native.h [hunk 1]
```diff
@@ -74,11 +74,12 @@
 
 /* addmuldiv(p,x,y) = x * 2^p + y / 2 ^ (63 - p) */
 /* (modulo 2^63) for p <= 63 */
-value uint63_addmuldiv(uint64_t p, uint64_t x, uint64_t y) {
+value uint63_addmuldiv(value p, value x, value y) {
+  if ((uint64_t)p >= 127) return uint63_zero();
```
Comment (proux01) [inline kernel/byterun/coq_uint63_native.h:78]: Could you explain the 127 here? According to the OCaml implem in kernel/uint63_63.ml I'd expected 64*2+1 = 129 here.
BTW, maybe permuting this with next line and having the test on `shiftby` would be more readable?

Comment (silene) [reply kernel/byterun/coq_uint63_native.h:78]: Good catch. In fact, what you suggest is what I originally wrote, but then I decided that it would be more homogeneous to follow the same convention as the other operations earlier in the file.

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now
