### PR TITLE
Fixes #7011: Fix/CoFix were not considered in main loop of tactic unification.

### LINKED ISSUE #7011: Unificiation fails to solve trivial problems under fix
#### Version

8.9+alpha

#### Description of the problem

I think this should succeed, but it fails:
```coq
Goal exists e, (fix foo (n : nat) : nat := match n with O => e | S n' => foo n' end)
               = (fix foo (n : nat) : nat := match n with O => O | S n' => foo n' end).
Proof.
  eexists.
  reflexivity. (* fails *)
```

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix, fixes #7011.

Tactic unification is eventually going to be deprecated and kept only for compatibility (as far as I understand?) but the fix is short, so in the meantime, I'm proposing one.

@mattam82: I compared types before bodies, mimicking what `evarconv.ml` is doing but I have no idea whether it is better than the converse...

### CODE REVIEW

**Comment by andres-erbsen** [comment]
Is the another kind of unification we should be using instead? Here are some failed attempts (8.7.0):

~~~~~~
Require Import Coq.Classes.Morphisms.
Goal exists e, (fix foo (n : nat) : nat := match n with O => e | S n' => foo n' end)
               = (fix foo (n : nat) : nat := match n with O => O | S n' => foo n' end).
Proof.
  eexists.
  Fail reflexivity.
  Fail eapply eq_refl.
  Fail eapply (reflexivity _).
  Fail lazymatch goal with |- ?a = ?b => unify a b end.
~~~~~~

**Comment by SkySkimmer** [comment]
You should use whatever tactic works for you, when the old unification is removed those tactics which use it will be moved to the new unification (we will try to minimize compat issues but ofc there may be some).
`exact` (and `refine`) use the new unification engine and succeed.
I think some ssr apply tactic does as well but I don't know ssr so not sure.

**Comment by Zimmi48** [comment]
Yes `apply:` uses the same unification as `refine`.

File: pretyping/unification.ml [hunk 1]
```diff
@@ -838,6 +838,26 @@ let rec unify_0_with_initial_metas (sigma,ms,es as subst : subst0) conv_at_top e
 	     with ex when precatchable_exception ex ->
 	       reduce curenvnb pb opt substn cM cN)
 
+        | Fix ((ln1,i1),(lna1,tl1,bl1)), Fix ((ln2,i2),(_,tl2,bl2)) when
+               Int.equal i1 i2 && Array.equal Int.equal ln1 ln2 ->
+            (try
+             let opt' = {opt with at_top = true; with_types = false} in
+             let curenvnb' = Array.fold_right2 (fun na t -> push (na,t)) lna1 tl1 curenvnb in
+               Array.fold_left2 (unirec_rec curenvnb' CONV opt')
+               (Array.fold_left2 (unirec_rec curenvnb CONV opt') substn tl1 tl1) bl1 bl2
```
Comment (mattam82) [inline pretyping/unification.ml]: Typo: tl1 tl1

File: pretyping/unification.ml [hunk 2]
```diff
@@ -838,6 +838,26 @@ let rec unify_0_with_initial_metas (sigma,ms,es as subst : subst0) conv_at_top e
...
+             with ex when precatchable_exception ex ->
+               reduce curenvnb pb opt substn cM cN)
+
+        | CoFix (i1,(lna1,tl1,bl1)), CoFix (i2,(_,tl2,bl2)) when
+               Int.equal i1 i2 ->
+            (try
+             let opt' = {opt with at_top = true; with_types = false} in
+             let curenvnb' = Array.fold_right2 (fun na t -> push (na,t)) lna1 tl1 curenvnb in
+               Array.fold_left2 (unirec_rec curenvnb' CONV opt')
+               (Array.fold_left2 (unirec_rec curenvnb CONV opt') substn tl1 tl1) bl1 bl2
```
Comment (mattam82) [inline pretyping/unification.ml]: Same typo. Should add a test where the types contain evars, although it's maybe not so easy to express...

**Review by mattam82 — APPROVED** [review]
LGTM, it's indeed just a missing case and clearly already handled by evarconv, so it should be forward compatible :)

**Comment by mattam82** [comment]
And yes, we should always compare types before bodies indeed.

**Comment by JasonGross** [comment]
> Should add a test where the types contain evars, although it's maybe not so easy to express...

Something like this?
```coq
Inductive foo (n : nat) : nat -> Type := bar (_ : foo n n) : foo n n.
Goal True.
  let v := open_constr:(fix a m (v : foo ?[n] m) := match v in foo _ m return foo _ m with @bar _ v' => a _ v' end) in
  pose v. (* should not fail, but does fail, with Error:
In environment
a : forall m : nat, foo ?m m -> foo ?n@{m0:=m; m:=m} m
m : nat
v : foo ?m m
v' : foo ?m ?m
Unable to unify "?n@{m0:=?m; m:=?m}" with "?n@{m0:=m; m:=?m}". *)
```
(is this a new bug?)
Or maybe something like this?
```coq
Inductive foo (n : nat) : nat -> Type := bar (_ : foo n n) : foo n n.
Goal True.
  let n := open_constr:(_) in
  let v := open_constr:(fix a m (val : foo n m) := match val in foo _ m return foo n m with @bar _ val' => a _ val' end) in
  let v' := open_constr:(fix a m (val : foo n m) := match val in foo _ m return _ with @bar _ val' => _ end) in
  pose v; pose v';
    unify v v';
    unify n 0;
    tryif has_evar v' then fail 1 else idtac.
```

**Comment by Zimmi48** [comment]
@mattam82 is on vacation for two weeks starting today so he approved this PR but he's not going to be the one to merge it.
@gares: Will you take care of it as a secondary maintainer of `pretyping/`?

**Comment by herbelin** [comment]
@JasonGross: To find an example, we would need an equation which is not too complex so that the unification knows how to solve it, and which is also not trivially derivable from unifying the bodies of the `fix`. So, I guess it has to involve a K-redex in the types (i.e. an equation on a phantom part of a type).

**Comment by gares** [comment]
@Zimmi48 no.
I see no hurry (no milestone), and @mattam82 did the review so he shall merge it.

In case the milestone was 8.8, I'd replay "I'm not going to merge a patch on unification so late in the release cycle".

**Comment by Zimmi48** [comment]
I think that @mattam82 did this review with the idea that this was a fix which could go in 8.8 (although it did not state that clearly) but I agree with your assessment that this is rather a 8.9 fix. Anyways, even if you had merged it and put it in the 8.8.0 milestone, the RM (@maximedenes) could have decided that this did not qualify and not backport it...

**Comment by herbelin** [comment]
This apparently only needs a brave soul to run the merge script.

**Comment by ejgallego** [comment]
This possibly breaks cross-crypto, as noted by @jashug on Gitter.
