### PR TITLE
[coqdep] give relative paths to META and .cmxs files.

### LINKED ISSUE #16571: coqdep generates wrong dependencies when looking for META files.
Dune's PR https://github.com/ocaml/dune/pull/6167 makes sure that the
needed `META` files are in place before calling `coqdep`/`coqc`
for Dune, which should make the new loading system in Dune
supported.

However, `coqdep` seems to produce broken dependencies.

We can reproduce as follows:

- rename `theories/dune.disabled` to `theories/dune`
- change `theories/Init/Ltac.v` to have `Declare ML Module "coq-core.plugins.ltac".` (without the compat syntax).

Now `dune build theories/Init/Ltac.v.d` will produce (simplified):

```
Init/Ltac.vo: Init/Ltac.v /home/egallego/external/coq-master/_build/install/default/lib/coq-core/META ../plugins/ltac/ltac_plugin.cmxs
```

which seems non-sense as the path to the plugin should relative to the `META`, that is to say:
`/home/egallego/external/coq-master/_build/install/default/lib/coq-core/plugins/ltac/ltac_plugin.cmxs`

This actually seems due to us passing the `-I` flag still to coqdep, and it picks the legacy one, however `coqc` will refuse to load it.

So this is bug one, coqdep and coqc exhibit different behavior here. If we call coqdep manually (with the `META` in place), we have a more puzzling error:
```
$ dune exec -- coqdep -boot -noinit -R theories Coq -dyndep opt _build/default/theories/Init/Ltac.v
*** Warning: in file _build/default/theories/Init/Ltac.v, declared ML module ./plugins/ltac/ltac_plugin has not been found!
```
So we have two problems here, first the path in incorrect, second, even if it findlib mode, we are relying on the `mlpack` file to be present, which we should not.

### PR DESCRIPTION
**Pull request by rlepigre**
This is an attempt to fix #16571.

### CODE REVIEW

**Comment by gares** [comment]
Thanks of working on this!
I think this patch really needs some tests in test-suite/misc (for example).
`coqdep` is indirectly tested by `coq_makefile`, but since that used to already work I think we need more tests.

**Comment by rlepigre** [comment]
> Thanks of working on this! I think this patch really needs some tests in test-suite/misc (for example). `coqdep` is indirectly tested by `coq_makefile`, but since that used to already work I think we need more tests.

Yeah, I know. I was hoping @ejgallego would tell me whether I should just apply the change he suggested in the issue linked above. So, basically, something like:
```diff
diff --git a/theories/Init/Ltac.v b/theories/Init/Ltac.v
index fbd60a940f..f26427dae1 100644
--- a/theories/Init/Ltac.v
+++ b/theories/Init/Ltac.v
@@ -8,6 +8,6 @@
 (*         *     (see LICENSE file for the text of the license)         *)
 (************************************************************************)
 
-Declare ML Module "ltac_plugin:coq-core.plugins.ltac".
+Declare ML Module "coq-core.plugins.ltac".
 
 Export Set Default Proof Mode "Classic".
```
I think that would already give good tests, since dune does not choke on the paths anymore.

**Comment by gares** [comment]
That would be good, for sure.
But I was more thinking about small tests of coqdep invocations, a sort of spec.

**Comment by Alizter** [comment]
@rlepigre You can also do that in a cram test if you like.

**Comment by ejgallego** [comment]
Thanks a lot for taking care of this @rlepigre , I will look into it after the ITP deadline. A few comments:

- ideally we would put the relativization path function in the general libraries, if it doesn't exist there. We may need to handle Windows paths and while I am careful to have the code never mix win / unix style (I use the native setup always) I'm unsure that's the case in other parts of the ecosystem.
- To test this with regular projects you need Dune 3.5, previous versions of dune didn't ensure the META file would be in place.
- Coq's generates its own rules so it is not affected by it.
- You may need to relativize the file that `add_dep_other_meta_file` emits.

To sum how a dune build works using this feature, let me review the build process:
- dune computes _all_ the dependencies for .v files using coqdep
- coqdep requires files to be in file system for it work
- when a dune theory depends in a plugin, and is gonna use findlib, we first need to setup the right context for coqdep
- that means, for an A.v file, all the sources of A's theory + depending theories need to be in place
- for plugins, Dune ensures that _before_ calling coqdep, the meta files are in place (and the mlpack files if present for legacy plugins)
- now we call coqdep, and meta files are in place and visible in OCALPATH, then coqdep will emit the deps for the file plus the deps for the .cmxs which has been located using findlib thanks to dune putting the META file in place before calling coqdep
- the file can now build normally, as dune will build the cmxs plugins in the install layout, so loading with findlib should work

There could be some issues with this setup, for example I'm not sure if Dune will also correctly place the dependencies of the findlib plugin in the install path, so if that's the case we'll have to fix dune (easy) and use a workaround meanwhile.

What I mean is imagine  workspace with the following setup:
- plugin A that depends on ocaml library B
- dune coq rule will put A metas in place, coqdep will emit correct cmxs dep
- but at runtime, B meta file and plugin is not there

So not sure what will happen in this case, we could do the dependency injection ourselves, but this is never a good thing to do in the build system, so if that case is problematic we should take a couple of days to reflect about it.

@rlepigre I agree with you that it is unfortunate that legacy mode is triggered when a package name has a dot. I suggested using a new command name but it was rejected. That's a problem that you'll have to workaround injecting a fake dep.

**Comment by ejgallego** [comment]
@coqbot run full CI

**Comment by rlepigre** [comment]
I added test cases using cram tests, as suggested by @Alizter.

I'm now wondering about other options for dune:
- We could have dune use the `-m` option (not sure we want that).
- We could also have dune extend the `OCAMLPATH` using a relative path.

In any case, I don't think the proposed change would hurt too much: you would only get a weird behaviour (a relative path that you could expect to be absolute) when using `Declare ML Module ...` with a findlib package coming from an external library, which I think is never reasonable.

**Comment by SkySkimmer** [comment]
Is this going to be like last time cram tests were tried, ie when they fail it's hard to  find the failure in the CI log?

**Comment by rlepigre** [comment]
> Is this going to be like last time cram tests were tried, ie when they fail it's hard to find the failure in the CI log?

No idea, I wasn't there the last time. Maybe they could be run separately with the `@runtest-cram` alias I defined.
```
dune build @runtest-cram
```

**Comment by ejgallego** [comment]
We hit the limitation of make not being able to parse `..`, ahhh.

**Comment by rlepigre** [comment]
> We hit the limitation of make not being able to parse `..`, ahhh.

Would it be enough to normalize away the `<dir>/..`?

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
The test suite prints NO FAILURES even though it's failing.
https://gitlab.com/coq/coq/-/jobs/3995874123

**Review by SkySkimmer — DISMISSED** [review]
To be clear I oppose adding cram tests until https://github.com/coq/coq/pull/16583 is merged
Otherwise we are going to have to deal with irritating test suite bugs

**Comment by Alizter** [comment]
@coqbot run full ci

**Comment by rlepigre** [comment]
I figured out I was not normalizing paths enough in some cases (which impacted mainly `coqhammer` it seems, because it has a relative path using `..` to a `.cmxs` in a META file), and this is now fixed.

Could someone take this over and push it through?

Note that I re-ordered the commits so that the cram test commit can be removed trivially. I don't have time to turn these tests into something else myself.

**Comment by ejgallego** [comment]
@coqbot run full CI

**Comment by rlepigre** [comment]
CI failures seem totally unrelated (no space left on device, network failure, ...).

**Comment by rlepigre** [comment]
The last remaining CI failure seems unrelated: missing an overlay?

**Comment by ppedrot** [comment]
Yes, itauto is broken on master due to an early overlay merge.

File: tools/coqdep/lib/fl.ml [hunk 1]
```diff
@@ -86,18 +86,54 @@ let rec find_plugin meta_file plugin_name path p { Fl_metascanner.pkg_defs ; pkg
     let path = path @ [find_plugin_field "directory" "." c.Fl_metascanner.pkg_defs] in
     find_plugin meta_file plugin_name path ps c
 
+let to_relative_path : string -> string = fun full_path ->
```
Comment (ejgallego) [inline tools/coqdep/lib/fl.ml:89]: A comment here wouldn't hurt IMVHO.

**Review by ejgallego — APPROVED** [review]
LGTM.

- @rlepigre can you move the cram tests to a different PR so I can merge?
- @Alizter I understand than Dune and Jane Stree Core may already have implementations of the `to_relative_path` function? If so it'd be maybe good to open an issue to eventually replace this implementation by a more tested one.

File: tools/coqdep/lib/fl.ml (hunk 1 above)
Comment (rlepigre) [reply tools/coqdep/lib/fl.ml:92]: I added documentation for both file functions, and also ran some tests locally:
```
Tests for [normalize_tests]:
 - normalize "." = "."
 - normalize "./dir1/dir2/test.v" = "dir1/dir2/test.v"
 - normalize "dir1/dir2/" = "dir1/dir2/"
 - normalize "/" = "/"
 - normalize "/tmp/dir" = "/tmp/dir"
 - normalize "/tmp/dir/" = "/tmp/dir/"
 - normalize "/tmp/dir/../dir2/../dir1/././dir3" = "/tmp/dir1/dir3"
 - normalize "/tmp/dir/./" = "/tmp/dir/"
 - normalize "/tmp/dir/.//" = "/tmp/dir//"
Tests for [to_relative_path] (PWD = "/home/rodolphe/dev/coq/coq-coqdep"):
 - to_relative_path "/tmp/" = "../../../../../tmp/"
 - to_relative_path "/home/rodolphe/" = "../../../"
 - to_relative_path "/home/rodolphe/../john" = "../../../../john"
 - to_relative_path "/home/rodolphe/../../tmp/../tmp/file.txt" = "../../../../../tmp/../tmp/file.txt"
```
This helped uncover a bug, but we would never have hit it here, since we are working with path to actual files (not directories).

**Comment by ejgallego** [comment]
> @ejgallego You are correct that stdune has an implementation. Not sure about JS Core tho. I don't think it is worth pulling another dep but we can definitely compare the implementations to be sure ours works correctly.

Yes the idea is not to pull the dep for now, but to "vendor" it.

**Comment by ejgallego** [comment]
Will merge soon, @SkySkimmer can you re-review now that the tests have been separated?

**Comment by ejgallego** [comment]
@Alizter can you link to the stddune implementation?

**Comment by Alizter** [comment]
IINM:

https://github.com/ocaml/dune/blob/6f8952c791d5a0053191021610dbadb048cc605f/otherlibs/stdune/src/path.ml#L97-L131

**Comment by ejgallego** [comment]
Can't get the CI to work reliably... but seems fine.

@coqbot: merge now
