### PR TITLE
CoqIDE: A few fixes in file management

### LINKED ISSUE #3977: Drag-and-drop to open documents in CoqIDE fails with "Load failed: no such file"
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#3977
From: @JasonGross
Reported version: 8.5
CC:   coq-bugs-redist@lists.gforge.inria.fr

### PR DESCRIPTION
**Pull request by Frigory33**
- More explicit message when trying in vain to open a file without extension
- Correctly load dropped files, using `filename_from_uri` (instead of a custom regexp which did not handle well all cases)
- Remove extension in tab label (as usual) when changing a file’s location
- Say “reload” instead of “revert” for files

Fixes #3977

- [x] Added **changelog**.

### CODE REVIEW

**Comment by Frigory33** [comment]
Should I split my commit into several commits?

**Comment by ppedrot** [comment]
@Frigory33 indeed, splitting the commits would be better.

**Comment by MSoegtropIMC** [comment]
I am not sure I like the renaming of "revert" to "reload" - IMHO "revert" is more to the point.

I would call such an operation "revert" if the changes one does are usually valuable and "reload" if the changes one does usually more mess up than improve things.

But I don't have strong feelings about it.

**Comment by Frigory33** [comment]
@jfehrle told me that “revert” should be changed to “reload,” and I had the same opinion, this is why I made the change. Using this feature is useful if you change the file with another program. In this case, the action is not a “revert” at all, but it is completely a “reload.”

**Comment by MSoegtropIMC** [comment]
@Frigory33 : the "changed elsewhere" scenario is indeed a good point - I sometimes have one file open in VSCoq for editing and in CoqIDE for Ltac debugging. I still tend more to `revert` because the "changed elsewhere" scenario should be rare, but as I said, I don't have string feelings about it.

**Comment by jfehrle** [comment]
Gentlemen: "revert" is the wrong word.  It doesn't accurately describe the associated operation.

If we don't fix details like this, one thing leads to another and eventually to the fall of Western Civilization.  That would be bad, so let's do the right thing here.  :-)

**Comment by herbelin** [comment]
On the other side, in "revert" there is the idea to renounce to the existing changes, and this is not present in "reload"?

The web looks undecided: https://discourse.jupyter.org/t/revert-vs-reload-from-disk/13844, https://intellij-support.jetbrains.com/hc/en-us/community/posts/207010565-Revert-file-changes-in-editor-to-disk-saved-version, ...

Emacs uses "revert-buffer".

Maybe can it be called "Reload/Revert"?

(In any case, whatever choice is done will be ok to me.)

**Comment by ppedrot** [comment]
Bikeshedding the name of a feature that reeks of a hack to work around missing polling APIs and thus should be replaced seems a bit of a waste of time. In all modern editors I know of, if a file is modified on disk while opened the user gets informed about that through a dialogue and can chose to reload / ignore / close. CoqIDE is the only editor that has this weird feature, maybe it's time to use the GIO polling APIs.

**Comment by herbelin** [comment]
> a bit of a waste of time

Technically yes, but socially...

**Comment by jfehrle** [comment]
Agreed, the existing behavior isn't very good.  Some time ago I looked at reloading files when CoqIDE regains focus from another application, but I couldn't figure out how to detect regaining focus.

IMO reloads should be automatic if the buffer hasn't changed and perhaps should give a prompt if both the buffer and the underlying file have been changed.  Showing a prompt for each changed file can be tedious, e.g. if I check out a different commit with git.

I would also have CoqIDE write modified files when it loses focus.  Then I don't need to consider multiple versions of the file in various places.  If I want to truly revert something, I use git.  I also make heavy use of diffs to see what I've changed.  It would nice if CoqIDE could conveniently launch a diff viewer.

If @Frigory33 is interested in making improvements along these lines and can get it to work, great!  If not, correcting the name at least where it's user-visible is still a reasonable change.  We should generally encourage new PR submitters rather than make them jump through hoops.  I do run across comments from time to time that the Coq team is hard to work with.

File: ide/coqide/fileOps.ml [hunk 1]
```diff
@@ -61,35 +61,35 @@ object(self)
...
-        if not buffer#modified then do_revert f
+        if not buffer#modified then do_reload f
         else
           let answ = Configwin_ihm.question_box
             ~title:"Modified buffer changed on disk"
-            ~buttons:["Revert from File";
+            ~buttons:["Reload from File";
                       "Overwrite File";
-                      "Disable Auto Revert"]
+                      "Disable Auto Reload"]
```
Comment (jfehrle) [inline ide/coqide/fileOps.ml:79]: These names in the preferences dialog are lousy, too.  I had to read the code to figure out what they do.  Maybe "Check for modified files" and "Modified file check interval" are better.  "auto" is misleading in that the user has to agree by clicking in the dialog.

image

File: doc/changelog/10-coqide/18524-coqide.rst [hunk 2]
```diff
@@ -0,0 +1,5 @@
+- **Fixed:**
+  Loading dropped files whose name contains special characters
+  (`#17421 <https://github.com/coq/coq/pull/17421>`_,
```
Comment (jfehrle) [inline doc/changelog/10-coqide/18524-coqide.rst:3]:
```suggestion
  (`#18524 <https://github.com/coq/coq/pull/18524 >`_,
```

File: doc/changelog/10-coqide/18524-coqide.rst [hunk 3]
```diff
@@ -0,0 +1,5 @@
...
+  fixes `#3977 <https://github.com/coq/coq/issues/3977>`_,
```
Comment (jfehrle) [inline doc/changelog/10-coqide/18524-coqide.rst:4]: I had no idea that CoqIDE could do drag and drop.  That would be a good thing to mention in the CoqIDE section of the documentation (one sentence should do it, eg "You can open files by dragging their icons from your file manager and dropping them in the CoqIDE window.")

File: doc/changelog/10-coqide/18524-coqide.rst [hunk 4]
```diff
@@ -0,0 +1,5 @@
+- **Fixed:**
+  Loading dropped files whose name contains special characters
```
Comment (jfehrle) [inline doc/changelog/10-coqide/18524-coqide.rst:2]:
```suggestion
  Opening a file with drag and drop now works correctly (fixed regression)
```

This was a regression.  In 8.13, drag and drop works fine except for spaces and Unicode characters, but `-` looks fine.

image

File: ide/coqide/coqide.ml [hunk 5]
```diff
@@ -117,9 +117,12 @@ let make_coqtop_args fname =
...
         (* otherwise the default “Top” will be used. *)
-        match Unicode.ident_refutation (Filename.chop_extension (Filename.basename fname)) with
-        | Some _ -> args
-        | None -> "-topfile"::fname::args
+        try
+          match Unicode.ident_refutation (Filename.chop_extension (Filename.basename fname)) with
+          | Some _ -> args
+          | None -> "-topfile"::fname::args
+        with Invalid_argument _ ->
+          failwith "CoqIDE cannot open files which do not have an extension in their filename."
```
Comment (jfehrle) [inline ide/coqide/coqide.ml:125]: User should be able to open and edit files that don't have an extension, such as _CoqProject.

**Review by jfehrle — COMMENTED** [review]
A few thoughts

**Comment by herbelin** [comment]
> maybe it's time to use the GIO polling APIs

Maybe

File: doc/changelog/10-coqide/18524-coqide.rst (hunk 2 above)
Comment (Frigory33) [reply doc/changelog/10-coqide/18524-coqide.rst]: My bad… Fixed.

**Comment by Frigory33** [comment]
> If @Frigory33 is interested in making improvements along these lines and can get it to work, great!

Not so soon. CoqIDE should be rewritten before to use a more complete and updated GUI library, and must be a separate project.

**Review by jfehrle — APPROVED** [review]
LGTM.

If there are no objections, I will merge soon.

**Comment by jfehrle** [comment]
@coqbot: merge now

**Comment by jfehrle** [comment]
@coqbot: merge now
