### PR TITLE
Fix variable name capture when using `Fast Name Printing` flag

### LINKED ISSUE #14141: Fast name printing seemingly causes variable capture
#### Version

Coq 8.13.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following program leads to a proof state,
where the same name refers to two different variables.

```
Set Fast Name Printing.

Lemma le_succ_diag_r (n : nat) : n <= S n.
Proof.
  apply (nat_ind (fun p : nat => p <= S n)).
  - apply le_0_n.
  - Show 1. rename n into p. Show 1. Abort.
```

```
subgoal 1 is:

  n : nat
  ============================
  forall (n : nat) (H : n <= S n), S n <= S n

subgoal 1 is:

  p : nat
  ============================
  forall (n : nat) (H : n <= S p), S n <= S p
```

#### Notes

I did not notice fast name printing to be particularly fast.

### PR DESCRIPTION
**Pull request by WojciechKarpiel**
Fixes / closes #14141

The root cause was in the algorithm that finds the greatest subscript for all identifiers (i.e. creates a map identifier -> subscript).
The algorithm treated not-yet-collected identifiers as already-collected-with-empty-subscript ones.
It worked like this:

1. Initially, the `identifier -> subscript` map is empty
1. We try to add an identifier `n` without a subscript to the map
1. We want to check if the identifier is already associated with and equal-or-greater subscript
1. [bug] We assume that we already have `n` with empty subscript in the map
1. Since we already have `n` without subscript in the map, we don't have to add it

And so the solution is explicit handling of identifier-not-yet-in-the-map case

- [x] Added / updated **test-suite**.

- [x] Added **changelog**.

### CODE REVIEW

File: pretyping/detyping.ml [hunk 1]
```diff
@@ -130,8 +130,8 @@ let make ~fast ids =
   if fast then
     let fold id accu =
       let id, ss = get_subscript id in
-      let old_ss = try Id.Map.find id accu with Not_found -> Subscript.zero in
-      if Subscript.compare ss old_ss <= 0 then accu else Id.Map.add id ss accu
+      let old_ss = Id.Map.find_opt id accu in
+      if Option.compare Subscript.compare (Some ss) old_ss <= 0 then accu else Id.Map.add id ss accu
```
Comment (ppedrot) [inline pretyping/detyping.ml:134]: Written this way, the intent is not very clear. I'd rather have something like this:
```suggestion
      match old_ss  with None -> accu | Some old_ss -> if Subscript.compare ss old_ss <= 0 then accu else Id.Map.add id ss accu
```

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
