### PR TITLE
Fail cleanly if clearbody asked to clear unbound variable

### LINKED ISSUE #20919: Anomaly (Assertion failed) in `clearbody` inside `match`
### Description of the problem

When using the `clearbody` tactic inside a `match` tactic, if the matched variable is not currently in the proof context, Rocq crashes with an internal assertion failure. The expected behavior would be for `clearbody` to fail

In versions <8.15.1 (e.g., 8.15.0), `clearbody x` does not crash but the tactic unexpectedly succeeds.

Error message in versions 8.15.1:
``` $ coqc test.v
File "./test.v", line 3, characters 0-69:
Error:
Anomaly
"File "tactics/tactics.ml", line 2126, characters 16-22: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

### Small Rocq / Coq file to reproduce the bug

```coq
Goal forall n: nat, n = n -> True.
intros.
match n with
| ?x => generalize dependent x;
        assert_fails clearbody x
end.
```

### Version of Rocq / Coq where this bug occurs

>=8.15.1

### Interface of Rocq / Coq where this bug occurs

_No response_

### Last version of Rocq / Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by yannl35133**
Fixes / closes #20919

### CODE REVIEW

File: tactics/tactics.ml [hunk 1]
```diff
@@ -1917,6 +1917,11 @@ let clear_body idl =
     let sigma = Proofview.Goal.sigma gl in
     let ctx = named_context env in
     let ids = Id.Set.of_list idl in
+    let () =
+      match Id.Set.find_first_opt (fun v -> not (mem_named v env)) ids with
+      | Some v -> TacticErrors.variable_has_no_value v
```
Comment (SkySkimmer) [inline tactics/tactics.ml:1922]: is that the right error?

Comment (yannl35133) [reply tactics/tactics.ml:1922]: There's no error for unbound variables readily available (AFAICT), since it's supposed to be handled by the elaborator (not sure it's the right name) for ltac. Since the message says "var doesn't have a body", it's still true and clearly comes from that tactic.
I get that it's not perfect, but it's in the vibe of the existing "close enough" messages in other tactics.

**Comment by ppedrot** [comment]
@coqbot run full ci

File: tactics/tactics.ml (hunk 1 above)
Comment (ppedrot) [reply tactics/tactics.ml:1922]: I find this a bit dubious but not really critical, so I'm fine with leaving this as-is.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Merging soon if no complaints.

**Comment by ppedrot** [comment]
@coqbot merge now
