### PR TITLE
Remove the Lforce node from the generic lambda AST.

### LINKED ISSUE #18715: Incorrect compilation of lazy native definitions in presence of variables
This is a byproduct of #18692. Native compilation wraps some definitions in a lazy node, but generates garbage code if this code happens to refer to free variables.

```coq
Section Foo.

Variable f : nat -> nat.

Definition foo := f 0.

Eval native_compute in foo.
(* Fails with:
  Native compiler exited with status 2 (in case of stack overflow, increasing stack size
  (typically with "ulimit -s") often helps)
The real error from the OCaml compiler is:
  Error: This expression has type (Nativevalues.t -> Nativevalues.t) lazy_t
         This is not a function; it cannot be applied.
*)
```
This can probably be weaponized into a segfault.

### PR DESCRIPTION
**Pull request by ppedrot**
We move the code responsible from the generation of the forcing of lazy constants in the native compiler to the second compilation phase. This also has the nice side-effect of encapsulating the code that decides to make a constant lazy behind a sealed API.

Additionally fixes the following issues discovered in the meantime.

Fixes #18715: Incorrect compilation of lazy native definitions.
Partial fix of #18703: Incorrect characterization of computational terms in native_compute.

### CODE REVIEW

File: kernel/nativecode.ml [hunk 1]
```diff
@@ -1225,7 +1246,9 @@ let compile_prim env decl cond paux =
   | Lconst (c, u) ->
      let prefix = env.env_const_prefix c in
      let args = ml_of_instance env.env_univ u in
-     mkMLapp (MLglobal(Gconstant (prefix, c))) args
+     let ans = mkMLapp (MLglobal(Gconstant (prefix, c))) args in
+     if env.env_const_lazy c then MLapp (MLglobal (Ginternal "Lazy.force"), [|ans|])
+     else ans
```
Comment (silene) [inline kernel/nativecode.ml:1251]: Maybe I am missing something, but this does not make sense at all to me. If I parse the code correctly, you are generating `Lazy.force (Prefix.c args...)`, while the correct code should be `(Lazy.force Prefix.c) args...`.

Do we even have something in the testsuite that tests native compilation?

Comment (ppedrot) [reply kernel/nativecode.ml:1251]: You're definitely right about this being wrong. I thought that the CI had a few tests of native compilation, but maybe this is not the case. Note that it didn't run properly on this PR due to unrelated docker issues, so maybe  the CI would have caught it.

**Comment by ppedrot** [comment]
I'll let the CI finish before fixing this, just to check whether we actually test anything about native compilation in there.

File: kernel/nativecode.ml (hunk 1 above)
Comment (silene) [reply kernel/nativecode.ml:1251]: Actually, now that I look more closely at the old code, you did not change the semantics. The native code that was generated for polymorphic constants was wrong, and it was only working fine by accident (and thus it still works fine by accident).

File: kernel/nativecode.ml [hunk 2]
```diff
@@ -67,6 +72,20 @@ let get_const_prefix env c =
    | NotLinked -> ""
    | Linked s -> s
 
+let get_const_lazy env =
+  let cache = ref Cmap_env.empty in
```
Comment (SkySkimmer) [inline kernel/nativecode.ml:76]: Is the cache actually useful? This doesn't seem like a complex computation.

File: kernel/nativecode.ml (hunk 1 above)
Comment (SkySkimmer) [reply kernel/nativecode.ml:1251]: We have some tests of native_compute in CI but maybe not on univ poly constants which use the lazy code.

File: kernel/nativecode.ml (hunk 2 above)
Comment (ppedrot) [reply kernel/nativecode.ml:76]: It cannot hurt, at least, the amount of added code is tiny.

File: kernel/nativecode.ml (hunk 1 above)
Comment (silene) [reply kernel/nativecode.ml:1251]: To be clear, the `force` is in the wrong place for polymorphic constants, but since the `lazy` is also in the wrong place, it just works. The thing is, `force` and `lazy` should never have been used for polymorphic constants, since they are actually functions.

File: kernel/nativecode.ml [hunk 3]
```diff
@@ -52,6 +52,11 @@ let fresh_lname n =
   incr lname_ctr;
   { lname = n; luid = !lname_ctr }
 
+let is_lazy t =
+  match Constr.kind t with
+  | App _ | LetIn _ | Case _ | Proj _ -> true
+  | _ -> false
```
Comment (silene) [inline kernel/nativecode.ml:58]: Now that I look at it, this function seems especially fragile, since the default case is `_ -> false`. It should have been the opposite: it is the negative cases that should have been listed explicitly, so that new constructors safely fall in the positive case. (Either that or both positive and negative cases should have been listed, in order to force people to think about the categorization of new constructors.)

In particular, it seems like a serious bug that `Array` is not marked as positive. (And possibly `Cast` is just as bad.)

**Comment by ppedrot** [comment]
Should I seize the opportunity of this PR to integrate the proposed fixes in the discussion?

File: kernel/nativecode.ml (hunk 1 above)
Comment (ppedrot) [reply kernel/nativecode.ml:1251]: I'm not even sure I understand the logic for the handling of free variables in `Nativecode.apply_fv`. How can the wrapping in a lazy node work if we apply it to the free variables immediately after? The check for laziness is applied to the original term, which is not λ-abstracted over the free variables. So we end up trying to apply a lazy object to something if the term is e.g. an application that contains free variables.

Comment (silene) [reply kernel/nativecode.ml:1251]: Only toplevel definitions are made lazy, so there should never be any free variable in them. Or am I misunderstanding your remark?

Comment (ppedrot) [reply kernel/nativecode.ml:1251]: Toplevel definitions in a section may contain variables, though. Or is native compilation doing special things in sections?

File: kernel/nativecode.ml (hunk 3 above)
Comment (silene) [reply kernel/nativecode.ml:58]: I confirm that it is a bug that `Cast` is not there. As for `Array`, I am pretty sure that it is a bug too, but I cannot trigger it yet because `Array` actually triggers an even worse bug. (As they say, it is the gift that keeps on giving...)

File: kernel/nativecode.ml (hunk 1 above)
Comment (ppedrot) [reply kernel/nativecode.ml:1251]:
```coq
Section Foo.

Variable f : nat -> nat.

Definition foo := f 0.

Eval native_compute in foo.
```
gives
```
Native compiler exited with status 2 (in case of stack overflow, increasing stack size
(typically with "ulimit -s") often helps)
```
That doesn't look fine.

Comment (ppedrot) [reply kernel/nativecode.ml:1251]: The real error spitted out by the OCaml compiler is actually
```
Error: This expression has type (Nativevalues.t -> Nativevalues.t) lazy_t
       This is not a function; it cannot be applied.
```
so indeed the generated code is garbage.

Comment (silene) [reply kernel/nativecode.ml:1251]: Interesting. I thought section variables were compiled as accumulators, not as free variables.

Comment (silene) [reply kernel/nativecode.ml:1251]: Oh, they are compiled as actual accumulators. But terms that are referencing them do not directly use these named constants. They instead use free variables, which are then instantiated with the named constants. (And since `lazy` was introduced just before the instantiation, the code is garbage.)

**Comment by ppedrot** [comment]
This should be ready. I haven't touched the semantics of laziness for array nodes since we probably need to decide for a more robust principle, but at least the cast nodes are handled correctly and the pattern-matching is total.

**Comment by ppedrot** [comment]
This needs an assignee. @silene ?

**Review by SkySkimmer — CHANGES_REQUESTED** [review]

**Comment by ppedrot** [comment]
Fixed.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by silene** [comment]
Since it only fixes one of the three issues listed in #18703 (only `Cast`, neither `Array` nor `Prod`), please remove the "Fixes" line from your original message, so that Github does not automatically close the issue.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now
