### PR TITLE
Fix relevances in identity coercions

### LINKED ISSUE #21799: Identity Coercion uses incorrect relevance mark with SProp.
### Description of the problem

Identity Coercion of SProps doesn't work, I think because the relevance marker is hard coded as relevant in build_id_coercion, e.g., [here](https://github.com/rocq-prover/rocq/blob/d7e59e734298802f84c547f195033662296e7f0c/vernac/comCoercion.ml#L189)

### Small Rocq / Coq file to reproduce the bug

```coq
Inductive sTrue : SProp := sI.
Class Foo (x : SProp) : SProp := foo : x.
Definition Bar := Foo sTrue.
Identity Coercion Bar_to_Foo : Bar >-> Foo.

(* Binder (x : "Bar") has relevance mark set to relevant but was expected to be irrelevant
(maybe a bugged tactic). *)
```

### Version of Rocq / Coq where this bug occurs

9.1.0

### Interface of Rocq / Coq where this bug occurs

_No response_

### Last version of Rocq / Coq where the bug did not occur

8.17.0

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #21799

### CODE REVIEW

File: vernac/comCoercion.ml [hunk 1]
```diff
@@ -174,32 +173,33 @@ let error_not_transparent source =
...
 let build_id_coercion ?loc idf_opt source poly =
+  let open EConstr in
   let env = Global.env () in
   let sigma = Evd.from_env env in
   let sigma, vs = match source with
     | CL_CONST sp -> Evd.fresh_global env sigma (GlobRef.ConstRef sp)
     | _ -> error_not_transparent source in
-  let vs = EConstr.Unsafe.to_constr vs in
-  let c = match constant_opt_value_in env (destConst vs) with
+  let c = match constant_opt_value_in env (Constr.destConst (EConstr.Unsafe.to_constr vs)) with
```
Comment (ppedrot) [inline vernac/comCoercion.ml:182]: I find this to be a very contrived way to write it, but I'm not sure I could do better so...

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
