### PR TITLE
Fixes #11237: support constructor with parameters in primitive notations for patterns

### LINKED ISSUE #11237: String notation and pattern matching: “No interpretation for string [...]”
#### Description of the problem

I am currently experimenting with string notation, and as far as I can tell, it looks like it does not work with a `match ... with ... end` construction, at least when used as a pattern. I have made a quick research in the currently opened issues and found noting related.

Here is a minimal example that triggers the issue I am facing.

```coq
Inductive bytes := wrap_bytes { unwrap_bytes : list byte }.

Delimit Scope bytes_scope with bytes.
Bind Scope bytes_scope with bytes.
String Notation bytes wrap_bytes unwrap_bytes : bytes_scope.

Open Scope bytes_scope.

Example test_match :=
  match "foo" with
  | "foo" => "bar"
  | "bar" => "foo"
  | x => x
  end.
```

It says there is no interpretation for string "foo", even if `Eval compute in "foo"` works.

Note that the following snippet actually works.

```coq
From Coq Require Import String.

Open Scope string_scope.

Example test_match :=
  match "foo" with
  | "foo" => "bar"
  | "bar" => "foo"
  | x => x
  end.
```

#### Coq Version

```
The Coq Proof Assistant, version 8.10.2 (December 2019)
compiled on Dec 3 2019 14:32:10 with OCaml 4.08.0
```

### PR DESCRIPTION
**Pull request by herbelin**
This is fixed by forcing the parameters of the constructors to be `_` when coming from a notation.

We also provide support for a notation at the head of an "in" clause of "match".

Fixes / closes #11237

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

File: dev/ci/ci-vst.sh [hunk 1]
```diff
@@ -11,9 +11,9 @@ if [ "$DOWNLOAD_ONLY" ]; then exit 0; fi
...
 
-ulimit -s
-ulimit -s 65536
-ulimit -s
+sudo ulimit -s
+sudo ulimit -s 65536
+sudo ulimit -s
 ( cd "${CI_BUILD_DIR}/vst"
   make IGNORECOQVERSION=true
 )
```
Comment (Zimmi48) [inline dev/ci/ci-vst.sh:19]: Same comment as in #17903.

Comment (herbelin) [reply dev/ci/ci-vst.sh]: That was debugging code introduced to locally run `make ci-vst`. It shoud not have been committed. Thanks for noticing. Fixed.

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now
