### PR TITLE
Fix #11351 : Version picking for 8.11

### LINKED ISSUE #11351: Version picking for 8.11
This is not really an issue, more a reminder and maybe a point for discssion. There appear to be a few deviations from the discussed policy in the version picking in file `dev\ci\ci-basic-overlay.sh` for 8.11:

- bignums_CI_REF:=v8.11 is a branach
- mtac2_CI_REF:=master-8.11 is a branch
- paramcoq_CI_REF:=v8.11 is a branch

I guess you plan to replace these with hashes and/or tags shortly before the release?

Everything else is set to commit hashes. Is it really so that for none of the addons we can pick proper tagged releases? Afaik the discussed policy is to use the latest tagged release unless this doesn't work.

If any of the picks are controversial and need testing or if I can help otherwise with this please let me know.

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
This PR picks suitable versions for all addons delivered in the Windows Installer with Coq 8.11.

The rationale behind each pick is described in dev/ci/ci-basic-overlay.sh.

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
P.S.: I am not super happy with the pciking for Coq-Interval. Since it needs heavy not very portable patching for 8.11 it is time consuming toi play with versions, but I see what I can do. But the current pick is not that bad. It is a bit arbitrary but well tested.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@MSoegtropIMC thanks a lot, I'll merge this as soon as CI passes.

**Comment by MSoegtropIMC** [comment]
@ppedrot ; can we wait until I reviewed the Interval pick? It works but some things look a bit slow.

**Comment by ppedrot** [comment]
Fine.

File: dev/ci/ci-basic-overlay.sh [hunk 1]
```diff
@@ -31,11 +46,43 @@
...
+#
+# The latest 8.10 tag v1.3.2-8.10
+# - has just 5 commit from Jan 2 2020 since Mar 15 2019
+# - does not include a port of the commit used before picking
+#   => looks old
+#
+# The commits on master beyond c33e66c look like adoptions to changes not in 8.11
+#
+# => Continue to use c33e66c8f2924449c7b98aab108d97b5ee105bab from Nov 4 2019
+# => Ask upstream to tag this as 8.11.0
```
Comment (Zimmi48) [inline dev/ci/ci-basic-overlay.sh]: Or rather, ask upstream to tag this as `v...-8.11`. Reusing version numbers from Coq for external packages is a practice that was started in coq-contribs but that we should not encourage beyond.

File: dev/ci/ci-basic-overlay.sh [hunk 2]
```diff
@@ -90,49 +137,166 @@
...
+# Before picking this was on 839a03e1bddbafab868fbceee59abe678e32a0f3
+# = Jul 20 2019 master
+#   "Avoid uncontrolled characters (e.g., 'C:/') as arguments to $(addprefix)."
+#
+# There are no Coq version specific tags or branches
+#
+# The latest tag is interval-3.4.1 from "5 months ago"
+# - This tag does not compile with Coq 8.11 mostly cause of library incompatibilities
+#
+# The hash 839a03e1bddbafab868fbceee59abe678e32a0f3 has been patched to work woth 8.11
```
Comment (Zimmi48) [inline dev/ci/ci-basic-overlay.sh]:
```suggestion
# The hash 839a03e1bddbafab868fbceee59abe678e32a0f3 has been patched to work with 8.11
```

**Comment by MSoegtropIMC** [comment]
@ppedrot : it doesn't look good. I have various issues with various plugins (apparently different issues with different plugins) - things which did work in 8.10.2.

E.g. for equations the cmxs file is missing. For gappa the plugin does not work (the cmxs file appears to be there, though). For gappa this could be a library compatibility issue (tactics compile but don't work cause of someone had the idea to introduce a list of Reals with constructors also named cons and nil which hides the usual list constructors).

**Comment by MSoegtropIMC** [comment]
@mattam82 : I need some help with the Equations plugin version picking. My version picking rationale for equations was:
```
# Picking:
#
# Before picking this was on b593e3734f01c6f9c05987e4af593d2712025ae3
# = Nov 5 2019 master
#   "Fix Make dependencies of test-suite and examples" on master
#
# There are no 8.11 specific tags or branches
# - there are Coq version specific tags and branches => request tag
#
# The latest tag is v1.2.1-8.10-2
# - it includes a backport of b593e37 (25bed60) and a few more changes.
# - it does NOT compile with Coq 8.11
#
# Choosing b593e37 seems to be arbitrary (latest on master on that day)
# - still 8.11 beta was done with this pick, so keep it.
#
# => Choose b593e37
# => Ask upstream to tag this as 8.11.0
```
Unfortunately the version I picked does compile but it has installation issues. In the install log I get about 60 informational messages (why is this not an error?) of the form:
```
SKIP src/equations_plugin.cmxs since it has no logical path
SKIP src/equations_plugin.cmxa since it has no logical path
```
As a result the cmxs file is missing in the installer.

Are you aware of such issues? Do you agree with my pick or should I pick somethign else? Should I patch up the version I picked to work? Note: this was working fine in 8.10.2.

File: dev/ci/ci-basic-overlay.sh (hunk 1 above)
Comment (MSoegtropIMC) [reply dev/ci/ci-basic-overlay.sh]: @Zimmi48 : I am not sure I understand what you mean. With my comment I intended to say that I want to ask upstream to tag the picked version such that it is obvious that this is the version included in 8.11.0. For the sake of speed I don't care that much if this is done before or after the release - for me it doesn't matter much if we use the hash or a tag with the same hash. But for long term maintenance it is helpful to tag it like this, even after the facts, so that people looking at the upstream repo understand the history.

Comment (Zimmi48) [reply dev/ci/ci-basic-overlay.sh]: I totally support this. I was just saying: don't suggest to project maintainers to literally use "8.11.0" as the tag name. But maybe that was not your intention indeed.

**Comment by ppedrot** [comment]
@MSoegtropIMC Equations changed its compilation script, and this was backported to 8.11 IIRC. In any case, summoning @mattam82.

**Comment by MSoegtropIMC** [comment]
@ppedrot : I did some tests (run examples, ...) for most stuff I deliver in the installer. The results are:
```
bignums      OK
equations    Fail - cmxs not installed
mtac2        OK
mathcomp     OK
menhir       not tested
menhirlib    not tested 
compcert     not tested 
extlib       OK
quickchick   OK
coquelicot   OK
vst          OK
aactactics   OK
flocq        Some issues with examples - not sure if these are maintained (some seem to not be adjusted to the changes in field)
interval     OK
gappa_tool   Fail (likely Rlist issues)
gappa
```

**Comment by mattam82** [comment]
There was some issue with the installation target indeed, that appeared in master IIRC. Let me make an 8.11 tag with it.

**Comment by MSoegtropIMC** [comment]
@ppedrot : just wanted to let you know that I am still looking into the Gappa issue. It is something at the OCaml level - I am debugging.

**Comment by MSoegtropIMC** [comment]
Still a lot of weird stuff going on on Windows when it gets down to OCaml. E.g. if I run coqtop.byte.exe just like that it works fine. If I run it via ocamldebug it doesn't find the libraries. The weird thing is that SysInternals ProcMon shows that it scans exactly the same folders in the same order (~ 4000 file ops) with the same results until CRelationClasses.vo and then it exits when run in the debugger while it continues when run directly. If someone can think of a good exaplanation for this ...

The remote connect debugging of OCaml still doesn't work - I guess I need to make a PR for all OCaml versions we use on OCaml upstream (I fixed all this when debuggint the GTK3 issues).

Since the Gappa issue is likely not Windows specific, I will continue to debug on OSX and if this is also weird on Linux.

**Comment by SkySkimmer** [comment]
>Still a lot of weird stuff going on on Windows when it gets down to OCaml. E.g. if I run coqtop.byte.exe just like that it works fine. If I run it via ocamldebug it doesn't find the libraries. The weird thing is that SysInternals ProcMon shows that it scans exactly the same folders in the same order (~ 4000 file ops) with the same results until CRelationClasses.vo and then it exits when run in the debugger while it continues when run directly. If someone can think of a good exaplanation for this ...

What's the specific command and error?

**Comment by MSoegtropIMC** [comment]
> What's the specific command and error?

I do
```
coqtop.byte.exe
vs.
ocamldebug coqtop.byte.exe
```
with proper paths supplied and coqtop is configured with relative paths, that is
```
./configure -with-doc no -prefix ./ -libdir ./lib/coq -mandir ./man
```
When I do `Require Import Reals.` the call without ocamldebug works, the call with ocamldebug doesn't:
```
$ ocamldebug $PREFIXCOQ_W/bin/coqtop.byte.exe
        OCaml Debugger version 4.07.1

(ocd) r
Loading program... done.
Welcome to Coq 8.11+beta1 (January 2020)

Coq < Require Import Reals.
Uncaught exception: Not_found
```
 I took care to copy ocamlrun into the same location as coqtop and make it first in path, so that this is the ocamlrun ocamldebug picks up. I am not sure if this is important, but I think coqtop deduces the library path from its own executable path when compiled with relative paths and when run with ocamldebug the executable sometimes appears to be ocamlrun and not coqtop (the ProcMon traces are a bit weird in this).

As I wrote I checked with SysInternals Procmon what happens and the first ~ 4000 file operations are the same. After this the ocamldebug variant simply exits, the direct call continues to scan the lib folder and eventually loads the Real library and its dependencies.

**Comment by ejgallego** [comment]
By the way, the `Not_found` error would have been quite easy to find just by passing `-debug` and getting the corresponding backtrace [no need to use ocamldebug for that]

**Comment by MSoegtropIMC** [comment]
> 
> 
> By the way, the `Not_found` error would have been quite easy to find just by passing `-debug` and getting the corresponding backtrace [no need to use ocamldebug for that]

Yes, although for code written by someone else it helps to step through it and look at terms to understand it. Also for me it is important to test the debug infrastructure from time to time - it is important for my risk assesment.

**Comment by MSoegtropIMC** [comment]
@mattam82 : I still need some advice what to pick for equations. I will do a test build now with the latest master hash (a13f2993f93d41d0cbd3a94e0bb18f927e5913ae)

**Comment by MSoegtropIMC** [comment]
@mattam82 : the latets hash on equations master fails with Coq 8.11 - see message below.
In case you don't have a better suggestion I will use b593e3734f01c6f9c05987e4af593d2712025ae3 (which is what was in 8.11 beta) and fix the installation issues (and hope that this is the only issue).

```
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt: File "src/simplify.ml", line 319, characters 13-42:
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt: Error: This function has type
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt:          Evarsolve.unifier ->
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt:          Evarsolve.unify_flags ->
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt:          Evd.evar_map -> Evar.t -> EConstr.constr -> Evd.evar_map
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt:        It is applied to too many arguments; maybe you forgot a `;'.
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt: make[1]: *** [Makefile:621: src/simplify.cmx] Error 2
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt: make[1]: *** Waiting for unfinished jobs....
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt: File "src/subterm.ml", line 151, characters 8-29:
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt: Error: Unbound record field mind_entry_cumulative
equations-a13f2993f93d41d0cbd3a94e0bb18f927e5913ae-make_err.txt: make[1]: *** [Makefile:621: src/subterm.cmx] Error 2
```

**Comment by MSoegtropIMC** [comment]
@ppedrot : I now fixed the equations plugin by simply copying over the missing files in my platform build script. Since the build mechanism of Equations is changing in master I didn't see a good reason for fixing it properly (btw: master does not build on 8.11).
Please don't forget to review my private patch forks of @silene 's work, namely:

https://github.com/MSoegtropIMC/gappa-coq/commit/d6f5177181c35f07ff50bd5c173ee13528e06576

https://github.com/MSoegtropIMC/flocq/commit/0b4bf91963064a119bc262b6571dbc2350dd3350

https://github.com/MSoegtropIMC/coquelicot/commit/1ec80657ce992fc5aa660dca86d423671f02e33c

Btw.: for Coquelicot I didn't use your version because it included commit over the last release which are not required. In general I try to do minimal patches over the last release.

I will test the artefacts of CI and let you know - local builds look fine.

I created (locally) a collection of tests for everything I deliver which allows to do some quick tests for everything.

**Comment by ppedrot** [comment]
There are linter errors about whitespace, and you still need to register the new reals files somehow with the doc, although I don't know how to do that.

**Comment by MSoegtropIMC** [comment]
> There are linter errors about whitespace, and you still need to register the new reals files somehow with the doc, although I don't know how to do that.

Yes, I guess I can figure that out. But I first want to run it through so that I can test the resulting installer (which should not depend on this)

**Comment by ppedrot** [comment]
@MSoegtropIMC do I understand correctly that up to CI and careful review of the overlays, this is ready to merge?

**Comment by MSoegtropIMC** [comment]
> do I understand correctly that up to CI and careful review of the overlays, this is ready to merge?

Yes, but let me do some final tests this evening.

**Comment by Zimmi48** [comment]
Stdlib files are indexed in `doc/` to get in the index of the coqdoc-generated documentation. There is also a `hidden` file to list those to ignore.

**Review by ppedrot — APPROVED** [review]
Overlays look OK to me.

**Comment by ppedrot** [comment]
@MSoegtropIMC I am waiting for your green light to merge this PR.

**Comment by MSoegtropIMC** [comment]
@ppedrot : looks good to me. I did about 1 hour of final testing with the 32 bit and 64 bit version. I once had a strange effect that one of the Flocq examples which uses gappa didn't run through (flocq_Cody_Waite.v) but it appears to be an intermittent error in running gappa. I did run it 10x afterwards and it did work. Otherwise CoqIDE seems to be very stable. I was running up to 15 files in parallel and was heavily opening, running and closing files.

The only thing I really don't like is that there is still the bug that CoqIDE can't load files with a '-' in the name (for example you have to rename the gappa samples to load them) and crashes without an error. But this was there already in 8.10.2.

You could fix the Flocq issue? If not I would suggest that you create a fork of Flocq based on my branch and use that or create a PR towards my Fork.

**Comment by MSoegtropIMC** [comment]
P.S.: Did yo review my changes to Gappa, especially my decision to put the register names it needs from Reals and Flocq into these libraries? My rationale is that this is part of the interface of the libraries.

One more note: the section in the manual for Rregisternames.v looks a bit silly. Not sure if register stuff generally does not appear in the manual or if I have to put somethign extra in there. But I think we can live with this.

**Comment by ppedrot** [comment]
@MSoegtropIMC Yes, your local registering is OK, it is actually better that way I think.

File: doc/stdlib/index-list.html.template [hunk 3]
```diff
@@ -595,6 +595,7 @@ through the <tt>Require Import</tt> command.</p>
     theories/Reals/SeqSeries.v
     theories/Reals/Sqrt_reg.v
     theories/Reals/Rlogic.v
+    theories/Reals/Rregisternames.v
```
Comment (Zimmi48) [inline doc/stdlib/index-list.html.template]: If you had put this file in the hidden index, it wouldn't be listed in the doc.

**Comment by Zimmi48** [comment]
@MSoegtropIMC Please open a PR with commits eee3a48819cc66e977284e0a29b9f3df1a7b6959 and 2e1ee79b3e6b1cb5d543695a69cf1d6642eb3fd8 for master (as these were not v8.11-specific).

File: doc/stdlib/index-list.html.template (hunk 3 above)
Comment (MSoegtropIMC) [reply doc/stdlib/index-list.html.template]: Actually I want it to be listed in the doc so that it is clear that this is part of the library interface and that if people use symbols of teh reals library, in plugins they should go in here. The issue I have is that the doc is empty - it doesn't show the name registrations, just a headline.

**Comment by MSoegtropIMC** [comment]
> 
> 
> @MSoegtropIMC Please open a PR with commits [eee3a48](https://github.com/coq/coq/commit/eee3a48819cc66e977284e0a29b9f3df1a7b6959) and [2e1ee79](https://github.com/coq/coq/commit/2e1ee79b3e6b1cb5d543695a69cf1d6642eb3fd8) for master (as these were not v8.11-specific).

Done, see #11443 and #11445.

File: doc/stdlib/index-list.html.template (hunk 3 above)
Comment (Zimmi48) [reply doc/stdlib/index-list.html.template]: @MSoegtropIMC coqdoc only knows about a subset of commands. This one was considered an internal command (in fact it is only useful to plugin authors), so it was never added to coqdoc. You could open an issue to have this discussed.

Comment (MSoegtropIMC) [reply doc/stdlib/index-list.html.template]: I will do so. I consider the registered names as part of the interface of the library, because plugin authors interface to it. Knowing the names of 0 and 1 might be useful for more than one plugin. Should I meanwhile add some doc visible comment stating what is in the file?

Comment (Zimmi48) [reply doc/stdlib/index-list.html.template]: Sure!
