### PR TITLE
Fix backtracking over plugin vernac extensions

### LINKED ISSUE #12575: "Back"/"Undo" don't undo syntax extensions
If you load a plugin such as, say, Ltac2 and then backtrack in CoqIDE, the syntax extensions from the plugin are not undone.  This causes unexpected and confusing errors when you try to redo those lines.

I ran into this while experimenting with Ltac2 Notation.  Here's an example in 8.12 from @tchajed:

```
(* evaluate these two lines, then delete the first and run the second *)
From Ltac2 Require Ltac2.
Ltac2 Eval ().
(* Error: Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/. *)
``` 

If you do the `Ltac2 Eval ()` in a fresh buffer, you get `Syntax error: illegal begin of vernac.`

From @ppedrot https://github.com/coq/coq/issues/11549#issuecomment-586730067:

> vernacular extensions should be backtracked upon by plugins. I wonder why nobody ever complained about that so far.

UPDATE: Backtracking seems to work correctly for both `Notation` and `Ltac2 Notation`, so apparently _some_ things are being backtracked.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #12575

This was hand tested using
~~~coq
Require Import Ltac2.Ltac2.

Ltac2 Eval ().
~~~
we must correctly handle
- eval all, backtrack before the Require, eval just Ltac2 Eval: should
  parsing error illegal begin etc
- eval all, backtrack before the Require, eval all again: should
  work (ie the parsing rules must be re-applied)

The interesting part is what happens in vernac_extend and the
associated egramml functions:
- an indirection is added from the command name (Foo in
  `VERNAC COMMAND EXTEND Foo`) to the extension data (which contains a
  closure: not marshallable).
  This is non-backtracking, and there is no use to making it backtrack
  since we can't unlink plugins.
- vernac_extend calls `Egramml.extend_vernac_command` with `undoable:false`
  when there is no `plugin` argument, this is the old non
  backtrackable behaviour. Typically for non-plugin callers like
  g_obligations.
  Eventually we will clean up so that rules added this way produce an
  error when backtracked over instead of having the redo code in pcoq,
  until then it's also available for plugin hacks which don't mind the
  backtrack bug I guess.
- when there is a `plugin` argument, vernac_extend wraps the call to
  `Egramml.extend_vernac_command` in `Mltop.add_init_function` and
  uses `undoable:true`. In undoable mode, egramml uses the
  Pcoq.create_grammar_command system which backtracks properly.
  Because this system puts its input in the grammar_stack which ends
  up in the summary, we need the indirection mentioned above to keep
  the input marshallable.

For GRAMMAR EXTEND there is no user-given name so we produce a uid
from DECLARE PLUGIN, the file name and the number of occurences of
GRAMMAR EXTEND in the file (we end up with eg
`coq.plugins.ltac:coretactics.mlg:42`).

In the future we will probably try to replace the redo code of
ByEXTEND with an error and make the users in plugins switch to the new
mechanism.
For now it is too much work, when a plugin is modifying its own
entries it doesn't matter if backtrack is undone.

Overlays:
- https://github.com/lukaszcz/coqhammer/pull/153
- https://github.com/ejgallego/coq-serapi/pull/307

### CODE REVIEW

File: parsing/pcoq.ml [hunk 1]
```diff
@@ -98,7 +98,7 @@ module EntryDataMap = EntryCommand.Map(EntryData)
 
 type ext_kind =
   | ByGrammar of extend_rule
-  | ByEXTEND of (unit -> unit) * (unit -> unit)
+  | ByEXTEND of (unit -> unit) * (unit -> unit) option
```
Comment (SkySkimmer) [inline parsing/pcoq.ml:101]: As explained in the commit message this whole file diff is just a hack for GRAMMAR EXTEND and should be replaced by something better.

File: plugins/ltac2/g_ltac2.ml [hunk 2]
```diff
@@ -0,0 +1,3674 @@
...
+                                   Vernacextend.arg_parsing = Vernacextend.Arg_alias (_ltac2_expr);
+                                   Vernacextend.arg_printer = fun env sigma ->
+
+
+             pr_ltac2expr
+                                   ;
+                                   }
+let _ = (wit_ltac2_expr, ltac2_expr)
+
+let () = Vernacextend.vernac_extend ~plugin:__coq_plugin_name ~command:"VernacDeclareTactic2Definition"  ?entry:None
```
Comment (SkySkimmer) [inline plugins/ltac2/g_ltac2.ml:3499]: typical change, the `plugin` argument was added

File: plugins/ltac2/g_ltac2.ml [hunk 3]
```diff
@@ -0,0 +1,3674 @@
...
+              ) in fun t
+         with_end_tac ?loc ~atts () -> coqpp_body t with_end_tac
+         (Attributes.unsupported_attributes atts)), Some (fun t with_end_tac
+                                                         ->
+
+    classify_as_proofstep
+                                                         )))]
+
+let _ = let () = Mltop.add_init_function __coq_plugin_name (fun () ->
+        Pcoq.grammar_extend ~redo:false tac2mode
```
Comment (SkySkimmer) [inline plugins/ltac2/g_ltac2.ml:3618]: hack change for GRAMMAR EXTEND

File: vernac/mltop.mli [hunk 4]
```diff
@@ -73,12 +73,16 @@ val module_is_known : string -> bool
...
+(** Declare a initialization function.
     The initialization function is granted to be called after Coq is fully
-    bootstrapped, even if the plugin is statically linked with the toplevel *)
-val add_known_plugin : (unit -> unit) -> string -> unit
-
-(** Calls all initialization functions in a non-specified order *)
+    bootstrapped, even if the plugin is statically linked with the toplevel.
+    TODO consider the spec of this more carefully, pretty sure the above comment is incorrect or incomplete.
+*)
+val add_init_function : string -> (unit -> unit) -> unit
```
Comment (SkySkimmer) [inline vernac/mltop.mli:81]: We use this init function mechanism to ensure that the grammar modifications are re-applied if we backtrack and redo the Declare ML Module / Require.
We could use the declare_cache_obj stuff instead but that would be more complex and I don't think it would be more useful.

**Comment by ejgallego** [comment]
Thanks Gaëtan, testing with https://github.com/ejgallego/coq-lsp/pull/152 , but the keywords still go missing. The sequence of events is as follows (yet to be 100% confirmed):

- we get coq root state just after initialization `st_root`
- we check a buffer (RTrigo1.v for example), for that, we import prelude etc..., then freeze after `st1`
- we check normally until we finish.
- then we check another buffer (for example Pfff.v), for that, we unfreeze `st_root`, then we get `st1` for the new document in the same way. Keywords are missing.

Gonna play with `-noinit` to see how the keywords look before and after each require import.

**Comment by SkySkimmer** [comment]
This only fixes ltac2 in the current state, so it's expected that your test still fails

**Comment by SkySkimmer** [comment]
@ejgallego ready for testing

**Comment by SkySkimmer** [comment]
test suite error is due to https://github.com/coq/coq/pull/17083

The refman is failing because
~~~coq
Declare ML Module "coq-core.plugins.ssreflect".
Reset Initial.
Declare ML Module "coq-core.plugins.ssreflect".
Reset Initial.
Declare ML Module "coq-core.plugins.ssreflect".
Reset Initial.
Declare ML Module "coq-core.plugins.ssreflect".
Reset Initial.
Declare ML Module "coq-core.plugins.ssreflect".
Reset Initial.
Declare ML Module "coq-core.plugins.ssreflect".
Reset Initial.
Declare ML Module "coq-core.plugins.ssreflect".
Reset Initial.
~~~
fails.
Some debug printing says it's failing to remove a rule about hypident. IDK WTF is going on here.

**Comment by ejgallego** [comment]
> @ejgallego ready for testing

Thanks a lot! When I restore the initial state I get this:
```
"Uncaught exception Failure("Grammar.extend: No top level in entry \"tactic_value\"")."
Please report at http://coq.inria.fr/bugs/.
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Gramlib__Grammar.GMake.levels_of_rules in file "vendor/coq/gramlib/grammar.ml", line 656, characters 30-55
Called from Gramlib__Grammar.GMake.extend_entry in file "vendor/coq/gramlib/grammar.ml", line 1592, characters 15-46
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Pcoq.extend_grammar_command in file "vendor/coq/parsing/pcoq.ml", line 381, characters 11-43
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.init_ml_object in file "vendor/coq/vernac/mltop.ml", line 312, characters 6-57
Called from Mltop.trigger_ml_object in file "vendor/coq/vernac/mltop.ml", line 363, characters 22-43
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Declaremods.StagedMod.do_module in file "vendor/coq/vernac/declaremods.ml", line 375, characters 4-34
Called from Library.register_library in file "vendor/coq/vernac/library.ml", line 321, characters 2-81
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Lib.add_leaf in file "vendor/coq/library/lib.ml", line 496, characters 2-39
Called from Vernacentries.vernac_require in file "vendor/coq/vernac/vernacentries.ml", line 1518, characters 2-60
Called from Flags.with_modified_ref in file "vendor/coq/lib/flags.ml", line 17, characters 14-17
Re-raised at Exninfo.iraise in file "vendor/coq/clib/exninfo.ml", line 81, characters 4-38
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Coq__Init.doc_init in file "coq/init.ml", line 82, characters 2-36
Called from Fleche__Doc.create in file "fleche/doc.ml", line 64, characters 11-33
Called from Dune__exe__Coq_lsp.do_open in file "controller/coq_lsp.ml", line 213, characters 4-74
Called from Dune__exe__Coq_lsp.dispatch_message in file "controller/coq_lsp.ml", line 471, characters 6-39

[Trace - 14:33:08] [BT]: Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Gramlib__Grammar.GMake.levels_of_rules in file "vendor/coq/gramlib/grammar.ml", line 656, characters 30-55
Called from Gramlib__Grammar.GMake.extend_entry in file "vendor/coq/gramlib/grammar.ml", line 1592, characters 15-46
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Pcoq.extend_grammar_command in file "vendor/coq/parsing/pcoq.ml", line 381, characters 11-43
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.add_init_function.(fun) in file "vendor/coq/vernac/mltop.ml", line 289, characters 34-37
Called from Mltop.init_ml_object in file "vendor/coq/vernac/mltop.ml", line 312, characters 6-57
Called from Mltop.trigger_ml_object in file "vendor/coq/vernac/mltop.ml", line 363, characters 22-43
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Declaremods.StagedMod.do_module in file "vendor/coq/vernac/declaremods.ml", line 375, characters 4-34
Called from Library.register_library in file "vendor/coq/vernac/library.ml", line 321, characters 2-81
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Lib.add_leaf in file "vendor/coq/library/lib.ml", line 496, characters 2-39
Called from Vernacentries.vernac_require in file "vendor/coq/vernac/vernacentries.ml", line 1518, characters 2-60
Called from Flags.with_modified_ref in file "vendor/coq/lib/flags.ml", line 17, characters 14-17
Re-raised at Exninfo.iraise in file "vendor/coq/clib/exninfo.ml", line 81, characters 4-38
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Coq__Init.doc_init in file "coq/init.ml", line 82, characters 2-36
Called from Fleche__Doc.create in file "fleche/doc.ml", line 64, characters 11-33
Called from Dune__exe__Coq_lsp.do_open in file "controller/coq_lsp.ml", line 213, characters 4-74
Called from Dune__exe__Coq_lsp.dispatch_message in file "controller/coq_lsp.ml", line 471, characters 6-39
```
so it bugs out for now. That's with ef2d22d8a121807e3743131a576843af8f7e47be

I will try to review the PR later this week, and maybe help, I'm sure we are gonna find funny stuff.

**Comment by SkySkimmer** [comment]
tactic_value is probably 7e5f91fbb82d20d8c9898456634847620ac5a540 (I could reproduce in coqtop/coqc -noinit)

https://github.com/coq/coq/pull/17069#issuecomment-1374512096 seems to be an issue where the rule is added using `of` as a keyword but removed with it as an ident, and the keyword counting code goes wrong. See debug prints in e08c543911cca7d1e4effe0e3266b4d83c08b70b.
The reason for this difference is probably some kind of rule factoring as if I modify the rules by adding an extra `IDENT "baz"` to the ssr rules, the error disappears.
The keyword counting is actually useless AFAICT considering how we call rule deletion, so maybe we should just remove it (version I'm pushing).

@ejgallego is there some script I can run to test what you're testing? The CI on https://github.com/ejgallego/coq-lsp/pull/152 is green so I guess it's not in a test suite.

**Comment by ejgallego** [comment]
Thanks for the detailed analysis and push; coq-lsp PR updated. With the new version I see some progress but still the server eventually crashes with `Grammar.extend: No top level in entry \"tactic_value\`

> @ejgallego is there some script I can run to test what you're testing? The CI on [ejgallego/coq-lsp#152](https://github.com/ejgallego/coq-lsp/pull/152) is green so I guess it's not in a test suite.

Indeed I'm doing manual testing for now, waiting until we put the LSP test suite.

What I do is from a fresh checkout is:
- git submodules update --init
- make     // this takes a while unfortunately as I'm testing Reals
- dune exec -- code editor/code
- There I launch the extension from the debug panel, play button
- In the new coq-lsp instance I open the `examples` folder
- Then I open `Rtrigo1.v` wait for it to finish checking
- Then I open `Pfff.v`, the error is there.

You can see the errors in the output buffer -> coq LSP server events , logging is still a bit of PITA, but I'm going to bed, will improve both logging and handling the errors from unfreeze tomorrow.

(I didn't realize that printing goals would call `unfreeze`, so I didn't protect that from anomalies in the server, my mistake)

There are many other combinations; but I'll give priority indeed to add an automated way to do this, after all it is just a couple of `didOpen` messages to coq-lsp.

**Comment by ejgallego** [comment]
I still need to look at this but I wonder if we wouldn't finish this quicker by actually making the parsing and lexing state truly functional, after all there are very few entry points so the upper layers would be easy, only pity is `gramlib`

**Comment by SkySkimmer** [comment]
@coqbot ci minimize ci-equations

**Comment by ppedrot** [comment]
@ejgallego gramlib is highly radioactive, but apart from the unfortunate exposure of an imperative API the remaining crap is somewhare reasonably contained. Although I doubt that you'd manage to fix it quickly, I'm highly supportive of such an endeavour.

**Comment by SkySkimmer** [comment]
@ejgallego 

>dune exec -- code editor/code

any way to test without vscode?
Also do we really need the whole rtrigo and pff to trigger the bug?

**Comment by ejgallego** [comment]
> @ejgallego
> 
> > dune exec -- code editor/code
> 
> any way to test without vscode?

I am working on it, would just node be acceptable to you?

Anyways so far the trace of coq calls is not very complex, so we could hack a small ML program to do the series of freezes and unfreezes.

Code provides quite nice features for debugging tho, hopefully soon even the ability to hook into Coq itself.

> Also do we really need the whole rtrigo and pff to trigger the bug?

I bet we don't, trying to reduce that case too.

**Comment by SkySkimmer** [comment]
In pcoq we have
~~~ocaml
let unfreeze (grams, lex) =
  let (undo, redo, common) = factorize_grams !grammar_stack grams in
  let n = number_of_entries 0 undo in
  remove_grammars n;
  grammar_stack := common;
  CLexer.set_keyword_state lex;
  List.iter extend_dyn_grammar (List.rev redo)
~~~
I'm not sure about the implications of doing the lexer before the redo. Does anyone know if something would change if we switch?

**Comment by SkySkimmer** [comment]
In Grammar.logically_eq_symbols entries are compared with `e1.ename = e2.ename` but there is no guarantee that entries have unique names, this is probably buggy

**Comment by ejgallego** [comment]
Test that shows the problem in master:
```coq
(* run with coqc -noinit *)
From Coq Require Import Prelude.
Print Keywords.
Reset Initial.
From Coq Require Import Prelude.
Print Keywords.
```
Testing with with this PR, things work fine!

File: vernac/mltop.mli (hunk 4 above)
Comment (ejgallego) [reply vernac/mltop.mli:86]: At some point the init functions should take a pointer to the parsing state I understand, right?

Comment (SkySkimmer) [reply vernac/mltop.mli:86]: It's possible that we will do that but not in my short term plans

**Comment by ejgallego** [comment]
Ok doing some more complex testing I've hit this:
```
Anomaly
"File "vendor/coq/gramlib/grammar.ml", line 1600, characters 82-88: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
Raised at Gramlib__Grammar.GMake.modify_entry in file "vendor/coq/gramlib/grammar.ml", line 1600, characters 82-94
Called from Pcoq.grammar_delete.(fun) in file "vendor/coq/parsing/pcoq.ml", line 153, characters 38-68
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Pcoq.remove_grammars in file "vendor/coq/parsing/pcoq.ml", line 211, characters 14-34
Called from Pcoq.unfreeze in file "vendor/coq/parsing/pcoq.ml", line 521, characters 2-19
Called from Vernacstate.Parser.parse in file "vendor/coq/vernac/vernacstate.ml", line 20, characters 4-20
Called from Coq__Parsing.parse in file "coq/parsing.ml", line 9, characters 2-58
Called from Coq__Protect.eval_exn in file "coq/protect.ml", line 35, characters 14-17
```

**Comment by SkySkimmer** [comment]
Please give reproduction method

**Comment by ejgallego** [comment]
> Please give reproduction method

Working on a more minimal test case, basically evaluating a file to a point, then `unfreeze`ing the state for another point of another file.

**Comment by ejgallego** [comment]
Ok, here is the simplest I could come https://github.com/coq/coq/pull/16190/files#diff-8be3e4f70c1afb9436669e3d46106556685442685a93bd1492b6ccc496b9afa9

You can also run it with `dune exec -- dev/shim/coqc hack` in that branch (which includes this one).

Unfortunately I couldn't manage to get this sequence with `Reset Initial`, the sequence basically is:
```ocaml
let root_st = freeze () in
let st1 = init_document doc1    (* load requires, etc... *)
let () = unfreeze root_st in   (* restore original state *)
let st2 = init_document doc2  (* init another doc *)
let () = unfreeze st1 (* boom! *) in
```

**Comment by SkySkimmer** [comment]
So when it does the failing unfreeze, it sees the common grammar_stack as being just the tactic_value Fresh from tacentries https://github.com/SkySkimmer/coq/blob/fed5366d214e16076fabfd75097c446450bcb673/plugins/ltac/tacentries.ml#L429-L430

It doesn't see more common points because the next element is a vernacextend, elements are compared with physical equality and vernacextend builds the id at every run of the init function https://github.com/SkySkimmer/coq/blob/fed5366d214e16076fabfd75097c446450bcb673/vernac/vernacextend.ml#L368-L369
Indeed changing that to `let ci = (command, i) in add_init_function ...` makes the example pass, but that may be considered a hack and not a true fix.

Another way to avoid the error is to not initialize tactic_value with trivial rules, for instance delete the call in tacentries and remove the TOP annotation in g_ltac. If we do it this way we need to order extraargs to happen after g_ltac as the create_generic_notation at its beginning extend tactic_value (doing the initialization is not in scope for create_generic_notation)

Finally we could try to make it so deleting all rules in an entry does not forget how it was initialized if the initialization was trivial. I don't know how to do that though.

I'm going to push the delete the call in tacentries option, try testing again and see if there are any other errors.

**Comment by ejgallego** [comment]
> I'm going to push the delete the call in tacentries option, try testing again and see if there are any other errors.

Thanks, the explanation is much appreciated, I will test tomorrow.

I will also try to have a deeper look to the PR, I'm curious to see how feasible is to get rid of `freeze / unfreeze` altogether.

**Comment by ejgallego** [comment]
Testing has gone pretty well so far; I will review and propose to merge soon, if anyone wants to have a look too.

**Comment by gares** [comment]
@SkySkimmer can you explain what the issue with Elpi is? Can I fix it on my side?

**Comment by herbelin** [comment]
BTW, what about having a specialized one-day workshop/working-group one of these days on parsing and notations, to share knowledge, synchronize objectives, collect solutions?

**Comment by SkySkimmer** [comment]
In https://github.com/LPCIC/coq-elpi/blob/fe6ddcbec9a32d591df9adb44485e4a5d5553e11/src/coq_elpi_vernacular.ml#L848-L886
every time the object gets imported we run vernac_extend with the same `command` string
for instance in https://github.com/LPCIC/coq-elpi/blob/fe6ddcbec9a32d591df9adb44485e4a5d5553e11/apps/derive/theories/derive/idx2inv.v#L12-L13 `derive` is explicitly imported (Export technically) and is also exported in `derive.invert` so the `Elpi Command derive` object runs the vernac_extend twice
this causes the check at https://github.com/SkySkimmer/coq/blob/050e446ac666999707106ecc1db060d33abbd9a2/vernac/egramml.ml#L85 to fail

That check isn't really necessary, it's just that I programmed thinking that vernac extends are require time and so repeating the extend is likely to be a programmer mistake (ie reusing the string for different command, which leads to bugs). So the solution was to disable it some of the time. TBH now that it's been run on my coqpp changes we could just remove it completely.

NB at the point of the check we can't compare the values to avoid an error when they're equal, because they contain closures only equal up to funext. Also if the user backtracks over the Elpi Command we can get actually different commands anyway.

**Comment by SkySkimmer** [comment]
@coqbot bench

File: plugins/ltac/g_obligations.mlg [hunk 5]
```diff
@@ -12,6 +12,8 @@
   Syntax for the subtac terms and types.
   Elaborated from correctness/psyntax.ml4 by Jean-Christophe Filliâtre *)
 
+DECLARE PLUGIN "coq-core.plugins.ltac"
```
Comment (ejgallego) [inline plugins/ltac/g_obligations.mlg:15]: Just a thought, but maybe we'd like to have `DECLARE PLUGIN "foo"` and `EXTENDS PLUGIN GRAMMAR "foo"` to be different things?

I say this because it seems to me that a plugin should call only once the `add_known_module` API in `Mltop`.

Comment (SkySkimmer) [reply plugins/ltac/g_obligations.mlg:15]: Doesn't really seem like a useful distinction to me.

**Comment by ejgallego** [comment]
@coqbot run full CI

**Review by ejgallego — APPROVED** [review]
LGTM, thanks!

Still some todos, but we will get to them.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by Alizter** [comment]
@ejgallego Can you document the todos here so we don't forget?

**Comment by ejgallego** [comment]
The TODOS are explained in the PR description.

**Comment by SkySkimmer** [comment]
Also having a better API for import time vernacextends that may be modified after backtracking as elpi has.

**Comment by LasseBlaauwbroek** [comment]
I'm trying to update my plugin to this change. In particular, I use `add_known_plugin` to initialize some data in my plugin:
```
let () = Mltop.add_init_function __coq_plugin_name f
```
What is the recommended alternative for this, now that this function is removed?

**Comment by LasseBlaauwbroek** [comment]
Okay, I'm now doing
```
let () = Mltop.add_init_function "coq-tactician.tactics-plugin" f
```
Is that the intended method?

**Comment by ejgallego** [comment]
You can use `Mltop.add_init_function` , but beware of the semantics (it will run each time the document manager decides to execute `Declare ML Module` which can happen many times per session).

**Comment by LasseBlaauwbroek** [comment]
Thanks, that'll work for me.
