### PR TITLE
Remove ad-hoc treatment of inductive parameters in implicit arguments

### LINKED ISSUE #7253: Standardize handling of implicit arguments of inductive types in constructors
#### Version
Coq 8.8+beta1

#### Description of the problem

Implicit parameters of inductive types get by default the parameter value in their definition, rather than being inferred. This leads to behavior like the below:

```coq
Fail Inductive foo {A : Set} (a : A) : Set :=
  sup : foo 3 -> foo a
.
(*
In environment
foo : forall A : Set, A -> Set
A : Set
a : A
The term "3" has type "nat"
while it is expected to have type 
"A".
*)

Inductive foo {A : Set} (a : A) : Set :=
  sup : foo (A:=nat) 3 -> foo a
.
(* succeeds *)
```

I think this is rather unintuitive. On the other hand, it allows to write things like
```
Inductive bar {A : Set} : Set
  := sup_bar : A -> bar -> bar.
```
without having to specify the parameter of bar in either the parameters or the conclusion of `sup_bar`.

In the conclusion, the we are restricted to `bar (A := A)`, but in the parameters, we can take `bar (A := B)`, turning `A` into a non-uniform parameter.

This is also the root cause of some of the problems in https://github.com/coq/coq/issues/6786

This behavior is caused by https://github.com/coq/coq/blob/15331729aaab16678c2f7e29dd391f72df53d76e/interp/constrintern.ml#L59-L61

My inclination is to remove this behavior, reducing the code complexity and standardizing how implicit arguments work. I don't know how often it is used in practice, so looking at the CI should be informative.

### LINKED ISSUE #8790: -mangle-names fails on inductive definition
#### Version

8.9.dev (but this was already broken with 8.8)

#### Operating system
Linux

#### Description of the problem

Consider this example file:
```coq
From Coq Require Import List.
Export ListNotations.

Inductive TCForall {A} (P : A -> Prop) : list A -> Prop :=
  | TCForall_nil : TCForall P []
  | TCForall_cons x xs : P x -> TCForall P xs -> TCForall P (x :: xs).
```
And compile it using `coqc -mangle-names mangled_ test.v`. I'd expect that to work, because the file does not refer to any auto-generated names.

Unfortunately, it fails:
```
File "/home/r/Desktop/test.v", line 5, characters 19-27:
Error: The reference mangled_0 was not found in the current environment.
```

This is really sad, because I was so happy when I saw this feature and wanted to use it on CI for all our projects immediately :(

I should also note that I thought I had reported this already half a year ago, but cannot find that original report any more...

### LINKED ISSUE #11585: Stack overflow with inductive having an implicit argument with the same name.
#### Description of the problem

Just try and check the following inductive.
```coq
Inductive type {type : Type} : Type := T : type.
```
**Note**: the fact that the `type` argument is implicit is important.

#### Coq Version

```
The Coq Proof Assistant, version 8.10.2 (February 2020)
compiled on Feb 5 2020 15:10:48 with OCaml 4.07.1
```
@Janno checked with Coq master and the problem is still there.

### PR DESCRIPTION
**Pull request by maximedenes**
This is another attempt at #7254. The code is mainly from @jashug.

I fixed the problem mentioned in that PR, let's see what the current status of CI is (I haven't included the overlays yet).

Fixes #7253.
Fixes #8790.
Fixes #11585.

### CODE REVIEW

File: vernac/comInductive.ml [hunk 1]
```diff
@@ -428,6 +439,30 @@ let interp_params env udecl uparamsl paramsl =
...
+      Array.fold_left_i (fun i sigma arg ->
+          if i >= nparams || not (EConstr.isEvar sigma arg) then sigma
+          else Evarconv.unify_delay env sigma arg (EConstr.mkRel (k+nparams-i)))
+        sigma args
+    | _ -> Termops.fold_constr_with_full_binders
+             sigma
+             (fun d (env,k) -> EConstr.push_rel d env, k+1)
+             aux envk sigma c
+  in
+  aux (env_ar_par,0) sigma c
```
Comment (SkySkimmer) [inline vernac/comInductive.ml]: I had an idea to restore the useful behaviour of the previous heuristic, which I pushed as a separate commit. The main part of it is this function. Whenever we encounter the inductive applied to evars, we unify those evars with the parameters as though they were uniform.
This allows to define 
~~~coq
Inductive Tree {A} : Type :=
   Tempty : Tree
 | Branch0 : Tree -> Tree -> Tree
 | Branch1 : A -> Tree -> Tree -> Tree.
~~~
and the like without using the Uniform Parameters option.

Comment (maximedenes) [reply vernac/comInductive.ml]: I spent the afternoon doing the same thing...

File: vernac/comInductive.ml [hunk 2]
```diff
@@ -145,16 +126,78 @@ let pretype_ind_arity env sigma (loc, c, impls, pseudo_poly) =
...
+    strbrk"this declaration relies on a deprecated fragile heuristic. Please specify the " ++
+    strbrk"value of the argument or declare the inductive type as uniform using the " ++
+    strbrk"#[uniform] attribute."))
+
+let solve_uniform_inductive_params env evd indnames nparams =
+  let indnames = List.map (fun x -> GlobRef.VarRef x) indnames in
+  let has_resolved = ref false in
+  let evd = Evd.fold_undefined (fun evk ev_info evd' ->
+    match ev_info.Evd.evar_source with
+    | loc,Evar_kinds.ImplicitArg(r,(k,na),force) when List.mem_f GlobRef.equal r indnames ->
```
Comment (SkySkimmer) [inline vernac/comInductive.ml]: Using the evar source seems more complicated than what I did, also IIUC it won't handle using explicit holes, eg
~~~
Inductive foo A := C : (_ : foo _).
~~~
I propose we go with my commit (https://github.com/coq/coq/commit/876b6f206748a3e4bcb26ee7b915b76653d9623e) instead, and don't deprecate as it doesn't seem especially fragile.

Comment (maximedenes) [reply vernac/comInductive.ml]: Looking at the evar source makes sense only if the goal is to detect situations where the previous heuristic applied, which is what I did, to emit a warning only in these cases.

I think I prefer to deprecate it, as the cost/benefit ratio seems very low. The code for this inferrence is not simple, and the idea seem really ad-hoc (why would Coq make random bets at what the parameters value could be?).

But I guess I could be convinced by a real-world example where the hack is useful (i.e. where specifying uniform or the arguments is too painful). Do you have one?

Comment (SkySkimmer) [reply vernac/comInductive.ml]: Uniform doesn't work if you have some non uniform parameters
Also IMO the cost is pretty low

Comment (maximedenes) [reply vernac/comInductive.ml]: @What does your code do on `C : id foo _ -> foo`? Does it also try to fill up the hole?

Comment (SkySkimmer) [reply vernac/comInductive.ml]: Yes

Comment (SkySkimmer) [reply vernac/comInductive.ml]: No wait I didn't see te `id`, so no

Comment (maximedenes) [reply vernac/comInductive.ml]: Where is reduction performed?

Comment (maximedenes) [reply vernac/comInductive.ml]: So this is fragile. If you want to be robust, you'd have to share the code analyzing parameters in `indtypes.ml` (i.e. what positivity accepts). Not worth it, IMHO.

Comment (SkySkimmer) [reply vernac/comInductive.ml]: I don't understand the meaning of fragile here.

Comment (maximedenes) [reply vernac/comInductive.ml]: Take a definition where your heuristic applies. Modify it slighlty (add an `id`, a cast, a beta redex) and suddenly the behavior of inferrence changes. That's what I call fragile.

Comment (gares) [reply vernac/comInductive.ml]: Ha ha ha, we had the same discussion yesterday.
FTR, I gave up trying to convince @maximedenes that the approach it is not fragile... :-)

Comment (SkySkimmer) [reply vernac/comInductive.ml]: Isn't the point of changing a definition to something convertible that it changes inference?

Comment (maximedenes) [reply vernac/comInductive.ml]: I think we tend to introduce way too often some features that work "often". This is part of what makes Coq hard to use sometimes.

If we really want the heuristic, let's go ahead and do the same analysis as `indtypes.ml` (i.e. with reduction).

File: interp/constrintern.ml [hunk 3]
```diff
@@ -430,12 +416,12 @@ let locate_if_hole ?loc na c = match DAst.get c with
...
+         | (Inductive (params,_),b,c) -> (Inductive (params,false),b,c)
          | x -> x) env.impls }
 
 let check_hidden_implicit_parameters ?loc id impls =
   if Id.Map.exists (fun _ -> function
-    | (Inductive (indparams,check),_,_,_) when check -> Id.List.mem id indparams
+    | (Inductive (indparams,check),_,_) when check -> Id.List.mem id indparams
     | _ -> false) impls
   then
     user_err ?loc (Id.print id ++ strbrk " is already used as name of " ++
```
Comment (SkySkimmer) [inline interp/constrintern.ml]: This error is for instance triggered by 
~~~coq
Inductive foo {A:Prop} := C : forall A : Prop, foo.
~~~
which previously could not work because of the name manipulation removed by this PR.
Now it does work (assuming we remove the error). 
Removing the error then allows removing the arguments to `Inductive`.

Does that seem like something we should do? cc @herbelin

Comment (SkySkimmer) [reply interp/constrintern.ml]: I'm pushing a commit doing it, we can always drop it if we don't want it.

Comment (herbelin) [reply interp/constrintern.ml]: What gives `Inductive foo {A:Prop} := C : forall A : Prop, foo.` with the PR? Is `A` renamed or is a failure telling that the name are not distinct?

In any case, if you have a way to avoid the "arguments to `Inductive`" hack, that's good.

Comment (SkySkimmer) [reply interp/constrintern.ml]: The second A is renamed to A0 AFAICT, ie
~~~coq
Inductive foo (A:Prop) := C : forall A : Prop, A -> foo _.
Print foo.
(* Inductive foo (A : Prop) : Type :=  C : forall A0 : Prop, A0 -> foo A *)
~~~

Comment (herbelin) [reply interp/constrintern.ml]: > The second A is renamed to A0 AFAICT, ie

I think, it is ok for this PR. In the plan I have around implicit arguments, there would be anyway a check that the names are distinct in the toplevel block of parameters.

**Comment by SkySkimmer** [comment]
Analysis of failures:
- output test changed (trivial)
- heuristic of pretending to have uniform params not implemented for record syntax (return of #5233)
- compcert: basically reduces to 
~~~coq
Class C := {}.

Inductive foo {a b : C} := CC : foo.
~~~
typeclass search gets run before unification and so resolves a parameter in the conclusion to the wrong instance.

I'll look into fixing these (and add a test for the compcert one).

**Comment by SkySkimmer** [comment]
Should work, let's see what CI says.

File: vernac/record.ml [hunk 4]
```diff
@@ -59,26 +59,37 @@ let () =
...
+           | None -> LocalAssum (make_annot i r,t')
+           | Some b' -> LocalDef (make_annot i r,b',t')
+         in
+         List.iter (Metasyntax.set_notation_for_interpretation env impls) no;
+         (EConstr.push_rel d env, sigma, impl :: uimpls, d::params, impls))
+      (env, sigma, [], [], impls_env) nots l
+  in
+  let _, sigma = Context.Rel.fold_outside ~init:(env,sigma) (fun f (env,sigma) ->
+      let sigma = RelDecl.fold_constr (fun c sigma ->
+          ComInductive.maybe_unify_params_in env sigma ~ninds ~nparams c)
```
Comment (SkySkimmer) [inline vernac/record.ml]: Adding this (+ exposing the function from cominductive) solves the record issue.

File: vernac/comInductive.ml [hunk 5]
```diff
@@ -145,16 +126,50 @@ let pretype_ind_arity env sigma (loc, c, impls, pseudo_poly) =
...
   let cnames,ctyps = List.split ind.ind_lc in
-  (* Complete conclusions of constructor types if given in ML-style syntax *)
-  let ctyps' = List.map2 (complete_conclusion mldata) cnames ctyps in
+  let arity_indices, cstr_sort = Reductionops.splay_arity env sigma arity in
   (* Interpret the constructor types *)
-  let sigma, (ctyps'', cimpls) =
+  let interp_cstr sigma ctyp =
+    let flags =
+      Pretyping.{ all_no_fail_flags with
+                  use_typeclasses = false;
```
Comment (SkySkimmer) [inline vernac/comInductive.ml]: This solves the compcert issue. Typeclasses are still resolved at the end of the typechecking for the mutual block. Waiting until then may change which error is shown when a declaration has multiple issues but should otherwise be fine.

**Comment by SkySkimmer** [comment]
Looks like https://github.com/uwplse/verdi/blob/fdb4ede19d2150c254f0ebcfbed4fb9547a734b0/core/LabeledNet.v#L237 is broken now, not sure about the details.

**Comment by SkySkimmer** [comment]
Reduced version 
~~~coq
Class Bla := { bla : Type }.

Instance bli : Bla := { bla := nat }.

Inductive vs := C : forall x : bla, x = 2 -> vs.
~~~

**Comment by gares** [comment]
I'm a bit lost, in the example there are no parameters.

**Comment by SkySkimmer** [comment]
Looks like it works now, VST failure is spurious.

**Comment by SkySkimmer** [comment]
@maximedenes  What should we do for documentation?

**Comment by maximedenes** [comment]
> What should we do for documentation?

Maybe nothing, now that we expect to preserve user behavior. I put the label on a previous version of this PR, which was introducing a new warning.

**Comment by maximedenes** [comment]
I believe this is ready, who could assign? @mattam82 or @herbelin maybe?

**Comment by maximedenes** [comment]
This has been waiting for a while, and now needs a rebase.

Can we get an assignee? @ppedrot @mattam82 @herbelin ?

**Comment by ppedrot** [comment]
Not sure I am qualified, if nobody reacts soon I might assign though.

**Comment by herbelin** [comment]
Ok, let me assign. It needs an approval too (I can do a review at some time but ping me if it does not come in the next few days.)

**Review by herbelin — APPROVED** [review]
This looks very good, with a rather intuitive heuristic. Well done.

Couldn't a few tests be added at the same time, like the `Tree {A}`, `foo`, `vs` and `TCForall` examples of @skyskimmer, the `expr` example of @JasonGross, the `exp_match` example of @jashug?

**Comment by SkySkimmer** [comment]
Newest commit includes suggestions

**Comment by herbelin** [comment]
> Newest commit includes suggestions

Thanks!

For the other possible examples, is the conclusion that they are not worth (or maybe wrong)?

**Comment by SkySkimmer** [comment]
Added test
~~~coq
Class Bla := { bla : Type }.

Instance bli : Bla := { bla := nat }.

Inductive vs := C : forall x : bla, x = 2 -> vs.
~~~
I think that's enough to have good coverage

**Comment by herbelin** [comment]
> I think that's enough to have good coverage

Ok. Thanks.

On my side, I'm ready for a merge, say on tomorrow afternoon. Last call for possible remarks then.

**Comment by herbelin** [comment]
Unfortunately, there is a new conflict and a rebase is needed.
