### PR TITLE
Ensure that a custom entry cannot be defined twice.

### LINKED ISSUE #11313: Strange Behaviour with Custom Entries and Import/Export
#### Description of the problem

There seems to be bad interaction with custom entries and importing/exporting modules that define such entries.

In the following code, the custom entry `test` ends up being empty.
```coq
Module G.
  Declare Custom Entry test.
  Notation "'some_keyword'" := (1) (in custom test at level 0).
End G.
Import G.
Print Custom Grammar test. (* one rules *)
Import G.
Print Custom Grammar test. (* zero rules *)
```

Additionally, undoing the second `Import G` deletes the custom entry entirely. (I.e., `Print Custom Entry test` fails.)

The second `Import G` can be replaced by `Export G`, yielding the same behaviour.

#### Coq Version

master with a bunch of PRs already merged in because I like to live dangerously. With a bit of extra notation one can reproduce this in the 8.11 branch. Define
```coq
Notation "'[test' t ]" := (t) (at level 0, t custom test at level 0).
```
and substitute `Print Custom Grammar test` by `Check [test some_keyword ]`.

### PR DESCRIPTION
**Pull request by ppedrot**
This highlights the fact that diamond inheritance of a custom entry is a tricky problem, as well as merely importing two custom entries with the same name from two different modules. The only sane way to give a semantics to that is to stick to module-scoped objects, i.e. give those entries a kernel name. In the meantime, I went for a warning when overriding entries.

I will submit another PR with a kernel-name based custom entry system soon, but this is an easily backportable hotfix.

Fixes #11313.

### CODE REVIEW

File: vernac/metasyntax.ml [hunk 1]
```diff
@@ -1654,10 +1654,16 @@ let add_syntactic_definition ~local deprecation env ident (vars,c) { onlyparsing
...
+let warn_custom_entry =
+  CWarnings.create ~name:"custom-entry-overriden" ~category:"parsing"
+         (fun s ->
+          strbrk "Custom entry " ++ str s ++ strbrk " has been overriden.")
+
 let load_custom_entry _ _ = ()
 
 let open_custom_entry _ (_,(local,s)) =
-  Egramcoq.create_custom_entry ~local s
+  if Egramcoq.exists_custom_entry s then warn_custom_entry s
```
Comment (maximedenes) [inline vernac/metasyntax.ml]: Isn't the warning bogus? For example, if you do `Import M. Import M.` where `M` contains a custom entry declaration, it will be triggered, but should not.

Comment (ppedrot) [reply vernac/metasyntax.ml]: Yes, but I think we have the same problem with notations, up to a sordid heuristic that tries to recognize that two notations are the same. The proper fix is to use kernames, which I am implementing.

Comment (ppedrot) [reply vernac/metasyntax.ml]: (Also, try pondering for one minute what happens if you have custom entries in functors / diamond inheritance via `Export` to realize that there is no way to get a sound and complete warning in the current implementation.)

Comment (maximedenes) [reply vernac/metasyntax.ml]: > (Also, try pondering for one minute what happens if you have custom entries in functors / diamond inheritance via `Export` to realize that there is no way to get a sound and complete warning in the current implementation.)

Oh sure, I'm aware of it, we had the same problem for notations indeed.

**Review by maximedenes — APPROVED** [review]
Looks good to me as a hotfix. It would be nice to add a test case that imports a custom grammar twice and check that it is not emptied (see the original bug report).

**Review by herbelin — APPROVED** [review]
OK to me.

>  I will submit another PR with a kernel-name based custom entry system soon, but this is an easily backportable hotfix.

> Yes, but I think we have the same problem with notations, up to a sordid heuristic that tries to recognize that two notations are the same. The proper fix is to use kernames, which I am implementing.

:+1: 

In passing, do you intend to have a nametab-like support for scopes (see [#11105](https://github.com/coq/coq/pull/11105#issuecomment-553968806))?

In passing, notice #10832. To save a few conflicts, it may be worth to merge it before adding a kernel name to notations.

**Comment by ppedrot** [comment]
@herbelin I'll wait a bit to implement the kername feature. It shouldn't go in 8.11, so it's not urgent and your PR can indeed go first to prevent rebase hassle.

**Comment by ppedrot** [comment]
Who is assigning?

**Comment by herbelin** [comment]
> Who is assigning?

Let me do it then (shall merge on Wednesday). About #10832, do you want to assign?

**Comment by ppedrot** [comment]
@herbelin ping. Regarding assigning your PR, I don't think I understand enough the invariants of the notation mechanism to review it effectively, but if really nobody reacts (which seems to be the case) I will indeed assign it to myself.

**Comment by herbelin** [comment]
Sorry, now merging (I see bedrock's failure in other PRs too so I assume it is unrelated).
