### PR TITLE
Reimplement Admit Obligations using standard Admitted code

### LINKED ISSUE #13109: Admit Obligations gives "Error: Anomaly "Uncaught exception AcyclicGraph.Make(Point).AlreadyDeclared."" on universe-polymorphic program definition
#### Description of the problem

```coq
Require Import Coq.Program.Basics.
Require Import Coq.Program.Tactics.
Set Universe Polymorphism.
Obligation Tactic := idtac.
Program Definition foo : Type := _.
Admit Obligations.
(* Error: Anomaly "Uncaught exception AcyclicGraph.Make(Point).AlreadyDeclared."
Please report at http://coq.inria.fr/bugs/.
 *)
```

#### Coq Version

master (cdfe69d6da6b32338ba74c9f599c74389089c9dd)

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13109

### CODE REVIEW

File: vernac/declare.ml [hunk 1]
```diff
@@ -2464,40 +2463,33 @@ let add_mutual_definitions l ~pm ~info ?obl_hook ~uctx
...
-
-(* get_any_prog *)
+let rec admit_prog ~pm prg =
+  let {obls} = Internal.get_obligations prg in
+  let is_open _ x = Option.is_empty x.obl_body && List.is_empty (deps_remaining obls x.obl_deps) in
+  let i = match Array.findi is_open obls with
+    | Some i -> i
+    | None -> CErrors.anomaly (Pp.str "Could not find a solvable obligation.")
+  in
+  let proof = solve_obligation prg i None in
```
Comment (SkySkimmer) [inline vernac/declare.ml:2473]: This could maybe be factored with next_obligation a bit.

**Review by ejgallego — APPROVED** [review]
Thank you for this cleanup.

@coqbot: merge now

File: vernac/declare.ml (hunk 1 above)
Comment (JasonGross) [reply vernac/declare.ml:2473]: Does this mean that if the obligation tactic is `fail`, then admitting the obligations will fail?  Is this expected/desired?  (Is it a regression?) Is it documented?  Is it tested?
