### PR TITLE
Fix #7348: extraction of dependent record projections

### LINKED ISSUE #7348: Extraction with dependent records produces `assert false`
#### Version

8.8.0

#### Operating system

Ubuntu

#### Description of the problem

Consider the following snippet:

```
From Coq Require Import Extraction.

Extraction Language OCaml.

Record rec := Rec {sort :> Type; op : sort -> bool}.

Definition foo (x : unit) := unit.

Record bar x := {
  f1 : foo x;
  f2 : foo x
}.

Definition wrong x (b : bar x) : bool := op (Rec unit (fun _ => true)) (f1 x b).

Extraction "test.ml" wrong.
```

On my machine, this leads to the following extracted file:

```

type __ = Obj.t

type unit0 =
| Tt

type bool =
| True
| False

type rec0 = __ -> bool
  (* singleton inductive, whose constructor was Rec *)

type sort = __

(** val op : rec0 -> sort -> bool **)

let op r =
  r

type foo = unit0

type bar = { f1 : foo; f2 : foo }

(** val f1 : unit0 -> bar -> foo **)

let f1 _ x = x.f1

(** val wrong : unit0 -> bar -> bool **)

let wrong _ b =
  op (fun _ -> True) (Obj.magic f1 (assert false (* Proj Args *)) b)
```

The extractor included an `assert false` that causes the program to crash when calling `wrong`. Oddly, the issue disappears if I remove the `f2` field from the record `bar`.

### PR DESCRIPTION
**Pull request by pi8027**
The OCaml extraction produces improper assertions `assert false (* Proj Args *)` for record projections involving `MLmagic` (`Obj.magic`) which are introduced here:
https://github.com/coq/coq/blob/c70412ec8b0bb34b7a5607c07d34607a147d834c/plugins/extraction/extraction.ml#L751-L762
As one can see in this comment, this kind of assertions should be removed during final pretty-printing and should not appear in the output. Currently, pretty-printing for record projections is implemented at the following three places: https://github.com/coq/coq/blob/9b7b34702f1134841f7f9408db27074b5479e07d/plugins/extraction/ocaml.ml#L579-L589 https://github.com/coq/coq/blob/9b7b34702f1134841f7f9408db27074b5479e07d/plugins/extraction/ocaml.ml#L317 https://github.com/coq/coq/blob/9b7b34702f1134841f7f9408db27074b5479e07d/plugins/extraction/ocaml.ml#L232-L236

The first one is pretty-printing for the definitions of record projections. The second one, `pp_record_proj` is pretty-printing for *inlined* record projections. The third one is pretty-printing for *non-inlined* record projections, which must erase those assertions; however, it doesn't erase. I think this issue was introduced by the following change which moves `MLmagic` around `MLapp`: https://github.com/coq/coq/commit/0c60735279301d22ac3e03f862f86997cb85bce0#diff-c99051d2f4403f00050d67d4ce4b9781R1039.

I have fixed this issue by
- inlining record projections by default (except Haskell extraction), and
- extending `pp_record_proj` for record projections involving `MLmagic`.

The special pretty-printing treatments for record projections other than `pp_record_proj` are eliminated and reduced to the above fixes. `micromega.ml` had to be changed due to this change of the extraction plugin.

CC: @maximedenes 

**Kind:** bug fix.

Fixes / closes #7348

- [x] Added / updated test-suite

### CODE REVIEW

File: plugins/extraction/mlutil.ml [hunk 1]
```diff
@@ -1547,6 +1547,7 @@ let inline r t =
   not (to_keep r) (* The user DOES want to keep it *)
   && not (is_inline_custom r)
   && (to_inline r (* The user DOES want to inline it *)
-     || (lang () != Haskell && not (is_projection r) &&
-         (is_recursor r || manual_inline r || inline_test r t)))
+     || (lang () != Haskell &&
```
Comment (pi8027) [inline plugins/extraction/mlutil.ml]: I don't understand why we don't inline recursors in Haskell extraction.

**Comment by pi8027** [comment]
I found a related issue: If a record type is recognized as a singleton type by the extractor, its projections are not recognized as projections; thus, they are not inlined.
https://github.com/coq/coq/blob/master/plugins/extraction/extraction.ml#L492-L494
https://github.com/coq/coq/blob/master/plugins/extraction/extraction.ml#L526-L535

**Comment by pi8027** [comment]
@maximedenes Hello. Do we have tables for recursors and record projections in `ind_tables.ml` and `recordops.ml` or somewhere else? If we have, other plugins can use that information, and the extractor can be simplified. Currently, the extractor implements them by itself. (I guess we can use `is_projection` here.) https://github.com/coq/coq/blob/9b7b34702f1134841f7f9408db27074b5479e07d/plugins/extraction/table.ml#L181 https://github.com/coq/coq/blob/9b7b34702f1134841f7f9408db27074b5479e07d/pretyping/recordops.mli#L54

File: plugins/extraction/mlutil.ml (hunk 1 above)
Comment (pi8027) [reply plugins/extraction/mlutil.ml]: > Concerning Haskell, type-preserving optimizations are less useful because of laziness. We still make some optimizations, for example in order to produce more readable code.

**Review by maximedenes — APPROVED** [review]
LGTM, you could maybe use a combinator to inspect mini ML terms without taking `MLmagic` into account. Also, since this patch sometimes changes behavior (more inlining), it would be good to have a changelog entry.

File: doc/changelog/08-tools/10577-extraction-dependent-projections.rst [hunk 2]
```diff
@@ -0,0 +1,8 @@
+- Fix a printing bug of OCaml extraction on dependent record projections, which
+  produced improper `assert false`. This change makes the OCaml extractor
+  internally inlines record projections by default and may not produce record
```
Comment (Zimmi48) [inline doc/changelog/08-tools/10577-extraction-dependent-projections.rst]: I think the correct grammar would be:

```suggestion
  internally inline record projections by default and may not produce record
```

File: doc/changelog/08-tools/10577-extraction-dependent-projections.rst [hunk 3]
```diff
@@ -0,0 +1,8 @@
...
+  projection constants anymore. If you want to extract record projection
+  constants, you may need to instruct it explicitly to the extractor
```
Comment (Zimmi48) [inline doc/changelog/08-tools/10577-extraction-dependent-projections.rst]: I am not sure how obvious this is to people who are used to extraction, but if it is not you might want to say using which command.

**Review by Zimmi48 — APPROVED** [review]

File: doc/changelog/08-tools/10577-extraction-dependent-projections.rst (hunk 3 above)
Comment (pi8027) [reply doc/changelog/08-tools/10577-extraction-dependent-projections.rst]: Thank you for suggestions. I have indicated that the change of behavior is specific to the monolithic OCaml extraction (`Extraction "file"` and `Recursive Extraction`).

File: doc/changelog/08-tools/10577-extraction-dependent-projections.rst (hunk 2 above)
Comment (pi8027) [reply doc/changelog/08-tools/10577-extraction-dependent-projections.rst]: @Zimmi48 Sorry, I didn't reply on this but actually I fixed this too. Could you confirm it?

Comment (Zimmi48) [reply doc/changelog/08-tools/10577-extraction-dependent-projections.rst]: @pi8027 Sure, I didn't really intend to go back to this PR and check. I believe the assignee should be @maximedenes here anyway.
