### PR TITLE
Remove O(n*n) runtime for unicode -> byte offset conversion

### LINKED ISSUE #15786: CoqIDE shows substantial slow down (about 30x for large files) in 8.15
A measurement of the "Run to end" time for the Flocq file [Pff.v](https://gitlab.inria.fr/flocq/flocq/-/raw/master/src/Pff/Pff.v) in CoqIDE for various versions of Coq gave these results:
```
8.12: 3'40"
8.13: 2'40"
8.14: 2'00"
8.15: between 55' and 85' (it finished while I was at lunch)
```
All times are manually measured and approximately (+0s/-10s). All versions use the same OCaml 4.10.2 (I used Coq Platform 2022.01 to install the 4 versions).

As discussed here [Zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Splitting.20CoqIDE.20-.20speed.20regression) the slow down might be quadratic with the length of the file, so that with "normal" files it is not that bad, but it is quite noticeable also with normal length files. The parsing part of a file with 100 definitions and lemmas takes 10..20s.

### PR DESCRIPTION
**Pull request by jfehrle**
With this change List.v (100KB) takes 6 seconds to run compared to 46 seconds without it.

Fixes: #15786

Let me know what you think.

### CODE REVIEW

File: ide/coqide/ideutils.ml [hunk 1]
```diff
@@ -179,14 +179,14 @@ let byte_off_to_buffer_off buffer byte_off =
   cvt (buffer#get_iter `START) byte_off
 
 (** convert unicode offset (used by GTK buffer) to UTF-8 byte offset (used by Coq) *)
-let buffer_off_to_byte_off (buffer : GText.buffer) uni_off =
+let buffer_off_to_byte_off (buffer : GText.buffer) (s_byte, s_uni) uni_off =
   let rec cvt iter rv =
-    if iter#offset <= 0 then
+    if iter#offset <= s_uni then
```
Comment (ppedrot) [inline ide/coqide/ideutils.ml:184]: This is incorrect if the function is called on a range that occurs before the cache.

**Comment by ppedrot** [comment]
This is a reasonable hotfix for 8.15 but I still believe we should follow a more principled approach.

File: ide/coqide/ideutils.ml (hunk 1 above)
Comment (jfehrle) [reply ide/coqide/ideutils.ml:184]: I assumed the sentences would be processed in ascending order.  Is that not guaranteed?

Comment (jfehrle) [reply ide/coqide/ideutils.ml:184]: Incorrect meaning slow.

Comment (ppedrot) [reply ide/coqide/ideutils.ml:184]: In all its current uses, the function is correct. But this is part of a public API, and if it happens to be used without this precondition it will produce garbage results.

Comment (jfehrle) [reply ide/coqide/ideutils.ml:184]: I don't see it.  If the value is (0,0) then it goes through the entire string.  Slower than we want but correct.

Comment (ppedrot) [reply ide/coqide/ideutils.ml:184]: The bug happens if you put it to something else than (0, 0). It will probably loop (not sure, depends what GTK does when iterating before the buffer start).

**Comment by ejgallego** [comment]
> This is a reasonable hotfix for 8.15 but I still believe we should follow a more principled approach.

Yes! Just to note tho that the stuff of locations and unicode, is not an easy one, even LSP f***** up royaly last time I looked. So we need to walk this issue with "pies de plomo"

File: ide/coqide/ideutils.ml (hunk 1 above)
Comment (ppedrot) [reply ide/coqide/ideutils.ml:184]: (The simplest way to fix this is to keep this function as-is there but redefine the one using the cache in the scriptview module.)

Comment (jfehrle) [reply ide/coqide/ideutils.ml]: Done.

**Comment by jfehrle** [comment]
"pies de plomo" doesn't translate literally to English.  "lead foot" refers to a tendency to drive excessively fast--rather different :-)

**Review by ppedrot — APPROVED** [review]

**Comment by ejgallego** [comment]
> "pies de plomo" doesn't translate literally to English. "lead foot" refers to a tendency to drive excessively fast--rather different :-)

Sorry, for some reason I couldn't find the right english term for it, but it is actually very easy, it means "we have to handle this issue very carefully"

[it means your feet are made of lead, so you walk slowly and with care]

**Comment by ppedrot** [comment]
This is not enough to fix the quadratic behaviour. The reverse call `byte_off_to_buffer_off` is now leading the perf profile. In addition, CoqIDE tends to randomly freeze on big files (this is not introduced by this PR but clearly the performance issue is still around).

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by jfehrle** [comment]
What is your test case?  When I add a print statement in `byte_off_to_buffer_off` and repeat the test with `List.v`, it's not even called.

**Comment by ppedrot** [comment]
I am testing the Pff.Pff file from flocq.
