### PR TITLE
[declare] Fix types of mutual lemmas when using Admitted.

### LINKED ISSUE #12895: Anomaly using `Admitted` for mutual fixpoint with differing+implicit arguments
#### Description of the problem

Under Coq 8.12, and current `master` (8.13+alpha), I get an anomaly in the following code:

```
Fixpoint bug_1 (e1 : nat) {struct e1}
  : nat
with bug_2 {H_imp : nat} (e2 : nat) {struct e2}
  : nat.
Proof.
  - exact e1.
  - exact e2.
Admitted.
```

This errors at the `Admitted`, with error message `Anomaly "File "interp/impargs.ml", line 378, characters 15-21: Assertion failed."`

Some experimenting suggests that the triggering condition is something roughly like:
- there is a mutual fixpoint, with two or more components;
- their interactive proof is concluded with `Admitted`;
- some *later* component of the mutual fixpoint has *more* implicit arguments than the first component;
- and *at least one* of the arguments of that component is implicit.
- This anomaly occurs under current `master`, bd4791ff, 8.13+alpha; also under 8.12.0, 558e8ea1.

In particular, in the example above:
- if `H_imp` is made explicit, then no error occurs
- if the implicit arg `H_imp` occurs in both components of the mutual fixpoint, or in just the first, then no error occurs 
- if the definition is completed to a `Defined` or `Qed`, then no error occurs
- when completing with `Admitted`, the error occurs regardless of how much proof (if any) has been given beforehand
- the specific types involved don’t seem to affect the error
- the `struct` annotations don’t seem to interact with the error
- in the original occurrence in the wild (reported at https://github.com/UniMath/TypeTheory/issues/182, arising from [Initiality.InterpretationLemmas.trivial_interpretation_ty](https://github.com/UniMath/TypeTheory/blob/a84fc71d116ff640f1e21a9a34301585e7c5caa8/TypeTheory/Initiality/InterpretationLemmas.v#L329)), the types of `e1`, `e2` were a genuinely mutually inductive pair of types.
- that original occurrence compiled fine under Coq 8.11, so presumably this bug didn’t occur there (though I haven’t downgraded to test this MWE under 8.11).

#### Coq Version

This MWE produces an anomaly under Coq bd4791ff (current `master`, at time of writing):

`The Coq Proof Assistant, version 8.13+alpha (August 2020) compiled on Aug 25 2020 9:37:00 with OCaml 4.05.0`

It also produces the same anomaly under Coq 558e8ea1 (8.12.0), compiled for UniMath.

### PR DESCRIPTION
**Pull request by ejgallego**
We fix a clear coding mistake in
79bcf1c0a22e736c4e2cae3460c35b3d9fca9aa0 that forgot to update the
type of the parameter entry when saving mutual definitions without a
body.

I am not sure what invariants have to hold regarding the universe
constraints, indeed it is possible that some constraints are still
missing as we call `prepare_parameter` only for the first type.

Fixes #12895

### CODE REVIEW

**Comment by ejgallego** [comment]
Submitted as a draft as this likely needs more work to craft the correct `parameter_entry`, but the essence of the fix should be there.

File: vernac/declare.ml [hunk 1]
```diff
@@ -1921,10 +1921,13 @@ end = struct
     in
     List.map_i (declare_mutdef ~pinfo ~uctx pe) 0 pinfo.Proof_info.cinfo
 
+  let update_mutual_pe ~typ (v,(_,univs),i) = (v,(typ,univs),i)
```
Comment (SkySkimmer) [inline vernac/declare.ml:1924]: Univs should be dropped if monomorphic, same as next_univs in comassumption

Comment (ejgallego) [reply vernac/declare.ml:1924]: Should we add a test case for the polmorphic case?

**Review by herbelin — DISMISSED** [review]
My feeling is that `MutInd.declare_variable` should not take a `typ` in its `pe` argument since it already has a `typ` in each of the list of `cinfo`. Since `MutInd.declare_variable` is going to call several times `declare_assumption`, it should be its own business to build the list of parameter entries and not the business of its callers, namely `save_admitted` and `save_lemma_admitted_delayed` (via `finish_admitted`). So, in my humble opinion, the latters (`save_admitted` and `save_lemma_admitted_delayed`) should just send the `sec_vars` and the univ `ctx`.

Incidentally, why do we have different computations of `sec_vars` in `save_admitted` and `save_lemma_admitted_delayed`: the former looks at the `Proof using` (via `compute_proof_using_for_admitted`) but the latter only at `get_keep_admitted_vars` (i.e. `Set Keep Admitted Variables`). Shouldn't it be a call to `compute_proof_using_for_admitted` for both? (What is the typical Coq code to trigger `save_lemma_admitted_delayed` on a mutual theorem so that we can check if it correctly grants `Proof using`?)

Regarding universes, the difference of business in `save_admitted` and `save_lemma_admitted_delayed` is a bit complicated to follow and I capitulated. Could more factorization between `save_admitted` and `save_lemma_admitted_delayed` be made? Also, do we have sufficient tests for the different possible combinations involving polymorphic or monomorphic universes?

In any case, a lot of progresses has clearly been made recently in cleaning this complex part of the code already. That's good.

**Comment by ejgallego** [comment]
Thanks for the comment @herbelin , working on this for 8.12.1 (cc: @Zimmi48 ) but it is gonna take a few cycles; will update the PR and reply to your comment.

**Comment by ejgallego** [comment]
@herbelin I have implemented your changes, thanks! Test-suite permitting I think this can go into 8.12.1; however as you note the code still has some strange paths, in particular the dissonance between "mutligoals" and the way mutual statements are handled is a bit worrying.

Delayed is a problem but I have a feeling that this path will be obsolete soon so I wouldn't worry too much about it.

**Review by herbelin — APPROVED** [review]
Thanks, I like it. Assigning (and merging tonight).

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by ejgallego** [comment]
Merci !

**Comment by Zimmi48** [comment]
This is hard to backport because this code has been moved around in 8.13. @ejgallego: if you want this in 8.12.1, please prepare the backport yourself (you can push it on top of the other one already done in #12391).

**Comment by ejgallego** [comment]
Oh indeed, sorry for that; see #13252 for the v8.12 version.
