### PR TITLE
fix #11279. Specialize h no longer expands letins in the type of h.

### LINKED ISSUE #11279: `specialize H with bindings_list` should not inline let binders
I wasn't fast enough to comment on @Matafou's https://github.com/coq/coq/pull/11271 before it was merged, so I'm raising a new issue: Consider

```coq
Goal forall (a b: nat) (P: Prop),
     a = 2 * b ->
     (forall m1 m2: nat,
         let x0 := m1 * m1 in
         let x1 := x0 * x0 in
         let x2 := x1 * x1 in
         let xn := x2 * x2 in
         m1 = m2 -> xn > m2) ->
     True.
Proof.
  intros.
```

If I do 

```coq
  specialize H0 with (1 := H).
```

the type of `H0` becomes

```coq
a * a * (a * a) * 
(a * a * (a * a)) * 
(a * a * (a * a) * 
(a * a * (a * a))) > 2 * b
```

This is unfortunate for two reasons: If `specialize` is followed by further tactics which depend on this let-in structure, these will fail, and if the let-in structure is deeper than just n=3, we might get an exponentially large term size.

Desired behavior: The type of `H0` should become

```coq
let x0 := a * a in
let x1 := x0 * x0 in
let x2 := x1 * x1 in
let xn := x2 * x2 in
xn > 2 * b
```

In general, each tactic should do one thing only, and have no unexpected side-effects.

(This is a follow-up on https://github.com/coq/coq/issues/11253 and https://github.com/coq/coq/issues/9893)

Coq version: master (4a7a5c36802701d0e1b47956bb14cfc9cab99baa)

### PR DESCRIPTION
**Pull request by Matafou**
The type of h is reconstructed to look as much as the initial type of
h as possible.

**Kind:** bug fix / feature

Fixes / closes #11279

- [X] Added / updated test-suite

This is a proposition to avoid expanding let-ins in the hypothesis (or lemma) specialized. As the letins are removed when unification clauses, the type of the hypothesis needs to be reconstructed from the original type.

As i am not an expert of rel_context manipulation I am open to suggestion to simplify the code.

### CODE REVIEW

File: tactics/tactics.ml [hunk 1]
```diff
@@ -2993,16 +2993,29 @@ let quantify lconstr =
    solve, ui are a mix of inferred args and yi. The overall effect
    is to remove from H as much quantification as possible given
    lbind. *)
+
+(* let subst a b et = Termops.replace_term sigma a b et in *)
+let rec map_rel_context_lift f env i (ctxt:EConstr.rel_context):EConstr.rel_context =
+  match ctxt with
+  | [] -> ctxt
+  | decl::ctxt' -> f i decl :: map_rel_context_lift f env (i+1) ctxt'
```
Comment (Matafou) [inline tactics/tactics.ml]: this is my way of lifting things in a rel_context. Is there a cleaner way?

File: tactics/tactics.ml [hunk 2]
```diff
@@ -3028,38 +3041,54 @@ let specialize (c,lbind) ipat =
...
-          let sigma,hd' = rebuild_lambdas sigma lp' args hd l in
-          sigma,hd'
+          (* we reabstract the non solved argument *)
+          sigma,mkLambda ({nme with binder_relevance=r},new_typ_of_t,hd''),prods
+        | (LocalAssum (nme,tnme))::lp' , t::l' ->
+           (* thie arg was solved, we update thing accordingly *)
+           (* we replace in lprod the arg by rel 1 *)
+           let substlp' = (* rel 1 must be lifted along the context *)
+             map_rel_context_lift (fun i x -> map_constr (replace_term sigma (mkRel i) t) x)
+               env 1 lp' in
```
Comment (Matafou) [inline tactics/tactics.ml]: This is my way of replacing a rel by another term (that may reference other rel) in a rel_context.

File: tactics/tactics.ml (hunk 1 above)
Comment (Matafou) [inline tactics/tactics.ml]: this is my way of doing a map that takes the depth into account lifting things in a rel_context. Is there a cleaner way?

**Review by ppedrot — APPROVED** [review]
The code is quite contrived and likely algorithmically inefficient. It's only making things marginally worse compared to the previous solution though. I don't think it should be implemented in such an unprincipled way in the long term, but for the time being this kind of term mangling seems to be performing the task correctly. Thus good to go in.

File: tactics/tactics.ml [hunk 3]
```diff
@@ -2993,16 +2993,29 @@ let quantify lconstr =
...
+  match ctxt with
+  | [] -> ctxt
+  | decl::ctxt' -> f i decl :: map_rel_context_lift f env (i+1) ctxt'
+
+(* debugging
+let pr_rel_context env sigma rel_context =
+  Ppconstr.pr_binders env sigma (Constrextern.extern_rel_context None env sigma (List.rev rel_context))
+let prlc env sigma = Pp.prlist_with_sep Pp.pr_comma (Printer.pr_leconstr_env env sigma)
+let prlrelctxt env sigma = pr_rel_context env sigma
+*)
```
Comment (ppedrot) [inline tactics/tactics.ml]: Sorry, forgot to mention that this should go away before merging.

File: tactics/tactics.ml (hunk 1 above)
Comment (ppedrot) [reply tactics/tactics.ml]: Not that I know of in the current API for contexts, but you could use the list API instead.

Comment (Matafou) [reply tactics/tactics.ml]: Strange, I would have bet that performing rel-aware substitutions in a rel_context was something usual (but maybe that is more something we want to avoid?).
I could indeed use a fold.

**Comment by ppedrot** [comment]
It seems that the rebase has gone quite wrong.

**Comment by Matafou** [comment]
Indeed. I really should remove my local "master" branch :-).

**Comment by Matafou** [comment]
I removed the debugging code.

**Comment by Matafou** [comment]
Sorry all for the wrong automatic review request.

File: tactics/tactics.ml [hunk 4]
```diff
@@ -3028,38 +3036,54 @@ let specialize (c,lbind) ipat =
...
+              ignore them, but we remember them in accprod, so that they remain in the type. *)
+           rebuild sigma concl lp' accargs (assum::accprods) hd l
         | _ ,_ -> assert false in
-      let sigma,hd = rebuild_lambdas sigma (List.rev lprod) [] thd tstack in
-      Evd.clear_metas sigma, hd
+      let sigma,hd,newtype = rebuild sigma concl (List.rev lprod) [] [] thd tstack in
+      Evd.clear_metas sigma, hd, newtype
   in
-  let typ = Retyping.get_type_of env sigma term in
+  (* let typ = Retyping.get_type_of env sigma term in *)
```
Comment (ppedrot) [inline tactics/tactics.ml]: You forgot to remove that line as well.

**Comment by Matafou** [comment]
Done. I guess fiat-crypto failure has nothing to do.

**Comment by ppedrot** [comment]
Yes, before your change it was compiling, and it is currently broken in all branches. I am merging this thus.
