### PR TITLE
Fix passing line number of errors in xml protocol, causing ill-located or non-located errors, notably in the presence of utf8 characters

### LINKED ISSUE #18682: Syntax errors reported at a wrong location in CoqIDE
#### Description of the problem

In CoqIDE, with the following code
```coq
_.
_
```
The syntax error is reported in the second line.
More generally, it looks like most if not all syntax errors are reported at the wrong location when the file is more than one line long.

coqc is not affected by this bug.

#### Affected Coq Versions
b3e2ddbe4e4ff708562a94c0adf119b3efa904e9 -- master
(I bisected)

### PR DESCRIPTION
**Pull request by herbelin**
Fix was actually very easy and will make life in xml-based UIs much more comfortable.

Fixes #18682, #19139.

- [x] Added **changelog**.

### CODE REVIEW

**Comment by herbelin** [comment]
@jfehrle tried something the details of which I don't know well, then @ejgallego tried to rely on the byte offset provided by gtk but this required passing the line number across the protocol, what he did in 3a3de8fb484d89347379f4a9c387901714919a4a but there was still a place in serialization which was not passing a line number.

So, to me, the current solution (passing the line number and relying on gtk's byte-offset computation rather than recomputing a char-offset by counting ourselves how many utf8 bytes are used) seems to be pretty reasonable.

At least, it is not like we are not knowing where we are going. It is more that we knew but made it by steps.

**Comment by jfehrle** [comment]
Aside from the line number issue, can you give an example of the UTF-8 problem you mention fixing?

It's a odd to share a Loc.t because the server side uses character offsets (in several fields) while the client side (GTK) only works with byte offsets.  Seems like this is likely to cause confusion.

IIRC there are at least 4 different cases to test for error messages and tooltips.  In particular, displaying errors correctly when the user modifies a file that's being processed asynchronously.  I pointed out problems (based on testing the code by hand) with multiple versions of @ejgallego's changes, including the final one.  If you're interested in trying the test cases, I'll see if I find my notes on that.  I had many comments in https://github.com/coq/coq/pull/17382.

File: ide/coqide/protocol/xmlprotocol.ml [hunk 1]
```diff
@@ -9,7 +9,7 @@
 (************************************************************************)
 
 (** Protocol version of this file. This is the date of the last modification. *)
-let protocol_version = "20230413"
+let protocol_version = "20240517"
```
[the remark this answers is not in the document]
Comment (jfehrle) [reply ide/coqide/protocol/xmlprotocol.ml:12]: I'd reach out to @whonore for coqTail.

**Comment by herbelin** [comment]
> Aside from the line number issue, can you give an example of the UTF-8 problem you mention fixing?

Actually no :(. I thought the PR was fixing the UTF-8 shift but it fixes only the line number issue (as in #18682). (My own test had the error on a line w/o UTF-8 so I did not realize it that it was fixing only the line and not the offset.)

**Comment by herbelin** [comment]
Actually, there seems to be a lablgtk bug! A bad copy-paste at this [line](https://github.com/garrigue/lablgtk/blob/ea5a8dc34e0b2e5fd5fcd6c0d37832e9a1074989/src/ml_gtktext.c#L369) of the ocaml-C wrapper `ml_gtktext.c`.

So, I guess we indeed have to rely on our own byte-to-char conversion!

**Comment by herbelin** [comment]
> It's a odd to share a Loc.t because the server side uses character offsets (in several fields) while the client side (GTK) only works with byte offsets.

Are meaning the opposite, i.e. bytes in Coq and chars in GTK?

Would you know how to insert a "b2c" in the current code? One that works from the beginning of the current line and not from the beginning of the whole sentence?

**Comment by herbelin** [comment]
Sorry, I was expected an answer but did not realize that you wrote.

> Also, do you know when will 8.20 will freeze?

There is thread here: https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/8.2E20 . The current plan is:

    Branch creation: 2024-06-17
    8.20+rc1: 2024-06-26
    8.20.0: 2024-09-04

> @ejgallego submitted 2 PRs related to this some months apart. The first broke the mechanism completely and the second didn't fix all the damage

I don't know the details of all the work done by everyone, but regarding the passing of the full loc, line included, as well as regarding the use of the native GTK support for byte offset (`get_iter_at_line_offset`), these seem a priori to be good ideas (better locality and less glue). The problem was that Emilio did not test his changes, not realizing that the XML protocol had still holes and that lablgtk had a bug (now fixed upstream, but I don't know when it will be part of a released version of lablgtk; the last release, 3.1.4, was in January and there are 3 commits since then). 

I just tested the PR with the development version of lablgtk and the example `Definition α := x.` has now the good underlining! So, let's continue testing and if it works for all expected examples, maybe the simplest is to ensure that coqide is compiled with the development version of lablgtk.

Otherwise, I think we can go with the byte-to-char translation from the beginning of the sentence (or maybe from the beginning of the line).

**Comment by ejgallego** [comment]
@herbelin , indeed testing this stuff is hard and I didn't realize of the real problem until later (which also impacted coq-lsp, which I have to say has no issues with locations)

In particular what I didn't realize is that the lexer had been totally broken w.r.t. to positions by the debugger PR (even if I requested we keep a bug, we shouldn't have merged the code in that state). See https://github.com/coq/coq/pull/16978 for a summary of the problems. So the hole was not in the protocol but in the lexer.

@herbelin this change is good, and I tried in some other PR; I did close it tho as I didn't have the cycles to adapt 3rd party users of the protocol, as the change doesn't seem backwards compatible.

I didn't notice the labgtk bug, that's cool.

I am at loss at how to react to @jfehrle comments, other than to say that they are just basically technically and historically inaccurate; as we explained in the call. The curious reader can dig in some of the relevant PRs as all the info is there, including a summary.

Contrary to what Jim believes, the code between the merge of the debugger PR and #16978 is just too broken to even make coq-lsp with loads of hacks (we ported to 8.11 so the code prior was way less buggy)

So I strongly recommend no to go back!

**Comment by herbelin** [comment]
I tested @ppedrot's [fail/wait 20](https://github.com/coq/coq/pull/17382#issuecomment-1470002594) example and it seems to have the underlining of `fail` stable. #17023 and #16987 seem still fixed. I don't know well what else to exactly test.

I propose that we already merge this PR and that any regular coqide user install the development version of lablgtk, so that we can daily test further. To install lablgtk, I did:
```
git clone https://github.com/garrigue/lablgtk.git
git checkout lablgtk3 # if not already the case
dune build
dune install # went for me in the current opam switch
```
Note that I needed the following patch for `src-goocanvas/dune` before calling dune:
```
diff --git a/src-goocanvas2/dune b/src-goocanvas2/dune
index 34145a18..5da5d91f 100644
--- a/src-goocanvas2/dune
+++ b/src-goocanvas2/dune
@@ -12,9 +12,9 @@
 
 (rule
  (targets
-   cflag-goocanvas-2.0.sexp
-   clink-goocanvas-2.0.sexp)
- (action (run dune_config -pkg goocanvas-2.0 -version 2.0.4)))
+   cflag-goocanvas-3.0.sexp
+   clink-goocanvas-3.0.sexp)
+ (action (run dune_config -pkg goocanvas-3.0 -version 3.0.0)))
 
 (rule
  (targets cflag-extraflags.sexp)
@@ -27,7 +27,7 @@
  (flags :standard -w -6-7-27-32-33-34-36)
  (modules_without_implementation gooCanvas_types)
  (c_names ml_gtkgoocanvas)
- (c_flags         (:include cflag-goocanvas-2.0.sexp) (:include cflag-extraflags.sexp) -Wno-deprecated-declarations)
- (c_library_flags (:include clink-goocanvas-2.0.sexp))
+ (c_flags         (:include cflag-goocanvas-3.0.sexp) (:include cflag-extraflags.sexp) -Wno-deprecated-declarations)
+ (c_library_flags (:include clink-goocanvas-3.0.sexp))
  (libraries lablgtk3))
 
```

**Review by ejgallego — APPROVED** [review]
LGTM ! Thanks a lot @herbelin 

I tried to do this in #17391 , but I think I didn't have the time to update the clients, sorry I didn't manage to point to you to this direction. The fix of lablgtk is impressive.

By the way, you can also vendor lablgtk (just do a symlink in Coq's tree), which is convenient for quick testing.

@herbelin , you may find some bits in #17391 interesting, in case you'd like to add them here, also Jim's tooltip test case (which is pretty good) is there I believe.

**Comment by ejgallego** [comment]
@herbelin the standard method for positions these days is indeed line / column , encoded in very different ways tho, due to windows and unicode (actually I misinterpreted the LSP spec in this sense, thanks to Léo Stefanesco who corrected this mistake, it took quite a bit of effort to get unicode working well but now we have a superb solution IMO)

However, offsets (in this case in byte form), even if less standard, are very very useful, so I'm so glad for Coq's `Loc.t` type, which has both.

Many advanced use cases and editors, such as CodeMirror , do require offsets too!

But yes, but GTK editing, the right choice is to use line numbers + offset adjustement, and store metadata in protocol-level format (which can vary between platforms)

**Comment by jfehrle** [comment]
> I propose that we already merge this PR

It would be good to fix everything at once so we don't (perhaps) change the protocol twice.  But there's also the argument that an incremental improvement would appreciated for 8.20.

> the standard method for positions these days is indeed line / column

That's fine if you don't allow the user to edit the buffer while Coq is processing it.  But we do.

**Comment by jfehrle** [comment]
Using PMP's example, the line number shown in the error panel is incorrect.  Maybe an easy fix:

image

**Comment by herbelin** [comment]
> Using PMP's example, the line number shown in the error panel is incorrect.

I confirm (and I have no idea a priori of how to fix it).

> > the standard method for positions these days is indeed line / column
> 
> That's fine if you don't allow the user to edit the buffer while Coq is processing it. But we do.

Hum, what to do? Could the computation once made from the beginning of the sentence be used to compute the line shift from the beginning of the sentence?

> You don't plan to do anything about the `Definition α := x`. case in this PR?

This works with the fixed version of lablgtk. So the question is about whether we want to have a solution (and have the courage to implement it) even without the lablgtk fix. In any case, this does not have to be in this PR.

What the PR fixes is practically important (as in #18682 but imagine when there are more lines involved). The wrong location (and sometimes even no location at all, because computed out of the text) made the use of coqide really more difficult to me. (If you don't know what to expect, maybe it is not so bad, but when you know that there should be a location and you have to look through e.g. 10 lines to understand from were some typing error could come, it is frustrating.). So, for me, the priority is to merge the PR and appreciate the incremental improvement for 8.20.

The unicode shift due to the lablgkt bug is not elegant but somehow less critical in practice because you can still reconstruct where the underlining was intended.

> That's fine if you don't allow the user to edit the buffer while Coq is processing it. But we do.


@ejgallego:

> By the way, you can also vendor lablgtk (just do a symlink in Coq's tree), which is convenient for quick testing.

Sorry, I don't understand. A symlink to what?

In any case, I'm glad that we are now converging to a resolution of most location problems!

> It would be good to fix everything at once so we don't (perhaps) change the protocol twice

Maybe the other known users of the XML protocol have an opinion here (CoqTail, VsCode 1)?

**Comment by ejgallego** [comment]
> I confirm (and I have no idea a priori of how to fix it).

What the rest of the code does is to adjust the locations, I guess this list is not updated? I can have a look and find the concrete code that does that for tooltips.

> Sorry, I don't understand. A symlink to what?

To lablgtk sources.

> That's fine if you don't allow the user to edit the buffer while Coq is processing it. But we do.

Why is the choice of offsets vs line / column relevant here? In both cases, the locations need adjustment, I don't see how line / col cannot be also adjusted (in fact it could be even more efficient, that's why _text_ editors prefer line/col coordinates)

**Comment by herbelin** [comment]
> To lablgtk sources.

You mean an http link? Or a copy of the sources? Anyway, we can discuss it elsewhere.

**Comment by ejgallego** [comment]
> You mean an http link? Or a copy of the sources? Anyway, we can discuss it elsewhere.

A symlink to a copy of the sources, or just drop a copy of the sources.

**Comment by jfehrle** [comment]
@herbelin If Coq's 8.20 build requires the updated labgtk then there's no point in adding new code to do a conversion ourselves.  Will there be a new version number for labgtk that includes the change or would our build have to pull a specific commit until they do a new release?  ([This](https://github.com/coq/coq/pull/19040#issuecomment-2132357234) is still the best way for me to get the fix today?)

We still have a couple weeks before the 8.20 freeze.  If you have time, let's try to identify _all_ the remaining problems and, if reasonably possible, fix them them for 8.20.  A focused effort is more likely to be correct.  Revisiting the same general issue repeatedly over a long period of time is inefficient.

@ejgallego
> > > the standard method for positions these days is indeed line / column

> > That's fine if you don't allow the user to edit the buffer while Coq is processing it. 

> Why is the choice of offsets vs line / column relevant here? In both cases, the locations need adjustment, I don't see how line / col cannot be also adjusted

Either one will work.  I'm agnostic.  But we need code that's 100% correct.  My point is that the protocol has to send (sentence id, line, column) or (sentence id, offset) for errors and the client has to remember something (a line number or offset) about each sentence it has sent to Coq so it can do the adjustment.  Needing the sentence id not at all standard; it is a quirk of CoqIDE async mode.

File: dev/doc/xml-protocol.md [hunk 2]
```diff
@@ -194,8 +193,9 @@ Moves current tip to `${stateId}`, such that commands may be added to the new st
 ```
 * Failure: If `stateId` is in an error-state and cannot be jumped to, `errorFreeStateId` is the parent state of `stateId` that should be edited instead.
 ```html
-<value val="fail" loc_s="${startOffsetOfError}" loc_e="${endOffsetOfError}">
+<value val="fail">
   <state_id val="${errorFreeStateId}"/>
+  <option val="none|some">${loc}</option>
   ${errorMessage}
 </value>
 ```
```
Comment (jfehrle) [inline dev/doc/xml-protocol.md:201]: The description at line 924 ("* <a name="location">Location</a>, a Coq location:") omits the fname field, which is part of Loc.t but not in the protocol (arguably it should be sent, too).  Probably it should also say that it's based on the `Loc.t` type (more specific).

File: dev/doc/xml-protocol.md [hunk 3]
```diff
@@ -151,16 +151,15 @@ state that should become the next tip.
 * Failure:
   - Syntax error. Error offsets are byte offsets (not character offsets) with respect to the start of the sentence, starting at 0.
```
Comment (jfehrle) [inline dev/doc/xml-protocol.md:152]: Should probably mention that _all_ of the field values received may need to be adjusted if the sentence was have moved since it was sent to Coq (e.g. due to async mode).  Maybe mention byte offsets vs UTF-8 character offsets/conversion.  Extra credit if you explain how to adjust values.

**Review by jfehrle — COMMENTED** [review]
Some odds and ends.

**Comment by herbelin** [comment]
> @herbelin If Coq's 8.20 build requires the updated labgtk then there's no point in adding new code to do a conversion ourselves. Will there be a new version number for labgtk that includes the change or would our build have to pull a specific commit until they do a new release?

I just asked them.

>  ([This](https://github.com/coq/coq/pull/19040#issuecomment-2132357234) is still the best way for me to get the fix today?)

This is how I installed the fix myself.

> We still have a couple weeks before the 8.20 freeze. If you have time, let's try to identify _all_ the remaining problems and, if reasonably possible, fix them them for 8.20. A focused effort is more likely to be correct. Revisiting the same general issue repeatedly over a long period of time is inefficient.

I don't have much time myself, but let's try yes.

File: dev/doc/xml-protocol.md (hunk 2 above)
Comment (herbelin) [reply dev/doc/xml-protocol.md:203]: Good point. Maybe should we send the `fname` too? Are there situations where Coq reports about locations in a file rather than in the toplevel input?

File: ide/coqide/protocol/xmlprotocol.ml [hunk 4]
```diff
@@ -1023,7 +1015,7 @@ let document to_string_fmt =
     (to_string_fmt (of_value (fun _ -> PCData "b") (Good ())));
   Printf.printf "or:\n\n%s\n\nwhere the attributes loc_s and loc_c are optional.\n"
     (to_string_fmt (of_value (fun _ -> PCData "b")
-      (Fail (Stateid.initial,Some (15,34), Pp.str "error message"))));
+      (Fail (Stateid.initial,Some (Loc.make_loc (15,34)), Pp.str "error message"))));
```
[the remark this answers is not in the document]
Comment (herbelin) [reply ide/coqide/protocol/xmlprotocol.ml]: Right, this needs a proper update.

**Review by herbelin — COMMENTED** [review]
Changed made. I also added `fname` (so, another change to the protocol).

File: ide/coqide/protocol/xmlprotocol.ml [hunk 5]
```diff
@@ -1021,9 +1013,12 @@ let document to_string_fmt =
     (to_string_fmt (constructor "call" "C" [PCData "a"]));
   Printf.printf "A response carrying output b can either be:\n\n%s\n\n"
     (to_string_fmt (of_value (fun _ -> PCData "b") (Good ())));
-  Printf.printf "or:\n\n%s\n\nwhere the attributes loc_s and loc_c are optional.\n"
+  Printf.printf "or:\n\n%s\n\n"
     (to_string_fmt (of_value (fun _ -> PCData "b")
-      (Fail (Stateid.initial,Some (15,34), Pp.str "error message"))));
+      (Fail
+         (Stateid.initial,
+          Some (Loc.{fname=ToplevelInput; line_nb=4; bol_pos=0; line_nb_last=6; bol_pos_last=10; bp=15; ep=34}),
```
Comment (jfehrle) [inline ide/coqide/protocol/xmlprotocol.ml:1020]: Better, but still has various magic numbers and not obvious how they were determined.  But not essential to clean up this bit in this PR.

File: dev/doc/xml-protocol.md (hunk 2 above)
Comment (jfehrle) [reply dev/doc/xml-protocol.md:203]: For reporting errors, warnings, etc. I'm pretty sure CoqIDE doesn't currently report anything that's outside the current buffer. The debugger "get stack" message includes the absolute filename with `bp/ep` offsets.  It will open a buffer for the referenced file if needed.  Let's not touch that--it works correctly now and doesn't have the location problems we're trying to address for error messages.  (Indeed, part of the problem with the error message locations has including unneeded, untested and buggy "clean up".)

Still not super keen about reusing `Loc.t` in CoqIDE.  It would be logical to receive a Loc.t in CoqIDE, then adjust all the fields in one place (encapsulation).  Putting the adjusted fields back into a Loc.t means that sometimes Loc.t has byte offsets and sometimes it has char offsets--easy to confuse and requires close reading of the code to follow.  Your choice.

File: dev/doc/xml-protocol.md [hunk 6]
```diff
@@ -151,18 +151,19 @@ state that should become the next tip.
...
     <richpp>${errorMessage}</richpp>
   </value>
   ```
   - Another kind of error, for example, Qed with a pending goal.	
   ```html
-  <value val="fail"><state_id val="${stateId}"/><richpp>${errorMessage}</richpp></value>
+  <value val="fail"><state_id val="${stateId}"/><option val="some">${loc}</option><richpp>${errorMessage}</richpp></value>
   ```
 
+  Note that locations may need to be adjusted by the IDE to character offsets in the presence of multi-byte characters. Also, due to asynchronous evaluation, a location may have to adjusted if the sentence has moved since it was sent to Coqtop.
```
Comment (jfehrle) [inline dev/doc/xml-protocol.md:165]:
```suggestion
  Note that IDEs may need to convert byte offsets passed in the four position fields of the location
  to character offsets to correctly handle multi-byte characters. Also, due to asynchronous
  evaluation, line number fields of locations may need to be adjusted if the sentence has moved
  since it was sent to Coqtop.
```

more detail, slight wording improvement and split into multiple lines

**Comment by jfehrle** [comment]
Another bug.  Could be fixed by saving the character offset of the beginning of the sentence and accounting for that in the adjustment.  But pretty unlikely users will put everything on one line like this.  (Still looking for more issues.)

image

File: ide/coqide/protocol/xmlprotocol.ml (hunk 5 above)
Comment (herbelin) [reply ide/coqide/protocol/xmlprotocol.ml:1020]: That's not magic numbers, it is an arbitrary example for documenting the protocol (it is in function `document`).

File: dev/doc/xml-protocol.md (hunk 2 above)
Comment (herbelin) [reply dev/doc/xml-protocol.md:206]: I'm not competent to judge here. Apparently, it works with `Loc.t`. And as far as I can judge, to work properly, it should *only* have byte offsets (as in Coq).

**Review by jfehrle — COMMENTED** [review]
minor cleanup

**Comment by jfehrle** [comment]
@herbelin I tried your instructions to set up the modified lablgtk [here](https://github.com/coq/coq/pull/19040#issuecomment-2132357234) but didn't get too far.  They need some refinement to be usable by "any regular coqide user" for testing.

- There should be a `cd lablgtk` before ` build dune`
- When I tried to apply the modifications to `src-goocanvas/dune` with `git apply`, I get `error: corrupt patch at line 27`.  But I think I got the right changes manually.
- I get several issues when I try to build with dune.
-- I don't have a `PKG_CONFIG_PATH` set up.  How do I get `goocanvas-3.0.pc` and the appropropriate source tree?
-- Same thing for `librsvg-2.0`, `gtkspell3-3.0` and `camlp5o`?

```
/home/proj/lablgtk$ dune build
File "src-rsvg2/dune", line 9, characters 0-128:
 9 | (rule
10 |  (targets
11 |    cflag-librsvg-2.0.sexp
12 |    clink-librsvg-2.0.sexp)
13 |  (action (run dune_config -pkg librsvg-2.0 -version 2.40)))
 dune_config src-rsvg2/cflag-librsvg-2.0.sexp,src-rsvg2/clink-librsvg-2.0.sexp (exit 1)
configure error: Package librsvg-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `librsvg-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'librsvg-2.0' found

File "src-gtkspell3/dune", line 8, characters 0-135:
 8 | (rule
 9 |  (targets
10 |    cflag-gtkspell3-3.0.sexp
11 |    clink-gtkspell3-3.0.sexp)
12 |  (action (run dune_config -pkg gtkspell3-3.0 -version 3.0.4)))
 dune_config src-gtkspell3/cflag-gtkspell3-3.0.sexp,src-gtkspell3/clink-gtkspell3-3.0.sexp (exit 1)
configure error: Package gtkspell3-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtkspell3-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtkspell3-3.0' found

File "src-goocanvas2/dune", line 13, characters 0-135:
13 | (rule
14 |  (targets
15 |    cflag-goocanvas-3.0.sexp
16 |    clink-goocanvas-3.0.sexp)
17 |  (action (run dune_config -pkg goocanvas-3.0 -version 3.0.0)))
 dune_config src-goocanvas2/cflag-goocanvas-3.0.sexp,src-goocanvas2/clink-goocanvas-3.0.sexp (exit 1)
configure error: Package goocanvas-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `goocanvas-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'goocanvas-3.0' found

File "tools/dune", line 13, characters 0-138:
13 | (rule
14 |  (targets propcc.ml)
15 |  (deps (:source propcc.ml4))
16 |  (mode promote)
17 |  (action (bash "camlp5o pr_o.cmo -impl %{source} -o %{targets}")))
        bash tools/propcc.ml (exit 127)
/bin/bash: camlp5o: command not found
File "tools/dune", line 7, characters 0-136:
 7 | (rule
 8 |  (targets varcc.ml)
 9 |  (deps (:source varcc.ml4))
10 |  (mode promote)
11 |  (action (bash "camlp5o pr_o.cmo -impl %{source} -o %{targets}")))
        bash tools/varcc.ml (exit 127)
/bin/bash: camlp5o: command not found
```

**Comment by herbelin** [comment]
> @herbelin I tried your instructions to set up the modified lablgtk [here](https://github.com/coq/coq/pull/19040#issuecomment-2132357234) but didn't get too far. They need some refinement to be usable by "any regular coqide user" for testing.
> 
>     * There should be a `cd lablgtk` before ` build dune`

Yes.

>     * When I tried to apply the modifications to `src-goocanvas/dune` with `git apply`, I get `error: corrupt patch at line 27`.  But I think I got the right changes manually.

OK.
 
>     * I get several issues when I try to build with dune.
>       -- I don't have a `PKG_CONFIG_PATH` set up.  How do I get `goocanvas-3.0.pc` and the appropropriate source tree?
>       -- Same thing for `librsvg-2.0`, `gtkspell3-3.0` and `camlp5o`?

My `PKG_CONFIG_PATH` has value `/path-to-opam/.opam/opam-switch-name/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig`

I installed librsvg, gtkspell3, goocanvas with my package manager (in my case brew). I installed camlp5o by `opam camlp5`.

Hope it'll work for you.

**Comment by jfehrle** [comment]
Some progress.  I got `ocamlp5` and `gtkspell3-3.0`.  I already had `librsvg2-2`.  Dune now finds ocamplp5 but not the other 3. Also I don't know how to set `PKG_CONFIG_PATH` (Neither `.opam/opam-switch-name` nor `/usr/local/opt` exist.)

My package manager doesn't have a package for goocanvas3.  When I try to do `apt-get update`, I get some public key errors that I'm not immediately able to solve.

Any thoughts?

```

~/.opam$ ls
4.06.0                      4.11.1                               _coq-platform_.8.14                   log
4.06.0+spacetime            4.12.0                               _coq-platform_.8.14+debugger_preview  opam-init
4.06.0+statistical-memprof  __coq-platform.2022.01.0~8.15~beta1  config                                plugins
4.06.1+statistical-memprof  _coq-platform_.2021.02.1             config.lock                           repo
4.07.1                      _coq-platform_.2021.03.0             download-cache
4.09.0                      _coq-platform_.2021.debugger         lock

$ apt-cache search goocanvas
gir1.2-goocanvas-2.0 - GObject introspection data for GooCanvas - gir bindings
libgoocanvas-2.0-9 - Canvas widget for GTK+ - shared library
libgoocanvas-2.0-common - Canvas widget for GTK+ - common files
libgoocanvas-2.0-dev - Canvas widget for GTK+ - development files
libgoocanvas2-perl - Perl bindings for the goocanvas-2.0 widget using Glib::Object::Introspection
libgoocanvasmm-2.0-6 - C++ bindings for GooCanvas - shared library
libgoocanvasmm-2.0-dev - C++ bindings for GooCanvas - development files
libgoocanvasmm-2.0-doc - C++ bindings for GooCanvas - documentation and examples
python-goocalendar - Calendar widget for GTK+ using PyGoocanvas (Python 2)

$ sudo !!
sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://ppa.launchpad.net/avsm/ppa/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:4 http://dl.google.com/linux/chrome/deb stable InRelease [1825 B]
Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Err:4 http://dl.google.com/linux/chrome/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E88979FB9B30ACF2
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E88979FB9B30ACF2
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E88979FB9B30ACF2
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by herbelin** [comment]
I would say to install the three libgoocanvas-2.0 packages (and then, since it is 2.0, you don't need the patch I had for 3.0).

For opam, I don't know if it is really necessary to add it to PKG_CONFIG_PATH but, if yes, this will be done automatically by ``eval `opam config env` ``. Then the path to the pkg configuration file of libffi can be added manually (and maybe you don't need it in your setting).

(I suspect that not all packages are mandatory but I don't know how to tell it to dune)

**Comment by jfehrle** [comment]
@herbelin I pushed alternative code that doesn't rely on the lablgtk fix.  Please try it out.

I spent quite a while trying to fix [this problem](https://github.com/coq/coq/pull/19040#issuecomment-2136090712).  I got one test case to work, then after I thought I was done, I found two others that don't work.  I needed to additionally save the beginning of line offset of each sentence and made the tooltip offsets in sentence.tooltips relative to the beginning of the sentence so that I could track positions.

I'll see if I have time to try some more test cases.

File: ide/coqide/ideutils.ml [hunk 7]
```diff
@@ -174,6 +174,17 @@ let ulen uni_ch =
   else if uni_ch < 0x10000 then 3
   else 4
 
+(* workaround for lablgtk bug *)
```
Comment (herbelin) [inline ide/coqide/ideutils.ml:177]: I suggest
```
(* workaround for lablgtk bug up to version 2.18.13 *)
(* see https://github.com/garrigue/lablgtk/pull/175 *)
```

**Comment by jfehrle** [comment]
This looks ready to merge.  The protocol change may break coqtail and vsCoq1.  Do you want to reach out to them before we merge this?  Not sure it's reasonable to add a protocol change in 8.19.2.  WDYT?

Some usability issues with the display of warnings and errors that are beyond the scope of this PR:
- warnings should appear in the error table so you can jump to them
- there should be a "next error" key binding to step through the error table.  (The Compile/Next Error function seems to be to handle errors from an external compilation.  I have no idea how to use it.  Do you?)
- error table locations can become inaccurate when editing in async mode
- Frequently the last error is highlighted like a tooltip but no tooltip is displayed
- Still some corner cases when tooltips don't appear properly (though locations are good).  Some may not be readily fixed.

**Comment by herbelin** [comment]
>  The protocol change may break coqtail and vsCoq1. 

Right, so maybe the protocol-breaking initial PR can be merged to only 8.20 but the utf8 workaround already to 8.19.2?

Regarding the usability issues, maybe @Frigory33 would like to be in the loop.

**Comment by whonore** [comment]
> The protocol change may break coqtail and vsCoq1.

I think this should be a fairly easy fix for coqtail. I'll open a PR probably today.

**Comment by jfehrle** [comment]
> Right, so maybe the protocol-breaking initial PR can be merged to only 8.20 but the utf8 workaround already to 8.19.2?

Yes, though we should check that it would improve 8.19.

File: ide/coqide/ideutils.ml [hunk 8]
```diff
@@ -174,6 +174,19 @@ let ulen uni_ch =
   else if uni_ch < 0x10000 then 3
   else 4
 
+(* workaround for lablgtk bug up to version 2.18.13 *)
+(* replaces: buffer#get_iter_at_byte ~line index *)
+(* see https://github.com/garrigue/lablgtk/pull/175 *)
```
Comment (SkySkimmer) [inline ide/coqide/ideutils.ml:179]: doesn't seem related, https://github.com/garrigue/lablgtk/pull/175 is about copy_string_check AFAICT

Comment (herbelin) [reply ide/coqide/ideutils.ml]: It should be fixed. It is 181.

Comment (jfehrle) [reply ide/coqide/ideutils.ml]: Got it.

**Comment by herbelin** [comment]
> Yes, though we should check that it would improve 8.19.

It improves at least the locating of the error in `Definition α := x.`.

**Review by jfehrle — APPROVED** [review]
Will merge soon if there are no further comments.

I'll submit the third commit to 8.19.2 separately.

**Comment by jfehrle** [comment]
@coqbot run full ci

**Comment by jfehrle** [comment]
@maximedenes @rtetley Do you know who, if anyone, maintains vsCoq1?  This PR will likely break it since it changes the XML protocol a little.  We'd like to give a heads up and get a clean fix.

**Comment by gares** [comment]
@thery for vscoq1 maintenance

**Comment by jfehrle** [comment]
@thery This PR makes a small modification to the XML protocol that vsCoq1 relies on.  Will you or someone else be able to update vsCoq1 for use with Coq 8.20?  Thanks.

**Comment by jfehrle** [comment]
@herbelin See #19139, for which the underlying problem is that a fail message only returns bp and ep.  See the code in `Xmlprotocol.to_value` with `loc_s` and `loc_e`.  We could change the fail return to include a full Loc.t, but parsing errors are reported _immediately_ so the user has no chance to move the sentence.  I have a simpler fix that's only 4 lines.  WDYT?

**Comment by jfehrle** [comment]
@coqbot: merge now

**Comment by jfehrle** [comment]
@coqbot: merge now
