### PR TITLE
Ltac2: don't anomaly when applying ()

### LINKED ISSUE #12820: Anomaly : Ltac2 -- giving absurd argument to ( )
This following absurd minimal example throws an anomaly error:

```
Ltac2 id_bool (b : bool) := b.

Goal True.
  () id_bool.
```
Giving the following error message:

```
Anomaly
"File "user-contrib/Ltac2/tac2intern.ml", line 1070, characters 2-8: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

Thanks!

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #12820

### CODE REVIEW

File: plugins/ltac2/tac2intern.ml [hunk 1]
```diff
@@ -1166,6 +1166,14 @@ and intern_constructor env loc kn args = match kn with
...
+| Tuple 0 when not (List.is_empty args) ->
+  (* parsing [() bla] produces [CTacApp (Tuple 0, [bla])] but parsing
+     [((), ()) bla] produces [CTacApp (CTacApp (Tuple 2, [(); ()]), [bla])]
+     so we only need to produce a sensible error for [Tuple 0] *)
+  let t = GTypRef (Tuple 0, []) in
+  CErrors.user_err ?loc Pp.(
+      str "This expression has type" ++ spc () ++ pr_glbtype env t ++
+      spc () ++ str "and is not a function")
 | Tuple n ->
   assert (Int.equal n (List.length args));
```
Comment (ppedrot) [inline plugins/ltac2/tac2intern.ml:1178]: Why not move the above code here? We're already performing an equality check here, and where clauses are not robust.

**Review by ppedrot — APPROVED** [review]

File: test-suite/bugs/bug_12820.v [hunk 2]
```diff
@@ -0,0 +1,3 @@
+Require Import Ltac2.Ltac2.
+
+Fail Ltac2 Eval () ().
```
Comment (JasonGross) [inline test-suite/bugs/bug_12820.v:3]: Should we also check `((), ()) ()` while we're at it, to avoid regressions?

Comment (SkySkimmer) [reply test-suite/bugs/bug_12820.v]: sure

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
CI failures are spurious and we're already putting a strong enough pressure on the few workers we have not to rerun a full CI for nothing. So @coqbot merge now
