### PR TITLE
[configure] Remove `-std=c99` from default C flags

### LINKED ISSUE #11940: Coq master no longer builds in Ubuntu precise, trusty, nor xenial
#### Description of the problem

It's possible this is actually an OCaml build issue rather than a Coq issue, or possibly a combination of them.  I suspect the commit at fault is #11102.
https://launchpadlibrarian.net/471008616/buildlog_ubuntu-xenial-i386.coq_8.master~git~202003271542+21178-0~daily335-bc500cd~ubuntu16.04.1_BUILDING.txt.gz
```
cd kernel/byterun/ && "/usr/bin/ocamlfind" ocamlc -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence  -ccopt "-Wall -Wno-unused -g -O2 -std=c99 -fasm -msse2 -mfpmath=sse" -c coq_memory.c
In file included from coq_memory.h:15:0,
                 from coq_memory.c:21:
/usr/lib/ocaml/caml/fail.h:45:3: error: unknown type name ‘sigjmp_buf’
   sigjmp_buf buf;
   ^
make[3]: *** [kernel/byterun/coq_memory.o] Error 2
```

Note that until this is fixed, HoTT (and any other repo using my ppa packages on travis, which defaults to using xenial) will not be testing new commits with the latest version of master.

#### Coq Version

master (bc500cd)  (Note that 53a84d4 works fine)

### PR DESCRIPTION
**Pull request by ejgallego**
Recent OCaml don't allow to build the VM with `--std=c99` anymore due
to changes in header files. `gnu99` is required, but it turns out this
is already enforced by OCaml, so we just remove the flag altogether.

See the discussion in #11432

Fixes #11940 , restores compatibility with OCaml 4.11

### CODE REVIEW

File: configure.ml [hunk 1]
```diff
@@ -923,7 +923,11 @@ let datadir,datadirsuffix = let (_,_,d,s) = select "DATADIR" in d,s
 
 (** * CC runtime flags *)
 
-let cflags_dflt = "-Wall -Wno-unused -g -O2 -std=c99 -fasm"
+(* Note that Coq's VM requires at least C99-compliant floating-point
+   arithmetic; this should be ensured by OCaml's own C flags, which
+   set a minimum of --std=gnu99 ; modern compilers by default assume
+   C11 or later, so not explicit --std flags is added by OCaml *)
```
Comment (SkySkimmer) [inline configure.ml]:
```suggestion
   C11 or later, so no explicit --std flags is added by OCaml *)
```
typo

Comment (ejgallego) [reply configure.ml]: Fixed, thanks @SkySkimmer

**Comment by ejgallego** [comment]
This is needed for 8.11 support, anyone willing to assign?

**Comment by JasonGross** [comment]
I'd be willing to assign, but I'm not sure how to wrangle @coq/build-maintainers / @coq/vm-native-maintainers , who presumably need to review before this is merged?  (The change seems good to me, if indeed we inherit OCaml's CFLAGS (which I don't know how to check).)

**Comment by ejgallego** [comment]
Change is good as per discussion with Xavier; there is little to do other than merge I think. Would be interesting to know if that was the cause of you problem tho.

**Comment by JasonGross** [comment]
Should I just assign and merge, then?  Or do we need to wait for a review from @coq/build-maintainers ?

**Comment by ejgallego** [comment]
> if indeed we inherit OCaml's CFLAGS

We do as we compile C files thru `ocamlopt` , see an excerpt from the log:
```
$ (cd _build/default/kernel/byterun && /home/egallego/.opam/4.09.1/bin/ocamlc.opt -g -ccopt -Wall -ccopt -Wno-unused -ccopt -g -ccopt -O2 -ccopt -std=c99 -ccopt -fasm -ccopt -msse2 -ccopt -mfpmath=sse -ccopt -g -o coq_interp.o coq_interp.c)
```

**Comment by JasonGross** [comment]
Should we wait at least for @SkySkimmer to weigh in on this again?

**Comment by ejgallego** [comment]
The patch is correct that we know as Xavier confirmed, he has the most expertise in this area.

Whether it solves your issue is a different story.

**Comment by JasonGross** [comment]
Okay, I will assign and merge, and it can be reverted later if need be.

**Review by JasonGross — APPROVED** [review]

**Comment by ejgallego** [comment]
Yeah if that's more efficient for you than patching `debian/rules` up to add support for quilt I suggest we go ahead. Anyways we need this to merge #11131 which IMO is also prioritary as we want to keep testing OCaml `trunk` as to detect problems / try new features out.

**Comment by JasonGross** [comment]
I'm going to assume the VST failure is spurious.

**Comment by ejgallego** [comment]
> I'm going to assume the VST failure is spurious.

Yes it is.
