### PR TITLE
Match-printing

### LINKED ISSUE #19227: Local definitions in inductive parameters mess up term printing
### Description of the problem

```coq
Inductive T (a := 0) : nat -> Set := C : T 0.

Check match _ in T e return e = e with C => _ end.
(**
match ?t in (@T _ _ e) return (e = e) with
| C _ => ?e
end
*)
```
I would expect this to print the following :
```coq
match ?t in T _ e return e = e with
| C _ => ?e
end
```
since T only has one parameter (albeit a local definition) and one index.
Also, the parentheses are unnecessary, but this is less of an issue.

### Small Coq file to reproduce the bug

_No response_

### Version of Coq where this bug occurs

8.19.1, master (`b57e3f4`)

### Last version of Coq where the bug did not occur

_No response_

### LINKED ISSUE #20968: Inconsistency between parsing and printing for constructors with local def arguments and implicit arguments
Example code:
```rocq
Inductive T := C (c := I) (n : nat).
Arguments C {_}.
Check fun x => match x return True with C i => i end.
```

Expected output (if this ought to be accepted):
```rocq
fun x : T => match x with
             | C i => i
             end
     : T -> True
```

Current output:
```rocq
fun x : T => match x with
             | @C i _ => i
             end
     : T -> True
```

### PR DESCRIPTION
**Pull request by yannl35133**
Fixes / closes #19227
Fixes / closes #20968

Harmonise printing behaviour to current parsing behaviour, in patterns, when the constructor/inductive has both declared implicit arguments and local definitions in its type.

Removes unneeded parentheses in in-clauses and case_types by setting their printing priority level to align with their parsing priority level (this may be controversial, so it's in its own commit)

This fixes a test case which was not following the new behaviour.

- [x] Added / updated **test-suite**.

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

Overlays:
- stdlib: https://github.com/rocq-prover/stdlib/pull/204

### CODE REVIEW

**Comment by Blaisorblade** [comment]
> Harmonise printing behaviour to current parsig behaviour, in patterns, when the constructor/inductive has both declared implicit arguments and local definitions in its type.

The testcase has no implicits, right? If they're important to the bug (and they appeared in Zulip https://rocq-prover.zulipchat.com/#narrow/channel/237656-Rocq-devs-.26-plugin-devs/topic/Interaction.20between.20patterns.20and.20implicit.20arguments/with/529943958), then they should appear in some testcase too.

```
(* About T. *)
T : let a := 0 in nat -> Set

T is not universe polymorphic
Arguments T _%_nat_scope
Expands to: Inductive bluerock.lang.cpp.logic.pred.T
Declared in toplevel input, characters 10-11
```

**Comment by yannl35133** [comment]
They are not needed for bug 19227. I'm not sure of the policy then, do I just add some more test in the same file even though it's only mildly related, do I add a `bug_20957.v` file even though it's not a bug issue, do I create a new bug for the specific issue and file the test at this entry instead?

**Comment by yannl35133** [comment]
In the end, I created another issue for the specific instance of implicit arguments.

**Comment by yannl35133** [comment]
I found another place where the meaning of `to_tags` had got reversed

**Comment by silene** [comment]
I must admit that the whole thing comes as a surprise to me. I knew about local definitions, but I never suspected that they might have a concrete existence, and that you could actually match over them. Rather than fixing the printing, I wonder if we should not just get rid of local definitions from patterns once and for all. Local definitions would still exist for typing, but the following construct would become unsupported.

```coq
Inductive T := C (n := 42).
Definition foo x := match x with C n => n end.
```

**Comment by yannl35133** [comment]
That sounds heavy-handed for a feature that mostly works and can have use cases. I use it somewhat in some developments (only in proof mode though).

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
overlay is not used by CI
(iris failure unrelated)

**Comment by yannl35133** [comment]
I was waiting on the CI to finish before pushing my overlay (made in response to the stdlib failure)

**Comment by SkySkimmer** [comment]
@coqbot run full ci

File: dev/ci/user-overlays/20957-Yann-Leray-match-printing.sh [hunk 1]
```diff
@@ -0,0 +1 @@
+overlay stdlib https://github.com/Yann-Leray/stdlib match-printing 20957
```
Comment (SkySkimmer) [inline dev/ci/user-overlays/20957-Yann-Leray-match-printing.sh]:
```suggestion
overlay stdlib https://github.com/Yann-Leray/rocq-stdlib match-printing 20957
```

Comment (yannl35133) [reply dev/ci/user-overlays/20957-Yann-Leray-match-printing.sh]: Oh, sorry about that

**Comment by SkySkimmer** [comment]
@coqbot merge now
