### PR TITLE
Fix representation of empty arrays (fix #16832).

### LINKED ISSUE #16832: Anomaly creating definition for array literal
#### Description of the problem

```coq
Require Import PArray Uint63.
Check [| [| | 0x0 |] | [| | 0x0 |] : array int |]%uint63.
Definition x := [| [| | 0x0 |] | [| | 0x0 |] : array int |]%uint63.
(*
Anomaly "Uncaught exception Invalid_argument("index out of bounds")."
Please report at http://coq.inria.fr/bugs/.
*)
```

Found while minimizing https://github.com/coq/coq/issues/16829

#### Coq Version

8.16.0

### PR DESCRIPTION
**Pull request by silene**
Since there are no arguments, `Vmbytegen.comp_args` cannot be called in that case, so we just skip it.

The `MAKEBLOCK` opcode needs to be adapted accordingly, since size-0 blocks have a special representation in OCaml.

Remark: OCaml's bytecode interpreter uses special opcodes `ATOM`, `PUSHATOM`, `ATOM0`, and `PUSHATOM0`, for that purpose; but that seems excessive in the case of Coq.

Fixes / closes #16832

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

File: kernel/byterun/coq_interp.c [hunk 1]
```diff
@@ -925,10 +925,14 @@ value coq_interprete
         mlsize_t i;
         value block;
         print_instr("MAKEBLOCK, tag=");
-        Coq_alloc_small(block, wosize, tag);
-        Field(block, 0) = accu;
-        for (i = 1; i < wosize; i++) Field(block, i) = *sp++;
-        accu = block;
+        if (wosize == 0) {
+          accu = Atom(tag);
```
Comment (ppedrot) [inline kernel/byterun/coq_interp.c:929]: Probably not worth it, but we know that the tag will always be 0 in the case of Coq so maybe we could just assert it.

Comment (silene) [reply kernel/byterun/coq_interp.c:929]: I have considered it, but that might send the wrong message, as it would look like a precondition of this code, while it works perfectly fine for non-zero tags.

**Comment by ppedrot** [comment]
@coqbot merge now
