### PR TITLE
Print custom grammar entries

### LINKED ISSUE #9681: "Print Grammar foobar." regression
~~~coq
Print Grammar foobar.
(* 8.8: Error: Unknown or unprintable grammar entry.
master: succeeds with no output
8.9: not tested *)
~~~

### PR DESCRIPTION
**Pull request by jashug**
**Kind:** bug fix

Fixes / closes #9681

- [x] Added / updated test-suite

Hacky, but works. I don't know what the intended path for printing this information was (cc: @herbelin @ppedrot). Without this, `Print Grammar myconstr.` succeeds with no output.

### CODE REVIEW

**Comment by ppedrot** [comment]
A bit hackish indeed, but this is working as intended. Maybe a proper registration mechanism in `egramcoq.ml` would make this more principled, I don't know.

**Comment by herbelin** [comment]
The missing `constr:` and `pattern:` is well-spotted.

Then, there is a more (longer-term) general question. Currently, the `constr:` and `pattern:` variants of a custom grammar are identical. It should either be made possible to enrich one and not the other, or, probably, to otherwise renounce to make them different.

In any case, for the current PR, I don't think that it is worth to print both `constr:myentry` and `pattern:myentry` since they are the same.

Also, it looks like `find_grammars_by_name` changed semantics in 7e96257529f, returning `[]` where it was failing before. So, if we want that `Print Grammar` fails if its argument is not an existing grammar, we would need for `pr_registered_grammar` to check if `find_grammars_by_name` returned an empty list.

Then, I see at least the following possible strategies:
- It is `pr_registered_grammar "foo"` which looks for both `"foo"` and `"constr:foo"`, concatenates the results and fails if it is an empty list
- A new variant `Print Grammar Custom foo` is added, which looks for `constr:foo`, while `Print Grammar foo` continues to look only for `foo`.

Opinions?

**Comment by ppedrot** [comment]
I'd favour the second option. I doesn't look like a very good idea to have super-global entries that have a name system based on strings. For custom entries, we could use both a different command, and a path-based naming scheme.

**Comment by jashug** [comment]
What is the conclusion for this PR? Should I just remove the printing of `pattern:myconstr`? Should I add a new vernacular? I'm also happy to let one of you two take over.

**Comment by herbelin** [comment]
> What is the conclusion for this PR? Should I just remove the printing of pattern:myconstr? Should I add a new vernacular? I'm also happy to let one of you two take over.

Yes, my understanding was also that the conclusion is to remove the printing of `pattern:myconstr` and to add a new `Print Grammar Custom myconstr` for printing `constr:myconstr`. I'm unsure of what @ppedrot means by "path-based naming scheme" though (maybe `Print Grammar constr:myconstr`?).

**Comment by ppedrot** [comment]
@herbelin I meant that custom grammar entries should be qualified, so that `Print Grammar Custom` takes a qualid as an argument.

**Comment by herbelin** [comment]
>  I meant that custom grammar entries should be qualified, so that Print Grammar Custom takes a qualid as an argument.

Good idea, indeed.

**Comment by jashug** [comment]
I pushed an update that uses `Print Custom Grammar myconstr` to inspect the custom entry `myconstr`.

**Comment by Zimmi48** [comment]
Does the new solution really fixes #9681 or only the wish it contained?
The documentation for the generic `Print Grammar` command disappears so it seems that it should go back to checking that the argument is `constr`, `pattern`, or `tactic`, as is suggested in #9681.

**Comment by Zimmi48** [comment]
And since in the end this PR introduces a new command, I would add a changelog entry, I guess.

**Comment by jashug** [comment]
Added changelog entry, and error on unrecognized grammar entries.

**Comment by cpitclaudel** [comment]
Nice work :+1: 
By the way, do we even have a way to print Coq's grammars in full?  For example, `Print Grammar Tactic` refers to `failkw` and `match_key`, but I don't know any way to print the corresponding grammar entries.

**Comment by ejgallego** [comment]
> By the way, do we even have a way to print Coq's grammars in full? For example, `Print Grammar Tactic` refers to `failkw` and `match_key`, but I don't know any way to print the corresponding grammar entries.

This is a TODO, doable since #8945 , there should be an open bug about it already.

**Comment by ejgallego** [comment]
> there should be an open bug about it already.

I couldn't find it but sure it has been discussed many times.

**Review by ejgallego — COMMENTED** [review]
Seems good @jashug , however I wonder if you should extend `PrintGrammar` and `pr_grammar` instead of adding a new constructor / toplevel function.

What do you think?

**Comment by jashug** [comment]
By wrapping the entry name in a `type entry = DefaultEntry of string | CustomEntry of string` (where to put it? layering seems a bit tricky), and using that as the input to both `PrintGrammar` and `pr_grammar`? 
That would work, and would unify the handling in `vernacentries.ml`, but I don't see much shared implementation in `metasyntax.ml` in the current state.

Both ways seem roughly as complicated to me, and I don't have a strong opinion either way.

**Comment by jashug** [comment]
There is also the approach to have parsing return `PrintGrammar ("constr:"^name)`, and for `pr_grammar` to continue to try searching for entries of the given name, failing only if it finds none such. That probably disturbs the least code, but moves the string-typed `"constr:"^name` very far from the notation system where it is used, and probably will need to be changed to something closer to this PR if qualified entries are ever implemented.

File: vernac/metasyntax.ml [hunk 1]
```diff
@@ -83,7 +83,10 @@ let pr_grammar = function
       pr_entry Pvernac.Vernac_.gallina ++
       str "Entry gallina_ext is" ++ fnl () ++
       pr_entry Pvernac.Vernac_.gallina_ext
-  | name -> pr_registered_grammar name
+  | _ -> user_err Pp.(str "Unknown grammar entry." ++ spc()
+                      ++ str "Use Print Custom Grammar to inspect custom entries.")
```
Comment (Zimmi48) [inline vernac/metasyntax.ml]: Perfect :+1: That's what I was asking for!

**Review by Zimmi48 — APPROVED** [review]

**Comment by ejgallego** [comment]
> Both ways seem roughly as complicated to me, and I don't have a strong opinion either way.

I guess the real question is whether we think in the future "grammar printing" should be a single, unified command, or we really think that these are really different. If the former, having a single AST / entry point helps IMHO code readability.

Anyways that was just a suggestion, from my part I'd happy to take the solution you deem best.

**Review by herbelin — DISMISSED** [review]
This is very good, thanks. Note a new probable problem with `Print Grammar tactic` though (originating in  7e96257,). The `Unknown grammar entry` should be raised when `find_grammars_by_name` returns `[]` in `pr_registered_grammar`, not in `pr_grammar`. The `Not_found` in `pr_registered_grammar` is meaningless since 7e96257.

**Comment by jashug** [comment]
Good catch, `Print Grammar tactic` was indeed regressing. I also removed the `Not_found` case from `pr_registered_grammar`.
It feels like the custom entries should be registered so that `find_grammars_by_name` works without prepending `constr:`, but I don't understand this code well enough to try that approach.

File: vernac/metasyntax.ml (hunk 1 above)
Comment (jashug) [reply vernac/metasyntax.ml]: Note that this change got reverted (it was clobbering `Print Grammar tactic`), but there is still a check in `pr_registered_grammar`.

**Comment by herbelin** [comment]
> It feels like the custom entries should be registered so that find_grammars_by_name works without prepending `constr:`

We could do that. What I was afraid of was to mix the namespace for custom grammars with the couple of grammar already registered for tactics.

But after all, custom grammars could also be used in principle in `Tactic Notation`, so we could use the same name space (and thus get rid of the `constr:` prefix)...

**Comment by ejgallego** [comment]
@herbelin is the current version OK for you ?

**Comment by herbelin** [comment]
> @herbelin is the updated version OK for you ?

Yes, this looks very good.

I summarize otherwise two questions for possible further work:
- eventually use qualid for custom entries
- possibly put custom entries in the same name space as tactic entries
