### PR TITLE
Properly pass the Ltac2 notation level to the gramlib API.

### LINKED ISSUE #11866: Ltac2 Notations do not respect precedence
It is not entirely clear from the documentation, but it appears that `Ltac2 Notation ... : n := ...` is a way to set the parsing precedence of the notation. This does not seem to work, however:
```coq
From Ltac2 Require Import Ltac2 Message.

Ltac2 Notation "foo" : 2 := print (of_string "a").
Ltac2 Notation "foo" : 1 := print (of_string "b").

Goal True.
foo.
```
This prints `b`, while I would expect it to print `a`. Is this a bug or am I using it wrong?

#### Coq Version

The Coq Proof Assistant, version 8.12+alpha (March 2020)
compiled on Mar 20 2020 10:37:25 with OCaml 4.09.0

### PR DESCRIPTION
**Pull request by ppedrot**
For some reason I was confusing the position and the level in the previous version of the code.

I am leaving this as a draft for now since we may seize the opportunity to have a richer level language for Ltac2 notations.

Fixes #11866: Ltac2 Notations do not respect precedence.

- [x] Added / updated test-suite
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by ppedrot** [comment]
> I am leaving this as a draft for now since we may seize the opportunity to have a richer level language for Ltac2 notations.

I changed my mind since we can alway introduce a backwards-compatible syntax using numbers for the built-in levels and combinators for user-defined levels. The camlp5 API actually provides something similar with the AFTER / BEFORE / FIRST / LAST / LIKE combinators so it's only a matter of exposing those constructs.

**Comment by ppedrot** [comment]
@JasonGross would you assign?

File: user-contrib/Ltac2/tac2entries.ml [hunk 1]
```diff
@@ -754,7 +754,15 @@ let register_notation ?deprecation ?(local = false) tkn lev body = match tkn, le
   let ids = List.fold_left fold Id.Set.empty entries in
   (* Globalize so that names are absolute *)
   let body = Tac2intern.globalize ids body in
-  let lev = match lev with Some _ -> lev | None -> Some 5 in
+  let lev = match lev with
+  | Some n ->
+    let () =
+      if n < 0 || n > 6 then
+        user_err (str "Notation levels must range between 0 and 6")
```
Comment (JasonGross) [inline user-contrib/Ltac2/tac2entries.ml:761]: Should this error message be documented?

**Comment by JasonGross** [comment]
I can assign if you'd like me to, but I don't feel competent to review the code changes and the current test in the test-suite is not adequate to convince me that the levels are working as intended.

If you can design some test that will fail if the levels are not correctly associated, such that I no longer need to care what the code is doing, I'd be happy to take this.

Alternatively, if you want to merge it under the premise that what's going on is not worse than what was happening before, I can merge it from that perspective too.

File: user-contrib/Ltac2/tac2entries.ml (hunk 1 above)
Comment (ppedrot) [reply user-contrib/Ltac2/tac2entries.ml:761]: I have added an entry in the refman.

**Comment by ppedrot** [comment]
> If you can design some test that will fail if the levels are not correctly associated

Not sure how to do that. Now that we can print the Ltac2 grammar we might try to rely on an output test but it'd be very fragile.

**Comment by JasonGross** [comment]
> > If you can design some test that will fail if the levels are not correctly associated
> 
> Not sure how to do that. Now that we can print the Ltac2 grammar we might try to rely on an output test but it'd be very fragile.

Add some Ltac2 notations that parse into an embedded AST and check for equality.  e.g.,
```coq
Ltac2 Type tree := [ Leaf | Node (tree * tree) ]
Ltac2 Notation tactic4(a) "node456" tactic6(b) : 5 := node (a, b).
```
or something like that, and then do stuff like `Leaf node456 Leaf node456 Leaf` and make sure that the tree you get is the one that you expect.  Granted, this seems pretty tedious, so maybe it's worth writing a small script to write the Ltac2 for you to test all of the expected outputs.

**Comment by SkySkimmer** [comment]
You can do something with types. eg in ocaml
~~~ocaml
let f (+) x y z = (x + y) + z
(* f : ('a -> 'b -> 'a) -> 'a -> 'b -> 'b -> 'a *)
 
let f (+) x y z = x + (y + z)
(* f : ('a -> 'b -> 'b) -> 'a -> 'a -> 'b -> 'b *)
~~~

File: doc/sphinx/proof-engine/ltac2.rst [hunk 2]
```diff
@@ -1251,6 +1251,10 @@ Notations
 
    This command supports the :attr:`deprecated` attribute.
 
+   .. exn:: Notation levels must range between 0 and 6.
+
+      The level of a notation must be an integer between 0 and 6 included.
```
Comment (jfehrle) [inline doc/sphinx/proof-engine/ltac2.rst:1256]:
```suggestion
      The level of a notation must be an integer between 0 and 6 inclusive.
```

File: doc/changelog/05-tactic-language/14094-ltac2-notation-level-fix.rst [hunk 3]
```diff
@@ -0,0 +1,6 @@
+- **Fixed:**
+  Ltac2 notations now correctly take into account the level
+  they have been ascribed to
```
Comment (jfehrle) [inline doc/changelog/05-tactic-language/14094-ltac2-notation-level-fix.rst:3]:
```suggestion
  Ltac2 notations now correctly take into account their assigned level.
```

A bit unusual to use "ascribed" here--not such a common word.

**Review by jfehrle — COMMENTED** [review]
Wording suggestions

**Comment by ppedrot** [comment]
@JasonGross I am too lazy to write this kind of test when 1. it's unlikely to break again because of this API and 2. there are other Ltac2 parsing issues lurking around that were not yet observed because parsing has an explosive combinatoric flavour to it. I have added the test you suggested in the bug report, that was failing before and is now properly working. If by a very unfortunate mistake we use the wrong API again it will be caught anyways, the rest seems like we would need a complete parsing test suite for the language which is kind of unrelated to the PR.

**Review by JasonGross — APPROVED** [review]

**Comment by JasonGross** [comment]
@coqbot merge now

**Comment by JasonGross** [comment]
@coqbot merge now
