### PR TITLE
Followup of #17993, fixes #18239: anomaly on triggering conditions for simpl on encapsulated mutual fixpoints

### LINKED ISSUE #18239: Error: Anomaly "Not an unfoldable reference."
Within the past four days or so (since the merging of https://github.com/coq/coq/pull/18014), it seems there's been a regression that introduced an anomaly into fiat-crypto-legacy:
```
File "./src/Experiments/SimplyTypedArithmetic.v", line 7059, characters 4-350:
Error: Anomaly "Not an unfoldable reference."
Please report at http://coq.inria.fr/bugs/.
```

### PR DESCRIPTION
**Pull request by herbelin**
We ensure that there are enough arguments in the original applied constant, in addition to ensuring enough arguments in the constant that immediately surrounds a global mutual fixpoint.

In addition to fixing bug #18239, introduced in #17993, this fixes also a similar bug anterior to #17993.

Fixes #18239

- [x] Added / updated **test-suite**.

### CODE REVIEW

File: pretyping/tacred.ml [hunk 1]
```diff
@@ -321,11 +321,11 @@ let compute_consteval allowed_reds env sigma ref u =
           let nbfix = Array.length lv in
           (if nbfix = 1 then
             let names = [|Some (ref,u)|] in
-            try check_fix_reversibility env sigma ref u labs l names fix
+            try check_fix_reversibility env sigma ref u n labs l names fix
             with Elimconst -> NotAnElimination
           else
-            let labs, l, names = invert_names allowed_reds env sigma lastref lastu names i in
-            try check_fix_reversibility env sigma lastref lastu labs l names fix
+            let labs', l', names = invert_names allowed_reds env sigma lastref lastu names i in
```
Comment (SkySkimmer) [inline pretyping/tacred.ml:327]: Why '?

File: test-suite/success/simpl.v
Comment (SkySkimmer) [inline test-suite/success/simpl.v:1]: Should we be checking the results in the new tests or do we only care that it doesn't fail?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

File: pretyping/tacred.ml (hunk 1 above)
Comment (herbelin) [reply pretyping/tacred.ml:327]: Because there are other `labs` and `l` and it seems clearer to name differently the labs/l of the original name (e.g. boo in your example) and the labs/l of the immediate name of the fixpoint (e.g. even in your example), especially due to the fact that the `n` passed on the next line is the length of the initial `labs`.

File: test-suite/success/simpl.v
Comment (herbelin) [reply test-suite/success/simpl.v:1]: Right, we could check.

**Comment by herbelin** [comment]
@SkySkimmer: I renamed the OCaml variables in a way which I hope is clearer. I added new tests, checked the result of simpl, and documented the behavior (using a `match goal` makes the reading of the tests difficult but I did not want to abuse too much of the output test-suite directory). I added two items to the changelog. If ok for you, we can restart the full CI (and check it is still green).

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Tried fiat crypto locally, Curves/Weierstrass/AffineProofs worked fine with `src/Curves/Weierstrass/AffineProofs.vo (real: 216.29, user: 373.41, sys: 1.75, mem: 2086324 ko)`
let's rerun and see

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
I retried 2 times and all 3 jobs failed the same way (`Curves/Weierstrass/AffineProofs` fails and seems to take a long time to do so, eg https://gitlab.inria.fr/coq/coq/-/jobs/3551339
~~~
COQC src/Curves/Weierstrass/AffineProofs.v
Finished transaction in 1.519 secs (1.385u,0.127s) (successful)
Command terminated by signal 9
src/Curves/Weierstrass/AffineProofs.vo (real: 3379.13, user: 6.29, sys: 74.80, mem: 1275872 ko)
~~~
)

cc @JasonGross @andres-erbsen

**Comment by SkySkimmer** [comment]
also why is `real` so much greater than `user + sys`

**Comment by SkySkimmer** [comment]
It did also fail on master in a similar way https://gitlab.inria.fr/coq/coq/-/jobs/3555681

**Comment by SkySkimmer** [comment]
Got it to pass after another retry, with the failures on master I gurss it's an unrelated problem.

@coqbot merge now
