### PR TITLE
Fix incorrect error locations with `}` in coqtop

### LINKED ISSUE #19355: Strange error location in coqtop
### Description of the problem

The error location in `coqtop` (didn't test in other interaction mode) usually gives the error location with character location *inside the last command*, for instance:

```coq
Unnamed_thm < rewrite toto.
Toplevel input, characters 8-12:
> rewrite toto.
>         ^^^^
Error: The variable toto was not found in the current environment.
```
the position (8-12) refers to current command only. But I found at least one situation where the location is completely wrong (probably counting from the "beginning"?)

```
Welcome to Coq dell-5750-Matafou:/home/courtieu/coq/v8.20/_build/default,v8.20 (a27916b9cff870b2a8b1819adb4a1a7dd05c74fe)

Coq < Goal True.
1 goal
  
  ============================
  True

Unnamed_thm < }
Toplevel input, characters 11-12:
Error: The proof is not focused

Unnamed_thm < }
Toplevel input, characters 13-14:
Error: The proof is not focused

Unnamed_thm < 
```

Each attempt to write the wrong command again gives a increasing location.

We would like to rely on his poosition information to locate error reliably in ProofGeneral, so this is a bit annoying.
I 

### Small Coq file to reproduce the bug

```coq
Goal True.
}
```

### Version of Coq where this bug occurs

8.20

### Last version of Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #19355

### CODE REVIEW

**Review by gares — APPROVED** [review]

File: parsing/cLexer.ml [hunk 1]
```diff
@@ -723,7 +723,11 @@ let rec next_token ~diff_mode ttree loc s =
       Stream.junk () s;
       let ep = Stream.count s in
       let t,new_between_commands =
-        if !between_commands then (KEYWORD (String.make 1 c), set_loc_pos loc bp ep), true
+        if !between_commands then begin
+          (* peek to force reading a following newline, cf #19355 *)
+          let _ = Stream.peek () s in
```
Comment (silene) [inline parsing/cLexer.ml:728]: Does it work if the user wrote something before the newline, e.g., a whitespace?

Comment (SkySkimmer) [reply parsing/cLexer.ml:728]: no
same as `.`

Comment (ejgallego) [reply parsing/cLexer.ml:728]: What will `Stream.peek` do if } is the last token on the stream?

Comment (gares) [reply parsing/cLexer.ml:728]: It returns None.

Said that the code calls `input`, instead of `really_input`, so it looks fishy

Comment (ejgallego) [reply parsing/cLexer.ml:728]: I couldn't come up with a case where this would be a problem, but indeed I'm not sure doing the peek here is a good idea; would be good if that could be moved to coqtop.

Comment (ejgallego) [reply parsing/cLexer.ml:728]: > What will this do if } is the last token on the stream?

Answering to my own question, it will always return `None`.

Comment (silene) [reply parsing/cLexer.ml:728]: > same as `.`

Ouch, I did not know location reporting was so broken. I just tested it and it is indeed quite impressive.

Comment (SkySkimmer) [reply parsing/cLexer.ml]: pushed version which does the peek in coqloop resynch_buffer and fixes the location when the command is followed by spaces

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by Matafou** [comment]
FTR proofgeneral never used this information until now (the ascii underlining being much more robust). This is probably why this bug went unnoticed for so long.
Side note: since ascii underlining code is so robust why not reuse its code?

**Comment by ppedrot** [comment]
I'm assigning and will merge soon if nobody complains.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by Matafou** [comment]
Thanks for this. Will this fix make it to 8.20 release or 8.21? No real big deal, just for documenting PG workaround.

**Comment by SkySkimmer** [comment]
8.21
