### PR TITLE
Fixes #15455: regression due to #14606 in computing best implicit arguments signature for projections

### LINKED ISSUE #15455: Serious unification errors in 8.15+rc1 and dev; not seen in 8.14.1
The error itself:

```
File "/Users/artagnon/Downloads/minimized.v", line 56, characters 16-26:
Error:
In environment
PartialBox :
forall n : nat, nat -> forall csp : Type, PartialBoxBase n csp -> Type
n : nat
p : nat
csp : Type
PB : PartialBoxBase n csp
box : p <= n -> csp -> Type
subbox :
forall (q : nat) (Hp : p.+1 <= q.+1) (Hq : q.+1 <= n),
side -> forall D : csp, box (↓ (Hp ↕ Hq)) D -> PB.(box') (Hp ↕ Hq) D
q : nat
r : nat
Hpr : p.+2 <= r.+2
Hr : r.+2 <= q.+2
Hq : q.+2 <= n
ε : side
ω : side
D : csp
d : box (↓ (⇓ Hpr ↕ ↓ (Hr ↕ Hq))) D
The term "Hpr ↕ Hr" has type "p.+2 <= q.+2" while it is expected to have type
 "p.+2 <= n" (cannot unify "le' p0 q.+2" and "le' p0 n").
```

The reduced example (please help fix coq/bot#183):

```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-w" "-deprecated-native-compiler-option,-native-compiler-disabled" "-R" "." "Top" "-top" "bug" "-native-compiler" "ondemand") -*- *)
(* File reduced by coq-bug-minimizer from original input, then from 164 lines to 55 lines, then from 60 lines to 54 lines *)
(* coqc version 8.16+alpha compiled with OCaml 4.11.2
   coqtop version 8.14.1
   Expected coqc runtime on this file: 0.272 sec *)
Set Printing Projections.
Set Primitive Projections.
Set Warnings "-notation-overridden".
Notation "x .+1" := (S x) (at level 1, left associativity, format "x .+1").
Notation "x .+2" := (S (S x)) (at level 1, left associativity, format "x .+2").

Inductive le' (n : nat) : nat -> SProp :=
  | le_refl' : n <= n
  | le_S_up' : forall {m : nat}, n <= m -> n <= m.+1
  where "n <= m" := (le' n m) : nat_scope.

Definition le n m := forall p, p <= n -> p <= m.
Infix "<=" := le : nat_scope.
Definition le_trans {n m p} (Hnm : n <= m) (Hmp : m <= p) : n <= p.
Admitted.

Infix "↕" := le_trans (at level 45).

Theorem le_S_down {n m} (Hnm : n.+1 <= m) : n <= m.
Admitted.

Notation "↓ p" := (le_S_down p) (at level 40).

Theorem lower_S_both {n m} (Hnm : n.+1 <= m.+1) : n <= m.
Admitted.

Notation "⇓ p" := (lower_S_both p) (at level 40).

Universe l'.
Universe l.

Inductive side := L | R.

Record PartialBoxBase (n : nat) (csp : Type@{l'}) := {
  box' {p} (Hp : p.+1 <= n) : csp -> Type@{l} ;

  box'' {p} (Hp : p.+2 <= n) : csp -> Type@{l} ;
  subbox' {p q} {Hp : p.+2 <= q.+2} (Hq : q.+2 <= n) (ε : side) {D : csp} :
    box' (↓ (Hp ↕ Hq)) D -> box'' (Hp ↕ Hq) D;
}.

Arguments box' {n csp} _ {p} Hp D.
Arguments subbox' {n csp} _ {p q Hp} Hq ε {D} d, {n csp} _ {p q} Hp Hq ε {D} d.

Record PartialBox (n p : nat) (csp : Type@{l'}) (PB : PartialBoxBase n csp) := {
  box (Hp : p <= n) : csp -> Type@{l} ;
  subbox {q} {Hp : p.+1 <= q.+1} (Hq : q.+1 <= n) (ε : side) {D : csp} :
  box (↓ (Hp ↕ Hq)) D -> PB.(box') (Hp ↕ Hq) D;
  cohbox {q r} {Hpr : p.+2 <= r.+2} {Hr : r.+2 <= q.+2} {Hq : q.+2 <= n}
  {ε : side} {ω : side} {D: csp} (d : box (↓ (⇓ Hpr ↕ (↓ (Hr ↕ Hq)))) D) :
  PB.(subbox') (Hpr ↕ Hr) Hq ε (subbox (Hp := ⇓ Hpr) (↓ (Hr ↕ Hq)) ω d) =
  (PB.(subbox') Hpr (Hr ↕ Hq) ω (subbox (Hp := ↓ (Hpr ↕ Hr)) Hq ε d));
}.
```

I'll run the bisect overnight, and report the bad commit in the morning.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** fix
 
In enhancement #14606, the main argument was forgotten in computing the number of given arguments in the case of multiple signatures for implicit arguments of a projection.

Fixes / closes #15455.

- [X] Added / updated **test-suite**.

I guess it does not need a changelog if it can go to 8.15.0.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

File: interp/impargs.ml [hunk 1]
```diff
@@ -792,7 +792,7 @@ let select_impargs_size_for_proj ~nexpectedparams ~ngivenparams ~nextraargs impl
     (* Force the main argument to be explicit *)
     (nimps1, imps1 @ [None], imps2)
   in
-  let nallgivenargs = ngivenparams + nextraargs in
+  let nallgivenargs = ngivenparams + nextraargs + 1 in
```
Comment (artagnon) [inline interp/impargs.ml:795]: Ouch; so it turned out to be a simple off-by-one error? 😅
