### PR TITLE
Fix #9994: `revert dependent` is extremely slow.

### LINKED ISSUE #9994: `revert dependent` is extremely slow when the type of the hyp being reverted is expensive to typecheck
#### Description of the problem

Here is a case where `revert dependent x` in a context containing only `x` takes 30 seconds, while `revert x` is instantaneous:

```coq
Fixpoint fact (n : nat) :=
  match n with
  | O => 1
  | S n' => fact n' * S n'
  end.

Definition slow_true := Nat.eqb (fact 10) (fact 10).

Definition a (T : Type) (x : T) := True.

Goal True.
  let c := constr:(I : a (true = slow_true) (eq_refl true <: true = slow_true)) in
  pose proof c as H.
  Time revert H. (* Finished transaction in 0. secs (0.u,0.s) (successful) *)
  Undo.
  Time revert dependent H. (* Finished transaction in 29.462 secs (27.772u,0.012s) (successful) *)
```

Here is a faster implementation of `revert dependent`:

```coq
Ltac has_body x :=
  match goal with
  | [ H : _ |- _ ] => constr_eq x H
  | _ => fail 1 x "has no body"
  end.

Ltac revert_dependent x :=
  (tryif has_body x then clearbody x else idtac);
  move x at bottom;
  repeat (let H := lazymatch goal with H : _ |- _ => H end in
          (tryif constr_eq H x then fail else idtac); revert H);
  revert x.

Tactic Notation "revert" "dependent" hyp(h) := revert_dependent h.
```

Note that `generalize x` takes about at long as `revert dependent x`, so perhaps `generalize` and `generalize dependent` could use a fast-path for when the term is a single identifier?

cc @ppedrot

#### Coq Version

8.9.0

### PR DESCRIPTION
**Pull request by ppedrot**
We add a fast path when generalizing over variables.

Fixes #9994

### CODE REVIEW

**Comment by vbgl** [comment]
This seems to break CompCert. Sounds annoying…

**Comment by ppedrot** [comment]
This looks like a bug in the tactic abstracting the dependent variable missing an occurrence. The observed error is a delayed one, as the goal is ill-typed by that time.

**Comment by ppedrot** [comment]
... and ultimately, it seems that the abstraction function is missing instances in the hidden type of branches of some pattern-matching...

**Comment by ppedrot** [comment]
Here is a reduced test-case:
```
Require Import Program.

Axiom I : Type.

Inductive S : Type := NT : I -> S.

Axiom F : S -> Type.

Axiom G : forall (s : S), F s -> Type.

Section S.

Variable init : I.
Variable my_s : F (NT init).

Inductive foo : forall (s: S) (hole_sem: F s), Type :=
| Foo : foo (NT init) my_s.

Goal forall
  (n : I) (s : F (NT n)) (ptz : foo (NT n) s) (pt : G (NT n) s) (x : unit),
match 
  match x with tt => tt end
with
| tt =>
    match
      match ptz in foo x s return (forall _ : G x s, unit) with
      | Foo => fun _ : G (NT init) my_s => tt
      end pt
    with
    | tt => False
    end
end.
Proof.
dependent destruction ptz.
Fail match goal with [ |- ?P ] => let t := type of P in idtac end.
```
With this PR, the ill-typed goal produced is
```
init : I
my_s, s : F (NT init)
ptz0 : foo (NT init) s
x : @JMeq (foo (NT init) s) Foo (foo (NT init) s) ptz0
______________________________________
forall (pt : G (NT init) s) (x0 : unit),
match match x0 with
      | tt => tt
      end with
| tt =>
    match
      match ptz0 in (foo x1 s0) return (forall _ : G x1 s0, unit) with
      | Foo => fun _ : G (NT init) s => tt
      end pt
    with
    | tt => False
    end
end```
whereas it was before
```
init : I
my_s : F (NT init)
______________________________________
G (NT init) my_s ->
forall x : (),
match match x with
      | () => ()
      end with
| tt => False
end
```

**Comment by ppedrot** [comment]
Note the necessary interaction of the section hypothesis with the variable generalization. The usual suspect...

**Comment by ppedrot** [comment]
I've added a check to typecheck when the abstracted variable is from the section. This solves the reduced example, hopefully CompCert will go through as well.

**Comment by ppedrot** [comment]
@vbgl looks like it's fine now.

**Review by JasonGross — DISMISSED** [review]
Please add your reduced example as a test-case to the test-suite; it seems worth tracking.

File: tactics/tactics.ml [hunk 1]
```diff
@@ -2863,17 +2863,22 @@ let generalize_dep ?(with_let=false) c =
...
   let cl' = it_mkNamedProd_or_LetIn (pf_concl gl) to_quantify in
-  let body =
-    if with_let then
-      match EConstr.kind sigma c with
-      | Var id -> id |> (fun id -> pf_get_hyp id gl) |> NamedDecl.get_value
-      | _ -> None
-    else None
+  let is_var, body = match EConstr.kind sigma c with
+  | Var id ->
+    let body = id |> (fun id -> pf_get_hyp id gl) |> NamedDecl.get_value in
```
Comment (vbgl) [inline tactics/tactics.ml]: What is this strange pattern? Can’t you simply write the following?

~~~
let body = pf_get_hyp id gl |> NamedDecl.get_value in
~~~

File: tactics/tactics.ml [hunk 2]
```diff
@@ -2863,17 +2863,22 @@ let generalize_dep ?(with_let=false) c =
...
+    let is_var = Option.is_empty body && not (List.mem id init_ids) in
+    if with_let then is_var, body
+    else is_var, None
```
Comment (vbgl) [inline tactics/tactics.ml]: Suggestion (instead of the three lines above):

~~~
Option.is_empty body && not (List.mem id init_ids),
if with_let then body else None
~~~

File: tactics/tactics.ml (hunk 1 above)
Comment (ppedrot) [reply tactics/tactics.ml]: I didn't write that, that's code I moved around. But indeed this is strange.

File: tactics/tactics.ml (hunk 2 above)
Comment (ppedrot) [reply tactics/tactics.ml]: I'm a crypto-C developer, I don't like to abuse the expression-based semantics...

File: tactics/tactics.ml (hunk 1 above)
Comment (ppedrot) [reply tactics/tactics.ml]: Rewritten.

File: tactics/tactics.ml (hunk 2 above)
Comment (vbgl) [reply tactics/tactics.ml]: No problem. Thanks.

**Review by vbgl — APPROVED** [review]

**Comment by vbgl** [comment]
Thanks. I’ll merge as soon as CI completes.
