### PR TITLE
Fix #8922 (uncaught pp_diff exception)

### LINKED ISSUE #8922: Uncaught exception Pp_diff.Diff_Failure
#### Version
master

#### Operating system
Fedora

#### Description of the problem

I tried the new feature that colours the changes in the goal, and encountered the following bug:
```
Lemma eza : True.
Proof.
  eassert(_).
  refine (fun _ => _).
```

```
Anomaly
"Uncaught exception Pp_diff.Diff_Failure("Unable to match goals betwen old and new proof states (6)")."
Please report at http://coq.inria.fr/bugs/.
```

### PR DESCRIPTION
**Pull request by jfehrle**
Fixed several problems exposed by #8922.  Without the change, diffs will omit some output lines when displaying the proof context, making the diff unacceptably unreliable.  While users can turn off diffs, this fix should go into 8.9.

Get hyps and goal the same way Printer does; don't omit info
Allow for new goals that don't map to old goals
Include background_goals in all_goals return value
Fix incorrect change to raw diffs in shorten_diff_span

**Kind:** bug fix

Fixes #8922

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Looks OK to me.

File: ide/idetop.ml [hunk 1]
```diff
@@ -212,25 +212,19 @@ let goals () =
...
-      in
 
       let process_goal_diffs nsigma ng =
         let open Evd in
-        let og = map_goal_for_diff ng in
         let og_s = match oldp with
         | Some oldp ->
           let (_,_,_,_,osigma) = Proof.proof oldp in
-          Some { it = og; sigma = osigma }
+          (try Some { it = Evar.Map.find ng diff_goal_map; sigma = osigma } with Not_found -> None)
```
Comment (herbelin) [inline ide/idetop.ml]: Hi @jfehrle, by curiosity, is this `try with Not_found` needed because you want to possibly parse strings of the form `?X = ?Y` with unbound `?X` and `?Y`, or is this `try` needed to fix #8922?

Comment (jfehrle) [reply ide/idetop.ml]: Short answer: no, this is not related to parsing.

Proof_diffs.make_goal_map uses a heuristic to match new goals to old goals by looking at the old and new proof objects, which works fine for the cases I tried.  One of the problems uncovered by this bug report is a goal that could not be matched.  In the example below (after the `refine`), `?Goal1` doesn't appear in the `Show Proof`, so it couldn't be matched.  My initial fix was to add the `try with Not_found` here, which would treat any such goals as new, which would show them as new, fully highlighting them.

A day or two later I discovered that Proof.all_goals doesn't include shelved goals.  Including those goals fixed the matching problem of this bug in a cleaner way.  Although `?Goal1` seems a bit of a strange corner case to me (not appearing in the proof object at all), I'm not sure that change covers all the possibilities.

I think I will change the code so it raises Diff_failure instead as a way of surfacing other unhandled cases if they indeed exist.  (Note that users can easily work around such anomalies by turning off diffs for the proof steps getting anomalies.)

```
eza < Show Proof.
(let X := fun H : ?Goal0 => ?Goal2@{y:=H} in ?Goal)

eza < Show Existentials.
Existential 1 = ?Goal : [X : forall x : ?Goal0, ?Goal1 |- True]
Existential 2 = ?Goal0 : [ |- Type] (shelved)
Existential 3 = ?Goal1 : [x : ?Goal0 |- Type] (shelved)
Existential 4 = ?Goal2 : [y : ?Goal0 |- ?Goal1@{x:=y}]
```

Comment (herbelin) [reply ide/idetop.ml]: OK, thanks for the explanation.

**Review by ppedrot — APPROVED** [review]
The change to Proof is OK and minor btw.

**Comment by herbelin** [comment]
> @herbelin and @ejgallego, which one of you will do the merge?

I let @ejgallego decide.

**Comment by ejgallego** [comment]
> I let @ejgallego decide.

@herbelin I didn't have time to look into this PR sadly, please feel free to assign it.

**Comment by herbelin** [comment]
> please feel free to assign it.

OK.

I did not look at all detals either but this is a fix which looks ok. So, I'll merge on Wednesday if no comments by then.

**Comment by jfehrle** [comment]
Thank you for the review, gentlemen.

**Comment by herbelin** [comment]
And thank you for your work!
