### PR TITLE
coqtop: stop on Sys_blocked_io

### LINKED ISSUE #10918: Anomaly "Uncaught exception Sys_blocked_io."
#### Description of the problem

At least in `bash`, if the `stdin` is in the non-blocking mode (e. g. from the previous running process in the shell), `coqtop` will die upon its start, flooding with messages
```
Error: Anomaly "Uncaught exception Sys_blocked_io."
Please report at http://coq.inria.fr/bugs/.
```

The easy real-world way to reproduce is to start `coqtop` after forcibly `SIGKILL`ing Erlang REPL (start `erl` and press `^c a`).

More info (bash): https://lists.gnu.org/archive/html/bug-bash/2017-01/msg00039.html

#### Coq Version

8.9.1, 8.10.0, master (and likely many many more)

#### Note

This can be WONTFIX.  I’m posting the issue for the record and to save time for the next person who may encounter this (not very obvious) behaviour.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #10918

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
That seems fine to me, the situation seems marginal enough as not to do a more invasive fix.

**Review by ejgallego — CHANGES_REQUESTED** [review]
It seems Windows doesn't like this OS-specific stuff:

```
Fatal error: exception Unix.Unix_error(40, "unix_clear_nonblock", "")
```

maybe we should just mark the original bug "invalid".

**Comment by llelf** [comment]
> maybe we should just mark the original bug "invalid".

But there is nothing “invalid” about it. However, as I said in the PR,  not fixing it is totally fine.

> This can be WONTFIX. I’m posting the issue for the record and to save time for the next person who may encounter this (not very obvious) behaviour.

**Comment by SkySkimmer** [comment]
>It seems Windows doesn't like this OS-specific stuff

Maybe @xavierleroy (as author of https://github.com/ocaml/ocaml/blob/trunk/otherlibs/win32unix/nonblock.c) will know why?

**Comment by ejgallego** [comment]
Maybe you could guard the call with `Sys.os_type` for now?

**Comment by gares** [comment]
We could also not fix #10918 . It is not even clear it is a Coq bug.

My understanding is that a program you run before Coq leaves the terminal in a messy state. It is not the role of Coq to repair that or be resilient to a non-blocking stdin situation, IMO.

**Comment by ejgallego** [comment]
> We could also not fix #10918 . It is not even clear it is a Coq bug.
> 
> My understanding is that a program you run before Coq leaves the terminal in a messy state. It is not the role of Coq to repair that or be resilient to a non-blocking stdin situation, IMO.

Yeah I agree, on the other hand given that is a one-line workaround in the init code the cost of adding it doesn't seem a lot I think. Alternatively we could just check for the flag and abort.

**Comment by SkySkimmer** [comment]
Here is a new attempt, instead of clearing the flag we just catch the exception and fail gracefully.

File: toplevel/coqloop.ml [hunk 1]
```diff
@@ -469,6 +469,16 @@ let rec vernac_loop ~state =
...
+  | Sys_blocked_io ->
+    (* the parser doesn't like nonblocking mode, cf #10918 *)
+    let msg =
+      Pp.(str "Uncaught exception Sys_blocked_io." ++ spc() ++
+          str "If stdin is in non-blocking mode please reset it to blocking mode,"
+          ++ spc() ++ str "otherwise please report at "
+          ++ str Coq_config.wwwbugtracker ++ str".")
+    in
+    TopErr.print_error_for_buffer Feedback.Error msg top_buffer;
+    exit 1
```
Comment (ejgallego) [inline toplevel/coqloop.ml]: Should we instead register this exception printer in the regular way ?

Comment (SkySkimmer) [reply toplevel/coqloop.ml]: I don't think this message makes sense elsewhere.

Comment (ejgallego) [reply toplevel/coqloop.ml]: We can register it this module then?

Comment (ejgallego) [reply toplevel/coqloop.ml]: I don't think having a special case is worth it, at some point errors should be sealed so the less special cases we have the better, specially when this error is so esoteric.

Comment (SkySkimmer) [reply toplevel/coqloop.ml]: We need a special case to exit, otherwise it will go back in the loop.

Comment (ejgallego) [reply toplevel/coqloop.ml]: The message you print makes me think this should be an anomaly?

Comment (ejgallego) [reply toplevel/coqloop.ml]: But indeed we have no way yet to register those.

Comment (SkySkimmer) [reply toplevel/coqloop.ml]: It's only an anomaly if it was triggered in some way other than stdin being nonblocking. I don't know if that's possible.

Comment (ejgallego) [reply toplevel/coqloop.ml]: No idea; looking at the code it can use some refactoring; I'll push another PR.

**Review by ejgallego — APPROVED** [review]
Looks OK, modulo some comments that @SkySkimmer may choose to follow or not.

I'll leave a bit of time for comments / amending then will merge.

File: toplevel/coqloop.ml (hunk 1 above)
Comment (gares) [reply toplevel/coqloop.ml]: May I suggest the following message:
```
Coqtop cannot work properly since the standard input is in non-blocking mode.
Use <command> to clear the non-blocking flag.
```

Comment (gares) [reply toplevel/coqloop.ml]: No bugreport, no uncaught exn...

Comment (ejgallego) [reply toplevel/coqloop.ml]: @SkySkimmer are you planning to implement this suggestion? Indeed the proposed message looks better to me.

Comment (SkySkimmer) [reply toplevel/coqloop.ml]: What's `<command>`?

Comment (JasonGross) [reply toplevel/coqloop.ml]: https://unix.stackexchange.com/a/558108/45323 suggests
```bash
perl -MFcntl -e 'fcntl STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) & ~O_NONBLOCK'
```

Comment (JasonGross) [reply toplevel/coqloop.ml]: Maybe there's an equivalent we can give with `ocamlrun` or something instead?

Comment (JasonGross) [reply toplevel/coqloop.ml]: https://unix.stackexchange.com/a/450066/45323 suggests that running `bash` and then executing `ctrl+D` inside the inner bash is enough

Comment (JasonGross) [reply toplevel/coqloop.ml]: https://stackoverflow.com/a/48011063/377022 suggests
```bash
python3 -c $'import os\nos.set_blocking(0, True)'
```

Comment (gares) [reply toplevel/coqloop.ml]: `stty sane` (to be tested)

File: toplevel/coqloop.ml [hunk 2]
```diff
@@ -469,6 +470,16 @@ let rec vernac_loop ~state =
   (* Exception printing should be done by the feedback listener,
      however this is not yet ready so we rely on the exception for
      now. *)
+  | Sys_blocked_io ->
+    (* the parser doesn't like nonblocking mode, cf #10918 *)
+    let msg =
+      Pp.(strbrk "Coqtop needs the standard input to be in blocking mode." ++ spc()
+          ++ str "One way of clearing the non-blocking flag is through python:" ++ fnl()
+          ++ str "  import os" ++ fnl()
+          ++ str "  os.set_blocking(0, True)")
```
Comment (SkySkimmer) [inline toplevel/coqloop.ml]: New version of the message

File: toplevel/coqloop.ml [hunk 3]
```diff
@@ -375,6 +375,7 @@ let rec vernac_loop ~state =
   let open CAst in
   let open Vernac.State in
   let open G_toplevel in
+  Unix.set_nonblock Unix.stdin;
```
Comment (gares) [inline toplevel/coqloop.ml]: This is a leftover. Thanks for testing.

File: toplevel/coqloop.ml [hunk 4]
```diff
@@ -469,6 +469,16 @@ let rec vernac_loop ~state =
   (* Exception printing should be done by the feedback listener,
      however this is not yet ready so we rely on the exception for
      now. *)
+  | Sys_blocked_io ->
+    (* the parser doesn't like nonblocking mode, cf #10918 *)
+    let msg =
+      Pp.(strbrk "Coqtop needs the standard input to be in blocking mode." ++ spc()
+          ++ str "One way of clearing the non-blocking flag is through python:" ++ fnl()
```
Comment (JasonGross) [inline toplevel/coqloop.ml]:
```suggestion
          ++ str "One way of clearing the non-blocking flag is through Python:" ++ fnl()
```
(Assuming we're talking about the language and not the binary)

Comment (ejgallego) [reply toplevel/coqloop.ml]: Not worth a rebase, will add this change to #11457
