### PR TITLE
Parameters of inductives in Number Notations can be arbitrary terms

### LINKED ISSUE #14806: Number Notations incorrectly think that notations containing nested applications don't denote to references
#### Description of the problem

```coq
Declare Scope foo_scope.
Module Good.
  Record aa (x  : Set) := { the_thing : Number.number }.
  Notation aa12 := (aa nat) (only parsing).
  Definition to_aa (n: Number.number) : aa12 := Build_aa _ n.
  Definition from_aa (x: aa12) : Number.number := the_thing _ x.
  Number Notation aa12 to_aa from_aa : foo_scope.
End Good.
Module Bad.
  Record aa (x : Set) := { the_thing : Number.number }.
  Notation aa12 := (aa (sum nat nat)) (only parsing).
  Definition to_aa (n: Number.number) : aa12 := Build_aa _ n.
  Definition from_aa (x: aa12) : Number.number := the_thing _ x.
  Number Notation aa12 to_aa from_aa : foo_scope. (* Error: aa12 is bound to a notation that does not denote a reference. *)
End Bad.
```

Workaround: make a `Definition` for the parameters (such as `sum nat nat`) and use that instead in the notation.

cc @herbelin @proux01 ?  I might take a look at this if I get a chance, but I imagine it's just that we need to add an extra case for app nodes somewhere in the conversion.

cc @andrew-appel

#### Coq Version

8.13

### PR DESCRIPTION
**Pull request by proux01**
Parameter of inductives used for the `Number Notation` command can now be arbitrary terms (rather than just references).

Fixes #14806 

- [x] Added / updated **test-suite**.

### CODE REVIEW

File: interp/notation.ml [hunk 1]
```diff
@@ -675,10 +675,8 @@ let rec constr_of_glob allow_constant to_post post env sigma g = match DAst.get
               let sigma,cl = aux sigma a gcl in
               sigma, c :: cl
            | ToPostCheck r :: a, gc :: gcl ->
-              let () = match DAst.get gc with
-                | Glob_term.GRef (r', _) when GlobRef.equal r r' -> ()
-                | _ -> raise NotAValidPrimToken in
               let sigma,c = constr_of_glob true [||] [] env sigma gc in
+              if not (Constr.equal r c) then raise NotAValidPrimToken;
```
Comment (ppedrot) [inline interp/notation.ml:679]: This looks very fragile to me. Term equality is notoriously wobbly, e.g. this might fail because of universe instances and the like. Can't we simply allow an arbitrary term?

Comment (proux01) [reply interp/notation.ml:679]: Allowing an arbitrary term means we could call the printing function on the wrong type (imagine a parsing function that parses `option bool`, calling it on `option nat` would be wrong), ideally we should check for convertibility.

Comment (ppedrot) [reply interp/notation.ml:679]: Then I'd rather have a small DSL of patterns allowing nested applications of references and wildcards than arbitrary terms. This is really asking for trouble, we've so many issues with arbitrary term equality...

Comment (JasonGross) [reply interp/notation.ml:679]: I don't want to derail this PR by increasing it's scope (I'm happy to have either the current version or @ppedrot's suggestion, ideally whichever one we go with coming with a comment about pitfalls and future extension directions), but I wonder if the correct time to check this is actually via conversion when constructing the application, rather than here.  That is, permit an arbitrary term here, retype the application of the parsing function to the term (after checking that it's closed?), and then reduce.  This might slot in nicely with permitting overlapping number notations, such that if a given one either fails to typecheck or returns `None`, we fall back to the next one.  (I don't have a use case yet for this, though, so perhaps it's not worth the complexity.)

Comment (ppedrot) [reply interp/notation.ml:679]: The problem is that not failing early can be catastrophic for performance. Furthermore, we need the check to be fast, ideally O(1) and worst case O(n), otherwise printing is going to be laboriously slow in some corner cases.

Comment (proux01) [reply interp/notation.ml]: @ppedrot here is a solution without arbitrary term equality and failing as early as possible
@JasonGross sorry, I'm not sure I grasp your idea, would you have an illustrative example? (even a dummy one)

**Comment by JasonGross** [comment]
@coqbot CI minimize

**Comment by proux01** [comment]
@JasonGross this category_theory failure is unrelated, likely an error upstream

File: interp/notation.ml (hunk 1 above)
Comment (ppedrot) [reply interp/notation.ml]: The current code seems more reasonable to me.

**Comment by proux01** [comment]
@JasonGross would you be the assignee here? You are certainly the most knowledgeable about that part of the code.

**Review by JasonGross — APPROVED** [review]
I've read over it somewhat carefully, and it looks good to me!  Here's a minor suggestion about a comment, let me know if you want me to merge it as-is or if you want to update the comment.

File: interp/notation.ml [hunk 2]
```diff
@@ -645,44 +645,72 @@ let constr_of_globref allow_constant env sigma = function
      sigma,mkConstU c
   | _ -> raise NotAValidPrimToken
 
-let rec constr_of_glob allow_constant to_post post env sigma g = match DAst.get g with
+(** [check_glob g c] checks that glob [g] is equal to constr [c]
+    and returns [g] as a constr or raises [NotAValidPrimToken]. *)
```
[the remark this answers is not in the document]
Comment (proux01) [reply interp/notation.ml]: Honestly, I'm not sure to perfectly know, it's more that it was working this way with the fresh universe instances before and did not want risking subtle breakages. So I just updated the comment reflecting that.

**Comment by JasonGross** [comment]
@coqbot merge now

**Comment by proux01** [comment]
Thanks!
