### PR TITLE
Fix primitive projection handling for `setoid_rewrite`

### LINKED ISSUE #7478: Unification doesn't exploit eta of records with primitive projections
#### Version

8.8.0

#### Description of the problem

I would like the below to work:

```coq
Set Primitive Projections.

Record Wrap := wrap { X : Set }.
Axiom f : forall (w : Wrap), X w -> True.

Check f (wrap _) 3.
Fail Check f _ 3.
(* The term "3" has type "nat" while it is expected to have type "X ?w". *)
```

With primitive projections, or more specifically eta for `Wrap`, I would expect `_ : Wrap` and `wrap _ : Wrap` to behave the same with respect to unification.

@mattam82

### PR DESCRIPTION
**Pull request by jpoiret**
While the kernel supports primitive projections properly, many subsystems are still not able to yield their full power:
- `setoid_rewrite`'s matching algorithm simply doesn't traverse under projections;
- neither `evarconv.ml` nor `unification.ml` exploit eta-expansion to solve `p ?e = t`;
- in the pretyper, the environment of the single branch of a destructuring let on a prim record contains a `LocalAssum` per field, whereas we would like them to be `LocalDef`, since the term ends up with a bunch of lets anyways. This is annoying when using evar-based refinement systems, e.g. Program or refine, where we get double the information in the context of the evar.

This is a draft as there are some issues with the current implementation:
- coercions to projected types do not work anymore (see `bug_3480.v`), as unification now succeeds with some unsolved evars when it used to just fail;
- nested pattern matches starting with a primitive record don't compile properly (see `bug_3584.v`).

I'm looking for some external suggestions of how to solve both issues. For the second one, I just don't know how `cases.ml` works intimately and how my change affects the rest of the pattern compilation mechanism.

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.
- [ ] Added / updated **documentation**.
- [ ] Opened **overlay** pull requests.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Test suite is broken

**Comment by jpoiret** [comment]
I kept only the `setoid_rewrite` fix for now. Unification will come later after I figure it out better (and the pretyper stuff will probably disappear, it's out of my league).

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Whoopsie. It looks like category-theory didn't like this change...

File: tactics/rewrite.ml [hunk 1]
```diff
@@ -1083,6 +1083,22 @@ let subterm all flags (s : 'a pure_strategy) : 'a pure_strategy =
...
+          let unfold_compat_constant sigma t =
+            match EConstr.kind sigma t with
+            | App (id, arr) -> mkProj (p, r, Array.last arr)
+            | _ -> assert false in
+            let state, res = s.strategy { state ; env ; unfresh ;
+                                 term1 = expanded ; ty1 = ty ;
+                                 cstr = (prop,cstr) ; evars = evars } in
+          let res =
+            match res with
+            | Success r -> Success { r with rew_to = unfold_compat_constant (goalevars r.rew_evars) r.rew_to }
```
Comment (ppedrot) [inline tactics/rewrite.ml:1097]: You should try moving the call to expand_projection inside the pattern-matching clause or into the closure.

**Comment by ppedrot** [comment]
Let's try again: @coqbot bench

**Comment by ppedrot** [comment]
I had a look at the profile, and it seems it's not directly expansion that is responsible for the slowdown. Rather, it's simply the fact that expanded terms are way bigger than the compact form due to the parameters being huge. I think that to keep a reasonable performance profile the code should rewrite in the scrutinee only and *then* perform expansion to behave as if the term were coming from an application.

**Comment by ppedrot** [comment]
@jpoiret I took the liberty to push a commit demonstrating the kind of behaviour I was thinking about. It's fast on category-theory, but the algorithm is a bit incomplete as it may miss instances of the rewrite lemma inside parameters, which will probably lead to a failure of rewriting. The test added by this PR is way too weak, we should also test a setoid rewrite on a projection with actual parameters and also rewriting in a dependent way in the parameters.

**Comment by ppedrot** [comment]
Let's have a bench with this one. @coqbot bench

**Comment by ppedrot** [comment]
Something went wrong with the two benches. Let's try again at least with the last version: @coqbot bench

**Comment by ppedrot** [comment]
The bench seems broken on this PR. cc @rocq-prover/bench-maintainers

**Comment by SkySkimmer** [comment]
try rebasing on top of https://github.com/rocq-prover/rocq/pull/20471

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Not sure what to do with this PR, since I completely rewrote the code that implements rewriting on projections. Somebody else needs to become assignee, and in any case this feature should also have more tests and a bit of discussion about the expected behaviour w.r.t. parameters.

File: tactics/rewrite.ml [hunk 2]
```diff
@@ -1083,6 +1083,50 @@ let subterm all flags (s : 'a pure_strategy) : 'a pure_strategy =
...
+          let evars = r.rew_evars in
+          let args' = Array.make (Array.length args) None in
+          let () = args'.(Array.length args - 1) <- Some r in
+          let res =
+            if not (is_rew_cast r.rew_prf) then
+              let evars, prf, _, rel, c2 =
+                resolve_morphism env hd args args' (prop, cstr') evars
+              in
+              { rew_car = ty; rew_from = t;
+                          rew_to = c2; rew_prf = RewPrf (rel, prf);
```
Comment (SkySkimmer) [inline tactics/rewrite.ml:1110]: indentation looks wrong here

File: tactics/rewrite.ml [hunk 3]
```diff
@@ -1083,6 +1083,50 @@ let subterm all flags (s : 'a pure_strategy) : 'a pure_strategy =
...
+              { rew_car = ty; rew_from = t;
+                rew_to = mkApp (hd, args'); rew_prf = RewCast DEFAULTcast;
+                rew_evars = evars }
+          in
+          Success res
+        in
+        let res = match res with
+        | Success res ->
+          let (_, args) = EConstr.destApp (goalevars res.rew_evars) res.rew_to in
+          let rew_to = mkProj (p, r, Array.last args) in
```
Comment (SkySkimmer) [inline tactics/rewrite.ml:1124]: why not do this in the `not (is_rew_cast ...)` branch and directly mkProj in the other?

**Comment by ppedrot** [comment]
@SkySkimmer code cleaned up a bit as you asked, and some tests added.

**Comment by SkySkimmer** [comment]
Maybe squash too? No point having the temporary behaviour of rewriting as though it's an application.

**Comment by ppedrot** [comment]
There are two authors here, and I think it's better to keep the intermediate commit just in case we want to fiddle with the implementation at some point.

**Comment by SkySkimmer** [comment]
The intermediate commit could be annoying during bisect.
You can add Co-authored-by to the commit message to handle multiple authorship

**Comment by ppedrot** [comment]
In my opinion the additional commit should not create trouble with bisect, it's basically the same up to the behaviour with parameters. In fact, it passes the CI just right except for the terrible slowdown of category-theory. As such I think it doesn't hurt to keep it around, it's also good to have the full-blown code for parameters stored in the repo.

**Comment by SkySkimmer** [comment]
>As such I think it doesn't hurt to keep it around, it's also good to have the full-blown code for parameters stored in the repo.

I disagree.

**Comment by ppedrot** [comment]
@SkySkimmer should be ready now.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by proux01** [comment]
@jpoiret this breaks graph-theory https://github.com/math-comp/math-comp/actions/runs/14579477219/job/40893944443

**Comment by proux01** [comment]
@jpoiret minimized in https://github.com/rocq-prover/rocq/issues/20575
