### PR TITLE
Fixes #9086: make "cbv" behave like other reductions with respect to unfoldable primitive projections

### LINKED ISSUE #9086: inconsistency between cbv and cbn on primitive projections
#### Version

8.8.2 and 22c0b10f139d9a30fcbe4a5a489022e2b94130e9

#### Operating system

Arch Linux, up to date as of a couple of days ago.

#### Description of the problem

~~~~~
Local Set Primitive Projections.
Record pair {A B} := mk { _1 : A; _2 : B _1 }.

Goal (@mk Prop (fun _ => Prop) True True).(_1).
  progress (cbn iota delta [_1]). (* succeeds *)
  (* Goal: True *)
Abort.

Goal (@mk Prop (fun _ => Prop) True True).(_1).
  progress (cbv iota delta [_1]).
  (* Error: Failed to progress. *)
Abort.
~~~~~

### PR DESCRIPTION
**Pull request by herbelin**
Fixes #9086

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

File: pretyping/cbv.ml [hunk 1]
```diff
@@ -628,7 +628,7 @@ and cbv_stack_value info env = function
 
     (* constructor in a Projection -> IOTA *)
     | (CONSTRUCT(((sp,n),u),[||]), APP(args,PROJ(p,_,stk)))
-        when red_set info.reds fMATCH && Projection.unfolded p ->
+        when red_set info.reds fMATCH && red_set info.reds (fPROJ (Projection.repr p)) ->
```
Comment (SkySkimmer) [inline pretyping/cbv.ml:631]: shouldn't it be 
```suggestion
        when red_projection p ->
```
?

File: test-suite/bugs/bug_9086.v
Comment (SkySkimmer) [inline test-suite/bugs/bug_9086.v:1]: you should test on unfolded projections too

File: pretyping/cbv.ml (hunk 1 above)
Comment (herbelin) [reply pretyping/cbv.ml:631]: Good question. Using `red_projection` seems indeed the correct entry point. But wasn't the convention that the reduction of a projection was requiring MATCH (and even COFIX for a recursive tuple?); that is, wasn't the convention that red_projection expects some iota to be set?

As for the unfolded, that's indeed better to keep it as for now In the longer term, wouldn't the unfolded/folded status disappear though?

File: test-suite/bugs/bug_9086.v
Comment (herbelin) [reply test-suite/bugs/bug_9086.v:1]: Could you please make one? Or give an idea of what you want to test.

**Comment by herbelin** [comment]
@coqbot run full ci

File: pretyping/cbv.ml (hunk 1 above)
Comment (herbelin) [reply pretyping/cbv.ml]: > reduction of a projection was requiring MATCH (and even COFIX for a recursive tuple?)

The [refman](https://coq.inria.fr/doc/V8.19.0/refman/proofs/writing-proofs/equality.html?highlight=cbv#grammar-token-reductions) seems silent about this issue. It does not even mention what `match`, `fix`, and `cofix` exactly cover.

In the chapter on inductive types, iota and fix are [mentioned](https://coq.inria.fr/doc/V8.19.0/refman/language/core/inductive.html#destructors).

In the chapter on records, how [reduction of primitive projections](https://coq.inria.fr/doc/V8.19.0/refman/language/core/inductive.html#destructors) is controlled is not explicit.

So, I guess a *necessary* step would already be to decide what we expect to see in the reference manual. For instance, do we add a flag `proj` covering reduction of primitive projections. And do we include the fold-to-unfold step of primitive projections in such `proj` flag or do we consider instead this step as relevant of `delta`, or even of only `delta`? Do we define `iota` to include such `proj` or not? Do we make reduction of match-defined positive projections entirely different from reduction of primitive projections? Etc.

Comment (SkySkimmer) [reply pretyping/cbv.ml]: sorry for the confusion, I actually meant 
```suggestion
        when red_set info.reds fMATCH && red_projection infos p ->
```
not just red_projection

File: test-suite/bugs/bug_9086.v
Comment (herbelin) [reply test-suite/bugs/bug_9086.v:1]: I can propose the following, which succeeds already w/o the PR:
```coq
Local Set Primitive Projections.
Record pair {A B} := mk { _1 : A; _2 : B _1 }.

Goal (@mk Prop (fun _ => Prop) True True).(_1).
  lazy delta [_1]. (* move to unfolded form *)
  assert_succeeds (progress (cbn iota delta [_1])).
  assert_succeeds (progress (cbv iota delta [_1])).
  assert_succeeds (progress (lazy iota delta [_1])).
  assert_succeeds (progress simpl).
Opaque _1.
  assert_succeeds (progress (cbn iota delta [_1])).
  assert_succeeds (progress (cbv iota delta [_1])).
  assert_succeeds (progress (lazy iota delta [_1])).
  assert_succeeds (progress simpl).
Abort.
```
The fact that `Opaque _1` does not have an effect on the thing displayed as `_1` is however a bit counterintuitive, so, enventually, this test should not make sense I would say (or the flag `Printing Unfolded Projection As Match` set by default).

Comment (SkySkimmer) [reply test-suite/bugs/bug_9086.v:1]: That flag has some issues with printing/parsing roundtrips so I don't think we want it by default. It was just the only idea I had for how to print unfolded projection differently from folded.

Comment (SkySkimmer) [reply test-suite/bugs/bug_9086.v:1]: ok to add that test

Comment (SkySkimmer) [reply test-suite/bugs/bug_9086.v:1]: Not just that, I think currently the `match` produces an error for records without eta.

**Comment by herbelin** [comment]
@SkySkimmer: My analysis of the failure was wrong. The very reason `cbv` on `{|...|}.(p)` with folded `p` did not work was not about not taking into account the folded `p` case in the iota redex but that `fBETA` was required to unfold a folded projection. In particular, the PR did not "fix" the following:
```coq
Local Set Primitive Projections.
Record pair {A B} := mk { _1 : A; _2 : B _1 }.

Set Printing Unfolded Projection As Match.
Goal (@mk Prop (fun _ => Prop) True True).(_1).
lazy delta [_1]. (* internally unfolds the projection *)
progress lazy iota. (* thus the iota happens *)
Restart.
cbv delta [_1]. (* does not internally unfold the projection *)
Fail progress lazy iota. (* thus no iota-reduction is performed *)
```
I updated the PR and added the test.

File: doc/changelog/04-tactics/18618-master+fix9086-align-cbv-prim-proj-other-reduction.rst [hunk 2]
```diff
@@ -0,0 +1,6 @@
+- **Fixed:**
+  Reduction of primitive projections applied to a tuple now works for
+  :tacn:`cbv` like it does for :tacn:`cbn`, :tacn:`lazy` and :tacn:`simpl`
```
Comment (SkySkimmer) [inline doc/changelog/04-tactics/18618-master+fix9086-align-cbv-prim-proj-other-reduction.rst:3]: maybe could be more explicit about the change, something like
```suggestion
  :tacn:`cbv` of primitive projections applied to a tuple now ignores `beta`
  like it does for :tacn:`cbn`, :tacn:`lazy` and :tacn:`simpl`
```

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now
