### PR TITLE
[Pretyping] Do not restrict a solved evar

### LINKED ISSUE #10300: Anomaly "Uncaught exception Not_found." on basic apply
#### Description of the problem

Raises "Anomaly Not_found".

```
Set Implicit Arguments.

Definition hprop := nat -> Prop.

Definition himpl := fun H1 H2 : hprop => forall (h : nat), H1 h -> H2 h.

Parameter himpl_refl : forall H : hprop, himpl H H.

Parameter hstar : hprop -> hprop -> hprop.

Parameter hpure : hprop.

Lemma test : (forall (H:hprop), himpl (hstar H H) hpure -> True) -> True.
Proof. intros M. eapply M. try apply himpl_refl. (* also anomaly without [try] *)
```

#### Coq Version

coq8.10beta1

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #10300. Also addresses #10285: rather than an anomaly, that example produces a regular error message.

> Unable to unify "?M163 tt x" with "Ref (list A) nil r x".

### CODE REVIEW

File: pretyping/evarconv.ml [hunk 1]
```diff
@@ -1315,12 +1315,17 @@ let thin_evars env sigma sign c =
   let rec applyrec (env,acc) t =
     match kind sigma t with
```
Comment (gares) [inline pretyping/evarconv.ml]: The code was wrong and the fix is the wrong fix imo.
The function keeps a state in evdref, but then inspect t using the initial value of the state (sigma).
Indeed `kind` is supposed to always apply the substitution and return `Evar` only when the evar is undefined, so the if-then-else you added is just working around the fact that `kind` is called with the wrong state.

@vgbl cold you pelase try to see if the fix I propose is actually fixing the bug?

**Review by gares — CHANGES_REQUESTED** [review]
Looks like the fix is not the best one

File: pretyping/evarconv.ml (hunk 1 above)
Comment (vbgl) [reply pretyping/evarconv.ml]: Thanks for your comment. I’ll try your suggestion.

Comment (vbgl) [reply pretyping/evarconv.ml]: Unfortunately, this does not fix the issue (same anomalies as before)…

Comment (gares) [reply pretyping/evarconv.ml]: Then I suspect your old fix was just masking the problem (or I'm completely wrong about what apply rec is supposed to do...)

Comment (gares) [reply pretyping/evarconv.ml]: I don't have time now to trace it myself, but I imagine the stack trace is now different

Comment (vbgl) [reply pretyping/evarconv.ml]: Thanks. Here is a second proposal. It only changes `sigma` into `!evdref` in two places. Notice that there are a few occurrences of `sigma` in this code: does someone who understand what’s going on knows whether it is correct to refer to the initial evarmap or not?

Comment (gares) [reply pretyping/evarconv.ml]: I think it is never correct... @ppederot

**Comment by vbgl** [comment]
> I think it is never correct...

Then let’s call that evdref `sigma` too, so as to avoid accidental use
of the stale value.

File: pretyping/evarconv.ml (hunk 1 above)
Comment (vbgl) [reply pretyping/evarconv.ml]: Even when raising the `TypingFailed sigma` exception?

**Comment by mattam82** [comment]
I think you are right and evdref should be used everywhere (maybe even for the error), as an evar might appear multiple times but should be thinned only once.

**Comment by gares** [comment]
@vbgl the content of the Pr seems a legitimate fix, even if it does not fix the bugreport and hence CI fails.
It would be nice to know if the fix actually impacts any CI job. In some sense, the patch should be integrated.

**Comment by vbgl** [comment]
CI is green.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
LGTM, I'd like to merge, but I'd like a summary from @vbgl in order to understand if the metadata is correct, since in the discussion it seems this PR is OK but not an actual fix for the cited bug (there is a new file in the test suite that passes, but you write

> Unfortunately, this does not fix the issue (same anomalies as before)…

so I'm a bit puzzled.

**Comment by vbgl** [comment]
Thanks Enrico.

My first try at implementing your suggestion (replace a single reference to the stale `sigma`) was not enough, hence my reply.

What is currently implemented in this PR (replace all references to the stale `sigma`) does fix the bugs.
