### PR TITLE
Fixing #7700: section variables bound to abbreviations were not found

### LINKED ISSUE #7700: Notation aliases for Lets are broken
#### Version

8.8.0

#### Description of the problem

This should work
```coq
Section foo.
  Let x := Set.
  Notation y := x.
  Check y. (* Error: The reference y was not found in the current environment. *)
```

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

Fixes #7700

Surprisingly enough this is a serious missing case of the globalization of variables which has remained non reported for more than a decade.

Redundancy between finding section variables in both `interp_var` and `interp_qualid` could probably be cleaned, if some courageous soul is wanting to investigate that.

- [X] Added / updated test-suite

### CODE REVIEW

File: interp/constrintern.ml [hunk 1]
```diff
@@ -994,9 +994,12 @@ let glob_sort_of_level (level: glob_level) : glob_sort =
   | GType info -> GType [sort_info_of_level_info info]
 
 (* Is it a global reference or a syntactic definition? *)
-let intern_qualid qid intern env ntnvars us args =
+let intern_qualid ?(no_secvar=false) qid intern env ntnvars us args =
```
Comment (ejgallego) [inline interp/constrintern.ml]: Maybe the parameter should be named `avoid_secvar`?

Comment (herbelin) [reply interp/constrintern.ml]: If you want.

Comment (ejgallego) [reply interp/constrintern.ml]: Not a strong feeling towards it, I was just thinking out loud and suggesting an alternative; so if you like the new one better update the branch, otherwise I'll merge tomorrow.

[Yes, I do agree that part could use a cleanup, also abbreviations could use some love]

**Review by ejgallego — APPROVED** [review]
This part of the code is indeed sensible but as far as I can tell the patch looks OK. Thanks!
