### PR TITLE
Fix #6751 trust_file_cache logic was inverted

### LINKED ISSUE #6751: Coq fails to import .v(i)o files created atfer it was started
#### Version

master

#### Operating system
Linux

#### Description of the problem

In ProofGeneral, open a file with some dependencies and run it. PG will compile the dependencies, but Coq still fails to import them.

@ejgallego says this has something to do with a "file cache" or so.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Bug introduced by 675a1dc401eb9a5540ba5bc9a522c1f84d4c3d54

### CODE REVIEW

**Review by gares — APPROVED** [review]

File: lib/system.ml [hunk 1]
```diff
@@ -82,7 +82,7 @@ let file_exists_respecting_case path f =
     let df = Filename.dirname f in
     (String.equal df "." || aux df)
     && exists_in_dir_respecting_case (Filename.concat path df) bf
-  in (!trust_file_cache || Sys.file_exists (Filename.concat path f)) && aux f
+  in (not !trust_file_cache || Sys.file_exists (Filename.concat path f)) && aux f
```
Comment (ejgallego) [inline lib/system.ml]: This doesn't look right, it `trust = true`, we should not `stat` the file.

Comment (SkySkimmer) [reply lib/system.ml]: Behaviour from 13f014ba37e0af547d57854df8926d633f9ccb7b

**Comment by SkySkimmer** [comment]
OK changed back.

Gaëtan Gilbert
