### PR TITLE
Fix timeout by ensuring signal exceptions are not erroneously caught

### LINKED ISSUE #7430: Timeout on infinite loop sometimes doesn't terminate
#### Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.8+alpha (April 2018)
compiled on Apr 21 2018 15:11:27 with OCaml 4.05.0
```

Coq master `dfbf22a098e8`.

#### Operating system

macOS 10.13

#### Description of the problem

Basically, the following code sometimes infinite loops.

The following attempt at a sleep tactic is unreliable. The idea is to repeat a tactic that grows the goal infinitely, then use `timeout` to keep it to 1 second. With an inlined version of `Basics.apply` it becomes fairly unreliable, often taking seemingly infinite time. Using a definition or using `eapply proj1` makes it more reliable but not 100%. Also, adding an additional `Timeout` to the command doesn't solve the problem I believe.

```coq
Tactic Notation "sleep" :=
  try solve [ timeout 1 (repeat eapply (fun (A B : Type) (f : A -> B) (x : A) => f x)) ].

(* this is much more reliable *)
Tactic Notation "sleep'" :=
  try solve [ timeout 1 (repeat eapply proj1) ].

Theorem true1 : True.
Proof.
  sleep.
  idtac "worked".
Abort.
```

You can test this with the following bash one-liner:

```bash
for i in $(seq 1 10); do timeout 2 coqc sleep.v || echo "failed"; done
```

(timeout is from coreutils; use `gtimeout` on macOS if using Homebrew coreutils)

### LINKED ISSUE #10968: `timeout` cannot interrupt `remember`, while `Timeout` can
#### Description of the problem

```coq
Ltac go c n P :=
  let m := fresh "n0" in pose proof n as m;
  let N := fresh in
  assert (P -> m = m) as N by refine (fun _ => eq_refl);
  move N at top;
  lazymatch c with
  | S ?c' => go c' m (P -> m = m)
  | O => idtac
  end.

Goal forall (n0: nat), n0 = n0 -> False.
  intros.
  go 300 n0 (n0 = n0).

  Time timeout 1 (match type of H288 with
                  | ?P -> _ => remember P as x
                  end).
```

prints

```
Finished transaction in 5.194 secs (5.176u,0.001s) (successful)
```

This is wrong: It should not last longer than roughly one second, and fail because it took too long.

On the other hand, upper case `Timeout` works as expected:

```coq
  Time Fail Timeout 1 (match type of H288 with
                       | ?P -> _ => remember P as x
                       end).
```

prints

```
The command has indeed failed with message:
         Timeout!
Finished transaction in 1. secs (0.996u,0.s) (successful)
```

#### Coq Version

8.9.0

/cc @JasonGross

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
Fixes #7430 and fixes #10968

This commit makes the following changes:
- Add an exception `Signal` used to convert OCaml signals to exceptions.
`Signal` is registered as critical in `CErrors` to avoid being caught in the
wrong `with` clauses.
- Make `Control.timeout` into a safer interface based on `option` instead of
exceptions.
- Modify tclTIMEOUT to fail with `CErrors.Timeout` instead of
`Logic_monad.Tac_timeout`, as was already advertised in the ocamldoc documentation.
- Removes `Logic_monad.Tac_timeout` altogether because it no longer has a use.

- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by SkySkimmer** [comment]
How do we handle nested timeouts (both in master and after this PR)?
eg what does
~~~coq
Ltac loop := repeat (pose proof I). (* easiest loop tactic I know of *)

Goal False.
  Timeout 1 ((timeout 2 loop) || pose proof 0).
~~~
In master it seems only the inner timeout has an affect, so it takes 2s and then succeeds producing a `nat` hypothesis.

**Comment by LasseBlaauwbroek** [comment]
Ocaml provides only one timeout at the same time. So the effects are:
- Master: An already running timer is replaced by a new timer. So in your case, the old timer is discarded.
- This PR: Same behaviour.
- PR #13378: The running timer is suspended and replaced by a new timer. After the second timer finishes, the old timer is restored. If necessary, I can replicate the behavior of master. I can also try to subtract the time of the second timer from the suspended timer, but I'm not sure how reliable that would be.

**Comment by LasseBlaauwbroek** [comment]
I've added an overlay for CoqHammer.

**Comment by SkySkimmer** [comment]
Not sure who may be familiar with the timeout system, maybe @ppedrot or @ejgallego ?

File: engine/proofview.ml [hunk 1]
```diff
@@ -264,7 +264,7 @@ module Monad = Proof
 
 (** [tclZERO e] fails with exception [e]. It has no success. *)
 let tclZERO ?(info=Exninfo.null) e =
-  if not (CErrors.noncritical e) then
+  if not (CErrors.noncritical e || e = CErrors.Timeout) then
```
Comment (ppedrot) [inline engine/proofview.ml:267]: This is very dangerous style, you must use a pattern-matching instead.

File: lib/control.ml [hunk 2]
```diff
@@ -16,6 +16,8 @@ let steps = ref 0
 
 let enable_thread_delay = ref false
 
+exception Signal of int
```
Comment (ppedrot) [inline lib/control.ml:19]: Why the int argument? You always raise it with the same value?

Comment (LasseBlaauwbroek) [reply lib/control.ml:19]: Yes, this is an attempt at generalization. Maybe some day someone wants to use a signal with a different code. Then I want to make sure that the `timeout` function does not catch it (by checking for the correct value).

Comment (ppedrot) [reply lib/control.ml:19]: Well, instead of introducing dead code I think you should define a dedicated exception for SIGALRM signals here. Some day seems too far away...

File: engine/proofview.ml (hunk 1 above)
Comment (LasseBlaauwbroek) [reply engine/proofview.ml]: I've changed this to pattern-matching style, but the result is a bit awkward. Or did you have something else in mind.

File: lib/control.ml (hunk 2 above)
Comment (LasseBlaauwbroek) [reply lib/control.ml]: Done.

**Review by ppedrot — APPROVED** [review]
The code changes seem fine but as usual this is tricky business. I don't know if we test this enough on our CI...

**Comment by ppedrot** [comment]
@LasseBlaauwbroek If you want to backport this to 8.13 I think it is enough not to remove the `Tac_Timeout` exception but simply redefine it as `exception Tac_Timeout = CErrors.Timeout`. This will simply declare it as an alias and the tracked development should hopefully still compile.

**Comment by LasseBlaauwbroek** [comment]
I've added the alias. (I tried to make it deprecated, but apparently, exceptions cannot be deprecated.)

**Comment by ppedrot** [comment]
Sorry, but I've realized that my proposal was wrong. Indeed, it allows to let critical exceptions (namely, `CErrors.Timeout`) sneak into the monad which is a big no-no w.r.t. expected invariants. Actually, if I remember correctly your original proposal had the same issue. So, in the end, you need to preserve the exception in Logic_monad as a distinct non-critical exception raised when `tclTIMEOUT` fails.

**Comment by ppedrot** [comment]
It's fairly complex code, so I am unsure whether what I am going to say is right, but it seems we have one too many exceptions. IIUC, just two of them should suffice.
- `Sigalarm` and `CErrors.Timeout` should be merged and considered critical
- `Logic_monad.Tac_Timeout` should be untouched by the PR.

**Comment by LasseBlaauwbroek** [comment]
Ah I was not aware of the invariant on the monad (although I could have known looking at `tclZERO`. Your approach will basically work, with the following caveats:
- We are now following existing behavior but not the spec as described in `proofview.mli`.
- I had to move `Timeout` to `Control`. It is now aliased in CErrors to maintain backwards compatibility.
- I originally implemented the solution using `Signal` because I was/am worried about plugins catching `Timeout`. We may be unintentionally introducing bugs in these plugins with this approach.

That being said, I confirmed that both linked issues are still fixed now. Note also that the overlay for CoqHammer is now invalidated.

**Comment by ppedrot** [comment]
>  I was/am worried about plugins catching Timeout

Plugins catching a critical exception without reraising it are not respecting the spec, so I wouldn't worry too much.

**Review by ppedrot — APPROVED** [review]
