### PR TITLE
Fixing #10286 (coqide hangs on invalid filenames)

### LINKED ISSUE #10286: CoqIDE 8.10beta1 fails to open filenames with dots
#### Description of the problem

CoqIDE 8.10 fails to handle file with dot in the name.

```
coqide foo.bar.v
Error: Invalid character '.' in identifier "foo.bar".
```

If the file already exists, CoqIDE can even silently hang on load.

#### Coq Version

coq-8.10beta1

### PR DESCRIPTION
**Pull request by herbelin**
The hang is caused by a failure in the interpretation by coqtop of the command line option `-topfile filename` (this happens before a proper XML communication is set up between coqtop and coqide).

The fix is a bit ad hoc. We copy in coqide the code for checking the validity of a filename. We copy it to avoid adding a dependency in either `Names.check_valid` or `Stm.dirpath_of_file`. We do a minimal check (on the basename) while (if it hadn't added extra depencencies or code duplication) it would have been more consistent to do the exact same check as in `Stm.dirpath_of_file`.

**Kind:** bug fix

Fixes / closes #10286.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
What happens on a file `foo.bar` (without `.v` at the end)?

**Comment by herbelin** [comment]
> What happens on a file foo.bar (without .v at the end)?

As it is: `Invalid character '.' in identifier "foo.bar".`

**Comment by SkySkimmer** [comment]
>As it is: Invalid character '.' in identifier "foo.bar".

I tested a bit
- when opening through File > Open no message (both the check and the -topfile interpretation blindly drop the extension so `-topfile foo.bar` is equivalent to `-topfile foo.v`)
- when opening through command line it does error with that message (coqide automatically appends .v to the command line argument, even if foo.bar already exists)

**Comment by herbelin** [comment]
@SkySkimmer: do you suggest that `Open`, via `load`, calls `make_file_buffer` rather than `FileAux.load_file` directly (or adds the first line of `make_file_buffer` in `load`)?

**Comment by SkySkimmer** [comment]
I have no clue

Gaëtan Gilbert

**Comment by herbelin** [comment]
I mean: do you suggest that we align the behavior of `Open` to the behavior of the command line?

File: ide/coqide.ml [hunk 1]
```diff
@@ -110,7 +110,13 @@ let make_coqtop_args fname =
     | None -> args
     | Some fname ->
       if List.exists (String.equal "-top") args then args
-      else "-topfile"::fname::args
+      else
+        (* We basically copy the code of Names.check_valid since it is not exported *)
```
Comment (maximedenes) [inline ide/coqide.ml]: Why not move this check to a library that can be shared between Coq and CoqIDE?

Alternatively, why not pass this name through the XML protocol rather than the command line, and have it validated by Coq?

Comment (herbelin) [reply ide/coqide.ml]: > Why not move this check to a library that can be shared between Coq and CoqIDE?

This is what I tried first (relying on `library_of_file` which `stm.ml` uses) but this would require at worst to be dependent on `loadpath.ml`, so I renounced.

> Alternatively, why not pass this name through the XML protocol rather than the command line, and have it validated by Coq?

This is probably an alternative. I don't know well the XML protocol. Can we add arbitrary new requests? (I'm also a bit afraid of the time it would take.)

**Comment by vbgl** [comment]
Pierre-Marie, do you have an opinion on this PR? It looks like a good fix to have in 8.10. Thanks.

Ping @ppedrot

**Review by ppedrot — APPROVED** [review]
LGTM.

**Comment by vbgl** [comment]
This is ready for merging. Thanks.
