### PR TITLE
Ltac2 typed notations

### LINKED ISSUE #17477: Imprecise typing error location if discriminee of Ltac2 `match!`/`lazy_match!` is not a `constr`
```
cat ltac2_imprecise_error_pos.v
```

```coq
Require Import Ltac2.Ltac2.

Ltac2 foo(b: bool): bool :=
  let c := b in
  match! c with
  | true => true
  | false => false
  end.
```

```
coqc ltac2_imprecise_error_pos.v 
```

```
File "./ltac2_imprecise_error_pos.v", line 3, characters 0-102:
Error: This expression has type bool but an expression was expected of type
constr
```

The reported error position spans the whole function, starting at the `L` of `Ltac2`, going all the way to the `.` at the end.

Desired behavior: Only the text between `match!` and the `with` should be reported in the error.

```
coqc -v
```
```
The Coq Proof Assistant, version 8.16.0
compiled with OCaml 4.13.0
```

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix https://github.com/coq/coq/issues/17477

We preserve the ability to define untyped notations with a flag (DONE unset the flag in the compat files), however it is not clear that this is at all useful.

To handle `globalize` on a typed notation (called when declaring an untyped notation which uses the typed notation, and when using `Ltac2 Globalize`) we add a constructor to raw_tacexpr which contains a glb_tacexpr with its expected type information. The types will be checked when the untyped notation is typechecked (eg at use in a regular definition or in a typed notation).

Aliases are currently never eagerly typed (so eg `Ltac2 Notation foo := Int.add ().` is still accepted), this could probably be easily changed.

### CODE REVIEW

File: plugins/ltac2/tac2intern.ml [hunk 1]
```diff
@@ -1670,6 +1712,35 @@ let debug_globalize_allow_ext ids tac =
   let tacext ?loc (RawExt (tag,arg)) = CAst.make ?loc @@ CTacExt (tag,arg) in
   globalize_gen ~tacext ids tac
 
+let { Goptions.get = typed_notations } =
+  Goptions.declare_bool_option_and_ref
+    ~key:["Ltac2";"Typed";"Notations"] ~value:true ()
```
Comment (rlepigre) [inline plugins/ltac2/tac2intern.ml:1717]: I expect that typed notations will be useful most of the time, so I think it would be better to allow disabling the type-checking locally, via an attribute. Have you considered this option?

Comment (SkySkimmer) [reply plugins/ltac2/tac2intern.ml:1717]: That would mean keeping the untyped data around too, it's not great.
Also typed notations can do more things, like have `constr:()` in them.
Also I'm pretty sure untyped notations are useless.

Comment (rlepigre) [reply plugins/ltac2/tac2intern.ml:1717]: Ah OK, I thought this would be as simple as  using the `UntypedNota` constructor if the attribute is used, and `TypedNota` otherwise (determined at the definition time of the notation).

Untyped notations are probably mostly useless, but there might be hacky cases where they could be useful I guess.

Comment (SkySkimmer) [reply plugins/ltac2/tac2intern.ml:1717]: I guess I misunderstood what you were saying, I thought you meant something like 
~~~coq
Ltac2 Notation "foo" ...

#[thing]
Ltac2 whatevr := foo ...
~~~
and in the definition `foo` would be treated as an untyped notation, but maybe you mean just having 
~~~coq
#[thing] Ltac2 Notation "foo" ...
~~~
as an alternative to
~~~coq
Unset Ltac2 Typed Notations.
Ltac2 Notation "foo" ...
~~~

Comment (rlepigre) [reply plugins/ltac2/tac2intern.ml:1717]: I indeed meant the latter, that is, allowing something like:
```
#[untyped]
Ltac2 Notation ...
```

**Comment by SkySkimmer** [comment]
doc/changelog added

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
> TODO unset the flag in the compat files

@SkySkimmer do you plan to do it before merging?

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now
