### PR TITLE
Fix #6313: lost goals in nested ltac in refine

### LINKED ISSUE #6313: ltac:(shelve) does not interact well with pattern matching and (simple) refine
#### Version

8.7.0

#### Description of the problem

This code should work.  It does not:
```coq
Inductive foo := a | b | c.
Goal foo -> foo.
  intro x.
  simple refine (match x with
                 | a => _
                 | b => ltac:(shelve)
                 | c => _
                 end); [ | ].
  (* Error: Tactic failure: Incorrect number of goals (expected 1 tactic). *)
```

Interestingly, this is also a case where `Unshelve` fails to unshelve evars:
```coq
Inductive foo := a | b | c.
Goal foo -> foo.
  intro x.
  unshelve refine (match x with
                   | a as x' => ?[a]
                   | b as x' => ltac:(shelve)
                   | c as x' => ?[b]
                   end).
  exact c.
  Unshelve.
  Fail idtac. (* Error: No such goal. *)
  Grab Existential Variables.
  exact b.
  exact a.
  Show Proof.
  (* (fun x : foo => match x with
                | a => a
                | b => b
                | c => c
                end) *)
```

### PR DESCRIPTION
**Pull request by herbelin**
This fixes what is actually a critical bug in nesting calls to the proof engine as `ltac:(...)`-in-terms does.

The fix is simply to save the list of pending goals (the "future" goals) and to restore them (as was done already for "side effects"), in `refine_by_tactic`.

Some issue remains with `ltac:(tac)`: what is it supposed to do with the shelf. If the shelf produced by `tac` is non empty, should the call fail or return the shelf? The current situation is not good as the shelf is simply lost, i.e. tacitly moved in the ether.

This should probably be versed to 8.7.1, but I modified the API, so a version of the PR which does not change the API should be done. But, first, let's answer the shelve in `ltac:()` question.

(Edited for clarification.)

### CODE REVIEW

**Comment by ppedrot** [comment]
Indeed. That's another argument to put the pretyper in the tactic monad...

**Comment by JasonGross** [comment]
I think it should keep shelved goals shelved.  I want to be able to write `ltac:(shelve)` to mean "start out with this goal on the shelf.  This seems strictly more expressive to me; if I want them to not be on the shelf, I can always prefix something with `unshelve`.

Here are design patterns that I want to use (maybe the test suite should gain tests for these?):
- `ltac:(shelve)` to shelve some holes in `refine `
- `instantiate (1 := ltac:(destruct x))` to partially refine an evar with a match (if the evar is already on the shelf, it should stay that way)
- `unshelve <stuff mentioning ltac:>` should leave nothing new on the shelf, I think

File: proofs/pfedit.ml [hunk 1]
```diff
@@ -177,7 +179,10 @@ let refine_by_tactic env sigma ty tac =
       iraise (e, info)
   in
   (** Plug back the retrieved sigma *)
-  let sigma = Proof.in_proof prf (fun sigma -> sigma) in
+  let (goals,stack,shelf,given_up,sigma) = Proof.proof prf in
+  assert (stack = []);
+(*  if shelf <> [] then CErrors.user_err (str "Tactic not supposed to shelve goals.");*)
+  if given_up <> [] then CErrors.user_err (str "Tactic not supposed to given up goals.");
```
Comment (JasonGross) [inline proofs/pfedit.ml]: Grammar nit: I'd instead say "Giving up goals in tactics in terms is unsupported".  (Or, at the very least, "given" should be "give" in your message.)

**Review by JasonGross — DISMISSED** [review]

**Comment by herbelin** [comment]
> Indeed. That's another argument to put the pretyper in the tactic monad...

Do you have a clear idea of how to do it? Looking at the `shelf` in `Proof.t`, at the `shelf` in `Proofview_monad.proofview`, at `future_goals` in `Evd`, at `undef` in `Proof.run_tactic`, I feel that a clarification of what should be in `sigma`, what should be in `proofview`, what should be in `Proof.t` is needed first.

In any case, my fix was incomplete. We should inform of the existence of pending goals at the end of `refine_by_tactic`. As far as I understand, the only way currently to communicate between pretyping and tactics is via the `future_goals` field, but that does not carry a lot of structure. What if I do a `ltac:(give_up)` or even a `ltac:(shelve)` within the scope of a `refine` for instance? (Note that keeping `shelf` information in the `sigma` was an old question from @gares if I remember correctly.)

Anyway, to get at least the following working:
```coq
Goal (True/\0=0 -> False) -> False.
  intro f.
  refine (f ltac:(split; only 1:exact I)).
  reflexivity.
Qed.
```
I experimented appending the result of `run_tactic` to the `future_goals` as a way to inform the upper `refine` that it has to consider these new goals (but still the `shelve` or `given_up` or regular status is lost).

As a side remark, there is also something strange in `Proof.run_tactic` which seems to decide somehow arbitrarily that any `future_goals` which is not already registered shall go on the shelf. This looks like a hack. It would seem safer to me to fail and investigate about why we sometimes lose the track of an evar. What do you think?

**Comment by ppedrot** [comment]
> Do you have a clear idea of how to do it? Looking at the shelf in Proof.t, at the shelf in Proofview_monad.proofview, at future_goals in Evd, at undef in Proof.run_tactic, I feel that a clarification of what should be in sigma, what should be in proofview, what should be in Proof.t is needed first.

One of the shelves from `sigma` and `proofview` have to disappear. I am under the impression that the one in evar maps is a hack to precisely work around the fact that not all functions are living in the tactic monad, so that we thread it in the almighty state to be cheaply backward compatible. If that's true, we should get rid of that one.

The shelf from `Proof.t` is meant to stay, as it's not living on the same layer.

**Comment by herbelin** [comment]
@ppedrot: I'll assume that you mean `future_goals` when you are talking about the shelf in sigma? One concrete advantage of keeping it would be to clarify the way how evars are tracked without requiring the "big" move of the pretyper in the monad (though maybe this is not so big move, it is just that it looks too big for me). On the lazy plan of action, adding a flag to the `future_goals` to tell if it is a shelved or given up evar looks easy to do, and this could be a temporary solution while waiting for the big move, no? That would also clarify the `advance` business where an evar which is given up or shelved seems to have lost its origin when returning to the `Proof.t` (though we could certainly do some computation in `refine` to recover this status... I can do it if it is clear that there is nothing more principled - though not too complicated either - to do).

I have other concerns with the interaction between the shelf in `Proof.t` and the one in proofview (iiuc, the invariants are not very well expressed in the data structure, like: is the `proofview` shelf supposed to be empty when entering `Proofview.apply` or not, as well as: isn't `to_shelve` the same as `pr.shelf` in `Proof.run_tactic`, and also: is the `undef` a safety strap?), but that's maybe more questions to @aspiwack.

**Comment by ejgallego** [comment]
> Do you have a clear idea of how to do it? Looking at the shelf in Proof.t, at the shelf in Proofview_monad.proofview, at future_goals in Evd, at undef in Proof.run_tactic, I feel that a clarification of what should be in sigma, what should be in proofview, what should be in Proof.t is needed first.

@herbelin that comment is spot on, hopefully we can discuss a bit in the WG about the work in the tactic layer, I would like to add some comments that arose while working on the patch to remove `Proof_global` but I am really overloaded right now. IMHO, we should prioritize cleaning up the tactic / monad layer before moving more components on top of it.

**Comment by ejgallego** [comment]
For a starter the `shelf` story needs quite a bit of work.

File: proofs/pfedit.ml (hunk 1 above)
Comment (herbelin) [reply proofs/pfedit.ml]: The problem is that this function is not used only by tactic-in-term. It is also used e.g. in `setoid_rewrite`.

Anyway, I'm more in the mood of supporting `ltac:(shelve)` in `refine`, as you also asked, than to forbid it. So this error message is more probably going to disappear.

**Comment by herbelin** [comment]
> For a starter the shelf story needs quite a bit of work.

I spent the whole previous day to understand better the various layers involved in dealing with the shelf. I'm getting more confident that it does not necessarily need a lot of work to a minima control its behavior better.

**Comment by herbelin** [comment]
> @herbelin that comment is spot on, hopefully we can discuss a bit in the WG
about the work in the tactic layer, I would like to add some comments that
arose while working on the patch to remove Proof_global (...).

Sure, we can discuss at the WG. I'm looking forward your comments on `Proof_global`.

About #6313 specifically, I think I can provide a rather simple patch by tagging the `future_goals` with their status. I'm going to try that, at least to fix the current behavior, until seeing a more longer term architectural project being developed.

**Comment by mattam82** [comment]
I’d be curious to hear about this too, it has impact on unifall too (the
various shelves)

**Comment by Zimmi48** [comment]
This PR has been waiting for a long time and subsequently the 8.7-only version also. What to do with it? (I didn't re-read the discussion.)

**Comment by herbelin** [comment]
Hi, I made a small update on this (underspecified) part of the proof engine, mainly tagging the `future_goals` with their status, allowing to propagate this status from `ltac:(...)` to `Refine.refine`, from `Refine.refine` to the `proofview` datatypes (the one which has a `shelf` field, a `comb` field and a `gaveup` component (slightly hidden!) in the `Proofview_monad.P.w` writer part of the monad, then finally to the `Proof.t` structure.

In the process, I found a couple of oddities but I'm renouncing to address them by lack of time. For instance, `clear` and the `Evarutil.advance` technique are leaking evars to the shelf (in the sense that it leads to duplicating evars existing once as regular goals, and once on the shelf). Concretely, if I have `?p : [x:A |- B]` and `?q : [x:A |- P(?p)]` both not shelved and I clear `x` while being focused on `?q`, then, `?p` is retricted to `?p'`, `?q` is restricted to `?q'`, the focus is updated to `?q'` and `?p'` using `advance`, but the new `?p'` is still marked as `future_goal` and thus later one `retrieved` in `Proof.run_tactic` which put it on the shelf thinking that it was generated out of control of the proof engine.

Another delicate thing (discussed briefly on gitter) is the order of goals when they enter or go out the shelf. For instance, `Unshelve` adds goals after but `unshelve` adds them before the existing goals. What to do in general so that it is convenient in practice is probably a difficult question.

In the process, I changed a little the output of `Show Existentials` output (see independent PR #6816).

I also shyly added a few functions to the "unsafe" part of the `Proofview` API. I'm saying shyly in the sense that I did it following what seemed to be a general design pattern of the API, but I'm still not able to finely grasp how the different levels of abstraction of the API are supposed to be used. Including some local issues, like I find confusing that `proofview` is both the conceptual name of the whole proof view and the name of the specific readable/writable field of the whole proof view.

At some time, I may do a mini-squashing of the commits.

**Comment by ejgallego** [comment]
Interesting thoughts @herbelin , I' date to say that when trying to clean up `run_tactic` et friends to be functional I had similar feeling about the abstraction level of the API. Maybe we should try to sketch a CEP for a wishlist of the Proofview API?

**Comment by herbelin** [comment]
I squashed what I intended to squash. So, from my point of view, this is ready (even if there are still a couple of strange things about collecting future goals in the presence of `clear` and `advance`, but I don't see it as prioritary as it works as it is).

**Comment by Zimmi48** [comment]
There's a failure in HoTT. Likely some tactic having become more powerful.

**Comment by herbelin** [comment]
> There's a failure in HoTT. 

Ah, I thought I had found the fix, but apparently not.

> Likely some tactic having become more powerful.

If the same bug as I had seen before, this is a "serious" one: losing track of a shelved goal which only `Grab Existentials` but not `Unshelve` is able to retrieve.

**Comment by herbelin** [comment]
> > There's a failure in HoTT.
> 
> Ah, I thought I had found the fix, but apparently not.

Well, was a stupid "typo". Should be ok now.

**Comment by maximedenes** [comment]
@ppedrot does this look good to you?

**Comment by maximedenes** [comment]
@ppedrot ping

**Review by ppedrot — APPROVED** [review]
I guess this is OK, and it's a welcome fix.

File: engine/proofview.mli [hunk 2]
```diff
@@ -425,6 +425,18 @@ module Unsafe : sig
   (** [tclGETGOALS] returns the list of goals under focus. *)
   val tclGETGOALS : Evar.t list tactic
 
+  (** [tclSETSHELF gls] sets goals [gls] as the current shelf. *)
+  val tclSETSHELF : Evar.t list -> unit tactic
+
+  (** [tclGETSHELF] returns the list of goals on the shelf. *)
+  val tclGETSHELF : Evar.t list tactic
```
Comment (mattam82) [inline engine/proofview.mli]: In the shelf/unshelve_goals PR #6943 (previously part of unifall-infra) I called this shelf and I don't think it's unsafe.

**Review by mattam82 — APPROVED** [review]
Great! I missed (EDIT: the update to) that PR somehow. It makes future_goals management more explicit and kind of explains their use in a much clearer way, I think unifall will also benefit from this :)

File: engine/proofview.mli (hunk 2 above)
Comment (herbelin) [reply engine/proofview.mli]: Right. So, do you suggest I move it out of `Unsafe` and give it the name `shelf`? That looks indeed better to me. (Or shall you do it as part of #6943?)

**Comment by maximedenes** [comment]
@herbelin if that's ok, I'll rebase and force push, to get a new run, because there are many (spurious?) failures.

File: clib/option.ml [hunk 3]
```diff
@@ -50,6 +50,9 @@ let get = function
 (** [make x] returns [Some x]. *)
 let make x = Some x
 
+(** [bind x f] is [f y] if [x] is [Some y] and [None] otherwise *)
+let bind x f = match x with Some y -> f y | None -> None
+
 (** [init b x] returns [Some x] if [b] is [true] and [None] otherwise. *)
```
Comment (ejgallego) [inline clib/option.ml]: Duplicate of `Option.map`

**Comment by herbelin** [comment]
> @herbelin if that's ok, I'll rebase and force push, to get a new run, because there are many (spurious?) failures.

Sure.

(From memory, they were indeed all spurious. I hope I did not miss a real one.)

**Comment by maximedenes** [comment]
Done!

**Comment by herbelin** [comment]
@ejgallgo, about `Option.bind`: do you mean that I should use `Option.map (fun x -> Some (f x))`. I could, but I thought that the idea with these combinators was to organize them around some standard bricks and that `bind` was one of them. What should I do?

**Comment by ejgallego** [comment]
> @ejgallego, about Option.bind: do you mean that I should use Option.map (fun x -> Some (f x)). I could, but I thought that the idea with these combinators was to organize them around some standard bricks and that bind was one of them. What should I do?

Never mind @herbelin I've retracted my review. Sorry for the noise.

**Comment by maximedenes** [comment]
Success here: https://travis-ci.org/herbelin/github-coq/builds/351021904

**Comment by Zimmi48** [comment]
Given the level of importance of this bug qualified by @herbelin of "critical" and given the small incompatibility detected on HoTT, this would have deserved an entry in CHANGES. Can be addressed as part of #6849.
