### PR TITLE
Make detyping of projections parameter recovery more robust

### LINKED ISSUE #16716: Ltac2 should never elide top-level arguments of uncaught exceptions (constr failed to print)
#### Description of the problem
When I write
```coq
Ltac2 Type exn ::= [ Cannot_eliminate_functional_dependencies (constr) ].
```
and then do `Control.zero (Cannot_eliminate_functional_dependencies term)`, it's not really very useful to get
```coq
Uncaught Ltac2 exception: RewriteRules.Reify.Cannot_eliminate_functional_dependencies (constr:(...))
```
I presume this is because the constr is too big, but even `Set Printing Depth 10000000.` does not get the constr to display.  I cannot reproduce this issue in a small test case, but it can be seen at https://github.com/JasonGross/fiat-crypto/tree/xxx-coq-bug-ltac2-constr-msg, branch xxx-coq-bug-ltac2-constr-msg, with `make TIMED=1 src/Rewriter/Passes/MultiRetSplit.vo`

#### Coq Version

8.16

### PR DESCRIPTION
**Pull request by SkySkimmer**
If we have a bad evar map retyping can fail with anomalies, eg the one from Evd.existential_type

Close #16716

### CODE REVIEW

File: pretyping/detyping.ml [hunk 1]
```diff
@@ -887,7 +887,7 @@ and detype_r d flags avoid env sigma t =
           try
             let c = Retyping.expand_projection (snd env) sigma p c [] in
             DAst.get (detype d flags avoid env sigma c)
-          with Retyping.RetypeError _ -> noparams ()
+          with _ -> noparams ()
```
Comment (ppedrot) [inline pretyping/detyping.ml:890]: Catch-all clauses for exceptions are very bad™. At the very least you should check for non-criticality.

Comment (SkySkimmer) [reply pretyping/detyping.ml:890]: The exception in https://github.com/coq/coq/issues/16716 is critical though
https://github.com/coq/coq/blob/90caf092f1946a81d3a104b6744faeef84ea2c4d/engine/evd.ml#L926

Comment (ppedrot) [reply pretyping/detyping.ml:890]: This this is a hack, and the fix should be more principled.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
