### PR TITLE
Fix #18769: Recompute stored projection constant 

### LINKED ISSUE #18769: Anomaly `Not_found` when printing `Include`d primitive projections in 8.19
### Description of the problem

The code below fails with an uncaught `Not_found` exception. The change that introduced the problem is:
```
c47984b84fa16811481a2ad734f6d1f947b7e45a is the first bad commit
commit c47984b84fa16811481a2ad734f6d1f947b7e45a
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Fri Nov 3 11:43:01 2023 +0100

    Store the associated constant directly in projection nodes.
    
    The goal is to prevent repeatedly rebuilding the constant when performing
    reduction, as CClosure.unfold_projection has to pass a constant to the
    transparent state.

 checker/values.ml |  2 +-
 kernel/names.ml   | 16 ++++++++++------
 2 files changed, 11 insertions(+), 7 deletions(-)
```

The code works in 8.18 and on master. On master it has been fixed (I think accidentally?) by:
```
2ab364ddf813cc9d7a26a0f31d511f08092c772c is the first bad commit
commit 2ab364ddf813cc9d7a26a0f31d511f08092c772c
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Wed Feb 28 00:50:06 2024 +0100

    Display projections in Print.

 test-suite/output/Projections.out | 13 ++++++++-----
 test-suite/output/UnivBinders.out | 16 +++++++++++++---
 vernac/prettyp.ml                 | 28 +++++++++++++++++++++-------
 3 files changed, 42 insertions(+), 15 deletions(-)
```

### Small Coq file to reproduce the bug

```coq
Module Type T.
  #[projections(primitive)]
  Record t := of_unit { to_unit : unit }.
End T.

Module M.
  Include T.
  Print to_unit.
End M.
```

### Version of Coq where this bug occurs

8.19.0, 8.19.1

### Last version of Coq where the bug did not occur

8.18, master

### PR DESCRIPTION
**Pull request by Janno**
Fixes / closes #18769

- [x] Added / updated **test-suite**.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

File: kernel/mod_subst.ml [hunk 1]
```diff
@@ -345,7 +345,14 @@ let rec map_kn f f' c =
...
       | Const kn -> (try f' kn with No_subst -> c)
       | Proj (p,r,t) ->
-          let p' = Projection.map f p in
+          (* TODO: how to do this nicely? *)
+          let f_const (c : Constant.t) =
+            match kind (f' (c, UVars.Instance.empty)) with
+            | Const (c', i) -> assert (UVars.Instance.is_empty i); c'
+            | exception No_subst -> c
+            | _ -> assert false
+          in
```
Comment (Janno) [inline kernel/mod_subst.ml:354]: This is a little hacky but I don't seem to have access to a usefully typed function in this context that I could call instead.

File: kernel/names.ml [hunk 2]
```diff
@@ -917,11 +917,13 @@ struct
       if npars == npars' then p
       else {p with proj_npars = npars'}
 
-    let map f p =
+    let map f_ind f_const p =
```
Comment (SkySkimmer) [inline kernel/names.ml:920]: Alternatively don't take a f_const here and instead rebuild the constant when `ind' != ind`

Comment (SkySkimmer) [reply kernel/names.ml:920]: also we could expose a Projection.canonize instead of using `map`

Comment (Janno) [reply kernel/names.ml:920]: That seems easier and less invasive than my change.

Comment (Janno) [reply kernel/names.ml:920]: Github is not loading new comments automatically for some reason so I only saw your second comment after I responded to the first. I am not sure how `canonize` will help with substitution. Is the idea to recompute the constant in `canonize`?

Comment (SkySkimmer) [reply kernel/names.ml:920]: I see that half your changes are about code trying to canonize, so I think we should expose that as an API instead of reimplementing it everywhere.

Comment (SkySkimmer) [reply kernel/names.ml:920]: call it a mildly related cleanup if you want

Comment (Janno) [reply kernel/names.ml:920]: I think that type of cleanup probably requires deeper understand of the code that I do not have. I was very happy to come up with the changes I have here and I could probably implement the solution that recomputes the name and doesn't change the signature of `map` but I don't think I can easily clean up the code that is there already.

Comment (Janno) [reply kernel/names.ml]: I implemented the proposal of recomputing the projection.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot run full ci
