### PR TITLE
Fix #9526: Registering inductives for primitive integers doesn't check enough

### LINKED ISSUE #9526: Registering inductives for primitive integers doesn't check enough
~~~coq
Primitive int := #int63_type.

Polymorphic Inductive badcarry (A:Type) : Type :=
| C0: A -> badcarry A
| C1: A -> badcarry A.
Register badcarry as kernel.ind_carry.
(* shouldn't be accepted, or kernel should support univ polymorphic carry *)

Primitive addc := #int63_addc.

Check addc _ _ : _.
(* Error: Conversion test raised an anomaly: Anomaly "Universe Var(0) undefined." *)
~~~
I don't know exactly how permissive the check should be, eg should we accept
~~~coq
(* currently accepted *)
Inductive badcarry (A:Type) : Prop :=
| C0: A -> badcarry A
| C1: A -> badcarry A.

(* currently rejected *)
Inductive badcarry (A:Set) : Set :=
| C0: A -> badcarry A
| C1: A -> badcarry A.

(* currently accepted *)
Inductive badcarry : Type -> Type  :=
| C0: forall A, A -> badcarry A
| C1: forall A, A -> badcarry A.
~~~

Of course this isn't limited to carry.

### PR DESCRIPTION
**Pull request by maximedenes**
@SkySkimmer I'd need your help to check that the sort is not `Prop`.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Does the kernel actually care if the sort is Prop? As far as I can tell it only cares that it can instantiate the types and constructors, not that it can destruct them.

File: kernel/safe_typing.ml [hunk 1]
```diff
@@ -1194,39 +1194,46 @@ let register_inline kn senv =
   let cb = {cb with const_inline_code = true} in
   let env = add_constant kn cb env in { senv with env}
 
-let check_register_ind (mind,i) r env =
-  let mb = Environ.lookup_mind mind env in
-  let check_if b s =
+let check_register_ind ind r env =
+  let (mb,ob as spec) = Inductive.lookup_mind_specif env ind in
```
Comment (SkySkimmer) [inline kernel/safe_typing.ml]: If we do care you can ask that `List.mem Sorts.(family_eq InType) ob.mind_kelim` ie the inductive is not squashed.

BTW usually we call the one_inductive_body "mip" (p for packet since it comes from mind_packets) not "ob"

**Comment by maximedenes** [comment]
> Does the kernel actually care if the sort is Prop? As far as I can tell it only cares that it can instantiate the types and constructors, not that it can destruct them.

Fair enough, let's drop the check.

**Comment by maximedenes** [comment]
@vbgl can you be the assignee?

**Comment by SkySkimmer** [comment]
For some reason you have unicode 0xFFFC "OBJECT REPLACEMENT CHARACTER" `￼` after the `:` in your commit message.

**Comment by vbgl** [comment]
The failure of equations in CI seems unrelated.

**Review by vbgl — APPROVED** [review]
