### PR TITLE
Stop inlining abstracted subproofs in tactics in terms.

### LINKED ISSUE #7905: (transparent_)abstract in tactics in terms should generate a new global identifier
#### Version

8.8.0

#### Description of the problem

This is wrong:
```coq
Check ltac:(refine (_ : Z); transparent_abstract (exact 1)). (* let Top_anonymous_subterm := 1 in Top_anonymous_subterm : Z *)
```
cc @ppedrot

### PR DESCRIPTION
**Pull request by ppedrot**
This is probably going to break some developments like fiat-crypto and friends, so for now I'm just running the CI and if there is too much breakage I'll provide a (deprecated) compatibility flag.

Fixes #7905: abstract in tactics in terms should not inline.

Depends on:
- #21755

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
Hmm, it's the rewriter plugin depending on this precise behaviour. I'm not sure I'm knowledgeable enough abouts its internals to try to fix this directly, calling @JasonGross to the rescue just in case. (After all he was the original reporter of #7905...)

**Comment by JasonGross** [comment]
I'm not sure I would call "raising an anomaly" as "depending on this behavior".  I should really make a version of this bit of code that does the orchestration in Ltac(2) rather than OCaml just so that it's easier to debug.  @ppedrot would you be willing to provide a backtrace of the anomaly (and maybe find the Ltac(2) mutable debug bool and set it to true so that we get some info about what stages completed and what raised the anomaly)?

I don't recall deliberately using abstract in tactics in terms anywhere (maybe to cache things under binders in Constr.in_context during reification???), so just knowing where the anomaly got raised (and ideally where the missing universe first got introduced, though maybe this is too much printf-debugging to do) would narrow things down significantly.

**Comment by JasonGross** [comment]
(Note that thing thing the plugin does is: call some Ltac to get the signature of a bunch of inductives, as the inductives to the env, then call some more Ltac to add a bunch of constants to the env.  It would be pretty easy to invert the flow by adding a tactic that adds the inductive to the env and doing everything from Ltac.)

**Comment by SkySkimmer** [comment]
This produces an undefined universe anomaly in 9.1 and in this PR but not in 9.2 and master:
~~~coq
Check ltac:(abstract exact Type).
~~~
Maybe fixing it would also fix rewriter.

EDIT not sure if it's actually related (seems Check specific) but should still be fixed

**Comment by SkySkimmer** [comment]
this is also broken by this PR:
~~~coq
Definition bar := ltac:(abstract exact ltac:(abstract exact Type)).
(* Error: The label ltac_gen_subproof is already declared. *)
~~~

**Comment by ppedrot** [comment]
CI is green after the minimal patch properly adding the constraints in build_by_constant. I'm a bit wary of the potential performance impact of this one-liner though so @coqbot bench

**Comment by JasonGross** [comment]
Do we have any test of `par: abstract` in the test suite?  (Does `par` correctly communicate side effects?)

**Comment by SkySkimmer** [comment]
syntactic `par: abstract` is handled specially, `par: some tactic that calls abstract` is known broken

**Comment by ppedrot** [comment]
Nothing out of the ordinary in the bench, I'll fix the bugs mentioned above and undraft this PR when done.

**Comment by ppedrot** [comment]
Given that the change is backwards compatible even for the tricky devs from the CI, do you people think it is worthwhile to introduce a (deprecated) flag to activate the old behaviour?

**Comment by SkySkimmer** [comment]
If it's not a lot of work you can do it but it's not a priority IMO

**Comment by ppedrot** [comment]
@SkySkimmer should be ready.

File: tactics/abstract.ml [hunk 1]
```diff
@@ -106,3 +106,10 @@ let abstract_subproof ~opaque tac =
 
 let tclABSTRACT ?(opaque=true) name_op tac =
   abstract_subproof ~opaque ~name_op tac
+
+let { Goptions.get = get_inline_abstract_subproof } =
+  Goptions.declare_bool_option_and_ref
+    ~depr:(Deprecation.make ~since:"9.3" ())
```
Comment (SkySkimmer) [inline tactics/abstract.ml:112]: we are supposed to add a new compat file when we add a new deprecation version (in this case add Rocq92)
the compat file could also set this new option btw

File: theories/Corelib/Compat/Rocq92.v [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+(*         *     GNU Lesser General Public License Version 2.1          *)
+(*         *     (see LICENSE file for the text of the license)         *)
+(************************************************************************)
+
+(** Compatibility file for making Rocq act similar to Coq v9.1 *)
+
+(* When adding Rocq93.v, uncomment the following line *)
+(* Require Export Corelib.Compat.Rocq93. *)
+
+#[warning="-deprecated"]
```
Comment (SkySkimmer) [inline theories/Corelib/Compat/Rocq92.v]:
```suggestion
#[export] Set Warnings "-deprecated-since-9.3".

#[export]
```

File: theories/Corelib/Compat/Rocq92.v [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+(*         *      The Rocq Prover / The Rocq Development Team           *)
+(*  v      *         Copyright INRIA, CNRS and contributors             *)
+(* <O___,, * (see version control and CREDITS file for authors & dates) *)
+(*   \VV/  **************************************************************)
+(*    //   *    This file is distributed under the terms of the         *)
+(*         *     GNU Lesser General Public License Version 2.1          *)
+(*         *     (see LICENSE file for the text of the license)         *)
+(************************************************************************)
+
+(** Compatibility file for making Rocq act similar to Coq v9.1 *)
```
Comment (proux01) [inline theories/Corelib/Compat/Rocq92.v]:
```suggestion
(** Compatibility file for making Rocq act similar to Coq v9.2 *)
```

File: theories/Corelib/Compat/Rocq91.v [hunk 4]
```diff
@@ -11,6 +11,6 @@
 (** Compatibility file for making Rocq act similar to Coq v9.1 *)
 
 (* When adding Rocq92.v, uncomment the following line *)
```
Comment (proux01) [inline theories/Corelib/Compat/Rocq91.v]: This line can now be removed

File: theories/Corelib/Compat/Rocq91.v [hunk 5]
```diff
@@ -8,9 +8,8 @@
 (*         *     (see LICENSE file for the text of the license)         *)
 (************************************************************************)
 
-(** Compatibility file for making Rocq act similar to Coq v9.1 *)
+(** Compatibility file for making Rocq act similar to Coq v9.2 *)
```
Comment (proux01) [inline theories/Corelib/Compat/Rocq91.v]: This should remain 9.1

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now
