### PR TITLE
Fix erroneous implicits-in-term warning

### LINKED ISSUE #12651: Erroneous implicits-in-term warning
~~~coq
Set Warnings "+implicits-in-term".
Definition thing : forall {A}, A -> A := fun A a => a.
~~~
should not fail.

I'll make a patch.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #12651

### CODE REVIEW

File: vernac/comDefinition.ml [hunk 1]
```diff
@@ -32,9 +32,11 @@ let check_imps ~impsty ~impsbody =
   match impsty, impsbody with
   | a1 :: impsty, a2 :: impsbody ->
     (match a1.CAst.v, a2.CAst.v with
-    | None , None -> aux impsty impsbody
-    | Some _ , Some _ -> aux impsty impsbody
-    | _, _ -> warn_implicits_in_term ?loc:a2.CAst.loc ())
+    | None , None | Some _, None -> aux impsty impsbody
+    | Some (_,b1) , Some (_,b2) ->
```
Comment (SkySkimmer) [inline vernac/comDefinition.ml:36]: We could also compare the names (to fail eg `Definition foo : forall {A}, A -> A := fun {B} b => b.`) but not sure if useful.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
I'll add most fixes to 8.12 @Zimmi48 , we can then discuss if we are good on them for backporting on Jeudi.

**Review by herbelin — APPROVED** [review]
This is a change of semantics wrt what I initially intended (see [#12651](https://github.com/coq/coq/issues/12651#issuecomment-655071867)) but the change makes sense after all.
