### PR TITLE
Fix #10268: vio2vo produces incorrect term when discharging.

### LINKED ISSUE #10268: vio2vo produces incorrect term when discharging
~~~coq
Section Foo.
  Variable A : Type.

  Definition bla := A.

  Variable B : bla.

  Lemma blu : {X:Type & X}.
  Proof using A B.
    exists bla;exact B.
  Qed.
End Foo.
~~~
after coqc -quick and coqc -vio2vo, coqchk says
~~~
  checking cst:Test.foo.blu
Fatal Error: Type error: CantApplyNonFunctional
~~~

### PR DESCRIPTION
**Pull request by ppedrot**
We do not partially abstract the section info. Instead, we reuse the same code in cook_constr and cook_constant and pass the same section info.

Fixes #10268.

### CODE REVIEW

File: kernel/cooking.ml [hunk 1]
```diff
@@ -217,6 +202,18 @@ let lift_univs cb subst auctx0 =
...
 
+let cook_constr { Opaqueproof.modlist ; abstract } c =
+  let cache = RefTable.create 13 in
+  let abstract, usubst, abs_ctx = abstract in
+  (* For now the STM only handles deferred computation of monomorphic
+    constants. The API will need to be adapted when it's not the case
+    anymore. *)
+  let () = assert (AUContext.is_empty abs_ctx) in
+  let expmod = expmod_constr_subst cache modlist usubst in
+  let hyps0 = Context.Named.map expmod abstract in
```
Comment (gares) [inline kernel/cooking.ml]: Hyps0 used to be used later on in the original code you copied. Here, and also there given the other change, there is no point in keeping this value alive. I think you should call it hyps so that it is shadowed.

**Review by gares — CHANGES_REQUESTED** [review]

File: kernel/cooking.ml (hunk 1 above)
Comment (ppedrot) [reply kernel/cooking.ml]: Fair enough. I was trying to keep the code of `cook_constr` and `cook_constant` as close as possible to easily remember to factorize them when implementing the delayed type-checking of polymorphic constants, but it doesn't hurt messing a bit with it already.

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
@gares you should assign.

**Comment by gares** [comment]
@maximedenes  can you take a look? I'd assign and merge...
