### PR TITLE
Close #11935: section variables do not have universe instances.

### LINKED ISSUE #11935: section variables ignore user-given universe instances
This should fail:
~~~coq
Section S.
  Variable A : Prop.

  Check A@{Type}.
End S.
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by gares** [comment]
Question, does it work for Ltac variables (instantiated as section variables)?

File: pretyping/pretyping.ml [hunk 1]
```diff
@@ -436,7 +436,15 @@ let pretype_ref ?loc sigma env ref us =
   match ref with
   | GlobRef.VarRef id ->
       (* Section variable *)
-      (try sigma, make_judge (mkVar id) (NamedDecl.get_type (lookup_named id !!env))
+    (try
+       let ty = NamedDecl.get_type (lookup_named id !!env) in
+       (match us with
+        | None | Some [] -> ()
```
Comment (ppedrot) [inline pretyping/pretyping.ml]: Why don't you forbid writing an instance at all? AFAIK `@{}` still means something even for polymorphic constants.

Comment (SkySkimmer) [reply pretyping/pretyping.ml]: `@{}` ensures no universes are generated imo, which is valid for variables too

**Comment by gares** [comment]
Le me be more explicit: What about
```coq
Ltac foo x := x@{u}.
Section A. Variable B. Goal True. foo A.
```

**Comment by SkySkimmer** [comment]
~~~coq
Ltac foo x := x@{u}.
~~~
syntax error `.` expected (position before the `@`)

~~~coq
Ltac foo x := exact x@{u}.
~~~
says `Variable x cannot have a universe instance` since at least 8.9

**Comment by SkySkimmer** [comment]
Waiting for https://github.com/HoTT/HoTT/pull/1313

File: pretyping/pretyping.ml (hunk 1 above)
Comment (ppedrot) [reply pretyping/pretyping.ml:444]: This is true when *declaring* a variable, but not when *interpreting* it. I believe we should fail in this piece of code.

Comment (SkySkimmer) [reply pretyping/pretyping.ml:444]: >This is true when declaring a variable, but not when interpreting it

?? Seems true when interpreting too (after this PR). 

I don't see why we would fail.

Comment (ppedrot) [reply pretyping/pretyping.ml:444]: This piece of code drops the instance, so I don't understand what is the point of allowing `@{}` when we know this is irrelevant. What I agree with is that we should be able to write `Let x@{} := ...` to ensure that no universe constraints are generated.

**Comment by SkySkimmer** [comment]
Ready

File: pretyping/pretyping.ml (hunk 1 above)
Comment (SkySkimmer) [reply pretyping/pretyping.ml:444]: It doesn't drop the instance, it checks that it has the correct size.

Comment (ppedrot) [reply pretyping/pretyping.ml:444]: ... and drops it afterwards, which means that it was irrelevant.

Comment (SkySkimmer) [reply pretyping/pretyping.ml:444]: I don't know what you mean by drop tbh

Comment (ppedrot) [reply pretyping/pretyping.ml:444]: Note that I don't think this is blocking the PR, I just find this introduces a discrepancy between the user-facing representation and what actually exists at the level of kernel terms.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Will merge when CI terminates.

**Comment by ppedrot** [comment]
I think I won't backport this, since it introduces breaking changes.
