### PR TITLE
Fix #13732: Implicit Type vs universes

### LINKED ISSUE #13732: Regression due to PR #13299 "Conversion test raised an anomaly"
#### Description of the problem

The nightly CI of Actris (an Iris-related project) fails since Jan 10. It gives the following error:

```
Conversion test raised an anomaly:
Anomaly "Universe actris.channel.channel.75 undefined."
Please report at http://coq.inria.fr/bugs/.
```

while type checking the statement of the following lemma (https://gitlab.mpi-sws.org/iris/actris/-/blob/master/theories/channel/channel.v#L258):

```coq
Lemma send_spec_tele {TT} c (tt : TT)
      (v : TT → val) (P : TT → iProp Σ) (p : TT → iProto Σ) :
  {{{ c ↣ (<!.. x > MSG v x {{ P x }}; p x) ∗ P tt }}}
    send c (v tt)
  {{{ RET #(); c ↣ (p tt) }}}.
```

See https://gitlab.mpi-sws.org/iris/actris/-/jobs/109417

The nightly CI runs against Coq master. The only Coq commit on Jan 9 is https://github.com/coq/coq/pull/13299, so I think that pull request caused a regression.

Since the error message provides limited information, I am not sure how to turn this into a smaller example. If you have any suggestions on how to minimize, I am happy to help. Otherwise I suggest to compile std++ master, Iris master, and Actris master against Coq master, and then you can replicate the error message.

#### Coq Version

Coq master 723440611965ccdecfd56e61c8f1f8618a08841d

/cc @RalfJung @jashug

### PR DESCRIPTION
**Pull request by SkySkimmer**
This returns to the previous behaviour of Implicit Type forgetting
universes.

`Implicit Type T : Type@{u}.` may be confusing as it is equivalent to
`: Type`, but until we have a better idea of what to do with anonymous
types I see no other solution, especially in the short term to fix the
bug.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Although I believe the bug could not be as easily triggered until yesterday's master, the underlying issue has been present since 8.13 so submitting for 8.13.1.

File: vernac/vernacentries.ml [hunk 1]
```diff
@@ -1458,7 +1458,10 @@ let vernac_reserve bl =
     let env = Global.env() in
     let sigma = Evd.from_env env in
     let t,ctx = Constrintern.interp_type env sigma c in
-    let t = Detyping.detype Detyping.Now false Id.Set.empty env (Evd.from_ctx ctx) t in
+    let t = Flags.without_option Detyping.print_universes (fun () ->
+        Detyping.detype Detyping.Now false Id.Set.empty env (Evd.from_ctx ctx) t)
```
Comment (ppedrot) [inline vernac/vernacentries.ml:1462]: It's quite confusing that something called `print_universe` affects the behaviour of pretyping...

**Review by ppedrot — APPROVED** [review]
This looks very hackish to me, but it's OK as a hotfix. This should ideally use argument flags rather than a hardcoded ill-named reference, and we shouldn't even go through detyping to start with.

File: vernac/vernacentries.ml (hunk 1 above)
Comment (SkySkimmer) [reply vernac/vernacentries.ml:1462]: Is detyping not part of printing?

Comment (ppedrot) [reply vernac/vernacentries.ml:1462]: Pretyping, not detyping. The root of the problem is that pattern interpretation goes through detyping.

**Comment by herbelin** [comment]
Looks good!

> `Implicit Type T : Type@{u}.` may be confusing as it is equivalent to `: Type`, but until we have a better idea of what to > do with anonymous types I see no other solution, especially in the short term to fix the bug.

To still allow `Implicit Type T : Type@{u}` when `u` is a (predeclared) global level, what about falling back on `None` in `detype_instance` when the level is not declared in the evar map canonically generated from the global environment, rather than depending on `print_universes`? I.e. passing `(Evd.from_env (Global.env()))` instead of `(Evd.from_ctx ctx)` to `detype` and not using `print_universes`.

**Comment by SkySkimmer** [comment]
@ppedrot @herbelin @coq/vernac-maintainers what's this waiting for?
