### PR TITLE
Fix coqchk on files containing global sorts

### LINKED ISSUE #20920: coqchk broken on global sorts (missing values update)
eg on a file containing `Sort s.` we get
~~~
Context: library/fld=0/compiled/fld=3/Set.t/fld=1/elem/qvar/tag=2
#2(#0(#0("foo",#0("Tmp",0)),"s"))
 failed!]

Fatal Error: Failure: Validation failed: sum: unexpected tag (in tag=2).
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #20920

### CODE REVIEW

File: kernel/environ.ml [hunk 1]
```diff
@@ -488,7 +488,7 @@ let add_universes_set ~strict ctx g =
 let push_context_set ?(strict=false) ctx env =
   map_universes (add_universes_set ~strict ctx) env
 
-let push_qualities ctx env =
+let unsafe_push_qualities ctx env =
```
Comment (ppedrot) [inline kernel/environ.ml]: I'm not convinced by the naming convention, most functions in Environ do not check whether the binding already exists yet without it being written on the label.

Comment (SkySkimmer) [reply kernel/environ.ml]: this change isn't actually needed for this PR so I'll remove it

File: test-suite/bugs/bug_20914.v [hunk 2]
```diff
@@ -0,0 +1,6 @@
+Sort s.
+
+Polymorphic Definition foo@{s;u} (A:Type@{s;u}) (a:A) := a.
+
+(* slightly eta expanded so "s" appears in a sort and in the instance *)
+Definition bla A := foo@{s;Set} A.
```
Comment (ppedrot) [inline test-suite/bugs/bug_20914.v:6]: Just to err on the safe side, maybe having a sort-poly inductive type rather that the identity function would be more robust. (Just a suggestion though.)

Comment (SkySkimmer) [reply test-suite/bugs/bug_20914.v:6]: robust to what?

Comment (ppedrot) [reply test-suite/bugs/bug_20914.v:6]: To it appearing in the type. But OK, maybe I'm just being paranoid.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
