### PR TITLE
Module subtyping: primitive fields cannot be implemented

### LINKED ISSUE #18503: Primitives are incorrectly considered convertible to anything by module subtyping
~~~coq
Require Import PrimInt63.
Open Scope int63_scope.

Module Type T.
  Primitive bar := #int63_sub.
End T.

Module F(X:T).
  Definition foo : X.bar 1 1 = 0 := eq_refl.
End F.

Module M.
  Definition bar := land.
End M.

Module N := F M. (* "bar := land" is subtype of "bar := #int63_sub"? *)

Lemma bad : False.
Proof.
  pose (f := fun x => eqb x 1).
  assert (H:f 1 = f 0) by (f_equal;exact N.foo).
  change (true = false) in H.
  inversion H.
Qed.

Print Assumptions bad.
(* Axioms:
land : int -> int -> int
int : Set
eqb : int -> int -> bool
*)
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #18503

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

File: kernel/subtyping.ml [hunk 1]
```diff
@@ -246,18 +246,23 @@ let check_constant (cst, ustate) trace env l info1 cb2 subst1 subst2 =
       (* Now we check the bodies:
          - A transparent constant can only be implemented by a compatible
            transparent constant.
+         - A primitive cannot be implemented.
+           (We could try to allow implementing with the same primitive,
+            but for some reason we get cb1.const_body = Def,
```
Comment (JasonGross) [inline kernel/subtyping.ml:251]: Presumably this is "NB: cb1 might have been strengthened and appear as transparent.", and the way to handle it would be to have conv_check check the constant is convertible with the primitive?  But maybe we want to forbid it anyway the same way we seem to forbid
```coq
Module A. Axiom X : Set. End A.
Module Type AT. Definition X : Set := A.X. End AT.
Module F (Av : AT). Definition Y := Av.X. End F.
Module G := F A.
```
(This does get rejected, right?  I'm not in front of a computer right now so can't check.)

**Review by mattam82 — APPROVED** [review]
Indeed without use cases, I think we shall not try and equate the primitive implementations. So, LGTM!

**Comment by SkySkimmer** [comment]
merge?

**Comment by SkySkimmer** [comment]
ping @mattam82

**Comment by SkySkimmer** [comment]
ping @mattam82

**Comment by mattam82** [comment]
@coqbot merge
