### PR TITLE
Fixing #9893. "Specialize with" would not support hyps type containing letins. 

### LINKED ISSUE #9893: assertion failure on `specialize P with (1 := A)` if `P` contains a let
```
Axiom foo: forall (m1 m2: nat), let n := 2 * m1 in m1 = m2 -> True.

Goal False.
  pose proof foo as P.
  assert (2 = 2) as A by reflexivity.
  specialize P with (1 := A).
```

leads to

```
Error: Anomaly "File "tactics/tactics.ml", line 3000, characters 18-24: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

If I do `cbv zeta in P.` before the `specialize`, it works.

Expected behavior: Perform enough zeta reduction (but not more than strictly needed) to make `specialize` work.

Coq version: master commit 424c1973e96dfbf3b2e3245d735853ffa9600373 of Mon Apr 1 19:40:53 2019 +0000

### PR DESCRIPTION
**Pull request by Matafou**
Letins were not supported inside the type of the specialized
hypothesis (or constant).

**Kind:**  bug fix
closes #9893

- [ X] Added test-suite
(Added two tests in success/specialize.v).

### CODE REVIEW

**Comment by Matafou** [comment]
I documented a bit more the code.

File: tactics/tactics.ml [hunk 1]
```diff
@@ -3038,8 +3050,13 @@ let specialize (c,lbind) ipat =
         | Context.Rel.Declaration.LocalAssum _::lp' , t::l' ->
           let sigma,hd' = rebuild_lambdas sigma lp' (args@[t]) hd l' in
           sigma,hd'
+        | Context.Rel.Declaration.LocalDef _::lp' , _ ->
+           (* letins are have been reduced in l and should anyway not
+              correspond to an arg, we ignore them. *)
+          let sigma,hd' = rebuild_lambdas sigma lp' args hd l in
+          sigma,hd'
```
Comment (Matafou) [inline tactics/tactics.ml]: This is the real code change. Others are mostly comments and one simplification (thd vs c_hd which are the same).

Comment (ppedrot) [inline tactics/tactics.ml]: So this means we are not reabstracting over the let-ins right? This is probably fine.

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
Please use a more informative title for your commit and PR such that looking at the shortlog / PR list doesn't require loading issues from github.

File: tactics/tactics.ml (hunk 1 above)
Comment (Matafou) [reply tactics/tactics.ml]: letins dont need to be abstracted (they do not correspond to an application to the hypothesis).
Moreover the line
```
let clause = make_clenv_binding env sigma (c,typ_of_c) lbind in
```
removes the letins from the clause anyway. So the letins are there in lprod but not in l.

Comment (ppedrot) [reply tactics/tactics.ml]: My point was that your code behaves as if you had performed a ζ reduction on the type of the term being specialized, i.e. let-ins in the middle of the telescope get expanded. Anyways I don't think it matters much.

Comment (Matafou) [reply tactics/tactics.ml]: Yes and no.

- You are right the letins are reduced from the start by make_clenv_binding. I would rather avoid that and keep the letins in the type but I don't think we can build a clause and solve it without removing the letins. Can we?
- Even if we find a way to not reduce the letins they do not correspond to arguments of the hypothesis. So we would still ignore them when reabstracting stuff.

**Review by ppedrot — APPROVED** [review]

**Review by SkySkimmer — DISMISSED** [review]
The commit message's first line (what you see in shortlog) is still rather opaque.

**Comment by Matafou** [comment]
> The commit message's first line (what you see in shortlog) is still rather opaque.

You mean in the commit itself? Ok I will update the commit messages once I have all remarks.
There is also a typo in the comments.

**Comment by Matafou** [comment]
Changed one typo in comment + more explicit shortlog.

**Comment by Matafou** [comment]
Backporting this fix to 8.10 and 8.11 is to be considered I suppose but I am not familiar with coq's backport policy.

**Comment by Zimmi48** [comment]
> I am not familiar with coq's backport policy

See Sections 5.3-5.4 of my thesis :laughing: 

I've put the appropriate milestone so that the 8.11 RM knows that this is considered for inclusion. There is no 8.10.3 release on the horizon currently, so this is probably not going to be backported further than this.

**Comment by Matafou** [comment]
I have pushed a better commit message. Seems ready to merge.
Thanks all.
