### PR TITLE
[ocaml] Remove Custom Backtrace module in favor of OCaml's

### LINKED ISSUE #6446: Future of Coq's internal `Backtrace` module
I am using OCaml's native backtraces for some stuff and indeed they seem better than what Coq does provide via it's private `Backtrace` module. In particular, I see inlined functions. I also see the logic monad operations.

Should we update this module to use newer features? Should we just get rid of it?

### PR DESCRIPTION
**Pull request by ejgallego**
As suggested by Pierre-Marie Pédrot, this is a more conservative
version of #8771 .

In this commit, we replace Coq's custom backtrace type with OCaml
`Printexc.raw_backtrace`; this seems to already give some improvements
in terms of backtraces [see below] and removes quite a bit of code.

Main difference in terms of API is that backtraces become now
first-class in `Exninfo`, and we seek to consolidate thus the
exception-related APIs in that module.

We also fix a bug in `vernac.ml` where the backtrace captured was the
one of `edit_at`.

Closes #6446

Example with backtrace from https://github.com/coq/coq/issues/11366

Old:

```
raise @ file "stdlib.ml", line 33, characters 17-33
frame @ file "pretyping/coercion.ml", line 406, characters 24-68
frame @ file "list.ml", line 117, characters 24-34
frame @ file "pretyping/coercion.ml", line 393, characters 4-1004
frame @ file "pretyping/coercion.ml", line 450, characters 12-40
raise @ unknown
frame @ file "pretyping/coercion.ml", line 464, characters 6-46
raise @ unknown
frame @ file "pretyping/pretyping.ml", line 839, characters 33-95
frame @ file "pretyping/pretyping.ml", line 875, characters 50-94
frame @ file "pretyping/pretyping.ml", line 1280, characters 2-81
frame @ file "pretyping/pretyping.ml", line 1342, characters 20-71
frame @ file "vernac/vernacentries.ml", line 1579, characters 17-48
frame @ file "vernac/vernacentries.ml", line 2215, characters 8-49
frame @ file "vernac/vernacinterp.ml", line 45, characters 4-13
...
```

New:

```
Raised at file "stdlib.ml", line 33, characters 17-33
Called from file "pretyping/coercion.ml", line 406, characters 24-68
Called from file "list.ml", line 117, characters 24-34
Called from file "pretyping/coercion.ml", line 393, characters 4-1004
Called from file "pretyping/coercion.ml", line 450, characters 12-40
Called from file "pretyping/coercion.ml", line 464, characters 6-46
Called from file "pretyping/pretyping.ml", line 839, characters 33-95
Called from file "pretyping/pretyping.ml", line 875, characters 50-94
Called from file "pretyping/pretyping.ml" (inlined), line 1280, characters 2-81
Called from file "pretyping/pretyping.ml", line 1294, characters 21-94
Called from file "pretyping/pretyping.ml", line 1342, characters 20-71
Called from file "vernac/vernacentries.ml", line 1579, characters 17-48
Called from file "vernac/vernacentries.ml", line 2215, characters 8-49
Called from file "vernac/vernacinterp.ml", line 45, characters 4-13
...
```

### CODE REVIEW

**Comment by ejgallego** [comment]
Some questions on naming do still remain, it seems to me that:
- we may want to remove `CErrors.push` and instead use `Exninfo.capture`
- we may want to remove `Exninfo.raise` and indeed rename `iraise` to `raise`
- we may want to remove / deprecate all aliases.

**Comment by ejgallego** [comment]
Bench https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/831/

File: clib/exninfo.ml [hunk 1]
```diff
@@ -57,12 +57,29 @@ let rec find_and_remove_assoc (i : int) = function
     if rem == ans then (r, l)
     else (r, (j, v) :: ans)
 
-let iraise e =
+type backtrace = Printexc.raw_backtrace
+let backtrace_to_string = Printexc.raw_backtrace_to_string
+
+let backtrace_info : backtrace t = make ()
```
Comment (ejgallego) [inline clib/exninfo.ml]: One question is whether we should use this or make `info` a record that may store the backtrace directly.

File: clib/exninfo.ml [hunk 2]
```diff
@@ -57,12 +57,29 @@ let rec find_and_remove_assoc (i : int) = function
...
   let id = Thread.id (Thread.self ()) in
-  let () = current := (id, e) :: remove_assoc id !current in
+  let () = current := (id, (e,i)) :: remove_assoc id !current in
   let () = Mutex.unlock lock in
-  raise (fst e)
+  match get i backtrace_info with
+  | None ->
+    raise e
+  | Some bt ->
+    Printexc.raise_with_backtrace e bt
```
Comment (ejgallego) [inline clib/exninfo.ml]: This could be made conditional on `is_recording`. IMHO it is worth to raise_with_backtrace instead of what we did before.

File: clib/exninfo.mli [hunk 3]
```diff
@@ -34,6 +34,49 @@ val get : info -> 'a t -> 'a option
...
+    should do is something like: {[
+
+    try foo
+    with exn ->
+      let exn = Exninfo.capture exn in
+      match err with
+      | Bar -> bar
+      | err -> baz
+
+    ]}
```
Comment (ejgallego) [inline clib/exninfo.mli]: I think newer OCaml does a bit better here, so we may update the comment.

**Comment by ejgallego** [comment]
@ppedrot would you like to assign this?

File: clib/exninfo.ml [hunk 4]
```diff
@@ -104,3 +117,19 @@ let info e =
...
+
+let capture e =
+  if !is_recording then
+    (* This must be the first function call, otherwise the stack may be
+       destroyed *)
+    let bt = Printexc.get_raw_backtrace () in
+    if debug_reraise then
+      (Printexc.print_raw_backtrace stderr bt;
+       output_string stderr "--------------------------------\n";
+       flush stderr);
```
Comment (ppedrot) [inline clib/exninfo.ml]: I don't think this should stay in production code.

Comment (ejgallego) [reply clib/exninfo.ml]: Removed.

**Review by ppedrot — APPROVED** [review]
LGTM, but I'd like a test to be sure that it works as intended. I am wondering whether using `raise_with_backtrace` is not duplicating the data, as you get it both in the OCaml stack and in the info field.

**Comment by ejgallego** [comment]
> LGTM, but I'd like a test to be sure that it works as intended.

You mean a test like in the test-suite? That may be tricky due to lines changing. I did a bit of testing and indeed seems to work fine, this approach is used in other projects I think (Jane Street?)

> I am wondering whether using `raise_with_backtrace` is not duplicating the data, as you get it both in the OCaml stack and in the info field.

With this approach I think you need to put the backtrace in both places:
- in the stack is needed as we cannot (and we shouldn't) manipulate `raw_backtraces` as we did before
- the info field needs it as it is the way the printer does get it.

We could maybe make `Exninfo.t` a record so we put the backtrace in a regular field instead of the store.

**Comment by ppedrot** [comment]
This seems to work as intended, let's merge.
