### PR TITLE
Make prvect tail recursive (fix #9355)

### LINKED ISSUE #9355: Stack overflow with universe polymorphism
#### Version

8.8.2

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following practical use case suffers from slowness and a stack overflow.

```
(** This file is attached. *)

Require Import UseCase.

(** There are too many universes for the rooster to handle. *)

Time Check Examples.Z_bimodule_laws.
Fail About Examples.Z_bimodule_laws.
Fail Print Examples.Z_bimodule_laws.
```

```
Z_bimodule_laws : Bimodule.laws_of Z_bimodule
Finished transaction in 5.812 secs (5.696u,0.114s) (successful)
The command has indeed failed with message:
Stack overflow.
The command has indeed failed with message:
Stack overflow.
```

#### Notes

Some careful debugging reveals that

* initially, the highest universe level is `0`,
* before proving `Z_bimodule_laws`, the highest universe level is `28375`,
* after proving `Z_bimodule_laws`, the highest universe level is `377562`, and
* after checking `Z_bimodule_laws`, the highest universe level is `676722`.

The situation is

* somewhat worsened by setting `Polymorphic Inductive Cumulativity`,
* slightly improved by setting `Cumulativity Weak Constraints` and
* further improved by setting `Universe Minimization ToSet`,

but not enough to prevent the stack overflow.

#### Attachments

[UseCase.v](https://github.com/coq/coq/files/2773135)

### PR DESCRIPTION
**Pull request by SkySkimmer**
Using a unit test as it's way faster than messing with universes.

You can test with universes by
~~~coq
Set Universe Polymorphism.
Definition x1@{i} := True.
Definition x2 := x1 -> x1.
Definition x3 := x2 -> x2.
Definition x4 := x3 -> x3.
Definition x5 := x4 -> x4.
Definition x6 := x5 -> x5.
Definition x7 := x6 -> x6.
Definition x8 := x7 -> x7.
Definition x9 := x8 -> x8.
Definition x10 := x9 -> x9.
Definition x11 := x10 -> x10.
Definition x12 := x11 -> x11.
Definition x13 := x12 -> x12.
Definition x14 := x13 -> x13.
Definition x15 := x14 -> x14.
Definition x16 := x15 -> x15.
Definition x17 := x16 -> x16.
Definition x18 := x17 -> x17.
Definition x19 := x18 -> x18.

About x19. (* 262144 universes *)
~~~
Note on my machine `About x18.` did not overflow.

### CODE REVIEW

**Comment by JasonGross** [comment]
Should the test-suite get a test case?  Also, in the commit message, it's not clear whether "Note on my machine About x18. did not overflow." is talking about the state of affairs after this commit, or before it.

**Comment by SkySkimmer** [comment]
>In the commit message, it's not clear whether "Note on my machine About x18. did not overflow." is talking about the state of affairs after this commit, or before it.

Changed.

File: lib/pp.ml [hunk 1]
```diff
@@ -284,15 +284,12 @@ let pr_vertical_list pr = function
...
-      let r = pr (i-1) and s = sep () and e = elem i v.(i) in
-      r ++ s ++ e
+  let v = CArray.mapi (fun i x ->
+      let pp = if i = 0 then mt() else sep() in
+      pp ++ elem i x)
+      v
   in
-  let n = Array.length v in
-  if Int.equal n 0 then mt () else pr (n - 1)
+  Ppcmd_glue (Array.to_list v)
```
Comment (ejgallego) [inline lib/pp.ml]: Please use `seq` here instead of the low-level constructor.

**Review by ejgallego — COMMENTED** [review]
Good change, will merge as soon as the nit is fixed.

File: lib/pp.ml (hunk 1 above)
Comment (SkySkimmer) [reply lib/pp.ml]: OK but why?

**Review by ejgallego — APPROVED** [review]
