### PR TITLE
Fix #10779 (hnf normalisation of instance + reification of overloaded operators)  

### LINKED ISSUE #10779: The extensible `zify` tactic reports anomaly when a class instance isn't a head normal form
#### Description of the problem

```coq
Require Import ZArith_base ZifyClasses ZifyInst ZifyBool.

Structure eqType := EqPack { sort :> Type; _ : sort -> sort -> bool }.

Definition eq_op (T : eqType) : T -> T -> bool :=
  match T return T -> T -> bool with @EqPack _ op => op end.

Canonical bool_eqType := @EqPack bool Bool.eqb.
Canonical nat_eqType := @EqPack nat Nat.eqb.

Instance Op_bool_eqb : BinOp Bool.eqb :=
  { TBOp := fun x y => isZero (Z.sub x y);
    TBOpInj := ltac:(now intros x y; destruct x, y) }.
Add BinOp Op_bool_eqb.

Instance Op_eqop_bool : BinOp (@eq_op bool_eqType) :=
  Op_bool_eqb. (* I think this must be a head normal form. *)
Add BinOp Op_eqop_bool.

Goal forall b : bool, eq_op _ b b = true.
Proof.
Fail Zify.zify.
(*
Anomaly "Uncaught exception Failure("Cannot register term Op_eqop_bool")."
Please report at http://coq.inria.fr/bugs/.
 *)
Abort.
```

cc: @fajb

#### Coq Version

master

### PR DESCRIPTION
**Pull request by fajb**
Improve zify so that:
- Instance declarations are normalised in hnf.
- Reification of binary operators of the form f xn ... x3 x2 x1 
  where (f xn ... x3) is declared BinOp.
- Reification of overloaded terms using a conversion test.

**Kind:** bug fix 

Fixes #10779

### CODE REVIEW

**Comment by fajb** [comment]
@pi8027 , when you have some time, could you have a look and tell me if this solves your issues with overloaded operators?

**Comment by vbgl** [comment]
Benchmark results (old: 41f3d8f0b0b6efbb7133cd4e44c70a1d9105c3e9; new: 7bc383683871ecf2c1e9ec049abd450b705f1999). There is something fishy with `flocq`.

~~~
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │
│                        │                         │                                             │                                             │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-math-classes │  218.13  218.66 -0.24 % │      610574268692      609835918109 +0.12 % │      770637930905      770602243040 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-fingroup │   51.78   51.90 -0.23 % │      144416848555      144060298334 +0.25 % │      187196694937      187230293568 -0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-sf-plf │   44.95   45.02 -0.16 % │      126131536033      125946746252 +0.15 % │      162560345122      162300099734 +0.16 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-unimath │ 4086.46 4092.23 -0.14 % │    11380567433377    11399993735532 -0.17 % │    20879858431116    20905411347310 -0.12 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-fiat-crypto-legacy │ 6261.01 6268.05 -0.11 % │    17426081299286    17441140054663 -0.09 % │    28310707780661    28361727903274 -0.18 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-verdi-raft │ 1330.50 1331.69 -0.09 % │     3710104904898     3714961822846 -0.13 % │     5014612948514     5014282956908 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│        coq-lambda-rust │ 1553.62 1554.46 -0.05 % │     4332074670232     4332371396383 -0.01 % │     5674406065456     5673102182837 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fourcolor │ 2171.95 2172.23 -0.01 % │     6057792840465     6057223098444 +0.01 % │    11360721425044    11360543046345 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│   coq-mathcomp-algebra │  165.82  165.83 -0.01 % │      462494919784      461788759155 +0.15 % │      569615355481      569611752233 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-odd-order │ 1443.71 1443.68 +0.00 % │     4024305127881     4022534051931 +0.04 % │     6860070413167     6859951216964 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-solvable │  190.17  190.16 +0.01 % │      530408434874      529375489079 +0.20 % │      705526048957      705544077261 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-hott │  391.44  391.11 +0.08 % │     1064760568621     1063814230265 +0.09 % │     1613684347018     1613702387853 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-fiat-parsers │  654.92  654.16 +0.12 % │     1830627870273     1829227398238 +0.08 % │     2743105081973     2742770030588 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-coquelicot │   77.26   77.17 +0.12 % │      212475963980      212582776058 -0.05 % │      256727181716      256587476291 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-compcert │  779.90  778.97 +0.12 % │     2172385026155     2170584715309 +0.08 % │     2898281589054     2893654776845 +0.16 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-ssreflect │   40.42   40.37 +0.12 % │      112030111341      111907796067 +0.11 % │      135481330108      135498037365 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│     coq-mathcomp-field │  231.75  231.45 +0.13 % │      645815900010      644854723048 +0.15 % │      917471598429      917519597315 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-geocoq │ 1587.64 1585.58 +0.13 % │     4430223390655     4425174940347 +0.11 % │     6442068539964     6442852805644 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-corn │ 1501.63 1499.48 +0.14 % │     4189848365006     4182074921106 +0.19 % │     6133027986482     6129766367906 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-character │  183.35  183.04 +0.17 % │      510411295071      510170247283 +0.05 % │      671035883763      670984874243 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-color │  710.02  708.50 +0.21 % │     1983130003955     1979346559493 +0.19 % │     2338338672575     2337339080933 +0.04 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-bignums │   69.31   69.14 +0.25 % │      190262001267      190330391454 -0.04 % │      252611391748      252540117040 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-verdi │  120.78  120.27 +0.42 % │      335720140195      335414598711 +0.09 % │      420162610027      420188659285 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fiat-core │  114.96  114.35 +0.53 % │      325766336844      325179611926 +0.18 % │      403963688899      403726857389 +0.06 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-flocq │  253.84  247.17 +2.70 % │      704467323931      687634734397 +2.45 % │      893492559647      865068675822 +3.29 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┘
~~~

**Comment by pi8027** [comment]
@fajb Thank you for the great work, again. Additionally, `Require Import ZifyBool` forces users to open `Z_scope`. You probably need to replace the following `Open Scope`s with `Local Open Scope`s. (But this change could break something else.)
```
Fourier_util.v:4:Open Scope R_scope.
RMicromega.v:44:Open Scope R_scope.
ZMicromega.v:26:Open Scope Z_scope.
ZMicromega.v:492:Open Scope Z_scope.
ZMicromega.v:1708:Open Scope Z_scope.
ZifyBool.v:12:Open Scope Z_scope.
ZifyComparison.v:3:Open Scope Z_scope.
ZifyInst.v:18:Open Scope Z_scope.
ZifyMatch.v:110:Open Scope Z_scope.
```

**Comment by fajb** [comment]
@vbgl  thanks for the bench. I hope the last commit fixes the flocq efficiently issue.

@pi8027 thanks. Good to know it seems to work with overloaded operators. 
Let see how it runs with Local scopes..

**Comment by vbgl** [comment]
Bad try. Here are some partial results (old: 41f3d8f0b0b6efbb7133cd4e44c70a1d9105c3e9; new: 41f3d8f0b0b6efbb7133cd4e44c70a1d9105c3e9):

~~~
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │
│                        │                         │                                             │                                             │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fiat-core │  115.43  114.14 +1.13 % │      326102765073      325329741632 +0.24 % │      403986290814      403679701457 +0.08 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-flocq │  257.04  247.23 +3.97 % │      714278502591      687311860254 +3.92 % │      893504847524      865117645809 +3.28 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┘
~~~

**Comment by fajb** [comment]
@vbgl bizarre. Did you missplell the commit (old: 41f3d8f; new: 41f3d8f) ?

**Comment by vbgl** [comment]
My bad: new is bc173876f9a5241cd2bd3dc1d6093fd3d487f67a.

**Comment by vbgl** [comment]
Some benchmark results (old: 397fa7d34e100213855df7f3aa05ce4d497724e1; new: 98a4e6ad0e5c6798b08a5f105436ddac745704f7):

~~~
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │
│                        │                         │                                             │                                             │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-ssreflect │   40.14   40.22 -0.20 % │      110852372469      110882902972 -0.03 % │      134857899555      134849667869 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-coquelicot │   77.18   77.27 -0.12 % │      212284522443      212141960804 +0.07 % │      256684979425      256579313008 +0.04 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│     coq-mathcomp-field │  231.37  231.58 -0.09 % │      644760398931      645054485927 -0.05 % │      919867516940      919631895122 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│   coq-mathcomp-algebra │  164.81  164.92 -0.07 % │      459519901047      459297024923 +0.05 % │      567635576104      567627317492 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-fiat-parsers │  653.71  653.87 -0.02 % │     1830878684663     1829143650872 +0.09 % │     2742406062791     2742256226393 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-geocoq │ 1577.87 1578.24 -0.02 % │     4406518673487     4405541782644 +0.02 % │     6442267769563     6441771348377 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fourcolor │ 2171.14 2171.56 -0.02 % │     6055953450445     6054576924445 +0.02 % │    11360156260965    11359608767259 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-fiat-crypto-legacy │ 6272.38 6273.48 -0.02 % │    17450249525560    17452337146247 -0.01 % │    28327330981276    28337691268345 -0.04 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-verdi-raft │ 1329.59 1328.51 +0.08 % │     3708062481772     3705303346490 +0.07 % │     5014531304232     5014262935886 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│        coq-lambda-rust │ 1553.95 1552.65 +0.08 % │     4329307177894     4327175844583 +0.05 % │     5675529658359     5674838955690 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-unimath │ 4083.42 4079.54 +0.10 % │    11375045525973    11366512425244 +0.08 % │    20879388001181    20879518631484 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-compcert │  778.71  777.97 +0.10 % │     2170399651198     2167236758509 +0.15 % │     2896210484038     2891386329402 +0.17 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-fingroup │   51.43   51.38 +0.10 % │      143254255640      143158040691 +0.07 % │      186654278967      186712459666 -0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-character │  182.18  181.99 +0.10 % │      507401194971      506935013186 +0.09 % │      669803846432      669781149325 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-verdi │  120.83  120.68 +0.12 % │      335129778032      334754080883 +0.11 % │      419862372863      419866932124 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-solvable │  189.36  189.10 +0.14 % │      527673281203      527118740421 +0.11 % │      704546105113      704560812404 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-math-classes │  218.19  217.85 +0.16 % │      608974771195      608592775982 +0.06 % │      770288828199      770275320040 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-bignums │   69.52   69.38 +0.20 % │      190498507630      190428719532 +0.04 % │      252480318577      252425992897 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-corn │ 1506.15 1503.02 +0.21 % │     4201303070398     4194018087159 +0.17 % │     6131882776881     6128355521627 +0.06 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-color │  707.56  705.96 +0.23 % │     1976963519544     1972837195160 +0.21 % │     2338209915212     2336619043423 +0.07 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-odd-order │ 1456.21 1452.84 +0.23 % │     4057928209446     4050065092744 +0.19 % │     6859007261636     6859175069749 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-hott │  393.84  392.10 +0.44 % │     1070426074326     1069211298510 +0.11 % │     1613288105839     1613260534569 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-sf-plf │   44.93   44.73 +0.45 % │      125779673644      125559569233 +0.18 % │      162531158299      162323079808 +0.13 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fiat-core │  114.90  113.88 +0.90 % │      324978015813      324137129406 +0.26 % │      403836919474      403533561095 +0.08 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-flocq │  253.09  246.81 +2.54 % │      703057067038      686755797428 +2.37 % │      892589798100      864373312889 +3.26 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┘
~~~

**Comment by vbgl** [comment]
Some benchmark results (old: e01c9132fc505a3c443bee27d88dcd16a566616f; new: ee56d2804b2635ce6056e9bffc05fa297950c19b):

~~~
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │
│                        │                         │                                             │                                             │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│     coq-mathcomp-field │  227.80  228.46 -0.29 % │      635249579228      636569279316 -0.21 % │      914896284505      914880369740 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-verdi-raft │ 1321.98 1324.26 -0.17 % │     3688566732115     3694025339432 -0.15 % │     5003183926114     5001470206506 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fiat-core │  113.85  114.02 -0.15 % │      325025631957      324138719837 +0.27 % │      405091009145      404373788668 +0.18 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-odd-order │ 1433.43 1435.48 -0.14 % │     3994904534001     4000141015113 -0.13 % │     6852058950165     6852132743309 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-ssreflect │   39.83   39.88 -0.13 % │      110367016898      110296545691 +0.06 % │      134429086830      134437647392 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-verdi │  119.68  119.80 -0.10 % │      332483160116      332585959573 -0.03 % │      418681569579      418387844277 +0.07 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-sf-plf │   44.55   44.58 -0.07 % │      124859074502      125052022198 -0.15 % │      161885212285      161885517776 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fourcolor │ 2171.08 2171.92 -0.04 % │     6055654185818     6058026294827 -0.04 % │    11356080194684    11355858774095 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-solvable │  187.67  187.74 -0.04 % │      523456483734      523587308163 -0.02 % │      702958771764      702963847892 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-geocoq │ 1568.40 1568.97 -0.04 % │     4379199995620     4380076299626 -0.02 % │     6434883798355     6434691171037 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-unimath │ 4063.49 4064.86 -0.03 % │    11314513052776    11320258519082 -0.05 % │    20888748206745    20883866721807 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-bignums │   68.76   68.78 -0.03 % │      189140348178      189107553375 +0.02 % │      252204876909      252102293543 +0.04 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-fingroup │   51.08   51.09 -0.02 % │      142392646872      142421815280 -0.02 % │      186244992521      186186910553 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-character │  179.89  179.92 -0.02 % │      501065320979      501510996501 -0.09 % │      666562724503      666553117124 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-coqprime │  186.77  186.79 -0.01 % │      519369412406      519034751672 +0.06 % │      916096701196      915610505452 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-hott │  389.76  389.62 +0.04 % │     1061562175037     1062177337754 -0.06 % │     1611811263067     1611850061623 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-compcert │  774.00  773.72 +0.04 % │     2156476350739     2154911290804 +0.07 % │     2891847725383     2886782611639 +0.18 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-math-classes │  215.02  214.93 +0.04 % │      600711064657      600897941018 -0.03 % │      765964684763      766006861959 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-fiat-parsers │  647.44  647.06 +0.06 % │     1811115770798     1811529056165 -0.02 % │     2731890559211     2734287057403 -0.09 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-corn │ 1488.71 1487.76 +0.06 % │     4154439689060     4150608436194 +0.09 % │     6120327284269     6117180885670 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-color │  704.13  703.56 +0.08 % │     1969510118772     1967416484625 +0.11 % │     2336202510721     2334588389243 +0.07 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-fiat-crypto-legacy │ 6230.31 6224.68 +0.09 % │    17330210184567    17326574611125 +0.02 % │    28283048702812    28286835564742 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│        coq-lambda-rust │ 1530.22 1527.98 +0.15 % │     4261900085340     4257826872193 +0.10 % │     5658540534303     5650063402246 +0.15 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-coquelicot │   77.27   77.11 +0.21 % │      211860213534      211647477102 +0.10 % │      256489300379      256175894269 +0.12 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│   coq-mathcomp-algebra │  162.67  161.95 +0.44 % │      453415052614      451427367488 +0.44 % │      563307247613      563320456548 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-coqutil │   60.58   60.24 +0.56 % │      168969988754      167764671821 +0.72 % │      205009972389      204943872856 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-flocq │  250.29  244.85 +2.22 % │      696125935815      680321114286 +2.32 % │      884765284933      856526691415 +3.30 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┘
~~~

**Review by vbgl — APPROVED** [review]
Benchmark results are good: the apparent slow-down in “flocq” is to see in light of the previous speed-up brought by the new implementation of “zify”.

File: plugins/micromega/zify.ml [hunk 1]
```diff
@@ -74,24 +79,22 @@ module HConstr = struct
...
-  | Constr.Const (c, u) ->
-     (match Environ.constant_opt_value_in (Global.env ()) (c,u) with
-      | None -> failwith "Add Injection requires a constant (with a body)"
-      | Some c -> (
-        match EConstr.kind evd (EConstr.of_constr c) with
-        | App (c, a) -> Some a
-        | _ -> None ))
-  | _ -> None
-
+  match EConstr.kind evd (Tacred.hnf_constr (Global.env ()) evd i) with
```
Comment (maximedenes) [inline plugins/micromega/zify.ml]: `hnf_constr` is notoriously slow. Any reason not to use standard weak head reduction here instead?

**Comment by maximedenes** [comment]
> Benchmark results are good

They don't seem so good to me. Are we really expecting significant computation time to be spent in computing these head normal forms?

**Comment by vbgl** [comment]
How do you know time in spent in computing HNFs?

**Comment by maximedenes** [comment]
I thought it was what this patch was about. But I don't know. You say that a 2% slowdown seems good: where were you expecting this time to be spent, that justifies it?

**Comment by vbgl** [comment]
Before, the matching process would fail fast on applications with more than two arguments and on applications with two arguments that are not registered as binary operators.

Now, more possibilities are tried: applications with more than two arguments may be an overloaded binary operator; applications with more than one argument may be an overloaded unary operator.

There are just more cases to consider before definitely failing. This is what brings the enhanced functionality of “zify”.

Had this change been part of the initial rewrite of “zify”, you would have said: “what an impressive speed-up”!

**Comment by maximedenes** [comment]
Does it mean that this PR is mixing two orthogonal changes? Wouldn't it make sense to bench them separately?

**Comment by maximedenes** [comment]
In any case, I'd recommend using a `whd_xxx` function (from the kernel, not reductionops!) instead of `hnf_constr`. The latter is not actually computing head normal forms.

**Comment by pi8027** [comment]
> Now, more possibilities are tried: applications with more than two arguments may be an overloaded binary operator; applications with more than one argument may be an overloaded unary operator.

Do you mean constants cannot be overloaded? So for example, `@GRing.zero int_ZmodType` (of MathComp) may not be Z-ified properly. I didn't check it so carefully and don't have time to produce examples for this now. (I'm sorry for mixing up things.)

**Comment by fajb** [comment]
@maximedenes  I can use whd_xxx but I do not think this will have any noticeable impact. This is only done once at the time of the declaration.

@pi8027 I did not think about constants. 
If you declare `@GRing.zero int_ZmodType` it would work.
If you write `@GRing.zero other_convertible_type` it will not. 
If this is needed, a fix similar to binary/unary operators should work. 
This might have some more negative performance impact...
In any case, tell me if you need that.

File: plugins/micromega/zify.ml (hunk 1 above)
Comment (fajb) [reply plugins/micromega/zify.ml]: BTW, what is the "standard" way ? Which function do you refer to exactly ?

**Comment by pi8027** [comment]
@fajb I need to zify `@GRing.zero other_convertible_type` too, but I don't want to force you to implement this. I'm fine to implement it in Ltac by myself.

On the performance issue, your current implementation doesn't seem to be what I meant in https://github.com/coq/coq/issues/10779#issuecomment-534529634:
> In my opinion, what I need here is not the normalisation, but is the term comparison using unification like ssrmatching. I can demonstrate it later by writing some Ltac code.

The head symbol of overloaded operators (e.g., `eq_op` and `GRing.zero`) are always syntactically the same. So one could construct a table of zify instances indexed by these head symbols (including non-overloaded ones) and use it to find instances. For overloaded operators, multiple zify instances can be registered to their head symbols (e.g., `eq_op bool_eqType` and `eq_op nat_eqType` have the same head symbol `eq_op`) so here we need to find the convertible one from them. For non-overloaded operators, only one instance can be registered to their head symbols. So I think ideally there is almost no additional overhead from this mechanism for non-overloaded operators.

**Comment by fajb** [comment]
@pi8027 I may get what you say. There are currently 2 tables, one being dedicated to overloaded operators.
Using a single one  may indeed streamline the code a bit.
I'll have look.

**Comment by vbgl** [comment]
Some benchmark results (old: c5f6186dd42f9eb937154953efeb2378d0bfb0ec; new: 335ea0083177f43951948029472e4b17d2c67834):

~~~
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │
│                        │                         │                                             │                                             │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-ssreflect │   39.94   40.20 -0.65 % │      110404580019      110686611990 -0.25 % │      134531452381      134505519405 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-coqutil │   60.44   60.74 -0.49 % │      168791766467      169392455419 -0.35 % │      206151557841      206124375872 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-odd-order │ 1447.68 1452.92 -0.36 % │     4035325435094     4042802371964 -0.18 % │     6860163154477     6859496833952 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-fingroup │   51.04   51.15 -0.22 % │      142544269375      142898973285 -0.25 % │      186225307143      186206511221 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-solvable │  188.30  188.55 -0.13 % │      524988190501      525909241342 -0.18 % │      703501569321      703451070885 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-character │  180.99  181.22 -0.13 % │      504122617345      505039420946 -0.18 % │      668784516394      668857838065 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-geocoq │ 1572.37 1573.70 -0.08 % │     4391236019222     4394284314067 -0.07 % │     6435002166494     6434696219096 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-color │  704.21  704.66 -0.06 % │     1969575458552     1970014332132 -0.02 % │     2335864037160     2334696630066 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│     coq-mathcomp-field │  229.08  229.15 -0.03 % │      638657628012      638595903945 +0.01 % │      915161964744      915155279849 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-unimath │ 4082.83 4082.96 -0.00 % │    11378096843416    11375452360366 +0.02 % │    20912172675421    20911684092813 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-verdi-raft │ 1324.21 1324.20 +0.00 % │     3694564337666     3693643952646 +0.02 % │     5002879522535     5001724756487 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│   coq-mathcomp-algebra │  162.62  162.60 +0.01 % │      453218165148      453581808625 -0.08 % │      564008381748      564030194173 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-fiat-crypto-legacy │ 6245.87 6244.84 +0.02 % │    17386023266135    17381766618556 +0.02 % │    28276887144085    28288224088131 -0.04 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fourcolor │ 2164.93 2164.51 +0.02 % │     6037565734418     6037663692503 -0.00 % │    11357845916687    11356905753137 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-bignums │   68.96   68.94 +0.03 % │      189131956375      189531692907 -0.21 % │      252225098414      252172484702 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│        coq-lambda-rust │ 1532.38 1530.66 +0.11 % │     4272150883259     4266231041156 +0.14 % │     5651247400211     5650156305539 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-sf-plf │   44.62   44.55 +0.16 % │      125280619034      125207097966 +0.06 % │      161935759449      161942689554 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-compcert │  775.27  774.04 +0.16 % │     2160707135717     2158894080966 +0.08 % │     2891871350842     2886934110453 +0.17 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-corn │ 1493.86 1491.44 +0.16 % │     4168469139731     4164508568274 +0.10 % │     6120798966098     6117902150831 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-fiat-parsers │  650.29  649.00 +0.20 % │     1818330852527     1817394177302 +0.05 % │     2733212947495     2733219465389 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-math-classes │  214.09  213.57 +0.24 % │      597833538583      598353908553 -0.09 % │      760708257538      760651515559 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-coqprime │  185.03  184.46 +0.31 % │      513523049033      512848156191 +0.13 % │      916263313327      915771990405 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-hott │  372.71  371.56 +0.31 % │     1011561729723     1011768079909 -0.02 % │     1544431539553     1544530575325 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-coquelicot │   77.00   76.70 +0.39 % │      211945847151      211331502700 +0.29 % │      256535299398      256241637371 +0.11 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-verdi │  120.27  119.58 +0.58 % │      333805814566      332721816075 +0.33 % │      418772914718      418332794649 +0.11 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fiat-core │  115.27  114.14 +0.99 % │      326223012464      325548616745 +0.21 % │      405550875328      404926196245 +0.15 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-flocq │  251.10  246.91 +1.70 % │      698147666124      685950151354 +1.78 % │      884817237028      856520514541 +3.30 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┘
~~~

**Comment by fajb** [comment]
@vbgl thanks for the bench. I implemented @pi8027 proposal, this reduces the slowdown a bit.
I do not expect the last push to be a significant improvement.
Anyhow, I think the slowdown is acceptable and is the price to pay to provide a `zify` support for `ssreflect`.

**Comment by vbgl** [comment]
Benchmark results (new: d9fe906c12675b2283711bd04407f58286bafa6b; old: 911accd83d0161d1587652af9ec5365943023c98):

~~~
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │
│                        │                         │                                             │                                             │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-coqutil │   60.74   61.15 -0.67 % │      169057974492      170601078384 -0.90 % │      206878661844      207303066669 -0.20 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fiat-core │  114.69  114.95 -0.23 % │      326234360632      326266014368 -0.01 % │      407410337768      406759060684 +0.16 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│     coq-mathcomp-field │  229.13  229.52 -0.17 % │      638682215531      639751680417 -0.17 % │      916747388118      916768632350 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-fingroup │   51.21   51.26 -0.10 % │      142713070913      142919847706 -0.14 % │      185938415447      186012217991 -0.04 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-hott │  372.36  372.69 -0.09 % │     1013378367121     1012722207707 +0.06 % │     1549918019667     1549851470455 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-math-classes │  215.39  215.57 -0.08 % │      601800393177      601453516185 +0.06 % │      763528544342      763539647167 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-coquelicot │   77.52   77.57 -0.06 % │      213075537600      212945517091 +0.06 % │      258289414230      258020501603 +0.10 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-solvable │  189.07  189.18 -0.06 % │      527137062586      527305311688 -0.03 % │      705858750270      705915445453 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-fiat-parsers │  650.13  650.42 -0.04 % │     1820052554697     1820189961074 -0.01 % │     2741480552345     2741531597057 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-character │  181.18  181.22 -0.02 % │      504984252433      504955761051 +0.01 % │      670662262055      670780218620 -0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-odd-order │ 1449.56 1449.55 +0.00 % │     4040510977171     4040860014231 -0.01 % │     6884263001052     6884071612787 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fourcolor │ 2178.57 2178.44 +0.01 % │     6076108907236     6075840281260 +0.00 % │    11366702646291    11366502653549 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-unimath │ 4109.64 4108.88 +0.02 % │    11451752019560    11450261647029 +0.01 % │    21041758218183    21040171530714 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-geocoq │ 1579.74 1578.96 +0.05 % │     4410010704445     4411285666682 -0.03 % │     6463169400290     6463177593083 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-verdi │  120.52  120.46 +0.05 % │      335342763980      334837557570 +0.15 % │      420351460150      420039718308 +0.07 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-corn │ 1497.80 1496.84 +0.06 % │     4181024734454     4178467728647 +0.06 % │     6150761042258     6148985178086 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-sf-plf │   44.81   44.78 +0.07 % │      125538277290      125628691446 -0.07 % │      162769013765      162727494051 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-coqprime │  188.07  187.94 +0.07 % │      522637560514      522572440120 +0.01 % │      917691859650      917155545113 +0.06 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-verdi-raft │ 1331.93 1330.96 +0.07 % │     3717144342408     3712929362344 +0.11 % │     5026502609278     5023794579264 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-compcert │  778.88  778.04 +0.11 % │     2171788814994     2167828319195 +0.18 % │     2903960618983     2897731553061 +0.21 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-fiat-crypto-legacy │ 6363.14 6355.22 +0.12 % │    17716723369470    17689415649891 +0.15 % │    28825022375152    28800598484710 +0.08 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-ssreflect │   40.13   40.07 +0.15 % │      110868305032      110683242574 +0.17 % │      134573428338      134581829969 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│        coq-lambda-rust │ 1535.39 1532.85 +0.17 % │     4279591961024     4272852242601 +0.16 % │     5659661288687     5658052404251 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│   coq-mathcomp-algebra │  163.30  163.02 +0.17 % │      454716941961      454992964379 -0.06 % │      564748539695      564770566581 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-color │  713.38  711.97 +0.20 % │     1994323161577     1990183771848 +0.21 % │     2368269607627     2366871867610 +0.06 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-bignums │   70.34   70.15 +0.27 % │      192746955836      192865771343 -0.06 % │      257113077446      257029818006 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-flocq │  249.96  249.20 +0.30 % │      695200855147      692813441655 +0.34 % │      874995505914      868240569884 +0.78 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┘
~~~

Everyone should be happy now!

**Comment by fajb** [comment]
@vbgl thanks again. I did not expect the results.
I just pushed a squased version. I also hope everyone will be happy.

**Comment by vbgl** [comment]
Maxime, was you complaint about `Tacred.hnd_constr` serious? In its current form it is as good as noise.

**Comment by maximedenes** [comment]
> Maxime, was you complaint about `Tacred.hnd_constr` serious?

I'm not sure what you mean by "serious" here. As I wrote above, `hnf_constr` is essentially call-by-name with some refolding. If there's no special point in using it, kernel call-by-value reduction is more efficient.

> In its current form it is as good as noise.

Sure, call-by-name is not strictly always worse than call-by-value...

**Comment by maximedenes** [comment]
And I meant call-by-need, rather than call-by-value. Also, maybe `hnf_constr` is using simpl rather than cbn, so it is not exactly what I wrote, but also known to be inefficient in some cases.

Bottom line: is there any drawback in using kernel reduction?

**Comment by vbgl** [comment]
IIUC, Frédéric was not able to make sense out of your comment, so he asked you to be more specific about which function to call rather than `Tacred.hnf_constr`.

**Comment by maximedenes** [comment]
I replied above:

> In any case, I'd recommend using a `whd_xxx` function (from the kernel, not reductionops!) instead of `hnf_constr`. The latter is not actually computing head normal forms.

I got the following reply:

> I can use whd_xxx but I do not think this will have any noticeable impact. This is only done once at the time of the declaration.

I don't understand the idea. To me, it reads like: "pathological cases will be rare, so let's use the inefficient function rather than the efficient one". There must be an implicit motivation, but I don't know what it is.

**Comment by ppedrot** [comment]
To add water to the mill, I'd be happy if we ever phase out `hnf_constr` of the Coq code. It is ill-named, quite non-trivial to specify, and utterly inefficient, even notwithstanding the call-by-name vs. call-by-need distinction. I believe it should thus only be used in legacy code.

@maximedenes beware that using by-need vs. by-name can sometimes change the whd normal form of the term being reduced in contrived ways due to sharing. This might matter when matching on the syntax of the arguments corresponding to the stack. I didn't check here if this was the case.

**Comment by fajb** [comment]
@maximedenes I cannot find any function `whd_xxx` working with Econstr.
What is exactly the reduction of type `Econstr.constr -> EConstr.constr` you propose to use ?

PS: We are most probably  wasting our collective time. 
Currently, the function performs a nop and the other use case seems to only unfold a definition.

**Comment by vbgl** [comment]
Pierre-Marie, are you saying that the `hnf` tactic should be deprecated?

**Comment by maximedenes** [comment]
> Pierre-Marie, are you saying that the `hnf` tactic should be deprecated?

The `hnf` tactic does not have a replacement yet...

**Comment by ppedrot** [comment]
Use `Reductionops.clos_whd_flags CClosure.all` if you want the slightly stronger `βδζι`.

**Comment by pi8027** [comment]
@fajb Thank you for great improvements!
