### PR TITLE
Fix #11121: Simultaneous definition of term and notation in custom gr…

### LINKED ISSUE #11121: Simultaneous definition of term and notation in custom grammar
#### Description of the problem

I am having trouble simultaneously defining a term and a notation in a custom grammar. Here is an indicative example:

```
Declare Custom Entry example.

Notation "'[' e ']'" := e (e custom example).
Notation "x" := x (in custom example at level 0, x constr at level 0).

Reserved Notation "'+a' x y" (in custom example at level 10).

Fixpoint add (x y :nat) :=
  match x with
  | 0 =>
    y
  | S x' =>
    S [+a x' y ]
  end

where "'+a' x y" := (add x y).
```

The parser returns the following error.

```
Error: Parsing rule for this notation has to be previously declared.
```

Am I doing something wrong?

#### Coq Version

8.9.0

### PR DESCRIPTION
**Pull request by maximedenes**
This PR tries to clean up the handling of levels in custom entries notations, and provides a new feature as requested in #11121.

Two changes are probably incorrect, I'll add a pointer to them.

- [x] Added / updated test-suite

- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

Equations overlay: https://github.com/mattam82/Coq-Equations/pull/305

### CODE REVIEW

File: interp/constrextern.ml [hunk 1]
```diff
@@ -486,7 +486,7 @@ and apply_notation_to_pattern ?loc gr ((subst,substlist),(no_implicit,nb_to_drop
   function
     | NotationRule (_,ntn as specific_ntn) ->
       begin
-        match availability_of_entry_coercion custom (fst ntn) with
+        match availability_of_entry_coercion custom InConstrEntrySomeLevel with
```
Comment (maximedenes) [inline interp/constrextern.ml:489]: @herbelin I'm not sure what to do here, this is the only place (with the one below) where the notation level is needed from a `NotationRule`.

File: interp/constrextern.ml [hunk 2]
```diff
@@ -1260,7 +1260,7 @@ and extern_notation (custom,scopes as allscopes) vars t rules =
         (* Try availability of interpretation ... *)
         match keyrule with
           | NotationRule (_,ntn as specific_ntn) ->
-             (match availability_of_entry_coercion custom (fst ntn) with
+             (match availability_of_entry_coercion custom InConstrEntrySomeLevel with
```
Comment (maximedenes) [inline interp/constrextern.ml:1263]: Same here as above.

Comment (herbelin) [reply interp/constrextern.ml:1263]: At first view, this is precisely where you need to recover the `entry_level` part of the level found by looking in the `Notgram_ops.level_of_notation` table.

File: vernac/metasyntax.ml [hunk 3]
```diff
@@ -1493,7 +1486,7 @@ let recover_notation_syntax ntn =
         synext_notation = ntn;
         synext_notgram = pa_rule }
     with Not_found ->
-      raise NoSyntaxRule in
+      (let entry = match ntn with (InConstrEntry,_) -> "in constr" | (InCustomEntry e,_) -> "in " ^ e in Feedback.msg_info Pp.(str"recover_notation_syntax: not found " ++ str entry); raise NoSyntaxRule) in
```
Comment (herbelin) [inline vernac/metasyntax.ml:1489]: I don't remember. Won't this `msg_info` print something which should be printed only in debug mode?

File: vernac/metasyntax.ml [hunk 4]
```diff
@@ -1663,36 +1658,46 @@ let add_notation_interpretation env decl_ntn =
...
+   | Some (only_parsing,only_printing,entry) ->
+     Feedback.msg_info Pp.(str"No syntax data, entry " ++ str(match entry with InConstrEntry -> "constr" | InCustomEntry e -> e));
     (* No syntax data: try to rely on a previously declared rule *)
-    let onlyparse = is_only_parsing modifiers in
-    let onlyprint = is_only_printing modifiers in
-    try add_notation_interpretation_core ~local df env c sc onlyparse onlyprint deprecation
+    begin try add_notation_interpretation_core ~local df env entry c sc only_parsing only_printing deprecation
     with NoSyntaxRule ->
       (* Try to determine a default syntax rule *)
+      Feedback.msg_info Pp.(str"No syntax rule");
```
Comment (herbelin) [inline vernac/metasyntax.ml:1697]: Shouldn't it be a debug message?

File: interp/notation.ml [hunk 5]
```diff
@@ -1377,28 +1378,28 @@ let rec insert_coercion_path path = function
       else if shorter_path path path' then path::allpaths
       else path'::insert_coercion_path path paths
 
-let declare_entry_coercion (scope,(entry,_) as specific_ntn) entry' =
-  let entry, lev = decompose_custom_entry entry in
+let declare_entry_coercion (scope,(entry,key)) entry' =
+  let lev = None in
```
Comment (herbelin) [inline interp/notation.ml:1382]: The level should not be discarded. It should instead take the `entry_level` found by looking at `level_of_notation`. Probably not here, but at the call place of `declare_entry_coercion`.

**Review by herbelin — COMMENTED** [review]
In addition to supporting a `custom` modifier in the `where` clause of declarations, this PR simplifies the confusing distinction between `notation_entry_level` vs `notation_entry`. Very nice!

See the detailed review for answers to your questions regarding the places where the levels are actually needed.

File: vernac/metasyntax.ml (hunk 3 above)
Comment (maximedenes) [reply vernac/metasyntax.ml:1489]: Yes, sorry, I simply forgot to remove it.

File: vernac/metasyntax.ml (hunk 4 above)
Comment (maximedenes) [reply vernac/metasyntax.ml:1697]: Same as above, indeed.

File: interp/notation.ml (hunk 5 above)
Comment (maximedenes) [reply interp/notation.ml:1382]: Yes, the problem for this and the other occurrence is that the level map is not available from `interp` (only from `parsing`). I could move it, but unfortunately it also contains the parsing rules (which belong to `parsing`, where they currently are). I could also split in two maps.

Comment (herbelin) [reply interp/notation.ml:1382]: One possibility could be to split the table into one for the parsing rule and another for the level. It would not make a big difference.

**Comment by maximedenes** [comment]
@herbelin One thing I'm wondering about this is: entry coercions (via `availability_of_entry_coercion` and `declare_entry_coercion`) seem to be the only place where interpretation (as opposed to parsing/printing) depends on the level of the notation. Is this true? If yes, what is so special about these coercions?

Sorry if the question is naive, but I'd like to understand this better before changing or not the scope of level-related data.

**Comment by herbelin** [comment]
> One thing I'm wondering about this is: entry coercions (via availability_of_entry_coercion and declare_entry_coercion) seem to be the only place where interpretation (as opposed to parsing/printing) depends on the level of the notation. Is this true? If yes, what is so special about these coercions?

It is used for "uninterpretation", precisely to insert parentheses or coercions from a (possibly custom) entry to another. I think that's right that this is the only place where the level (and entry) of a notation matters (in addition to parsing).

I don't think you have to worry too much. The `interp` directory is connecting `constr_expr` and `glob_constr`. Nothing bad as having a dependency of `interp` on the levels. The dependency was already there and your PR makes it more principled. Looking for coercions only at printing time would be too late because the possibility to use a notation (which is done in `constrextern.ml`) depends on the existence of coercions.

**Comment by maximedenes** [comment]
What is not obvious to me is that the `level` type seems more complex than just the level of notations. It is defined as `notation_entry * entry_level * entry_relative_level list * constr_entry_key list`. In particular, the `constr_entry_key` type is also not in scope of interpretation today (despite the comment saying that it is used for interpretation). Should I make all of this accessible from `interp`?

**Comment by herbelin** [comment]
Indeed, that starts to look like taking a bit arbitrary decisions. I would not mind having `constr_entry_key` (actually used only for error reporting IINM) visible for `interp` but that's true that it is a bit too much in the sense that it is really more about the surface language.

I would say that whatever solution is ok (either moving what provides `constr_entry_key` to `interp` or splitting the table into two tables).

**Comment by maximedenes** [comment]
@herbelin I fixed the previous issues by splitting the map in two (levels vs grammar rules). However, the patch now fails because some notations do not declare a level, due to the following conditional:

https://github.com/coq/coq/blob/34e62d05df4ecd833f87115aa0e986ef7626359e/vernac/metasyntax.ml#L1616

Can you explain a bit the rationale behind it?

**Comment by herbelin** [comment]
> However, the patch now fails

You mean the `funind` failure in `theories/MSets/MSetAVL.v`. How does it come that the level comes in play there?

> Can you explain a bit the rationale behind it?

It is supposed to recover the grammar rule for a notation which already has one. I don't see at once what the problem is. Do you understand what exact change causes the failure?

**Comment by maximedenes** [comment]
> It is supposed to recover the grammar rule for a notation which already has one. I don't see at once what the problem is. Do you understand what exact change causes the failure?

The following example triggers an anomaly:
```coq
Parameter T : Type.
Parameter x : T.
Notation "2" := x.
Definition y := 2.
Print y.
```

The notation does not declare a level, so it is not found in the map. You write "for a notation which already has one", but where does the level come from?

**Comment by herbelin** [comment]
Notations about numbers do not add a grammar rule because they are already parsed by the default rule for parsing numbers. 

If the anomaly is caused by `Print`, this is not related to the parsing rule. Is printing correctly handled by `uninterp_prim_token`? If not, a registration is maybe missing.

What anomaly is raised?

**Comment by maximedenes** [comment]
> Notations about numbers do not add a grammar rule

Sure, but as this patch shows, levels are also needed for interpretation, not just parsing (because of entry coercions). Where's the level of such notations registered?

> What anomaly is raised?

It's a `Not_found` exception when looking up the notation in the levels map.

**Comment by herbelin** [comment]
I see. Then, this anticipates on #11561... The point is that numerals in custom entries are not really supported yet, so `make_notation_entry_level` should take a level only when the grammar is custom (or conversely, that `make_notation_entry_level` does the call to `level_of_notation` itself, and only when custom).

**Comment by maximedenes** [comment]
> `make_notation_entry_level` should take a level only when the grammar is custom

Yes, this is something I was wondering. Why do entry coercions give a special status to `constr`? In particular, why does `availability_of_entry_coercion` require a level for custom entries but not for `constr`?

**Comment by herbelin** [comment]
>  In particular, why does availability_of_entry_coercion require a level for custom entries but not for constr?

Because the coercions between `constr` levels (namely addition of parentheses) is managed in `ppconstr.ml` for `constr` and levels of `constr` are seen as one unique level from the point of view of `constrextern.ml`.

If ever you'd like to anticipate on #11561, the level in constr would be 0 for positive numbers and level of unary `-` for negative ones (i.e. 35 according to `Notations.v`). But since it is optional that a grammar supports numerals, I would simply wait for #11561 and do nothing too elaborated about numerals in this PR.

**Comment by maximedenes** [comment]
@ejgallego The Dune build gives an error message: `Error: Unbound module Gramlib`. Any suggestion on what I should do to fix it?

It is a bit strange, because I didn't have to touch the Makefile-based build.

File: interp/notation.mli [hunk 6]
```diff
@@ -323,6 +325,48 @@ val declare_custom_entry_has_ident : string -> int -> unit
 val entry_has_global : notation_entry_level -> bool
 val entry_has_ident : notation_entry_level -> bool
 
+(** Entry keys for constr notations *)
+
+type side = Left | Right
+
+type production_position =
+  | BorderProd of side * Gramlib.Gramext.g_assoc option
```
Comment (SkySkimmer) [inline interp/notation.mli:333]: make doesn't enforce separation between directories (so you can have a dependency chain like a/a.ml -> b/b.ml -> a/c.ml) but dune does, so you need to add gramlib to interp/dune to do this (currently it's added to the dependencies of parsing/ not interp/)

Comment (SkySkimmer) [reply interp/notation.mli:333]: (or move this part of notation.ml to a parsing/ file if it doesn't need to be in interp/)

File: interp/notation.mli [hunk 7]
```diff
@@ -323,6 +325,48 @@ val declare_custom_entry_has_ident : string -> int -> unit
...
+  | ETPattern of bool * int option (* true = strict pattern, i.e. not a single variable *)
+
+(** Entries level (left-hand side of grammar rules) *)
+
+type constr_entry_key =
+    (production_level * production_position) constr_entry_key_gen
+
+(** Dealing with precedences *)
+
+type level = notation_entry * entry_level * entry_relative_level list * constr_entry_key list
```
Comment (SkySkimmer) [inline interp/notation.mli:358]: AFAICT interp only needs the `Constrexpr.entry_level` part, so maybe the other data should be left in the upper levels such that interp doesn't depend on gramlib.

Comment (maximedenes) [reply interp/notation.mli:358]: Ok, but the data is really the whole thing. This single integer taken out of other level data does not make much sense IMHO. What's the pb with interp depending on gramlib?

Comment (ejgallego) [reply interp/notation.mli:358]: Indeed, as @SkySkimmer pointed out interp doesn't depend on parsing. I guess not a huge problem having `interp` depend on the parsing engine but the idea was to enforce a more orthogonal codebase at that point. In particular, we were aiming for a self-contained parsing module, which is only depended by the toplevel / document managers. So that:

- pretyping: containing the glob_constr elaborated forms, + `pretype : glob_constr -> constr`
- interp: containing the const_expr AST + `interp: constr_expr -> glob_constr`
- parsing: a separate component + `parse : input -> constr_expr`

Indeed how to organize things with custom notations etc... is a bit tricky.

Comment (ejgallego) [reply interp/notation.mli:358]: The current separation enforces statically that parsing cannot be called from interpretation tho. Whether that's a useful property, I'm not sure, I'd say yes.

**Comment by maximedenes** [comment]
@herbelin I'm a bit puzzled. This patch now fails on `test-suite/bugs/closed/bug_9517.v`, which involves precisely a numeral notation in a custom entry. How does that example work on master? Who adds the parsing rule for `1` in entry `expr`, on that example?

**Comment by maximedenes** [comment]
I suspect this is because I had to change `Metasyntax.not_a_syntax_modifier`. What's the exact spec of that predicate?

**Comment by herbelin** [comment]
> How does that example work on master?

The `no_syntax_modifiers` test in `add_notation` is false (because of the `custom` modifier), hence a grammar rule is added (set at level 0).

> This patch now fails on`test-suite/bugs/closed/bug_9517.v`

What is the failure?

> The current separation enforces statically that parsing cannot be called from interpretation tho. Whether that's a useful property, I'm not sure, I'd say yes.

I would rally @ejgallego and @skyskimmer's view. Having two tables would enforce stronger invariants on the non-dependency of interp on parsing (even though there is a dependency on `entry_level`).

**Comment by maximedenes** [comment]
> I would rally @ejgallego and @SkySkimmer's view. Having two tables would enforce stronger invariants on the non-dependency of interp on parsing (even though there is a dependency on `entry_level`).

Yes, I'll try to refine this once I get the functionality right.

> The `no_syntax_modifiers` test in `add_notation` is false (because of the `custom` modifier), hence a grammar rule is added (set at level 0).

But is it a feature or a bug? What precisely is a "syntax modifier"? The corresponding predicate does not seem documented.

> What is the failure?

It fails to parse `1` in the custom entry `expr`, because the parsing rule is not added after my change in `not_a_syntax_modifier`.

**Comment by maximedenes** [comment]
> The `no_syntax_modifiers` test in `add_notation` is false (because of the `custom` modifier)

This seems like a bug to me, isn't the absence of the `custom` modifier morally equivalent to `in custom constr`? Why would the predicate distinguish the two?

**Comment by herbelin** [comment]
> But is it a feature or a bug? What precisely is a "syntax modifier"? The corresponding predicate does not seem documented.

In the `no_syntax_modifiers` test, I would say that what is intended is "not changing the parsing rule". So, a `custom`, in some sense, is not changing the parsing rule.

So, a fix could be to change the `not (is_numeral symbs)` to some "not (is_numeral_in_constr symbs)".

**Comment by maximedenes** [comment]
> So, a fix could be to change the `not (is_numeral symbs)` to some "not (is_numeral_in_constr symbs)".

Thanks, I'll try that.

Side (naive) question: interpretation depends on levels of notations, but not on the levels of their arguments. Is it natural or not? I haven't thought too much about it, just wondering.

**Comment by herbelin** [comment]
> Side (naive) question: interpretation depends on levels of notations, but not on the levels of their arguments. Is it natural or not? I haven't thought too much about it, just wondering.

It does depend (field `subentry` returned by `match_notation_constr`, which comes from `Notation_term.interpretation`).

**Comment by JasonGross** [comment]
> For your complete information, the following job in allow failure mode has failed: library:ci-fiat_crypto_legacy

Seems genuine, and probably much easier for you to debug than for me (it's complaining about not being about to determine the level of some notation)

**Comment by maximedenes** [comment]
@herbelin should be ready now, modulo CI. I removed the dependency of `interp` on parsing. Can you assign yourself?

File: interp/notation.mli (hunk 7 above)
Comment (maximedenes) [reply interp/notation.mli]: I put the separation back.

**Comment by herbelin** [comment]
I can assign but I have no time to catch up with PRs before a minima next Wednesday. So, if it needs to be merged earlier, it should rather be someone else.

**Review by ejgallego — COMMENTED** [review]
After a very quick scan the changes looks pretty good; unfortunately as Hugo I'm busy after the end of the workshop [wed], but there is time then to ship this in 8.12 I think.

**Review by SkySkimmer — APPROVED** [review]
Will merge once the overlay is linked.

File: theories/ZArith/Int.v [hunk 8]
```diff
@@ -45,6 +45,7 @@ Module Type Int.
   Notation "2" := _2 : Int_scope.
   Notation "3" := _3 : Int_scope.
   Infix "+" := add : Int_scope.
+
```
Comment (SkySkimmer) [inline theories/ZArith/Int.v:48]: Why this space?

Comment (maximedenes) [reply theories/ZArith/Int.v:48]: This is a spurious change I had fixed locally but forgot to push. Thanks.

File: vernac/g_vernac.mlg [hunk 9]
```diff
@@ -321,10 +322,13 @@ GRAMMAR EXTEND Gram
       | -> { None } ] ]
   ;
   decl_notation:
-    [ [ ntn = ne_lstring; ":="; c = constr; b = only_parsing;
+    [ [ ntn = ne_lstring; ":="; c = constr;
+        modl = [ "("; l = LIST1 syntax_modifier SEP ","; ")" -> { l } | -> { [] } ];
```
Comment (SkySkimmer) [inline vernac/g_vernac.mlg:326]: Shouldn't we factor this parenthesized modifier list? For instance the equations overlay ends up with a space-separated list, if it was factored it would just get the same thing.

Comment (maximedenes) [reply vernac/g_vernac.mlg]: Done!

**Comment by ejgallego** [comment]
> Will merge once the overlay is linked.

OK, but IMO we should get @herbelin to give this a look before we ship this in 8.12

**Comment by Zimmi48** [comment]
If we want to get this backported to `v8.12`, then we need the overlay for Equations to be backported to the `8.12` branch of the Equations repository (cc @maximedenes, @mattam82, @ppedrot).
Also, Emilio requested a thumbs up from @herbelin before we backport the PR, but we haven't got it yet.

**Comment by herbelin** [comment]
The PR is good to me, and Software Foundations would "love" having it in 8.12.

**Comment by ejgallego** [comment]
Great thanks @herbelin ; @Zimmi48 this should be the last PR we backport with overlays, correct?

**Comment by Zimmi48** [comment]
That's right.

**Comment by euisuny** [comment]
Thanks a lot for this fix! Is there an approximate timeline to when this will be included in 8.12.dev?
I'm helping the notation changes in SF, and we're hoping to have a stable version out soon.

**Comment by Zimmi48** [comment]
@euisuny This should be the case now.
