### PR TITLE
Delay removing native_compute .ml files until exit

### LINKED ISSUE #15263: `native_compute` should not reuse filename suffixes
#### Description of the problem

At https://github.com/coq-community/coq-performance-tests/runs/3479329691?check_suite_focus=true#step:6:754, I see
```
Error: Dynlink error: The module `Coq_native13c5a0' is already loaded (either by the main program or a previously-dynlinked library)
```
@SkySkimmer [suggested on Zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/Dynlink.20module.20already.20loaded/near/263050390) that Coq might be re-using the same filename multiple times.  It seems worth storing a hashset of used filenames and retrying if a filename has already been used.

#### Coq Version

8.12

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #15263 (assuming it was correctly diagnosed)

### CODE REVIEW

**Comment by ppedrot** [comment]
Can we check whether this reliably fixes the bug?

**Comment by SkySkimmer** [comment]
>Can we check whether this reliably fixes the bug?

We can't reliably trigger the bug so no.

File: kernel/nativelib.ml [hunk 1]
```diff
@@ -48,6 +48,9 @@ let () = at_exit (fun () ->
           Pp.(str "Native compile: failed to cleanup: " ++
               str(Printexc.to_string e) ++ fnl()))
 
+let delay_cleanup_file f =
+  at_exit (fun () -> if not (keep_debug_files()) && Sys.file_exists f then Sys.remove f)
```
Comment (ppedrot) [inline kernel/nativelib.ml:52]: Could you use a `string list ref` and a single `at_exit` call, instead of implicitly relying on the closure registration? It would make the intent clearer. Also, you should probably extrude the flag check.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
