### PR TITLE
[`setoid_rewrite`] rewrite hypotheses without evar instance shenanigans

### LINKED ISSUE #17295: Nested existential variables break expected semantics
Consider the following script.
```coq
Require Import Setoid.

Set Printing Existential Instances.

Axiom A : Type.
Axiom i : A.
Axiom Equal : A -> A -> Prop.
Axiom P : A -> Prop.

Axiom everything_equal : forall (j : A), Equal i j.

Instance b : Morphisms.Proper (Equal ==> Basics.impl) P. Admitted.

Lemma blah (H : P i) : True.
rewrite everything_equal in H.
Show Proof.
(*
(fun H : P i =>
 ?Goal@{H:=(fun lemma : Equal i ?Goal0@{H:=H} => b i ?Goal0@{H:=H} lemma)
             (everything_equal ?Goal0@{H:=H}) H}) 
*)
Show.
(* 
  H : P ?Goal0@{H:=H}
  ============================
  True 
*)
exact I.
Unshelve. exact i.
Qed.
```
The printed proof term looks acceptable at first sight. However, the printed proof state violates the semantics that I've always ascribed to existential instances. Granted, I'm not sure that a formal description of existential variables for Coq exists. However, I've always interpreted it such that terms in an existential instance should be typable in the current context. As such, in the existential variable `?Goal0@{H:=H}` of hypothesis `H` of the printed proof state, I would expect the instance term `H` to be typable in an empty context, which it isn't.

Am I interpreting the semantics wrong, or is this a bug?

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
Fix #17295

The previous approach of rewriting a hypothesis by putting the proof term for the new hypothesis in the instance of the new evar seems fundamentally broken. Because it replaces the old hypothesis with a new one, subgoals no longer have access to the old hypothesis.

Instead, we use the conventional method of generating a new hypothesis, and then replacing the old hypothesis with the new one, clearing any dependent variables.

- [x] Added / updated **test-suite**.

- [x] Added **changelog**.

Overlays:
- https://github.com/uds-psl/coq-library-undecidability/pull/191

### CODE REVIEW

**Comment by LasseBlaauwbroek** [comment]
@cotbot run full ci

**Comment by LasseBlaauwbroek** [comment]
@coqbot run full ci

**Comment by LasseBlaauwbroek** [comment]
Meta-question: How can I check locally that my overlay file is working? When I run `make coq_library_undecidability` it compiles the library without the overlay (presumably because the makesystem doenn't know in which PR I am?) Or is my overlay file incorrect?

**Comment by LasseBlaauwbroek** [comment]
@coqbot run full ci

**Comment by Alizter** [comment]
@LasseBlaauwbroek the overlay file is considered working when the CI passes. You can also `make ci-the_proj` having checked out your overlay in _builc_ci by stopping the build after it copies sources and then starting again, modulo any dependencies.

File: dev/ci/user-overlays/17304-LasseBlaauwbroek-17295-attempt-two.sh [hunk 1]
```diff
@@ -0,0 +1 @@
+overlay coq_library_undecidability https://github.com/LasseBlaauwbroek/coq-library-undecidability overlay-17304 17304
```
Comment (SkySkimmer) [inline dev/ci/user-overlays/17304-LasseBlaauwbroek-17295-attempt-two.sh:1]: If you add your branch name at the end it will get auto detected locally
```suggestion
overlay coq_library_undecidability https://github.com/LasseBlaauwbroek/coq-library-undecidability overlay-17304 17304 fix-17295-attempt-two 
```
note that usually the overlay branch and the coq branch use the same name, when that's the case there's no need for the last argument and it autodetects based on the overlay branch.

Comment (LasseBlaauwbroek) [reply dev/ci/user-overlays/17304-LasseBlaauwbroek-17295-attempt-two.sh:1]: Thanks! (I'll not commit this now, to avoid running the CI again.

**Comment by JasonGross** [comment]
> clearing any dependent variables

I thought that one of the benefits of `setoid_rewrite` + the CRelations stuff was that you could rewrite in a hyp without needing to clear dependent variables.  That is, in cases where rewriting is reversible, the old hyp should always be derivable (up to propositional equality) from the new hyp, so clearing dependent hyps should not be necessary.

I guess the issue is that if the rewriting lemma depends on one of the dependent hyps, then we can't do the replacement because we can no longer access the old hyps?

It seems like there's a genuine tension here: it's nice to be able to refer to the original rewriting lemma (and its dependents) in side conditions, but it's also nice to be able to not have to clear dependents.

Maybe users should be allowed to choose?

(It also seems to me that at least in cases where there are no side conditions and the rewriting lemma does not depend on anything, we should not be clearing dependent variables, but should instead update them.)

(cc @mattam82?)

**Comment by LasseBlaauwbroek** [comment]
> It's nice to be able to refer to the original rewriting lemma (and its dependents) in side conditions

With this PR, almost all side-conditions still have the original non-rewritten hypothesis available. Only if the main subgoal depends on a side-condition (through an evar) will the hypothesis be cleared. There is no way around that, unless one is prepared to keep the original hypothesis in the main subgoal as well.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
If no opposition soon I'm going to merge this.

**Comment by ppedrot** [comment]
@coqbot merge now
