### PR TITLE
[ci] Fix #7396: VST is broken

### LINKED ISSUE #7396: VST script broken
We make .loadpath but this doesn't exist anymore.
https://github.com/PrincetonUniversity/VST/commit/90e164d01f74b2ad1aaa348379e8dbed9989154b

### PR DESCRIPTION
**Pull request by ejgallego**
This is due to our CI script relying on their makefile internals,
unfortunately we still have to do this to avoid timeouts.

### CODE REVIEW

File: dev/ci/ci-vst.sh [hunk 1]
```diff
@@ -8,6 +8,10 @@ VST_CI_DIR="${CI_BUILD_DIR}/VST"
...
 
-# Targets are: msl veric floyd progs , we remove progs to save time
-# Patch to avoid the upper version limit
-( cd "${VST_CI_DIR}" && make IGNORECOQVERSION=true .loadpath version.vo msl veric floyd )
+# HACK: from the upstream makefile:
+#
+# default_target: _CoqProject version.vo msl veric floyd progs
+#
+# We have to omit progs as otherwise we timeout on Travis; once we
+# move to Gitlab we will able to just use `make`
```
Comment (Zimmi48) [inline dev/ci/ci-vst.sh]: Unfortunately, that would mean also removing Travis support, which is easier to run for our contributors.

**Review by Zimmi48 — APPROVED** [review]
Yes as a quick solution. But what about asking them to provide a real target for this? Say `lite`.

File: dev/ci/ci-vst.sh (hunk 1 above)
Comment (SkySkimmer) [reply dev/ci/ci-vst.sh]: >Unfortunately, that would mean also removing Travis support, which is easier to run for our contributors.

I think we will end up with a ci-vst-lite.sh and a ci-vst.sh for travis/gitlab.

File: dev/ci/ci-vst.sh [hunk 2]
```diff
@@ -8,6 +8,10 @@ VST_CI_DIR="${CI_BUILD_DIR}/VST"
...
+( cd "${VST_CI_DIR}" && make IGNORECOQVERSION=true _CoqProject version.vo msl veric floyd )
```
Comment (SkySkimmer) [inline dev/ci/ci-vst.sh]: Maybe we should use `make -o progs` (assume-old) since that's closer to what we mean.
I tested with a dummy makefile and it worked as I expected.

**Review by SkySkimmer — APPROVED** [review]

File: dev/ci/ci-vst.sh (hunk 1 above)
Comment (ejgallego) [reply dev/ci/ci-vst.sh]: > Unfortunately, that would mean also removing Travis support, which is easier to run for our contributors.

Realistically Travis support will be phased out at some point, Gitlab is pretty to run by the way; they can just clone the main Coq repos there and hit "mirror".
