### PR TITLE
Fixes #5481: support for unification of universe variables in congruence and f_equal

### LINKED ISSUE #5481: Universe polymorphism weakens [congruence]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5481
From: @andersk
Reported version: 8.6
CC:   @herbelin

### LINKED ISSUE #9979: congruence fails if universes differ, results in weird f_equal behavior
```
Set Universe Polymorphism.

Record Map(K V: Type) := {
  rep: Type;
  put: rep -> K -> V -> rep;
}.

Section Test.
  Universes u1 u2 u3 u4 u5 u6.

  Goal forall K V (M: Map K V) (k: K) (v: V) (m: rep K V M),
      put@{u1 u2 u3} K V M m k v = put@{u4 u5 u6} K V M m k v.
  Proof.
    intros.
    Fail congruence.
    reflexivity.
```

Desired behavior: `congruence` should succeed and solve the goal.

Moreover, since `f_equal` calls `congruence`, the following

```
  Goal forall K V (M: Map K V) (k: K) (v1 v2: V) (m: rep K V M),
      put@{u1 u2 u3} K V M m k v1 = put@{u4 u5 u6} K V M m k v2.
  Proof.
    intros.
    f_equal.
```
results in

```
2 subgoals (ID 28)
  
  K : Type
  V : Type
  M : Map K V
  k : K
  v1, v2 : V
  m : rep K V M
  ============================
  K = K -> V = V -> M = M -> m = m -> k = k -> v1 = v2 -> put K V M m k v1 = put K V M m k v2

subgoal 2 (ID 19) is:
 v1 = v2
```

instead of just the second subgoal.

Coq version: Both master (424c1973e96dfbf3b2e3245d735853ffa9600373, Apr 1), and 8.9 are affected.

Might be the same as https://github.com/coq/coq/issues/5481.

Thx @JasonGross for helping me isolate the problem.
/cc @andres-erbsen

### PR DESCRIPTION
**Pull request by herbelin**
We hash declarations without their universe instances while the universe constraints are (anyway) reinferred at the time of building the proof.

Giving two arguments to `Ccalgo.Symb` as I did is a bit hackish. The alternative would be to have a hash-consing function that discards universes but I did not find one.

Fixes #5481
Fixes #9979

Now also added: unification of universe levels so that `congruence` works on e.g. `Type -> Type`, the same way as it works for any non-Type `T -> T`.

- [X] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
This is very hackish, and somewhat only side-stepping the real problem that we shouldn't ever rely on an ill-defined notion of "equality" for terms in an unification state... I guess this can qualify as a hotfix but I really don't like neither the original code nor the change.

**Comment by herbelin** [comment]
> an ill-defined notion of "equality" for terms in an unification state

Can't we just say that congruence works with its own notion of quotient over terms and that it does not have to be a standard one?

That is, from the moment that congruence is able to reconstruct a CIC proof that the terms it equates are equal, is it blamable that it uses its own quotient?

[This being said, I don't like particularly the patch either, but I don't know what else to do.]

File: plugins/cc/ccalgo.ml [hunk 1]
```diff
@@ -207,7 +207,15 @@ struct
...
-  let mkSymb s = make (Symb s)
+  let rec drop_univ c =
+    match kind c with
+    | Const (c,_u) -> mkConstU (c,Univ.Instance.empty)
+    | Ind (c,_u) -> mkIndU (c,Univ.Instance.empty)
+    | Construct (c,_u) -> mkConstructU (c,Univ.Instance.empty)
+    | Sort (Type _u) -> mkSort (type1)
+    | _ -> Constr.map drop_univ c
+
+  let mkSymb s = make (Symb (s,drop_univ s))
```
Comment (SkySkimmer) [inline plugins/cc/ccalgo.ml:218]: Maybe we could store just the hash instead of keeping an invalid constr around, ie
```suggestion
  let mkSymb s = make (Symb (s,Constr.hash (drop_univ s)))
```
or even define a hash_nounivs

Comment (herbelin) [reply plugins/cc/ccalgo.ml:218]: Indeed, much cleaner.

> or even define a hash_nounivs

Also possible. No strong opinion in either way.

**Comment by ppedrot** [comment]
> That is, from the moment that congruence is able to reconstruct a CIC proof that the terms it equates are equal

Equality only makes sense when the state is around. If you change the values of evars for instance, you'd get a different term. You cannot even EConstr.kind these things without the state.

**Comment by herbelin** [comment]
The union-find part of `congruence` currently reasons on the nf_evar-form of the term (`EConstr.to_constr ~abort_on_undefined_evars:false sigma t` in `cctac.decompose_term`). Then, it does no unification at all between evars and treat them equal only if syntactically equal.

In the PR, there is unification involved but only between universe levels. With the PR, any two universe levels are assumed unifiable by default and an attempt to actually unify them happens at proof reconstruction. (Note that I did not test what happens when it fails to reconstruct, so let's try, ah, it says "Not convertible", which maybe should be turned instead into "congruence failed"...).

Back to evars, would we like to have congruence work also modulo evar-unification? At least, it is unclear to me how to implement union-find up to unification, if that's your point.

**Comment by ppedrot** [comment]
@herbelin if you implement @SkySkimmer 's change I can merge.

**Comment by herbelin** [comment]
> @herbelin if you implement @SkySkimmer 's change I can merge.

Done.

I also added catching a typing error so that a proper error message is issued when unification of levels fails.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now
