### PR TITLE
Fixes #13241: nested Ltac functions wrongly reporting error on the inner calls

### LINKED ISSUE #13241: Confusing error location on tactic failure
#### Description of the problem

A [Coq proof check on CI](https://gitlab.mpi-sws.org/iris/lambda-rust/-/jobs/98534) failed with the following error message:
```
File "./theories/base.v", line 7, characters 13-31:
Error: No applicable tactic.
Makefile.coq:719: recipe for target 'theories/lang/arc_cmra.vo' failed
make[2]: *** [theories/lang/arc_cmra.vo] Error 1
```
Note how Coq says that the error is in `./theories/base.v`, which is a file that does not even exist in this repository. As make says, the actual failure is in `theories/lang/arc_cmra.v`.

The failure occurs while executing the `done` tactic, which is defined in `stdpp.base`.  Looks like the Coq error reporting is getting confused and shows the tactic definition as the error location, instead of the place where the tactic is invoked. And then it additionally shows a not very helpful file path, relative to the stdpp repository instead of relative to where the current build is happening. (It might be useful to *also* show the tactic definition, but if you show only one location, then it certainly should be the top-level command in the proof script that actually failed. Also the filename should then clearly indicate that the error occurred in a file installed in `user-contrib`.)

#### Coq Version

```
name        coq
version     dev
source-hash 9db73ef1
```

### PR DESCRIPTION
**Pull request by herbelin**
This continues #12223, #12773, #12992, #12774, #12999.

**Kind:** bug fix 

Fixes / closes #13241

- [X] Added / updated test-suite
- [X] Entry added in the changelog (I referred there to #12773 and #12992 but not to #13241 since the latter was only in the dev branch).

### CODE REVIEW

File: plugins/ltac/tacinterp.ml [hunk 1]
```diff
@@ -153,11 +153,14 @@ let add_extra_loc loc extra =
...
-let add_loc loc ist =
+let extract_loc ist = TacStore.get ist.extra f_loc
+
+let ensure_loc loc ist =
   match loc with
   | None -> ist
-  | Some loc -> { ist with extra = TacStore.set ist.extra f_loc loc }
-let extract_loc ist = TacStore.get ist.extra f_loc
+  | Some loc ->
+    if extract_loc ist = None then { ist with extra = TacStore.set ist.extra f_loc loc }
```
Comment (ppedrot) [inline plugins/ltac/tacinterp.ml:162]: Use `Option.is_empty` or a pattern-matching.

Comment (herbelin) [reply plugins/ltac/tacinterp.ml]: Right. Done

**Comment by ppedrot** [comment]
@herbelin can you rebase to get a clean CI?

**Review by ppedrot — APPROVED** [review]

File: test-suite/output/ErrorLocation_13241_1.v [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Ltac a := intro.
+Ltac b := a.
+Goal True.
+b.
```
Comment (Zimmi48) [inline test-suite/output/ErrorLocation_13241_1.v:4]: Missing `Abort.`

File: test-suite/output/ErrorLocation_13241_2.v [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Ltac a _ := intro.
+Ltac b := a ().
+Goal True.
+b.
```
Comment (Zimmi48) [inline test-suite/output/ErrorLocation_13241_2.v:4]: Same thing.

**Review by Zimmi48 — COMMENTED** [review]
FTR the async failure was not spurious, it is due to these unclosed proofs in the test-suite.

**Comment by Zimmi48** [comment]
I'll open a PR fixing this.

**Comment by ppedrot** [comment]
Oops, sorry.

**Comment by herbelin** [comment]
Sorry also... 😟
