### PR TITLE
[parsing] Remove hack which hampered correct parsing resumption, fix CoqIDE tooltip display.

### LINKED ISSUE #15087: Lexer ignores initial Loc.t offsets
See the code changes in #14898.  In `Clexer.func`, the lexer ignores some of the offsets passed in with `loc`, so it's necessary to patch up the lexer-returned loc with this code (below) to return the correct offsets.  The line number is handled correctly.  IIRC some of the other returned character offsets were not correct but I couldn't figure out how to fix them.  The debugger currently only needs correct values for `bp`, `ep` and `line_nb`.  I don't recall whether this patch gives the correct `bol_pos`--it's from 6 months ago.

```
     let aloc = Loc.{loc with bol_pos = loc.bol_pos + bp_;
                                    bp = loc.bp + bp_;
                                    ep = loc.ep + bp_} in
```

The debugger needs this because each sentence passed by CoqIDE is a new invocation of the parser.  The `Loc.t`s in the AST need to be relative to the beginning of the buffer rather than relative to the beginning of the sentence.

### LINKED ISSUE #16987: [coqide] Tooltip locations are broken in `master`
Open this file in coqide:
```
Definition a := 3.

Definition b := 3.  Variable n : nat.
```

Then hover under `Variable n : nat` , you will see no tooltip. If you hover over the first line, you can see that the tooltip tries to appear there.

This is due to a large mess in location handling, fix in #16978 

Note that this bug deals with the case where `coqops:attach_tooltip` is called, and the tooltip is attached incorrectly.

There is a different bug that also makes tooltips to go missing which is when the feedback comes without a `Stateid.t`, but in this case, `attach_tooltip` is never called in the first place.

### PR DESCRIPTION
**Pull request by ejgallego**
This is a follow up of #14220 and #14898 ; in particular, we revert the hack in `CLexer.func` and instead require the caller to set the stream to right count, as this is critical for the current architecture.

Together with #16476, which addedd `Parsable.loc`, and the export of `CLexer.after` in this PR, it seems we can now properly implement parsing resumption (and memoization) in the following manner:

- when done with parsing, use `Pcoq.Parsable.loc` to get the last lexing position `loc` used by the parser.
- advance `loc` using `CLexer.after`
- setup a new stream with the resuming text, you *must* make sure the `count` in the stream corresponds to `loc.bp`, easiest is to use `Stream.njunk`.
- pass `loc` to `Pcoq.Parsable.make ~loc`

Memoization is a bit more advanced and requires using `Pcoq.Parsable.consume`.

It would be nice drop the `Stream.njunk` requirement, but Coq's lexer internals do heavily rely on `Stream.count` so that would imply a full rewrite of the lexer which is something I'd rather don't do now.

Unit test added.

Moreover, we start to fix issues in CoqIDE now that the semantics of XML's protocol `add` call is sane.

Fixes #15087 
Fixes #16987

### CODE REVIEW

File: ide/coqide/idetop.ml [hunk 1]
```diff
@@ -87,13 +87,19 @@ let ide_doc = ref None
...
 let add ((((s,eid),(sid,verbose)),off),(line_nb,bol_pos)) =
   let doc = get_doc () in
   let open Loc in
   (* note: this won't yield correct values for bol_pos_last,
      but the debugger doesn't use that *)
   let loc = { (initial ToplevelInput) with bp=off; line_nb } in
-  let pa = Pcoq.Parsable.make ~loc (Gramlib.Stream.of_string s) in
+  let s_wrapped = wrap_string off s in
+  let r_stream = Gramlib.Stream.of_string s_wrapped in
+  let () = Gramlib.Stream.njunk off r_stream in
```
Comment (ejgallego) [inline ide/coqide/idetop.ml:101]: We could alternatively add a new API `Stream.set_count`, but I'm not sure that allowing users to mess with that is a good idea, WDYT?

Comment (SkySkimmer) [reply ide/coqide/idetop.ml:101]: Maybe just an optional offset count argument for `of_string`?

Comment (ejgallego) [reply ide/coqide/idetop.ml:101]: Good idea, will push a commit with that and see how it looks.

File: gramlib/stream.ml [hunk 2]
```diff
@@ -94,15 +94,15 @@ let is_empty s =
...
 let empty () = {count = 0; data = Sempty}
 
-let of_string s =
-  let count = ref 0 in
-  from (fun () ->
-    let c = !count in
+let of_string ?(offset=0) s =
+  let count = ref offset in
+  from ~offset (fun () ->
+    let c = (!count - offset) in
```
Comment (SkySkimmer) [inline gramlib/stream.ml:105]:
```suggestion
  let count = ref 0 in
  from ~offset (fun () ->
    let c = !count in
```

File: gramlib/stream.mli [hunk 3]
```diff
@@ -40,8 +40,10 @@ val empty : unit -> 'a t
 (** Return the stream holding the elements of the list in the same
    order. *)
 
-val of_string : string -> char t
-(** Return the stream of the characters of the string parameter. *)
+val of_string : ?offset:int -> string -> char t
+(** Return the stream of the characters of the string parameter. If
+    set, [offset] will initialize the stream to start with [offset]
```
Comment (SkySkimmer) [inline gramlib/stream.mli:45]: The explanation of offset should probably be on from not of_string

File: parsing/cLexer.ml [hunk 4]
```diff
@@ -773,18 +773,12 @@ let rec next_token ~diff_mode loc s =
...
   Gramlib.LStream.from ~loc
     (fun () ->
       let (tok, loc) = next_token !cur_loc cs in
       cur_loc := after loc;
-      let aloc = Loc.{loc with bol_pos = loc.bol_pos + bp_;
-                                    bp = loc.bp + bp_;
-                                    ep = loc.ep + bp_} in
-     (* Debug: uncomment this for tracing tokens seen by coq...*)
-     (*  Printf.eprintf "(line %i, %i-%i)[%s]\n%!" aloc.line_nb aloc.bp aloc.ep (Tok.extract_string diff_mode t);*)
-      Some (tok,aloc))
```
Comment (jfehrle) [inline parsing/cLexer.ml:787]: The debugger needs this code to get correct offsets for breakpoints.  Please figure out a way to support it.  Also, please test it in the debugger.

**Review by jfehrle — DISMISSED** [review]

File: parsing/cLexer.ml (hunk 4 above)
Comment (jfehrle) [reply parsing/cLexer.ml:787]: How do you ensure that the returned `bol_pos` is correct?

Comment (ejgallego) [reply parsing/cLexer.ml:787]: `Stream.count` is now set correctly at `idetop.ml` , which is what determines `bp`, so TTBOMK this should be correct, as described in the commit message.

Comment (ejgallego) [reply parsing/cLexer.ml:787]: > How do you ensure that the returned `bol_pos` is correct?

More concretely, CLexer will update `bol_pos` from `Stream.count`, so indeed maybe you want to pass `bol_pos` to the initial `loc` in `idetop.ml` ? I didn't do so as before it wasn't done, but I've pushed a commit to do so.

Anyways, these kind of stuff should be covered by fake_ide tests, as I've done with the unit test here.

Comment (ejgallego) [reply parsing/cLexer.ml:787]: Patch tested, seems to work fine!

Comment (ejgallego) [reply parsing/cLexer.ml:787]: Last patch doesn't make a different as far as I can see tho.

Comment (jfehrle) [reply parsing/cLexer.ml:787]: I won't have time to fully dig into this (or try it) until Thursday or Friday.  Does this have to be in 8.17?

I earlier made some performance fixes due to side effects of the debugger changes.  In its current state, I think this PR will break the positioning of tooltips in the script buffer (not breakpoint offsets as I said earlier).

The `let bol_pos = bp - bol_byte` in `coqOps.ml` (from #15787) passes `bol_pos` _relative_ to `bp`, which works with the existing code because `bol_pos = loc.bol_pos + bp_` on line 782 above adds `bp` back to return an _absolute_ value.  So you may need to change that line to just `let bol_pos = bol_byte`.  This assumes that vsCoq and coqtail are simply passing 0 for bp, which is probably true.  But it a tweak to the semantics of the message; a more conservative approach would be to add bp to bol_pos on the Coq side when you initialize the stream.

If `bol_pos` is incorrect, IIRC tooltips for warnings will be applied in the wrong spot in the script buffer.  A reasonable test would be to run a script that generates a warning or two and verify that tooltips are attached to the correct part of the script buffer.  Note that the sentence that generates the warning must not be the first sentence in the script (that wouldn't have the error).

Comment (jfehrle) [reply parsing/cLexer.ml:787]: You may need to generate the warning on the second sentence in a single line to see the error if there is one.

Take my analysis with a grain of salt, I didn't have time to run the code and verify it.

**Comment by ejgallego** [comment]
@coqbot run full CI

**Comment by ejgallego** [comment]
Any assignee? AFAICT this PR is ready and all the questions and testing on Jim's review have been addressed.

**Comment by Zimmi48** [comment]
@ppedrot maybe?

File: parsing/cLexer.ml (hunk 4 above)
Comment (Zimmi48) [reply parsing/cLexer.ml:787]: @jfehrle did you get a chance to look at Emilio's answers?

**Comment by ppedrot** [comment]
@ejgallego Are you sure that this PR is not introducing a regression on the quadratic blowup of location computation? This whole system is a matchstick cathedral waiting to collapse in flames after the smallest tweak. Otherwise, I do prefer the new version.

**Comment by ejgallego** [comment]
> @ejgallego Are you sure that this PR is not introducing a regression on the quadratic blowup of location computation? 

It looks fine to me. For the regular `add` part, we are doing strictly less, for the tooltip part, already the tooltips are broken in `master` so it is hard to test performance against broken code.

As you say, it is hard to deal with this code as it is really messy, but the new result looks way saner to me, and morevoer I've been spending years fighting with different editors and UI protocols so I'd dare to say I got a good idea on what is the sane thing to do here.

To start with, this patch, and have all the interactions with Coq's parser in terms of parser locs / offsets. (At least until Coq's parser uses an enconding-aware string type)

**Comment by ejgallego** [comment]
The tooltip code can be improved likely, but I need to understand more about what the invariants are. Likely we are missing a `c2b` conversion there. But even in the current state, it is less broken than in `master` if my testing is correct.

**Review by ppedrot — APPROVED** [review]
Alea jacta est.

File: parsing/cLexer.ml (hunk 4 above)
Comment (jfehrle) [reply parsing/cLexer.ml:787]: I've been out of town for several days.  I will look at this later today.  I'd like to understand what broke it in master and to verify that it doesn't introduce a performance issue.

File: ide/coqide/coqOps.ml [hunk 5]
```diff
@@ -494,11 +494,14 @@ object(self)
...
-    let pre = b2c phrase (pre_bytes - (sentence.byte_start)) in
-    let post = b2c phrase (post_bytes - (sentence.byte_start)) in
-    let start = start_sentence#forward_chars pre in
-    let stop = start_sentence#forward_chars post in
+    let start, stop = match loc with
+      | None -> start_sentence, stop_sentence
+      | Some loc ->
+        let start, stop = new GText.iter (start_sentence#as_iter), new GText.iter (start_sentence#as_iter) in
+        let start = start#set_offset loc.Loc.bp in
+        let stop = stop#set_offset loc.ep in
```
Comment (jfehrle) [inline ide/coqide/coqOps.ml:502]: Losing the `b2c` here is not correct when there are unicode characters in the sentence.  The test case in #16987 only triggers the `None` case.  The issue is that `Loc` uses byte offsets while `buffer` uses unicode character offsets, so a conversion is necessary, else you may highlight too much.  (Also add more stuff after the sentence getting the warning for the test.)

This seems to be what's needed in master, though I have to test it some more.
```
        let pre = b2c phrase loc.Loc.bp in
        let post = b2c phrase loc.ep in
```

I'll get back to this over the weekend.

File: parsing/cLexer.ml (hunk 4 above)
Comment (jfehrle) [reply parsing/cLexer.ml:787]: The last commit ("Fix bizarre location-handling code.") reintroduces the O(n^2) behavior.  The ones before it are OK. 
(Pff.v, a 1.2 MB file, takes about 3 minutes to run in CoqIDE both on master and with the first 3 commits.  With the 4th commit, I gave up after 10 minutes, and it had only processed half the source.)

If the last commit is omitted, I think this change is OK.  The change I suggest [here](https://github.com/coq/coq/pull/16978/files#r1045382094) is not critical.

File: ide/coqide/coqOps.ml (hunk 5 above)
Comment (jfehrle) [reply ide/coqide/coqOps.ml:502]: I will submit a separate PR to fix the warning tooltips in a separate PR for 8.17 shortly.  The case where `loc` is `None` is the important one--none of the calls to `CWarnings.create` pass loc.  I haven't figured out the fix for the `Some` case yet.  IMO that's not urgent, though I will work on it in the next few days.

Error messages also generate tooltips.  These seem to work correctly even when `loc` is provided.  FWIW, I found 79 places in the source that can provide `loc`.

**Review by jfehrle — COMMENTED** [review]
These changes look OK provided you remove the last commit.

The tooltips don't depend on having a correct bol_pos.  I had to re-read the code--after 6 months I don't remember many of the details.

And I'll submit a separate fix for the tooltips.

File: parsing/cLexer.ml (hunk 4 above)
Comment (Zimmi48) [reply parsing/cLexer.ml:787]: Thanks!

**Comment by ejgallego** [comment]
Thanks for the performance testing @jfehrle , I will have a look and split the last commit into two commits. Still the fix here is better than the one you submitted IMO as it provides code that at least looks correct for the `Some` case.

**Comment by ejgallego** [comment]
Moreover, IMHO it makes little sense to work on CoqIDE and locations directly over `master` without the resumption fix in this PR first; it is futile as without the first commits here, the protocol is simply broken and what we seem to have is pile of hack on top of the clients to workaround Coq reporting nonsensical locations on parsing resumption.

**Comment by ejgallego** [comment]
Indeed, the last commit was bogus, I've removed it.

I did clean up quite a bit how locations are handled now, but wire-wise should be identical.

Tested with all the usual suspects, including `Pff.v`

**Comment by ejgallego** [comment]
An issue to consider when testing warnings is that in quite a few cases, the STM will send a warning feedback message without a state id attached, this makes coqide not to attach the tooltip.

**Comment by jfehrle** [comment]
Rewriting the location handling code is not a priority.  There's no urgent reason to include it in 2.17 at this late date.  It's not relevant to the main point of this PR, which is about parsing resumption.

Fixing the tooltip display should be a separate PR, and preferably the one who creates a bug should fix it.  I don't understand why you insist on doing your own thing when I've obviously been working on the issue--that means I've been wasting my time.  I don't know if your most recent changes handle all the cases correctly--it takes a long time to test.

File: ide/coqide/coqOps.ml (hunk 5 above)
Comment (ejgallego) [reply ide/coqide/coqOps.ml]: Solved thanks; used GTK native methods instead of `b2c` now that Coq returns the full location info correctly.

**Comment by ejgallego** [comment]
> Rewriting the location handling code is not a priority.

It may not be a priority for you, but indeed the current code is buggy (at least one bug I could spot, I'm sure there are more) and moreover, the code seems pretty hard to maintain, as yourself mentioned before.

> There's no urgent reason to include it in 2.17 at this late date. It's not relevant to the main point of this PR, which is about parsing resumption.

Not to include what? This PR fixes two bugs, both serious in my book.

> 
> Fixing the tooltip display, which is broken in master, should be a separate PR, and preferably the one who creates a bug should fix it.

That's your point of view, we have no such policy in Coq, moreover you stated that you had problems understanding what your code was doing after so much time had passed; given that I understand what is going and I'm warn with the code I'd rather fix this myself.

> I don't understand why you insist on doing your own thing when I've obviously been working on the issue--that means I've been wasting my time.

Yes, it is indeed bizarre why you choose to spend time re-submitting a poorer version of a fix that I had already submitted here. That was your call tho, but yes, I fail to see the point of it.

> I don't know if your most recent changes handle all the cases correctly--it takes a long time to test.

Indeed it takes some time to test (I wish we had proper tests for this in test suite, but that's complex for other reasons).

I'm satisfied with the testing I've done myself, and of course, while not infallible, I'm positive the new code is in better shape (and less buggy)

File: parsing/cLexer.ml (hunk 4 above)
Comment (ejgallego) [reply parsing/cLexer.ml:787]: Last commit indeed was bogus, removed from the set.

**Comment by ppedrot** [comment]
> that means I've been wasting my time

@jfehrle I also lost quite a bit of time with this stuff, and I am really not happy about the current mess we have. It is not reasonable to keep piling up hacks over hacks to solve foundational issues.

**Comment by Zimmi48** [comment]
Does the current version, despite the removed commit, still fixes #16987? If yes, please update the PR description to:
>Fixes #15087
>Fixes #16987

Otherwise, GitHub doesn't pick it up.

**Comment by ejgallego** [comment]
Oh indeed, needs to be in the format you mention, PR description updated.

**Comment by ppedrot** [comment]
I don't think this fixes #16987 for good, I'm still getting missing tooltips from rather simple examples.

**Comment by ejgallego** [comment]
> I don't think this fixes #16987 for good, I'm still getting missing tooltips from rather simple examples.

Can you send me these cases (or post them in the issue)

Note that there is another bug that makes tooltips go missing, but that one is an STM bug, where the warning arrives without a `Stateid.t`, thus CoqIDE doesn't know where to attach the tooltip.

You can see that doing `dune exec -- dev/shim/coqide -debug` and checking the log, it will complain for "Orphan feedback" or something like that.

That STM bug may be simple to fix, but it is a bit beyond my pay grade :)

**Comment by ejgallego** [comment]
I will update the original issue to be more precise tho.

**Comment by ejgallego** [comment]
It would be interesting to see if the "lack of Stateid.t missing tooltip bug" is also a regression.

**Comment by ppedrot** [comment]
@coqbot merge now

File: ide/coqide/coqOps.ml [hunk 6]
```diff
@@ -146,6 +138,54 @@ end = struct
...
+   This is meant to be used in the resumption of parsing, to tell Coq
+   where the input stream was left at. In this case, these 3 points
+   uniquely determine the position where to restart
+   from. [CLexer.after] can compute this from the position of the last
+   parsed token.
+
+   However, for CoqIDE, we have a huge problem in the sense that
+   CoqIDE will do its own parsing and the locations may not start at
+   the same point. Thus, we need to perform potentially very costly
+   char to offset conversion, for that we need the whole buffer.
```
Comment (jfehrle) [inline ide/coqide/coqOps.ml:175]: Would you elaborate on this?  What do you mean by "CoqIDE will do its own parsing and locations may not start at the same point?"

Comment (ejgallego) [reply ide/coqide/coqOps.ml:175]: CoqIde uses `coq_lex.mll` to split sentences, whereas Coq uses it's own parser, nothing ensures they will pick the same exact splitting point, due to comments, etc...

Comment (jfehrle) [reply ide/coqide/coqOps.ml:175]: CoqIDE may split sentences a bit differently from another IDE, but I don't see how that's a huge problem.  Presumably `get_iter_at_byte` does the conversion efficiently enough that there's no user-visible perf issue.

One thing we could do more neatly is to always return `loc` with errors and warnings so we use the parser's notion of sentence boundaries.  Currently we highlight code based on CoqIDE's notion, so the highlight includes leading white space and comments.  Making this change would require addressing  the use case in #17023; notice that the first screen shot there doesn't highlight the white space.

image

Comment (ejgallego) [reply ide/coqide/coqOps.ml:175]: > CoqIDE may split sentences a bit differently from another IDE, but I don't see how that's a huge problem. Presumably get_iter_at_byte does the conversion efficiently enough that there's no user-visible perf issue.

Indeed, `get_iter_at_byte` is the direction that is not problematic; in the other direction we can't rely on Coq's loc as to avoid scanning the whole buffer. The problem is not CoqIDE splitting sentences differently from other IDEs, but from Coq itself, and thus we can't reuse the line work.

> One thing we could do more neatly is to always return loc with errors and warnings so we use the parser's notion of sentence boundaries.

Sane document managers already do that. However often errors are more specific than a sentence.

> Currently we highlight code based on CoqIDE's notion, so the highlight includes leading white space and comments. Making this change would require addressing the use case in https://github.com/coq/coq/issues/17023; notice that the first screen shot there doesn't highlight the white space.

that's a problem with CoqIDE, coq side should be mostly good. The above example works fine for example in `coq-lsp`.
