### PR TITLE
Stricter non-ambiguousness check in Require

### LINKED ISSUE #20587: Rocq doesn't complain about duplicate files when using ROCQPATH
### Description of the problem

```shell
cd $HOME
mkdir testab
cd testab
mkdir a
mkdir b
echo "Definition n := 0." > a/f.v
echo "Definition n := 1." > b/f.v
cd a
rocq c -Q . testab.a f.v
mkdir -p testab/a
mv f.vo testab/a/
cd ../b
rocq c -Q . testab.b f.v
mkdir -p testab/b
mv f.vo testab/b/
cd ..
export ROCQPATH=$HOME/testab/a:$HOME/testab/b
echo "From testab Require f." | rocq top
# Works :(
#   Welcome to Rocq 9.0.0
#
#   Rocq <
#   Rocq <
# Expected result:
#   Error: Required library f matches several files in path (found
#   HOME/testab/a/testab/a/f.vo and HOME/testab/b/testab/b/f.vo).
```

### Version of Rocq / Coq where this bug occurs

At least 8.20.1, 9.0.0 and master

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #20587

TODO:
- [x] update doc, changelog
- [x] update tests
- [x] check ambiguousness for exact matches
- [ ] add check in coqdep??

#### Async overlays (to be merged before the current PR)

* https://github.com/math-comp/math-comp/pull/1425
* https://github.com/HoTT/Coq-HoTT/pull/2283
* https://github.com/impermeable/coq-waterproof/pull/141

#### Synchronous overlays (to be merged in sync with the PR)

* https://github.com/ejgallego/coq-lsp/pull/964

### CODE REVIEW

**Comment by proux01** [comment]
Interesting, this seems to uncover actual bugs in the CI.

**Comment by proux01** [comment]
The misc/deps-order.sh and misc/deps-order-distinct-root.sh somehow test that the bug this is fixing (i.e., #20587) is actually present.
Should we remove them in favor of a test for #20587?

**Comment by proux01** [comment]
That being said, the current PR has the net effect of preventing compilation of anything that is already installed. We might want something a bit less radical?

**Comment by SkySkimmer** [comment]
>That being said, the current PR has the net effect of preventing compilation of anything that is already installed. We might want something a bit less radical?

I guess if it finds 2 files with the same logical paths it can pick the first one?

**Comment by proux01** [comment]
In some sense that's the current behavior, causing the bug we are trying to fix. In practice, this means for instance that opam and nix get different behaviors (one complaining with an error, the other silently ignoring it and picking one of the two files).
Maybe we could keep the current PR, changing the error to a warning (error by default) taking the first file.
Anyway, that seems subtle, let's discuss it during next call: https://github.com/rocq-prover/rocq/wiki/Rocq-Call-2025-05-13

**Comment by SkySkimmer** [comment]
>In some sense that's the current behavior, causing the bug we are trying to fix.

I don't think so. In #20587 `From testab Require f` can find `testab.a.f` in `a/testab/a/f.vo` and `testab.b.f` in `b/testab/b/f.vo`, `testab.a.f <> testab.b.f` so I propose producing an error. 
With an already installed development `From foo Require bar` would get `foo.bar` in `local/bar.vo` and also in `/installed/user-contrib/foo/bar.vo` so my proposal wouldn't error (`foo.bar = foo.bar`).
(however if the local version has different layout from the installed version you could still get an error so that's still a problem I guess? eg if the local version moved `bar` to `foo.baz.bar`, `From foo Require bar` would find `foo.baz.bar` locally and `foo.bar` in the installed files)

**Comment by ejgallego** [comment]
This is a tricky topic, there is a large amount of discussion already in several parts, AFAICT @herbelin is the one that knows the current rules best.

I'm not sure what would the best fix be, a few things to consider (mostly based from experience in builds):
- One has to be very careful with "non-compositional" search, that is today, imagine my package compiles fine, then I install an unrelated library and it breaks. This is hell.
- Ambiguous search does also create eventually problems. IMHO, if two paths are in scope, and the Require is ambiguous, an error should happen.

The way we try to address this in Dune is:
- using isolation, we don't import user-contrib in full but selective. This is way more stable for point 1, but still we need to figure out some "alias" rules tho.
- having a hierarchical database, search first resolves in the local database, then we resolve in the installed one

I think implementing this last point for Rocq could help with this problem. Thus, we could put a flag on loadpaths to signal they come from "installed" paths, like user-contrib, and we consider -R / -Q flags "local", then resolution happens hierarchically.

There are some non-trivial details to figure out tho, so I'm not sure how workable this would be in practice.

**Comment by SkySkimmer** [comment]
New version based on the separation between "installed" and "local" paths discussed in call

The deps-order tests still fail since they're essentially checking that ambiguousness is resolved a specific way instead of rejecting it, I guess I'll replace them if CI says no major issues.

File: vernac/loadpath.ml [hunk 1]
```diff
@@ -241,36 +234,30 @@ let locate_absolute_library dir : (CUnix.physical_path, Error.t) Result.t =
...
   let dir, base = Libnames.repr_qualid qid in
   match expand_path ?root dir with
-  | [], [] -> Error LibUnmappedDir
-  | full_matches, others ->
+  | [], ([], []) -> Error LibUnmappedDir
+  | full_matches, (installed, local) ->
     let result =
       (* Priority to exact matches *)
+      (* XXX why find_first instead of find_unique? *)
       match select_vo_file ~find:(find_first full_matches) base with
```
[the remark this answers is not in the document]
Comment (SkySkimmer) [reply vernac/loadpath.ml:250]: no

[the remark this answers is not in the document]
Comment (SkySkimmer) [reply vernac/loadpath.ml:250]: if someone does `From foo Require bar` and there is both `foo.bar` and `foo.x.bar` available you want to error, and force doing `Require foo.bar`?

With non-From syntax I guess you can only have both exact and nonexact match with -R, in which case the exact match would become impossible to access.

File: vernac/loadpath.mli [hunk 2]
```diff
@@ -88,6 +88,10 @@ type vo_path =
       true for -R, false for -Q in command line *)
   ; recursive : bool
   (** [recursive] will determine whether we explore sub-directories  *)
+  ; automatic : bool
```
Comment (ejgallego) [inline vernac/loadpath.mli:91]: `automatic` seems quite non-standard, also IIANM `ROCQPATH` will set this to true, which is not so "automatic".

In build systems this is called `installed`, I dunno, `global` could be another option. It seems to me that `installed` better fits the two use cases.

File: vernac/loadpath.ml [hunk 3]
```diff
@@ -17,7 +17,7 @@ type t = {
   path_physical : CUnix.physical_path;
   path_logical : DP.t;
   path_implicit : bool;  (* true for -R, false for -Q in command line *)
-  path_root : (CUnix.physical_path * DP.t);
+  path_automatic : bool; (* true for automatically added paths (assumed installed), false for command line paths *)
```
Comment (ejgallego) [inline vernac/loadpath.ml:20]: Yeah, I see this comment now, let's call this `path_installed`

**Comment by SkySkimmer** [comment]
CI errors are those 2 tests + coq_lsp needing overlay +

hott:
~~~
Error: Required library Groups.Group matches several files in path (found
/builds/coq/coq/_build_ci/hott/theories/Algebra/Groups/Group.vo and
/builds/coq/coq/_build_ci/hott/test/Algebra/Groups/Group.vo).
~~~

waterproof:
~~~
File "./theories/Libs/Reals.v", line 23, characters 0-25:
Error: Required library Notations matches several files in path (found
/builds/coq/coq/_build_ci/waterproof/_build/default/theories/Notations.vo and
/builds/coq/coq/_install_ci/lib/coq/theories/Init/Notations.vo).
~~~
(built with dune so corelib is bound with -R instead of automatically)

**Comment by ejgallego** [comment]
@SkySkimmer yes, will do

**Comment by ejgallego** [comment]
Overlay done (c.f. https://github.com/ejgallego/coq-lsp/pull/964)

> (built with dune so corelib is bound with -R instead of automatically)

Thanks for implementing this, I am lost on what the status of `From Corelib` these days, should Corelib be bound with -Q now?

File: sysinit/coqloadpath.ml [hunk 4]
```diff
@@ -57,6 +58,7 @@ let init_load_path ~coqenv =
       ; coq_path = Libnames.default_root_prefix
       ; implicit = false
       ; recursive = false
+      ; installed = true
```
Comment (SkySkimmer) [inline sysinit/coqloadpath.ml:61]: not sure if this one should be installed (this is the implicit -Q . "" which doesn't recurse in subdirs)

**Comment by SkySkimmer** [comment]
>Thanks for implementing this, I am lost on what the status of From Corelib these days, should Corelib be bound with -Q now?

No, still -R. dune is different from rocq makefile because it does `-boot -R /path Corelib` instead of nothing, so this PR's heuristic doesn't see Corelib as installed.
Note this is fine since only the declared dependencies are passed to coqc, so it shouldn't be producing the ambiguities with unrelated libraries which motivated using the installed/not installed heuristic.

File: sysinit/coqloadpath.ml (hunk 4 above)
Comment (ejgallego) [reply sysinit/coqloadpath.ml:61]: It'd dare to say this needs to be `installed = false` indeed.

Maybe time to start thinking of removing this, and actually forbidding to bind to an empty path except for the (internal) case of user-contrib

File: vernac/loadpath.ml (hunk 1 above)
[the remark this answers is not in the document]
Comment (proux01) [reply vernac/loadpath.ml]: I guess we would need some `Require Exact` syntax. Anyway, definitely outside the scope of the current PR.

File: sysinit/coqloadpath.ml (hunk 4 above)
Comment (proux01) [reply sysinit/coqloadpath.ml:61]: I agree it is not installed. I also agree we could consider removing it (but not in the current PR).

**Comment by ejgallego** [comment]
> File "./theories/Libs/Reals.v", line 23, characters 0-25:
> Error: Required library Notations matches several files in path (found
> /builds/coq/coq/_build_ci/waterproof/_build/default/theories/Notations.vo and
> /builds/coq/coq/_install_ci/lib/coq/theories/Init/Notations.vo).

Interesting, I though that was the case already; IMHO we want to keep this behavior in Dune as it is stable under vendoring (aka substitution), but I'm open to have dune mark stuff in user-contrib as "installed" (we'd have to add a new flag)

File: sysinit/coqloadpath.ml (hunk 4 above)
Comment (SkySkimmer) [reply sysinit/coqloadpath.ml]: changed to installed = false

File: doc/changelog/09-cli-tools/20601-find-unique-Changed.rst [hunk 5]
```diff
@@ -0,0 +1,7 @@
+- **Added:**
+  error on ambiguous require. Rocq used to silently select a file
```
Comment (Villetaneuse) [inline doc/changelog/09-cli-tools/20601-find-unique-Changed.rst]:
```suggestion
  error on ambiguous :cmd:`Require`. Rocq used to silently select a file
```

File: doc/changelog/09-cli-tools/20601-find-unique-Changed.rst [hunk 6]
```diff
@@ -0,0 +1,7 @@
...
+  when ambiguous requires came from different loadpaths, for instance
```
Comment (Villetaneuse) [inline doc/changelog/09-cli-tools/20601-find-unique-Changed.rst]:
```suggestion
  when ambiguous :cmd:`Require`\s came from different loadpaths, for instance
```

File: doc/changelog/09-cli-tools/20601-find-unique-Changed.rst [hunk 7]
```diff
@@ -0,0 +1,7 @@
...
+  diferent fields of the ``ROCQPATH`` environment variable
```
Comment (Villetaneuse) [inline doc/changelog/09-cli-tools/20601-find-unique-Changed.rst]:
```suggestion
  different fields of the ``ROCQPATH`` environment variable
```

**Comment by proux01** [comment]
@Villetaneuse thanks for the review

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now
