### PR TITLE
Fix ocamlpath order in findlib init

### LINKED ISSUE #16406: Incorrect search order of plugins for Findlib
When loading a plugin, Coq/Findlib first looks in the system directories and then in the directories specified by option `-I` on the command line. As a consequence, if a plugin with the same name (e.g., an older version) happens to be installed in a system directory, Coq will load it instead of the one explicitly specified on the command line.

This makes plugin development especially cumbersome. Indeed, one has to first remove any other installed version of the plugin (e.g., `opam remove`). Otherwise, Coq will silently load an outdated version of the plugin.

I think that replacing `ml_path @ opts.pre.ml_includes` by `opts.pre.ml_includes @ ml_path` in `Coqargs.build_load_path` is sufficient to fix this bug, but I have yet to test it. (This also begs the question of whether `vo_path @ opts.pre.vo_includes` on the following line suffers from a similar bug.)

Since it involves the Findlib machinery, this bug only exists in Coq 8.16 for now.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16406

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Anyone know how to make a good test for this? 
cc @silene @ppedrot @gares

**Comment by gares** [comment]
I don't have the time, sorry

The way I experience the bug is to run `make install` and have a plugin installed in `~/.opam/`, then change the plugin (adding an assert false), run make, and see things working (since the old copy is found). IMO this is what we should reproduce, but if you start to export OCAMLPATH then you kind of bias the test.

**Comment by silene** [comment]
I think it is impossible test in Coq itself. But here is how I tested my patch manually:

`foo.ml`:
```ocaml
let _ = Mltop.add_known_module "coq-foo.foo"
let () = Printf.printf "foo 1\n%!"
```

`foo.v`:
```coq
Declare ML Module "coq-foo.foo".
```

`META.coq-foo`:
```
package "foo" (
  directory = "."
  description = "Coq Foo"
  plugin(native) = "foo.cmxs"
)
directory = "."
```

```shell
ocamlfind ocamlopt -package coq-core.toplevel -rectypes -thread -shared foo.ml -o foo.cmxs
coqc -I . foo.v
DIR=$(ocamlfind printconf destdir)/coq-foo
cp foo.cmxs $DIR/
grep -v 'directory *=' META.coq-foo > $DIR/META
coqc foo.v
sed -i -e 's/foo 1/foo 2/' foo.ml
ocamlfind ocamlopt -package coq-core.toplevel -rectypes -thread -shared foo.ml -o foo.cmxs
coqc -I . foo.v
```

**Comment by ejgallego** [comment]
> Anyone know how to make a good test for this?
> cc @silene @ppedrot @gares

I think you can set the right env variables (see http://projects.camlcity.org/projects/dl/findlib-1.9.5/doc/ref-html/lib/Findlib.html) to have an alternate tree / config for findlib in the test suite which is reproducible.

File: sysinit/coqinit.ml [hunk 1]
```diff
@@ -149,10 +149,8 @@ let init_runtime opts =
   List.iter Mltop.add_ml_dir ml_load_path;
   List.iter Loadpath.add_vo_path vo_load_path;
   let ocamlpathsep = if Sys.unix then ":" else ";" in
-  let ocamlpath = String.concat ocamlpathsep ml_load_path in
-  let env_ocamlpath =
-    try Sys.getenv "OCAMLPATH" ^ ocamlpathsep ^ ocamlpath
-    with Not_found -> ocamlpath in
+  let env_ocamlpath = try Sys.getenv "OCAMLPATH" :: ml_load_path with Not_found -> ml_load_path in
+  let env_ocamlpath = String.concat ocamlpathsep (List.rev env_ocamlpath) in
```
Comment (silene) [inline sysinit/coqinit.ml:153]: As mentioned in the issue, using `List.rev` is an unfortunate choice, since it causes `-I` directories to be scanned right-to-left, while the vast majority of compilers (e.g., `gcc`, `ocamlc`) use a left-to-right policy.

- "Directories specified with -I options are scanned in left-to-right order."
- "Directories added with -I are searched [...] in the order in which they were given on the command line"

**Review by silene — CHANGES_REQUESTED** [review]

**Comment by SkySkimmer** [comment]
I guess we don't document the effect of order for -I so either is technically correct, but shouldn't we keep the past behaviour?

**Comment by SkySkimmer** [comment]
Changed: when passed `-I A -I B` we produce `A:B:$OCAMLPATH:$default_dirs` (default_dirs is the list of install locations for the core plugins and other such stuff)

File: sysinit/coqargs.ml [hunk 2]
```diff
@@ -448,7 +448,12 @@ let build_load_path opts =
     else
       let coqenv = Boot.Env.init () in
       Coqloadpath.init_load_path ~coqenv in
-  ml_path @ opts.pre.ml_includes ,
+  let ocamlpathsep = if Sys.unix then ':' else ';' in
+  let env_ocamlpath =
```
Comment (ppedrot) [inline sysinit/coqargs.ml:452]: Didn't we say that when -boot is set, we don't use OCAMLPATH?

Comment (SkySkimmer) [reply sysinit/coqargs.ml:452]: That is the opposite of what I understood.
-boot is about not binding the stdlib, so it is unrelated to OCAMLPATH

Comment (silene) [reply sysinit/coqargs.ml:452]: Yes, OCAMLPATH should always be used (e.g., critical on Nix). Otherwise, dependencies will not be found.

**Comment by silene** [comment]
> Changed: when passed `-I A -I B` we produce `A:B:$OCAMLPATH:$default_dirs` (default_dirs is the list of install locations for the core plugins and other such stuff)

Will that not break the compilation of Coq when there is already a release of Coq installed on the system? Indeed, the currently compiled Coq will look for its plugins in `$OCAMLPATH` instead of `$default_dirs` and thus will find the wrong versions. (I am assuming that the not yet installed plugins are in `$default_dirs`.) If so, the order should be `A:B:$default_dirs:$OCAMLPATH`.

**Comment by ejgallego** [comment]
@silene compilation of Coq has moved to using less implicit stuff, so indeed the standard library is compiled using`-boot` and explicit `-I` paths.

**Comment by ejgallego** [comment]
Dune is also scheduled to use `-boot` for all user developments soon, this allows, among other things, for a crude way to hide selectively what is installed in `user-contrib`.

**Comment by gares** [comment]
Isn't dune setting OCAMLPATH to point to the _build directory?

**Comment by ejgallego** [comment]
> Isn't dune setting OCAMLPATH to point to the _build directory?

Yes, as part of the workspace configuration.

File: sysinit/coqargs.ml [hunk 3]
```diff
@@ -448,7 +448,12 @@ let build_load_path opts =
...
+    try String.split_on_char ocamlpathsep (Sys.getenv "OCAMLPATH")
+    with Not_found -> []
+  in
+  opts.pre.ml_includes @ env_ocamlpath @ ml_path ,
```
Comment (silene) [inline sysinit/coqargs.ml:456]: Is it on purpose that the content of `$OCAMLPATH` is passed to `Mltop.add_ml_dir`? This seems like a very bad idea.

Comment (gares) [reply sysinit/coqargs.ml:456]: This point came up at the call, but nobody could find the problem. What is it?

Comment (ejgallego) [reply sysinit/coqargs.ml:456]: What problem?

Comment (gares) [reply sysinit/coqargs.ml:456]: > the content of $OCAMLPATH is passed to Mltop.add_ml_dir? This seems like a very bad idea.

what is the problem when doing that?

Comment (ejgallego) [reply sysinit/coqargs.ml:456]: I guess not a critical one.

I'd be nice tho if we can find some cycles in Sep and remove the legacy mode, actually there is not a lot to do, but what requires time (as you are well aware) is testing.

Comment (silene) [reply sysinit/coqargs.ml:456]: The problem is that, on some systems (e.g., Nix), `$OCAMLPATH` contains the whole world. Thus, when trying to load a legacy plugin, Coq will scan a bunch of directories that are completely unrelated to Coq. (Notice that this pull request scans `env_ocamlpath` before `ml_path`, where the legacy plugins lie.) In fact, if by sheer luck Coq were to actually find a plugin with the searched name in one of these directories, it is guaranteed to be a broken one.

Comment (gares) [reply sysinit/coqargs.ml:456]: OK, then I think @SkySkimmer should avoid this, and that requires changing the API IMO, since you need to separate the paths from OCAMPATH from the others.

I keep the occasion, in case Nix people are listening, to remind that OCAMLPATH is there to let one override the system config, not a place to store it. If they want to stay with env variables, they should add a nix specific one to findlib, eg NIX_OCAMLPATH, and have findlib honor both, giving OCAMLPATH precedence.

Comment (silene) [reply sysinit/coqargs.ml:456]: You only need to change the API if you want `$OCAMLPATH` to be searched after `opts.pre.ml_includes` but before `ml_path`. But why do you even want that in the first place? Why should the Coq directories in `ml_path` not take precedence over `OCAMLPATH`?

Comment (gares) [reply sysinit/coqargs.ml:456]: > remind that OCAMLPATH is there to let one override

because of this?

**Comment by SkySkimmer** [comment]
changed: findlib sees `A:B:$default_dirs:$OCAMLPATH`, legacy loading doesn't see OCAMLPATH

**Comment by gares** [comment]
Hum, this way OCAMLPATH cannot be used to override default_dirs, but just to extend them. Was there a problem with default_dirs being last?

**Comment by Zimmi48** [comment]
> Hum, this way OCAMLPATH cannot be used to override default_dirs, but just to extend them. Was there a problem with default_dirs being last?

https://github.com/coq/coq/pull/16428#issuecomment-1233089729

File: sysinit/coqargs.ml (hunk 3 above)
Comment (Zimmi48) [reply sysinit/coqargs.ml]: > I keep the occasion, in case Nix people are listening, to remind that OCAMLPATH is there to let one override the system config, not a place to store it. If they want to stay with env variables, they should add a nix specific one to findlib, eg NIX_OCAMLPATH, and have findlib honor both, giving OCAMLPATH precedence.

Nix is using this "trick" in many programming languages that have a `PATH` environment variable, and has done so successfully for years. If Nix users had had to request changes to most of their programming tools to be able to work, it would have been less successful. The fact that Nix is becoming more and more important and has more and more users does not justify (IMHO) to introduce Nix-specific quirks in generic tools.

**Comment by gares** [comment]
Hum, so?

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@SkySkimmer adding a test wouldn't hurt, we can simulate a "global" install using the findlib variables, then we can test precedence properly.

File: sysinit/coqargs.ml [hunk 4]
```diff
@@ -442,15 +442,6 @@ let prelude_data = "Prelude", Some "Coq", Some Lib.Import
 let injection_commands opts =
   if opts.pre.load_init then RequireInjection prelude_data :: opts.pre.injections else opts.pre.injections
 
-let build_load_path opts =
```
Comment (ejgallego) [inline sysinit/coqargs.ml:445]: Just curious, if I read this correctly, it seems to me you did inline this function in `coqinit`, why?

The idea of the function was for it to be used by coq-serapi and jscoq (and other toplevels). But indeed, the name should be `load_paths_from_args` to make that clearer.

So not a big deal but it seemed a good idea to me to keep the separation between the loadpaths that come from args and the rest.

Comment (SkySkimmer) [reply sysinit/coqargs.ml:445]: The separation made it harder to work with IMO.
There is no way for me to know what plugins outside CI depend on, they'll have to adapt on their own.

**Comment by SkySkimmer** [comment]
If you want to write a test feel free, I don't have quite enough understanding to do it myself.

File: sysinit/coqargs.ml (hunk 4 above)
Comment (ejgallego) [reply sysinit/coqargs.ml:445]: Yeah I lost track, so I guess there was a version of the PR that did modify it, now it is just inlined so in a sense that change is noise. I don't mind it.

**Comment by ejgallego** [comment]
> If you want to write a test feel free, I don't have quite enough understanding to do it myself.

I'll open an issue, I don't have time to write the test now, but happy to sheperd.

**Review by silene — APPROVED** [review]

File: doc/sphinx/practical-tools/coq-commands.rst [hunk 5]
```diff
@@ -184,6 +184,9 @@ and ``coqtop``, unless stated otherwise:
   (``.cmo`` or ``.cmxs``).  Subdirectories are not included.
   See the command :cmd:`Declare ML Module`.
 
+  Directories added with ``-I`` are searched after the current directory,
+  in the order in which they were given on the command line
```
[the remark this answers is not in the document]
Comment (jfehrle) [reply doc/sphinx/practical-tools/coq-commands.rst:188]: I think neither comma is needed.
