### PR TITLE
Fixes #12467: internal inconsistency when a notation variable is used both for binder lists and for term lists

### LINKED ISSUE #12467: Error: Anomaly "Inconsistent substitution of recursive notation." Please report at http://coq.inria.fr/bugs/.
#### Description of the problem

```coq
Notation "'WITH' ( x1 : t1 ) , x2t2 , .. , xntn  'PRE'  [ ] P 'POST' [ ] Q" :=
  ((fun x1 : t1 => (fun x2t2 => .. (fun xntn => (pair .. (pair x1 x2t2) .. xntn)) .. )),
   (fun x1 : t1 => (fun x2t2 => .. (fun xntn => P) .. )),
   (fun x1 : t1 => (fun x2t2 => .. (fun xntn => Q) .. )))
    (at level 200, x1 at level 0, x2t2 at level 0, xntn at level 0, P at level 100, Q at level 100, only parsing).
Check WITH (x : nat) , (y : nat) , (z : nat) PRE [] (x, y, z) POST [] (z, y, x).
(* Error: Anomaly "Inconsistent substitution of recursive notation."
Please report at http://coq.inria.fr/bugs/.
*)
```

cc @herbelin 

#### Coq Version

8.11.1, also 831e901a8b796c3f2e7cec7f2b5d8adae4dfbea3

### PR DESCRIPTION
**Pull request by herbelin**
The first commit clarifies the conversion between the parsing status of list of binders and the internal (semantic) status of list of binders (functions split_by_type, group_by_type, make_interpretation_type).

This allows to adopt a convention on the internal representation of lists of binders (thus always as binders). This fixes #12467.

The second commit is anecdotical.

The third commit adds parsing and printing of lists of binders restricted to be lists of idents or lists of names or lists of patterns. This is quite a lot of ad hoc code for an interest which is unclear. Comments are welcome. For instance, this allows to define:
```
Notation "'WITH' ( x1 : t1 ) , x2t2 , .. , xntn  'PRE'  [ ] P 'POST' [ ] Q" :=
  ((fun x1 : t1 => (fun x2t2 => .. (fun xntn => (pair .. (pair x1 x2t2) .. xntn)) .. )),
   (fun x1 : t1 => (fun x2t2 => .. (fun xntn => P) .. )), 
   (fun x1 : t1 => (fun x2t2 => .. (fun xntn => Q) .. )))
    (at level 200, x1 at level 0, x2t2 pattern, P at level 100, Q at level 100, only parsing). 
```
while with the first commit, only `x2t2 constr`, or `x2t2 constr as pattern` are allowed (thus parsing any constr, enforcing after parsing that it is a pattern, rather than parsing only patterns).

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.
- [x] Opened **overlay** pull request : ejgallego/coq-serapi#304

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
The PR has now an extra commit to fix the first part of #17094, namely a misclassification of binder entries leading to the error message "x and y should appear in term position as part of a recursive pattern". See #17094 for details on what remains to be implemented so that #17094 works.

@coqbot run full ci

**Comment by herbelin** [comment]
The PR has now another short extra commit to fix a printing part of https://github.com/coq/coq/issues/17094, namely to add printing support for binders that are assumptions parsed as constr. 

@coqbot run full ci

**Comment by herbelin** [comment]
@proux01: by chance, would you have time for reviewing this PR (and possibly the related #17115)?

**Comment by proux01** [comment]
@herbelin I'll try to have a look in the coming days (but can't promise anything)

**Comment by herbelin** [comment]
@proux01: if ever you'd like a presentation of the PR, allowing to save you time, we can have a videocall.

File: parsing/extend.ml [hunk 1]
```diff
@@ -62,11 +62,11 @@ type simple_constr_prod_entry_key =
...
 (** Entries used in productions (in right-hand-side of grammar rules), to parse non-terminals *)
 
-type binder_entry_kind = ETBinderOpen | ETBinderClosed of (bool * string) list
-
 type binder_target = ForBinder | ForTerm
 
-type constr_prod_entry_key =
+type binder_entry_kind = ETBinderOpen | ETBinderClosed of constr_prod_entry_key option * (bool * string) list
+
+and constr_prod_entry_key =
```
Comment (proux01) [inline parsing/extend.ml:69]: I'd rather move it upward and use `type` instead of `and` since there is no mutual recursivity (but I agree this enlarge the diff a bit).

File: printing/ppextend.mli [hunk 2]
```diff
@@ -35,7 +35,7 @@ type unparsing =
   | UnpMetaVar of entry_relative_level * Extend.side option
   | UnpBinderMetaVar of entry_relative_level * pattern_quote_style
   | UnpListMetaVar of entry_relative_level * unparsing list * Extend.side option
-  | UnpBinderListMetaVar of bool * unparsing list
+  | UnpBinderListMetaVar of bool * bool * unparsing list
```
Comment (proux01) [inline printing/ppextend.mli:38]: Perhaps a small comment saying that the booleans are respectively for isopen and noquote.
BTW, wouldn't quote be easier to use than the negative noquote? (well, ideally, those boolean should probably be adhoc variant types with two constructors)

(P.S. : the comment should probably rather be in the mli)

**Review by proux01 — APPROVED** [review]
Sorry for the delay.
LGTM, will rerurn the CI to be on the safe side (last run is one month old now) and merge.

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@herbelin CI green. Let me know if you want to address any of the nitpicking comments I left above, otherwise I'll merge.

File: parsing/extend.ml (hunk 1 above)
Comment (herbelin) [reply parsing/extend.ml:69]: There is a recursivity (in `ETProdBinderList`).

File: interp/notation_term.ml [hunk 3]
```diff
@@ -66,27 +66,29 @@ type extended_subscopes = Constrexpr.notation_entry_level * subscopes
 (** Type of the meta-variables of an notation_constr: in a recursive pattern x..y,
     x carries the sequence of objects bound to the list x..y  *)
 
-type constr_as_binder_kind =
+type notation_binder_kind =
+  (* This accepts only ident *)
   | AsIdent
+  (* This accepts only name *)
   | AsName
+  (* This accepts pattern *)
```
[the remark this answers is not in the document]
Comment (herbelin) [reply interp/notation_term.ml:75]: I think "pattern" is better, as name is included in pattern. It is more `AsNameOrPattern` which should be renamed into `AsNonNecessarilyStrictPattern` (I can do it if you want).

File: printing/ppextend.mli (hunk 2 above)
Comment (herbelin) [reply printing/ppextend.mli:38]: I will add a comment and negate the quote boolean. 

I will also adopt your other suggestions.

File: interp/notation_term.ml (hunk 3 above)
[the remark this answers is not in the document]
Comment (proux01) [reply interp/notation_term.ml:75]: Or maybe just `AsPattern` (with just the comment mentionning it's not necessarily strict)

File: parsing/extend.ml (hunk 1 above)
Comment (proux01) [reply parsing/extend.ml:69]: Indeed, my bad

File: interp/notation_term.ml (hunk 3 above)
[the remark this answers is not in the document]
Comment (herbelin) [reply interp/notation_term.ml:75]: Or `AsAnyPattern` to emphasize a difference with `AsStrictPattern`?

**Comment by proux01** [comment]
@coqbot merge now

**Comment by herbelin** [comment]
Thanks for the review!
