### PR TITLE
[xml protocol] [coqide] Alternative PR fixing some loc problems in master.

### LINKED ISSUE #16987: [coqide] Tooltip locations are broken in `master`
Open this file in coqide:
```
Definition a := 3.

Definition b := 3.  Variable n : nat.
```

Then hover under `Variable n : nat` , you will see no tooltip. If you hover over the first line, you can see that the tooltip tries to appear there.

This is due to a large mess in location handling, fix in #16978 

Note that this bug deals with the case where `coqops:attach_tooltip` is called, and the tooltip is attached incorrectly.

There is a different bug that also makes tooltips to go missing which is when the feedback comes without a `Stateid.t`, but in this case, `attach_tooltip` is never called in the first place.

### LINKED ISSUE #17023: Tooltips for messages with an explicit loc broken
The changes made in #16978 don't display tooltips correctly when the warning has a `loc` value.  (I'm not sure that PR was intended to fix this case.)

I added a command that generates a warning with a `loc`.  ~The first time you run it,~ If you run it with 2 `Forward`s the tooltip doesn't show up correctly:

image

~Resetting Coq and rerunning the script in the same buffer~, If you ~undo and rerun `Foo`~ run both the `Goal` and `Foo` with a single `Run to End`, the tooltip doesn't appear at all.  (You also get this with 2 `Forward`s if `Foo` is not the last line in the buffer.):

image

My test command:

```
      | IDENT "Foo"; x = string -> {
                                        Printf.eprintf "Some bp ep %d %d \n%!" loc.Loc.bp loc.ep;
                                        let f = CWarnings.create ~name:"Foo" ~category:"scope"
                                            (fun () ->
                                             Pp.strbrk "Foo message") in
                                             f ~loc ();
                                             VernacAbort }
```

Attn: @ejgallego

### PR DESCRIPTION
**Pull request by ejgallego**
@herbelin suggested to have a look at the current status of Coq master problems, so indeed, the main source of pain on what we could see is just that the locations are not fully serialized, in particular missing line number on the protocol wire impedes us to properly handle Coq locations effectively (and without hacks).

We also fix a off-by-one error we hand't spot due to the missing line info.

We have verified that this PR seems to fix the loc part of #17023 , modulo the 8.16 behavior, which as noted by Théo is:

> however, in Coq 8.15-8.16, the displayed warning is associated to a (correctly located) underline, but the tooltip is broken, and if we undo and redo the last line, it does not show at all (exactly as described for the Foo command in this issue),

Not sure about the `idtac` display and we didn't get CoqIDE to display it, neither in 8.16.

We submit this PR for testing against #17348 , as to see if `master` revert to 8.16 vs `master` + this fix has more bugs.

Fixes #17023 fixes #16987

### CODE REVIEW

**Comment by herbelin** [comment]
Also: the PR fixes the wrong error line numbers in Errors tab.

For loading @MSoegtropIMC's test file Flocq's Pff.v, it takes for me 3mns (compared to ~1mn with coqc and ~1mn 15s with coqide 8.16).  So this seems a bit too long (but I don't know which PR caused this).

Location, message and tooltip on warnings works for e.g. `Set unknown option`, or `Variable a:nat` at toplevel. For `Focus`, location is ok but the tooltip is empty, apparently due a wrong stm id (so Coq side, since 8.15).

**Comment by Zimmi48** [comment]
> For loading @MSoegtropIMC's test file Flocq's Pff.v, it takes for me 3mns (compared to ~1mn with coqc and ~1mn 15s with coqide 8.16). So this seems too long (but I don't know which PR caused this).

I'll let @coq/coqide-maintainers be the judges, but I would tend to find this an acceptable performance regression in CoqIDE. From what I recall, the previous performance regression was way worse on this file. This should also be compared with the alternative in https://github.com/coq/coq/pull/17348, rather than with Coq 8.16.

Another point of comparison is that this PR currently passes CI fully, but https://github.com/coq/coq/pull/17348 does not (although its backport for Coq 8.17 does).

**Comment by Zimmi48** [comment]
Oh, but I didn't realize that this fix actually changes the XML protocol, so would be good for Coq `master` only and would require documentation and fixing Coqtail + VsCoq.

So, we could merge #17381 in `v8.17` and this PR in `master`...

**Comment by ejgallego** [comment]
Yes this PR changes the XML protocol hence it would be master-only. Hugo's idea was to see whether we could do better in `master` than just reverting to 8.16 status which had some problems on its own.

There should not be any performance regression in master w.r.t. large files, if that is happening then we got a bug, wouldn't be surprised. If someone can profile CoqIDE and see where the time is spent with this patch that could be helpful.

**Comment by MSoegtropIMC** [comment]
As discussed in Zulip I can test CoqIDE but I see still PRs opened. Please let me know when is a good time to test and then also which commit to test.

**Comment by Zimmi48** [comment]
> As discussed in Zulip I can test CoqIDE but I see still PRs opened. Please let me know when is a good time to test and then also which commit to test.

The point is precisely to test PRs before they are merged though.

**Comment by MSoegtropIMC** [comment]
> The point is precisely to test PRs before they are merged though.

Sure, but afaik there are several PRs and some pushed to again and I don't have the bandwidth to test it 5 times. So I need to know what the sweet spot is.

Btw.: with CoqIDE 8.17+rc1 I get for my favourite IDE test file

https://gitlab.inria.fr/flocq/flocq/-/blob/master/src/Pff/Pff.v

a strange syntax error when stepping over the tactic definitions right at the top.

**Comment by MSoegtropIMC** [comment]
> > For loading MSoegtropIMC's test file Flocq's Pff.v, it takes for me 3mns

2..3 minutes is normal. If it is bad it is more like an hour.

**Comment by ppedrot** [comment]
FWIW the runtime of go-to-end with CoqIDE on Pff.v with both this PR and master are the same. Furthermore I don't see anything suspect, neither in the profiling of coqide nor on the one of coqidetop. So for me this is good.

**Comment by MSoegtropIMC** [comment]
@ppedrot : I guess this means you also don't get the strange syntax error I am getting with 8.17+rc1.

I am currently working on getting the smoke test kit in Coq Platform master working - in creates _CoqProject files, so one can load all files directly into CoqIDE. It should work again today evening.

**Comment by ppedrot** [comment]
Also, as I've already ranted about at the WG this still looks fundamentally broken to me because the protocol confuses lines with sentences. You can trigger line desynchronization with the following snippet.
```coq
Ltac wait n := match n with 0 => idtac | S ?n => wait n; wait n end.

#[deprecated(since="8.16")] Notation tt0 := tt.

Goal True.
Proof.
fail.
Qed.

Goal True.
Proof.
wait 20.
elim tt0.
Qed.
```
To trigger the bug, eval to end and before the "wait 20" line returns, introduce random text in the first Proof-Qed block. This will cause the warning location to be shifted by as many lines inserted. This kind of problem can only be solved by making locations sentenceid-based, but I'm not sure we want this. This would require changing the protocol, again.

**Comment by herbelin** [comment]
> Yes this PR changes the XML protocol hence it would be master-only.

Wasn't #17348 already changing the XML protocol (in the sense of changing the conventions about the positions returned in Message outputs of Coq)?

Conversely, what convention are Coqtail or vscoq expecting the locations returned by Coq?

As far as I'm concerned, if Coqtail and vscoq are fine with the PR (i.e., see next comment, if neither #17348 nor this PR change their use of the protocol - up to adding a fallback when bol_pos and cie are not present, but this is easy to do), the locs seem good in what I tested and I would recommend merging the PR.

> 2..3 minutes is normal. If it is bad it is more like an hour.

Then, ok, let's not make the current 2-3mns situation "blocking" (reminding that these 2-3 mins are indeed unrelated to this PR).

> the protocol confuses lines with sentences.

My (vague) perception is that the cause of the loc shift when interactively editing (also reported in #17023) is not about the use of lines per se but about how a returned message is dynamically "relocated" wrt to the beginning of the input initially sent (rather than kept relatively to the beginning of the buffer).

**Comment by jfehrle** [comment]
> @ppedrot You can trigger line desynchronization with the following snippet.

The fix I proposed in #17012 handles this case just fine without changing the protocol and so could be included in 8.17:

image

**Comment by ejgallego** [comment]
> To trigger the bug, eval to end and before the "wait 20" line returns, introduce random text in the first Proof-Qed block. This will cause the warning location to be shifted by as many lines inserted.

Fixed by the last commit. Actually you only need to compensate for the offset difference of when the tooltip was created. At some we had a similar mechanism but was broken for other reasons, it should be now more principled.

> This kind of problem can only be solved by making locations sentenceid-based, but I'm not sure we want this. This would require changing the protocol, again.

Only may be a too strong statement here, given any sentence, you can actually compute the absolute offset that the sentenced has moved when compared to its creation, so you can adjust locations that were created a sentence-creation time, as done now. So no change in the protocol needed, just proper handling of information lifetime (in particular when you wanna do some incremental stuff such as not regenerating tooltips in later parts of the document)

**Comment by herbelin** [comment]
@jfehrle: if I'm correct, the fix in #17012 (for None) was included in #16978, right?

I tested warnings, errors and tooltip in vscoq.
- the location of `Focus` (as reported in #17023) is wrong (one line above) for 8.15, 8.16, master and this PR (*)
- the location of the underlining and of the tooltip on say `Variable n:nat` at toplevel or of a `Set UnknownFlag` is correct in 8.15, 8.16, master and this PR (except that it starts from the period at the line before...)
- the location of errors seems correct for 8.15, 8.16, master and this PR.
- the presence of unicode does not break the locations

My conclusion on these tests is that this PR is not worse for vscoq than previous statuses.

I don't know how to test coqtail.

(*) maybe the same +1 missing somewhere as in Coq at some time?

**Comment by jfehrle** [comment]
> @herbelin if I'm correct, the fix in https://github.com/coq/coq/pull/17012 (for None) was included in https://github.com/coq/coq/pull/16978, right?

The code for the None case looks like it's probably equivalent.  The code for the Some case was not included.  Hard to remember who did what when 3 months after working on it.  And hard to visualize the net change when it's split across multiple PRs.

> I tested warnings, errors and tooltip in vscoq.

Meaning this PR or #17012?

**Comment by jfehrle** [comment]
> @ejgallego Fixed by the last commit. Actually you only need to compensate for the offset difference of when the tooltip was created. At some we had a similar mechanism but was broken for other reasons, it should be now more principled.

You've adopted my approach, which is to save and apply the original offset in the sentence.  Earlier you were rejecting that out of hand.  (At the time, you seemed unable or unwilling to understand my short code.)  If you use that approach, you don't need to modify the protocol at all.  That seems like a better solution.

**Comment by herbelin** [comment]
Same analysis with coqide (confirming the analysis of @Zimmi48 [here](https://github.com/coq/coq/issues/17023#issuecomment-1366644890):
- the location of the warning for `Focus` is ok for 8.15, 8.16 and this PR; depending on position in text, tooltip is empty (only the bulb) or absent; ill-located and well-tooltipped in 8.14; not located, nor tooltipped in master
- the location of the warning and of the tooltip on say `Variable n:nat` at toplevel or of a `Set UnknownFlag` is correct in 8.14, 8.15, 8.16, master and this PR
- the location of errors seems correct for 8.14, 8.15, 8.16, master and this PR.
- the location of errors from the error tab seems correct for 8.14, 8.15, and this PR but wrong in 8.16 and master
- the presence of unicode does not break the locations
- the blue display of the debugger is ok in 8.16, master and in the PR
- the red display of breakpoint of the debugger is ok in 8.16, master and in the PR but the setting of the breakpoint is off by 1 in 8.16, master and the PR (you need to highlight the character preceding the first letter of the tactic name)

So, shortly, the PR looks good to me (no change for vscoq, improvement for coqide, even though the ltac breakpoint is still off by one and the tooltip on `Focus` is still empty).

**Comment by ejgallego** [comment]
@herbelin the missing tooltip in focus is due to the tooltip being attached to the wrong sentence, the code in `tooltip_callback` will still display the icon even if no matching tooltip was setup.

That's beyond what we can fix here I think.

**Comment by herbelin** [comment]
> That's beyond what we can fix here I think.

Yes, I don't think it is important to fix now (even if, apparently, vscoq knows how to do it correctly).

So, @Zimmi48 may merge the PR tomorrow, if no opposition?

**Comment by jfehrle** [comment]
> @herbelin the red display of breakpoint of the debugger is ok in 8.16, master and in the PR but the setting of the breakpoint is off by 1 in 8.16, master and the PR (you need to highlight the character preceding the first letter of the tactic name)

Are you sure?  I don't see that behavior with this PR.  I'm on Windows+WSL if it is perhaps a machine/library version issue.  (I couldn't remember the incantation to build and test on 8.16.   I certainly would have noticed such an obvious debugger issue long ago.)

**Comment by herbelin** [comment]
I used the following example:
```
Ltac f := intros; idtac "A".

Set Ltac Debug.

Lemma testl :  True -> True.
f.
```
If I press F8 on the `i` of `idtac`, the `d` is red and it does not stop. If I press F8 on the space before the `i`, the `i` becomes red and it does stop (on MacOS 12). Tested with 8.16, master, and the PR.

**Comment by jfehrle** [comment]
You have to click before you press F8.  Do you see the cursor in this position before you press F8?

image

If I press F8 at this point, CoqIDE highlights the "i".

image

Click-drag to select text works uses similar cursor positioning.  If you click on the left half of a character, the cursor goes before the character and otherwise after it.

**Comment by herbelin** [comment]
Yes, it is like you describe. I think I just got confused with the text in the reference manual which says "position the cursor on the first character of the tactic name in an Ltac construct", which I wrongly interpreted as "select the first character of the tactic name in an Ltac construct".

**Comment by Zimmi48** [comment]
If this PR is for master only, I'd rather have a CoqIDE maintainer merge it and handle the merging of the v8.17-only PR.

**Comment by Zimmi48** [comment]
I would like to merge https://github.com/coq/coq/pull/17381 ASAP so that I can release 8.17.0. Has it been tested so far? For consistency, it would be better to also merge a fix for master, but this can wait a few more days for sure.

**Comment by herbelin** [comment]
> Needlessly changing the protocol to fix the tooltip problems is dumb.

My understanding of the protocol changes is the following:
- XML protocol: the line position is now passed, so if the UI does not use the line position (and it does not have too because it was not meaningful anyway beforehand), this change is invisible for the UI.
- Convention on lexer: the "bp_" hack is removed; I suppose this has virtually an impact on clients of the protocol but I was not able to observe an impact on vscoq (see tests made above). If Jim or Emilio can explain what impact it may have, that would help.
 
BTW, I doubt that the lexer conventions are taken into account in the versioning of the protocol. I guess the versioning only reflects the XML DTD syntax of the protocol (??).

**Comment by ejgallego** [comment]
Indeed the protocol change here is not "breaking" in the sense that most clients should continue to work fine, as this change is an extension and behavior-preserving for clients not using it.

The change to the lexer semantics won't impact any user as indeed that change in the protocol was introduced in #14644 not in any of the PRs we have been discussing, and clients are just keeping the old model, for example see this patch:

 https://github.com/whonore/Coqtail/pull/209/files#diff-ebca5b65ea24f824b2440bde41ead9887fc43854a42f1d09411ebdddbe27f5c4R1751

CoqIDE wanted absolute positions for sentences, however the implementation there was buggy and not fully finished in terms of not setting the lexer resumption status correctly.

**Comment by jfehrle** [comment]
> @ejgallego Indeed the protocol change here is not "breaking" in the sense that most clients should continue to work fine, as this change is an extension and behavior-preserving for clients not using it.

Someone should test this in Coqtail before we merge this rather than assuming it is nonbreaking.

**Comment by whonore** [comment]
I can check this with Coqtail a little later today.

**Comment by whonore** [comment]
I compiled this and did a couple quick checks and it does seem to work fine in Coqtail. That's what I'd expect since Coqtail just ignores the `<loc>` child in `<message>` tags and that seems to be the only place they're used. Is that correct?

**Comment by ejgallego** [comment]
> I compiled this and did a couple quick checks and it does seem to work fine in Coqtail. That's what I'd expect since Coqtail just ignores the `<loc>` child in `<message>` tags and that seems to be the only place they're used. Is that correct?

@whonore eventually the loc in the Fail query will be also affected, but that it is.

File: ide/coqide/coqOps.ml [hunk 1]
```diff
@@ -58,6 +59,11 @@ module SentenceId : sig
 
   val start_iter : GText.buffer -> sentence -> GText.iter
   val start_stop_iters : GText.buffer -> sentence -> GText.iter * GText.iter
+
+  (** [ofsset_compensation] Drift of a sentence over its original
```
Comment (jfehrle) [inline ide/coqide/coqOps.ml:63]: Typo: SB offset_compensation

File: ide/coqide/coqOps.ml [hunk 2]
```diff
@@ -58,6 +59,11 @@ module SentenceId : sig
...
+      location, in offset. May be needed to compensage Coq locations. *)
```
Comment (jfehrle) [inline ide/coqide/coqOps.ml:64]: Typo: SB compensate (?)

"offset" is characters or bytes?

File: ide/coqide/protocol/serialize.ml [hunk 3]
```diff
@@ -110,16 +110,44 @@ let to_edit_id = function
...
+  ; ep
+  } = loc in
+  Element ("loc",
+           [ ("line_nb", string_of_int line_nb)
+           ; ("bol_pos", string_of_int bol_pos)
+           ; ("line_nb_last", string_of_int line_nb_last)
+           ; ("bol_pos_last", string_of_int bol_pos_last)
+           ; ("start", string_of_int bp)
+           ; ("stop", string_of_int ep )
+           ],
```
Comment (jfehrle) [inline ide/coqide/protocol/serialize.ml:129]: Returning values other than `start` and `stop` isn't helpful.  For Pierre-Marie's example, the returned `line_nb` may be incorrect (and unusable) because new line(s) were inserted in the buffer above the sentence.  Same thing for `bol_pos`, `line_nb_last` and `bol_pos_last`.  All these values could be incorrect and would need to be recomputed in CoqIDE, so there's no point in sending them in the first place.

**Review by jfehrle — DISMISSED** [review]
I suggest abandoning this PR.

File: ide/coqide/protocol/serialize.ml (hunk 3 above)
Comment (ejgallego) [reply ide/coqide/protocol/serialize.ml:129]: Your argument seems strange as by it, also `start` and `stop` would be useless as they would have to be recomputed in Pierre-Marie's example.

Anyways they are recomputed fine and things work OK, and moreover the current code makes sense from an implementation and data ownership properties.

Line/column location is actually pretty useful due to the way the GTK API work (and other editors can for sure profit from it). The benefits are already clear if you look at the code in this PR vs the code in 8.16.

Comment (jfehrle) [reply ide/coqide/protocol/serialize.ml:129]: How would you return a correct value for `bol_pos` for stmt2 for the following input?  The two statements are passed in separate calls to the parser (`(* comment *)\nstmt1.` and ` stmt2.`).  Would you have the parser retain this state or require that CoqIDE always pass the previous `bol_pos` (which is not easy to manage)?  Same thing for `bol_pos_last`.

It's not worth the trouble to make this work (likely fragile in CoqIDE) and it's silly to return values that the GUI can't rely on.

```
(* comment *)
stmt1. stmt2.
```

In `idetop.ml`, the earlier code was like this.  There are two problems.  First, the parser ignores `bol_pos`.  Second, it's not convenient for CoqIDE to pass the correct value.  Hence my comment "this won't yield correct values for bol_pos_last".

```
let add ((((s,eid),(sid,verbose)),off),(line_nb,bol_pos)) =
  let doc = get_doc () in
  let open Loc in
  (* note: this won't yield correct values for bol_pos_last,
     but the debugger doesn't use that *)
  let loc = { (initial ToplevelInput) with bp=off; line_nb; bol_pos } in   (* bol_pos IGNORED *)
  let r_stream = Gramlib.Stream.of_string ~offset:off s in
  let pa = Pcoq.Parsable.make ~loc r_stream in
```

**Comment by jfehrle** [comment]
This is busted too.  Doesn't work for PMP's example.

Tooltip is empty:

image


Tooltip highlight is mispositioned, no tooltip appear if you hover over the period.

image

File: ide/coqide/protocol/serialize.ml (hunk 3 above)
Comment (jfehrle) [reply ide/coqide/protocol/serialize.ml:129]: Your branch has exactly the code shown above, so I very much doubt it.  Try adding some print statements in the lexer to see what is returned for my little example above.

Comment (jfehrle) [reply ide/coqide/protocol/serialize.ml:129]: IINM this test suggests that it's incorrect:  (I made the tactic that gets the warning the second sentence on the line.)

image

Comment (ejgallego) [reply ide/coqide/protocol/serialize.ml:129]: I'll have a look thanks, but if we can set `bp` correctly there is certainly not a problem setting `bol_pos` correctly too.

Comment (jfehrle) [reply ide/coqide/protocol/serialize.ml:129]: Even if you can, it adds a bunch more bookkeeping (and adjustment) on the CoqIDE side.

Comment (ejgallego) [reply ide/coqide/protocol/serialize.ml:129]: It adds maybe one line of bookeeping, true, but on the other it provides accurate info on line / column which is very useful for other endeavors, like for example reusing GTK's index-to-char UTF conversion methods, so the tradeoff is a clear win.

Moreover quite a few parts of the interface could use accurate line/column info.

**Comment by ejgallego** [comment]
Thanks for the testing, I'll see what happened as that example was working last time I checked.

**Comment by Zimmi48** [comment]
I've put the blocker label because if this is not finished soon (and in time for 8.18), then #17348 should be merged in `master` (so far, only it's backported version was merged, directly to `v8.17`).

File: ide/coqide/protocol/serialize.ml (hunk 3 above)
Comment (ejgallego) [reply ide/coqide/protocol/serialize.ml:129]: There were indeed two bugs here, see commit messages.

Comment (ejgallego) [reply ide/coqide/protocol/serialize.ml:129]: Actually the bug was pretty subtle if you are curious, we were setting `bol_pos` correctly, but not `bol_pos_last`, which turns out to be used by the lexer in this particular example so the location with the warning the lexer used `bol_pos_last` setting bol_pos to the incorrect value.

So far all test cases look good to me.

**Comment by jfehrle** [comment]
I will look at it.

**Comment by jfehrle** [comment]
This latest code still doesn't work.  The issues are that:
- the tooltips are empty in both test cases, and
- the tooltip is on the wrong line and sentence if the user adds new lines in the failed proof.

For the second screen shot, the tooltip should be on "tt0" on line 16; instead 3 characters on line 13 are highlighted.  (16 - 13 = 3, the number of lines the user added to the failed proof.  I suspect the issue is that you also need to adjust the line number of the sentence (I didn't try to read the code).

image

 ```

```
  

image

**Comment by jfehrle** [comment]
These match the hashes shown by github.

image

**Review by ppedrot — APPROVED** [review]
This is a sensible way to fix the current mess. Regardless of the full correctness status of this PR, I am intending to merge it now.

**Comment by ppedrot** [comment]
@ejgallego any progress on this?

**Comment by ppedrot** [comment]
@ejgallego This PR makes it already way better than we have on master, and it's a blocking issue for the 8.18 release. If you don't have a look soon, I'll forcefully merge this PR so that it does not delay 8.18.

**Comment by Zimmi48** [comment]
Indeed! Either this PR, or the solution that was merged in v8.17, should be merged in master and available in 8.18.

**Comment by ejgallego** [comment]
Ok, found the last problem, I think this looks ready to me.

Last commit contains the detailed information, but basically we need to be careful about what our ground truth for locations are, and correct in all cases (coqide likes to use location sources with are related to the Coq location truth in different ways)

Also, due to the UTF-8 conversion routine, we need to compute line_drift.

All the examples I could come up with seem to be working now; I'd be there are more bugs lurking around (maybe the "errors" panel doesn't account for drift properly?), but IIANM, the current infrastructure should be solid in that sense and allow for quick fixes.

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
@coqbot merge now

File: ide/coqide/coqOps.ml [hunk 4]
```diff
@@ -40,13 +40,16 @@ module SentenceId : sig
     mutable flags : flag list;
     mutable tooltips : (int * int * string) list;
     start_offset : int;
+    (** Original start offset of the sentence, to be compared when moved *)
+    start_line : int;
+    (** Original start line of the sentence, to be compared when moved *)
```
Comment (ejgallego) [inline ide/coqide/coqOps.ml:45]: To clarify semantics, "Original" here means "location Coq thinks the sentence is at." 

The `start` / `stop` marks do contain the buffer real location of the sentence, so `offset_compensation` below can be used to apply / track the delta between the two.
