### PR TITLE
Be more resilient to garbage arguments passed to rocq check.

### LINKED ISSUE #14397: coqchk should handle the empty string gracefully
```
$ coqchk ''
Fatal Error: Error during initialization :Anomaly: uncaught exception Invalid_argument "path_of_string".
                                          Please report at
                                          http://coq.inria.fr/bugs/.
$ coqchk ' '
Welcome to Chicken 8.13.1 (April 2021)
Fatal Error: User error: Cannot find library   in loadpath
```

### PR DESCRIPTION
**Pull request by ppedrot**
We print a proper error rather than dying with an anomaly.

Fix #14397: coqchk should handle the empty string gracefully.

### CODE REVIEW

File: checker/coqchk_main.ml [hunk 1]
```diff
@@ -165,17 +165,21 @@ let make_senv () =
   let senv = Safe_typing.set_allow_sprop true senv in (* be smarter later *)
   Safe_typing.set_native_compiler false senv
 
+let try_add_path s l = match path_of_string s with
+| Ok path -> path :: l
+| Error () -> CErrors.user_err (str "Invalid path " ++ qstring s)
```
Comment (SkySkimmer) [inline checker/coqchk_main.ml:170]: why not user_err directly in path_of_string?

Comment (ppedrot) [reply checker/coqchk_main.ml:170]: I hesitated to put a warning rather than an error, and written that way it makes it easy to replace it locally.

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now
