### PR TITLE
[native compiler] Fix critical bug with stuck primitive projections

### LINKED ISSUE #9684: Index out of bounds in native_compute
#### Description of the problem

Running a native_compute in file examples/AlmostFull.v of this branch of Equations https://github.com/mattam82/Coq-Equations/tree/almost_full_native_compute_bug
on current master results in an "Index out of bounds" error. It's hard to minimize. I would bet we're doing something wrong with universes (there are a few polymorphic things there).

#### Coq Version

master

### PR DESCRIPTION
**Pull request by maximedenes**
Since e1e7888, stuck projections were not computed correctly.

Fixes #9684

### CODE REVIEW

File: pretyping/nativenorm.ml [hunk 1]
```diff
@@ -222,7 +222,12 @@ and nf_type_sort env sigma v =
   match kind_of_value v with
   | Vaccu accu -> 
       let t,s = nf_accu_type env sigma accu in
-      let s = try destSort s with DestKO -> assert false in
+      let s =
+        try
+          destSort (whd_all env s)
+        with DestKO ->
+          CErrors.anomaly (Pp.str "Value should be a sort")
+      in
```
Comment (SkySkimmer) [inline pretyping/nativenorm.ml]: Why bother catching the destko?

Comment (maximedenes) [reply pretyping/nativenorm.ml]: This was there before. I guess the idea is that `DestKO` is used as a catchable exception in the codebase. So we want to raise a fatal exception here.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
Why not mark this for backporting (i.e. put this in the 8.9.1 milestone)? Otherwise, the "Impacted version" information is quickly going to become out of date when 8.9.1 is released.

**Comment by maximedenes** [comment]
> Why not mark this for backporting (i.e. put this in the 8.9.1 milestone)? Otherwise, the "Impacted version" information is quickly going to become out of date when 8.9.1 is released.

Right, it is better in the 8.9.1 milestone. Note that only one of the two commits will have to be backported (the other one is fixing an aggravation of the problem after the merge of `SProp`).

File: pretyping/nativenorm.ml (hunk 1 above)
Comment (SkySkimmer) [reply pretyping/nativenorm.ml]: Is there a reason to expect a destko to happen here? Considering we raise an anomaly it seems strange to me.

Comment (maximedenes) [reply pretyping/nativenorm.ml]: > Is there a reason to expect a destko to happen here?

No, except in a tricky scenario as was the case. It should certainly be a fatal error, otherwise debugging will be a pain (imagine this gets caught by unification).

I'm afraid I don't understand your concern. You feel more comfortable with raising an exception that can be silently caught by random clients?

**Review by ppedrot — APPROVED** [review]
That will teach me to look up for the place where a lexical variable is bound, a.k.a λ-calculus 101.

**Comment by maximedenes** [comment]
@ppedrot can you be the assignee?

**Comment by maximedenes** [comment]
@ppedrot ping
