### PR TITLE
Fix #21902: Incorrect path constraint in with Module construct.

### LINKED ISSUE #21902: Incorrect path constraint in with Module construct
### Description of the problem

The path check in Mod_typing is incorrect in the submodule case, it uses the wrong modpath. This doesn't seem to lead to a proof of False, but is instead a source of incompleteness.

### Small Rocq / Coq file to reproduce the bug

```coq
Module Type Inner.
  Parameter t : Type.
End Inner.

Module ConcreteInner : Inner.
  Definition t := True.
End ConcreteInner.

Module Wrapper.
  Module Sub := ConcreteInner.
End Wrapper.

Module Type MT.
  Module A := Wrapper.
End MT.

Module Type Good := MT with Module A.Sub := ConcreteInner.
(* No field named A in MT. *)
```

### Version of Rocq / Coq where this bug occurs

_No response_

### Interface of Rocq / Coq where this bug occurs

_No response_

### Last version of Rocq / Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by ppedrot**
This is seemingly not a soundness issue but it is still problematic enough.

### CODE REVIEW

File: kernel/mod_typing.ml [hunk 1]
```diff
@@ -232,7 +232,7 @@ let rec check_with_mod (cst, ustate) env struc (idl,new_mp) mp reso =
         before @ (lab, SFBmodule new_mb) :: new_after, subreso, cst
       | Algebraic (MENoFunctor (MEident mp0)) ->
         let mpnew = rebuild_mp mp0 idl in
-        check_modpath_equiv env' mpnew mp;
+        let () = check_modpath_equiv env' mpnew new_mp in
```
Comment (yannl35133) [inline kernel/mod_typing.ml]: Can you use more understandable names than `mpnew` vs `new_mp`?

Comment (ppedrot) [reply kernel/mod_typing.ml]: There you go, here is a version without a confusing name (and the same comparison order as in the check for the toplevel case).

Comment (yannl35133) [reply kernel/mod_typing.ml]: At least now it mirrors better what happens 32 lines above; not that I could attest that part was correct.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now
