### PR TITLE
[lib] Respect change of options under with/without_option.

### LINKED ISSUE #6645: Set Silent is broken
#### Version

8.8+alpha (e2d1c676b23a335b4fb8a528c99dfca2b82a1a39)

#### Description of the problem

This is wrong, and makes it extremely painful to do some proofs because every period incurs an overhead of multiple seconds while Coq does useless work trying to print goals.

```coq
$ ~/.local64/coq/coq-master/bin/coqtop -emacs
Welcome to Coq jgross-Leopard-WS:/home/jgross/Downloads/coq/coq-master,master (e2d1c676b23a335b4fb8a528c99dfca2b82a1a39)

<prompt>Coq < 3 || 0 < </prompt>Set Silent.

<prompt>Coq < 4 || 0 < </prompt>Goal True.
1 subgoal (ID 1)
  
  ============================
  True

<prompt>Unnamed_thm < 5 |branch| 0 < </prompt>
jgross@jgross-Leopard-WS:~/Documents/repos/coq$ ~/.local64/coq/coq-master/bin/coqtop -emacs
Welcome to Coq jgross-Leopard-WS:/home/jgross/Downloads/coq/coq-master,master (e2d1c676b23a335b4fb8a528c99dfca2b82a1a39)

<prompt>Coq < 3 || 0 < </prompt>Goal True.
1 subgoal (ID 1)
  
  ============================
  True

<prompt>Unnamed_thm < 4 |branch| 0 < </prompt>Set Silent.

<prompt>Unnamed_thm < 6 |branch| 0 < </prompt>idtac.
1 subgoal (ID 1)
  
  ============================
  True

<prompt>Unnamed_thm < 7 |branch| 0 < </prompt>
```

### PR DESCRIPTION
**Pull request by ejgallego**
The old semantics of `with/without_option` allowed the called function
to modify the value of the option. This is an issue mainly with the
`silently/verbose` combinators, as `Set Silent` can be executed under
one of them and thus the modification will be lost in the updated code
introduced in a554519874c15d0a790082e5f15f3dc2419c6c38

IMHO these kind of semantics are quite messy but we have to preserve
them in order for the `Silent` system to work. In fact, note that in
the previous code, `with_options` was not consistent with
`with_option` [maybe that got me confused?]

Ideally we could restore the saner semantics once we clean up the
`Silent` system [that is, we remove the flag altogether], but that'll
have to wait.

Fixes #6645.

### CODE REVIEW

File: lib/flags.ml [hunk 1]
```diff
@@ -6,18 +6,28 @@
...
-let with_modified_ref r nf f x =
+(* [respect] indicates whether if [f] modifies the ref, we preserve
+   the modification. *)
+let with_modified_ref ?(restore=true) r nf f x =
   let old_ref = !r in r := nf !r;
-  try let res = f x in r := old_ref; res
+  try
+    let pre = !r in
+    let res = f x in
+    (* If r was modified don't restore it's old value *)
```
Comment (psteckler) [inline lib/flags.ml]: `its`, not `it's`

File: lib/flags.ml [hunk 2]
```diff
@@ -6,18 +6,28 @@
 (*         *       GNU Lesser General Public License Version 2.1        *)
 (************************************************************************)
 
-let with_modified_ref r nf f x =
+(* [respect] indicates whether if [f] modifies the ref, we preserve
```
Comment (psteckler) [inline lib/flags.ml]: I think you mean `restore`, not `respect` in the comment

Comment (ejgallego) [reply lib/flags.ml]: Yup, the option was renamed in some revision of the patch, both comments fixed, thanks!
