### PR TITLE
Fix name generation in `destruct bla as [_ _0]` when name mangling is on

### LINKED ISSUE #17994: `apply <-` fails with name mangling enabled
#### Description of the problem

The following script surprisingly fails:
```
Set Mangle Names.

Section test.
  Context (P Q : Prop).
  Lemma p_q : P <-> Q. Proof. Admitted.
  Lemma test : Q -> P.
  Proof.
    intros HQ. apply <-p_q.
```
```
Error: _0 is already used.
```
Without `Set Mangle Names`, it works fine.

#### Coq Version

8.17.0

### PR DESCRIPTION
**Pull request by SkySkimmer**
Name mangling means that feeding a fresh name into the name generator
with insufficient avoid set may produce a non-fresh name.

Fix #17994

### CODE REVIEW

**Comment by SkySkimmer** [comment]
(the original example does essentially `let H := fresh in destruct bla as [_ H]` which boils down to `destruct bla as [_ _0]` with name mangling on. See https://github.com/coq/coq/blob/96dd2317ee2aa78d22ddd4b4f0103661cf85c49a/theories/Init/Tactics.v#L147)

**Comment by ppedrot** [comment]
This seems to be a partial revert of eb38680, do you know what changed since?

File: tactics/tactics.ml [hunk 1]
```diff
@@ -2478,7 +2471,7 @@ let rec make_naming_action avoid l = function
   (* In theory, we could use a tmp id like "wild_id" for all actions
      but we prefer to avoid it to avoid this kind of "ugly" names *)
   | IntroWildcard ->
-    NamingBasedOn (fresh_wild (Id.Set.union avoid (explicit_all_intro_names l)), Id.Set.empty)
+    NamingBasedOn (Id.of_string "_H", Id.Set.union avoid (explicit_all_intro_names l))
```
Comment (SkySkimmer) [inline tactics/tactics.ml:2474]: This was 
```suggestion
    NamingBasedOn (Id.of_string "_H", Id.Set.union avoid (explicit_intro_names l))
```
before eb38680520811e7a5e64678719d7b57e87af1269

Comment (SkySkimmer) [reply tactics/tactics.ml:2474]: (ie not containing the `IntroFresh` names)

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
AFAICT CI failures are spurious, so @coqbot merge now
