### PR TITLE
[coqtop] be verbose only in interactive mode

### LINKED ISSUE #13864: `coqtop -print-mod-uid` has become too noisy
```console
> bin/coqtop -print-mod-uid theories/Init/Datatypes.vo
Welcome to Coq 8.14+alpha (February 2021)
theories/Init/.coq-native/NCoq_Init_Datatypes
```

Expected output: no banner, as it is meant to be consumed by other tools.

This is regression with respect to Coq 8.13.  It was caused by f5ec3f5cbd4bc2e0f65e1c52143b199ce7c2a5ad from #13418. @gares

### PR DESCRIPTION
**Pull request by gares**
Fix #13864 CC @silene

### CODE REVIEW

**Comment by gares** [comment]
@MSoegtropIMC FYI the windows64 failure is due to a full hard drive.

File: test-suite/misc/coqtop_print-mod-uid.sh [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+export COQBIN=$BIN
+export PATH=$COQBIN:$PATH
+
+TMP=`mktemp -d`
+cd $TMP
+
+function assert_eq() {
+  if [ "$1" != "$2" ]; then
+    echo "coqtop -print-mod-uid" $1 "!=" $2
```
Comment (silene) [inline test-suite/misc/coqtop_print-mod-uid.sh:11]: The error message will be quite strange, since it will show the result of `coqtop` as an argument of `coqtop`.

File: test-suite/misc/coqtop_print-mod-uid.sh [hunk 2]
```diff
@@ -0,0 +1,24 @@
+#!/usr/bin/env bash
+
+export COQBIN=$BIN
+export PATH=$COQBIN:$PATH
+
+TMP=`mktemp -d`
+cd $TMP
```
Comment (SkySkimmer) [inline test-suite/misc/coqtop_print-mod-uid.sh:7]: We usually put the files in a misc/ subdirectory.
For this test I would just use prerequisite/admit instead of making new files though.

File: test-suite/misc/coqtop_print-mod-uid.sh [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+    cd /
+    rm -rf $TMP
+    exit 1
+  fi
+}
+
+mkdir theories/
+touch theories/a.v
+coqc -R theories foo.bar theories/a.v
+assert_eq `coqtop -print-mod-uid theories/a.vo` "theories/.coq-native/NFoo_Bar_A"
```
Comment (SkySkimmer) [inline test-suite/misc/coqtop_print-mod-uid.sh:21]: Please use $() instead of backquotes (I thought it was a regular string with single quotes and wasconfused until I looked closer)

File: test-suite/misc/coqtop_print-mod-uid.sh [hunk 4]
```diff
@@ -0,0 +1,17 @@
+#!/usr/bin/env bash
+
+export COQBIN=$BIN
+export PATH=$COQBIN:$PATH
+
+function assert_eq() {
+  if [ "$1" != "$2" ]; then
+    echo "Unexpected output: " $1 "!=" $2
+    cd /
+    rm -rf $TMP
```
Comment (silene) [inline test-suite/misc/coqtop_print-mod-uid.sh:10]: I am always a bit worried I see `rm -rf` just next to `cd /`. Anyway, this can all be removed now.

File: test-suite/misc/coqtop_print-mod-uid.sh [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+    exit 1
+  fi
+}
+
+assert_eq "$(coqtop -print-mod-uid primitive/admit.vo)" "primitive/.coq-native/NTestSuite_admit"
+
+exit 0
```
Comment (SkySkimmer) [inline test-suite/misc/coqtop_print-mod-uid.sh:17]:
```suggestion
[ "$(coqtop -print-mod-uid primitive/admit.vo)" = "primitive/.coq-native/NTestSuite_admit" ]
```

**Comment by gares** [comment]
Eureka

**Review by silene — APPROVED** [review]

**Comment by silene** [comment]
Given the existence of #13861, is there a chance the bench would fail on Windows?

**Comment by gares** [comment]
IIRC windows64 just tests the platform scripts which don't run the test suite and, for now, don't install coq-native either.

**Comment by SkySkimmer** [comment]
Looks like we stopped running the test suite in the other windows job at some point too 6ce9ba1ca3f7795cf12798ee1bc6d9d2656f8074

**Comment by gares** [comment]
maybe we can just fix the opam .dev package and use `{with-test}`

**Comment by Zimmi48** [comment]
> Looks like we stopped running the test suite in the other windows job at some point too [6ce9ba1](https://github.com/coq/coq/commit/6ce9ba1ca3f7795cf12798ee1bc6d9d2656f8074)

Yes. We should reintroduce it since we don't have such timeout limits on GitHub Actions.

**Comment by MSoegtropIMC** [comment]
I restarted Windows CI - should pass now.

**Comment by gares** [comment]
Great! We still miss an assignee here.

**Comment by silene** [comment]
@coqbot mege now

**Comment by silene** [comment]
@coqbot merge now
